kind = 'module'
title = 'Lagrangians of generalized convex programs'
module = 'Tdaf.Analysis.Convex.Optimization.Lagrangian'
namespace = 'Tdaf.ConvexAnalysis'

[[node]]
id = 'lagrangian'

[[node]]
id = 'lagrangian_eq_concaveConj'

[[node]]
id = 'iInf_lagrangian'

[[node]]
id = 'mem_kuhnTucker_iff_iInf_lagrangian'
