kind = 'module'
title = 'Normality of a dual pair of convex programs'
module = 'Tdaf.Analysis.Convex.Optimization.Normal'
namespace = 'Tdaf.ConvexAnalysis'

[[node]]
id = 'Normal'

[[node]]
id = 'supBifun'

[[node]]
id = 'domConcaveBifun'

[[node]]
id = 'ConcaveConsistent'

[[node]]
id = 'ConcaveNormal'

[[node]]
id = 'ConcaveStronglyConsistent'

[[node]]
id = 'clFn_infBifun_zero_eq_iSup_adjointBifun'

[[node]]
id = 'normal_iff_iSup_adjointBifun_eq'

[[node]]
id = 'clConcave_supBifun_adjointBifun_zero_eq'

[[node]]
id = 'concaveNormal_adjointBifun_iff'

[[node]]
id = 'normal_iff_concaveNormal_adjointBifun'

[[node]]
id = 'normal_of_kuhnTucker_nonempty'

[[node]]
id = 'mem_kuhnTucker_iff_adjointBifun_zero_eq_iSup'

[[node]]
id = 'kuhnTucker_eq_setOf_isMax'

[[node]]
id = 'StronglyConsistent.normal'

[[node]]
id = 'normal_of_concaveStronglyConsistent_adjointBifun'

[[node]]
id = 'normal_of_exists_setOf_le'

[[node]]
id = 'ConcaveKuhnTucker'

[[node]]
id = 'liminf_infBifun_eq_iSup_adjointBifun'

[[node]]
id = 'mem_concaveKuhnTucker_adjointBifun_iff_mem_argmin'

[[node]]
id = 'exists_infBifun_eq_of_concaveStronglyConsistent'
