/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Tdaf.Analysis.Convex.Polyhedral.Function
import Tdaf.Analysis.Convex.Polyhedral.Recession
import Tdaf.Analysis.Convex.Recession.Closedness
import Tdaf.Analysis.Convex.Recession.Conjugate
import Tdaf.Analysis.Convex.Subgradient.Approx
import Tdaf.Analysis.Convex.Subgradient.Calculus
import Tdaf.Analysis.Convex.Subgradient.Existence

/-!
# The minimum of a convex function

Rockafellar's §27. The unconstrained minimum of a convex function, its duality with `f*` at the
origin, existence and well-posedness under a recession hypothesis, minimisation over a closed
convex set, and the optimality condition `0 ∈ ∂h x + N_C(x)`.

## Main definitions

* `argmin f` — Rockafellar's *minimum set* `{x | ∀ z, f x ≤ f z}`.

## Main results

* `mem_argmin_iff_zero_mem_subgradient` — `x` minimises `f` exactly when `0 ∈ ∂f x`. This is true
  by the definition of a subgradient, and it is why §23 is the engine of §27.
* `conj_zero_eq_neg_iInf`, `iInf_eq_neg_conj_zero` — **Theorem 27.1(a)**: `inf f = -f*(0)`, with no
  hypothesis whatsoever, and `zero_mem_dom_conj_iff` for "bounded below ⟺ `0 ∈ dom f*`".
* `argmin_eq_subgradient_conj_zero` — **Theorem 27.1(b)**: the minimum set of `f` is `∂f*(0)`.
* `le_of_mem_subgradient_of_neg_mem_normalCone` — **Theorem 27.4**, sufficiency.
* `exists_mem_subgradient_neg_mem_normalCone` — **Theorem 27.4**, necessity, against `IsExactSum`.
* `argmin_nonempty_of_recessionConeFn_eq_zero`, `isCompact_argmin_of_recessionConeFn_eq_zero`,
  `exists_pos_forall_exists_mem_argmin_dist_lt` — **Theorem 27.2**: a closed proper convex function
  with no direction of recession attains its infimum, on a nonempty compact set, and does so in a
  well-posed way.
* `tendsto_infDist_argmin`, `isBounded_range_of_tendsto_iInf`, `mem_argmin_of_mapClusterPt` —
  **Corollary 27.2.1**; `tendsto_of_argmin_eq_singleton` is **Corollary 27.2.2**.
* `exists_forall_le_of_recessionConeFn_inter_eq_zero` — **Theorem 27.3**, the non-polyhedral case,
  with `recessionConeFn_add_indicatorFn` for the recession calculus behind it and
  `exists_forall_le_of_forall_le_zero` for **Corollary 27.3.3**.
* `exists_forall_le_of_inter_subset_constancySpace_inter_linealitySpace` — **Theorem 27.3** in the
  general form: the common recession cone need only consist of directions of constancy of `h` that
  are directions of linearity of `C`.
* `exists_forall_le_of_polyhedral_of_inter_subset_constancySpace` — **Theorem 27.3**, the
  polyhedral refinement: for polyhedral `C` the linearity requirement drops.
  `argmin_nonempty_of_recessionConeFn_subset_constancySpace` is its unconstrained case, and
  `exists_linearProj` is the projection that both run on.
* `argmin_nonempty_of_polyhedralFn` — a polyhedral convex function bounded below attains its
  infimum; `exists_forall_le_of_polyhedralFn_of_polyhedral` is the same statement relative to a
  polyhedral convex set, **Corollary 27.3.2**.
* `recessionCone_setOf_le_eq_polarCone_dom_conj`, `recessionCone_argmin_eq_polarCone_dom_conj` —
  **Theorem 27.1(f)**: every nonempty level set, and the minimum set, has the same recession cone,
  the polar of the cone generated by `dom f*`.
* `argmin_nonempty_and_isBounded_iff_zero_mem_interior_dom_conj` — **Theorem 27.1(d)**, with
  `zero_mem_interior_dom_conj_iff_recessionConeFn_eq_zero` for its second sentence.
* `supportFn_setOf_le`, `supportFn_argmin` — **Theorem 27.1(g)**, the two sentences.
* `iInf_supportFn_setOf_le` — **Theorem 27.1(h)**, with `epsSubgradient_conj_zero` identifying
  the level sets of `f` above `inf f` with the ε-subdifferentials of `f*` at the origin.
* `iInf_ne_bot_and_argmin_eq_empty_iff` — **Theorem 27.1(c)**: the infimum is finite but
  unattained exactly when `f*(0)` is finite and `f*'(0; ·)` is `−∞` somewhere.
* `exists_setOf_le_nonempty_and_isBounded_iff_zero_mem_interior_dom_conj`,
  `argmin_nonempty_and_isBounded_iff_exists_setOf_le` — Theorem 27.1(d) and (f) combined, in the
  form **Theorem 30.4** conditions (g) and (i) take: *some* level set is non-empty and bounded
  exactly when the minimum set is, and both say `0 ∈ int (dom f*)`.

## Design notes

**`argmin` rather than `IsMinOn f Set.univ`.** The minimum set is quantified over in almost every
statement of §27, and `{x | ∀ z, f x ≤ f z}` unfolds to exactly the subgradient inequality at
`y = 0`. `mem_argmin_iff_isMinOn` is the bridge to Mathlib's predicate.

**Theorem 27.1(a) needs no hypotheses.** `f*(0) = ⨆ x, (0 - f x) = -(⨅ x, f x)`, and Rockafellar's
standing "closed proper convex" is only there because the rest of Theorem 27.1 needs it.

**Theorem 27.4 is Theorem 23.8 plus `∂δ(· | C) = N_C`.** The sufficiency half is stated separately
and needs nothing at all: the subgradient inequality and the normality inequality simply add.
Necessity is stated against `IsExactSum B h (indicatorFn C)`, so Rockafellar's `ri` hypothesis and
his polyhedral hypothesis both instantiate it — see `Duality/Relint.lean`.

**The well-posedness clause of Theorem 27.2 avoids the nested-compactness argument.** Rockafellar
intersects a nest of closed bounded sets; a single application of the extreme value theorem to
`{f ≤ inf f + 1} \ (M + ε·int B)` gives the `δ` directly. The two corollaries are then read off
`tendsto_infDist_argmin`, which is stated for an arbitrary filter rather than for sequences.

**§27's minimising results are stated for arbitrary filters where Rockafellar uses sequences.**
Only `isBounded_range_of_tendsto_iInf`, whose conclusion is about the range of a sequence, is
restricted to `ℕ` and `atTop`.

## What is not here

**Theorem 27.1(e).** It says that `∂f*(0)` is a singleton, which lives in `E**` and so needs a
reflexive pairing to be stated at all. Both sentences of (i) are in `Duality/Level.lean`, as
`zero_mem_closure_dom_conj_iff` and `zero_notMem_closure_dom_conj_iff`, next to the Corollary
13.3.4 they specialise.

**Theorem 27.1(c) mentions only one of the book's two finiteness conditions.** Rockafellar asks
that `f*(0)` be finite, i.e. `≠ ⊥` and `≠ ⊤`; for proper `f` the first half is automatic
(`conj_ne_bot`), and symmetrically `⨅ f ≠ ⊤` is automatic because `dom f ≠ ∅`. So on both sides of
the equivalence only one of the two bounds carries information, and `iInf_ne_top` records the one
that does not.

**Theorem 27.1(d) does not need Corollary 13.3.4**, contrary to Rockafellar's proof: Corollary
14.2.2 already says that every level set is bounded exactly when the origin is interior to
`dom f*`, and Theorem 27.2 turns that into existence of a minimiser. Neither does (g) need a
shifted-function API: Corollary 13.2.1 computes the closure of a generated function as a support
function directly, and the level set it produces is `{x | f**(x) - α ≤ 0}`.

**`supportFn_setOf_le` is a §13 statement living in §27.** It is Theorem 13.5 for `f - α`, and its
natural home is beside `supportFn_setOf_le_zero` in `Duality/Level.lean`; it is here because that
module sits below this one and because §27 is where level sets of `f` are the subject.

**Corollary 27.3.1.** Its statement could not be checked against the book, so nothing is claimed
under that number; the two statements the polyhedral refinement is known to yield —
`argmin_nonempty_of_recessionConeFn_subset_constancySpace` and, through it, the polyhedral half of
Corollary 27.3.3 for affine constraints — are what is here.

**The polyhedral refinement of Theorem 27.3 does not need Helly.** Rockafellar derives it from
Theorem 21.5, applied to `C` together with the level sets `lev_α h`; Theorem 21.5 is still not
formalised (see `Helly.lean`), and the refinement no longer waits for it. The directions of
constancy of `h` form a subspace, and `exists_linearProj` projects along it: `h` is unchanged, the
image of `C` is polyhedral, and the common recession cone collapses to `{0}`, which is the
hypothesis of the non-polyhedral case. Polyhedrality of `C` enters exactly once, through
`Polyhedral.recessionCone_image` — a linear map commutes with `0⁺` on a polyhedral set and, in
general, on no other kind.

Corollary 27.3.2 does not need the refinement either: the finitely generated description of a
polyhedral epigraph gives it directly, and `argmin_nonempty_of_polyhedralFn` cuts Rockafellar's
route through Corollary 27.3.1.

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §27 (Theorem 27.1(a),
  (b), (d), (f), (g), (h), Theorem 27.2 with Corollaries 27.2.1–27.2.2, Theorem 27.3 with
  Corollaries 27.3.2 and 27.3.3, Theorem 27.4). Theorem 27.3's general and polyhedral recession
  hypotheses are stated as the book's constancy/linearity conditions; the derivation is not the
  book's.
-/

open Set Pointwise

namespace Tdaf.ConvexAnalysis

/-! ### The minimum set -/

section Defs

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} {f : E → EReal} {x : E}

/-- The **minimum set** of `f`: the points where `f` attains its infimum. Rockafellar's
`lev_{inf f} f`. -/
def argmin (f : E → EReal) : Set E := {x | ∀ z, f x ≤ f z}

omit [AddCommGroup E] [Module ℝ E] in
theorem mem_argmin_iff : x ∈ argmin f ↔ ∀ z, f x ≤ f z := Iff.rfl

omit [AddCommGroup E] [Module ℝ E] in
theorem mem_argmin_iff_isMinOn : x ∈ argmin f ↔ IsMinOn f Set.univ x := by
  rw [isMinOn_univ_iff]
  exact Iff.rfl

omit [AddCommGroup E] [Module ℝ E] in
theorem mem_argmin_iff_le_iInf : x ∈ argmin f ↔ f x ≤ ⨅ z, f z := le_iInf_iff.symm

omit [AddCommGroup E] [Module ℝ E] in
/-- The infimum of `f` is its value at any minimiser. -/
theorem iInf_eq_of_mem_argmin {a : E} (ha : a ∈ argmin f) : (⨅ z, f z) = f a :=
  le_antisymm (iInf_le _ _) (mem_argmin_iff_le_iInf.1 ha)

omit [AddCommGroup E] [Module ℝ E] in
/-- Rockafellar's `lev_{inf f} f`: once the infimum is attained and finite, the minimum set is
literally a level set of `f`. -/
theorem argmin_eq_setOf_le {a : E} (ha : a ∈ argmin f) {μ : ℝ} (hμ : f a = (μ : EReal)) :
    argmin f = {z : E | f z ≤ (μ : EReal)} := by
  ext z
  constructor
  · intro hz
    rw [← hμ]
    exact hz a
  · intro hz w
    rw [Set.mem_ofPred_eq, ← hμ] at hz
    exact le_trans hz (ha w)

/-- Minimising is `0 ∈ ∂f x`, by the definition of a subgradient. -/
theorem mem_argmin_iff_zero_mem_subgradient (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (f : E → EReal) (x : E) :
    x ∈ argmin f ↔ (0 : F) ∈ subgradient B f x := by
  constructor
  · intro h z; simpa using h z
  · intro h z; simpa using h z

/-- **Rockafellar, Theorem 27.1(a)**: `f*(0) = -inf f`. No hypothesis at all. -/
theorem conj_zero_eq_neg_iInf (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (f : E → EReal) :
    conj B f 0 = -(⨅ x, f x) := by
  rw [EReal.neg_iInf]
  refine iSup_congr fun x => ?_
  simp

/-- **Rockafellar, Theorem 27.1(a)**, in Rockafellar's own orientation. -/
theorem iInf_eq_neg_conj_zero (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (f : E → EReal) :
    (⨅ x, f x) = -(conj B f 0) := by
  rw [conj_zero_eq_neg_iInf, neg_neg]

/-- **Rockafellar, Theorem 27.1(a)**, second sentence: `f` is bounded below exactly when `f*` is
finite at the origin. -/
theorem zero_mem_dom_conj_iff (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (f : E → EReal) :
    (0 : F) ∈ dom (conj B f) ↔ (⊥ : EReal) < ⨅ x, f x := by
  rw [mem_dom, conj_zero_eq_neg_iInf, lt_top_iff_ne_top, bot_lt_iff_ne_bot, ne_eq, ne_eq,
    _root_.EReal.neg_eq_top_iff]

/-- The minimum set is convex. -/
theorem convex_argmin (hf : ConvexFn f) : Convex ℝ (argmin f) := by
  rcases eq_or_ne (argmin f) ∅ with hE | hE
  · rw [hE]; exact convex_empty
  · obtain ⟨a, ha⟩ := Set.nonempty_iff_ne_empty.2 hE
    have hset : argmin f = {z : E | f z ≤ f a} := by
      ext z
      exact ⟨fun hz => hz a, fun hz w => le_trans hz (ha w)⟩
    rw [hset]
    exact hf.convex_le _

end Defs

/-! ### Theorem 27.1(b) -/

section FenchelMoreau

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  [TopologicalSpace E] [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [LocallyConvexSpace ℝ E]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} [IsCompatiblePairing B] {f : E → EReal}

/-- **Rockafellar, Theorem 27.1(b)**: the minimum set of a closed convex function is `∂f*(0)`.
In particular the infimum is attained exactly when `f*` is subdifferentiable at the origin.

The proof is Theorem 23.5 (`y ∈ ∂g x` is Fenchel's inequality with equality) applied to `g = f*`
at the origin, where Fenchel–Moreau turns `f**` back into `f` and the pairing term vanishes. -/
theorem argmin_eq_subgradient_conj_zero (hf : ConvexFn f) (hc : ClosedFn f) :
    argmin f = subgradient B.flip (conj B f) 0 := by
  ext x
  have hbi : conj B.flip (conj B f) x = f x := congrFun (biconj_eq_self hf hc) x
  have hpair : ((B.flip 0 x : ℝ) : EReal) = 0 := by simp
  rw [mem_argmin_iff_le_iInf, iInf_eq_neg_conj_zero B, mem_subgradient_iff_add_conj_le, hbi,
    hpair, ← _root_.EReal.le_sub_iff_add_le (.inr (by simp)) (.inr (by simp)), zero_sub,
    _root_.EReal.le_neg]

/-- **Rockafellar, Theorem 27.1(f)**: every nonempty level set of a closed proper convex function
has the same recession cone, namely the polar of the effective domain of the conjugate.

Theorem 8.7 identifies all the level-set recession cones with the recession cone of `f`, and
Theorem 14.2 identifies that with the polar of `dom f*`. -/
theorem recessionCone_setOf_le_eq_polarCone_dom_conj (hf : ConvexFn f) (hc : ClosedFn f)
    (hp : Proper f) {α : ℝ} (hne : {z : E | f z ≤ (α : EReal)}.Nonempty) :
    recessionCone {z : E | f z ≤ (α : EReal)} = polarCone B.flip (dom (conj B f)) := by
  rw [recessionCone_setOf_le hf (ClosedProperConvexFn.isClosed_epi ⟨hf, hc, hp⟩) hne,
    recessionConeFn_eq_polarCone_dom_conj (B := B) hf hc hp]

/-- **Rockafellar, Theorem 27.1(f)**, for the minimum set: when the infimum is attained the minimum
set is a level set, so it too has the polar of `dom f*` as its recession cone. -/
theorem recessionCone_argmin_eq_polarCone_dom_conj (hf : ConvexFn f) (hc : ClosedFn f)
    (hp : Proper f) {a : E} (ha : a ∈ argmin f) {μ : ℝ} (hμ : f a = (μ : EReal)) :
    recessionCone (argmin f) = polarCone B.flip (dom (conj B f)) := by
  rw [argmin_eq_setOf_le ha hμ]
  exact recessionCone_setOf_le_eq_polarCone_dom_conj hf hc hp ⟨a, le_of_eq hμ⟩

end FenchelMoreau

/-! ### Theorem 27.4: minimising over a convex set -/

section Optimality

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} {h : E → EReal} {C : Set E} {x : E} {y : F}

/-- **Rockafellar, Theorem 27.4**, sufficiency: if some `y ∈ ∂h x` has `-y` normal to `C` at `x`,
then `h` attains its infimum over `C` at `x`.

No hypothesis is needed: the subgradient inequality `h x + ⟨z - x, y⟩ ≤ h z` and the normality
inequality `⟨z - x, -y⟩ ≤ 0` simply add. -/
theorem le_of_mem_subgradient_of_neg_mem_normalCone (hy : y ∈ subgradient B h x)
    (hn : -y ∈ normalCone B C x) {z : E} (hz : z ∈ C) : h x ≤ h z := by
  have h2 : B (z - x) (-y) ≤ 0 := hn z hz
  rw [map_neg, neg_nonpos] at h2
  calc h x ≤ h x + ((B (z - x) y : ℝ) : EReal) :=
        le_add_of_nonneg_right (by exact_mod_cast h2)
    _ ≤ h z := hy z

omit [AddCommGroup E] [Module ℝ E] in
/-- Minimising `h` over `C` is minimising `h + δ(· | C)` over the whole space. -/
theorem mem_argmin_add_indicatorFn_of_forall (hp : Proper h) (hx : x ∈ C)
    (hmin : ∀ z ∈ C, h x ≤ h z) : x ∈ argmin (h + indicatorFn C) := by
  intro z
  by_cases hzC : z ∈ C
  · simpa [indicatorFn_of_mem hx, indicatorFn_of_mem hzC] using hmin z hzC
  · have hrhs : (h + indicatorFn C) z = ⊤ := by
      rw [Pi.add_apply, indicatorFn_of_notMem hzC]
      exact _root_.EReal.add_top_of_ne_bot (hp.ne_bot z)
    rw [hrhs]
    exact le_top

omit [AddCommGroup E] [Module ℝ E] in
/-- The converse of `mem_argmin_add_indicatorFn_of_forall`: a minimiser of `h + δ(· | C)` that lies
in `C` minimises `h` over `C`. -/
theorem forall_le_of_mem_argmin_add_indicatorFn (hx : x ∈ argmin (h + indicatorFn C))
    (hxC : x ∈ C) {z : E} (hz : z ∈ C) : h x ≤ h z := by
  have hle := hx z
  rwa [Pi.add_apply, Pi.add_apply, indicatorFn_of_mem hxC, indicatorFn_of_mem hz, add_zero,
    add_zero] at hle

/-- **Rockafellar, Theorem 27.4**, necessity: when the sum `h + δ(· | C)` is exact, every point
where `h` attains its infimum over `C` carries a subgradient `y ∈ ∂h x` with `-y` normal to `C`.

Rockafellar's two hypotheses — `ri (dom h)` meets `ri C`, and `C` polyhedral with `ri (dom h)`
meeting `C` — are two ways of supplying `IsExactSum B h (indicatorFn C)`. -/
theorem exists_mem_subgradient_neg_mem_normalCone (hex : IsExactSum B h (indicatorFn C))
    (hx : x ∈ C) (hmin : ∀ z ∈ C, h x ≤ h z) :
    ∃ y ∈ subgradient B h x, -y ∈ normalCone B C x := by
  have hzero : (0 : F) ∈ subgradient B (h + indicatorFn C) x :=
    (mem_argmin_iff_zero_mem_subgradient B _ x).1
      (mem_argmin_add_indicatorFn_of_forall hex.proper_left hx hmin)
  rw [hex.subgradient_add x, subgradient_indicatorFn hx] at hzero
  obtain ⟨y, hy, n, hn, hsum⟩ := hzero
  have hs : y + n = 0 := hsum
  have hny : -y = n := by
    rw [eq_comm, eq_neg_iff_add_eq_zero, add_comm]
    exact hs
  exact ⟨y, hy, hny ▸ hn⟩

end Optimality

/-! ### Theorem 27.2: existence of a minimiser -/

section Existence

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  {f : E → EReal}

/-- The level set that carries the argument of Theorem 27.2: nonempty, closed, convex, and — when
`f` has no direction of recession — compact. -/
private theorem isCompact_setOf_le (hf : ConvexFn f) (hc : ClosedFn f) (hp : Proper f)
    (hrec : recessionConeFn f = {0}) {α : ℝ} (hne : {z : E | f z ≤ (α : EReal)}.Nonempty) :
    IsCompact {z : E | f z ≤ (α : EReal)} := by
  have hlsc : LowerSemicontinuous f := (closedFn_iff_lowerSemicontinuous hp.ne_bot).1 hc
  have hepi : IsClosed (epi f) := lowerSemicontinuous_iff_isClosed_epi.1 hlsc
  refine (isCompact_iff_recessionCone_eq_zero (hf.convex_le _)
    (lowerSemicontinuous_iff_isClosed_le.1 hlsc α) hne).2 ?_
  rw [recessionCone_setOf_le hf hepi hne]
  exact hrec

/-- **Rockafellar, Theorem 27.2**: a closed proper convex function with no direction of recession
attains its infimum.

The level set at any value of `f` is nonempty, closed, convex and — by Theorem 8.7 and Theorem 8.4
— compact, so lower semicontinuity attains a minimum on it; and off that level set `f` is larger
than on it. -/
theorem argmin_nonempty_of_recessionConeFn_eq_zero (hf : ConvexFn f) (hc : ClosedFn f)
    (hp : Proper f) (hrec : recessionConeFn f = {0}) : (argmin f).Nonempty := by
  have hlsc : LowerSemicontinuous f := (closedFn_iff_lowerSemicontinuous hp.ne_bot).1 hc
  obtain ⟨x₀, hx₀⟩ := hp.dom_nonempty
  obtain ⟨α, hα⟩ := EReal.exists_coe_of_ne_bot_of_lt_top (hp.ne_bot x₀) (mem_dom.1 hx₀)
  set L : Set E := {z : E | f z ≤ (α : EReal)} with hL
  have hLne : L.Nonempty := ⟨x₀, le_of_eq hα⟩
  obtain ⟨a, haL, hamin⟩ := LowerSemicontinuousOn.exists_isMinOn hLne
    (isCompact_setOf_le hf hc hp hrec hLne) (hlsc.lowerSemicontinuousOn L)
  refine ⟨a, fun z => ?_⟩
  by_cases hzL : z ∈ L
  · exact isMinOn_iff.1 hamin z hzL
  · exact le_trans haL (le_of_lt (not_le.1 hzL))

/-- **Rockafellar, Theorem 27.2**, second assertion: the minimum set is then a nonempty compact
convex set. -/
theorem isCompact_argmin_of_recessionConeFn_eq_zero (hf : ConvexFn f) (hc : ClosedFn f)
    (hp : Proper f) (hrec : recessionConeFn f = {0}) : IsCompact (argmin f) := by
  obtain ⟨a, ha⟩ := argmin_nonempty_of_recessionConeFn_eq_zero hf hc hp hrec
  obtain ⟨μ, hμ⟩ := EReal.exists_coe_of_ne_bot_of_lt_top (hp.ne_bot a)
    (lt_of_le_of_lt (ha _) (mem_dom.1 hp.dom_nonempty.choose_spec))
  have hset : argmin f = {z : E | f z ≤ (μ : EReal)} := by
    ext z
    constructor
    · intro hz; exact le_trans (hz a) (le_of_eq hμ)
    · intro hz w; exact le_trans (hμ ▸ hz) (ha w)
  rw [hset]
  exact isCompact_setOf_le hf hc hp hrec ⟨a, le_of_eq hμ⟩

/-- Under the hypotheses of Theorem 27.2 the infimum is a real number. -/
theorem exists_iInf_eq_coe (hf : ConvexFn f) (hc : ClosedFn f) (hp : Proper f)
    (hrec : recessionConeFn f = {0}) : ∃ μ : ℝ, (⨅ z, f z) = (μ : EReal) := by
  obtain ⟨a, ha⟩ := argmin_nonempty_of_recessionConeFn_eq_zero hf hc hp hrec
  obtain ⟨x₀, hx₀⟩ := hp.dom_nonempty
  obtain ⟨μ, hμ⟩ := EReal.exists_coe_of_ne_bot_of_lt_top (hp.ne_bot a)
    (lt_of_le_of_lt (ha x₀) (mem_dom.1 hx₀))
  exact ⟨μ, by rw [iInf_eq_of_mem_argmin ha, hμ]⟩

/-- **Rockafellar, Theorem 27.2**, third assertion: the minimum is *well posed*. For every `ε > 0`
there is a `δ > 0` such that the whole level set `{x | f x ≤ inf f + δ}` lies within `ε` of the
minimum set.

Rockafellar runs a nested-compactness argument; one application of the extreme value theorem is
enough. If the compact set `{f ≤ inf f + 1} \ (M + ε·int B)` is empty then `δ = 1` works. Otherwise
`f` attains a minimum on it at some `b`, and `b` is not a minimiser of `f`, so `inf f < f b`; any
`δ` with `inf f + δ < f b` will do. -/
theorem exists_pos_forall_exists_mem_argmin_dist_lt (hf : ConvexFn f) (hc : ClosedFn f)
    (hp : Proper f) (hrec : recessionConeFn f = {0}) {ε : ℝ} (hε : 0 < ε) :
    ∃ δ : ℝ, 0 < δ ∧ ∀ x, f x ≤ (⨅ z, f z) + (δ : EReal) → ∃ z ∈ argmin f, dist x z < ε := by
  have hlsc : LowerSemicontinuous f := (closedFn_iff_lowerSemicontinuous hp.ne_bot).1 hc
  obtain ⟨a, ha⟩ := argmin_nonempty_of_recessionConeFn_eq_zero hf hc hp hrec
  obtain ⟨x₀, hx₀⟩ := hp.dom_nonempty
  obtain ⟨μ, hμ⟩ := EReal.exists_coe_of_ne_bot_of_lt_top (hp.ne_bot a)
    (lt_of_le_of_lt (ha x₀) (mem_dom.1 hx₀))
  have hinf : (⨅ z, f z) = (μ : EReal) := by rw [iInf_eq_of_mem_argmin ha, hμ]
  set U : Set E := ⋃ w ∈ argmin f, Metric.ball w ε with hUdef
  have hUopen : IsOpen U := isOpen_biUnion fun w _ => Metric.isOpen_ball
  have hmemU : ∀ x : E, x ∈ U ↔ ∃ z ∈ argmin f, dist x z < ε := by
    intro x
    simp [hUdef, Metric.mem_ball]
  have haL : a ∈ {z : E | f z ≤ ((μ + 1 : ℝ) : EReal)} := by
    rw [Set.mem_ofPred_eq, hμ]
    exact_mod_cast (by linarith : μ ≤ μ + 1)
  have hLcomp : IsCompact {z : E | f z ≤ ((μ + 1 : ℝ) : EReal)} :=
    isCompact_setOf_le hf hc hp hrec ⟨a, haL⟩
  set K : Set E := {z : E | f z ≤ ((μ + 1 : ℝ) : EReal)} \ U with hKdef
  have hKcomp : IsCompact K := by
    rw [hKdef, Set.sdiff_eq]
    exact hLcomp.inter_right (isClosed_compl_iff.2 hUopen)
  have hfinish : ∀ d : ℝ, 0 < d → d ≤ 1 →
      (∀ x : E, x ∈ K → ¬ f x ≤ ((μ + d : ℝ) : EReal)) →
      ∃ δ : ℝ, 0 < δ ∧ ∀ x, f x ≤ (⨅ z, f z) + (δ : EReal) → ∃ z ∈ argmin f, dist x z < ε := by
    intro d hd0 hd1 hout
    refine ⟨d, hd0, fun x hx => ?_⟩
    rw [hinf, ← _root_.EReal.coe_add] at hx
    have hxL : x ∈ {z : E | f z ≤ ((μ + 1 : ℝ) : EReal)} :=
      le_trans hx (by exact_mod_cast (by linarith : μ + d ≤ μ + 1))
    refine (hmemU x).1 ?_
    by_contra hxU
    exact hout x ⟨hxL, hxU⟩ hx
  rcases Set.eq_empty_or_nonempty K with hKe | hKne
  · exact hfinish 1 one_pos le_rfl fun x hxK => absurd hxK (by rw [hKe]; exact Set.notMem_empty x)
  · obtain ⟨b, hbK, hbmin⟩ :=
      LowerSemicontinuousOn.exists_isMinOn hKne hKcomp (hlsc.lowerSemicontinuousOn K)
    have hbnot : b ∉ argmin f := fun hb => hbK.2 ((hmemU b).2 ⟨b, hb, by simpa using hε⟩)
    obtain ⟨w, hw⟩ : ∃ w, f w < f b := by
      by_contra hcon
      push Not at hcon
      exact hbnot fun z => hcon z
    have hμb : (μ : EReal) < f b := lt_of_le_of_lt (by rw [← hμ]; exact ha w) hw
    obtain ⟨r, hr⟩ := EReal.exists_coe_of_ne_bot_of_lt_top (hp.ne_bot b)
      (lt_of_le_of_lt hbK.1 (_root_.EReal.coe_lt_top (μ + 1)))
    have hμr : μ < r := by
      rw [hr] at hμb
      exact_mod_cast hμb
    refine hfinish (min 1 ((r - μ) / 2)) (lt_min one_pos (by linarith)) (min_le_left _ _) ?_
    intro x hxK hxle
    have hble : ((r : ℝ) : EReal) ≤ ((μ + min 1 ((r - μ) / 2) : ℝ) : EReal) := by
      rw [← hr]
      exact le_trans (isMinOn_iff.1 hbmin x hxK) hxle
    rw [_root_.EReal.coe_le_coe_iff] at hble
    have hhalf : min 1 ((r - μ) / 2) ≤ (r - μ) / 2 := min_le_right _ _
    linarith

/-- **Rockafellar, Corollary 27.2.1**, the substance: along any minimising net the distance to the
minimum set tends to `0`. Stated for an arbitrary filter — `atTop` on `ℕ` is Rockafellar's case. -/
theorem tendsto_infDist_argmin (hf : ConvexFn f) (hc : ClosedFn f) (hp : Proper f)
    (hrec : recessionConeFn f = {0}) {ι : Type*} {l : Filter ι} {u : ι → E}
    (hu : Filter.Tendsto (fun i => f (u i)) l (nhds (⨅ z, f z))) :
    Filter.Tendsto (fun i => Metric.infDist (u i) (argmin f)) l (nhds 0) := by
  obtain ⟨μ, hμ⟩ := exists_iInf_eq_coe hf hc hp hrec
  refine Metric.tendsto_nhds.2 fun ε hε => ?_
  obtain ⟨δ, hδ, hmain⟩ := exists_pos_forall_exists_mem_argmin_dist_lt hf hc hp hrec hε
  have hlt : (⨅ z, f z) < (⨅ z, f z) + (δ : EReal) := by
    rw [hμ, ← _root_.EReal.coe_add]
    exact_mod_cast (by linarith : μ < μ + δ)
  filter_upwards [hu (Iio_mem_nhds hlt)] with i hi
  obtain ⟨z, hz, hdz⟩ := hmain (u i) (le_of_lt hi)
  rw [Real.dist_eq, sub_zero, abs_of_nonneg Metric.infDist_nonneg]
  exact lt_of_le_of_lt (Metric.infDist_le_dist_of_mem hz) hdz

/-- **Rockafellar, Corollary 27.2.1**, second assertion: every cluster point of a minimising net
belongs to the minimum set. -/
theorem mem_argmin_of_mapClusterPt (hf : ConvexFn f) (hc : ClosedFn f) (hp : Proper f)
    (hrec : recessionConeFn f = {0}) {ι : Type*} {l : Filter ι} {u : ι → E}
    (hu : Filter.Tendsto (fun i => f (u i)) l (nhds (⨅ z, f z))) {x : E}
    (hx : MapClusterPt x l u) : x ∈ argmin f := by
  obtain ⟨μ, hμ⟩ := exists_iInf_eq_coe hf hc hp hrec
  have hMcomp : IsCompact (argmin f) := isCompact_argmin_of_recessionConeFn_eq_zero hf hc hp hrec
  have hMne : (argmin f).Nonempty := argmin_nonempty_of_recessionConeFn_eq_zero hf hc hp hrec
  refine (hMcomp.isClosed.mem_iff_infDist_zero hMne).2 ?_
  have key : ∀ ε : ℝ, 0 < ε → Metric.infDist x (argmin f) < ε := by
    intro ε hε
    obtain ⟨δ, hδ, hmain⟩ :=
      exists_pos_forall_exists_mem_argmin_dist_lt hf hc hp hrec (half_pos hε)
    have hlt : (⨅ z, f z) < (⨅ z, f z) + (δ : EReal) := by
      rw [hμ, ← _root_.EReal.coe_add]
      exact_mod_cast (by linarith : μ < μ + δ)
    have hV : {z : E | f z < (⨅ z, f z) + (δ : EReal)} ∈ Filter.map u l :=
      hu (Iio_mem_nhds hlt)
    obtain ⟨y, hy1, hy2⟩ :=
      clusterPt_iff_nonempty.1 hx (Metric.ball_mem_nhds x (half_pos hε)) hV
    obtain ⟨z, hz, hdz⟩ := hmain y (le_of_lt hy2)
    have hxy : dist x y < ε / 2 := by rwa [Metric.mem_ball, dist_comm] at hy1
    have hyz : Metric.infDist y (argmin f) ≤ dist y z := Metric.infDist_le_dist_of_mem hz
    calc Metric.infDist x (argmin f) ≤ Metric.infDist y (argmin f) + dist x y :=
          Metric.infDist_le_infDist_add_dist
      _ < ε := by linarith
  rcases lt_or_ge 0 (Metric.infDist x (argmin f)) with hpos | hnonpos
  · exact absurd (key _ hpos) (lt_irrefl _)
  · exact le_antisymm hnonpos Metric.infDist_nonneg

/-- **Rockafellar, Corollary 27.2.1**, first assertion: a minimising sequence is bounded. -/
theorem isBounded_range_of_tendsto_iInf (hf : ConvexFn f) (hc : ClosedFn f) (hp : Proper f)
    (hrec : recessionConeFn f = {0}) {u : ℕ → E}
    (hu : Filter.Tendsto (fun i => f (u i)) Filter.atTop (nhds (⨅ z, f z))) :
    Bornology.IsBounded (Set.range u) := by
  have hMcomp : IsCompact (argmin f) := isCompact_argmin_of_recessionConeFn_eq_zero hf hc hp hrec
  have hMne : (argmin f).Nonempty := argmin_nonempty_of_recessionConeFn_eq_zero hf hc hp hrec
  obtain ⟨R, hR⟩ := hMcomp.isBounded.subset_closedBall (0 : E)
  obtain ⟨N, hN⟩ := Filter.eventually_atTop.1
    (Metric.tendsto_nhds.1 (tendsto_infDist_argmin hf hc hp hrec hu) 1 one_pos)
  have hsub : ∀ i, N ≤ i → u i ∈ Metric.closedBall (0 : E) (R + 1) := by
    intro i hi
    obtain ⟨w, hw, hdw⟩ := hMcomp.exists_infDist_eq_dist hMne (u i)
    have h1 : Metric.infDist (u i) (argmin f) < 1 := by
      have h2 := hN i hi
      rwa [Real.dist_eq, sub_zero, abs_of_nonneg Metric.infDist_nonneg] at h2
    have h3 : dist (u i) w < 1 := by rwa [← hdw]
    have h4 : dist w 0 ≤ R := Metric.mem_closedBall.1 (hR hw)
    rw [Metric.mem_closedBall]
    calc dist (u i) 0 ≤ dist (u i) w + dist w 0 := dist_triangle _ _ _
      _ ≤ R + 1 := by linarith
  have hsplit : Set.range u ⊆ (u '' Set.Iio N) ∪ Metric.closedBall (0 : E) (R + 1) := by
    rintro _ ⟨i, rfl⟩
    rcases lt_or_ge i N with hi | hi
    · exact Or.inl ⟨i, hi, rfl⟩
    · exact Or.inr (hsub i hi)
  exact Bornology.IsBounded.subset
    (((Set.finite_Iio N).image u).isBounded.union Metric.isBounded_closedBall) hsplit

/-- **Rockafellar, Corollary 27.2.2**: if a closed proper convex function attains its infimum at a
unique point, every minimising net converges to that point. No recession hypothesis is needed: a
one-point minimum set is a level set, so Theorem 8.7 forces the recession cone to be `{0}`. -/
theorem tendsto_of_argmin_eq_singleton (hf : ConvexFn f) (hc : ClosedFn f) (hp : Proper f)
    {a : E} (hM : argmin f = {a}) {ι : Type*} {l : Filter ι} {u : ι → E}
    (hu : Filter.Tendsto (fun i => f (u i)) l (nhds (⨅ z, f z))) :
    Filter.Tendsto u l (nhds a) := by
  have haM : a ∈ argmin f := by rw [hM]; exact Set.mem_singleton a
  obtain ⟨x₀, hx₀⟩ := hp.dom_nonempty
  obtain ⟨μ, hμ⟩ := EReal.exists_coe_of_ne_bot_of_lt_top (hp.ne_bot a)
    (lt_of_le_of_lt (haM x₀) (mem_dom.1 hx₀))
  have hlsc : LowerSemicontinuous f := (closedFn_iff_lowerSemicontinuous hp.ne_bot).1 hc
  have hne : {z : E | f z ≤ (μ : EReal)}.Nonempty := ⟨a, le_of_eq hμ⟩
  have hrec : recessionConeFn f = {0} := by
    rw [← recessionCone_setOf_le hf (lowerSemicontinuous_iff_isClosed_epi.1 hlsc) hne,
      ← argmin_eq_setOf_le haM hμ, hM, recessionCone_singleton]
  have hlim := tendsto_infDist_argmin hf hc hp hrec hu
  rw [hM] at hlim
  rw [tendsto_iff_dist_tendsto_zero]
  simpa only [Metric.infDist_singleton] using hlim

end Existence

/-! ### Theorem 27.3: minimising over a closed convex set -/

section Constrained

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  {h : E → EReal} {C : Set E}

omit [FiniteDimensional ℝ E] in
/-- The indicator of a nonempty closed convex set is a closed proper convex function. -/
theorem closedProperConvexFn_indicatorFn (hC : Convex ℝ C) (hCc : IsClosed C) (hCne : C.Nonempty) :
    ClosedProperConvexFn (indicatorFn C) :=
  ⟨convexFn_indicatorFn.2 hC, closedFn_indicatorFn hCc,
    ⟨by rw [dom_indicatorFn]; exact hCne, indicatorFn_ne_bot C⟩⟩

omit [FiniteDimensional ℝ E] in
/-- The directions of recession of `h + δ(· | C)` are exactly the directions of recession common to
`h` and to `C`. This is Theorem 9.3's recession formula read against an indicator: `δ(· | C)0⁺` is
`δ(· | 0⁺C)`, which is `0` on `0⁺C` and `⊤` off it. -/
theorem recessionConeFn_add_indicatorFn (hh : ClosedProperConvexFn h) (hC : Convex ℝ C)
    (hCc : IsClosed C) (hCne : C.Nonempty) (hne : (dom (h + indicatorFn C)).Nonempty) :
    recessionConeFn (h + indicatorFn C) = recessionConeFn h ∩ recessionCone C := by
  have hsum := recessionFn_add hh (closedProperConvexFn_indicatorFn hC hCc hCne) hne
  ext y
  rw [Set.mem_inter_iff, mem_recessionConeFn, mem_recessionConeFn, hsum, Pi.add_apply,
    recessionFn_indicatorFn hCne]
  by_cases hy : y ∈ recessionCone C
  · rw [indicatorFn_of_mem hy, add_zero]
    simp [hy]
  · rw [indicatorFn_of_notMem hy,
      _root_.EReal.add_top_of_ne_bot (recessionFn_ne_bot hh.proper y)]
    simp [hy]

/-- **Rockafellar, Theorem 27.3**, the non-polyhedral case: a closed proper convex `h` attains its
infimum over a nonempty closed convex set `C` as soon as `h` and `C` have no direction of recession
in common.

The book's proof: `h + δ(· | C)` is closed proper convex whenever it is not identically `+∞`, and
its directions of recession are the common ones, so Theorem 27.2 applies. The degenerate case
`dom h ∩ C = ∅` is genuinely degenerate — `h` is then `+∞` throughout `C` and every point of `C`
minimises. -/
theorem exists_forall_le_of_recessionConeFn_inter_eq_zero (hh : ClosedProperConvexFn h)
    (hC : Convex ℝ C) (hCc : IsClosed C) (hCne : C.Nonempty)
    (hrec : recessionConeFn h ∩ recessionCone C = {0}) :
    ∃ x ∈ C, ∀ z ∈ C, h x ≤ h z := by
  by_cases hne : (dom (h + indicatorFn C)).Nonempty
  · have hsum : ClosedProperConvexFn (h + indicatorFn C) :=
      hh.add (closedProperConvexFn_indicatorFn hC hCc hCne) hne
    obtain ⟨x, hx⟩ := argmin_nonempty_of_recessionConeFn_eq_zero hsum.convex hsum.closed
      hsum.proper (by rw [recessionConeFn_add_indicatorFn hh hC hCc hCne hne]; exact hrec)
    obtain ⟨w, hw⟩ := hne
    have hxdom : x ∈ dom (h + indicatorFn C) := mem_dom.2 (lt_of_le_of_lt (hx w) (mem_dom.1 hw))
    rw [dom_add hh.proper.ne_bot (indicatorFn_ne_bot C), dom_indicatorFn] at hxdom
    exact ⟨x, hxdom.2, fun z hz => forall_le_of_mem_argmin_add_indicatorFn hx hxdom.2 hz⟩
  · obtain ⟨x, hx⟩ := hCne
    refine ⟨x, hx, fun z hz => ?_⟩
    have hempty : dom h ∩ C = ∅ := by
      rw [← dom_indicatorFn C, ← dom_add hh.proper.ne_bot (indicatorFn_ne_bot C)]
      exact Set.not_nonempty_iff_eq_empty.1 hne
    have hz' : h z = ⊤ := by
      by_contra hcon
      exact Set.eq_empty_iff_forall_notMem.1 hempty z
        ⟨mem_dom.2 (lt_top_iff_ne_top.2 hcon), hz⟩
    rw [hz']
    exact le_top

/-- **Rockafellar, Corollary 27.3.3**, the non-polyhedral case: a closed proper convex `h` attains
its infimum subject to a consistent system of constraints `g i x ≤ 0` when `h` and the `g i` have
no direction of recession in common. The index type is arbitrary. -/
theorem exists_forall_le_of_forall_le_zero {ι : Type*} {g : ι → E → EReal}
    (hh : ClosedProperConvexFn h) (hg : ∀ i, ClosedProperConvexFn (g i))
    (hCne : {x : E | ∀ i, g i x ≤ 0}.Nonempty)
    (hrec : recessionConeFn h ∩ ⋂ i, recessionConeFn (g i) = {0}) :
    ∃ x, (∀ i, g i x ≤ 0) ∧ ∀ z, (∀ i, g i z ≤ 0) → h x ≤ h z := by
  obtain ⟨x₀, hx₀⟩ := hCne
  have hCeq : {x : E | ∀ i, g i x ≤ 0} = ⋂ i, {z : E | g i z ≤ ((0 : ℝ) : EReal)} := by
    ext z
    simp
  have hconv : ∀ i, Convex ℝ {z : E | g i z ≤ ((0 : ℝ) : EReal)} := fun i =>
    (hg i).convex.convex_le _
  have hclosed : ∀ i, IsClosed {z : E | g i z ≤ ((0 : ℝ) : EReal)} := fun i =>
    lowerSemicontinuous_iff_isClosed_le.1 (hg i).lowerSemicontinuous 0
  have hx₀' : x₀ ∈ ⋂ i, {z : E | g i z ≤ ((0 : ℝ) : EReal)} := hCeq ▸ hx₀
  have hCrec : recessionCone {x : E | ∀ i, g i x ≤ 0} = ⋂ i, recessionConeFn (g i) := by
    rw [hCeq, recessionCone_iInter hconv hclosed ⟨x₀, hx₀'⟩]
    exact Set.iInter_congr fun i =>
      recessionCone_setOf_le (hg i).convex (hg i).isClosed_epi ⟨x₀, Set.mem_iInter.1 hx₀' i⟩
  obtain ⟨x, hxC, hmin⟩ := exists_forall_le_of_recessionConeFn_inter_eq_zero hh
    (by rw [hCeq]; exact convex_iInter hconv) (by rw [hCeq]; exact isClosed_iInter hclosed)
    ⟨x₀, hx₀⟩ (by rw [hCrec]; exact hrec)
  exact ⟨x, hxC, hmin⟩

end Constrained

/-! ### Theorem 27.3: the polyhedral refinement

When the constraint set is polyhedral the recession hypothesis may be weakened from "`h` and `C`
have no direction of recession in common" to "every direction of recession common to `h` and `C` is
a direction in which `h` is *constant*". Rockafellar derives this from Helly's theorem in the form
of Theorem 21.5, applied to `C` together with the level sets `lev_α h` for `α` above the infimum.
The proof here does not: the directions of constancy of `h` form a subspace, and projecting `E`
along that subspace leaves `h` untouched while shrinking the common recession cone to `{0}`, which
is the hypothesis of the non-polyhedral case. Polyhedrality of `C` enters exactly once, through
`Polyhedral.recessionCone_image`: a linear map commutes with `0⁺` on a polyhedral set and on no
other kind. -/

section ConstancyReduction

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  {h : E → EReal} {C : Set E}

omit [FiniteDimensional ℝ E] in
/-- Two points differing by a direction of constancy carry the same value. This is
`mem_constancySpace_iff_forall_eq` (Corollary 8.6.1) read as a statement about a *pair* of points
rather than about a direction. -/
theorem eq_of_sub_mem_constancySpace {x y : E} (hxy : x - y ∈ constancySpace h) : h x = h y := by
  have hxy' : y + (1 : ℝ) • (x - y) = x := by rw [one_smul]; abel
  have hval := (mem_constancySpace_iff_forall_eq.1 hxy) y 1
  rwa [hxy'] at hval

omit [FiniteDimensional ℝ E] in
/-- **Every subspace is the kernel of a linear projection.** For a subspace `M` of `E` there is a
linear `A : E →ₗ[ℝ] E` and a complement `N` such that `A` moves every point only by a direction of
`M`, annihilates `M`, lands in `N` and fixes `N` pointwise.

This is the vehicle for "quotient out a subspace" arguments without leaving `E`: composing with `A`
keeps a function that is constant along `M` unchanged, and keeps its epigraph in play, which a
passage to `E ⧸ M` would not. -/
theorem exists_linearProj (M : Submodule ℝ E) :
    ∃ (A : E →ₗ[ℝ] E) (N : Submodule ℝ E), (∀ x, x - A x ∈ M) ∧ (∀ y ∈ M, A y = 0) ∧
      (∀ x, A x ∈ N) ∧ ∀ y ∈ N, A y = y := by
  obtain ⟨N, hN⟩ := Submodule.exists_isCompl M
  refine ⟨(LinearMap.id : E →ₗ[ℝ] E) - M.projection N hN, N, fun x => ?_, fun y hy => ?_,
    fun x => ?_, fun y hy => ?_⟩
  · have hval : x - ((LinearMap.id : E →ₗ[ℝ] E) - M.projection N hN) x
        = M.projection N hN x := by simp
    rw [hval, ← Submodule.coe_projectionOnto_apply]
    exact (M.projectionOnto N hN x).2
  · have hfix : M.projection N hN y = y := by
      rw [← Submodule.coe_projectionOnto_apply, Submodule.projectionOnto_apply_of_mem_left hN hy]
    simp [hfix]
  · have hval : ((LinearMap.id : E →ₗ[ℝ] E) - M.projection N hN) x = x - M.projection N hN x := by
      simp
    rw [hval, ← Submodule.projectionOnto_apply_eq_zero_iff hN, map_sub,
      Submodule.projectionOnto_projection hN, sub_self]
  · have hzero : M.projection N hN y = 0 := by
      rw [← Submodule.coe_projectionOnto_apply, Submodule.projectionOnto_apply_of_mem_right hN hy,
        Submodule.coe_zero]
    simp [hzero]

/-- **Rockafellar, Theorem 27.3**, in the general form the polyhedral refinement refines: a closed
proper convex `h` attains its infimum over a nonempty closed convex `C` as soon as every direction
of recession common to `h` and `C` is *both* a direction in which `h` is constant *and* a direction
of linearity of `C`.

`exists_forall_le_of_recessionConeFn_inter_eq_zero` is the case where the common recession cone is
`{0}`; here it may be any subspace along which `h` is constant and `C` is linear. The proof is the
projection argument again, this time along `constancySubmodule h ⊓ linealitySubmodule C`: the
image of `C` is literally `C ∩ N`, because `C` is invariant under the directions being projected
out, and its recession cone is `0⁺C ∩ N` by `recessionCone_inter`. -/
theorem exists_forall_le_of_inter_subset_constancySpace_inter_linealitySpace
    (hh : ClosedProperConvexFn h) (hC : Convex ℝ C) (hCc : IsClosed C) (hCne : C.Nonempty)
    (hrec : recessionConeFn h ∩ recessionCone C ⊆ constancySpace h ∩ linealitySpace C) :
    ∃ x ∈ C, ∀ z ∈ C, h x ≤ h z := by
  obtain ⟨A, N, hsub, hA0, hAN, hAfix⟩ :=
    exists_linearProj (constancySubmodule h ⊓ linealitySubmodule C)
  have hsubc : ∀ x, x - A x ∈ constancySpace h := fun x =>
    mem_constancySubmodule.1 (Submodule.mem_inf.1 (hsub x)).1
  have hsubl : ∀ x, x - A x ∈ linealitySpace C := fun x =>
    mem_linealitySubmodule.1 (Submodule.mem_inf.1 (hsub x)).2
  have hmemC : ∀ x ∈ C, A x ∈ C := by
    intro x hx
    have hneg : -(x - A x) ∈ recessionCone C := (mem_linealitySpace.1 (hsubl x)).2
    have := add_mem_of_mem_recessionCone hneg hx
    rwa [show x + -(x - A x) = A x by abel] at this
  have himg : A '' C = C ∩ (N : Set E) := by
    refine Set.Subset.antisymm ?_ fun y hy => ⟨y, hy.1, hAfix y hy.2⟩
    rintro _ ⟨x, hx, rfl⟩
    exact ⟨hmemC x hx, hAN x⟩
  obtain ⟨x₀, hx₀⟩ := hCne
  have hne : (C ∩ (N : Set E)).Nonempty := ⟨A x₀, hmemC x₀ hx₀, hAN x₀⟩
  have hrecimg : recessionCone (A '' C) = recessionCone C ∩ (N : Set E) := by
    rw [himg, recessionCone_inter hC hCc N.convex N.closed_of_finiteDimensional hne,
      recessionCone_coe_submodule]
  have hrec' : recessionConeFn h ∩ recessionCone (A '' C) = {0} := by
    refine Set.Subset.antisymm (fun y hy => ?_) fun y hy => ?_
    · obtain ⟨hy1, hy2⟩ := hy
      rw [hrecimg] at hy2
      obtain ⟨hy2C, hy2N⟩ := hy2
      have hyM : y ∈ constancySubmodule h ⊓ linealitySubmodule C := by
        obtain ⟨hc, hl⟩ := hrec ⟨hy1, hy2C⟩
        exact Submodule.mem_inf.2 ⟨mem_constancySubmodule.2 hc, mem_linealitySubmodule.2 hl⟩
      have h1 : A y = 0 := hA0 y hyM
      have h2 : A y = y := hAfix y hy2N
      exact Set.mem_singleton_iff.2 (by rw [← h2, h1])
    · rw [Set.mem_singleton_iff] at hy
      subst hy
      exact ⟨recessionFn_apply_zero_le h, zero_mem_recessionCone _⟩
  have hCimgconv : Convex ℝ (A '' C) := by rw [himg]; exact hC.inter N.convex
  have hCimgcl : IsClosed (A '' C) := by
    rw [himg]; exact hCc.inter N.closed_of_finiteDimensional
  obtain ⟨x', hx'C, hx'min⟩ := exists_forall_le_of_recessionConeFn_inter_eq_zero hh
    hCimgconv hCimgcl ⟨A x₀, ⟨x₀, hx₀, rfl⟩⟩ hrec'
  obtain ⟨x, hxC, rfl⟩ := hx'C
  refine ⟨x, hxC, fun z hz => ?_⟩
  rw [eq_of_sub_mem_constancySpace (hsubc x), eq_of_sub_mem_constancySpace (hsubc z)]
  exact hx'min (A z) ⟨z, hz, rfl⟩

/-- **Rockafellar, Theorem 27.3**, the polyhedral refinement: a closed proper convex `h` attains
its infimum over a nonempty **polyhedral** convex set `C` as soon as every direction of recession
common to `h` and `C` is a direction in which `h` is constant.

The hypothesis is strictly weaker than the one of
`exists_forall_le_of_recessionConeFn_inter_eq_zero`, which asks the common recession cone to be
`{0}`; polyhedrality of `C` is what pays for the weakening. It cannot be dropped: on `ℝ²` with
`h(x₁, x₂) = x₂` and the closed convex `C = {x | x₁ ≥ x₂²}`, the common recession cone is
`{(a, 0) | a ≥ 0}`, along which `h` is constant, yet `inf_C h = -∞`.

The proof replaces `C` by its image under a projection killing the constancy space of `h`
(`exists_linearProj`). The image is polyhedral, `h` is unchanged along the
fibres, and the common recession cone collapses to `{0}` — for a common direction of recession of
the image lifts to one of `C` by `Polyhedral.recessionCone_image`, and the lift differs from it by
a direction of constancy, hence is itself a common direction of recession and so lies in the
kernel. -/
theorem exists_forall_le_of_polyhedral_of_inter_subset_constancySpace
    (hh : ClosedProperConvexFn h) (hC : Polyhedral C) (hCne : C.Nonempty)
    (hrec : recessionConeFn h ∩ recessionCone C ⊆ constancySpace h) :
    ∃ x ∈ C, ∀ z ∈ C, h x ≤ h z := by
  obtain ⟨A, -, hsub', hA0, -, -⟩ := exists_linearProj (constancySubmodule h)
  have hsub : ∀ x, x - A x ∈ constancySpace h := fun x => mem_constancySubmodule.1 (hsub' x)
  have hCimg : Polyhedral (A '' C) := hC.image A
  have hCimgne : (A '' C).Nonempty := hCne.image A
  have hrec' : recessionConeFn h ∩ recessionCone (A '' C) = {0} := by
    refine Set.Subset.antisymm (fun y hy => ?_) (fun y hy => ?_)
    · obtain ⟨hy1, hy2⟩ := hy
      rw [hC.recessionCone_image hCne A] at hy2
      obtain ⟨y', hy', rfl⟩ := hy2
      have hdrec : y' - A y' ∈ recessionConeFn h := (mem_constancySpace.1 (hsub y')).1
      have hy'rec : y' ∈ recessionConeFn h := by
        have hadd : A y' + (y' - A y') ∈ recessionConeFn h :=
          (recessionPointedConeFn h).add_mem hy1 hdrec
        have heq : A y' + (y' - A y') = y' := by abel
        rwa [heq] at hadd
      exact Set.mem_singleton_iff.2
        (hA0 y' (mem_constancySubmodule.2 (hrec ⟨hy'rec, hy'⟩)))
    · rw [Set.mem_singleton_iff] at hy
      subst hy
      exact ⟨recessionFn_apply_zero_le h, zero_mem_recessionCone _⟩
  obtain ⟨x', hx'C, hx'min⟩ := exists_forall_le_of_recessionConeFn_inter_eq_zero hh
    hCimg.convex hCimg.isClosed hCimgne hrec'
  obtain ⟨x, hxC, rfl⟩ := hx'C
  refine ⟨x, hxC, fun z hz => ?_⟩
  rw [eq_of_sub_mem_constancySpace (hsub x), eq_of_sub_mem_constancySpace (hsub z)]
  exact hx'min (A z) ⟨z, hz, rfl⟩

/-- The unconstrained case of the polyhedral refinement: a closed proper convex function whose
recession cone consists entirely of directions of constancy — equivalently, whose recession cone is
a subspace — attains its infimum.

`argmin_nonempty_of_recessionConeFn_eq_zero` (Theorem 27.2) is the case where that subspace is
`{0}`. -/
theorem argmin_nonempty_of_recessionConeFn_subset_constancySpace (hh : ClosedProperConvexFn h)
    (hrec : recessionConeFn h ⊆ constancySpace h) : (argmin h).Nonempty := by
  obtain ⟨x, -, hx⟩ := exists_forall_le_of_polyhedral_of_inter_subset_constancySpace hh
    polyhedral_univ ⟨0, Set.mem_univ 0⟩ fun y hy => hrec hy.1
  exact ⟨x, mem_argmin_iff.2 fun z => hx z (Set.mem_univ z)⟩

end ConstancyReduction


/-! ### Polyhedral minimisation -/

section Polyhedral

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  {f : E → EReal}

/-- **A polyhedral convex function bounded below attains its infimum.**

Run the finitely generated description `epi f = conv P + cone D` (Theorem 19.1): a lower bound
forces every generating *direction* to point upward, so the vertical coordinate is minimised over
`epi f` at one of the finitely many generating *points*, and that point's horizontal coordinate
minimises `f`.

Neither closedness nor properness is assumed: boundedness below already excludes the value `-∞`,
and `f ≡ +∞` is minimised everywhere. -/
theorem argmin_nonempty_of_polyhedralFn (hf : PolyhedralFn f) (hbdd : ⊥ < ⨅ x, f x) :
    (argmin f).Nonempty := by
  classical
  have hbot : ∀ x, f x ≠ ⊥ := by
    intro x hx
    have hle : (⨅ z, f z) ≤ (⊥ : EReal) := by rw [← hx]; exact iInf_le f x
    exact absurd hle (not_le.2 hbdd)
  rcases eq_top_or_lt_top (⨅ x, f x) with htop | htop
  · refine ⟨0, fun z => ?_⟩
    have hz : f z = ⊤ := by
      refine top_le_iff.1 ?_
      rw [← htop]
      exact iInf_le f z
    rw [hz]
    exact le_top
  obtain ⟨β, hβ⟩ := Tdaf.EReal.exists_coe_of_ne_bot_of_lt_top (ne_of_gt hbdd) htop
  have hβle : ∀ x, (β : EReal) ≤ f x := by
    intro x
    rw [← hβ]
    exact iInf_le f x
  obtain ⟨P, D, hPD⟩ := Polyhedral.finitelyGenerated (hf : Polyhedral (epi f))
  -- the epigraph is non-empty, so there is at least one generating point
  have hepine : (epi f).Nonempty := by
    obtain ⟨x, hx⟩ := iInf_lt_iff.1 htop
    obtain ⟨r, hr⟩ := Tdaf.EReal.exists_coe_of_ne_bot_of_lt_top (hbot x) hx
    exact ⟨(x, r), mk_mem_epi.2 (le_of_eq hr)⟩
  have hPne : (P : Finset (E × ℝ)).Nonempty := by
    rcases Finset.eq_empty_or_nonempty P with rfl | hne
    · exfalso
      rw [hPD] at hepine
      simp only [Finset.coe_empty, convexHull_empty, Set.empty_add] at hepine
      exact hepine.ne_empty rfl
    · exact hne
  obtain ⟨p₀, hp₀⟩ := hPne
  have hmem_epi : ∀ p ∈ P, (p : E × ℝ) ∈ epi f := by
    intro p hp
    rw [hPD]
    exact ⟨p, subset_convexHull ℝ _ (by exact_mod_cast hp), 0, Submodule.zero_mem _, by simp⟩
  -- every generating direction points upward
  have hDnonneg : ∀ d ∈ D, (0 : ℝ) ≤ (d : E × ℝ).2 := by
    intro d hd
    by_contra hneg
    push Not at hneg
    have hβp₀ : (β : EReal) ≤ (p₀.2 : EReal) := le_trans (hβle p₀.1) (hmem_epi p₀ hp₀)
    have hβp₀' : β ≤ p₀.2 := by exact_mod_cast hβp₀
    have hdne : d.2 ≠ 0 := ne_of_lt hneg
    have htpos : 0 < (p₀.2 - β + 1) / (-d.2) := div_pos (by linarith) (by linarith)
    have hmemd : ((p₀.2 - β + 1) / (-d.2)) • (d : E × ℝ) ∈
        (PointedCone.hull ℝ (D : Set (E × ℝ)) : Set (E × ℝ)) :=
      Submodule.smul_mem _ (⟨(p₀.2 - β + 1) / (-d.2), htpos.le⟩ : {c : ℝ // 0 ≤ c})
        (PointedCone.subset_hull (by exact_mod_cast hd))
    have hsum : (p₀ : E × ℝ) + ((p₀.2 - β + 1) / (-d.2)) • (d : E × ℝ) ∈ epi f := by
      rw [hPD]
      exact ⟨p₀, subset_convexHull ℝ _ (by exact_mod_cast hp₀), _, hmemd, rfl⟩
    have hval : ((p₀ : E × ℝ) + ((p₀.2 - β + 1) / (-d.2)) • (d : E × ℝ)).2
        = p₀.2 + ((p₀.2 - β + 1) / (-d.2)) * d.2 := rfl
    have hle := le_trans (hβle _) hsum
    rw [hval] at hle
    have hle' : β ≤ p₀.2 + ((p₀.2 - β + 1) / (-d.2)) * d.2 := by exact_mod_cast hle
    have hcancel : ((p₀.2 - β + 1) / (-d.2)) * d.2 = -(p₀.2 - β + 1) := by
      field_simp
    rw [hcancel] at hle'
    linarith
  have hBall : ∀ b ∈ (PointedCone.hull ℝ (D : Set (E × ℝ)) : Set (E × ℝ)),
      (0 : ℝ) ≤ (b : E × ℝ).2 := by
    intro b hb
    induction hb using Submodule.span_induction with
    | mem z hz => exact hDnonneg z (by exact_mod_cast hz)
    | zero => exact le_refl 0
    | add z w _ _ hz hw =>
        have hadd : ((z + w : E × ℝ)).2 = z.2 + w.2 := rfl
        rw [hadd]
        linarith
    | smul c z _ hz =>
        have hc : (0 : ℝ) ≤ (c : ℝ) := c.2
        have hval : ((c • z : E × ℝ)).2 = (c : ℝ) * z.2 := rfl
        rw [hval]
        exact mul_nonneg hc hz
  -- the vertical coordinate is minimised over the generating points
  obtain ⟨pm, hpmP, hpmmin⟩ := P.exists_min_image (fun p : E × ℝ => p.2) ⟨p₀, hp₀⟩
  have hlow : ∀ q ∈ epi f, pm.2 ≤ (q : E × ℝ).2 := by
    intro q hq
    rw [hPD] at hq
    obtain ⟨a, ha, b, hb, hab⟩ := hq
    have hA : pm.2 ≤ a.2 := by
      have hsub : convexHull ℝ (P : Set (E × ℝ)) ⊆ {z : E × ℝ | pm.2 ≤ z.2} :=
        convexHull_min (fun p hp => hpmmin p (by exact_mod_cast hp))
          (convex_halfSpace_ge (LinearMap.isLinear (LinearMap.snd ℝ E ℝ)) pm.2)
      exact hsub ha
    have hB : (0 : ℝ) ≤ b.2 := hBall b hb
    have hq2 : (q : E × ℝ).2 = a.2 + b.2 := by rw [← hab]; rfl
    rw [hq2]
    linarith
  refine ⟨pm.1, fun z => ?_⟩
  have h1 : f pm.1 ≤ (pm.2 : EReal) := hmem_epi pm hpmP
  rcases eq_top_or_lt_top (f z) with hz | hz
  · rw [hz]
    exact le_top
  obtain ⟨r, hr⟩ := Tdaf.EReal.exists_coe_of_ne_bot_of_lt_top (hbot z) hz
  have hzepi : ((z, r) : E × ℝ) ∈ epi f := mk_mem_epi.2 (le_of_eq hr)
  have hmr : pm.2 ≤ r := hlow _ hzepi
  calc f pm.1 ≤ (pm.2 : EReal) := h1
    _ ≤ (r : EReal) := by exact_mod_cast hmr
    _ = f z := hr.symm

/-- **A polyhedral convex function attains its infimum relative to any non-empty polyhedral convex
set on which it is bounded below.**

Restricting `f` to `C` — the function that agrees with `f` on `C` and is `+∞` off it — cuts the
epigraph down by the vertical prism over `C`, so the restriction is again polyhedral, and
`argmin_nonempty_of_polyhedralFn` applies to it.

This is **Rockafellar, Corollary 27.3.2**. He derives it from Corollary 27.3.1, hence from Helly's
theorem; the argument here needs neither. -/
theorem exists_forall_le_of_polyhedralFn_of_polyhedral (hf : PolyhedralFn f) {C : Set E}
    (hC : Polyhedral C) (hCne : C.Nonempty) (hbdd : ⊥ < ⨅ x ∈ C, f x) :
    ∃ x ∈ C, ∀ z ∈ C, f x ≤ f z := by
  classical
  set g : E → EReal := fun x => ⨅ _ : x ∈ C, f x with hgdef
  have hgin : ∀ x ∈ C, g x = f x := fun x hx => iInf_pos hx
  have hgout : ∀ x ∉ C, g x = ⊤ := fun x hx => iInf_neg hx
  have hgpoly : PolyhedralFn g := by
    have hepi : epi g = epi f ∩ (C ×ˢ (Set.univ : Set ℝ)) := by
      ext p
      rw [mem_epi, Set.mem_inter_iff, mem_epi, Set.mem_prod]
      by_cases hx : p.1 ∈ C
      · rw [hgin _ hx]
        simp [hx]
      · rw [hgout _ hx, top_le_iff]
        simp [hx]
    change Polyhedral (epi g)
    rw [hepi]
    exact Polyhedral.inter hf (Polyhedral.prod hC polyhedral_univ)
  obtain ⟨x, hx⟩ := argmin_nonempty_of_polyhedralFn hgpoly hbdd
  by_cases hxC : x ∈ C
  · refine ⟨x, hxC, fun z hz => ?_⟩
    have h := hx z
    rwa [hgin _ hxC, hgin _ hz] at h
  · obtain ⟨x₀, hx₀⟩ := hCne
    refine ⟨x₀, hx₀, fun z hz => ?_⟩
    have h := hx z
    rw [hgout _ hxC, hgin _ hz, top_le_iff] at h
    rw [h]
    exact le_top

end Polyhedral

/-! ### The conjugate at the origin

Three readings of `f*` near the origin: the interior of `dom f*` governs boundedness of the
minimum set, and the support functions of the level sets are read off `f*` by homogenisation and
by a limit of directional derivatives. -/

section ConjugateAtZero

variable {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F] [FiniteDimensional ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} [IsCompatiblePairing B] [IsCompatiblePairing B.flip] {f : E → EReal}

omit [FiniteDimensional ℝ E] in
/-- The origin is interior to the effective domain of the conjugate exactly when the function has
no direction of recession.

Theorem 14.2 turns the recession cone into the polar of `dom f*`, and a convex set has the origin
in its interior exactly when its polar is trivial. -/
theorem zero_mem_interior_dom_conj_iff_recessionConeFn_eq_zero (hf : ConvexFn f) (hc : ClosedFn f)
    (hp : Proper f) :
    (0 : F) ∈ interior (dom (conj B f)) ↔ recessionConeFn f = {(0 : E)} := by
  rw [zero_mem_interior_iff_polarCone_eq_zero (B := B) (convexFn_conj B f).convex_dom
      (proper_conj ⟨hf, hc, hp⟩).dom_nonempty,
    ← recessionConeFn_eq_polarCone_dom_conj (B := B) hf hc hp]

/-- **Rockafellar, Theorem 27.1(d)**: the minimum set of a closed proper convex function is
non-empty and bounded exactly when the origin is interior to the effective domain of the
conjugate.

Both directions pass through "no direction of recession": one way, Theorem 8.7 identifies the
recession cone of the minimum set with that of `f`; the other, Theorem 27.2 produces the minimum
set and its compactness. -/
theorem argmin_nonempty_and_isBounded_iff_zero_mem_interior_dom_conj (hf : ConvexFn f)
    (hc : ClosedFn f) (hp : Proper f) :
    ((argmin f).Nonempty ∧ Bornology.IsBounded (argmin f))
      ↔ (0 : F) ∈ interior (dom (conj B f)) := by
  rw [zero_mem_interior_dom_conj_iff_recessionConeFn_eq_zero (B := B) hf hc hp]
  have hlsc : LowerSemicontinuous f := (closedFn_iff_lowerSemicontinuous hp.ne_bot).1 hc
  constructor
  · rintro ⟨⟨a, ha⟩, hbd⟩
    obtain ⟨x₀, hx₀⟩ := hp.dom_nonempty
    obtain ⟨μ, hμ⟩ := EReal.exists_coe_of_ne_bot_of_lt_top (hp.ne_bot a)
      (lt_of_le_of_lt (ha x₀) (mem_dom.1 hx₀))
    have hset : argmin f = {z : E | f z ≤ (μ : EReal)} := argmin_eq_setOf_le ha hμ
    have hne : {z : E | f z ≤ (μ : EReal)}.Nonempty := ⟨a, le_of_eq hμ⟩
    have hbd' : Bornology.IsBounded {z : E | f z ≤ (μ : EReal)} := by rw [← hset]; exact hbd
    have hrec := (isBounded_iff_recessionCone_eq_zero (hf.convex_le _)
      (lowerSemicontinuous_iff_isClosed_le.1 hlsc μ) hne).1 hbd'
    rwa [recessionCone_setOf_le hf (lowerSemicontinuous_iff_isClosed_epi.1 hlsc) hne] at hrec
  · intro hrec
    exact ⟨argmin_nonempty_of_recessionConeFn_eq_zero hf hc hp hrec,
      (isCompact_argmin_of_recessionConeFn_eq_zero hf hc hp hrec).isBounded⟩

/-- **Rockafellar, Theorem 27.1(d)** in the form Theorem 30.4(g) states it: *some* level set of
`f` is non-empty and bounded exactly when the origin is interior to `dom f*`.

Theorem 27.1(f) is what makes "some" as good as "every": all non-empty level sets share the
recession cone of `f`, so one bounded level set forces `f 0⁺` to be trivial, and Theorem 27.2 then
returns a bounded minimum set. -/
theorem exists_setOf_le_nonempty_and_isBounded_iff_zero_mem_interior_dom_conj (hf : ConvexFn f)
    (hc : ClosedFn f) (hp : Proper f) :
    (∃ α : ℝ, {x : E | f x ≤ (α : EReal)}.Nonempty ∧
        Bornology.IsBounded {x : E | f x ≤ (α : EReal)})
      ↔ (0 : F) ∈ interior (dom (conj B f)) := by
  rw [zero_mem_interior_dom_conj_iff_recessionConeFn_eq_zero (B := B) hf hc hp]
  have hlsc : LowerSemicontinuous f := (closedFn_iff_lowerSemicontinuous hp.ne_bot).1 hc
  constructor
  · rintro ⟨α, hne, hbd⟩
    have hrec := (isBounded_iff_recessionCone_eq_zero (hf.convex_le _)
      (lowerSemicontinuous_iff_isClosed_le.1 hlsc α) hne).1 hbd
    rwa [recessionCone_setOf_le hf (lowerSemicontinuous_iff_isClosed_epi.1 hlsc) hne] at hrec
  · intro hrec
    obtain ⟨a, ha⟩ := argmin_nonempty_of_recessionConeFn_eq_zero hf hc hp hrec
    obtain ⟨x₀, hx₀⟩ := hp.dom_nonempty
    obtain ⟨μ, hμ⟩ := EReal.exists_coe_of_ne_bot_of_lt_top (hp.ne_bot a)
      (lt_of_le_of_lt (ha x₀) (mem_dom.1 hx₀))
    refine ⟨μ, ⟨a, le_of_eq hμ⟩, ?_⟩
    rw [← argmin_eq_setOf_le ha hμ]
    exact (isCompact_argmin_of_recessionConeFn_eq_zero hf hc hp hrec).isBounded

include B in
/-- **Rockafellar, Theorem 30.4**, the equivalence of its conditions (g) and (i) for the objective
function of a convex program: the minimum set is non-empty and bounded exactly when some level set
is. Both say `0 ∈ int (dom f*)`. -/
theorem argmin_nonempty_and_isBounded_iff_exists_setOf_le (hf : ConvexFn f) (hc : ClosedFn f)
    (hp : Proper f) :
    ((argmin f).Nonempty ∧ Bornology.IsBounded (argmin f))
      ↔ ∃ α : ℝ, {x : E | f x ≤ (α : EReal)}.Nonempty ∧
          Bornology.IsBounded {x : E | f x ≤ (α : EReal)} :=
  (argmin_nonempty_and_isBounded_iff_zero_mem_interior_dom_conj (B := B) hf hc hp).trans
    (exists_setOf_le_nonempty_and_isBounded_iff_zero_mem_interior_dom_conj (B := B) hf hc hp).symm

omit [FiniteDimensional ℝ E] [FiniteDimensional ℝ F] [IsCompatiblePairing B]
  [IsCompatiblePairing B.flip] in
/-- Raising the conjugate by a real constant lowers the biconjugate by the same constant. -/
theorem conj_flip_conj_add_coe (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (f : E → EReal) (α : ℝ) (x : E) :
    conj B.flip (fun y => conj B f y + (α : EReal)) x = biconj B f x - (α : EReal) := by
  have hpt : ∀ (u : ℝ) (c : EReal), (u : EReal) - (c + (α : EReal))
      = ((u : EReal) - c) + ((-α : ℝ) : EReal) := by
    intro u c
    induction c with
    | bot => simp
    | top => simp
    | coe d =>
        rw [← _root_.EReal.coe_add, ← _root_.EReal.coe_sub, ← _root_.EReal.coe_sub,
          ← _root_.EReal.coe_add, _root_.EReal.coe_eq_coe_iff]
        ring
  rw [conj_apply]
  simp only [hpt]
  rw [← Tdaf.EReal.iSup_add_coe, _root_.EReal.coe_neg, ← sub_eq_add_neg]
  rfl

omit [FiniteDimensional ℝ E] [FiniteDimensional ℝ F] in
/-- **Rockafellar, Theorem 27.1(g)**, first sentence: for each real `α` the support function of
the level set `{f ≤ α}` is the closure of the positively homogeneous convex function generated by
`f* + α`.

This is Theorem 13.5 for `f - α`, obtained without any shifted-function API: Corollary 13.2.1
already computes the closure of a generated function as a support function, and the level set it
produces is `{x | f**(x) - α ≤ 0}`. -/
theorem supportFn_setOf_le (hf : ConvexFn f) (hc : ClosedFn f) (α : ℝ) :
    supportFn B {x : E | f x ≤ (α : EReal)}
      = clFn (posHomGen fun y => conj B f y + (α : EReal)) := by
  rw [clFn_posHomGen (B := B) fun y => conj B f y + (α : EReal)]
  congr 1
  ext x
  rw [Set.mem_ofPred_eq, Set.mem_ofPred_eq, conj_flip_conj_add_coe,
    show biconj B f x = f x from congrFun (biconj_eq_self hf hc) x,
    _root_.EReal.sub_le_iff_le_add (.inl (_root_.EReal.coe_ne_bot α))
      (.inl (_root_.EReal.coe_ne_top α)), zero_add]

omit [FiniteDimensional ℝ E] [FiniteDimensional ℝ F] in
/-- **Rockafellar, Theorem 27.1(g)**, second sentence: when `f` is bounded below, the support
function of its minimum set is the closure of the directional derivative of `f*` at the origin.

Theorem 27.1(b) identifies the minimum set with `∂f*(0)`, and Theorem 23.2 says the closure of a
directional derivative is the support function of the subdifferential. -/
theorem supportFn_argmin (hf : ConvexFn f) (hc : ClosedFn f) (hp : Proper f)
    (hbdd : conj B f 0 ≠ ⊤) :
    supportFn B (argmin f) = clFn (dirDeriv (conj B f) 0) := by
  rw [argmin_eq_subgradient_conj_zero (B := B) hf hc,
    clFn_dirDeriv (B := B.flip) (convexFn_conj B f) hbdd (conj_ne_bot hp.dom_nonempty 0),
    LinearMap.flip_flip]

omit [FiniteDimensional ℝ E] [FiniteDimensional ℝ F] [IsCompatiblePairing B.flip] in
/-- The level sets of `f` above its infimum are exactly the ε-subdifferentials of `f*` at the
origin.

Rockafellar states this inside the proof of Theorem 27.1(h). It is Fenchel–Moreau plus the
identity `f*(0) = -inf f`: `z ∈ ∂_ε f*(0)` says `⟨z, y⟩ - f*(y) ≤ inf f + ε` for every `y`, and the
supremum of the left side is `f**(z) = f(z)`. -/
theorem epsSubgradient_conj_zero (hf : ConvexFn f) (hc : ClosedFn f) (hp : Proper f)
    {μ : ℝ} (hμ : (⨅ x, f x) = (μ : EReal)) (ε : ℝ) :
    epsSubgradient B.flip ε (conj B f) 0 = {z : E | f z ≤ ((μ + ε : ℝ) : EReal)} := by
  have hc0 : conj B f 0 = ((-μ : ℝ) : EReal) := by
    rw [conj_zero_eq_neg_iInf, hμ, _root_.EReal.coe_neg]
  ext z
  rw [Set.mem_ofPred_eq, mem_epsSubgradient]
  have hstep : ∀ y : F, (conj B f 0 + ((B.flip (y - 0) z : ℝ) : EReal)
        ≤ conj B f y + (ε : EReal))
      ↔ (((B.flip y z : ℝ) : EReal) - conj B f y ≤ ((μ + ε : ℝ) : EReal)) := fun y => by
    rw [sub_zero, hc0, coe_add_le_add_coe_iff,
      _root_.EReal.sub_le_iff_le_add (.inl (conj_ne_bot hp.dom_nonempty y))
        (.inr (_root_.EReal.coe_ne_bot _)),
      add_comm (((μ + ε : ℝ) : EReal)) (conj B f y), show ε - -μ = μ + ε from by ring]
  simp only [hstep]
  have hbi : (⨆ y : F, ((B.flip y z : ℝ) : EReal) - conj B f y) = f z := by
    rw [← conj_apply]
    exact congrFun (biconj_eq_self hf hc) z
  rw [← iSup_le_iff, hbi]

omit [FiniteDimensional ℝ E] in
/-- **Rockafellar, Theorem 27.1(h)**: as the level shrinks to the infimum, the support functions of
the level sets of `f` converge to the directional derivative of `f*` at the origin.

Theorem 23.6 for `f*` at the origin, once `epsSubgradient_conj_zero` identifies the
ε-subdifferentials with the level sets. The limit is an infimum because `ε ↦ ∂_ε f*(0)` is
monotone; see `Subgradient/Approx.lean`. -/
theorem iInf_supportFn_setOf_le (hf : ConvexFn f) (hc : ClosedFn f) (hp : Proper f)
    {μ : ℝ} (hμ : (⨅ x, f x) = (μ : EReal)) (y : F) :
    (⨅ ε ∈ Set.Ioi (0 : ℝ), supportFn B {z : E | f z ≤ ((μ + ε : ℝ) : EReal)} y)
      = dirDeriv (conj B f) 0 y := by
  have hcp : Proper (conj B f) := proper_conj ⟨hf, hc, hp⟩
  have hc0 : conj B f 0 = ((-μ : ℝ) : EReal) := by
    rw [conj_zero_eq_neg_iInf, hμ, _root_.EReal.coe_neg]
  have hepi : IsClosed (epi (conj B f)) :=
    ClosedProperConvexFn.isClosed_epi ⟨convexFn_conj B f, closedFn_conj, hcp⟩
  rw [← dirDeriv_eq_iInf_supportFn_epsSubgradient (B := B.flip) (convexFn_conj B f) hcp hepi hc0 y]
  refine iInf_congr fun ε => iInf_congr fun hε => ?_
  rw [epsSubgradient_conj_zero hf hc hp hμ ε, LinearMap.flip_flip]

omit [NormedAddCommGroup E] [NormedSpace ℝ E] in
/-- A proper function takes a value below `⊤` somewhere, so its infimum is never `⊤`. Together
with `conj_ne_bot` this is why "finite" costs only one inequality on each side of Theorem
27.1(c). -/
theorem iInf_ne_top (hp : Proper f) : (⨅ x, f x) ≠ ⊤ := by
  obtain ⟨x₀, hx₀⟩ := hp.dom_nonempty
  exact (lt_of_le_of_lt (iInf_le _ x₀) (mem_dom.1 hx₀)).ne

omit [FiniteDimensional ℝ E] in
/-- **Rockafellar, Theorem 27.1(c)**: the infimum of a closed proper convex function is finite but
*unattained* exactly when `f*(0)` is finite and `f*'(0; ·)` takes the value `−∞` somewhere.

Theorem 27.1(a) turns "the infimum is finite" into "`f*(0)` is finite", Theorem 27.1(b) turns
"unattained" into "`∂f*(0) = ∅`", and Theorem 23.3 reads the latter off the directional
derivative. Only one bound appears on each side: `f*(0) ≠ ⊥` and `⨅ f ≠ ⊤` hold for every proper
`f`, by `conj_ne_bot` and `iInf_ne_top`. -/
theorem iInf_ne_bot_and_argmin_eq_empty_iff (hf : ConvexFn f) (hc : ClosedFn f) (hp : Proper f) :
    ((⨅ x, f x) ≠ ⊥ ∧ argmin f = ∅)
      ↔ (conj B f 0 ≠ ⊤ ∧ ∃ y : F, dirDeriv (conj B f) 0 y = ⊥) := by
  have hb : conj B f 0 ≠ ⊥ := conj_ne_bot hp.dom_nonempty 0
  have hiff : (⨅ x, f x) ≠ ⊥ ↔ conj B f 0 ≠ ⊤ := by
    rw [conj_zero_eq_neg_iInf, ne_eq, ne_eq, _root_.EReal.neg_eq_top_iff]
  rw [hiff, and_congr_right_iff]
  intro ht
  rw [argmin_eq_subgradient_conj_zero (B := B) hf hc,
    subgradient_eq_empty_iff_exists_dirDeriv_eq_bot (B := B.flip) (convexFn_conj B f) ht hb]

end ConjugateAtZero

end Tdaf.ConvexAnalysis
