/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Tdaf.Analysis.Convex.Duality.Gauge
import Tdaf.Analysis.Convex.Duality.Level

/-!
# The conjugate read off the polar of the homogenised epigraph

A convex function `f` on `E` is encoded, one dimension up, by the convex cone in `ℝ × E × ℝ`
generated by the vectors `(1, x, μ)` with `μ ≥ f x` — the cone `homCone f` of
`Convex/Homogenize.lean`. This module computes its polar for the pairing
`⟨(λ, x, μ), (λ*, y, μ*)⟩ = λ λ* + ⟨x, y⟩ + μ μ*`, and finds the *conjugate* of `f` inside it:
under the reflection `(λ*, y, μ*) ↦ (-μ*, y, -λ*)` the polar of `homCone f` is exactly the closure
of `homCone f*`.

So conjugacy of functions and polarity of cones are the same correspondence, read in two coordinate
systems one dimension apart. `Duality/Polar.lean` develops polarity from conjugacy; this module is
the derivation in the other direction.

## Main definitions

* `homConePairing B` — the pairing of `ℝ × E × ℝ` with `ℝ × F × ℝ` induced by `B`.
* `homCoord F` — the homogenising coordinate `(λ*, y, μ*) ↦ λ*`. Its cross-section `λ* = 1` is
  where the conjugate lives, and its positivity is what the density argument cuts on.
* `negSwapEnds F` — the reflection `(λ*, y, μ*) ↦ (-μ*, y, -λ*)`, a linear involution.

## Main results

* `conj_le_coe_iff_forall_mem_epi` — `f*(y) ≤ c` read on the epigraph: `⟨x, y⟩ - μ ≤ c` for every
  `(x, μ) ∈ epi f`. This is what turns a polarity condition into a statement about `f*`.
* `polarCone_homCone` — the polar of `homCone f` unfolded. The cone hull is invisible to polarity,
  so the polar is cut out by the generating vectors `(1, x, μ)` alone.
* `mem_homCone_conj_iff_of_pos` — the cross-section: for `λ* > 0`, the reflected vector
  `(-μ*, y, -λ*)` lies in the polar of `homCone f` exactly when `(λ*, y, μ*)` lies in `homCone f*`.
* `closure_homCone_conj` — `cl (homCone f*) = (negSwapEnds F) ⁻¹' (homCone f)°`
  (Theorem 14.4 in [^1]).

## Divergences from the reference

The hypotheses are the two properness conditions rather than "closed proper convex": `dom f`
nonempty, to see that the polar lies in the half-space `λ* ≥ 0`, and `dom f*` nonempty, to see that
it is not contained in the boundary hyperplane `λ* = 0`, plus convexity of `f`. Closedness of `f`
is what makes the second automatic, and belongs at the call site.

No bipolar theorem is used, and no closure of `K`. The classical argument reads "`cl K` contains
`(0, 0, 1)` but not `(0, 0, -1)`"; both facts are already visible in `K`, from the ray
`(1, x₀, r + t)` and from a single affine minorant of `f`. So the whole module needs no local
convexity, no compatibility of the pairing and no finite dimension.

## References

[^1]: R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §14.
-/

open Set Pointwise

namespace Tdaf.ConvexAnalysis

/-! ### The pairing, the coordinate and the reflection -/

section Defs

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]

/-- The pairing of `ℝ × E × ℝ` with `ℝ × F × ℝ` induced by `B`:
`⟨(λ, x, μ), (λ*, y, μ*)⟩ = λ λ* + ⟨x, y⟩ + μ μ*`. An `abbrev`, so that the `prodPairing` instances
remain visible to instance search. -/
abbrev homConePairing (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) :
    ((ℝ × E) × ℝ) →ₗ[ℝ] ((ℝ × F) × ℝ) →ₗ[ℝ] ℝ :=
  epiPairing (prodPairing mulPairing B)

@[simp] theorem homConePairing_apply (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (p : (ℝ × E) × ℝ)
    (q : (ℝ × F) × ℝ) :
    homConePairing B p q = p.1.1 * q.1.1 + B p.1.2 q.1.2 + p.2 * q.2 := rfl

theorem homConePairing_flip (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) :
    (homConePairing B).flip = homConePairing B.flip := by
  simp only [homConePairing, prodPairing_flip, mulPairing_flip]

/-- The **homogenising coordinate** `(λ*, y, μ*) ↦ λ*`, as a linear functional on `ℝ × F × ℝ`. -/
def homCoord (F : Type*) [AddCommGroup F] [Module ℝ F] : ((ℝ × F) × ℝ) →ₗ[ℝ] ℝ :=
  (LinearMap.fst ℝ ℝ F).comp (LinearMap.fst ℝ (ℝ × F) ℝ)

@[simp] theorem homCoord_apply (q : (ℝ × F) × ℝ) : homCoord F q = q.1.1 := rfl

/-- The **reflection** `(λ*, y, μ*) ↦ (-μ*, y, -λ*)` of `ℝ × F × ℝ`: it exchanges the homogenising
coordinate with the epigraph coordinate and reverses the sign of both. This linear involution is
the change of variables that turns the polar of a homogenised epigraph back into one. -/
def negSwapEnds (F : Type*) [AddCommGroup F] [Module ℝ F] :
    ((ℝ × F) × ℝ) →ₗ[ℝ] (ℝ × F) × ℝ where
  toFun q := ((-q.2, q.1.2), -q.1.1)
  map_add' p q := by simp [add_comm]
  map_smul' c q := by simp

@[simp] theorem negSwapEnds_apply (q : (ℝ × F) × ℝ) :
    negSwapEnds F q = ((-q.2, q.1.2), -q.1.1) := rfl

@[simp] theorem negSwapEnds_negSwapEnds (q : (ℝ × F) × ℝ) :
    negSwapEnds F (negSwapEnds F q) = q := by simp

theorem continuous_negSwapEnds (F : Type*) [AddCommGroup F] [Module ℝ F] [TopologicalSpace F] :
    Continuous (negSwapEnds F) :=
  ((continuous_snd.neg).prodMk continuous_fst.snd).prodMk continuous_fst.fst.neg

end Defs

/-! ### The conjugate on the epigraph -/

section Conj

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} {f : E → EReal}

/-- **`f*(y) ≤ c` read on the epigraph**: `⟨x, y⟩ - μ ≤ c` for every point `(x, μ)` of the
epigraph. This is `conj_le_coe_iff` with the affine minorant traded for the epigraph it dominates,
and it needs no properness. -/
theorem conj_le_coe_iff_forall_mem_epi {y : F} {c : ℝ} :
    conj B f y ≤ (c : EReal) ↔ ∀ p ∈ epi f, B p.1 y - p.2 ≤ c := by
  rw [conj_le_coe_iff]
  constructor
  · intro h p hp
    have h₁ : affineFn B y c p.1 ≤ ((p.2 : ℝ) : EReal) := le_trans (h p.1) hp
    rw [affineFn_eq_coe, _root_.EReal.coe_le_coe_iff] at h₁
    linarith
  · intro h x
    by_contra hlt
    rw [not_le] at hlt
    obtain ⟨μ, hμ₁, hμ₂⟩ := EReal.lt_iff_exists_real_btwn.1 hlt
    have hmem : ((x, μ) : E × ℝ) ∈ epi f := le_of_lt hμ₁
    have hle := h (x, μ) hmem
    rw [affineFn_eq_coe, _root_.EReal.coe_lt_coe_iff] at hμ₂
    simp only at hle
    linarith

end Conj

/-! ### The polar of the homogenised epigraph -/

section Polar

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} {f : E → EReal}

/-- **Membership of the polar of the generating epigraph**, unfolded: the generating vectors are
the `(1, x, μ)` with `μ ≥ f x`, and each of them contributes one homogeneous inequality. -/
theorem mem_polarCone_epi_levelOneLift {q : (ℝ × F) × ℝ} :
    q ∈ polarCone (homConePairing B) (epi (levelOneLift f)) ↔
      ∀ x : E, ∀ μ : ℝ, f x ≤ (μ : EReal) → q.1.1 + B x q.1.2 + μ * q.2 ≤ 0 := by
  rw [mem_polarCone]
  constructor
  · intro h x μ hμ
    have hmem : (((1, x), μ) : (ℝ × E) × ℝ) ∈ epi (levelOneLift f) :=
      mk_one_mem_epi_levelOneLift.2 hμ
    have hle := h _ hmem
    rw [homConePairing_apply] at hle
    simpa using hle
  · intro h p hp
    rw [mem_epi_levelOneLift] at hp
    rw [homConePairing_apply, hp.1, one_mul]
    exact h p.1.2 p.2 hp.2

/-- **Polarity does not see the cone generated**: the polar of `homCone f` is cut out by the
generating vectors `(1, x, μ)` alone. -/
theorem polarCone_homCone (hf : ConvexFn f) :
    polarCone (homConePairing B) (homCone f)
      = polarCone (homConePairing B) (epi (levelOneLift f)) := by
  rw [homCone_eq_coe_hull hf, polarCone_hull]

/-- **The cross-section.** For a strictly positive homogenising coordinate, the reflected vector
`(-μ*, y, -λ*)` lies in the polar of `homCone f` exactly when `(λ*, y, μ*)` lies in `homCone f*`.
This is the computation "`(-μ*, x*, -1) ∈ K°` iff `μ* ≥ f*(x*)`", at a general positive `λ*`. -/
theorem mem_homCone_conj_iff_of_pos (hf : ConvexFn f) {q : (ℝ × F) × ℝ} (ha : 0 < q.1.1) :
    q ∈ homCone (conj B f) ↔ negSwapEnds F q ∈ polarCone (homConePairing B) (homCone f) := by
  have hzero : q ≠ 0 := fun h => by rw [h] at ha; exact lt_irrefl 0 ha
  rw [mem_homCone_iff, polarCone_homCone hf, mem_polarCone_epi_levelOneLift,
    conj_le_coe_iff_forall_mem_epi]
  have key : ∀ u v : ℝ,
      (q.1.1⁻¹ * u - v ≤ q.1.1⁻¹ * q.2 ↔ -q.2 + u + v * -q.1.1 ≤ 0) := by
    intro u v
    constructor
    · intro hle
      have h₂ := mul_le_mul_of_nonneg_left hle ha.le
      rw [mul_sub, mul_inv_cancel_left₀ ha.ne', mul_inv_cancel_left₀ ha.ne'] at h₂
      linarith
    · intro hle
      have h₂ : q.1.1⁻¹ * (u - q.1.1 * v) ≤ q.1.1⁻¹ * q.2 :=
        mul_le_mul_of_nonneg_left (by linarith) (inv_nonneg.2 ha.le)
      have h₃ : q.1.1⁻¹ * (u - q.1.1 * v) = q.1.1⁻¹ * u - v := by
        calc q.1.1⁻¹ * (u - q.1.1 * v) = q.1.1⁻¹ * u - q.1.1⁻¹ * q.1.1 * v := by ring
          _ = q.1.1⁻¹ * u - v := by rw [inv_mul_cancel₀ ha.ne']; ring
      rw [h₃] at h₂
      exact h₂
  constructor
  · rintro (h | ⟨-, h⟩)
    · exact absurd h hzero
    · intro x μ hμ
      have hle := h (x, μ) hμ
      simp only [map_smul, smul_eq_mul] at hle
      exact (key (B x q.1.2) μ).1 hle
  · intro h
    refine Or.inr ⟨ha, fun p hp => ?_⟩
    have hle := h p.1 p.2 hp
    simp only [map_smul, smul_eq_mul]
    exact (key (B p.1 q.1.2) p.2).2 hle

/-- If a real affine expression `C + t d` is non-positive for every `t ≥ 0`, its slope is
non-positive. This is the "let `μ → ∞` along the vertical ray" step, done with an explicit `t`. -/
theorem nonpos_of_forall_add_mul_nonpos {C d : ℝ} (h : ∀ t : ℝ, 0 ≤ t → C + t * d ≤ 0) :
    d ≤ 0 := by
  by_contra hd
  rw [not_le] at hd
  have h₁ := h ((|C| + 1) / d) (div_nonneg (by positivity) hd.le)
  rw [div_mul_cancel₀ _ hd.ne'] at h₁
  have h₂ := neg_abs_le C
  linarith

/-- **The polar of the homogenised epigraph lies in the half-space `λ* ≥ 0`.** The vertical ray
`(1, x₀, r + t)`, `t ≥ 0`, above a point of `dom f` is what forces it. -/
theorem nonneg_homCoord_of_mem_polarCone (hf : ConvexFn f) (hdom : (dom f).Nonempty)
    {q : (ℝ × F) × ℝ} (hq : negSwapEnds F q ∈ polarCone (homConePairing B) (homCone f)) :
    0 ≤ homCoord F q := by
  obtain ⟨x₀, hx₀⟩ := hdom
  obtain ⟨r, hr, -⟩ := EReal.lt_iff_exists_real_btwn.1 hx₀
  rw [polarCone_homCone hf, mem_polarCone_epi_levelOneLift] at hq
  have hray : ∀ t : ℝ, 0 ≤ t →
      (-q.2 + B x₀ q.1.2 + r * -q.1.1) + t * -q.1.1 ≤ 0 := by
    intro t ht
    have hle := hq x₀ (r + t) (le_trans hr.le (by exact_mod_cast le_add_of_nonneg_right ht))
    simp only [negSwapEnds_apply] at hle
    nlinarith [hle]
  have hslope := nonpos_of_forall_add_mul_nonpos hray
  rw [homCoord_apply]
  linarith

end Polar

/-! ### The theorem -/

section Main

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  [TopologicalSpace F] [IsTopologicalAddGroup F] [ContinuousSMul ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} {f : E → EReal}

/-- For a convex `f` with nonempty effective domain and nonempty conjugate domain, and `K` the
convex cone generated by the vectors `(1, x, μ)` with `μ ≥ f x`,

`cl (homCone f*) = {(λ*, y, μ*) | (-μ*, y, -λ*) ∈ (homCone f)°}`.

The three steps are the cross-section `λ* > 0`, the fact that the polar lies in `λ* ≥ 0`, and
`Convex.closure_inter_setOf_pos`. -/
theorem closure_homCone_conj [IsContinuousPairing B.flip] (hf : ConvexFn f)
    (hdom : (dom f).Nonempty) (hdom' : (dom (conj B f)).Nonempty) :
    closure (homCone (conj B f))
      = negSwapEnds F ⁻¹' polarCone (homConePairing B) (homCone f) := by
  have hflip : IsContinuousPairing (homConePairing B).flip := by
    rw [homConePairing_flip]; infer_instance
  have hPclosed : IsClosed (polarCone (homConePairing B) (homCone f)) := isClosed_polarCone
  have hLclosed : IsClosed (negSwapEnds F ⁻¹' polarCone (homConePairing B) (homCone f)) :=
    hPclosed.preimage (continuous_negSwapEnds F)
  have hLconvex : Convex ℝ (negSwapEnds F ⁻¹' polarCone (homConePairing B) (homCone f)) :=
    Convex.linear_preimage (convex_polarCone _ _) (negSwapEnds F)
  have hsub : homCone (conj B f) ⊆
      negSwapEnds F ⁻¹' polarCone (homConePairing B) (homCone f) := by
    intro q hq
    rcases mem_homCone_iff.1 hq with rfl | ⟨hpos, -⟩
    · rw [Set.mem_preimage, map_zero]
      exact zero_mem_polarCone _ _
    · exact (mem_homCone_conj_iff_of_pos hf hpos).1 hq
  obtain ⟨y₀, hy₀⟩ := hdom'
  obtain ⟨c₀, hc₀, -⟩ := EReal.lt_iff_exists_real_btwn.1 hy₀
  have hq₀ : (((1, y₀), c₀) : (ℝ × F) × ℝ) ∈ homCone (conj B f) := by
    refine mem_homCone_iff.2 (Or.inr ⟨one_pos, ?_⟩)
    simpa using hc₀.le
  have hnn : ∀ q ∈ negSwapEnds F ⁻¹' polarCone (homConePairing B) (homCone f),
      0 ≤ homCoord F q := fun _ hq => nonneg_homCoord_of_mem_polarCone hf hdom hq
  have hcross : (negSwapEnds F ⁻¹' polarCone (homConePairing B) (homCone f)) ∩
      {q | 0 < homCoord F q} = homCone (conj B f) ∩ {q | 0 < homCoord F q} := by
    ext q
    simp only [Set.mem_inter_iff, Set.mem_preimage, Set.mem_ofPred, homCoord_apply]
    exact and_congr_left fun hpos => (mem_homCone_conj_iff_of_pos hf hpos).symm
  refine subset_antisymm (closure_minimal hsub hLclosed) ?_
  calc negSwapEnds F ⁻¹' polarCone (homConePairing B) (homCone f)
      ⊆ closure ((negSwapEnds F ⁻¹' polarCone (homConePairing B) (homCone f)) ∩
          {q | 0 < homCoord F q}) :=
        Convex.subset_closure_inter_setOf_pos hLconvex hnn (hsub hq₀) (by simp)
    _ = closure (homCone (conj B f) ∩ {q | 0 < homCoord F q}) := by rw [hcross]
    _ ⊆ closure (homCone (conj B f)) := closure_mono Set.inter_subset_left

end Main

end Tdaf.ConvexAnalysis
