/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Tdaf.Analysis.Convex.Homogenize
import Tdaf.Analysis.Convex.Recession.Conjugate
import Tdaf.Analysis.Convex.RelativeInterior

/-!
# Support functions of level sets

Rockafellar, *Convex Analysis*, §13, the part of the section that needs both the conjugate and the
recession function: **Theorem 13.5** (the support function of `{x | f x ≤ 0}`), **Theorem 13.4**
(the lineality space of `f*`), and **Corollary 13.3.1** (co-finiteness).

Theorem 13.5 is stated in terms of "the positively homogeneous convex function generated by `f`",
which is a *different* operator from `Homogenize.lean`'s `hom`: it lives on the same space as `f`,
and `hom` is that operator applied to the level-one lift (`posHomGen_levelOneLift`). §5 is
therefore developed here, since §13.5 is its first consumer.

## What is here

### The generating operator (§5)

* `posHomGenCone f` — the convex cone `{0} ∪ ⋃_{a > 0} a • epi f` generated by the epigraph.
* `posHomGen f = ofEpi (posHomGenCone f)` — **the positively homogeneous convex function generated
  by `f`**, with `posHomogeneous_posHomGen`, `convexFn_posHomGen`, `posHomGen_le`,
  `le_posHomGen` and the maximality statement `posHomGen_isGreatest`.
* `posHomGen_apply_of_ne_zero` — the book's formula `k x = inf {λ f (λ⁻¹ x) | λ > 0}`, valid away
  from the origin.
* `dom_posHomGen` — the effective domain is the cone generated by `dom f`.
* `posHomGen_levelOneLift` — the bridge to `hom`.

### The conjugate (§13, layer A)

* `supportSet_posHomGen` — homogenising does not change the set of linear minorants.
* `conj_posHomGen` — **`(posHomGen f)* = δ(· | {y | f* y ≤ 0})`**, with no hypothesis whatsoever.
  This is the shape Theorem 21.3 consumes.

### Theorem 13.5

* `clFn_posHomGen` — the second assertion: `cl (posHomGen g) = δ*(· | {x | g* x ≤ 0})`.
* `supportFn_setOf_le_zero` — the first assertion: `δ*(· | {x | f x ≤ 0}) = cl (posHomGen f*)`.

### Theorem 13.4

* `supportFn_neg_eq_neg_iff` — `δ*(-y | s) = -δ*(y | s)` iff `⟨·, y⟩` is constant on `s`.
* `linealitySpaceFn_conj`, `linealitySpaceFn_conj_eq_annihilator` — the lineality space of `f*` is
  the annihilator of the subspace parallel to `aff (dom f)`;
  `linealitySpaceFn_eq_annihilator_dom_conj` is the dual assertion.

### Corollary 13.3.1

* `Cofinite f` — Rockafellar's co-finite convex functions.
* `recessionFn_eq_supportFn_dom_conj` — **Theorem 13.3**, second assertion.
* `closure_dom_conj_eq_univ_iff` — the infinite-dimensional form: `dom f*` is *dense* iff `f` is
  co-finite.
* `dom_conj_eq_univ_iff`, `cofinite_iff_dom_conj_eq_univ`, `cofinite_iff_forall_conj_lt_top` — the
  book's form, under `FiniteDimensional ℝ F`.

## What is not here

* Corollary 13.5.1 (the support function of `epi f`), which needs the product pairing on `ℝ × E`
  and the conjugate of the level-one lift.
* The dimension formulas of Theorem 13.4 (`lineality f* = n - dim f`) and Corollaries 13.4.1–13.4.2,
  which need finite dimension and a `finrank` count of an annihilator.
* Corollaries 13.3.2–13.3.4, which belong with `Recession/Conjugate.lean`.

## Design notes

### The layers are not uniform

`conj_posHomGen` is layer A: positive homogeneity forces the conjugate to be an indicator, and
`posHomGen f 0 ≤ 0` holds because the generated cone contains the origin *by construction* — so,
unlike `hom_isGreatest`, no `f ≢ +∞` side condition appears anywhere in this file's core. Theorem
13.5 is layer C on the space where the *function* lives (Corollary 13.2.1 is Fenchel–Moreau for the
flipped pairing); its first assertion is layer C on both spaces, because that is what
Fenchel–Moreau on `f` costs. Theorem 13.4 is layer A. Corollary 13.3.1 is the only result that
needs finite dimension, and only in one direction.

### Two hypotheses the book does not write

* **`SeparatingDual ℝ E`.** "`δ*(y | F) = +∞` for `y ≠ 0`" needs the pairing to separate the points
  of `E`. With the indiscrete topology on `E` the continuous dual is `0`, the pairing with `F = 0`
  is compatible, and every support function vanishes; the book never meets this because `ℝⁿ` is
  Hausdorff.
* **`FiniteDimensional ℝ F`** in Corollary 13.3.1. The book's argument is "`dom f*` is not contained
  in any closed half-space, hence is everything", and the step from "not contained in a half-space"
  to "everything" fails in infinite dimensions — the kernel of a discontinuous functional is a
  dense proper convex subset. `closure_dom_conj_eq_univ_iff` is the statement that survives.

### Properness is not needed in Theorem 13.5

Rockafellar states Theorem 13.5 for closed *proper* convex `f`. Properness is never used here: the
improper cases are carried by Corollary 13.2.1 (`clFn_eq_supportFn_of_posHomogeneous`), which
already covers `cl g ≡ -∞` as the support function of `∅`, and by `biconj_eq_self`, which holds for
every closed convex function.

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §5 (the positively
  homogeneous convex function generated by a convex function) and §13 (Theorems 13.3–13.5).
-/

open Set Pointwise

namespace Tdaf.ConvexAnalysis

/-! ### Two `ofEpi` lemmas -/

section OfEpi

variable {E : Type*}

/-- `ofEpi` turns unions into infima. -/
theorem ofEpi_iUnion {ι : Sort*} (u : ι → Set (E × ℝ)) (x : E) :
    ofEpi (⋃ i, u i) x = ⨅ i, ofEpi (u i) x := by
  refine le_antisymm (le_iInf fun i => ofEpi_mono (Set.subset_iUnion u i) x) ?_
  refine le_ofEpi fun μ hμ => ?_
  obtain ⟨i, hi⟩ := Set.mem_iUnion.1 hμ
  exact (iInf_le (fun i => ofEpi (u i) x) i).trans (ofEpi_apply_le hi)

/-- `ofEpi` turns binary unions into infima. -/
theorem ofEpi_union (F G : Set (E × ℝ)) (x : E) :
    ofEpi (F ∪ G) x = ofEpi F x ⊓ ofEpi G x := by
  refine le_antisymm (le_inf (ofEpi_mono Set.subset_union_left x)
    (ofEpi_mono Set.subset_union_right x)) (le_ofEpi fun μ hμ => ?_)
  rcases hμ with hμ | hμ
  · exact inf_le_of_left_le (ofEpi_apply_le hμ)
  · exact inf_le_of_right_le (ofEpi_apply_le hμ)

end OfEpi

/-! ### The positively homogeneous convex function generated by `f` -/

section PosHomGen

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {f g : E → EReal} {K : Set (E × ℝ)}
  {a : ℝ} {x : E} {p : E × ℝ}

/-- The convex cone in `E × ℝ` generated by `epi f`: the origin together with every positive
multiple of the epigraph.

This is the set to which Rockafellar applies Theorem 5.3 to obtain the positively homogeneous
convex function generated by `f` (`posHomGen_eq_ofEpi`, which is the definition here). It is the
one-dimension-down analogue of `homCone`, and like it, it is *not* an epigraph: it meets the
fibre over `0` in the single point `0`. -/
def posHomGenCone (f : E → EReal) : Set (E × ℝ) := {0} ∪ ⋃ a > (0 : ℝ), a • epi f

/-- Membership of the generated cone, unfolded. -/
theorem mem_posHomGenCone_iff_exists :
    p ∈ posHomGenCone f ↔ p = 0 ∨ ∃ a > (0 : ℝ), p ∈ a • epi f := by
  simp [posHomGenCone]

/-- The generated cone contains the origin. -/
theorem zero_mem_posHomGenCone (f : E → EReal) : (0 : E × ℝ) ∈ posHomGenCone f :=
  mem_posHomGenCone_iff_exists.2 (Or.inl rfl)

/-- The generated cone contains the epigraph that generates it. -/
theorem epi_subset_posHomGenCone (f : E → EReal) : epi f ⊆ posHomGenCone f := fun _ hp =>
  mem_posHomGenCone_iff_exists.2 (Or.inr ⟨1, one_pos, by rwa [one_smul]⟩)

/-- The generated cone is a cone: it is invariant under multiplication by positive scalars. -/
theorem smul_posHomGenCone (ha : 0 < a) (f : E → EReal) :
    a • posHomGenCone f = posHomGenCone f := by
  ext q
  simp only [Set.mem_smul_set_iff_inv_smul_mem₀ ha.ne', mem_posHomGenCone_iff_exists]
  constructor
  · rintro (h | ⟨b, hb, hq⟩)
    · left
      have hz : a • (a⁻¹ • q) = a • (0 : E × ℝ) := by rw [h]
      rwa [smul_inv_smul₀ ha.ne', smul_zero] at hz
    · refine Or.inr ⟨a * b, mul_pos ha hb, ?_⟩
      have hmem : a • (a⁻¹ • q) ∈ a • (b • epi f) := Set.smul_mem_smul_set hq
      rwa [smul_inv_smul₀ ha.ne', smul_smul] at hmem
  · rintro (rfl | ⟨b, hb, hq⟩)
    · exact Or.inl (smul_zero _)
    · refine Or.inr ⟨a⁻¹ * b, mul_pos (inv_pos.2 ha) hb, ?_⟩
      rw [← smul_smul]
      exact Set.smul_mem_smul_set hq

/-- The generated cone is convex.

By Rockafellar's Theorem 2.6 (`convex_iff_add_mem_of_isCone`) it is enough to check closure under
addition, and that is `Convex.add_smul`: `a • S + b • S = (a + b) • S` for convex `S`. -/
theorem convex_posHomGenCone (hf : ConvexFn f) : Convex ℝ (posHomGenCone f) := by
  rw [convex_iff_add_mem_of_isCone fun c hc => smul_posHomGenCone hc f]
  intro p hp q hq
  rw [mem_posHomGenCone_iff_exists] at hp hq ⊢
  rcases hp with rfl | ⟨a, ha, hp⟩
  · rw [zero_add]
    exact hq
  rcases hq with rfl | ⟨b, hb, hq⟩
  · rw [add_zero]
    exact Or.inr ⟨a, ha, hp⟩
  refine Or.inr ⟨a + b, by positivity, ?_⟩
  rw [hf.convex_epi.add_smul ha.le hb.le]
  exact Set.add_mem_add hp hq

/-- **Minimality of the generated cone**: it is contained in every cone through the origin that
contains `epi f`. -/
theorem posHomGenCone_subset (h0 : (0 : E × ℝ) ∈ K) (hK : ∀ a : ℝ, 0 < a → a • K ⊆ K)
    (hf : epi f ⊆ K) : posHomGenCone f ⊆ K := by
  intro p hp
  rcases mem_posHomGenCone_iff_exists.1 hp with rfl | ⟨a, ha, hpa⟩
  · exact h0
  · exact hK a ha (Set.smul_set_mono hf hpa)

/-- **The positively homogeneous convex function generated by `f`** (Rockafellar §5): the function
obtained by applying Theorem 5.3 to the convex cone generated by `epi f`.

It is the greatest positively homogeneous convex `g` with `g 0 ≤ 0` and `g ≤ f`
(`posHomGen_isGreatest`), and away from the origin it is the book's infimum
`inf {λ f (λ⁻¹ x) | λ > 0}` (`posHomGen_apply_of_ne_zero`).

This is a *different* operator from `hom` (`Homogenize.lean`), which is the one generated by the
*level-one lift* of `f` and lives on `ℝ × E`; see the design note there. -/
noncomputable def posHomGen (f : E → EReal) : E → EReal := ofEpi (posHomGenCone f)

/-- The definition, restated: `posHomGen` is Theorem 5.3 applied to the generated cone. -/
theorem posHomGen_eq_ofEpi (f : E → EReal) : posHomGen f = ofEpi (posHomGenCone f) := rfl

/-- `posHomGen f` is a minorant of `f`. -/
theorem posHomGen_le (f : E → EReal) : posHomGen f ≤ f := by
  have h := ofEpi_mono (epi_subset_posHomGenCone f)
  rwa [ofEpi_epi] at h

/-- `posHomGen f` is nonpositive at the origin — with no hypothesis on `f`, since the generated
cone contains the origin even when `epi f` is empty. -/
theorem posHomGen_apply_zero_le (f : E → EReal) : posHomGen f 0 ≤ 0 := by
  have h : ((0 : E), (0 : ℝ)) ∈ posHomGenCone f := zero_mem_posHomGenCone f
  simpa [posHomGen] using ofEpi_apply_le (F := posHomGenCone f) h

/-- `posHomGen f` is never identically `+∞`: at the origin it is finite or `-∞`. -/
theorem posHomGen_apply_zero_ne_top (f : E → EReal) : posHomGen f 0 ≠ ⊤ :=
  ((posHomGen_apply_zero_le f).trans_lt (by simp)).ne

/-- **`ofEpi` of a cone is positively homogeneous.** This is the mechanism behind
`posHomogeneous_posHomGen`, and it needs nothing of the cone beyond invariance under positive
scaling — in particular it does not need convexity. -/
theorem posHomogeneous_ofEpi (hK : ∀ a : ℝ, 0 < a → a • K = K) : PosHomogeneous (ofEpi K) := by
  have key : ∀ b : ℝ, 0 < b → ∀ y : E, ofEpi K (b • y) ≤ (b : EReal) * ofEpi K y := by
    intro b hb y
    have hmul : (b : EReal) * ofEpi K y
        = ⨅ μ ∈ {μ : ℝ | (y, μ) ∈ K}, ((b * μ : ℝ) : EReal) := by
      simp only [ofEpi, Tdaf.EReal.coe_mul_iInf hb, Tdaf.EReal.coe_mul_coe]
    rw [hmul]
    refine le_iInf₂ fun μ hμ => ?_
    have hmem0 : ((y, μ) : E × ℝ) ∈ K := hμ
    have hmem : ((b • y, b * μ) : E × ℝ) ∈ K := by
      rw [← hK b hb]
      have hs := Set.smul_mem_smul_set (a := b) hmem0
      rwa [Prod.smul_mk, smul_eq_mul] at hs
    exact ofEpi_apply_le hmem
  intro a ha x
  refine le_antisymm (key a ha x) ?_
  have h := key a⁻¹ (inv_pos.2 ha) (a • x)
  rw [inv_smul_smul₀ ha.ne'] at h
  have h2 : (a : EReal) * ofEpi K x ≤ (a : EReal) * (((a⁻¹ : ℝ) : EReal) * ofEpi K (a • x)) :=
    mul_le_mul_of_nonneg_left h (by exact_mod_cast ha.le)
  rwa [← mul_assoc, Tdaf.EReal.coe_mul_coe, mul_inv_cancel₀ ha.ne', _root_.EReal.coe_one,
    one_mul] at h2

/-- **`posHomGen f` is positively homogeneous**, with no hypothesis on `f`. -/
theorem posHomogeneous_posHomGen (f : E → EReal) : PosHomogeneous (posHomGen f) :=
  posHomogeneous_ofEpi fun _ ha => smul_posHomGenCone ha f

/-- **`posHomGen f` is convex** whenever `f` is: Theorem 5.3 applied to the generated cone. -/
theorem convexFn_posHomGen (hf : ConvexFn f) : ConvexFn (posHomGen f) :=
  convexFn_ofEpi (convex_posHomGenCone hf)

/-- **The upper-bound half of the maximality property**: every positively homogeneous `g` with
`g 0 ≤ 0` that is majorised by `f` is majorised by `posHomGen f`.

Convexity of `g` is not used. The hypothesis `g 0 ≤ 0` is what makes `epi g` a cone *through the
origin*, and it is not removable. -/
theorem le_posHomGen (hg : PosHomogeneous g) (h0 : g 0 ≤ 0) (hle : g ≤ f) : g ≤ posHomGen f := by
  refine subset_epi_iff_le_ofEpi.1 (posHomGenCone_subset ?_ ?_ (epi_anti hle))
  · exact mk_mem_epi.2 (by simpa using h0)
  · exact fun a ha => (posHomogeneous_iff_isCone_epi.1 hg a ha).subset

/-- **The maximality property of `posHomGen f`** (Rockafellar §5): it is the greatest positively
homogeneous convex `g` with `g 0 ≤ 0` and `g ≤ f`.

Unlike `hom_isGreatest`, no hypothesis `f ≢ +∞` is needed: the generated cone contains the origin
by construction, so `posHomGen f 0 ≤ 0` holds even for `f ≡ +∞`, where `posHomGen f = δ(· | 0)`. -/
theorem posHomGen_isGreatest (hf : ConvexFn f) :
    IsGreatest {g : E → EReal | PosHomogeneous g ∧ ConvexFn g ∧ g 0 ≤ 0 ∧ g ≤ f}
      (posHomGen f) := by
  refine ⟨⟨posHomogeneous_posHomGen f, convexFn_posHomGen hf, posHomGen_apply_zero_le f,
    posHomGen_le f⟩, ?_⟩
  rintro g ⟨hg, -, h0, hle⟩
  exact le_posHomGen hg h0 hle

/-- **Rockafellar's formula for the generated function** (§5), away from the origin:
`k x = inf {λ f (λ⁻¹ x) | λ > 0}`.

The origin has to be excluded because the generated cone contributes the point `(0, 0)` there; this
is the book's remark that `λ = 0` may be dropped from the infimum `inf {(fλ) x | λ ≥ 0}` when
`x ≠ 0` or `f 0 < +∞`. -/
theorem posHomGen_apply_of_ne_zero (hx : x ≠ 0) (f : E → EReal) :
    posHomGen f x = ⨅ a > (0 : ℝ), (a : EReal) * f (a⁻¹ • x) := by
  have hsing : ∀ μ : ℝ, (x, μ) ∉ ({0} : Set (E × ℝ)) := fun μ h =>
    hx (congrArg (fun q : E × ℝ => q.1) h)
  have hcongr : ∀ μ : ℝ, (x, μ) ∈ posHomGenCone f ↔ (x, μ) ∈ ⋃ a > (0 : ℝ), a • epi f := by
    intro μ
    rw [posHomGenCone, Set.mem_union]
    exact or_iff_right (hsing μ)
  rw [posHomGen, ofEpi_apply_congr hcongr, ofEpi_iUnion]
  refine iInf_congr fun b => ?_
  rw [ofEpi_iUnion]
  refine iInf_congr fun hb => ?_
  rw [← smulRight, smulRight_apply_pos hb]

/-- The effective domain of `posHomGen f` is the convex cone generated by `dom f`.

This is what Theorem 21.3 calls "the convex cone generated by the union of the sets `dom fᵢ*`",
for a single function. -/
theorem dom_posHomGen (f : E → EReal) :
    dom (posHomGen f) = {0} ∪ ⋃ a > (0 : ℝ), a • dom f := by
  rw [posHomGen_eq_ofEpi, dom_ofEpi, posHomGenCone, Set.image_union, Set.image_iUnion₂]
  congr 1
  · exact Set.image_singleton
  · refine Set.iUnion₂_congr fun a _ => ?_
    rw [dom_eq_fst_image_epi]
    ext z
    constructor
    · rintro ⟨-, ⟨q, hq, rfl⟩, rfl⟩
      exact ⟨q.1, ⟨q, hq, rfl⟩, rfl⟩
    · rintro ⟨-, ⟨q, hq, rfl⟩, rfl⟩
      exact ⟨a • q, ⟨q, hq, rfl⟩, rfl⟩

/-- **`hom f` is `posHomGen` applied to the level-one lift.**

This reconciles the two homogenisation operators: Rockafellar's `hom f` on `ℝ × E` is *the*
positively homogeneous convex function generated by the level-one lift of `f`, and the two generated
cones are literally the same set (`posHomGenCone_levelOneLift`). The hypothesis `f ≢ +∞` is
`hom_eq_ofEpi_homCone`'s: for `f ≡ +∞` the cone degenerates to `{0}`, whose `ofEpi` is
`δ(· | 0)`, whereas `hom f ≡ +∞`. -/
theorem posHomGenCone_levelOneLift (f : E → EReal) :
    posHomGenCone (levelOneLift f) = homCone f := rfl

/-- `hom f` is the positively homogeneous convex function generated by the level-one lift of `f`. -/
theorem posHomGen_levelOneLift (hdom : (dom f).Nonempty) :
    posHomGen (levelOneLift f) = hom f := by
  rw [posHomGen_eq_ofEpi, posHomGenCone_levelOneLift, ← hom_eq_ofEpi_homCone hdom]

end PosHomGen

/-! ### The conjugate of a generated positively homogeneous function

This is the layer-A core of Theorem 13.5, and it needs no topology: `posHomGen f` is positively
homogeneous, so its conjugate is an indicator function (`conj_eq_indicatorFn_of_posHomogeneous`),
and the set it indicates is unchanged by the passage from `f` to `posHomGen f`. -/

section Conj

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]

/-- A linear functional read off a pairing is positively homogeneous. -/
theorem posHomogeneous_pairing (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (y : F) :
    PosHomogeneous fun x => ((B x y : ℝ) : EReal) := by
  intro a ha x
  simp only [map_smul, LinearMap.smul_apply, smul_eq_mul]
  exact (Tdaf.EReal.coe_mul_coe _ _).symm

/-- **Homogenising does not change the support set**: `⟨·, y⟩ ≤ posHomGen f` if and only if
`⟨·, y⟩ ≤ f`.

`⊆` is `posHomGen f ≤ f`; `⊇` is the maximality property applied to the linear function `⟨·, y⟩`,
which is positively homogeneous and vanishes at the origin. No hypothesis on `f`. -/
theorem supportSet_posHomGen (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (f : E → EReal) :
    supportSet B (posHomGen f) = supportSet B f := by
  ext y
  refine ⟨fun hy x => (hy x).trans (posHomGen_le f x), fun hy => ?_⟩
  exact le_posHomGen (posHomogeneous_pairing B y) (by simp) hy

/-- **The conjugate of the positively homogeneous convex function generated by `f`** is the
indicator of the set on which `f*` is nonpositive.

This is the layer-A core of Rockafellar's Theorem 13.5, and it is the form Theorem 21.3 consumes
("the conjugate of `k` is the indicator function of the convex set `{x | h*(x) ≤ 0}`"). It carries
**no hypothesis at all** — neither closedness, nor properness, nor convexity of `f` — because
`posHomGen f` is positively homogeneous and nonpositive at the origin whatever `f` is. -/
theorem conj_posHomGen (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (f : E → EReal) :
    conj B (posHomGen f) = indicatorFn {y : F | conj B f y ≤ 0} := by
  rw [conj_eq_indicatorFn_of_posHomogeneous (posHomogeneous_posHomGen f)
      ⟨0, posHomGen_apply_zero_ne_top f⟩, supportSet_posHomGen, supportSet_eq_setOf_conj_le]

/-- Homogenising does not change the conjugate's zero sublevel set: `(posHomGen f)*` and `f*` are
nonpositive on exactly the same vectors. -/
theorem setOf_conj_posHomGen_le_zero (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (f : E → EReal) :
    {y : F | conj B (posHomGen f) y ≤ 0} = {y : F | conj B f y ≤ 0} := by
  rw [← supportSet_eq_setOf_conj_le, ← supportSet_eq_setOf_conj_le, supportSet_posHomGen]

end Conj

/-! ### Theorem 13.5

Only the space the *function* lives on carries a topology: this is Corollary 13.2.1 applied to
`posHomGen`, and the level set produced is a subset of the other space. -/

section Theorem135

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  [TopologicalSpace F] [IsTopologicalAddGroup F] [ContinuousSMul ℝ F] [LocallyConvexSpace ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} [IsCompatiblePairing B.flip] {g : F → EReal}

/-- **Rockafellar, Theorem 13.5**, second assertion: the closure of the positively homogeneous
convex function `k` generated by `g` is the support function of `{x | g*(x) ≤ 0}`.

Convexity of `g` is the only hypothesis: neither closedness nor properness is used, because the
improper cases are already carried by Corollary 13.2.1 (`clFn_eq_supportFn_of_posHomogeneous`) —
if `g` takes `-∞` then `cl (posHomGen g) ≡ -∞`, the level set is empty, and both sides are the
support function of `∅`. -/
theorem clFn_posHomGen (hg : ConvexFn g) :
    clFn (posHomGen g) = supportFn B {x : E | conj B.flip g x ≤ 0} := by
  rw [clFn_eq_supportFn_of_posHomogeneous (B := B) (posHomogeneous_posHomGen g)
      (convexFn_posHomGen hg) ⟨0, posHomGen_apply_zero_ne_top g⟩, supportSet_posHomGen,
    supportSet_eq_setOf_conj_le]

/-- **Rockafellar, Theorem 13.5**, second assertion, in the form that identifies the support
function outright: if in addition `posHomGen g` is closed, it *is* the support function of
`{x | g*(x) ≤ 0}`. -/
theorem supportFn_setOf_conj_le_zero (hg : ConvexFn g) (hcl : ClosedFn (posHomGen g)) :
    supportFn B {x : E | conj B.flip g x ≤ 0} = posHomGen g :=
  (clFn_posHomGen hg).symm.trans hcl

end Theorem135

section Theorem135First

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  [TopologicalSpace E] [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [LocallyConvexSpace ℝ E]
  [TopologicalSpace F] [IsTopologicalAddGroup F] [ContinuousSMul ℝ F] [LocallyConvexSpace ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} [IsCompatiblePairing B] [IsCompatiblePairing B.flip] {f : E → EReal}

/-- **Rockafellar, Theorem 13.5**, first assertion: the support function of the level set
`{x | f x ≤ 0}` of a closed convex function is the closure of the positively homogeneous convex
function generated by `f*`.

This is the second assertion applied to `f*` together with Fenchel–Moreau, which is where
closedness of `f` enters: it is what turns `{x | f**(x) ≤ 0}` back into `{x | f(x) ≤ 0}`.
Rockafellar states the theorem for closed *proper* convex `f`; properness is not needed here,
since Fenchel–Moreau in the form `biconj_eq_self` covers the improper cases too. -/
theorem supportFn_setOf_le_zero (hf : ConvexFn f) (hc : ClosedFn f) :
    supportFn B {x : E | f x ≤ 0} = clFn (posHomGen (conj B f)) := by
  have hset : {x : E | conj B.flip (conj B f) x ≤ 0} = {x : E | f x ≤ 0} := by
    rw [show conj B.flip (conj B f) = biconj B f from rfl, biconj_eq_self hf hc]
  rw [clFn_posHomGen (B := B) (convexFn_conj B f), hset]

end Theorem135First

/-! ### Theorem 13.4

The *lineality space of a function* (`linealitySpaceFn`) is the set of directions in which its
recession function is additively reversible — Rockafellar's directions of affineness. It is
strictly larger than the *constancy space* (`constancySpace`), which asks the recession function to
vanish in both directions, and it is the lineality space that Theorem 13.4 is about. -/

section Theorem134

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} {s : Set E} {f : E → EReal}

/-- **A support function is additively reversible in the direction `y` exactly when `⟨·, y⟩` is
constant on the set.**

This is the support-function content of Theorem 13.4: `δ*(-y | s) = -δ*(y | s)` says that the
supremum and the infimum of `⟨·, y⟩` over `s` agree. Nonemptiness of `s` is needed — for `s = ∅`
both sides are `-∞` and `-(-∞) = +∞`. -/
theorem supportFn_neg_eq_neg_iff (hs : s.Nonempty) (y : F) :
    supportFn B s (-y) = -supportFn B s y ↔ ∃ c : ℝ, ∀ x ∈ s, B x y = c := by
  obtain ⟨x₀, hx₀⟩ := hs
  constructor
  · intro h
    have hbot : supportFn B s y ≠ ⊥ := supportFn_ne_bot ⟨x₀, hx₀⟩ y
    have hbot' : supportFn B s (-y) ≠ ⊥ := supportFn_ne_bot ⟨x₀, hx₀⟩ (-y)
    have htop : supportFn B s y ≠ ⊤ := by
      intro ht
      rw [ht, _root_.EReal.neg_top] at h
      exact hbot' h
    obtain ⟨c, hc⟩ :=
      Tdaf.EReal.exists_coe_of_ne_bot_of_lt_top hbot (lt_top_iff_ne_top.2 htop)
    refine ⟨c, fun x hx => ?_⟩
    have h1 : B x y ≤ c := supportFn_le_coe_iff.1 hc.le x hx
    have h2 : B x (-y) ≤ -c := by
      refine supportFn_le_coe_iff.1 ?_ x hx
      rw [h, hc, ← _root_.EReal.coe_neg]
    rw [map_neg] at h2
    linarith
  · rintro ⟨c, hc⟩
    have hy : supportFn B s y = ((c : ℝ) : EReal) :=
      le_antisymm (supportFn_le_coe_iff.2 fun x hx => (hc x hx).le)
        (by rw [← hc x₀ hx₀]; exact le_supportFn hx₀ y)
    have hy' : supportFn B s (-y) = ((-c : ℝ) : EReal) := by
      refine le_antisymm (supportFn_le_coe_iff.2 fun x hx => ?_)
        (by rw [show (-c : ℝ) = B x₀ (-y) by rw [map_neg, hc x₀ hx₀]]; exact le_supportFn hx₀ (-y))
      rw [map_neg, hc x hx]
    rw [hy, hy', _root_.EReal.coe_neg]

/-- **Rockafellar, Theorem 13.4**, unfolded: `y` is a direction of affineness of `f*` exactly when
`⟨·, y⟩` is constant on `dom f`. -/
theorem mem_linealitySpaceFn_conj_iff (hp : Proper f) (hc : Proper (conj B f)) {y : F} :
    y ∈ linealitySpaceFn (conj B f) ↔ ∃ c : ℝ, ∀ x ∈ dom f, B x y = c := by
  rw [mem_linealitySpaceFn, recessionFn_conj hp hc]
  exact supportFn_neg_eq_neg_iff hp.dom_nonempty y

/-- **Rockafellar, Theorem 13.4**, in the "constant on `dom f`" form. -/
theorem linealitySpaceFn_conj (hp : Proper f) (hc : Proper (conj B f)) :
    linealitySpaceFn (conj B f) = {y : F | ∀ x₁ ∈ dom f, ∀ x₂ ∈ dom f, B x₁ y = B x₂ y} := by
  ext y
  rw [mem_linealitySpaceFn_conj_iff hp hc]
  refine ⟨fun ⟨c, hc'⟩ x₁ h₁ x₂ h₂ => by rw [hc' x₁ h₁, hc' x₂ h₂], fun h => ?_⟩
  obtain ⟨x₀, hx₀⟩ := hp.dom_nonempty
  exact ⟨B x₀ y, fun x hx => h x hx x₀ hx₀⟩

/-- **Rockafellar, Theorem 13.4**: the lineality space of `f*` is the annihilator of the subspace
parallel to `aff (dom f)`.

`vectorSpan ℝ (dom f)` *is* that subspace: `direction_affineSpan` identifies it with
`(affineSpan ℝ (dom f)).direction`. In an inner-product space the annihilator is the orthogonal
complement, which is the book's phrasing. -/
theorem linealitySpaceFn_conj_eq_annihilator (hp : Proper f) (hc : Proper (conj B f)) :
    linealitySpaceFn (conj B f) = {y : F | ∀ v ∈ vectorSpan ℝ (dom f), B v y = 0} := by
  rw [linealitySpaceFn_conj hp hc]
  ext y
  constructor
  · intro h v hv
    have hle : vectorSpan ℝ (dom f) ≤ LinearMap.ker (B.flip y) := by
      rw [vectorSpan_def, Submodule.span_le]
      intro w hw
      obtain ⟨x₁, hx₁, x₂, hx₂, rfl⟩ := Set.mem_vsub.1 hw
      have hzero : B (x₁ - x₂) y = 0 := by
        rw [map_sub, LinearMap.sub_apply, h x₁ hx₁ x₂ hx₂, sub_self]
      simpa [vsub_eq_sub] using hzero
    exact hle hv
  · intro h x₁ h₁ x₂ h₂
    have hv : x₁ - x₂ ∈ vectorSpan ℝ (dom f) := by
      have hm := vsub_mem_vectorSpan ℝ h₁ h₂
      rwa [vsub_eq_sub] at hm
    have hz := h _ hv
    rw [map_sub, LinearMap.sub_apply] at hz
    linarith

end Theorem134

section Theorem134Dual

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  [TopologicalSpace E] [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [LocallyConvexSpace ℝ E]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} [IsCompatiblePairing B] {f : E → EReal}

/-- **Rockafellar, Theorem 13.4**, second assertion: for a closed proper convex `f`, the lineality
space of `f` itself is the annihilator of the subspace parallel to `aff (dom f*)`.

This is the first assertion applied to `f*`, with Fenchel–Moreau turning `f**` back into `f`. -/
theorem linealitySpaceFn_eq_annihilator_dom_conj (hf : ClosedProperConvexFn f) :
    linealitySpaceFn f = {x : E | ∀ w ∈ vectorSpan ℝ (dom (conj B f)), B x w = 0} := by
  have hcp : Proper (conj B f) := proper_conj hf
  have hbi : conj B.flip (conj B f) = f := biconj_eq_self hf.convex hf.closed
  have h := linealitySpaceFn_conj_eq_annihilator (B := B.flip) hcp
    (by rw [hbi]; exact hf.proper)
  rw [hbi] at h
  rw [h]
  ext x
  exact forall₂_congr fun w _ => Iff.rfl

end Theorem134Dual

/-! ### Co-finiteness and Corollary 13.3.1 -/

section Cofinite

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  [TopologicalSpace E] [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [LocallyConvexSpace ℝ E]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} {f : E → EReal}

/-- **Rockafellar's co-finite convex functions** (§13): closed proper convex functions whose
epigraph contains no non-vertical half-line, i.e. whose recession function is `+∞` in every
nonzero direction.

Corollary 13.3.1 identifies them as exactly the functions with an everywhere-finite conjugate. -/
structure Cofinite (f : E → EReal) : Prop extends ClosedProperConvexFn f where
  /-- The recession function is `+∞` in every direction but `0`. -/
  recessionFn_eq_top : ∀ y : E, y ≠ 0 → recessionFn f y = ⊤

/-- **Rockafellar, Theorem 13.3**, second assertion: for a closed proper convex `f`, the recession
function of `f` is the support function of `dom f*`.

This is `recessionFn_conj` applied to `f*`, with Fenchel–Moreau turning `f**` back into `f`. -/
theorem recessionFn_eq_supportFn_dom_conj [IsCompatiblePairing B]
    (hf : ClosedProperConvexFn f) :
    recessionFn f = supportFn B.flip (dom (conj B f)) := by
  have hcp : Proper (conj B f) := proper_conj hf
  have hbi : conj B.flip (conj B f) = f := biconj_eq_self hf.convex hf.closed
  have h := recessionFn_conj (B := B.flip) (f := conj B f) hcp (by rw [hbi]; exact hf.proper)
  rwa [hbi] at h

end Cofinite

section CofiniteMain

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  [TopologicalSpace E] [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [LocallyConvexSpace ℝ E]
  [TopologicalSpace F] [IsTopologicalAddGroup F] [ContinuousSMul ℝ F] [LocallyConvexSpace ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} [IsCompatiblePairing B] [IsCompatiblePairing B.flip] {f : E → EReal}

omit [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [LocallyConvexSpace ℝ E]
  [TopologicalSpace F] [IsTopologicalAddGroup F] [ContinuousSMul ℝ F] [LocallyConvexSpace ℝ F]
  [IsCompatiblePairing B.flip] in
/-- The support function of the *whole* dual space is `+∞` in every nonzero direction — provided
the pairing separates the points of `E`, which is what `SeparatingDual ℝ E` plus compatibility
gives.

The hypothesis is not decoration: for `E` with the indiscrete topology, `StrongDual ℝ E = 0`, the
pairing with `F = 0` is compatible, and every support function vanishes identically. Rockafellar
never writes it because `ℝⁿ` is Hausdorff. -/
theorem supportFn_univ_of_ne_zero [SeparatingDual ℝ E] {y : E} (hy : y ≠ 0) :
    supportFn B.flip (univ : Set F) y = ⊤ := by
  by_contra hne
  obtain ⟨c, hc⟩ := supportFn_lt_top_iff.1 (lt_top_iff_ne_top.2 hne)
  obtain ⟨g, hg⟩ := SeparatingDual.exists_ne_zero (R := ℝ) hy
  obtain ⟨w, hw⟩ := exists_pairing_eq B g
  have hBw : B y w ≠ 0 := by rw [← hw y]; exact hg
  have hstep : B y (((c + 1) / B y w) • w) ≤ c := hc _ (mem_univ _)
  rw [map_smul, smul_eq_mul, div_mul_cancel₀ _ hBw] at hstep
  linarith

/-- **Rockafellar, Corollary 13.3.1**, in the form that survives infinite dimensions: `dom f*` is
*dense* if and only if `f` is co-finite.

The book's statement is `dom f* = ℝⁿ`, and it is genuinely stronger than density outside finite
dimensions: the kernel of a discontinuous linear functional is a dense proper convex subset on
which no nonzero continuous linear functional is bounded above (gotcha: Corollary 11.5.2 needs
`closure C ≠ univ`, not `C ≠ univ`). `dom_conj_eq_univ_iff` restores the book's form under
`FiniteDimensional ℝ F`. -/
theorem closure_dom_conj_eq_univ_iff [SeparatingDual ℝ E] (hf : ClosedProperConvexFn f) :
    closure (dom (conj B f)) = univ ↔ ∀ y : E, y ≠ 0 → recessionFn f y = ⊤ := by
  have hrec := recessionFn_eq_supportFn_dom_conj (B := B) hf
  constructor
  · intro h y hy
    have := congrFun hrec y
    rw [this, ← supportFn_closure (B := B.flip) (dom (conj B f)), h]
    exact supportFn_univ_of_ne_zero (B := B) hy
  · intro h
    by_contra hcl
    obtain ⟨φ, c, hφ, hbnd⟩ := exists_ne_zero_forall_le_of_closure_ne_univ
      (convexFn_conj B f).convex_dom (proper_conj hf).dom_nonempty hcl
    obtain ⟨y, hy⟩ := exists_pairing_eq B.flip φ
    have hy0 : y ≠ 0 := by
      rintro rfl
      refine hφ (ContinuousLinearMap.ext fun w => ?_)
      simp [hy w]
    have hle : recessionFn f y ≤ (c : EReal) := by
      rw [congrFun hrec y, supportFn_le_coe_iff]
      exact fun w hw => (hy w).symm ▸ hbnd w hw
    rw [h y hy0] at hle
    exact absurd hle (by simp)

end CofiniteMain

section CofiniteFiniteDim

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [TopologicalSpace E]
  [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [LocallyConvexSpace ℝ E] [SeparatingDual ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F] [FiniteDimensional ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} [IsCompatiblePairing B] [IsCompatiblePairing B.flip] {f : E → EReal}
  {D : Set F}

omit [TopologicalSpace E] [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [LocallyConvexSpace ℝ E]
  [SeparatingDual ℝ E] [IsCompatiblePairing B] [IsCompatiblePairing B.flip] in
/-- In finite dimensions a dense convex set is everything: this is Theorem 6.3 (`ri (cl C) = ri C`)
together with `ri univ = univ`. It is what upgrades `closure_dom_conj_eq_univ_iff` to the book's
statement of Corollary 13.3.1. -/
theorem Convex.eq_univ_of_closure_eq_univ (hD : Convex ℝ D) (h : closure D = univ) : D = univ := by
  have h1 : ri (closure D) = ri D := Convex.relint_closure hD
  rw [h, intrinsicInterior_univ] at h1
  exact univ_subset_iff.1 (h1 ▸ intrinsicInterior_subset)

/-- **Rockafellar, Corollary 13.3.1**: for a closed proper convex `f`, the conjugate `f*` is finite
everywhere if and only if `f` is co-finite. -/
theorem dom_conj_eq_univ_iff (hf : ClosedProperConvexFn f) :
    dom (conj B f) = univ ↔ ∀ y : E, y ≠ 0 → recessionFn f y = ⊤ := by
  rw [← closure_dom_conj_eq_univ_iff (B := B) hf]
  exact ⟨fun h => by rw [h, closure_univ],
    Convex.eq_univ_of_closure_eq_univ (convexFn_conj B f).convex_dom⟩

/-- **Rockafellar, Corollary 13.3.1**, stated through `Cofinite`. -/
theorem cofinite_iff_dom_conj_eq_univ (hf : ClosedProperConvexFn f) :
    Cofinite f ↔ dom (conj B f) = univ := by
  rw [dom_conj_eq_univ_iff (B := B) hf]
  exact ⟨fun h => h.recessionFn_eq_top, fun h => { hf with recessionFn_eq_top := h }⟩

/-- **Rockafellar, Corollary 13.3.1**, in the "finite everywhere" phrasing. -/
theorem cofinite_iff_forall_conj_lt_top (hf : ClosedProperConvexFn f) :
    Cofinite f ↔ ∀ y : F, conj B f y < ⊤ := by
  rw [cofinite_iff_dom_conj_eq_univ (B := B) hf]
  exact ⟨fun h y => by rw [← mem_dom, h]; trivial, fun h => eq_univ_of_forall fun y => h y⟩

end CofiniteFiniteDim

end Tdaf.ConvexAnalysis
