/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Tdaf.Analysis.Convex.Duality.SupportRelint
import Tdaf.Analysis.Convex.Homogenize
import Tdaf.Analysis.Convex.Recession.ConeHull
import Tdaf.Analysis.Convex.Recession.Conjugate
import Tdaf.Analysis.Convex.RelativeInterior

/-!
# Support functions of level sets

Rockafellar, *Convex Analysis*, §13, the part of the section that needs both the conjugate and the
recession function: **Theorem 13.5** (the support function of `{x | f x ≤ 0}`), **Theorem 13.4**
(the lineality space of `f*`), and **Corollary 13.3.1** (co-finiteness).

Theorem 13.5 is stated in terms of "the positively homogeneous convex function generated by `f`",
which is a *different* operator from `Homogenize.lean`'s `hom`: it lives on the same space as `f`,
and `hom` is that operator applied to the level-one lift (`posHomGen_levelOneLift`). §5 is
therefore developed here, since §13.5 is its first consumer.

## What is here

### The generating operator (§5)

* `posHomGenCone f` — the convex cone `{0} ∪ ⋃_{a > 0} a • epi f` generated by the epigraph, and
  `posHomGenCone_eq_coe_hull`, which identifies it with `PointedCone.hull ℝ (epi f)` when `f` is
  convex.
* `posHomGen_eq_ofEpi` — the bridge to `posHomGen` (`Recession/ConeHull.lean`), **the positively
  homogeneous convex function generated by `f`**: for convex `f` it is `ofEpi` of the cone above.
  The operator's basic API (`posHomogeneous_posHomGen`, `convexFn_posHomGen`, `posHomGen_le`,
  `le_posHomGen`, `posHomGen_isGreatest`) is there, not here.
* `posHomGen_apply_of_ne_zero` — the book's formula `k x = inf {λ f (λ⁻¹ x) | λ > 0}`, valid away
  from the origin.
* `dom_posHomGen` — the effective domain is the cone generated by `dom f`.
* `posHomGen_apply_zero_of_nonneg` and `posHomGen_apply_zero_eq_bot_iff` — the value at the origin
  is `0` or `-∞`, according to the sign of `f 0`.
* `posHomGen_levelOneLift` — the bridge to `hom`.

### The zero level set of the generated function

* `coe_hull_setOf_le_zero_subset` and `setOf_posHomGen_lt_zero_subset` — the convex cone generated
  by `{x | f x ≤ 0}` lies between `{x | k x < 0}` and `{x | k x ≤ 0}`.
* `setOf_clFn_posHomGen_le_zero` — **`{x | (cl k) x ≤ 0}` is the closed convex cone generated by
  `{x | f x ≤ 0}`**, for closed proper convex `f` with `f 0 > 0 > inf f`. This is the geometric
  step of Rockafellar's Theorem 14.3, and the only layer-D result in the `posHomGen` material: it
  cites Theorem 7.6 and `proper_posHomGen`.

### The conjugate (§13, layer A)

* `supportSet_posHomGen` — homogenising does not change the set of linear minorants.
* `conj_posHomGen` — **`(posHomGen f)* = δ(· | {y | f* y ≤ 0})`**, with no hypothesis whatsoever.
  This is the shape Theorem 21.3 consumes.
* `conj_apply_zero` and `iInf_conj_eq_neg_apply_zero` — `f*(0) = -inf f` unconditionally, and
  `inf f* = -f(0)` for closed convex `f`. Together they say that Rockafellar's Theorem 14.3
  hypothesis `f(0) > 0 > inf f` is self-dual.

### Theorem 13.5

* `clFn_posHomGen` — the second assertion: `cl (posHomGen g) = δ*(· | {x | g* x ≤ 0})`.
* `supportFn_setOf_le_zero` — the first assertion: `δ*(· | {x | f x ≤ 0}) = cl (posHomGen f*)`.
* `conj_levelOneLift_le_zero_iff` and `clFn_hom` — **Corollary 13.5.1**: `cl (hom f)` is the
  support function of `{(λ*, x*) | λ* ≤ -f*(x*)}`, for the product pairing on `ℝ × E`.

### Theorem 13.4

* `mem_linealitySpaceFn_conj_iff` — `y` is a direction of affineness of `f*` exactly when
  `⟨·, y⟩` is constant on `dom f`. The support-function fact behind it,
  `supportFn_neg_eq_neg_iff`, is in `Duality/SupportRelint.lean`.
* `linealitySpaceFn_conj`, `linealitySpaceFn_conj_eq_annihilator` — the lineality space of `f*` is
  the annihilator of the subspace parallel to `aff (dom f)`;
  `linealitySpaceFn_eq_annihilator_dom_conj` is the dual assertion.

### Corollary 13.3.1

* `Cofinite f` — Rockafellar's co-finite convex functions.
* `recessionFn_eq_supportFn_dom_conj` — **Theorem 13.3**, second assertion.
* `closure_dom_conj_eq_univ_iff` — the infinite-dimensional form: `dom f*` is *dense* iff `f` is
  co-finite.
* `mem_closure_dom_conj_iff`, `mem_relint_dom_conj_iff`, `mem_interior_dom_conj_iff`,
  `mem_affineSpan_dom_conj_iff` — **Corollary 13.3.4**, its four clauses: where a point sits
  relative to `dom f*` is decided by the sign of `f 0⁺ - ⟨·, y₀⟩`.
* `zero_mem_closure_dom_conj_iff`, `zero_notMem_closure_dom_conj_iff` — clause (a) at the origin,
  which is **Theorem 27.1(i)** in both its sentences.
* `separatingRight_flip_of_separatingDual` — a compatible pairing with a separating dual separates
  the points of `E`, which is what clause (c) needs in place of the book's `y ≠ 0`.
* `dom_conj_eq_univ_iff`, `cofinite_iff_dom_conj_eq_univ`, `cofinite_iff_forall_conj_lt_top` — the
  book's form, under `FiniteDimensional ℝ F`.

### Corollary 13.4.2

* `interior_dom_conj_nonempty_iff` — `dom f*` has nonempty interior exactly when the lineality
  space of `f` is trivial.

## What is not here

* Corollary 8.5.2, which is what identifies `cl (hom f)` with Rockafellar's explicit `k` in
  Corollary 13.5.1; it is a §8 statement and belongs with `Recession/Function.lean`.
* The dimension formulas of Theorem 13.4 (`lineality f* = n - dim f`) and Corollary 13.4.1, which
  need finite dimension and a `finrank` count of an annihilator. Corollary 13.4.2 needs no count
  and is here, as `interior_dom_conj_nonempty_iff`.
* Corollaries 13.3.2 and 13.3.3, which belong with `Recession/Conjugate.lean`.

## Design notes

### The layers are not uniform

`conj_posHomGen` is layer A: positive homogeneity forces the conjugate to be an indicator, and
`posHomGen f 0 ≤ 0` holds because the generated cone contains the origin *by construction* — so,
unlike `hom_isGreatest`, no `f ≢ +∞` side condition appears anywhere in this file's core. Theorem
13.5 is layer C on the space where the *function* lives (Corollary 13.2.1 is Fenchel–Moreau for the
flipped pairing); its first assertion is layer C on both spaces, because that is what
Fenchel–Moreau on `f` costs. Theorem 13.4 is layer A. Corollary 13.3.1 and
`setOf_clFn_posHomGen_le_zero` are the only results that need finite dimension — Corollary 13.3.1
in one direction only, and `setOf_clFn_posHomGen_le_zero` through Theorem 7.6 and
`proper_posHomGen`, both of which are stated over a finite-dimensional space.

### Two hypotheses the book does not write

* **`SeparatingDual ℝ E`.** "`δ*(y | F) = +∞` for `y ≠ 0`" needs the pairing to separate the points
  of `E`. With the indiscrete topology on `E` the continuous dual is `0`, the pairing with `F = 0`
  is compatible, and every support function vanishes; the book never meets this because `ℝⁿ` is
  Hausdorff.
* **`FiniteDimensional ℝ F`** in Corollary 13.3.1. The book's argument is "`dom f*` is not contained
  in any closed half-space, hence is everything", and the step from "not contained in a half-space"
  to "everything" fails in infinite dimensions — the kernel of a discontinuous functional is a
  dense proper convex subset. `closure_dom_conj_eq_univ_iff` is the statement that survives.

### Properness is not needed in Theorem 13.5

Rockafellar states Theorem 13.5 for closed *proper* convex `f`. Properness is never used here: the
improper cases are carried by Corollary 13.2.1 (`clFn_eq_supportFn_of_posHomogeneous`), which
already covers `cl g ≡ -∞` as the support function of `∅`, and by `biconj_eq_self`, which holds for
every closed convex function.

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §5 (the positively
  homogeneous convex function generated by a convex function), §13 (Theorems 13.3–13.5) and
  §14 (the geometric step of Theorem 14.3).
-/

open Set Pointwise

namespace Tdaf.ConvexAnalysis

/-! ### The positively homogeneous convex function generated by `f` -/

section PosHomGen

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {f g : E → EReal} {K : Set (E × ℝ)}
  {a : ℝ} {x : E} {p : E × ℝ}

/-- The convex cone in `E × ℝ` generated by `epi f`: the origin together with every positive
multiple of the epigraph.

This is the set to which Rockafellar applies Theorem 5.3 to obtain the positively homogeneous
convex function generated by `f` (`posHomGen_eq_ofEpi`, which is the definition here). It is the
one-dimension-down analogue of `homCone`, and like it, it is *not* an epigraph: it meets the
fibre over `0` in the single point `0`. -/
def posHomGenCone (f : E → EReal) : Set (E × ℝ) := {0} ∪ ⋃ a > (0 : ℝ), a • epi f

/-- Membership of the generated cone, unfolded. -/
theorem mem_posHomGenCone_iff_exists :
    p ∈ posHomGenCone f ↔ p = 0 ∨ ∃ a > (0 : ℝ), p ∈ a • epi f := by
  simp [posHomGenCone]

/-- The generated cone contains the origin. -/
theorem zero_mem_posHomGenCone (f : E → EReal) : (0 : E × ℝ) ∈ posHomGenCone f :=
  mem_posHomGenCone_iff_exists.2 (Or.inl rfl)

/-- The generated cone contains the epigraph that generates it. -/
theorem epi_subset_posHomGenCone (f : E → EReal) : epi f ⊆ posHomGenCone f := fun _ hp =>
  mem_posHomGenCone_iff_exists.2 (Or.inr ⟨1, one_pos, by rwa [one_smul]⟩)

/-- The generated cone is a cone: it is invariant under multiplication by positive scalars. -/
theorem smul_posHomGenCone (ha : 0 < a) (f : E → EReal) :
    a • posHomGenCone f = posHomGenCone f := by
  ext q
  simp only [Set.mem_smul_set_iff_inv_smul_mem₀ ha.ne', mem_posHomGenCone_iff_exists]
  constructor
  · rintro (h | ⟨b, hb, hq⟩)
    · left
      have hz : a • (a⁻¹ • q) = a • (0 : E × ℝ) := by rw [h]
      rwa [smul_inv_smul₀ ha.ne', smul_zero] at hz
    · refine Or.inr ⟨a * b, mul_pos ha hb, ?_⟩
      have hmem : a • (a⁻¹ • q) ∈ a • (b • epi f) := Set.smul_mem_smul_set hq
      rwa [smul_inv_smul₀ ha.ne', smul_smul] at hmem
  · rintro (rfl | ⟨b, hb, hq⟩)
    · exact Or.inl (smul_zero _)
    · refine Or.inr ⟨a⁻¹ * b, mul_pos (inv_pos.2 ha) hb, ?_⟩
      rw [← smul_smul]
      exact Set.smul_mem_smul_set hq

/-- The generated cone is convex.

By Rockafellar's Theorem 2.6 (`convex_iff_add_mem_of_isCone`) it is enough to check closure under
addition, and that is `Convex.add_smul`: `a • S + b • S = (a + b) • S` for convex `S`. -/
theorem convex_posHomGenCone (hf : ConvexFn f) : Convex ℝ (posHomGenCone f) := by
  rw [convex_iff_add_mem_of_isCone fun c hc => smul_posHomGenCone hc f]
  intro p hp q hq
  rw [mem_posHomGenCone_iff_exists] at hp hq ⊢
  rcases hp with rfl | ⟨a, ha, hp⟩
  · rw [zero_add]
    exact hq
  rcases hq with rfl | ⟨b, hb, hq⟩
  · rw [add_zero]
    exact Or.inr ⟨a, ha, hp⟩
  refine Or.inr ⟨a + b, by positivity, ?_⟩
  rw [hf.convex_epi.add_smul ha.le hb.le]
  exact Set.add_mem_add hp hq

/-- **Minimality of the generated cone**: it is contained in every cone through the origin that
contains `epi f`. -/
theorem posHomGenCone_subset (h0 : (0 : E × ℝ) ∈ K) (hK : ∀ a : ℝ, 0 < a → a • K ⊆ K)
    (hf : epi f ⊆ K) : posHomGenCone f ⊆ K := by
  intro p hp
  rcases mem_posHomGenCone_iff_exists.1 hp with rfl | ⟨a, ha, hpa⟩
  · exact h0
  · exact hK a ha (Set.smul_set_mono hf hpa)

/-- **The cone generated by the epigraph of a convex function is its `PointedCone` hull.**

This is `coe_hull_of_convex` read for `epi f`, and it is what makes `posHomGenCone` a *description*
of the cone that defines `posHomGen` (`Recession/ConeHull.lean`) rather than a second definition of
it. For non-convex `f` the two differ: the hull adds the sums that `{0} ∪ ⋃_{a > 0} a • epi f`
misses. -/
theorem posHomGenCone_eq_coe_hull (hf : ConvexFn f) :
    posHomGenCone f = (PointedCone.hull ℝ (epi f) : Set (E × ℝ)) := by
  rw [coe_hull_of_convex hf.convex_epi]
  ext q
  rw [mem_posHomGenCone_iff_exists, Set.mem_insert_iff]
  constructor
  · rintro (rfl | ⟨a, ha, h⟩)
    · exact Or.inl rfl
    · exact Or.inr ⟨a, ha, h⟩
  · rintro (rfl | ⟨a, ha, h⟩)
    · exact Or.inl rfl
    · exact Or.inr ⟨a, ha, h⟩

/-- **The positively homogeneous convex function generated by a convex `f`** is Theorem 5.3 applied
to `posHomGenCone f`.

`posHomGen` itself is defined in `Recession/ConeHull.lean` from the `PointedCone` hull, which is
what gives it its unconditional convexity and maximality; this is the ray description that
Rockafellar's formulas in §5 and §13 are stated against. -/
theorem posHomGen_eq_ofEpi (hf : ConvexFn f) : posHomGen f = ofEpi (posHomGenCone f) := by
  rw [posHomGenCone_eq_coe_hull hf, posHomGen]

/-- `posHomGen f` is never identically `+∞`: at the origin it is finite or `-∞`. -/
theorem posHomGen_apply_zero_ne_top (f : E → EReal) : posHomGen f 0 ≠ ⊤ :=
  ((posHomGen_apply_zero_le f).trans_lt (by simp)).ne

/-- If `f` is nonnegative at the origin, so is every positive multiple of its epigraph, and
`posHomGen f 0 = 0`. -/
theorem posHomGen_apply_zero_of_nonneg (hf : ConvexFn f) (h : 0 ≤ f 0) : posHomGen f 0 = 0 := by
  refine le_antisymm (posHomGen_apply_zero_le f) ?_
  rw [posHomGen_eq_ofEpi hf]
  refine le_ofEpi fun μ hμ => ?_
  rcases mem_posHomGenCone_iff_exists.1 hμ with h0 | ⟨a, ha, hmem⟩
  · rw [show μ = 0 from congrArg (fun q : E × ℝ => q.2) h0]
    exact le_of_eq _root_.EReal.coe_zero.symm
  · rw [Set.mem_smul_set_iff_inv_smul_mem₀ ha.ne'] at hmem
    have hx : (a⁻¹ • ((0 : E), μ)).1 = (0 : E) := by simp
    have hfle : f 0 ≤ ((a⁻¹ * μ : ℝ) : EReal) := by
      have := mem_epi.1 hmem
      rwa [hx] at this
    have hnn : (0 : ℝ) ≤ a⁻¹ * μ := by
      exact_mod_cast h.trans hfle
    have : (0 : ℝ) ≤ μ := by
      have ha' : 0 < a⁻¹ := inv_pos.2 ha
      nlinarith
    exact_mod_cast this

/-- **`posHomGen f` is `-∞` at the origin exactly when `f` is negative there.**

This is the step "`k(0) = -∞`, therefore `h(0) < 0`" in Rockafellar's proof of Theorem 21.3. -/
theorem posHomGen_apply_zero_eq_bot_iff (hf : ConvexFn f) : posHomGen f 0 = ⊥ ↔ f 0 < 0 := by
  constructor
  · intro h
    by_contra hcon
    rw [not_lt] at hcon
    rw [posHomGen_apply_zero_of_nonneg hf hcon] at h
    exact absurd h (by simp)
  · intro h
    have h0 : f 0 < ((0 : ℝ) : EReal) := by rwa [_root_.EReal.coe_zero]
    obtain ⟨q, hq₁, hq₂⟩ := Tdaf.EReal.exists_real_btwn_of_lt_coe h0
    rw [posHomGen_eq_ofEpi hf]
    refine Tdaf.EReal.eq_bot_of_forall_le_coe fun r => ?_
    set a : ℝ := max (r / q) 1 with ha
    have ha0 : 0 < a := lt_of_lt_of_le one_pos (le_max_right _ _)
    have hmem : ((0 : E), a * q) ∈ posHomGenCone f := by
      refine mem_posHomGenCone_iff_exists.2 (Or.inr ⟨a, ha0, ⟨((0 : E), q), ?_, ?_⟩⟩)
      · exact mk_mem_epi.2 hq₁.le
      · simp [Prod.smul_mk]
    refine (ofEpi_apply_le hmem).trans ?_
    have hle : a * q ≤ r :=
      calc a * q ≤ (r / q) * q := mul_le_mul_of_nonpos_right (le_max_left _ _) hq₂.le
        _ = r := div_mul_cancel₀ r hq₂.ne
    exact_mod_cast hle

/-- **`ofEpi` of a cone is positively homogeneous.** This is the mechanism behind
`posHomogeneous_posHomGen`, and it needs nothing of the cone beyond invariance under positive
scaling — in particular it does not need convexity. -/
theorem posHomogeneous_ofEpi (hK : ∀ a : ℝ, 0 < a → a • K = K) : PosHomogeneous (ofEpi K) := by
  have key : ∀ b : ℝ, 0 < b → ∀ y : E, ofEpi K (b • y) ≤ (b : EReal) * ofEpi K y := by
    intro b hb y
    have hmul : (b : EReal) * ofEpi K y
        = ⨅ μ ∈ {μ : ℝ | (y, μ) ∈ K}, ((b * μ : ℝ) : EReal) := by
      simp only [ofEpi, Tdaf.EReal.coe_mul_iInf hb, Tdaf.EReal.coe_mul_coe]
    rw [hmul]
    refine le_iInf₂ fun μ hμ => ?_
    have hmem0 : ((y, μ) : E × ℝ) ∈ K := hμ
    have hmem : ((b • y, b * μ) : E × ℝ) ∈ K := by
      rw [← hK b hb]
      have hs := Set.smul_mem_smul_set (a := b) hmem0
      rwa [Prod.smul_mk, smul_eq_mul] at hs
    exact ofEpi_apply_le hmem
  intro a ha x
  refine le_antisymm (key a ha x) ?_
  have h := key a⁻¹ (inv_pos.2 ha) (a • x)
  rw [inv_smul_smul₀ ha.ne'] at h
  have h2 : (a : EReal) * ofEpi K x ≤ (a : EReal) * (((a⁻¹ : ℝ) : EReal) * ofEpi K (a • x)) :=
    mul_le_mul_of_nonneg_left h (by exact_mod_cast ha.le)
  rwa [← mul_assoc, Tdaf.EReal.coe_mul_coe, mul_inv_cancel₀ ha.ne', _root_.EReal.coe_one,
    one_mul] at h2

/-- **The ray description of the generated cone is enough for maximality**: it is contained in
`epi g` for every positively homogeneous `g` with `g 0 ≤ 0` and `g ≤ f`, *without* convexity of
`g`. `le_posHomGen` (`Recession/ConeHull.lean`) needs `ConvexFn g` because it works with the hull;
for convex `f` the two descriptions agree (`posHomGen_eq_ofEpi`). -/
theorem le_ofEpi_posHomGenCone (hg : PosHomogeneous g) (h0 : g 0 ≤ 0) (hle : g ≤ f) :
    g ≤ ofEpi (posHomGenCone f) := by
  refine subset_epi_iff_le_ofEpi.1 (posHomGenCone_subset ?_ ?_ (epi_anti hle))
  · exact mk_mem_epi.2 (by simpa using h0)
  · exact fun a ha => (posHomogeneous_iff_isCone_epi.1 hg a ha).subset

/-- **Rockafellar's formula for the generated function** (§5), away from the origin:
`k x = inf {λ f (λ⁻¹ x) | λ > 0}`.

The origin has to be excluded because the generated cone contributes the point `(0, 0)` there; this
is the book's remark that `λ = 0` may be dropped from the infimum `inf {(fλ) x | λ ≥ 0}` when
`x ≠ 0` or `f 0 < +∞`. -/
theorem posHomGen_apply_of_ne_zero (hf : ConvexFn f) (hx : x ≠ 0) :
    posHomGen f x = ⨅ a > (0 : ℝ), (a : EReal) * f (a⁻¹ • x) := by
  have hsing : ∀ μ : ℝ, (x, μ) ∉ ({0} : Set (E × ℝ)) := fun μ h =>
    hx (congrArg (fun q : E × ℝ => q.1) h)
  have hcongr : ∀ μ : ℝ, (x, μ) ∈ posHomGenCone f ↔ (x, μ) ∈ ⋃ a > (0 : ℝ), a • epi f := by
    intro μ
    rw [posHomGenCone, Set.mem_union]
    exact or_iff_right (hsing μ)
  rw [posHomGen_eq_ofEpi hf, ofEpi_apply_congr hcongr, ofEpi_iUnion, iInf_apply]
  refine iInf_congr fun b => ?_
  rw [ofEpi_iUnion, iInf_apply]
  refine iInf_congr fun hb => ?_
  rw [← smulRight, smulRight_apply_pos hb]

/-- The effective domain of `posHomGen f` is the convex cone generated by `dom f`.

This is what Theorem 21.3 calls "the convex cone generated by the union of the sets `dom fᵢ*`",
for a single function. -/
theorem dom_posHomGen (hf : ConvexFn f) :
    dom (posHomGen f) = {0} ∪ ⋃ a > (0 : ℝ), a • dom f := by
  rw [posHomGen_eq_ofEpi hf, dom_ofEpi, posHomGenCone, Set.image_union, Set.image_iUnion₂]
  congr 1
  · exact Set.image_singleton
  · refine Set.iUnion₂_congr fun a _ => ?_
    rw [dom_eq_fst_image_epi]
    ext z
    constructor
    · rintro ⟨-, ⟨q, hq, rfl⟩, rfl⟩
      exact ⟨q.1, ⟨q, hq, rfl⟩, rfl⟩
    · rintro ⟨-, ⟨q, hq, rfl⟩, rfl⟩
      exact ⟨a • q, ⟨q, hq, rfl⟩, rfl⟩

/-- **`hom f` is `posHomGen` applied to the level-one lift.**

This reconciles the two homogenisation operators: Rockafellar's `hom f` on `ℝ × E` is *the*
positively homogeneous convex function generated by the level-one lift of `f`, and the two generated
cones are literally the same set (`posHomGenCone_levelOneLift`). The hypothesis `f ≢ +∞` is
`hom_eq_ofEpi_homCone`'s: for `f ≡ +∞` the cone degenerates to `{0}`, whose `ofEpi` is
`δ(· | 0)`, whereas `hom f ≡ +∞`. -/
theorem posHomGenCone_levelOneLift (f : E → EReal) :
    posHomGenCone (levelOneLift f) = homCone f := rfl

/-- `hom f` is the positively homogeneous convex function generated by the level-one lift of `f`. -/
theorem posHomGen_levelOneLift (hf : ConvexFn f) (hdom : (dom f).Nonempty) :
    posHomGen (levelOneLift f) = hom f := by
  rw [posHomGen_eq_ofEpi (convexFn_levelOneLift hf), posHomGenCone_levelOneLift,
    ← hom_eq_ofEpi_homCone hdom]

end PosHomGen

/-! ### The zero level set of the generated function

Two sublevel sets of `k = posHomGen f` sandwich the convex cone generated by `{x | f x ≤ 0}`:
`{k < 0}` lies inside it and `{k ≤ 0}` contains it, because `(fλ) x ≤ 0` for a positive `λ` says
exactly that `λ⁻¹ x` lies in `{x | f x ≤ 0}`. Both sublevel sets have the same closure, so the
closed convex cone generated by `{x | f x ≤ 0}` is the zero sublevel set of `cl k`. -/

section PosHomGenLevel

section Algebraic

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {f : E → EReal}

/-- **The zero sublevel set of `posHomGen f` is a convex cone**, so it contains the whole cone
generated by `{x | f x ≤ 0}`.

Positive homogeneity together with convexity is subadditivity (Theorem 4.7), which is what closes
the additive step of the induction; the hypothesis `∀ x, posHomGen f x ≠ ⊥` is Theorem 4.7's, and
is supplied by properness of `posHomGen f`. -/
theorem coe_hull_setOf_le_zero_subset (hb : ∀ x, posHomGen f x ≠ ⊥) :
    (PointedCone.hull ℝ {x : E | f x ≤ 0} : Set E) ⊆ {x : E | posHomGen f x ≤ 0} := by
  have hsub := ((posHomogeneous_posHomGen f).convexFn_iff_subadditive hb).1 (convexFn_posHomGen f)
  intro x hx
  induction hx using Submodule.span_induction with
  | mem y hy => exact (posHomGen_le f y).trans hy
  | zero => exact posHomGen_apply_zero_le f
  | add y z _ _ hy hz =>
      have hy' : posHomGen f y ≤ 0 := hy
      have hz' : posHomGen f z ≤ 0 := hz
      exact (hsub y z).trans (by simpa using add_le_add hy' hz')
  | smul c y _ hy =>
      rcases eq_or_lt_of_le c.2 with hc | hc
      · have hzero : (c : ℝ) • y = 0 := by rw [← hc, zero_smul]
        change posHomGen f ((c : ℝ) • y) ≤ 0
        rw [hzero]
        exact posHomGen_apply_zero_le f
      · change posHomGen f ((c : ℝ) • y) ≤ 0
        rw [posHomogeneous_posHomGen f (c : ℝ) hc y]
        calc ((c : ℝ) : EReal) * posHomGen f y
            ≤ ((c : ℝ) : EReal) * 0 := mul_le_mul_of_nonneg_left hy (by exact_mod_cast c.2)
          _ = 0 := mul_zero _

/-- **Where `posHomGen f` is negative, the point already lies on a ray through `{x | f x ≤ 0}`.**

This is Rockafellar's step "`(fλ) x ≤ 0` for a positive `λ` if and only if `λ⁻¹ x` lies in
`{y | f y ≤ 0}`", in the direction that needs the infimum formula for `posHomGen`. The origin is
excluded from the hypothesis by `f 0 ≥ 0`, which forces `posHomGen f 0 = 0`. -/
theorem setOf_posHomGen_lt_zero_subset (hf : ConvexFn f) (h0 : 0 ≤ f 0) :
    {x : E | posHomGen f x < 0} ⊆ (PointedCone.hull ℝ {x : E | f x ≤ 0} : Set E) := by
  intro x hx
  have hxne : x ≠ 0 := by
    rintro rfl
    rw [Set.mem_ofPred, posHomGen_apply_zero_of_nonneg hf h0] at hx
    exact absurd hx (lt_irrefl 0)
  rw [Set.mem_ofPred, posHomGen_apply_of_ne_zero hf hxne] at hx
  obtain ⟨a, ha⟩ := iInf_lt_iff.1 hx
  obtain ⟨hapos, ha'⟩ := iInf_lt_iff.1 ha
  have hz : f (a⁻¹ • x) ≤ 0 := by
    by_contra hcon
    rw [not_le] at hcon
    have hnn : (0 : EReal) ≤ (a : EReal) * f (a⁻¹ • x) := by
      have h := mul_le_mul_of_nonneg_left hcon.le (a := ((a : ℝ) : EReal))
        (by exact_mod_cast hapos.le)
      rwa [mul_zero] at h
    exact absurd ha' (not_lt.2 hnn)
  have hmem : a • (a⁻¹ • x) ∈ PointedCone.hull ℝ {y : E | f y ≤ 0} :=
    Submodule.smul_mem _ (⟨a, hapos.le⟩ : {c : ℝ // 0 ≤ c}) (PointedCone.subset_hull hz)
  rwa [smul_inv_smul₀ hapos.ne'] at hmem

end Algebraic

section FiniteDim

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  {f : E → EReal}

/-- **The closed convex cone generated by `{x | f x ≤ 0}` is the zero sublevel set of `cl k`**,
where `k = posHomGen f` is the positively homogeneous convex function generated by `f`.

This is the geometric identity behind **Rockafellar, Theorem 14.3**. The two sublevel sets
`{k < 0}` and `{k ≤ 0}` sandwich the convex cone generated by `{x | f x ≤ 0}`
(`setOf_posHomGen_lt_zero_subset`, `coe_hull_setOf_le_zero_subset`), and Theorem 7.6 says that both
have closure `{x | (cl k) x ≤ 0}`; that theorem needs `k` proper convex with `inf k < 0`, which is
where `f 0 > 0` (through `proper_posHomGen`) and `inf f < 0` are used.

Finite dimension enters only through those two citations. -/
theorem setOf_clFn_posHomGen_le_zero (hf : ClosedProperConvexFn f) (h0 : 0 < f 0)
    (hinf : ⨅ x, f x < 0) :
    {x : E | clFn (posHomGen f) x ≤ 0}
      = closure (PointedCone.hull ℝ {x : E | f x ≤ 0} : Set E) := by
  have hkp : Proper (posHomGen f) := proper_posHomGen hf.convex hf.proper hf.isClosed_epi h0
  have hkc : ConvexFn (posHomGen f) := convexFn_posHomGen f
  obtain ⟨x₀, hx₀⟩ := iInf_lt_iff.1 hinf
  have hkinf : ⨅ x, posHomGen f x < ((0 : ℝ) : EReal) := by
    rw [_root_.EReal.coe_zero]
    exact lt_of_le_of_lt ((iInf_le _ x₀).trans (posHomGen_le f x₀)) hx₀
  have hle := hkc.closure_setOf_le_clFn hkp hkinf
  have hlt := hkc.closure_setOf_lt_eq hkinf
  simp only [_root_.EReal.coe_zero] at hle hlt
  refine subset_antisymm ?_ ?_
  · rw [← hle, ← hlt]
    exact closure_mono (setOf_posHomGen_lt_zero_subset hf.convex h0.le)
  · rw [← hle]
    exact closure_mono (coe_hull_setOf_le_zero_subset hkp.ne_bot)

end FiniteDim

end PosHomGenLevel

/-! ### The conjugate of a generated positively homogeneous function

This is the layer-A core of Theorem 13.5, and it needs no topology: `posHomGen f` is positively
homogeneous, so its conjugate is an indicator function (`conj_eq_indicatorFn_of_posHomogeneous`),
and the set it indicates is unchanged by the passage from `f` to `posHomGen f`. -/

section Conj

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]

/-- A linear functional read off a pairing is positively homogeneous. -/
theorem posHomogeneous_pairing (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (y : F) :
    PosHomogeneous fun x => ((B x y : ℝ) : EReal) := by
  intro a ha x
  simp only [map_smul, LinearMap.smul_apply, smul_eq_mul]
  exact (Tdaf.EReal.coe_mul_coe _ _).symm

/-- A linear functional read off a pairing is convex. -/
theorem convexFn_pairing (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (y : F) :
    ConvexFn fun x => ((B x y : ℝ) : EReal) := by
  have h : (fun x => ((B x y : ℝ) : EReal)) = affineFn B y 0 := by
    funext x
    rw [affineFn_apply, _root_.EReal.coe_zero, sub_zero]
  rw [h]
  exact convexFn_affineFn y 0

/-- **Homogenising does not change the support set**: `⟨·, y⟩ ≤ posHomGen f` if and only if
`⟨·, y⟩ ≤ f`.

`⊆` is `posHomGen f ≤ f`; `⊇` is the maximality property applied to the linear function `⟨·, y⟩`,
which is positively homogeneous and vanishes at the origin. No hypothesis on `f`. -/
theorem supportSet_posHomGen (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (f : E → EReal) :
    supportSet B (posHomGen f) = supportSet B f := by
  ext y
  refine ⟨fun hy x => (hy x).trans (posHomGen_le f x), fun hy => ?_⟩
  exact le_posHomGen (posHomogeneous_pairing B y) (convexFn_pairing B y) (by simp) hy

/-- **The conjugate of the positively homogeneous convex function generated by `f`** is the
indicator of the set on which `f*` is nonpositive.

This is the layer-A core of Rockafellar's Theorem 13.5, and it is the form Theorem 21.3 consumes
("the conjugate of `k` is the indicator function of the convex set `{x | h*(x) ≤ 0}`"). It carries
**no hypothesis at all** — neither closedness, nor properness, nor convexity of `f` — because
`posHomGen f` is positively homogeneous and nonpositive at the origin whatever `f` is. -/
theorem conj_posHomGen (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (f : E → EReal) :
    conj B (posHomGen f) = indicatorFn {y : F | conj B f y ≤ 0} := by
  rw [conj_eq_indicatorFn_of_posHomogeneous (posHomogeneous_posHomGen f)
      ⟨0, posHomGen_apply_zero_ne_top f⟩, supportSet_posHomGen, supportSet_eq_setOf_conj_le]

/-- Homogenising does not change the conjugate's zero sublevel set: `(posHomGen f)*` and `f*` are
nonpositive on exactly the same vectors. -/
theorem setOf_conj_posHomGen_le_zero (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (f : E → EReal) :
    {y : F | conj B (posHomGen f) y ≤ 0} = {y : F | conj B f y ≤ 0} := by
  rw [← supportSet_eq_setOf_conj_le, ← supportSet_eq_setOf_conj_le, supportSet_posHomGen]

/-- **The conjugate at the origin is minus the infimum**: `f*(0) = -inf f`.

The pairing contributes nothing at the origin, so the supremum defining `f*` collapses to
`sup (-f)`. No hypothesis on `f`. -/
theorem conj_apply_zero (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (f : E → EReal) :
    conj B f 0 = -⨅ x, f x := by
  rw [conj_apply, Tdaf.EReal.neg_iInf]
  refine iSup_congr fun x => ?_
  rw [map_zero (B x), _root_.EReal.coe_zero]
  exact zero_add _

end Conj

section ConjZero

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  [TopologicalSpace E] [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [LocallyConvexSpace ℝ E]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} [IsCompatiblePairing B] {f : E → EReal}

/-- **The infimum of the conjugate is minus the value at the origin**: `inf f* = -f(0)`, for a
closed convex `f`.

This is `conj_apply_zero` applied to `f*` and read back through Fenchel–Moreau. With
`conj_apply_zero` it is the pair of identities Rockafellar opens the proof of Theorem 14.3 with,
and together they say that the hypothesis `f 0 > 0 > inf f` is self-dual. -/
theorem iInf_conj_eq_neg_apply_zero (hf : ConvexFn f) (hc : ClosedFn f) :
    ⨅ y, conj B f y = -f 0 := by
  have h : conj B.flip (conj B f) 0 = -⨅ y, conj B f y := conj_apply_zero B.flip (conj B f)
  rw [show conj B.flip (conj B f) = biconj B f from rfl, biconj_eq_self hf hc] at h
  rw [h, neg_neg]

end ConjZero

/-! ### Theorem 13.5

Only the space the *function* lives on carries a topology: this is Corollary 13.2.1 applied to
`posHomGen`, and the level set produced is a subset of the other space. -/

section Theorem135

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  [TopologicalSpace F] [IsTopologicalAddGroup F] [ContinuousSMul ℝ F] [LocallyConvexSpace ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} [IsCompatiblePairing B.flip] {g : F → EReal}

/-- **Rockafellar, Theorem 13.5**, second assertion: the closure of the positively homogeneous
convex function `k` generated by `g` is the support function of `{x | g*(x) ≤ 0}`.

**No hypothesis at all**: `posHomGen g` is positively homogeneous, convex and nonpositive at the
origin whatever `g` is, so Corollary 13.2.1 (`clFn_eq_supportFn_of_posHomogeneous`) applies
directly. Even convexity of `g` is unnecessary — the improper cases are already carried by that
corollary: if `g` takes `-∞` then `cl (posHomGen g) ≡ -∞`, the level set is empty, and both sides
are the support function of `∅`. -/
theorem clFn_posHomGen (g : F → EReal) :
    clFn (posHomGen g) = supportFn B {x : E | conj B.flip g x ≤ 0} := by
  rw [clFn_eq_supportFn_of_posHomogeneous (B := B) (posHomogeneous_posHomGen g)
      (convexFn_posHomGen g) ⟨0, posHomGen_apply_zero_ne_top g⟩, supportSet_posHomGen,
    supportSet_eq_setOf_conj_le]

/-- **Rockafellar, Theorem 13.5**, second assertion, in the form that identifies the support
function outright: if in addition `posHomGen g` is closed, it *is* the support function of
`{x | g*(x) ≤ 0}`. -/
theorem supportFn_setOf_conj_le_zero (hcl : ClosedFn (posHomGen g)) :
    supportFn B {x : E | conj B.flip g x ≤ 0} = posHomGen g :=
  (clFn_posHomGen g).symm.trans hcl

end Theorem135

section Theorem135First

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  [TopologicalSpace E] [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [LocallyConvexSpace ℝ E]
  [TopologicalSpace F] [IsTopologicalAddGroup F] [ContinuousSMul ℝ F] [LocallyConvexSpace ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} [IsCompatiblePairing B] [IsCompatiblePairing B.flip] {f : E → EReal}

/-- **Rockafellar, Theorem 13.5**, first assertion: the support function of the level set
`{x | f x ≤ 0}` of a closed convex function is the closure of the positively homogeneous convex
function generated by `f*`.

This is the second assertion applied to `f*` together with Fenchel–Moreau, which is where
closedness of `f` enters: it is what turns `{x | f**(x) ≤ 0}` back into `{x | f(x) ≤ 0}`.
Rockafellar states the theorem for closed *proper* convex `f`; properness is not needed here,
since Fenchel–Moreau in the form `biconj_eq_self` covers the improper cases too. -/
theorem supportFn_setOf_le_zero (hf : ConvexFn f) (hc : ClosedFn f) :
    supportFn B {x : E | f x ≤ 0} = clFn (posHomGen (conj B f)) := by
  have hset : {x : E | conj B.flip (conj B f) x ≤ 0} = {x : E | f x ≤ 0} := by
    rw [show conj B.flip (conj B f) = biconj B f from rfl, biconj_eq_self hf hc]
  rw [clFn_posHomGen (B := B) (conj B f), hset]

end Theorem135First

/-! ### Corollary 13.5.1

Theorem 13.5 applied to the level-one lift of `f`, paired against `ℝ × F` by
`⟨(λ, x), (λ*, x*)⟩ = λ λ* + ⟨x, x*⟩`. The `ℝ` factor is paired with itself by multiplication,
which is `innerₗ ℝ`; that is the only compatible pairing of `ℝ` with `ℝ` up to a positive
scalar, and it is the one the book's `λ λ*` means. -/

section Corollary1351

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  [TopologicalSpace E] [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [LocallyConvexSpace ℝ E]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} [IsCompatiblePairing B] {f : E → EReal}

omit [TopologicalSpace E] [IsTopologicalAddGroup E] [ContinuousSMul ℝ E]
  [LocallyConvexSpace ℝ E] [IsCompatiblePairing B] in
/-- The conjugate of the level-one lift is nonpositive at `(λ*, x*)` exactly when
`f*(x*) ≤ -λ*`.

This is Rockafellar's computation `h*(λ*, x*) = λ* + f*(x*)` in the proof of Corollary 13.5.1, in
the only form that proof uses — and stating it as a sublevel-set condition rather than as an
equation keeps it clear of `EReal`'s `⊤ + ⊥`. -/
theorem conj_levelOneLift_le_zero_iff (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (f : E → EReal) (q : ℝ × F) :
    conj (prodPairing (innerₗ ℝ) B) (levelOneLift f) q ≤ 0 ↔
      conj B f q.2 ≤ ((-q.1 : ℝ) : EReal) := by
  have hcoef : ∀ p : ℝ × E, p.1 = 1 →
      affineFn (prodPairing (innerₗ ℝ) B) q 0 p = affineFn B q.2 (-q.1) p.2 := by
    intro p hp
    rw [affineFn_apply, affineFn_apply, ← _root_.EReal.coe_sub, ← _root_.EReal.coe_sub]
    congr 1
    simp only [prodPairing_apply, sub_zero, sub_neg_eq_add, hp]
    have h1 : innerₗ ℝ (1 : ℝ) q.1 = q.1 := by simp
    rw [h1, add_comm]
  rw [show ((0 : EReal)) = ((0 : ℝ) : EReal) from _root_.EReal.coe_zero.symm, conj_le_coe_iff,
    conj_le_coe_iff, Pi.le_def, Pi.le_def]
  constructor
  · intro h x
    have hx := h ((1 : ℝ), x)
    rwa [hcoef ((1 : ℝ), x) rfl, levelOneLift_apply_one] at hx
  · intro h p
    by_cases hp : p.1 = 1
    · rw [hcoef p hp, levelOneLift_of_fst_eq_one hp]
      exact h p.2
    · rw [levelOneLift_of_fst_ne_one hp]
      exact le_top

/-- **Rockafellar, Corollary 13.5.1**: the closure of the homogenisation `hom f` is the support
function of `{(λ*, x*) | λ* ≤ -f*(x*)}`.

Rockafellar states the conclusion for the explicit function `k (λ, x) = (fλ) x` for `λ > 0`,
`(f 0⁺) x` for `λ = 0`, `+∞` for `λ < 0`; identifying that `k` with `cl (hom f)` is Corollary
8.5.2 and belongs to §8, so it is left out here. As always, `f ≢ +∞` is the hypothesis that
`hom f` is the function generated by the level-one lift. -/
theorem clFn_hom (hf : ConvexFn f) (hdom : (dom f).Nonempty) :
    clFn (hom f) = supportFn (prodPairing (innerₗ ℝ) B).flip
      {q : ℝ × F | conj B f q.2 ≤ ((-q.1 : ℝ) : EReal)} := by
  rw [← posHomGen_levelOneLift hf hdom,
    clFn_posHomGen (B := (prodPairing (innerₗ ℝ) B).flip) (levelOneLift f)]
  refine congrArg (supportFn (prodPairing (innerₗ ℝ) B).flip) (Set.ext fun q => ?_)
  simp only [Set.mem_ofPred_eq, LinearMap.flip_flip]
  exact conj_levelOneLift_le_zero_iff B f q

end Corollary1351

/-! ### Theorem 13.4

The *lineality space of a function* (`linealitySpaceFn`) is the set of directions in which its
recession function is additively reversible — Rockafellar's directions of affineness. It is
strictly larger than the *constancy space* (`constancySpace`), which asks the recession function to
vanish in both directions, and it is the lineality space that Theorem 13.4 is about. -/

section Theorem134

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} {f : E → EReal}

/-- **Rockafellar, Theorem 13.4**, unfolded: `y` is a direction of affineness of `f*` exactly when
`⟨·, y⟩` is constant on `dom f`. -/
theorem mem_linealitySpaceFn_conj_iff (hp : Proper f) (hc : Proper (conj B f)) {y : F} :
    y ∈ linealitySpaceFn (conj B f) ↔ ∃ c : ℝ, ∀ x ∈ dom f, B x y = c := by
  rw [mem_linealitySpaceFn, recessionFn_conj hp hc]
  exact supportFn_neg_eq_neg_iff hp.dom_nonempty y

/-- **Rockafellar, Theorem 13.4**, in the "constant on `dom f`" form. -/
theorem linealitySpaceFn_conj (hp : Proper f) (hc : Proper (conj B f)) :
    linealitySpaceFn (conj B f) = {y : F | ∀ x₁ ∈ dom f, ∀ x₂ ∈ dom f, B x₁ y = B x₂ y} := by
  ext y
  rw [mem_linealitySpaceFn_conj_iff hp hc]
  refine ⟨fun ⟨c, hc'⟩ x₁ h₁ x₂ h₂ => by rw [hc' x₁ h₁, hc' x₂ h₂], fun h => ?_⟩
  obtain ⟨x₀, hx₀⟩ := hp.dom_nonempty
  exact ⟨B x₀ y, fun x hx => h x hx x₀ hx₀⟩

/-- **Rockafellar, Theorem 13.4**: the lineality space of `f*` is the annihilator of the subspace
parallel to `aff (dom f)`.

`vectorSpan ℝ (dom f)` *is* that subspace: `direction_affineSpan` identifies it with
`(affineSpan ℝ (dom f)).direction`. In an inner-product space the annihilator is the orthogonal
complement, which is the book's phrasing. -/
theorem linealitySpaceFn_conj_eq_annihilator (hp : Proper f) (hc : Proper (conj B f)) :
    linealitySpaceFn (conj B f) = {y : F | ∀ v ∈ vectorSpan ℝ (dom f), B v y = 0} := by
  rw [linealitySpaceFn_conj hp hc]
  ext y
  constructor
  · intro h v hv
    have hle : vectorSpan ℝ (dom f) ≤ LinearMap.ker (B.flip y) := by
      rw [vectorSpan_def, Submodule.span_le]
      intro w hw
      obtain ⟨x₁, hx₁, x₂, hx₂, rfl⟩ := Set.mem_vsub.1 hw
      have hzero : B (x₁ - x₂) y = 0 := by
        rw [map_sub, LinearMap.sub_apply, h x₁ hx₁ x₂ hx₂, sub_self]
      simpa [vsub_eq_sub] using hzero
    exact hle hv
  · intro h x₁ h₁ x₂ h₂
    have hv : x₁ - x₂ ∈ vectorSpan ℝ (dom f) := by
      have hm := vsub_mem_vectorSpan ℝ h₁ h₂
      rwa [vsub_eq_sub] at hm
    have hz := h _ hv
    rw [map_sub, LinearMap.sub_apply] at hz
    linarith

end Theorem134

section Theorem134Dual

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  [TopologicalSpace E] [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [LocallyConvexSpace ℝ E]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} [IsCompatiblePairing B] {f : E → EReal}

/-- **Rockafellar, Theorem 13.4**, second assertion: for a closed proper convex `f`, the lineality
space of `f` itself is the annihilator of the subspace parallel to `aff (dom f*)`.

This is the first assertion applied to `f*`, with Fenchel–Moreau turning `f**` back into `f`. -/
theorem linealitySpaceFn_eq_annihilator_dom_conj (hf : ClosedProperConvexFn f) :
    linealitySpaceFn f = {x : E | ∀ w ∈ vectorSpan ℝ (dom (conj B f)), B x w = 0} := by
  have hcp : Proper (conj B f) := proper_conj hf
  have hbi : conj B.flip (conj B f) = f := biconj_eq_self hf.convex hf.closed
  have h := linealitySpaceFn_conj_eq_annihilator (B := B.flip) hcp
    (by rw [hbi]; exact hf.proper)
  rw [hbi] at h
  rw [h]
  ext x
  exact forall₂_congr fun w _ => Iff.rfl

end Theorem134Dual

/-! ### Co-finiteness and Corollary 13.3.1 -/

section Cofinite

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  [TopologicalSpace E] [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [LocallyConvexSpace ℝ E]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} {f : E → EReal}

/-- **Rockafellar's co-finite convex functions** (§13): closed proper convex functions whose
epigraph contains no non-vertical half-line, i.e. whose recession function is `+∞` in every
nonzero direction.

Corollary 13.3.1 identifies them as exactly the functions with an everywhere-finite conjugate. -/
structure Cofinite (f : E → EReal) : Prop extends ClosedProperConvexFn f where
  /-- The recession function is `+∞` in every direction but `0`. -/
  recessionFn_eq_top : ∀ y : E, y ≠ 0 → recessionFn f y = ⊤

/-- **Rockafellar, Theorem 13.3**, second assertion: for a closed proper convex `f`, the recession
function of `f` is the support function of `dom f*`.

This is `recessionFn_conj` applied to `f*`, with Fenchel–Moreau turning `f**` back into `f`. -/
theorem recessionFn_eq_supportFn_dom_conj [IsCompatiblePairing B]
    (hf : ClosedProperConvexFn f) :
    recessionFn f = supportFn B.flip (dom (conj B f)) := by
  have hcp : Proper (conj B f) := proper_conj hf
  have hbi : conj B.flip (conj B f) = f := biconj_eq_self hf.convex hf.closed
  have h := recessionFn_conj (B := B.flip) (f := conj B f) hcp (by rw [hbi]; exact hf.proper)
  rwa [hbi] at h

end Cofinite

section CofiniteMain

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  [TopologicalSpace E] [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [LocallyConvexSpace ℝ E]
  [TopologicalSpace F] [IsTopologicalAddGroup F] [ContinuousSMul ℝ F] [LocallyConvexSpace ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} [IsCompatiblePairing B] [IsCompatiblePairing B.flip] {f : E → EReal}

omit [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [LocallyConvexSpace ℝ E]
  [TopologicalSpace F] [IsTopologicalAddGroup F] [ContinuousSMul ℝ F] [LocallyConvexSpace ℝ F]
  [IsCompatiblePairing B.flip] in
/-- The support function of the *whole* dual space is `+∞` in every nonzero direction — provided
the pairing separates the points of `E`, which is what `SeparatingDual ℝ E` plus compatibility
gives.

The hypothesis is not decoration: for `E` with the indiscrete topology, `StrongDual ℝ E = 0`, the
pairing with `F = 0` is compatible, and every support function vanishes identically. Rockafellar
never writes it because `ℝⁿ` is Hausdorff. -/
theorem supportFn_univ_of_ne_zero [SeparatingDual ℝ E] {y : E} (hy : y ≠ 0) :
    supportFn B.flip (univ : Set F) y = ⊤ := by
  by_contra hne
  obtain ⟨c, hc⟩ := supportFn_lt_top_iff.1 (lt_top_iff_ne_top.2 hne)
  obtain ⟨g, hg⟩ := SeparatingDual.exists_ne_zero (R := ℝ) hy
  obtain ⟨w, hw⟩ := exists_pairing_eq B g
  have hBw : B y w ≠ 0 := by rw [← hw y]; exact hg
  have hstep : B y (((c + 1) / B y w) • w) ≤ c := hc _ (mem_univ _)
  rw [map_smul, smul_eq_mul, div_mul_cancel₀ _ hBw] at hstep
  linarith

omit [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [LocallyConvexSpace ℝ E]
  [TopologicalSpace F] [IsTopologicalAddGroup F] [ContinuousSMul ℝ F] [LocallyConvexSpace ℝ F]
  [IsCompatiblePairing B.flip] in
/-- **The conjugate of the constant function `0` is `δ(· | 0)`.** This is the other half of
Rockafellar's one-sentence proof of Theorem 16.1 at `λ = 0`; `conj_indicatorFn_zero`
(`Duality/Ops.lean`) is the half that runs the other way.

It carries the same separation hypothesis as `supportFn_univ_of_ne_zero`, and for the same reason:
`0` is the indicator of the whole space, so its conjugate is the support function of the whole
space, which is `+∞` away from the origin exactly when the pairing separates points. -/
theorem conj_zero_eq_indicatorFn [SeparatingDual ℝ E] :
    conj B.flip (0 : F → EReal) = indicatorFn ({0} : Set E) := by
  have hzero : (0 : F → EReal) = indicatorFn (univ : Set F) := by
    funext x
    rw [indicatorFn_of_mem (mem_univ x)]
    rfl
  rw [hzero, ← supportFn_eq_conj_indicatorFn]
  funext y
  by_cases hy : y = 0
  · subst hy
    rw [indicatorFn_of_mem (Set.mem_singleton _), supportFn_zero ⟨0, mem_univ 0⟩]
  · rw [indicatorFn_of_notMem (by simpa using hy), supportFn_univ_of_ne_zero (B := B) hy]

/-- **Rockafellar, Corollary 13.3.1**, in the form that survives infinite dimensions: `dom f*` is
*dense* if and only if `f` is co-finite.

The book's statement is `dom f* = ℝⁿ`, and it is genuinely stronger than density outside finite
dimensions: the kernel of a discontinuous linear functional is a dense proper convex subset on
which no nonzero continuous linear functional is bounded above (gotcha: Corollary 11.5.2 needs
`closure C ≠ univ`, not `C ≠ univ`). `dom_conj_eq_univ_iff` restores the book's form under
`FiniteDimensional ℝ F`. -/
theorem closure_dom_conj_eq_univ_iff [SeparatingDual ℝ E] (hf : ClosedProperConvexFn f) :
    closure (dom (conj B f)) = univ ↔ ∀ y : E, y ≠ 0 → recessionFn f y = ⊤ := by
  have hrec := recessionFn_eq_supportFn_dom_conj (B := B) hf
  constructor
  · intro h y hy
    have := congrFun hrec y
    rw [this, ← supportFn_closure (B := B.flip) (dom (conj B f)), h]
    exact supportFn_univ_of_ne_zero (B := B) hy
  · intro h
    by_contra hcl
    obtain ⟨φ, c, hφ, hbnd⟩ := exists_ne_zero_forall_le_of_closure_ne_univ
      (convexFn_conj B f).convex_dom (proper_conj hf).dom_nonempty hcl
    obtain ⟨y, hy⟩ := exists_pairing_eq B.flip φ
    have hy0 : y ≠ 0 := by
      rintro rfl
      refine hφ (ContinuousLinearMap.ext fun w => ?_)
      simp [hy w]
    have hle : recessionFn f y ≤ (c : EReal) := by
      rw [congrFun hrec y, supportFn_le_coe_iff]
      exact fun w hw => (hy w).symm ▸ hbnd w hw
    rw [h y hy0] at hle
    exact absurd hle (by simp)

omit [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [LocallyConvexSpace ℝ E]
  [TopologicalSpace F] [IsTopologicalAddGroup F] [ContinuousSMul ℝ F] [LocallyConvexSpace ℝ F]
  [IsCompatiblePairing B.flip] in
/-- **A compatible pairing whose left space has a separating dual separates the points of that
space**: if `⟨x, y⟩ = 0` for every `y`, then every continuous linear functional kills `x`.

This replaces Rockafellar's identification of `Rⁿ` with its dual wherever a statement quantifies
over the *nonzero* vectors of `E`, as the interior clause of Theorem 13.1 does. -/
theorem separatingRight_flip_of_separatingDual (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) [IsCompatiblePairing B]
    [SeparatingDual ℝ E] : B.flip.SeparatingRight := by
  intro x hx
  by_contra hne
  obtain ⟨g, hg⟩ := SeparatingDual.exists_ne_zero (R := ℝ) hne
  obtain ⟨y, hy⟩ := exists_pairing_eq B g
  exact hg (by rw [hy x]; simpa using hx y)

/-! ### Corollary 13.3.4

Where a point `y₀` sits relative to `dom f*` — in its closure, its relative interior, its interior
or its affine hull — is decided by the recession function of `f`, through Theorem 13.1 applied to
`dom f*` and Theorem 13.3 identifying its support function as `f 0⁺`.

Rockafellar states the four clauses for the translated function `g = f - ⟨·, y₀⟩`, whose recession
function is `g 0⁺ = f 0⁺ - ⟨·, y₀⟩`; "`(g 0⁺)(y) ≥ 0`" and "`⟨y, y₀⟩ ≤ (f 0⁺)(y)`" are the same
inequality, and the translation is what the statements below avoid having to name. -/

/-- **Rockafellar, Corollary 13.3.4(a)**: `y₀` lies in the closure of `dom f*` exactly when the
recession function of `f` dominates the linear function `⟨·, y₀⟩`. -/
theorem mem_closure_dom_conj_iff (hf : ClosedProperConvexFn f) (y₀ : F) :
    y₀ ∈ closure (dom (conj B f)) ↔ ∀ y : E, ((B y y₀ : ℝ) : EReal) ≤ recessionFn f y := by
  have hconv : Convex ℝ (dom (conj B f)) := (convexFn_conj B f).convex_dom
  rw [← hconv.convexHull_eq, mem_closure_convexHull_iff_le_supportFn (B := B.flip)]
  simp only [LinearMap.flip_apply, ← recessionFn_eq_supportFn_dom_conj (B := B) hf]

/-- **Rockafellar, Corollary 13.3.4(a)** at the origin — the first sentence of **Theorem 27.1(i)**:
the origin lies in the closure of `dom f*` exactly when `f` recedes nowhere at a negative rate. -/
theorem zero_mem_closure_dom_conj_iff (hf : ClosedProperConvexFn f) :
    (0 : F) ∈ closure (dom (conj B f)) ↔ ∀ y : E, 0 ≤ recessionFn f y := by
  rw [mem_closure_dom_conj_iff (B := B) hf]
  simp

omit [TopologicalSpace E] [IsTopologicalAddGroup E] [ContinuousSMul ℝ E]
  [LocallyConvexSpace ℝ E] in
/-- The recession bound `f 0⁺ y ≤ -ε` written out: `f` decreases at rate at least `ε` along `y`.

This is `recessionFn_le_coe_iff_forall` — Theorem 8.5 through Theorem 8.1's `a = 1` test — with the
sign moved onto the right-hand side and `x` restricted to `dom f`. The restriction is free: off
`dom f` the right-hand side is `⊤ - ε = ⊤`. -/
theorem recessionFn_le_neg_coe_iff (f : E → EReal) (y : E) (ε : ℝ) :
    recessionFn f y ≤ ((-ε : ℝ) : EReal) ↔
      ∀ x ∈ dom f, ∀ a : ℝ, 0 ≤ a → f (x + a • y) ≤ f x - ((a * ε : ℝ) : EReal) := by
  have hrw : ∀ (x : E) (a : ℝ), (f x + ((a * -ε : ℝ) : EReal))
      = f x - ((a * ε : ℝ) : EReal) := fun x a => by
    rw [show (a * -ε : ℝ) = -(a * ε) from by ring, _root_.EReal.coe_neg, ← sub_eq_add_neg]
  rw [recessionFn_le_coe_iff_forall]
  refine ⟨fun h x _ a ha => (hrw x a) ▸ h x a ha, fun h x a ha => (hrw x a).symm ▸ ?_⟩
  rcases eq_or_ne (f x) ⊤ with hx | hx
  · rw [hx, _root_.EReal.top_sub_coe]
    exact le_top
  · exact h x (mem_dom.2 (lt_top_iff_ne_top.2 hx)) a ha

/-- **Rockafellar, Theorem 27.1(i)**, second sentence: the origin lies *outside* the closure of
`dom f*` exactly when `f` decreases at a uniform positive rate along some direction.

It is the first sentence with the quantifier negated, once `recessionFn_le_neg_coe_iff` spells out
what a negative recession value means. Two remarks the book does not make: `y ≠ 0` is automatic
here, because at `y = 0` the inequality at `a = 1` would read `0 ≤ -ε` at any point of the
(non-empty) effective domain; and restricting `x` to `dom f` costs nothing. -/
theorem zero_notMem_closure_dom_conj_iff (hf : ClosedProperConvexFn f) :
    (0 : F) ∉ closure (dom (conj B f)) ↔
      ∃ y : E, y ≠ 0 ∧ ∃ ε : ℝ, 0 < ε ∧
        ∀ x ∈ dom f, ∀ a : ℝ, 0 ≤ a → f (x + a • y) ≤ f x - ((a * ε : ℝ) : EReal) := by
  rw [zero_mem_closure_dom_conj_iff (B := B) hf, not_forall]
  constructor
  · rintro ⟨y, hy⟩
    rw [not_le] at hy
    obtain ⟨m, hm₁, hm₂⟩ := _root_.EReal.lt_iff_exists_real_btwn.1 hy
    have hmneg : m < 0 := by exact_mod_cast hm₂
    refine ⟨y, ?_, -m, neg_pos.2 hmneg, (recessionFn_le_neg_coe_iff f y (-m)).1 ?_⟩
    · rintro rfl
      rw [recessionFn_apply_zero hf.proper] at hy
      exact absurd hy (lt_irrefl 0)
    · rw [neg_neg]
      exact hm₁.le
  · rintro ⟨y, -, ε, hε, hineq⟩
    refine ⟨y, not_le.2 (lt_of_le_of_lt ((recessionFn_le_neg_coe_iff f y ε).2 hineq) ?_)⟩
    exact_mod_cast neg_lt_zero.2 hε

end CofiniteMain

section CofiniteFiniteDim

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [TopologicalSpace E]
  [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [LocallyConvexSpace ℝ E] [SeparatingDual ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F] [FiniteDimensional ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} [IsCompatiblePairing B] [IsCompatiblePairing B.flip] {f : E → EReal}
  {D : Set F}

omit [TopologicalSpace E] [IsTopologicalAddGroup E] [ContinuousSMul ℝ E] [LocallyConvexSpace ℝ E]
  [SeparatingDual ℝ E] [IsCompatiblePairing B] [IsCompatiblePairing B.flip] in
/-- In finite dimensions a dense convex set is everything: this is Theorem 6.3 (`ri (cl C) = ri C`)
together with `ri univ = univ`. It is what upgrades `closure_dom_conj_eq_univ_iff` to the book's
statement of Corollary 13.3.1. -/
theorem Convex.eq_univ_of_closure_eq_univ (hD : Convex ℝ D) (h : closure D = univ) : D = univ := by
  have h1 : ri (closure D) = ri D := Convex.relint_closure hD
  rw [h, intrinsicInterior_univ] at h1
  exact univ_subset_iff.1 (h1 ▸ intrinsicInterior_subset)

/-- **Rockafellar, Corollary 13.3.1**: for a closed proper convex `f`, the conjugate `f*` is finite
everywhere if and only if `f` is co-finite. -/
theorem dom_conj_eq_univ_iff (hf : ClosedProperConvexFn f) :
    dom (conj B f) = univ ↔ ∀ y : E, y ≠ 0 → recessionFn f y = ⊤ := by
  rw [← closure_dom_conj_eq_univ_iff (B := B) hf]
  exact ⟨fun h => by rw [h, closure_univ],
    Convex.eq_univ_of_closure_eq_univ (convexFn_conj B f).convex_dom⟩

/-- **Rockafellar, Corollary 13.3.1**, stated through `Cofinite`. -/
theorem cofinite_iff_dom_conj_eq_univ (hf : ClosedProperConvexFn f) :
    Cofinite f ↔ dom (conj B f) = univ := by
  rw [dom_conj_eq_univ_iff (B := B) hf]
  exact ⟨fun h => h.recessionFn_eq_top, fun h => { hf with recessionFn_eq_top := h }⟩

/-- **Rockafellar, Corollary 13.3.1**, in the "finite everywhere" phrasing. -/
theorem cofinite_iff_forall_conj_lt_top (hf : ClosedProperConvexFn f) :
    Cofinite f ↔ ∀ y : F, conj B f y < ⊤ := by
  rw [cofinite_iff_dom_conj_eq_univ (B := B) hf]
  exact ⟨fun h y => by rw [← mem_dom, h]; trivial, fun h => eq_univ_of_forall fun y => h y⟩

omit [SeparatingDual ℝ E] in
/-- **Rockafellar, Corollary 13.3.4(b)**: `y₀` lies in the *relative* interior of `dom f*` exactly
when the recession function of `f` dominates `⟨·, y₀⟩`, strictly in every direction in which it is
not additively reversible.

The exceptional directions — those with `-(f 0⁺)(-y) = (f 0⁺)(y)` — are the ones along which
`dom f*` lies in a hyperplane; the book records them as the `y` with
`-(g 0⁺)(-y) = (g 0⁺)(y) = 0`, which is the same condition once the inequality at `-y` is used. -/
theorem mem_relint_dom_conj_iff (hf : ClosedProperConvexFn f) (y₀ : F) :
    y₀ ∈ ri (dom (conj B f)) ↔ (∀ y : E, ((B y y₀ : ℝ) : EReal) ≤ recessionFn f y) ∧
      ∀ y : E, -recessionFn f (-y) ≠ recessionFn f y →
        ((B y y₀ : ℝ) : EReal) < recessionFn f y := by
  have hconv : Convex ℝ (dom (conj B f)) := (convexFn_conj B f).convex_dom
  rw [mem_relint_iff_lt_supportFn (B := B.flip) hconv y₀]
  simp only [LinearMap.flip_apply, ← recessionFn_eq_supportFn_dom_conj (B := B) hf]

/-- **Rockafellar, Corollary 13.3.4(c)**: `y₀` lies in the interior of `dom f*` exactly when the
recession function of `f` strictly dominates `⟨·, y₀⟩` in every nonzero direction. -/
theorem mem_interior_dom_conj_iff (hf : ClosedProperConvexFn f) (y₀ : F) :
    y₀ ∈ interior (dom (conj B f)) ↔
      ∀ y : E, y ≠ 0 → ((B y y₀ : ℝ) : EReal) < recessionFn f y := by
  have hconv : Convex ℝ (dom (conj B f)) := (convexFn_conj B f).convex_dom
  rw [mem_interior_iff_lt_supportFn (B := B.flip) hconv (proper_conj hf).dom_nonempty
    (separatingRight_flip_of_separatingDual B) y₀]
  simp only [LinearMap.flip_apply, ← recessionFn_eq_supportFn_dom_conj (B := B) hf]

omit [SeparatingDual ℝ E] in
/-- **Rockafellar, Corollary 13.3.4(d)**: `y₀` lies in the affine hull of `dom f*` exactly when
`⟨·, y₀⟩` agrees with the recession function of `f` in every direction in which the latter is
additively reversible. -/
theorem mem_affineSpan_dom_conj_iff (hf : ClosedProperConvexFn f) (y₀ : F) :
    y₀ ∈ affineSpan ℝ (dom (conj B f)) ↔
      ∀ y : E, -recessionFn f (-y) = recessionFn f y →
        ((B y y₀ : ℝ) : EReal) = recessionFn f y := by
  rw [mem_affineSpan_iff_eq_supportFn (B := B.flip) (proper_conj hf).dom_nonempty y₀]
  simp only [LinearMap.flip_apply, ← recessionFn_eq_supportFn_dom_conj (B := B) hf]

/-- **Rockafellar, Corollary 13.4.2**: `dom f*` has nonempty interior exactly when the lineality
space of `f` is trivial — when there is no line along which `f` is finite and affine.

Theorem 13.4 (`linealitySpaceFn_eq_annihilator_dom_conj`) presents that lineality space as the
annihilator of the subspace parallel to `aff (dom f*)`, and an annihilator is trivial exactly when
the subspace it annihilates is everything. -/
theorem interior_dom_conj_nonempty_iff (hf : ClosedProperConvexFn f) :
    (interior (dom (conj B f))).Nonempty ↔ linealitySpaceFn f = {0} := by
  have hconv : Convex ℝ (dom (conj B f)) := (convexFn_conj B f).convex_dom
  have hnedom : (dom (conj B f)).Nonempty := (proper_conj hf).dom_nonempty
  rw [hconv.interior_nonempty_iff_affineSpan_eq_top,
    AffineSubspace.affineSpan_eq_top_iff_vectorSpan_eq_top_of_nonempty ℝ F F hnedom,
    linealitySpaceFn_eq_annihilator_dom_conj (B := B) hf]
  constructor
  · intro htop
    ext x
    simp only [Set.mem_ofPred_eq, Set.mem_singleton_iff]
    refine ⟨fun hx => separatingRight_flip_of_separatingDual B x fun w => ?_, ?_⟩
    · simpa using hx w (by rw [htop]; exact Submodule.mem_top)
    · rintro rfl w -
      simp
  · intro hlin
    by_contra hcon
    obtain ⟨w₀, hw₀⟩ : ∃ w₀ : F, w₀ ∉ vectorSpan ℝ (dom (conj B f)) := by
      by_contra hall
      push Not at hall
      exact hcon (eq_top_iff.2 fun w _ => hall w)
    obtain ⟨φ, u, v, hφw, huv, hφV⟩ := geometric_hahn_banach_compact_closed
      (convex_singleton w₀) isCompact_singleton (vectorSpan ℝ (dom (conj B f))).convex
      (vectorSpan ℝ (dom (conj B f))).closed_of_finiteDimensional
      (Set.disjoint_singleton_left.2 hw₀)
    have hzero : ∀ w ∈ vectorSpan ℝ (dom (conj B f)), φ w = 0 := by
      intro w hw
      by_contra hne
      have hb : ∀ t : ℝ, v < t * φ w := fun t => by
        simpa using hφV (t • w) ((vectorSpan ℝ (dom (conj B f))).smul_mem t hw)
      have hcontra := hb ((v - 1) / φ w)
      rw [div_mul_cancel₀ _ hne] at hcontra
      linarith
    have hv0 : v < 0 := by
      have hz := hφV 0 (Submodule.zero_mem _)
      rwa [hzero 0 (Submodule.zero_mem _)] at hz
    have hw0ne : φ w₀ ≠ 0 := by
      have h₁ : φ w₀ < u := hφw w₀ rfl
      linarith
    obtain ⟨x, hx⟩ := exists_pairing_eq B.flip φ
    have hbx : ∀ w : F, B x w = φ w := fun w => (hx w).symm
    have hxne : x ≠ 0 := by
      rintro rfl
      exact hw0ne (by rw [← hbx w₀]; simp)
    have hmem : x ∈ {z : E | ∀ w ∈ vectorSpan ℝ (dom (conj B f)), B z w = 0} :=
      fun w hw => by rw [hbx w]; exact hzero w hw
    rw [hlin] at hmem
    exact hxne hmem

end CofiniteFiniteDim

end Tdaf.ConvexAnalysis
