/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Tdaf.Analysis.Convex.Duality.Gauge
import Tdaf.Analysis.Convex.Recession.Conjugate

/-!
# Boundedness of a polar

Over a dual pair `B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ` of finite-dimensional spaces, the polar `C°` of a closed
convex set containing the origin is bounded exactly when the origin is interior to `C`. The two
sides of the polarity correspondence trade boundedness for interiority, and the exchange is an
identity between three descriptions of the same cone: the recession cone of `C°`, the polar cone
of `C`, and the trivial cone.

## Main results

* `isBounded_polarSet_iff_zero_mem_interior` — `C°` is bounded if and only if `0 ∈ int C`.
* `isBounded_iff_zero_mem_interior_polarSet` — the dual statement: `C` is bounded if and only if
  `0 ∈ int C°`.

## Why a module of its own

The proof needs three facts that no single existing module carries: the recession cone of a polar
set (`recessionCone_eq_polarCone_polarSet`, `Duality/Gauge.lean`), boundedness from a trivial
recession cone (`isBounded_iff_recessionCone_eq_zero`, `Recession/Cone.lean`), and interiority from
a trivial polar cone (`zero_mem_interior_iff_polarCone_eq_zero`, `Recession/Conjugate.lean`).
`Duality/Gauge.lean` does not import `Recession/Conjugate.lean`, nor the other way round, so this is
the first module sitting below both.

**No gauge is involved.** Rockafellar's own proof runs through Corollary 13.2.2 and the finiteness
of `γ(· | C)`; the route taken here needs neither, which is why the result does not wait for a gauge
module. Finite dimension is genuine: it is what `isBounded_iff_recessionCone_eq_zero` (Theorem 8.4)
costs, and what turns "the cone generated by `C°` is dense" into "it is everything" in Corollary
6.4.1.

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §14 (Corollary 14.5.1).
-/

open Bornology Set

namespace Tdaf.ConvexAnalysis

section PolarBounded

variable {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F] [FiniteDimensional ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} [IsCompatiblePairing B] [IsCompatiblePairing B.flip] {C : Set E}

omit [FiniteDimensional ℝ E] [FiniteDimensional ℝ F] in
/-- **The recession cone of a polar set is the polar cone**: `0⁺(C°) = C°` read as a *cone* polar
rather than a *set* polar, for a closed convex `C` containing the origin.

Theorem 14.6 (`recessionCone_eq_polarCone_polarSet`) applied to `C°`, whose bipolar is `C`. This
one needs no finite dimension; it belongs beside `recessionCone_eq_polarCone_polarSet` in
`Duality/Gauge.lean` and is here only because the two theorems below consume it. -/
theorem recessionCone_polarSet (hconv : Convex ℝ C) (hcl : IsClosed C) (h0 : (0 : E) ∈ C) :
    recessionCone (polarSet B C) = polarCone B C := by
  have h := recessionCone_eq_polarCone_polarSet (B := B.flip) (C := polarSet B C)
    (convex_polarSet B C) isClosed_polarSet (zero_mem_polarSet B C)
  rwa [LinearMap.flip_flip, polarSet_polarSet (B := B) hconv hcl h0] at h

/-- **Rockafellar, Corollary 14.5.1.** For a closed convex set `C` containing the origin, the polar
`C°` is bounded if and only if the origin is interior to `C`.

Theorem 8.4 turns boundedness of `C°` into triviality of its recession cone, Theorem 14.6
identifies that recession cone with the polar *cone* of `C`, and Corollary 6.4.1
(`zero_mem_interior_iff_polarCone_eq_zero`) reads a trivial polar cone as interiority of the
origin. -/
theorem isBounded_polarSet_iff_zero_mem_interior (hconv : Convex ℝ C) (hcl : IsClosed C)
    (h0 : (0 : E) ∈ C) : IsBounded (polarSet B C) ↔ (0 : E) ∈ interior C := by
  rw [isBounded_iff_recessionCone_eq_zero (convex_polarSet B C) isClosed_polarSet
      ⟨0, zero_mem_polarSet B C⟩, recessionCone_polarSet hconv hcl h0]
  exact (zero_mem_interior_iff_polarCone_eq_zero (B := B.flip) (D := C) hconv ⟨0, h0⟩).symm

/-- **Rockafellar, Corollary 14.5.1**, dual form: `C` is bounded if and only if the origin is
interior to `C°`.

The first form applied to `C°`, using `C°° = C`. -/
theorem isBounded_iff_zero_mem_interior_polarSet (hconv : Convex ℝ C) (hcl : IsClosed C)
    (h0 : (0 : E) ∈ C) : IsBounded C ↔ (0 : F) ∈ interior (polarSet B C) := by
  have h := isBounded_polarSet_iff_zero_mem_interior (B := B.flip) (C := polarSet B C)
    (convex_polarSet B C) isClosed_polarSet (zero_mem_polarSet B C)
  rwa [polarSet_polarSet (B := B) hconv hcl h0] at h

end PolarBounded

end Tdaf.ConvexAnalysis
