/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Tdaf.Analysis.Convex.Duality.Gauge
import Tdaf.Analysis.Convex.Recession.Conjugate

/-!
# Boundedness of a polar

Over a dual pair of finite-dimensional spaces, the polar `C°` of a closed convex set containing the
origin is bounded exactly when the origin is interior to `C`: polarity trades boundedness on one
side for interiority on the other.

## Main results

* `isBounded_polarSet_iff_zero_mem_interior` — **Corollary 14.5.1**: `C°` is bounded if and only
  if `0 ∈ int C`. `isBounded_iff_zero_mem_interior_polarSet` is the dual statement.

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §14.
-/

open Bornology Set

namespace Tdaf.ConvexAnalysis

section PolarBounded

variable {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F] [FiniteDimensional ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} [IsCompatiblePairing B] [IsCompatiblePairing B.flip] {C : Set E}

/-- **Corollary 14.5.1.** For a closed convex set `C` containing the origin, the polar `C°` is
bounded if and only if the origin is interior to `C`.

Finite dimension is genuine: it is what Theorem 8.4 (`isBounded_iff_recessionCone_eq_zero`) costs,
and what turns "the cone generated by `C°` is dense" into "it is everything". -/
theorem isBounded_polarSet_iff_zero_mem_interior (hconv : Convex ℝ C) (hcl : IsClosed C)
    (h0 : (0 : E) ∈ C) : IsBounded (polarSet B C) ↔ (0 : E) ∈ interior C := by
  rw [isBounded_iff_recessionCone_eq_zero (convex_polarSet B C) isClosed_polarSet
      ⟨0, zero_mem_polarSet B C⟩, recessionCone_polarSet hconv hcl h0]
  exact (zero_mem_interior_iff_polarCone_eq_zero (B := B.flip) (D := C) hconv ⟨0, h0⟩).symm

/-- **Corollary 14.5.1**, dual form: `C` is bounded if and only if the origin is interior to
`C°`. -/
theorem isBounded_iff_zero_mem_interior_polarSet (hconv : Convex ℝ C) (hcl : IsClosed C)
    (h0 : (0 : E) ∈ C) : IsBounded C ↔ (0 : F) ∈ interior (polarSet B C) := by
  have h := isBounded_polarSet_iff_zero_mem_interior (B := B.flip) (C := polarSet B C)
    (convex_polarSet B C) isClosed_polarSet (zero_mem_polarSet B C)
  rwa [polarSet_polarSet (B := B) hconv hcl h0] at h

end PolarBounded

end Tdaf.ConvexAnalysis
