/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Tdaf.Analysis.Convex.LinearInequalities
import Tdaf.Surface.Rockafellar.Part3.Section14

/-!
# Rockafellar, §22: Linear Inequalities

R. T. Rockafellar, *Convex Analysis* (Princeton, 1970), §22, pp. 198–212: finite systems of weak
and strict linear inequalities, the theorems of the alternative that decide their solvability, and
Farkas' Lemma.

The four results of the section's first half are here, stated over `Rn n = ℝⁿ` and closed by
specialising `Tdaf/Analysis/Convex/LinearInequalities.lean`. The second half — the independent,
combinatorial development through elementary vectors — is deferred; see below.

## Contents

| label | declaration |
|---|---|
| Theorem 22.1 | `theorem_22_1`, `theorem_22_1_matrix` |
| Theorem 22.2 | `theorem_22_2` |
| Theorem 22.3 | `theorem_22_3` |
| Corollary 22.3.1 | `corollary_22_3_1`, `corollary_22_3_1_polar` |

## The section's definitions

* **Consequence of a system** (p. 200): `IsConsequence a α a₀ α₀` says that `⟨a₀, x⟩ ≤ α₀` holds at
  every `x` satisfying `⟨aᵢ, x⟩ ≤ αᵢ` for `i = 1, …, m`. `isConsequence_iff` is the bridge to the
  backbone's orientation of the pairing, and every result below is stated through it.
* **The matrix form** (p. 201): `IsRowsOf A a` says that `A` is the `m × n` matrix whose rows are
  `a₁, …, a_m`, i.e. `(Ax)ᵢ = ⟨aᵢ, x⟩`. Rockafellar's transpose `A*` is `LinearMap.adjoint A`
  through the backbone's `isAdjointPair_adjoint`, and `adjoint_eq_sum_smul` is the identity
  `A*w = ∑ wᵢaᵢ` that turns alternative (b) of Theorem 22.1 into `w ≥ 0`, `A*w = 0`, `⟨w, a⟩ < 0`.
* **Real interval** (p. 202): "by a real interval we mean merely a convex subset of `R`", so
  `IsRealInterval` is `Convex ℝ` on `Set ℝ`. `rectangle I` is the generalized rectangle
  `{z | ζⱼ ∈ Iⱼ}` of p. 203 and `intervalCombo z I` is the set `ζ*₁I₁ + ⋯ + ζ*_N I_N`.
  **`Σ ζ*ⱼIⱼ > 0` is a set containment**, `⊆ (0, +∞)`: the convention is stated once, in a
  parenthesis on p. 202, and is what the deferred Theorem 22.6 is about. `posIntervalCombo`
  records it so that the convention is not lost with the theorem.

## The two orientations of the pairing

The book writes `⟨aᵢ, x⟩` with the coefficient vector first; the backbone writes `B x (a i)`,
because in general the solution vector and the coefficient vectors live in different spaces. On
`ℝⁿ` the pairing is symmetric, and `pairing_comm` (with `forall_pairing_le_comm` and
`forall_pairing_lt_comm`, all three in `Surface/Common/Euclidean.lean`) is the only translation any
statement below needs.

## What is not here

* **Lemma 22.4** (every non-zero vector of a subspace `L` is a non-negative combination of
  elementary vectors of `L` conformal to it) — *deferred by scope*: elementary vectors are the
  minimal-support vectors of a subspace, and their theory is combinatorial matroid theory rather
  than convex analysis.
* **Corollary 22.4.1** (`L` is generated by its elementary vectors) — *deferred by scope*, with
  Lemma 22.4.
* **Lemma 22.5** (the conformal realisation step for a vector of `L` on a painted index set) —
  *deferred by scope*, with Lemma 22.4.
* **The vocabulary the deferred development runs on** — the *support* of a vector (the set of
  indices `j` with `ζⱼ ≠ 0`) and an *elementary vector* of a subspace `L` (a non-zero `z ∈ L` whose
  support is minimal with respect to `L`, i.e. does not properly include the support of any other
  non-zero vector of `L`) — *deferred by scope*, with Lemma 22.4. The section plan records this
  definition as OCR-truncated in the source text; it is not truncated there, and reads as just
  quoted.
* **Theorem 22.6** (given intervals `I₁, …, I_N` and a subspace `L`, either `L` meets the
  generalized rectangle or some `z* ∈ L^⊥` has `Σ ζ*ⱼIⱼ > 0`) — *deferred by scope*: it is the
  conjecture the elementary-vector development is built to prove, and the book's proof is
  explicitly independent of all convexity theory. Its statement is the one place the containment
  convention for `Σ ζ*ⱼIⱼ > 0` is used, and `posIntervalCombo` below is that convention, kept so
  that the theorem can be stated verbatim when the development is formalised.
* **Theorem 22.7** (Tucker's complementarity theorem) — *deferred by scope*, with Theorem 22.6,
  from which the book derives it.
* **The graph-theoretic material** (pp. 205–206: directed graphs, incidence matrices, circulation
  and tension spaces, cocircuits) — *omitted with a reason*: the book presents it explicitly "for
  the sake of motivation", and it is used in no proof.
* **The interval reading of `Ax ≤ a` and of `x ≥ 0, Ax = a`** (p. 202) — *omitted with a reason*:
  the correspondence is between a system in `ℝⁿ` with `m` constraints and a rectangle in `ℝᴺ`,
  `N = m + n`, and the transport between `ℝᵐ × ℝⁿ` and `ℝᵐ⁺ⁿ` is not available to the surface
  (`Euclidean.lean`, "`pairingProd` is not `Rn (m + n)`"). The vocabulary itself is here.
* **The two further dual pairs of systems** (p. 201: `x ≥ 0, Ax = a` against `A*w ≤ 0, ⟨a, w⟩ > 0`,
  and the exercise `x ≥ 0, Ax ≤ a` against `w ≥ 0, A*w ≥ 0, ⟨a, w⟩ < 0`) — *omitted with a reason*:
  both read `A` by its columns rather than its rows, so each needs a second matrix dictionary while
  adding no mathematics to Farkas' Lemma, which is `corollary_22_3_1`.
* **The equality-constraint variant of Theorem 22.1** (p. 204, "the reader can prove this, as an
  exercise") — *omitted with a reason*: an unnumbered exercise, proved by expressing each equation
  as two inequalities and splitting the multiplier.
* **The illustration that `ξ₁ + ξ₂ ≥ 0` is a consequence of `ξᵢ ≥ 0`** (p. 200) — *omitted with a
  reason*: a two-variable numerical example of the definition, testing nothing.
* **The infinite-system remark** (p. 201: Theorem 22.3 and Farkas' Lemma hold for systems indexed
  by a compact set of `(aᵢ, αᵢ)` whose solution set has non-empty interior, by Theorem 17.3) —
  *deferred by scope* to §17, whose Theorem 17.3 it is stated as a consequence of.

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §22.
-/

open Set Pointwise

namespace Rockafellar

open Tdaf.ConvexAnalysis Tdaf.Surface

variable {m n : ℕ}

/-! ### Theorem 22.1: the alternative for a system of weak inequalities -/

/-- **Rockafellar, Theorem 22.1** (Gale's theorem of the alternative). Let `aᵢ ∈ ℝⁿ` and `αᵢ ∈ ℝ`
for `i = 1, …, m`. Then one and only one of the following alternatives holds:

(a) there exists a vector `x ∈ ℝⁿ` such that `⟨aᵢ, x⟩ ≤ αᵢ` for `i = 1, …, m`;

(b) there exist non-negative reals `λ₁, …, λ_m` such that `∑ λᵢaᵢ = 0` and `∑ λᵢαᵢ < 0`.

"One and only one" is the `Iff` with the negation on the right: the forward direction is the
exclusivity and the backward direction is the existence.

Specialises `alternative_linear_system`. Rockafellar derives this from Theorem 21.4; the backbone
uses the elementary route through Farkas' Lemma that he offers as an alternative, so §22 does not
wait on §21 here. -/
theorem theorem_22_1 (a : Fin m → Rn n) (α : Fin m → ℝ) :
    (∃ x : Rn n, ∀ i, pairing n (a i) x ≤ α i) ↔
      ¬ ∃ l : Fin m → ℝ, (∀ i, 0 ≤ l i) ∧ (∑ i, l i • a i = 0) ∧ ∑ i, l i * α i < 0 := by
  rw [← alternative_linear_system (B := pairing n) a α]
  exact exists_congr fun x => forall_pairing_le_comm a α x

/-! ### Theorem 22.2: the alternative for a mixed system -/

/-- **Rockafellar, Theorem 22.2** (Motzkin's transposition theorem). Assume that the weak system
`⟨bⱼ, x⟩ ≤ βⱼ` is consistent. Then one and only one of the following alternatives holds:

(a) there exists a vector `x` with `⟨aᵢ, x⟩ < αᵢ` for every `i` and `⟨bⱼ, x⟩ ≤ βⱼ` for every `j`;

(b) there exist non-negative reals `λᵢ, μⱼ`, at least one `λᵢ` non-zero, such that
`∑ λᵢaᵢ + ∑ μⱼbⱼ = 0` and `∑ λᵢαᵢ + ∑ μⱼβⱼ ≤ 0`.

The book cuts one index range `1, …, m` at `k`, the first `k` constraints being the strict ones;
here the two groups are separate families, which is the same statement with the bookkeeping done by
the index type.

Specialises `alternative_linear_system_strict`. -/
theorem theorem_22_2 {p q : ℕ} (a : Fin p → Rn n) (α : Fin p → ℝ) (b : Fin q → Rn n)
    (β : Fin q → ℝ) (hcons : ∃ x : Rn n, ∀ j, pairing n (b j) x ≤ β j) :
    (∃ x : Rn n, (∀ i, pairing n (a i) x < α i) ∧ ∀ j, pairing n (b j) x ≤ β j) ↔
      ¬ ∃ (l : Fin p → ℝ) (μ : Fin q → ℝ), (∀ i, 0 ≤ l i) ∧ (∀ j, 0 ≤ μ j) ∧ (∃ i, l i ≠ 0) ∧
        (∑ i, l i • a i + ∑ j, μ j • b j = 0) ∧ ∑ i, l i * α i + ∑ j, μ j * β j ≤ 0 := by
  obtain ⟨x₀, hx₀⟩ := hcons
  rw [← alternative_linear_system_strict (B := pairing n) a α b β
    ⟨x₀, (forall_pairing_le_comm b β x₀).1 hx₀⟩]
  exact exists_congr fun x =>
    and_congr (forall_pairing_lt_comm a α x) (forall_pairing_le_comm b β x)

/-- The hypothesis of Theorem 22.2 is itself decided by Theorem 22.1 (p. 200): the weak subsystem
is inconsistent exactly when it carries non-negative multipliers annihilating the `bⱼ` with
`∑ μⱼβⱼ < 0`. Together with Theorem 22.2 this is a necessary and sufficient condition for the
solvability of any finite system of weak and strict linear inequalities. -/
theorem not_consistent_iff {q : ℕ} (b : Fin q → Rn n) (β : Fin q → ℝ) :
    (¬ ∃ x : Rn n, ∀ j, pairing n (b j) x ≤ β j) ↔
      ∃ μ : Fin q → ℝ, (∀ j, 0 ≤ μ j) ∧ (∑ j, μ j • b j = 0) ∧ ∑ j, μ j * β j < 0 := by
  rw [theorem_22_1 b β, not_not]

/-! ### Theorem 22.3: consequences of a system -/

/-- **Consequence of a system** (Rockafellar, §22, p. 200). The inequality `⟨a₀, x⟩ ≤ α₀` is a
*consequence* of the system `⟨aᵢ, x⟩ ≤ αᵢ`, `i = 1, …, m`, if it is satisfied by every `x` which
satisfies the system. -/
def IsConsequence (a : Fin m → Rn n) (α : Fin m → ℝ) (a₀ : Rn n) (α₀ : ℝ) : Prop :=
  ∀ x : Rn n, (∀ i, pairing n (a i) x ≤ α i) → pairing n a₀ x ≤ α₀

/-- Being a consequence, in the backbone's orientation of the pairing. This is the bridge lemma for
`IsConsequence`; every result below is stated through it. -/
theorem isConsequence_iff {a : Fin m → Rn n} {α : Fin m → ℝ} {a₀ : Rn n} {α₀ : ℝ} :
    IsConsequence a α a₀ α₀ ↔
      ∀ x : Rn n, (∀ i, pairing n x (a i) ≤ α i) → pairing n x a₀ ≤ α₀ :=
  forall_congr' fun x => imp_congr (forall_pairing_le_comm a α x) (by rw [pairing_comm])

/-- **Rockafellar, Theorem 22.3.** Assume that the system `⟨aᵢ, x⟩ ≤ αᵢ`, `i = 1, …, m`, is
consistent. An inequality `⟨a₀, x⟩ ≤ α₀` is then a consequence of this system if and only if there
exist non-negative reals `λ₁, …, λ_m` such that `∑ λᵢaᵢ = a₀` and `∑ λᵢαᵢ ≤ α₀`.

Specialises `le_consequence_iff`. -/
theorem theorem_22_3 (a : Fin m → Rn n) (α : Fin m → ℝ) (a₀ : Rn n) (α₀ : ℝ)
    (hcons : ∃ x : Rn n, ∀ i, pairing n (a i) x ≤ α i) :
    IsConsequence a α a₀ α₀ ↔
      ∃ l : Fin m → ℝ, (∀ i, 0 ≤ l i) ∧ (∑ i, l i • a i = a₀) ∧ ∑ i, l i * α i ≤ α₀ := by
  obtain ⟨x₀, hx₀⟩ := hcons
  rw [isConsequence_iff]
  exact le_consequence_iff a α a₀ α₀ ⟨x₀, (forall_pairing_le_comm a α x₀).1 hx₀⟩

/-- **Rockafellar, Corollary 22.3.1** (Farkas' Lemma). An inequality `⟨a₀, x⟩ ≤ 0` is a consequence
of the system `⟨aᵢ, x⟩ ≤ 0`, `i = 1, …, m`, if and only if there exist non-negative reals
`λ₁, …, λ_m` such that `∑ λᵢaᵢ = a₀`.

The book's proof is Theorem 22.3 with `α = 0`, whose hypothesis holds because `x = 0` solves the
system. Specialises `farkas`, which the backbone proves directly as `K°° = K`. -/
theorem corollary_22_3_1 (a : Fin m → Rn n) (a₀ : Rn n) :
    IsConsequence a (fun _ => 0) a₀ 0 ↔
      ∃ l : Fin m → ℝ, (∀ i, 0 ≤ l i) ∧ ∑ i, l i • a i = a₀ := by
  rw [isConsequence_iff]
  exact farkas (B := pairing n) a a₀

/-- **The solution set of a homogeneous system is a polar cone** (p. 200): the solutions of
`⟨aᵢ, x⟩ ≤ 0` are exactly `K°`, for `K` the convex cone generated by `a₁, …, a_m`. -/
theorem solutions_eq_polarCone (a : Fin m → Rn n) :
    {x : Rn n | ∀ i, pairing n (a i) x ≤ 0}
      = polarCone (pairing n) (PointedCone.hull ℝ (Set.range a) : Set (Rn n)) :=
  (polarCone_hull_range_rn a).symm

/-- **Farkas' Lemma says `K°° = K`** (p. 200), for `K` the convex cone generated by finitely many
vectors: the consequences of the system are the members of `K°°`, and `K` is closed because it is
finitely generated (Theorem 19.1), so Theorem 14.1 gives `K°° = cl K = K`.

Specialises `polarCone_hull_range_rn` and `polarCone_setOf_forall_le_zero_rn` (§14) together with
`isClosed_coe_pointedCone_hull_range`. -/
theorem corollary_22_3_1_polar (a : Fin m → Rn n) :
    polarCone (pairing n) (polarCone (pairing n)
        (PointedCone.hull ℝ (Set.range a) : Set (Rn n)))
      = (PointedCone.hull ℝ (Set.range a) : Set (Rn n)) := by
  rw [polarCone_hull_range_rn, polarCone_setOf_forall_le_zero_rn,
    (isClosed_coe_pointedCone_hull_range a).closure_eq]

/-! ### The matrix form -/

/-- **The matrix form** (p. 201): `A` is the `m × n` matrix whose rows are `a₁, …, a_m`, so that
the system of alternative (a) of Theorem 22.1 reads `Ax ≤ a`, componentwise. -/
def IsRowsOf (A : Rn n →ₗ[ℝ] Rn m) (a : Fin m → Rn n) : Prop := ∀ x i, A x i = pairing n (a i) x

/-- **Rockafellar's transpose `A*` is the adjoint**, and on the rows it is the map
`w ↦ ∑ wᵢaᵢ`: the vector condition `∑ λᵢaᵢ = 0` of Theorem 22.1(b) is `A*w = 0`.

Uses the backbone's `isAdjointPair_adjoint`, which supplies the adjoint datum of design decision D3
for `pairing n`. -/
theorem adjoint_eq_sum_smul {A : Rn n →ₗ[ℝ] Rn m} {a : Fin m → Rn n} (h : IsRowsOf A a)
    (w : Rn m) : LinearMap.adjoint A w = ∑ i, w i • a i := by
  refine ext_inner_left ℝ fun x => ?_
  rw [← pairing_apply, ← isAdjointPair_adjoint A x w, pairing_apply, PiLp.inner_apply, inner_sum]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [real_inner_smul_right, ← pairing_apply, pairing_comm, ← h x i]
  simp

/-- **Rockafellar, Theorem 22.1, in matrix form** (p. 201). With `A` the matrix whose rows are the
`aᵢ` and `a = (α₁, …, α_m)`, the system of alternative (a) is `Ax ≤ a` and the system of
alternative (b) is `w ≥ 0`, `A*w = 0`, `⟨w, a⟩ < 0`. The two systems are dual to each other: no
matter what coefficients are chosen, one has a solution and the other does not. -/
theorem theorem_22_1_matrix {A : Rn n →ₗ[ℝ] Rn m} {a : Fin m → Rn n} (h : IsRowsOf A a)
    (α : Rn m) :
    (∃ x : Rn n, ∀ i, A x i ≤ α i) ↔
      ¬ ∃ w : Rn m, (∀ i, 0 ≤ w i) ∧ LinearMap.adjoint A w = 0 ∧ pairing m w α < 0 := by
  have hsum : ∀ w : Rn m, pairing m w α = ∑ i, w i * α i := by
    intro w
    rw [pairing_apply, PiLp.inner_apply]
    exact Finset.sum_congr rfl fun i _ => by simp [mul_comm]
  have hL : (∃ x : Rn n, ∀ i, A x i ≤ α i) ↔ ∃ x : Rn n, ∀ i, pairing n (a i) x ≤ α i :=
    exists_congr fun x => forall_congr' fun i => by rw [h x i]
  rw [hL, theorem_22_1 a fun i => α i]
  refine not_congr ⟨fun hl => ?_, fun hw => ?_⟩
  · obtain ⟨l, hl0, hla, hlα⟩ := hl
    refine ⟨WithLp.toLp 2 l, hl0, ?_, ?_⟩
    · rw [adjoint_eq_sum_smul h]
      exact hla
    · rw [hsum]
      exact hlα
  · obtain ⟨w, hw0, hwa, hwα⟩ := hw
    refine ⟨fun i => w i, hw0, ?_, ?_⟩
    · rw [← adjoint_eq_sum_smul h w]
      exact hwa
    · rw [← hsum w]
      exact hwα

/-! ### The interval form -/

/-- **Real interval** (p. 202): "by a real interval we mean merely a convex subset of `R`; thus
`Iⱼ` may be open or closed or neither, and it may consist of just a single number". -/
def IsRealInterval (I : Set ℝ) : Prop := Convex ℝ I

/-- The **generalized rectangle** `C = {(ζ₁, …, ζ_N) | ζⱼ ∈ Iⱼ, j = 1, …, N}` of p. 203, the set
the subspace `L` of Theorem 22.6 either meets or is separated from. -/
def rectangle {N : ℕ} (I : Fin N → Set ℝ) : Set (Rn N) := {z : Rn N | ∀ j, z j ∈ I j}

@[simp] theorem mem_rectangle {N : ℕ} {I : Fin N → Set ℝ} {z : Rn N} :
    z ∈ rectangle I ↔ ∀ j, z j ∈ I j := Iff.rfl

/-- A generalized rectangle of real intervals is convex. -/
theorem convex_rectangle {N : ℕ} {I : Fin N → Set ℝ} (h : ∀ j, IsRealInterval (I j)) :
    Convex ℝ (rectangle I) := by
  intro x hx y hy s t hs ht hst j
  simpa using h j (hx j) (hy j) hs ht hst

/-- The set `ζ*₁I₁ + ⋯ + ζ*_N I_N` of p. 202, the left side of Rockafellar's `Σ ζ*ⱼIⱼ > 0`. -/
def intervalCombo {N : ℕ} (z : Rn N) (I : Fin N → Set ℝ) : Set ℝ := ∑ j, z j • I j

/-- **Rockafellar's `Σ ζ*ⱼIⱼ > 0`** (p. 202). The inequality is a *set containment*: it says that
`ζ*₁ζ₁ + ⋯ + ζ*_NζN > 0` for every choice of `ζⱼ ∈ Iⱼ`, that is, that the interval `Σ ζ*ⱼIⱼ` is
contained in `(0, +∞)`. The convention is stated once, in a parenthesis on p. 202, a hundred lines
before the theorem that uses it. -/
def posIntervalCombo {N : ℕ} (z : Rn N) (I : Fin N → Set ℝ) : Prop :=
  intervalCombo z I ⊆ Set.Ioi 0

theorem posIntervalCombo_iff {N : ℕ} {z : Rn N} {I : Fin N → Set ℝ} :
    posIntervalCombo z I ↔ ∀ c ∈ intervalCombo z I, 0 < c := Iff.rfl

/-- "The set `Σ ζ*ⱼIⱼ` is a real interval, by the way, since a linear combination of convex sets is
convex" (p. 203). -/
theorem isRealInterval_intervalCombo {N : ℕ} (z : Rn N) {I : Fin N → Set ℝ}
    (h : ∀ j, IsRealInterval (I j)) : IsRealInterval (intervalCombo z I) := by
  classical
  refine Finset.sum_induction _ (Convex ℝ) (fun s t hs ht => hs.add ht) ?_ ?_
  · rw [← Set.singleton_zero]
    exact convex_singleton 0
  · exact fun j _ => (h j).smul (z j)

end Rockafellar
