import Tdaf.Analysis.Convex.Recession.ConeHull
import Tdaf.Surface.Common.Euclidean
import Tdaf.Surface.Rockafellar.Part1.Section01

/-!
# Rockafellar, §17: Carathéodory's Theorem

Carathéodory's theorem for a set `S` that mixes **points and directions**, its closedness
consequences, and the dual question of which half-spaces contain the solution set of a compact
system of linear inequalities.

All ten numbered results of §17 are formalized over `Rn n = ℝⁿ`: Theorems 17.1–17.3 and
Corollaries 17.1.1–17.1.6, 17.2.1.

A mixed set `S = S₀ ∪ S₁` is carried as a pair, not as a subset of `ℝⁿ`: a set `P` of points and a
set `D` of *representative vectors* for the directions, one or more per direction. Every
construction here is invariant under rescaling a member of `D` by a positive scalar, so no quotient
type is needed. `ray D` and `coneOf D` are the book's `ray S₁` and `cone S₁`, and `convexHullPD P D`
is `conv S`.

Three statements diverge from the book. **Corollaries 17.1.4 and 17.1.6 are false as printed**:
each is recorded as a proposition (`corollary_17_1_4`, `corollary_17_1_6`) and refuted on `ℝ¹`
(`corollary_17_1_4_false`, `corollary_17_1_6_false`). **Theorem 17.3 is false without `0 ∉ S*`**,
so `theorem_17_3` carries that hypothesis; the book's `x* ≠ 0` is conversely unnecessary.

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §17.
-/

namespace Rockafellar

open Tdaf.ConvexAnalysis Tdaf.Surface

open scoped Pointwise

variable {n : ℕ}

/-! ### Points and directions -/

/-- **`ray S₁`** (p. 153): the origin together with all vectors whose directions belong to `S₁`,
represented here by a set `D` of vectors, one or more per direction. -/
def ray (D : Set (Rn n)) : Set (Rn n) :=
  insert 0 {x | ∃ y ∈ D, ∃ a : ℝ, 0 < a ∧ x = a • y}

/-- **`cone S₁`** (p. 153): the convex cone generated by the vectors of `D`. The book defines it
as `conv (ray S₁)`; `coneOf_eq_convexHull_ray` is the bridge. -/
def coneOf (D : Set (Rn n)) : Set (Rn n) := (PointedCone.hull ℝ D : Set (Rn n))

theorem subset_ray (D : Set (Rn n)) : D ⊆ ray D := fun y hy =>
  Or.inr ⟨y, hy, 1, one_pos, (one_smul ℝ y).symm⟩

theorem ray_subset_coneOf (D : Set (Rn n)) : ray D ⊆ coneOf D := by
  rintro x (rfl | ⟨y, hy, a, ha, rfl⟩)
  · exact zero_mem _
  · exact Submodule.smul_mem _ (⟨a, ha.le⟩ : {c : ℝ // 0 ≤ c}) (PointedCone.subset_hull hy)

/-- Rockafellar's definition `cone S₁ = conv (ray S₁)`, for any set of representative vectors. -/
theorem coneOf_eq_convexHull_ray (D : Set (Rn n)) : coneOf D = convexHull ℝ (ray D) := by
  classical
  refine subset_antisymm (fun x hx => ?_) ?_
  · obtain ⟨c, hcD, hc0, hcx⟩ := PointedCone.mem_hull_set.1 hx
    set T : ℝ := ∑ y ∈ c.support, c y with hT
    rcases eq_or_lt_of_le (Finset.sum_nonneg fun y _ => hc0 y) with hT0 | hT0
    · have hzero : ∀ y ∈ c.support, c y = 0 :=
        (Finset.sum_eq_zero_iff_of_nonneg fun y _ => hc0 y).1 hT0.symm
      have hx0 : x = 0 := by
        rw [← hcx, Finsupp.sum]
        exact Finset.sum_eq_zero fun y hy => by rw [hzero y hy, zero_smul]
      exact hx0 ▸ subset_convexHull ℝ (ray D) (Or.inl rfl)
    · have hsum : ∑ y ∈ c.support, (c y / T) • (T • y) = x := by
        rw [← hcx, Finsupp.sum]
        refine Finset.sum_congr rfl fun y _ => ?_
        rw [smul_smul, div_mul_cancel₀ _ hT0.ne']
      rw [← hsum]
      refine (convex_convexHull ℝ (ray D)).sum_mem (fun y _ => div_nonneg (hc0 y) hT0.le) ?_ ?_
      · rw [← Finset.sum_div, ← hT, div_self hT0.ne']
      · intro y hy
        exact subset_convexHull ℝ (ray D)
          (Or.inr ⟨y, hcD (by exact_mod_cast hy), T, hT0, rfl⟩)
  · exact convexHull_min (ray_subset_coneOf D)
      ((PointedCone.hull ℝ D : ConvexCone ℝ (Rn n)).convex)

/-- **`conv S = conv S₀ + cone S₁`** (p. 153): the book's formula for the convex hull of a mixed
set, which is the backbone's definition of `convexHullPD`. -/
theorem convexHullPD_eq_add (P D : Set (Rn n)) :
    convexHullPD P D = convexHull ℝ P + coneOf D := rfl

/-- **Rockafellar's definition of `conv S`** (p. 153): the smallest convex set containing `S₀` and
receding in every direction of `S₁`. -/
theorem convexHullPD_isLeast (P D : Set (Rn n)) :
    IsLeast {C : Set (Rn n) | Convex ℝ C ∧ P ⊆ C ∧ D ⊆ recessionCone C} (convexHullPD P D) :=
  isLeast_convexHullPD P D

/-- **`aff S = conv S = ∅` if `S` contains directions only** (p. 154). -/
theorem convexHullPD_empty_points (D : Set (Rn n)) : convexHullPD (∅ : Set (Rn n)) D = ∅ :=
  convexHullPD_empty_left D

/-! ### Theorem 17.1 -/

/-- **Theorem 17.1** (Carathéodory's Theorem). For a set `S` of points and directions in `ℝⁿ`,
`x ∈ conv S` iff `x` is a convex combination of `n + 1` of the points and directions of `S`, not
necessarily distinct. The count is the total number of points and directions used, and every
coefficient produced is strictly positive. -/
theorem theorem_17_1 (P D : Set (Rn n)) (x : Rn n) :
    x ∈ convexHullPD P D ↔
      ∃ (p d : Finset (Rn n)) (a b : Rn n → ℝ), ↑p ⊆ P ∧ ↑d ⊆ D ∧
        (∀ y ∈ p, 0 < a y) ∧ (∀ y ∈ d, 0 < b y) ∧ ∑ y ∈ p, a y = 1 ∧
        p.card + d.card ≤ n + 1 ∧ (∑ y ∈ p, a y • y) + ∑ y ∈ d, b y • y = x := by
  constructor
  · intro hx
    obtain ⟨p, d, a, b, hp, hd, ha, hb, hsum, hcard, hval⟩ := exists_of_mem_convexHullPD hx
    rw [finrank_euclideanSpace_fin] at hcard
    exact ⟨p, d, a, b, hp, hd, ha, hb, hsum, hcard, hval⟩
  · rintro ⟨p, d, a, b, hp, hd, ha, hb, hsum, -, rfl⟩
    exact sum_mem_convexHullPD hp hd (fun y hy => (ha y hy).le) (fun y hy => (hb y hy).le) hsum

/-- **Theorem 17.1**, second sentence: `conv S` is the union of the generalized `d`-dimensional
simplices whose vertices belong to `S`, where `d = dim (conv S)`. A generalized `d`-dimensional
simplex (p. 155) is `convexHullPD` of `d + 1` affinely independent points and directions — the
points its ordinary vertices, the directions its vertices at infinity — affine independence of a
mixed set meaning that the lifted vectors `(1, xᵢ)` and `(0, xⱼ)` are linearly independent in
`ℝⁿ⁺¹`. The hypothesis `P ≠ ∅` is the book's convention `conv S = ∅` for directions only. -/
theorem theorem_17_1_simplex {P D : Set (Rn n)} (hP : P.Nonempty) {m : ℕ}
    (hm : dim (convexHullPD P D) = (m : ℤ)) :
    convexHullPD P D =
      ⋃ (p : Finset (Rn n)) (d : Finset (Rn n)) (_ : ↑p ⊆ P) (_ : ↑d ⊆ D)
        (_ : AffineIndepPD (↑p : Set (Rn n)) (↑d : Set (Rn n)))
        (_ : p.card + d.card = m + 1),
        convexHullPD (↑p : Set (Rn n)) (↑d : Set (Rn n)) := by
  have hCne : (convexHullPD P D).Nonempty := hP.mono (subset_convexHullPD P D)
  have hdim : finrankPD P D = m := by
    rw [dim_of_nonempty hCne] at hm
    rw [finrankPD_def]
    exact_mod_cast hm
  rw [← hdim]
  exact convexHullPD_eq_iUnion_simplex hP

/-- **Corollary 17.1.1**. Every point of the convex hull of a union of convex sets `Cᵢ` is a
convex combination of `n + 1` or fewer affinely independent points, each from a different `Cᵢ`. -/
theorem corollary_17_1_1 {ι : Type*} {C : ι → Set (Rn n)} (hC : ∀ i, Convex ℝ (C i)) {x : Rn n}
    (hx : x ∈ convexHull ℝ (⋃ i, C i)) :
    ∃ (t : Finset ι) (w : ι → ℝ) (p : ι → Rn n), (∀ i ∈ t, 0 < w i) ∧ ∑ i ∈ t, w i = 1 ∧
      (∀ i ∈ t, p i ∈ C i) ∧ AffineIndependent ℝ (fun i : (t : Set ι) => p (i : ι)) ∧
      t.card ≤ n + 1 ∧ ∑ i ∈ t, w i • p i = x := by
  obtain ⟨t, w, p, hw, hone, hmem, hai, hcard, hval⟩ :=
    exists_affineIndependent_of_mem_convexHull_iUnion hC hx
  rw [finrank_euclideanSpace_fin] at hcard
  exact ⟨t, w, p, hw, hone, hmem, hai, hcard, hval⟩

/-- **Corollary 17.1.2**. Every vector of the convex cone generated by a union of convex sets `Cᵢ`
is a non-negative combination of `n` or fewer linearly independent vectors, each from a different
`Cᵢ`. Neither the book's `x ≠ 0` nor its `Cᵢ ≠ ∅` is needed: the empty index set covers the origin,
and an empty `Cᵢ` never contributes an index. -/
theorem corollary_17_1_2 {ι : Type*} {C : ι → Set (Rn n)} (hC : ∀ i, Convex ℝ (C i)) {x : Rn n}
    (hx : x ∈ coneOf (⋃ i, C i)) :
    ∃ (t : Finset ι) (w : ι → ℝ) (v : ι → Rn n), (∀ i ∈ t, 0 < w i) ∧ (∀ i ∈ t, v i ∈ C i) ∧
      LinearIndepOn ℝ v (t : Set ι) ∧ t.card ≤ n ∧ ∑ i ∈ t, w i • v i = x := by
  obtain ⟨t, w, v, hw, hmem, hli, hcard, hval⟩ :=
    exists_linearIndepOn_of_mem_coneHull_iUnion hC hx
  rw [finrank_euclideanSpace_fin] at hcard
  exact ⟨t, w, v, hw, hmem, hli, hcard, hval⟩

/-- **Corollary 17.1.3**. For proper convex `fᵢ`, `(conv fᵢ) x` is the infimum of `∑ λᵢ fᵢ(xᵢ)`
over convex combinations `∑ λᵢ xᵢ = x` with at most `n + 1` non-zero coefficients whose `xᵢ` are
affinely independent. The elimination behind it may choose the sign of an affine dependency by the
cost, both signs carrying a positive coefficient; that is what fails for Corollary 17.1.4. -/
theorem corollary_17_1_3 {ι : Type*} {f : ι → Rn n → EReal} (hf : ∀ i, ConvexFn (f i))
    (hp : ∀ i, Proper (f i)) (x : Rn n) :
    convFn f x = sInf {z : EReal | ∃ (t : Finset ι) (w : ι → ℝ) (p : ι → Rn n),
      (∀ i ∈ t, 0 < w i) ∧ ∑ i ∈ t, w i = 1 ∧ t.card ≤ n + 1 ∧
        AffineIndependent ℝ (fun i : (t : Set ι) => p (i : ι)) ∧ (∀ i ∈ t, f i (p i) ≠ ⊤) ∧
        ∑ i ∈ t, w i • p i = x ∧ z = ∑ i ∈ t, (w i : EReal) * f i (p i)} := by
  have h := convFn_apply_affineIndependent hf (fun i y => (hp i).ne_bot y) x
  rwa [finrank_euclideanSpace_fin] at h

/-- **Corollary 17.1.5**. For any `f : ℝⁿ → (-∞, +∞]`, `(conv f) x` is the infimum of
`∑_{i=1}^{n+1} λᵢ f(xᵢ)` over convex combinations `∑ λᵢ xᵢ = x`. The points need not be distinct:
repetitions and zero coefficients turn Carathéodory's "at most `n + 1`" into a statement about the
fixed index type `Fin (n + 1)`, and `0 · (+∞) = 0` makes a zero coefficient harmless. -/
theorem corollary_17_1_5 {f : Rn n → EReal} (hf : ∀ x, f x ≠ ⊥) (x : Rn n) :
    convHullFn f x = sInf {z : EReal | ∃ (w : Fin (n + 1) → ℝ) (p : Fin (n + 1) → Rn n),
      (∀ i, 0 ≤ w i) ∧ ∑ i, w i = 1 ∧ ∑ i, w i • p i = x ∧
        z = ∑ i, (w i : EReal) * f (p i)} := by
  have h := convHullFn_apply_fin hf x
  rwa [finrank_euclideanSpace_fin] at h

/-! ### Theorems 17.2 and 17.3 -/

/-- **Theorem 17.2**. `cl (conv S) = conv (cl S)` for a bounded set `S ⊆ ℝⁿ`. -/
theorem theorem_17_2 {S : Set (Rn n)} (hS : Bornology.IsBounded S) :
    closure (convexHull ℝ S) = convexHull ℝ (closure S) :=
  hS.closure_convexHull

/-- **Theorem 17.2**, second sentence: `conv S` is closed and bounded whenever `S` is. In `ℝⁿ`
"closed and bounded" is "compact". -/
theorem theorem_17_2_isCompact {S : Set (Rn n)} (hS : IsCompact S) :
    IsCompact (convexHull ℝ S) :=
  hS.isCompact_convexHull

/-- **Corollary 17.2.1**. If `S` is non-empty, closed and bounded and `h` is continuous on `S`,
the convex hull of `h` extended by `+∞` off `S` is a closed proper convex function. -/
theorem corollary_17_2_1 {S : Set (Rn n)} (hSne : S.Nonempty) (hScl : IsClosed S)
    (hSb : Bornology.IsBounded S) {h : Rn n → ℝ} (hcont : ContinuousOn h S) :
    ClosedProperConvexFn (convHullFn (restrict S fun x => ((h x : ℝ) : EReal))) :=
  closedProperConvexFn_convHullFn_restrict hSne
    (Metric.isCompact_of_isClosed_isBounded hScl hSb) hcont

/-- **Theorem 17.3**. Let `S*` be a non-empty closed bounded set of vectors `(x*, μ*)` in `ℝⁿ⁺¹`
and let `C = {x | ⟨x, x*⟩ ≤ μ* for all (x*, μ*) ∈ S*}` be `n`-dimensional. The half-space
`{x | ⟨x, b⟩ ≤ β}` contains `C` iff `b = ∑ λᵢ xᵢ*` and `∑ λᵢ μᵢ* ≤ β` for some `(xᵢ*, μᵢ*) ∈ S*`
and `λᵢ ≥ 0`, at most `n` terms in all.

**The book's statement is false without `0 ∉ S*`**, which is assumed here: its proof concludes that
the origin of `ℝⁿ⁺¹` lies outside `conv (S* ∪ {(0,1)})`, and that fails as soon as `(0,0) ∈ S*`.
The book's `x* ≠ 0` is conversely unnecessary — the empty combination covers it. -/
theorem theorem_17_3 {S : Set (Rn n × ℝ)} (hScl : IsClosed S) (hSb : Bornology.IsBounded S)
    (hS0 : (0 : Rn n × ℝ) ∉ S)
    (hdim : dim (inequalitySet (pairing n) S) = (n : ℤ)) (b : Rn n) (β : ℝ) :
    inequalitySet (pairing n) S ⊆ {x : Rn n | pairing n x b ≤ β} ↔
      ∃ (t : Finset (Rn n × ℝ)) (l : Rn n × ℝ → ℝ), ↑t ⊆ S ∧ (∀ q ∈ t, 0 ≤ l q) ∧
        t.card ≤ n ∧ ∑ q ∈ t, l q • q.1 = b ∧ ∑ q ∈ t, l q * q.2 ≤ β := by
  have hne : (inequalitySet (pairing n) S).Nonempty := by
    rcases Set.eq_empty_or_nonempty (inequalitySet (pairing n) S) with hempty | hne
    · rw [hempty, dim_empty] at hdim; omega
    · exact hne
  have hconv : Convex ℝ (inequalitySet (pairing n) S) := by
    intro u hu v hv a c ha hc hac q hq
    have hcomb := add_le_add (mul_le_mul_of_nonneg_left (hu q hq) ha)
      (mul_le_mul_of_nonneg_left (hv q hq) hc)
    simpa [map_add, map_smul, smul_eq_mul, ← add_mul, hac] using hcomb
  have hspan : vectorSpan ℝ (inequalitySet (pairing n) S) = ⊤ := by
    refine Submodule.eq_top_of_finrank_eq ?_
    have h := dim_of_nonempty hne
    rw [hdim] at h
    rw [finrank_euclideanSpace_fin]
    exact_mod_cast h.symm
  have hint : (interior (inequalitySet (pairing n) S)).Nonempty := by
    refine hconv.interior_nonempty_iff_affineSpan_eq_top.2 ?_
    rw [← AffineSubspace.direction_eq_top_iff_of_nonempty ((affineSpan_nonempty ℝ).2 hne),
      direction_affineSpan]
    exact hspan
  have h := inequalitySet_subset_halfSpace_iff (B := pairing n) hScl hSb hS0 hint b β
  rwa [finrank_euclideanSpace_fin] at h

/-! ### Corollaries 17.1.4 and 17.1.6: stated and refuted -/

private theorem exists_unit_coord : ∃ (e : Rn 1) (L : Rn 1 →ₗ[ℝ] ℝ), e ≠ 0 ∧ L e = 1 := by
  obtain ⟨e, he⟩ := exists_ne (0 : Rn 1)
  have hne : pairing 1 e e ≠ 0 := fun h => he (by simpa using h)
  refine ⟨e, (pairing 1 e e)⁻¹ • (pairing 1).flip e, he, ?_⟩
  simp only [LinearMap.smul_apply, LinearMap.flip_apply, smul_eq_mul]
  exact inv_mul_cancel₀ hne

private theorem eq_bot_of_forall_le {v : EReal} (h : ∀ r : ℝ, v ≤ (r : EReal)) : v = ⊥ := by
  by_contra hv
  obtain ⟨r, -, hr⟩ :=
    _root_.EReal.lt_iff_exists_real_btwn.1 (lt_of_le_of_ne bot_le (Ne.symm hv))
  exact absurd (h r) (not_le.2 hr)

/-- **Corollary 17.1.4** as the book states it: for proper convex `fᵢ` and `f` the positively
homogeneous convex function generated by `conv {fᵢ}`, `f x` for `x ≠ 0` is the infimum of
`∑ λᵢ fᵢ(xᵢ)` over non-negative combinations `∑ λᵢ xᵢ = x` with at most `n` non-zero coefficients
whose `xᵢ` are linearly independent. **The proposition is false**, and `corollary_17_1_4_false`
refutes it; it is stated because the book prints it as a corollary with a proof. -/
def corollary_17_1_4 : Prop :=
  ∀ (n : ℕ) (ι : Type) (f : ι → Rn n → EReal), (∀ i, ConvexFn (f i)) → (∀ i, Proper (f i)) →
    ∀ x : Rn n, x ≠ 0 →
      posHomGen (convFn f) x =
        sInf {z : EReal | ∃ (t : Finset ι) (l : ι → ℝ) (p : ι → Rn n),
          (∀ i ∈ t, 0 < l i) ∧ t.card ≤ n ∧ LinearIndepOn ℝ p (t : Set ι) ∧
            ∑ i ∈ t, l i • p i = x ∧ z = ∑ i ∈ t, (l i : EReal) * f i (p i)}

/-- **Corollary 17.1.4 is false as stated.** On `ℝ¹` take `f₁ y = -y` and `f₂ y = y`, both proper
convex. Then `conv {f₁, f₂} ≡ -∞`, since the midpoint of `(y + s, f₁(y + s))` and
`(y - s, f₂(y - s))` is `(y, -s)` for every `s > 0`, so the positively homogeneous convex function
generated is `-∞` everywhere; but at `x = e ≠ 0` the infimum on the right is `-1`, because `n = 1`
admits a single index and `λ x₁ = e` forces the value `-1` or `1`.

The elimination that proves Corollary 17.1.3 has no conical analogue: an affine dependency has
coefficients summing to zero, so both signs occur and one may be chosen to lower the cost, whereas
a conical dependency can have every coefficient of one sign. -/
theorem corollary_17_1_4_false : ¬ corollary_17_1_4 := by
  classical
  intro hcor
  obtain ⟨e, L, he, hLe⟩ := exists_unit_coord
  obtain ⟨g, hg0, hg1⟩ : ∃ g : Fin 2 → (Rn 1 →ₗ[ℝ] ℝ), g 0 = -L ∧ g 1 = L := ⟨![-L, L], rfl, rfl⟩
  set f : Fin 2 → Rn 1 → EReal := fun i y => ((g i y : ℝ) : EReal) with hf
  have hconv : ∀ i, ConvexFn (f i) := fun i => convexFn_coe_linearMap (g i)
  have hproper : ∀ i, Proper (f i) := fun i => ⟨⟨0, by simp [hf]⟩, fun y => by simp [hf]⟩
  have hbot : ∀ y : Rn 1, convFn f y = ⊥ := by
    intro y
    refine eq_bot_of_forall_le fun r => ?_
    obtain ⟨s, hs0, hsr⟩ : ∃ s : ℝ, 0 < s ∧ -s ≤ r :=
      ⟨|r| + 1, by positivity, by have := neg_abs_le r; linarith⟩
    have hL1 : L (y + s • e) = L y + s := by
      rw [map_add, map_smul, smul_eq_mul, hLe, mul_one]
    have hL2 : L (y - s • e) = L y - s := by
      rw [map_sub, map_smul, smul_eq_mul, hLe, mul_one]
    have h1 : ((y + s • e, -(L y + s)) : Rn 1 × ℝ) ∈ ⋃ i, epi (f i) :=
      Set.mem_iUnion.2 ⟨0, mk_mem_epi.2
        (le_of_eq (by simp only [hf, hg0, LinearMap.neg_apply, hL1]))⟩
    have h2 : ((y - s • e, L y - s) : Rn 1 × ℝ) ∈ ⋃ i, epi (f i) :=
      Set.mem_iUnion.2 ⟨1, mk_mem_epi.2 (le_of_eq (by simp only [hf, hg1, hL2]))⟩
    have hpt : (1 / 2 : ℝ) • ((y + s • e, -(L y + s)) : Rn 1 × ℝ)
        + (1 / 2 : ℝ) • ((y - s • e, L y - s) : Rn 1 × ℝ) = ((y, -s) : Rn 1 × ℝ) := by
      refine Prod.ext ?_ ?_
      · change (1 / 2 : ℝ) • (y + s • e) + (1 / 2 : ℝ) • (y - s • e) = y
        module
      · change (1 / 2 : ℝ) * -(L y + s) + (1 / 2 : ℝ) * (L y - s) = -s
        ring
    have hmem : ((y, -s) : Rn 1 × ℝ) ∈ convexHull ℝ (⋃ i, epi (f i)) := by
      rw [← hpt]
      exact convex_convexHull ℝ _ (subset_convexHull ℝ _ h1) (subset_convexHull ℝ _ h2)
        (by norm_num) (by norm_num) (by norm_num)
    exact (ofEpi_apply_le hmem).trans (by exact_mod_cast hsr)
  have hbot0 : posHomGen (convFn f) e = ⊥ :=
    le_bot_iff.1 ((posHomGen_le (convFn f) e).trans (hbot e).le)
  have h := hcor 1 (Fin 2) f hconv hproper e he
  rw [hbot0] at h
  have hle : ((-1 : ℝ) : EReal) ≤ (⊥ : EReal) := by
    rw [h]
    refine le_sInf ?_
    rintro z ⟨t, l, p, -, hcard, -, hval, rfl⟩
    rcases Nat.lt_or_ge t.card 1 with hlt | hge
    · rw [Nat.lt_one_iff, Finset.card_eq_zero] at hlt
      rw [hlt, Finset.sum_empty] at hval
      exact absurd hval.symm he
    · obtain ⟨i, rfl⟩ := Finset.card_eq_one.1 (le_antisymm hcard hge)
      rw [Finset.sum_singleton] at hval ⊢
      have hgi : l i * g i (p i) = g i e := by rw [← hval, map_smul, smul_eq_mul]
      simp only [hf]
      rw [← _root_.EReal.coe_mul, hgi, _root_.EReal.coe_le_coe_iff]
      rcases (by decide : ∀ j : Fin 2, j = 0 ∨ j = 1) i with rfl | rfl
      · rw [hg0]; simp [hLe]
      · rw [hg1]; norm_num [hLe]
  exact absurd (le_bot_iff.1 hle) (_root_.EReal.coe_ne_bot _)

/-- **Corollary 17.1.6** as the book states it: for `f : ℝⁿ → (-∞, +∞]` and `k` the positively
homogeneous convex function generated by `conv f`, `k x` for `x ≠ 0` is the infimum of
`∑_{i=1}^{n} λᵢ f(xᵢ)` over non-negative combinations `∑ λᵢ xᵢ = x`. **The proposition is false**,
and `corollary_17_1_6_false` refutes it. -/
def corollary_17_1_6 : Prop :=
  ∀ (n : ℕ) (f : Rn n → EReal), (∀ x, f x ≠ ⊥) → ∀ x : Rn n, x ≠ 0 →
    posHomGen (convHullFn f) x =
      sInf {z : EReal | ∃ (w : Fin n → ℝ) (p : Fin n → Rn n), (∀ i, 0 ≤ w i) ∧
        ∑ i, w i • p i = x ∧ z = ∑ i, (w i : EReal) * f (p i)}

/-- **Corollary 17.1.6 is false as stated.** On `ℝ¹` take `f y = -|y|`, which never takes the value
`-∞`. Then `conv f ≡ -∞`, because the midpoint of `(y + s, -|y + s|)` and `(y - s, -|y - s|)` is
`(y, α)` with `α ≤ -s` for every `s > 0`, so the generated `k` is `-∞` everywhere. At `x = e ≠ 0`,
however, `n = 1` admits one vector and `λ x₁ = e` with `λ ≥ 0` forces `λ f(x₁) = -1`, so the
infimum is `-1`. This is Corollary 17.1.4's failure for a one-element family. -/
theorem corollary_17_1_6_false : ¬ corollary_17_1_6 := by
  classical
  intro hcor
  obtain ⟨e, L, he, hLe⟩ := exists_unit_coord
  set f : Rn 1 → EReal := fun y => ((-|L y| : ℝ) : EReal) with hf
  have hfne : ∀ y, f y ≠ ⊥ := fun y => by simp [hf]
  have hbot : ∀ y : Rn 1, convHullFn f y = ⊥ := by
    intro y
    refine eq_bot_of_forall_le fun r => ?_
    obtain ⟨s, hs0, hsr⟩ : ∃ s : ℝ, 0 < s ∧ -s ≤ r :=
      ⟨|r| + 1, by positivity, by have := neg_abs_le r; linarith⟩
    have hL1 : L (y + s • e) = L y + s := by
      rw [map_add, map_smul, smul_eq_mul, hLe, mul_one]
    have hL2 : L (y - s • e) = L y - s := by
      rw [map_sub, map_smul, smul_eq_mul, hLe, mul_one]
    have h1 : ((y + s • e, -|L y + s|) : Rn 1 × ℝ) ∈ epi f :=
      mk_mem_epi.2 (le_of_eq (by simp only [hf, hL1]))
    have h2 : ((y - s • e, -|L y - s|) : Rn 1 × ℝ) ∈ epi f :=
      mk_mem_epi.2 (le_of_eq (by simp only [hf, hL2]))
    have hpt : (1 / 2 : ℝ) • ((y + s • e, -|L y + s|) : Rn 1 × ℝ)
        + (1 / 2 : ℝ) • ((y - s • e, -|L y - s|) : Rn 1 × ℝ)
        = ((y, 1 / 2 * -|L y + s| + 1 / 2 * -|L y - s|) : Rn 1 × ℝ) := by
      refine Prod.ext ?_ rfl
      change (1 / 2 : ℝ) • (y + s • e) + (1 / 2 : ℝ) • (y - s • e) = y
      module
    have hmem : ((y, 1 / 2 * -|L y + s| + 1 / 2 * -|L y - s|) : Rn 1 × ℝ)
        ∈ convexHull ℝ (epi f) := by
      rw [← hpt]
      exact convex_convexHull ℝ _ (subset_convexHull ℝ _ h1) (subset_convexHull ℝ _ h2)
        (by norm_num) (by norm_num) (by norm_num)
    have hvalue : 1 / 2 * -|L y + s| + 1 / 2 * -|L y - s| ≤ r := by
      have hA : L y + s ≤ |L y + s| := le_abs_self _
      have hB : -(L y - s) ≤ |L y - s| := neg_le_abs _
      linarith
    exact (ofEpi_apply_le hmem).trans (by exact_mod_cast hvalue)
  have hbot0 : posHomGen (convHullFn f) e = ⊥ :=
    le_bot_iff.1 ((posHomGen_le (convHullFn f) e).trans (hbot e).le)
  have h := hcor 1 f hfne e he
  rw [hbot0] at h
  have hle : ((-1 : ℝ) : EReal) ≤ (⊥ : EReal) := by
    rw [h]
    refine le_sInf ?_
    rintro z ⟨w, p, hw, hsum, rfl⟩
    rw [Fin.sum_univ_one] at hsum ⊢
    have h0 : w 0 * L (p 0) = 1 := by
      have hL := congrArg L hsum
      rwa [map_smul, smul_eq_mul, hLe] at hL
    have habs : w 0 * |L (p 0)| = 1 := by
      rw [← abs_of_nonneg (hw 0), ← abs_mul, h0, abs_one]
    simp only [hf]
    rw [← _root_.EReal.coe_mul, _root_.EReal.coe_le_coe_iff, mul_neg, habs]
  exact absurd (le_bot_iff.1 hle) (_root_.EReal.coe_ne_bot _)

end Rockafellar
