/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Tdaf.Surface.Rockafellar.Part3.Section11
import Tdaf.Surface.Rockafellar.Part3.Section12
import Tdaf.Surface.Rockafellar.Part3.Section13
import Tdaf.Surface.Rockafellar.Part3.Section14
import Tdaf.Surface.Rockafellar.Part3.Section15
import Tdaf.Surface.Rockafellar.Part3.Section16

/-!
# Rockafellar, Part III: Duality Correspondences

R. T. Rockafellar, *Convex Analysis* (Princeton, 1970), §§11–16. This module imports the six
section modules and adds nothing of its own.

| § | module | subject |
|---|---|---|
| 11 | `Part3.Section11` | Separation Theorems |
| 12 | `Part3.Section12` | Conjugates of Convex Functions |
| 13 | `Part3.Section13` | Support Functions |
| 14 | `Part3.Section14` | Polars of Convex Sets |
| 15 | `Part3.Section15` | Polars of Convex Functions |
| 16 | `Part3.Section16` | Dual Operations |

72 of Part III's 77 numbered results have declarations. The five that do not, each with its reason
in the owning module's `## What is not here`:

* **Theorem 14.3** — one backbone lemma short: the level set `{cl (posHomGen f) ≤ 0}` is the closure
  of the convex cone generated by `{f ≤ 0}`. Everything else Theorem 14.3 needs is present.
* **Theorem 14.4** — the same, plus the `ℝⁿ × ℝ × ℝ` ↔ `ℝⁿ⁺²` transport (remediation §4.8).
* **Lemma 16.2, Corollary 16.2.1, Corollary 16.2.2** — the recession-form dual of §9's constraint
  qualification. The backbone's `IsExactImage.of_relint` and `IsExactSum.of_relint` take the
  relative-interior condition straight to the conclusion, so the recession-function step these
  three isolate is never taken; stating them means assembling Theorems 11.1, 11.3 and 13.3 into a
  new backbone result.

This is the Part that tests design decision D3 — duality developed for a *dual pair* rather than
for `ℝⁿ` or for a topological dual. It passes: the ambient `pairing n` discharges every pairing
class, `flip_pairing` says the pairing is its own flip, and the only friction is that a backbone
statement hands back `B.flip` where the surface wants `B` — which the six `*_flip_pairing` rewrites
in `Surface/Common/Euclidean.lean` absorb.
-/
