namespace = 'Tdaf.ConvexAnalysis'

[[node]]
id = 'concaveConj_sub_conj_le_sub'

[[node]]
id = 'fenchel_duality'

[[node]]
id = 'exists_concaveConj_sub_conj_eq'

[[node]]
id = 'fenchel_duality_comp'

[[node]]
id = 'exists_concaveConj_sub_conj_comp_eq'

[[node]]
id = 'fenchel_duality_of_closed'

[[node]]
id = 'exists_sub_eq_iInf'

[[node]]
id = 'sub_eq_concaveConj_sub_conj_iff'

[[node]]
id = 'iInf_sub_eq_iff_exists_kuhnTucker'

[[node]]
id = 'sub_comp_eq_concaveConj_sub_conj_iff'

[[node]]
id = 'iInf_sub_comp_eq_iff_exists_kuhnTucker'

[[node]]
id = 'iInf_mem_eq_neg_iInf_mem_neg_polarCone'

[[node]]
id = 'exists_mem_neg_polarCone_conj_eq_iInf'

[[node]]
id = 'iInf_mem_submodule_eq_neg_iInf_mem_polarCone'

[[node]]
id = 'exists_mem_eq_iInf_of_isExactSum_conj'
