namespace = 'Tdaf.ConvexAnalysis'

[[node]]
id = 'quadFn'

[[node]]
id = 'conj_quadFn'

[[node]]
id = 'conj_quadFn_sub'

[[node]]
id = 'moreau_add'

[[node]]
id = 'infConv_quadFn_ne_top'

[[node]]
id = 'infConv_quadFn_ne_bot'

[[node]]
id = 'mem_subgradient_iff_infConv_eq'
