/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Tdaf.Analysis.Convex.Duality.Gauge
import Tdaf.Surface.Rockafellar.Part3.Section12
import Tdaf.Surface.Rockafellar.Part3.Section13

/-!
# Rockafellar, §14: Polars of Convex Sets

R. T. Rockafellar, *Convex Analysis* (Princeton, 1970), §14, pp. 121–127: the polar `K°` of a
convex cone, obtained by restricting the conjugacy correspondence of §12 to indicator functions of
cones, and its extension to the polar `C°` of a convex set containing the origin, obtained by
conjugating gauges instead of indicators.

Nine of the eleven numbered results are here, stated over `Rn n = ℝⁿ` and closed by specialising
`Tdaf/Analysis/Convex/Duality/{Polar, Gauge, Barrier}.lean` and
`Tdaf/Analysis/Convex/Recession/Conjugate.lean`.

## Contents

| label | declaration |
|---|---|
| Theorem 14.1 | `theorem_14_1_nonempty`, `theorem_14_1_convex`, `theorem_14_1_isCone`, |
| | `theorem_14_1_isClosed`, `theorem_14_1_bipolar`, `theorem_14_1_conj`, |
| | `theorem_14_1_conj_dual` |
| Theorem 14.2 | `theorem_14_2`, `theorem_14_2_dual` |
| Corollary 14.2.1 | `corollary_14_2_1` |
| Corollary 14.2.2 | `corollary_14_2_2` |
| Theorem 14.5 | `theorem_14_5_isClosed`, `theorem_14_5_convex`, `theorem_14_5_zero_mem`, |
| | `theorem_14_5_bipolar`, `theorem_14_5_gauge`, `theorem_14_5_gauge_dual` |
| Corollary 14.5.1 | `corollary_14_5_1`, `corollary_14_5_1_dual` |
| Theorem 14.6 | `theorem_14_6_recession`, `theorem_14_6_recession_dual`, |
| | `theorem_14_6_lineality`, `theorem_14_6_lineality_dual` |
| Corollary 14.6.1 | `corollary_14_6_1_dim`, `corollary_14_6_1_lineality`, `corollary_14_6_1_rank` |
| Theorem 14.7 | `theorem_14_7_conj_nonneg`, `theorem_14_7_conj_zero`, `theorem_14_7_left`, |
| | `theorem_14_7_right` |

## The section's definitions

* **The polar of a convex cone** `K° = {x* | ⟨x, x*⟩ ≤ 0 for every x ∈ K}` is the backbone's
  `polarCone (pairing n)`, unfolded here as `mem_polarCone_rn`.
* **The polar of a convex set** `C° = {x* | ⟨x, x*⟩ ≤ 1 for every x ∈ C}` is `polarSet (pairing n)`,
  unfolded as `mem_polarSet_rn`. The two agree on cones (`polarCone_eq_polarSet_rn`, the remark
  following Corollary 14.5.1).
* **Rank** of a convex set (§8, p. 70) is `rankSet C = dim C - lineality C`, defined here because
  Corollary 14.6.1 is its first consumer among sets; §13's `rankFn` is the companion for functions.

## Two theorems with no printed proof

Theorem 14.1 and Theorem 14.5 carry **no `Proof.` paragraph** in the book: each summarises the
running text immediately preceding it (lines 4759–4767 and 4907–4947). Both arguments are recovered
here. For Theorem 14.1 the text runs: `δ(· | K)` is positively homogeneous, so its conjugate is
again an indicator (Corollary 13.2.1), of a cone that is closed because a conjugate is closed; and
`K°° = cl K` because `f** = cl f`. That is exactly `conj_indicatorFn_polarCone` and
`polarCone_polarCone`, and the backbone proves the latter by the alternative route Rockafellar
mentions — separation, i.e. Corollary 11.7.1. For Theorem 14.5 the text computes
`cl γ(· | C) = δ*(· | C°)` from Theorem 13.5 applied to `f = δ(· | C) + 1`, then reads
`C°° = {x | cl γ(x | C) ≤ 1}` and closes with Corollary 9.7.1; the backbone instead proves
`C°° = C` by the same separation argument as for cones with the constant normalised to `1`, and
`γ(· | C°) = δ*(· | C)` directly from the two infima.

## The unnumbered running text

Recorded: `(cl K)° = K°` (`polarCone_closure_rn`) and `K°° = cl K` for an arbitrary bundled cone
(`polarCone_polarCone_rn`); the examples of pp. 122–123 — the polar of a subspace is its orthogonal
complement (`polarCone_submodule_rn`), the polar of the non-negative orthant is the non-positive
orthant (`polarCone_nonnegOrthant_rn`), the polar of the cone generated by `{aᵢ}` is the solution
set of `⟨aᵢ, x*⟩ ≤ 0` and conversely (`polarCone_hull_range_rn`,
`polarCone_setOf_forall_le_zero_rn`); that polarity is order-inverting (`polarSet_anti_rn`,
`polarCone_anti_rn`); that the polar of a cone as a cone and as a set agree
(`polarCone_eq_polarSet_rn`); that `C° = D°` for `D = cl(conv(C ∪ {0}))`
(`polarSet_convexHullZero_rn`) and hence the identity `C°° = cl(conv(C ∪ {0}))` of line 4944
(`polarSet_polarSet_convexHullZero_rn`), which is what makes Theorem 14.5's hypotheses exactly the
right ones.

## What is not here

* **Theorem 14.3** (the closed convex cones generated by `{x | f x ≤ 0}` and `{x* | f* x* ≤ 0}` are
  polar to each other) — *deferred by scope*, and a **backbone gap**. Its proof needs the recession
  cone of `cl k`, where `k` is the positively homogeneous convex function generated by `f`,
  identified with the closure of the convex cone generated by `{x | f x ≤ 0}`; that step (Theorem
  7.6 plus the analysis of when `(fλ)(x) ≤ 0`) is not in `Recession/`, and the surface is not the
  place to prove it. Everything else the theorem needs — Theorem 13.5
  (`supportFn_setOf_conj_le_zero`) and Theorem 14.2 (`polarCone_recessionConeFn`) — is available,
  so the gap is one lemma wide.
* **Theorem 14.4** (the cone in `ℝⁿ⁺²` generated by the `(1, x, μ)` with `μ ≥ f(x)`, whose polar
  carries `f*`) — *deferred by scope*. `Duality/Polar.lean` defers it for want of the recession
  function of the positively homogeneous function generated by `f`, and the statement additionally
  needs the transport between `ℝⁿ × ℝ × ℝ` and `ℝⁿ⁺²` that the surface does not yet have.
* **The example table `C₁°`–`C₄°`** (book, lines 4959–4997) — *omitted with a reason*. Four
  coordinatewise computations, printed with the words "may be determined to be" and no argument;
  none is used later and none tests the backbone.
* **"`K°` consists of all the vectors normal to `K` at `0`"** (book, line 4787) — *deferred by
  scope* to §23, where the normal cone is defined.
* **"the polar consists of all non-negative linear combinations when the collection `{aᵢ}` is
  finite"** (book, line 4805) — *deferred by scope*: it is Theorem 19.1, that a finitely generated
  cone is closed.

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §14.
-/

open Set Pointwise

namespace Rockafellar

open Tdaf.ConvexAnalysis Tdaf.Surface

variable {n : ℕ}

/-! ### The two polars of §14 -/

/-- **Rockafellar's polar of a convex cone** (§14, p. 121):
`K° = {x* | ⟨x, x*⟩ ≤ 0 for every x ∈ K}`.

This is the backbone's `polarCone (pairing n)`, and the equation is the definition unfolded. -/
theorem mem_polarCone_rn (K : Set (Rn n)) (y : Rn n) :
    y ∈ polarCone (pairing n) K ↔ ∀ x ∈ K, (inner ℝ x y : ℝ) ≤ 0 := Iff.rfl

/-- **Rockafellar's polar of a convex set** (§14, p. 125):
`C° = {x* | ⟨x, x*⟩ ≤ 1 for every x ∈ C}`. -/
theorem mem_polarSet_rn (C : Set (Rn n)) (y : Rn n) :
    y ∈ polarSet (pairing n) C ↔ ∀ x ∈ C, (inner ℝ x y : ℝ) ≤ 1 := Iff.rfl

/-- **Polarity is order-inverting** (§14, line 4955): `C₁ ⊆ C₂` implies `C₂° ⊆ C₁°`.

Specialises `polarSet_anti`. -/
theorem polarSet_anti_rn {C D : Set (Rn n)} (h : C ⊆ D) :
    polarSet (pairing n) D ⊆ polarSet (pairing n) C :=
  polarSet_anti h

/-- Order-inversion for cones. Specialises `polarCone_anti`. -/
theorem polarCone_anti_rn {K L : Set (Rn n)} (h : K ⊆ L) :
    polarCone (pairing n) L ⊆ polarCone (pairing n) K :=
  polarCone_anti h

/-- **The polar of a convex cone as a cone and as a set coincide** (§14, line 4953): the half-space
`{x | ⟨x, x*⟩ ≤ 1}` contains `K` if and only if `{x | ⟨x, x*⟩ ≤ 0}` does.

Specialises `polarCone_eq_polarSet_of_isCone`; the hypothesis is Rockafellar's "cone", closure
under *positive* scalar multiplication. -/
theorem polarCone_eq_polarSet_rn {K : Set (Rn n)} (hK : ∀ a : ℝ, 0 < a → a • K = K) :
    polarCone (pairing n) K = polarSet (pairing n) K :=
  polarCone_eq_polarSet_of_isCone hK

/-- The bipolar of a set, with the `.flip` the backbone statement carries rewritten away;
`flip_pairing` says that `⟨·, ·⟩` on `ℝⁿ` is its own flip. -/
theorem polarSet_polarSet_rn {C : Set (Rn n)} (hconv : Convex ℝ C) (hcl : IsClosed C)
    (h0 : (0 : Rn n) ∈ C) :
    polarSet (pairing n) (polarSet (pairing n) C) = C := by
  simpa using polarSet_polarSet (B := pairing n) hconv hcl h0

/-! ### Theorem 14.1

The polarity correspondence for convex cones. The book prints no proof; see the module docstring. -/

/-- **Rockafellar, Theorem 14.1**, first assertion: the polar of a convex cone is **non-empty** —
it always contains the origin.

Specialises `polarCone_nonempty`; no hypothesis on `K` is needed. -/
theorem theorem_14_1_nonempty (K : Set (Rn n)) : (polarCone (pairing n) K).Nonempty :=
  polarCone_nonempty (pairing n) K

/-- **Rockafellar, Theorem 14.1**, first assertion: the polar of a convex cone is **convex**.

Specialises `convex_polarCone`; no hypothesis on `K` is needed. -/
theorem theorem_14_1_convex (K : Set (Rn n)) : Convex ℝ (polarCone (pairing n) K) :=
  convex_polarCone (pairing n) K

/-- **Rockafellar, Theorem 14.1**, first assertion: the polar of a convex cone is a **cone** in
Rockafellar's sense, `a K° = K°` for every `a > 0`.

Specialises `smul_polarCone`; no hypothesis on `K` is needed. -/
theorem theorem_14_1_isCone (K : Set (Rn n)) {a : ℝ} (ha : 0 < a) :
    a • polarCone (pairing n) K = polarCone (pairing n) K :=
  smul_polarCone (pairing n) K a ha

/-- **Rockafellar, Theorem 14.1**, first assertion: the polar of a convex cone is **closed**, being
an intersection of homogeneous closed half-spaces — which is Rockafellar's own remark that the
first assertion could also be derived from Corollary 11.7.1.

Specialises `isClosed_polarCone`; no hypothesis on `K` is needed. -/
theorem theorem_14_1_isClosed (K : Set (Rn n)) : IsClosed (polarCone (pairing n) K) :=
  isClosed_polarCone

/-- **Rockafellar, Theorem 14.1**, second assertion: `K°° = K` for a non-empty closed convex cone.

A non-empty closed cone in Rockafellar's sense contains the origin, so it is a `PointedCone`, and
the bundled `polarCone_polarCone_pointedCone` supplies convexity, positive homogeneity and
non-emptiness at once. -/
theorem theorem_14_1_bipolar (K : PointedCone ℝ (Rn n)) (hcl : IsClosed (K : Set (Rn n))) :
    polarCone (pairing n) (polarCone (pairing n) (K : Set (Rn n))) = (K : Set (Rn n)) := by
  simpa using polarCone_polarCone_pointedCone (B := pairing n) K hcl

/-- **Rockafellar, Theorem 14.1**, third assertion: the indicator functions of `K` and `K°` are
conjugate to each other. This direction is the computation §14 opens with, and needs no closedness.

Specialises `conj_indicatorFn_eq_indicatorFn_polarCone`, with the hypothesis triple supplied by the
bundling. -/
theorem theorem_14_1_conj (K : PointedCone ℝ (Rn n)) :
    conj (pairing n) (indicatorFn (K : Set (Rn n)))
      = indicatorFn (polarCone (pairing n) (K : Set (Rn n))) :=
  conj_indicatorFn_eq_indicatorFn_polarCone (smul_coe_pointedCone K) ⟨0, K.zero_mem⟩

/-- **Rockafellar, Theorem 14.1**, third assertion, in the remaining direction: `δ(· | K°)*` is
`δ(· | K)` for a non-empty closed convex cone.

Specialises `conj_indicatorFn_polarCone_pointedCone`. -/
theorem theorem_14_1_conj_dual (K : PointedCone ℝ (Rn n)) (hcl : IsClosed (K : Set (Rn n))) :
    conj (pairing n) (indicatorFn (polarCone (pairing n) (K : Set (Rn n))))
      = indicatorFn (K : Set (Rn n)) := by
  simpa using conj_indicatorFn_polarCone_pointedCone (B := pairing n) K hcl

/-- **`(cl K)° = K°`** (§14, line 4763), the invariance that lets Theorem 14.1 be stated for closed
cones without loss. Specialises `polarCone_closure`. -/
theorem polarCone_closure_rn (K : Set (Rn n)) :
    polarCone (pairing n) (closure K) = polarCone (pairing n) K :=
  polarCone_closure K

/-- **`K°° = cl K`** (§14, line 4763) for a convex cone that need not be closed.

Specialises `polarCone_polarCone_pointedCone_eq_closure`. -/
theorem polarCone_polarCone_rn (K : PointedCone ℝ (Rn n)) :
    polarCone (pairing n) (polarCone (pairing n) (K : Set (Rn n)))
      = closure (K : Set (Rn n)) := by
  simpa using polarCone_polarCone_pointedCone_eq_closure (B := pairing n) K

/-! ### The examples of §14 (pp. 122–123) -/

/-- **The polar of a subspace is the orthogonally complementary subspace** (§14, line 4785).

Specialises `polarCone_coe_submodule'`, whose annihilator description is Mathlib's
`Submodule.orthogonal` for the Euclidean pairing. -/
theorem polarCone_submodule_rn (L : Submodule ℝ (Rn n)) :
    polarCone (pairing n) (L : Set (Rn n)) = (Lᗮ : Set (Rn n)) := by
  rw [polarCone_coe_submodule' (pairing n) L]
  ext y
  simp only [Set.mem_ofPred_eq, pairing_apply, SetLike.mem_coe, Submodule.mem_orthogonal]

/-- **The polar of the non-negative orthant is the non-positive orthant** (§14, line 4789).

Specialises `polarCone_nonnegOrthant`; `nonnegOrthant` is §12's. -/
theorem polarCone_nonnegOrthant_rn (n : ℕ) :
    polarCone (pairing n) (nonnegOrthant n) = {y : Rn n | ∀ j, y j ≤ 0} :=
  polarCone_nonnegOrthant

/-- **The polar of the convex cone generated by a family `{aᵢ}`** is the solution set of the
homogeneous inequalities `⟨aᵢ, x*⟩ ≤ 0` (§14, line 4791).

Specialises `polarCone_hull_range`. -/
theorem polarCone_hull_range_rn {ι : Sort*} (a : ι → Rn n) :
    polarCone (pairing n) (PointedCone.hull ℝ (Set.range a) : Set (Rn n))
      = {y : Rn n | ∀ i, (inner ℝ (a i) y : ℝ) ≤ 0} :=
  polarCone_hull_range (pairing n) a

/-- **Dually** (§14, line 4801): the polar of `{y | ⟨aᵢ, y⟩ ≤ 0 for every i}` is the closure of the
convex cone generated by the `aᵢ`.

Specialises `polarCone_setOf_forall_le_zero`. -/
theorem polarCone_setOf_forall_le_zero_rn {ι : Sort*} (a : ι → Rn n) :
    polarCone (pairing n) {y : Rn n | ∀ i, (inner ℝ (a i) y : ℝ) ≤ 0}
      = closure (PointedCone.hull ℝ (Set.range a) : Set (Rn n)) := by
  simpa using polarCone_setOf_forall_le_zero (B := pairing n) a

/-! ### Theorem 14.2 -/

/-- **Rockafellar, Theorem 14.2**, first assertion. Let `f` be a proper convex function. The polar
of the convex cone generated by `dom f` is the recession cone of `f*`.

Specialises `recessionConeFn_conj_hull`; the backbone's second properness hypothesis is discharged
by Theorem 12.2 (`theorem_12_2_proper`), which is available on `ℝⁿ`. -/
theorem theorem_14_2 {f : Rn n → EReal} (hf : ConvexFn f) (hp : Proper f) :
    polarCone (pairing n) (PointedCone.hull ℝ (dom f) : Set (Rn n))
      = recessionConeFn (conj (pairing n) f) :=
  recessionConeFn_conj_hull hp ((theorem_12_2_proper hf).2 hp)

/-- **Rockafellar, Theorem 14.2**, second assertion. If `f` is closed, the polar of the recession
cone of `f` is the closure of the convex cone generated by `dom f*`.

Specialises `polarCone_recessionConeFn`. -/
theorem theorem_14_2_dual {f : Rn n → EReal} (hf : ClosedProperConvexFn f) :
    polarCone (pairing n) (recessionConeFn f)
      = closure (PointedCone.hull ℝ (dom (conj (pairing n) f)) : Set (Rn n)) :=
  polarCone_recessionConeFn hf.convex hf.closed hf.proper

/-- **Rockafellar, Corollary 14.2.1.** The polar of the barrier cone of a non-empty closed convex
set `C` is the recession cone of `C`.

Specialises `polarCone_dom_supportFn`; `barrierCone` is §13's. -/
theorem corollary_14_2_1 {C : Set (Rn n)} (hC : Convex ℝ C) (hcl : IsClosed C)
    (hne : C.Nonempty) :
    polarCone (pairing n) (barrierCone C) = recessionCone C := by
  rw [barrierCone_eq_dom_supportFn]
  simpa using polarCone_dom_supportFn (B := pairing n) hC hcl hne

/-- **Rockafellar, Corollary 14.2.2.** Let `f` be a closed proper convex function. In order that
`{x | f x ≤ α}` be bounded for every `α ∈ ℝ`, it is necessary and sufficient that
`0 ∈ int (dom f*)`.

Specialises `isBounded_setOf_le_iff_zero_mem_interior_dom_conj`. -/
theorem corollary_14_2_2 {f : Rn n → EReal} (hf : ClosedProperConvexFn f) :
    (∀ α : ℝ, Bornology.IsBounded {x : Rn n | f x ≤ (α : EReal)})
      ↔ (0 : Rn n) ∈ interior (dom (conj (pairing n) f)) :=
  isBounded_setOf_le_iff_zero_mem_interior_dom_conj hf.convex hf.closed hf.proper

/-! ### Theorem 14.5

The polarity correspondence for closed convex sets containing the origin. The book prints no proof;
see the module docstring. -/

/-- **Rockafellar, Theorem 14.5**, first assertion: `C°` is **closed**.
Specialises `isClosed_polarSet`; no hypothesis on `C` is needed. -/
theorem theorem_14_5_isClosed (C : Set (Rn n)) : IsClosed (polarSet (pairing n) C) :=
  isClosed_polarSet

/-- **Rockafellar, Theorem 14.5**, first assertion: `C°` is **convex**.
Specialises `convex_polarSet`; no hypothesis on `C` is needed. -/
theorem theorem_14_5_convex (C : Set (Rn n)) : Convex ℝ (polarSet (pairing n) C) :=
  convex_polarSet (pairing n) C

/-- **Rockafellar, Theorem 14.5**, first assertion: `C°` **contains the origin**.
Specialises `zero_mem_polarSet`; no hypothesis on `C` is needed. -/
theorem theorem_14_5_zero_mem (C : Set (Rn n)) : (0 : Rn n) ∈ polarSet (pairing n) C :=
  zero_mem_polarSet (pairing n) C

/-- **Rockafellar, Theorem 14.5**, first assertion: `C°° = C` for a closed convex set containing
the origin. Specialises `polarSet_polarSet`. -/
theorem theorem_14_5_bipolar {C : Set (Rn n)} (hconv : Convex ℝ C) (hcl : IsClosed C)
    (h0 : (0 : Rn n) ∈ C) :
    polarSet (pairing n) (polarSet (pairing n) C) = C :=
  polarSet_polarSet_rn hconv hcl h0

/-- **Rockafellar, Theorem 14.5**, second assertion: the gauge function of `C` is the support
function of `C°`.

Obtained from `gaugeFn_polarSet` at `C°` together with `C°° = C`; the backbone records that only
`0 ∈ C°` — which is automatic — is needed for that step. -/
theorem theorem_14_5_gauge {C : Set (Rn n)} (hconv : Convex ℝ C) (hcl : IsClosed C)
    (h0 : (0 : Rn n) ∈ C) :
    gaugeFn C = supportFn (pairing n) (polarSet (pairing n) C) := by
  conv_lhs => rw [← polarSet_polarSet_rn hconv hcl h0]
  exact gaugeFn_polarSet (zero_mem_polarSet (pairing n) C)

/-- **Rockafellar, Theorem 14.5**, third assertion: dually, the gauge function of `C°` is the
support function of `C`.

Specialises `gaugeFn_polarSet`, which needs only `0 ∈ C`. -/
theorem theorem_14_5_gauge_dual {C : Set (Rn n)} (h0 : (0 : Rn n) ∈ C) :
    gaugeFn (polarSet (pairing n) C) = supportFn (pairing n) C :=
  gaugeFn_polarSet h0

/-- **`C° = D°` where `D = cl(conv(C ∪ {0}))`** (§14, line 4941): a half-space `{x | ⟨x, x*⟩ ≤ 1}`
contains `C` if and only if it contains `D`, because such a half-space is closed and convex and
contains the origin. -/
theorem polarSet_convexHullZero_rn (C : Set (Rn n)) :
    polarSet (pairing n) (closure (convexHull ℝ (C ∪ {0}))) = polarSet (pairing n) C := by
  refine subset_antisymm (polarSet_anti ?_) ?_
  · exact (Set.subset_union_left.trans (subset_convexHull ℝ _)).trans subset_closure
  · have hD : closure (convexHull ℝ (C ∪ {0}))
        ⊆ polarSet (pairing n) (polarSet (pairing n) C) := by
      refine closure_minimal (convexHull_min ?_ (convex_polarSet _ _)) isClosed_polarSet
      refine Set.union_subset ?_ ?_
      · simpa using subset_polarSet_polarSet (pairing n) C
      · simp
    have h := polarSet_anti (B := pairing n) hD
    rwa [polarSet_polarSet_rn (convex_polarSet _ _) isClosed_polarSet
      (zero_mem_polarSet (pairing n) C)] at h

/-- **`C°° = cl(conv(C ∪ {0}))`** (§14, line 4944), the identity that makes Theorem 14.5's
hypotheses exactly the right ones: the bipolar of an arbitrary set is the smallest closed convex
set containing it and the origin. -/
theorem polarSet_polarSet_convexHullZero_rn (C : Set (Rn n)) :
    polarSet (pairing n) (polarSet (pairing n) C) = closure (convexHull ℝ (C ∪ {0})) := by
  rw [← polarSet_convexHullZero_rn C]
  refine polarSet_polarSet_rn (convex_convexHull ℝ _).closure isClosed_closure ?_
  exact subset_closure (subset_convexHull ℝ _ (Set.mem_union_right _ rfl))

/-- **Rockafellar, Corollary 14.5.1.** Let `C` be a closed convex set containing the origin. Then
`C°` is bounded if and only if `0 ∈ int C`.

Theorem 14.6 identifies the recession cone of `C°` with the polar *cone* of `C`, Theorem 8.4 turns
"trivial recession cone" into "bounded", and `zero_mem_interior_iff_polarCone_eq_zero` is Corollary
6.4.1 in the form this needs. Rockafellar argues instead through Corollary 13.2.2 and the
finiteness of `γ(· | C)`. -/
theorem corollary_14_5_1 {C : Set (Rn n)} (hconv : Convex ℝ C) (hcl : IsClosed C)
    (h0 : (0 : Rn n) ∈ C) :
    Bornology.IsBounded (polarSet (pairing n) C) ↔ (0 : Rn n) ∈ interior C := by
  have hcvx : Convex ℝ (polarSet (pairing n) C) := convex_polarSet _ _
  have h0' : (0 : Rn n) ∈ polarSet (pairing n) C := zero_mem_polarSet _ _
  have hrec : recessionCone (polarSet (pairing n) C) = polarCone (pairing n) C := by
    have h := recessionCone_eq_polarCone_polarSet (B := pairing n) hcvx isClosed_polarSet h0'
    rw [flip_pairing, polarSet_polarSet_rn hconv hcl h0] at h
    exact h
  have hiff := zero_mem_interior_iff_polarCone_eq_zero (B := pairing n) (D := C) hconv ⟨0, h0⟩
  rw [flip_pairing] at hiff
  rw [isBounded_iff_recessionCone_eq_zero hcvx isClosed_polarSet ⟨0, h0'⟩, hrec]
  exact hiff.symm

/-- **Rockafellar, Corollary 14.5.1**, dual form: `C` is bounded if and only if `0 ∈ int C°`.

Corollary 14.5.1 applied to `C°`, using `C°° = C`. -/
theorem corollary_14_5_1_dual {C : Set (Rn n)} (hconv : Convex ℝ C) (hcl : IsClosed C)
    (h0 : (0 : Rn n) ∈ C) :
    Bornology.IsBounded C ↔ (0 : Rn n) ∈ interior (polarSet (pairing n) C) := by
  have h := corollary_14_5_1 (C := polarSet (pairing n) C) (convex_polarSet _ _)
    isClosed_polarSet (zero_mem_polarSet _ _)
  rwa [polarSet_polarSet_rn hconv hcl h0] at h

/-! ### Theorem 14.6 -/

/-- **Rockafellar, Theorem 14.6**, first assertion: the polar of the recession cone of `C` is the
closure of the convex cone generated by `C°`.

Specialises `polarCone_recessionCone`. -/
theorem theorem_14_6_recession {C : Set (Rn n)} (hconv : Convex ℝ C) (hcl : IsClosed C)
    (h0 : (0 : Rn n) ∈ C) :
    polarCone (pairing n) (recessionCone C)
      = closure (PointedCone.hull ℝ (polarSet (pairing n) C) : Set (Rn n)) :=
  polarCone_recessionCone hconv hcl h0

/-- **Rockafellar, Theorem 14.6**, first assertion, in the other direction: the polar of the closed
convex cone generated by `C°` is the recession cone of `C`. With `theorem_14_6_recession` this is
the book's "polar to each other".

Specialises `recessionCone_eq_polarCone_polarSet`, after `polarCone_closure` and `polarCone_hull`
strip the closure and the cone hull, which a polar does not see. -/
theorem theorem_14_6_recession_dual {C : Set (Rn n)} (hconv : Convex ℝ C) (hcl : IsClosed C)
    (h0 : (0 : Rn n) ∈ C) :
    polarCone (pairing n) (closure (PointedCone.hull ℝ (polarSet (pairing n) C) : Set (Rn n)))
      = recessionCone C := by
  rw [polarCone_closure, polarCone_hull]
  have h := recessionCone_eq_polarCone_polarSet (B := pairing n) hconv hcl h0
  rw [flip_pairing] at h
  exact h.symm

/-- **Rockafellar, Theorem 14.6**, second assertion: the lineality space of `C` and the subspace
generated by `C°` are orthogonally complementary — here in the form "the lineality space of `C` is
the annihilator of `C°`".

Specialises `linealitySpace_eq_setOf_pairing_eq_zero`. -/
theorem theorem_14_6_lineality {C : Set (Rn n)} (hconv : Convex ℝ C) (hcl : IsClosed C)
    (h0 : (0 : Rn n) ∈ C) :
    linealitySpace C
      = {x : Rn n | ∀ y ∈ polarSet (pairing n) C, (inner ℝ x y : ℝ) = 0} :=
  linealitySpace_eq_setOf_pairing_eq_zero hconv hcl h0

/-- **Rockafellar, Theorem 14.6**, second assertion, dual form: the polar of the lineality space of
`C` is the closed subspace generated by `C°`.

Specialises `polarCone_linealitySpace`. -/
theorem theorem_14_6_lineality_dual {C : Set (Rn n)} (hconv : Convex ℝ C) (hcl : IsClosed C)
    (h0 : (0 : Rn n) ∈ C) :
    polarCone (pairing n) (linealitySpace C)
      = closure (Submodule.span ℝ (polarSet (pairing n) C) : Set (Rn n)) :=
  polarCone_linealitySpace hconv hcl h0

/-! ### Corollary 14.6.1 -/

/-- Rockafellar's **rank** of a convex set (§8, p. 70): `rank C = dim C - lineality C`. §13's
`rankFn` is the companion for convex functions. -/
noncomputable def rankSet (C : Set (Rn n)) : ℤ := dim C - (lineality C : ℤ)

/-- **Rockafellar, Corollary 14.6.1**, first relation: `dim C° = n - lineality C` for a closed
convex set `C` containing the origin.

Specialises `finrank_vectorSpan_polarSet_add_lineality`; `dim` is §1's, and the affine hull of `C°`
is a subspace because `0 ∈ C°`. -/
theorem corollary_14_6_1_dim {C : Set (Rn n)} (hconv : Convex ℝ C) (hcl : IsClosed C)
    (h0 : (0 : Rn n) ∈ C) :
    dim (polarSet (pairing n) C) = (n : ℤ) - (lineality C : ℤ) := by
  have h := finrank_vectorSpan_polarSet_add_lineality (B := pairing n) hconv hcl h0
  rw [finrank_euclideanSpace_fin] at h
  rw [dim_of_nonempty ⟨0, zero_mem_polarSet (pairing n) C⟩]
  omega

/-- **Rockafellar, Corollary 14.6.1**, second relation: `lineality C° = n - dim C`.

Specialises `finrank_vectorSpan_add_lineality_polarSet`. -/
theorem corollary_14_6_1_lineality {C : Set (Rn n)} (hconv : Convex ℝ C) (hcl : IsClosed C)
    (h0 : (0 : Rn n) ∈ C) :
    (lineality (polarSet (pairing n) C) : ℤ) = (n : ℤ) - dim C := by
  have h := finrank_vectorSpan_add_lineality_polarSet (B := pairing n) hconv hcl h0
  rw [finrank_euclideanSpace_fin] at h
  rw [dim_of_nonempty ⟨0, h0⟩]
  omega

/-- **Rockafellar, Corollary 14.6.1**, third relation: `rank C° = rank C`.

It is the difference of the other two, both of which read `n`. -/
theorem corollary_14_6_1_rank {C : Set (Rn n)} (hconv : Convex ℝ C) (hcl : IsClosed C)
    (h0 : (0 : Rn n) ∈ C) :
    rankSet (polarSet (pairing n) C) = rankSet C := by
  rw [rankSet, rankSet, corollary_14_6_1_dim hconv hcl h0,
    corollary_14_6_1_lineality hconv hcl h0]
  ring

/-! ### Theorem 14.7 -/

/-- **Rockafellar, Theorem 14.7**, first assertion: if `f` is non-negative and vanishes at the
origin, then `f*` is likewise non-negative.

Specialises `zero_le_conj`, which needs only `f 0 ≤ 0`. -/
theorem theorem_14_7_conj_nonneg {f : Rn n → EReal} (h0 : f 0 = 0) (y : Rn n) :
    0 ≤ conj (pairing n) f y :=
  zero_le_conj (le_of_eq h0) y

/-- **Rockafellar, Theorem 14.7**, first assertion: `f*` vanishes at the origin.

Specialises `conj_zero_eq_zero`. -/
theorem theorem_14_7_conj_zero {f : Rn n → EReal} (hnn : ∀ x, 0 ≤ f x) (h0 : f 0 = 0) :
    conj (pairing n) f 0 = 0 :=
  conj_zero_eq_zero hnn (le_of_eq h0)

/-- **Rockafellar, Theorem 14.7**, first inclusion: `{x | f x ≤ α}° ⊆ α⁻¹ {x* | f* x* ≤ α}` for
`0 < α < ∞`.

Specialises `polarSet_setOf_le_subset_and_subset`. Rockafellar assumes `f` closed and routes the
proof through Theorems 13.5 and 9.7; the backbone shows that closedness is not needed, and that one
inclusion is a rescaling into the level set while the other is Fenchel's inequality. The
hypothesis is therefore weaker here than in the book. -/
theorem theorem_14_7_left {f : Rn n → EReal} (hf : ConvexFn f) (hnn : ∀ x, 0 ≤ f x)
    (h0 : f 0 = 0) {α : ℝ} (hα : 0 < α) :
    polarSet (pairing n) {x : Rn n | f x ≤ (α : EReal)}
      ⊆ α⁻¹ • {y : Rn n | conj (pairing n) f y ≤ (α : EReal)} :=
  (polarSet_setOf_le_subset_and_subset hf hnn (le_of_eq h0) hα).1

/-- **Rockafellar, Theorem 14.7**, second inclusion:
`α⁻¹ {x* | f* x* ≤ α} ⊆ 2 {x | f x ≤ α}°`. -/
theorem theorem_14_7_right {f : Rn n → EReal} (hf : ConvexFn f) (hnn : ∀ x, 0 ≤ f x)
    (h0 : f 0 = 0) {α : ℝ} (hα : 0 < α) :
    α⁻¹ • {y : Rn n | conj (pairing n) f y ≤ (α : EReal)}
      ⊆ (2 : ℝ) • polarSet (pairing n) {x : Rn n | f x ≤ (α : EReal)} :=
  (polarSet_setOf_le_subset_and_subset hf hnn (le_of_eq h0) hα).2

end Rockafellar
