import Tdaf.Analysis.Convex.RelativeInterior
import TdafSurface.Rockafellar.Part1.Section02

/-!
# Rockafellar, §6: Relative Interiors of Convex Sets

Relative interiors and closures of convex sets: the line segment principle, the fact that a
non-empty convex set has a non-empty relative interior, and how `ri` and `cl` behave under
intersection, linear images and inverse images, products, and convex hulls of unions. All 18
numbered results of §6 are formalized.

The book's `cl C` is Mathlib's `closure C`, its `int C` is `interior C`, and its `ri C` is the
backbone's `ri`, that is `intrinsicInterior ℝ`.

## Main definitions

* `relbd C` — the **relative boundary** `(cl C) \ (ri C)`, bridged to Mathlib's
  `intrinsicFrontier ℝ` by `relbd_eq_intrinsicFrontier`.
* `IsRelativelyOpen C` — the book's **relatively open**: `ri C = C`.
* `coneOver C` — the convex cone of Corollary 6.8.1, generated by `{(1, x) | x ∈ C}`.

**Theorem 6.2 is where finite-dimensionality enters, and it never leaves.** That a non-empty
convex set has a non-empty relative interior is false in infinite dimensions — the positive cone
of `ℓ²` is the standard witness — and §§7, 9, 10, 11, 16, 18 and 20 use it without saying so.
Every statement below inherits `FiniteDimensional ℝ (Rn n)` from the ambient instance, so none of
them carries a dimension hypothesis of its own, which is what makes the dependence easy to miss.

`theorem_6_9` is the two-set case, where the book states the result for `m` sets. `ℝᵐ⁺ᵖ` is
`Rn m × Rn p` here, as in §3, so Theorem 6.8 is stated on the product and Corollary 6.8.1 on
`ℝ × ℝⁿ`. Theorems 6.6 and 6.7 take a `LinearMap`, where the book remarks that affine
transformations work too. `theorem_6_5_ri` adds `Finite ι` to the book's arbitrary index set: the
intersection of `ri [0, 1 + α]` over all `α > 0` is the book's own counterexample to dropping it.

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §6.
-/

namespace Rockafellar

open Tdaf.ConvexAnalysis TdafSurface
open scoped Pointwise

variable {n m p : ℕ} {C C₁ C₂ : Set (Rn n)}

/-! ### The relative interior, the relative boundary and relatively open sets -/

/-- **Rockafellar, §6 (p. 44).** The **relative boundary** of `C` is `(cl C) ∖ (ri C)`. -/
def relbd (C : Set (Rn n)) : Set (Rn n) := closure C \ ri C

/-- The bridge: the book's relative boundary is Mathlib's `intrinsicFrontier`. -/
theorem relbd_eq_intrinsicFrontier (C : Set (Rn n)) : relbd C = intrinsicFrontier ℝ C :=
  closure_sdiff_intrinsicInterior (𝕜 := ℝ) C

/-- Membership in the relative boundary, spelled out. -/
theorem mem_relbd_iff {x : Rn n} : x ∈ relbd C ↔ x ∈ closure C ∧ x ∉ ri C := Iff.rfl

/-- **Rockafellar, §6 (p. 44).** `C` is **relatively open** when `ri C = C`. -/
def IsRelativelyOpen (C : Set (Rn n)) : Prop := ri C = C

/-- The bridge: relative openness is the equation `ri C = C`, by definition. -/
theorem isRelativelyOpen_iff : IsRelativelyOpen C ↔ ri C = C := Iff.rfl

/-- **Rockafellar, §6 (p. 44).** The sandwich `ri C ⊆ C ⊆ cl C`. -/
theorem relint_subset_subset_closure (C : Set (Rn n)) : ri C ⊆ C ∧ C ⊆ closure C :=
  ⟨intrinsicInterior_subset, subset_closure⟩

/-- **Rockafellar, §6 (p. 45).** For an `n`-dimensional convex set `aff C = ℝⁿ`, and then
`ri C = int C`. -/
theorem relint_eq_interior (h : affineSpan ℝ C = ⊤) : ri C = interior C :=
  intrinsicInterior_eq_interior h

/-- **Rockafellar, §6 (p. 45).** An affine set is relatively open. -/
theorem isRelativelyOpen_of_isAffineSet {M : Set (Rn n)} (h : IsAffineSet M) :
    IsRelativelyOpen M := by
  have key := AffineSubspace.intrinsicInterior_coe h.toAffineSubspace
  rw [h.coe_toAffineSubspace] at key
  exact key

/-- **Rockafellar, §6 (p. 45).** Every affine set is closed. In the book this is read off from
Corollary 1.4.1 and Theorem 1.3; here it is the finite-dimensionality of `ℝⁿ`. -/
theorem isClosed_of_isAffineSet {M : Set (Rn n)} (h : IsAffineSet M) : IsClosed M := by
  have key := h.toAffineSubspace.closed_of_finiteDimensional
  rwa [h.coe_toAffineSubspace] at key

/-- **Rockafellar, §6 (p. 45).** `cl C ⊆ cl (aff C) = aff C`, so a line through two points of
`cl C` lies in `aff C`. -/
theorem closure_subset_affineSpan (C : Set (Rn n)) :
    closure C ⊆ (affineSpan ℝ C : Set (Rn n)) :=
  Tdaf.ConvexAnalysis.closure_subset_affineSpan C

/-! ### Theorem 6.1: the line segment principle -/

/-- **Theorem 6.1.** Let `C` be a convex set in `ℝⁿ`, let `x ∈ ri C` and
`y ∈ cl C`. Then `(1 - λ) x + λ y` belongs to `ri C` (and hence in particular to `C`) for
`0 ≤ λ < 1`. -/
theorem theorem_6_1 (hC : Convex ℝ C) {x y : Rn n} (hx : x ∈ ri C) (hy : y ∈ closure C)
    {l : ℝ} (hl₀ : 0 ≤ l) (hl₁ : l < 1) : (1 - l) • x + l • y ∈ ri C :=
  Convex.segment_mem_relint hC hx hy hl₀ hl₁

/-! ### Theorem 6.2 -/

/-- **Theorem 6.2.** `cl C` is convex. -/
theorem theorem_6_2_convex_cl (hC : Convex ℝ C) : Convex ℝ (closure C) :=
  hC.closure

/-- **Theorem 6.2.** `ri C` is convex. This is Theorem 6.1 with `y` taken in `ri C`. -/
theorem theorem_6_2_convex_ri (hC : Convex ℝ C) : Convex ℝ (ri C) :=
  Convex.relint hC

/-- **Theorem 6.2.** `cl C` has the same affine hull as `C`. No convexity is needed. -/
theorem theorem_6_2_aff_cl (C : Set (Rn n)) : affineSpan ℝ (closure C) = affineSpan ℝ C :=
  affineSpan_closure C

/-- **Theorem 6.2.** `ri C` has the same affine hull as `C`. -/
theorem theorem_6_2_aff_ri (hC : Convex ℝ C) : affineSpan ℝ (ri C) = affineSpan ℝ C :=
  Convex.affineSpan_relint hC

/-- **Theorem 6.2.** `cl C` has the same dimension as `C`. -/
theorem theorem_6_2_dim_cl (C : Set (Rn n)) : dim (closure C) = dim C := by
  rcases C.eq_empty_or_nonempty with rfl | hne
  · simp
  · rw [dim_of_nonempty (hne.mono subset_closure), dim_of_nonempty hne, ← direction_affineSpan,
      ← direction_affineSpan, affineSpan_closure]

/-- **Theorem 6.2.** `ri C` has the same dimension as `C`. -/
theorem theorem_6_2_dim_ri (hC : Convex ℝ C) : dim (ri C) = dim C := by
  rcases C.eq_empty_or_nonempty with rfl | hne
  · simp
  · rw [dim_of_nonempty (Convex.relint_nonempty hC hne), dim_of_nonempty hne,
      ← direction_affineSpan, ← direction_affineSpan, Convex.affineSpan_relint hC]

/-- **Theorem 6.2**, the parenthetical clause: `ri C ≠ ∅` when `C ≠ ∅`. This is the single fact
that makes Part II finite-dimensional; it is false in infinite dimensions, and nothing weaker than
finite-dimensionality will do. -/
theorem theorem_6_2_nonempty (hC : Convex ℝ C) (hne : C.Nonempty) : (ri C).Nonempty :=
  Convex.relint_nonempty hC hne

/-! ### Theorem 6.3 and its corollaries -/

/-- **Theorem 6.3.** For any convex set `C` in `ℝⁿ`, `cl (ri C) = cl C`. -/
theorem theorem_6_3_cl_ri (hC : Convex ℝ C) : closure (ri C) = closure C :=
  Convex.closure_relint hC

/-- **Theorem 6.3.** For any convex set `C` in `ℝⁿ`, `ri (cl C) = ri C`. -/
theorem theorem_6_3_ri_cl (hC : Convex ℝ C) : ri (closure C) = ri C :=
  Convex.relint_closure hC

/-- **Rockafellar, §6 (p. 46).** `ri (ri C) = ri C`: the relative interior of a convex set is
relatively open. The book asserts this for arbitrary sets, before Theorem 6.3; the backbone proves
it for convex sets, through Theorem 6.3. -/
theorem isRelativelyOpen_relint (hC : Convex ℝ C) : IsRelativelyOpen (ri C) :=
  Convex.relint_relint hC

/-- **Corollary 6.3.1.** Let `C₁` and `C₂` be convex sets in `ℝⁿ`. Then
`cl C₁ = cl C₂` if and only if `ri C₁ = ri C₂`. -/
theorem corollary_6_3_1 (h₁ : Convex ℝ C₁) (h₂ : Convex ℝ C₂) :
    closure C₁ = closure C₂ ↔ ri C₁ = ri C₂ :=
  Convex.closure_eq_iff_relint_eq h₁ h₂

/-- **Corollary 6.3.1**, third condition: the two above are equivalent to
`ri C₁ ⊆ C₂ ⊆ cl C₁`. -/
theorem corollary_6_3_1_sandwich (h₁ : Convex ℝ C₁) (h₂ : Convex ℝ C₂) :
    closure C₁ = closure C₂ ↔ ri C₁ ⊆ C₂ ∧ C₂ ⊆ closure C₁ := by
  constructor
  · intro h
    refine ⟨?_, h ▸ subset_closure⟩
    rw [(Convex.closure_eq_iff_relint_eq h₁ h₂).1 h]
    exact intrinsicInterior_subset
  · rintro ⟨hsub, hsup⟩
    exact (Convex.closure_eq_of_relint_subset_of_subset_closure h₁ hsub hsup).symm

/-- **Corollary 6.3.2.** If `C` is a convex set in `ℝⁿ`, then every open set which
meets `cl C` also meets `ri C`. -/
theorem corollary_6_3_2 (hC : Convex ℝ C) {U : Set (Rn n)} (hU : IsOpen U)
    (h : (U ∩ closure C).Nonempty) : (U ∩ ri C).Nonempty :=
  Convex.relint_inter_nonempty_of_isOpen hC hU h

/-- A non-empty convex set inside `cl C₂` whose affine hull is that of `C₂` already meets
`ri C₂`: a relative interior point of `C₁` has a ball of `aff C₁ = aff C₂` around it inside `C₁`,
and `cl C₂ = cl (ri C₂)` puts a point of `ri C₂` in that ball. The step Corollary 6.3.3 needs. -/
theorem inter_relint_nonempty_of_affineSpan_eq (h₁ : Convex ℝ C₁) (hne₁ : C₁.Nonempty)
    (h₂ : Convex ℝ C₂) (hsub : C₁ ⊆ closure C₂) (hspan : affineSpan ℝ C₁ = affineSpan ℝ C₂) :
    (C₁ ∩ ri C₂).Nonempty := by
  obtain ⟨z, hz⟩ := Convex.relint_nonempty h₁ hne₁
  have hzC₁ : z ∈ C₁ := intrinsicInterior_subset hz
  rw [mem_intrinsicInterior_iff] at hz
  obtain ⟨-, ε, hε, hball⟩ := hz
  have hzcl : z ∈ closure (ri C₂) := by
    rw [Convex.closure_relint h₂]
    exact hsub hzC₁
  obtain ⟨w, hw, hzw⟩ := Metric.mem_closure_iff.1 hzcl ε hε
  refine ⟨w, hball w ?_ (by rwa [dist_comm]), hw⟩
  rw [hspan]
  exact subset_affineSpan ℝ C₂ (intrinsicInterior_subset hw)

/-- **Corollary 6.3.3.** A convex subset `C₁` of the relative boundary of a non-empty convex set
`C₂` has `dim C₁ < dim C₂`. -/
theorem corollary_6_3_3 (h₁ : Convex ℝ C₁) (h₂ : Convex ℝ C₂) (hne₂ : C₂.Nonempty)
    (hsub : C₁ ⊆ relbd C₂) : dim C₁ < dim C₂ := by
  have hcl : C₁ ⊆ closure C₂ := fun x hx => (hsub hx).1
  have hdisj : ∀ x ∈ C₁, x ∉ ri C₂ := fun x hx => (hsub hx).2
  rcases C₁.eq_empty_or_nonempty with rfl | hne₁
  · rw [dim_empty, dim_of_nonempty hne₂]
    omega
  have hle : vectorSpan ℝ C₁ ≤ vectorSpan ℝ C₂ := by
    have h := vectorSpan_mono ℝ hcl
    rwa [← direction_affineSpan, ← direction_affineSpan, affineSpan_closure,
      direction_affineSpan, direction_affineSpan] at h
  rw [dim_of_nonempty hne₁, dim_of_nonempty hne₂, Nat.cast_lt]
  refine lt_of_le_of_ne (Submodule.finrank_mono hle) fun heq => ?_
  have hdir : vectorSpan ℝ C₁ = vectorSpan ℝ C₂ := Submodule.eq_of_le_of_finrank_eq hle heq
  have hspan : affineSpan ℝ C₁ = affineSpan ℝ C₂ := by
    refine AffineSubspace.ext_of_direction_eq ?_ ?_
    · rw [direction_affineSpan, direction_affineSpan, hdir]
    · obtain ⟨x, hx⟩ := hne₁
      exact ⟨x, subset_affineSpan ℝ C₁ hx,
        Tdaf.ConvexAnalysis.closure_subset_affineSpan C₂ (hcl hx)⟩
  obtain ⟨x, hx₁, hx₂⟩ := inter_relint_nonempty_of_affineSpan_eq h₁ hne₁ h₂ hcl hspan
  exact hdisj x hx₁ hx₂

/-! ### Theorem 6.4: the prolongation criterion -/

/-- **Theorem 6.4.** Let `C` be a non-empty convex set in `ℝⁿ`. Then `z ∈ ri C` if and
only if, for every `x ∈ C`, there exists a `μ > 1` such that `(1 - μ) x + μ z` belongs to `C`. -/
theorem theorem_6_4 (hC : Convex ℝ C) (hne : C.Nonempty) {z : Rn n} :
    z ∈ ri C ↔ ∀ x ∈ C, ∃ μ > (1 : ℝ), (1 - μ) • x + μ • z ∈ C :=
  Convex.mem_relint_iff_prolong hC hne

/-- **Corollary 6.4.1.** Let `C` be a convex set in `ℝⁿ`. Then `z ∈ int C` if and only
if, for every `y ∈ ℝⁿ`, there exists some `ε > 0` such that `z + ε y ∈ C`. -/
theorem corollary_6_4_1 (hC : Convex ℝ C) {z : Rn n} :
    z ∈ interior C ↔ ∀ y : Rn n, ∃ ε : ℝ, 0 < ε ∧ z + ε • y ∈ C :=
  Convex.mem_interior_iff_absorbs hC

/-! ### Theorem 6.5: intersections -/

/-- **Theorem 6.5**, the closure formula. Let `Cᵢ` be a convex set in `ℝⁿ` for
`i ∈ I`. Suppose that the sets `ri Cᵢ` have at least one point in common. Then
`cl ⋂ᵢ Cᵢ = ⋂ᵢ cl Cᵢ`. The index set is arbitrary. -/
theorem theorem_6_5_cl {ι : Type*} {C : ι → Set (Rn n)} (hC : ∀ i, Convex ℝ (C i))
    (h : (⋂ i, ri (C i)).Nonempty) : closure (⋂ i, C i) = ⋂ i, closure (C i) :=
  Convex.closure_iInter hC h

/-- **Theorem 6.5**, the relative interior formula: if in addition `I` is finite,
`ri ⋂ᵢ Cᵢ = ⋂ᵢ ri Cᵢ`. Finiteness cannot be dropped — the book's own counterexample is the family
`[0, 1 + α]` for `α > 0`. -/
theorem theorem_6_5_ri {ι : Type*} [Finite ι] {C : ι → Set (Rn n)} (hC : ∀ i, Convex ℝ (C i))
    (h : (⋂ i, ri (C i)).Nonempty) : ri (⋂ i, C i) = ⋂ i, ri (C i) :=
  Convex.relint_iInter hC h

/-- **Corollary 6.5.1.** Let `C` be a convex set, and let `M` be an affine set (such
as a line or a hyperplane) which contains a point of `ri C`. Then `ri (M ∩ C) = M ∩ ri C`. -/
theorem corollary_6_5_1_ri (hC : Convex ℝ C) {M : Set (Rn n)} (hM : IsAffineSet M)
    (h : (M ∩ ri C).Nonempty) : ri (M ∩ C) = M ∩ ri C := by
  have key := Convex.relint_inter_affine (M := hM.toAffineSubspace) hC
    (by rwa [hM.coe_toAffineSubspace])
  rwa [hM.coe_toAffineSubspace] at key

/-- **Corollary 6.5.1**, the closure half: `cl (M ∩ C) = M ∩ cl C`. -/
theorem corollary_6_5_1_cl (hC : Convex ℝ C) {M : Set (Rn n)} (hM : IsAffineSet M)
    (h : (M ∩ ri C).Nonempty) : closure (M ∩ C) = M ∩ closure C := by
  have key := Convex.closure_inter_affine (M := hM.toAffineSubspace) hC
    (by rwa [hM.coe_toAffineSubspace])
  rwa [hM.coe_toAffineSubspace] at key

/-- **Corollary 6.5.2.** For convex `C₂ ⊆ cl C₁` not entirely contained in the relative boundary
of `C₁`, `ri C₂ ⊆ ri C₁`. The hypothesis is the positive reading `(C₂ ∩ ri C₁).Nonempty` of "not
entirely contained in the relative boundary". -/
theorem corollary_6_5_2 (h₁ : Convex ℝ C₁) (h₂ : Convex ℝ C₂) (hsub : C₂ ⊆ closure C₁)
    (hnb : ¬ C₂ ⊆ relbd C₁) : ri C₂ ⊆ ri C₁ := by
  refine Convex.relint_subset_relint_of_subset_closure h₁ h₂ hsub ?_
  by_contra hem
  refine hnb fun x hx => ⟨hsub hx, fun hx₁ => hem ⟨x, hx, hx₁⟩⟩

/-! ### Theorem 6.6: images under a linear transformation -/

/-- **Theorem 6.6.** Let `C` be a convex set in `ℝⁿ`, and let `A` be a linear
transformation from `ℝⁿ` to `ℝᵐ`. Then `ri (AC) = A (ri C)`. -/
theorem theorem_6_6_ri (hC : Convex ℝ C) (A : Rn n →ₗ[ℝ] Rn m) : ri (A '' C) = A '' ri C :=
  Convex.relint_image hC A

/-- **Theorem 6.6.** `cl (AC) ⊇ A (cl C)`. This is just continuity of `A` and needs
no convexity. -/
theorem theorem_6_6_cl (C : Set (Rn n)) (A : Rn n →ₗ[ℝ] Rn m) :
    A '' closure C ⊆ closure (A '' C) :=
  image_closure_subset C A

/-- **Corollary 6.6.1.** For any convex set `C` and any real number `λ`,
`ri (λ C) = λ (ri C)`. -/
theorem corollary_6_6_1 (hC : Convex ℝ C) (l : ℝ) : ri (l • C) = l • ri C :=
  Convex.relint_smul hC l

/-- **Rockafellar, §6 (p. 49).** The direct-sum formula the book calls "elementary":
`ri (C₁ ⊕ C₂) = ri C₁ ⊕ ri C₂`. -/
theorem relint_prod (D₁ : Set (Rn n)) (D₂ : Set (Rn m)) :
    ri (D₁ ×ˢ D₂) = ri D₁ ×ˢ ri D₂ :=
  intrinsicInterior_prod_eq D₁ D₂

/-- **Rockafellar, §6 (p. 49).** `cl (C₁ ⊕ C₂) = cl C₁ ⊕ cl C₂`. -/
theorem closure_prod (D₁ : Set (Rn n)) (D₂ : Set (Rn m)) :
    closure (D₁ ×ˢ D₂) = closure D₁ ×ˢ closure D₂ :=
  closure_prod_eq

/-- **Corollary 6.6.2.** For any convex sets `C₁` and `C₂` in `ℝⁿ`,
`ri (C₁ + C₂) = ri C₁ + ri C₂`. -/
theorem corollary_6_6_2_ri (h₁ : Convex ℝ C₁) (h₂ : Convex ℝ C₂) :
    ri (C₁ + C₂) = ri C₁ + ri C₂ :=
  Convex.relint_add h₁ h₂

/-- **Corollary 6.6.2.** `cl (C₁ + C₂) ⊇ cl C₁ + cl C₂`. No convexity is needed. Corollary 9.1.1
sharpens this to an equality. -/
theorem corollary_6_6_2_cl (D₁ D₂ : Set (Rn n)) :
    closure D₁ + closure D₂ ⊆ closure (D₁ + D₂) :=
  closure_add_subset D₁ D₂

/-! ### Theorem 6.7: inverse images under a linear transformation -/

/-- **Theorem 6.7.** Let `A` be a linear transformation from `ℝⁿ` to `ℝᵐ`. Let `C` be
a convex set in `ℝᵐ` such that `A⁻¹(ri C) ≠ ∅`. Then `ri (A⁻¹C) = A⁻¹(ri C)`. -/
theorem theorem_6_7_ri {D : Set (Rn m)} (hD : Convex ℝ D) (A : Rn n →ₗ[ℝ] Rn m)
    (h : (A ⁻¹' ri D).Nonempty) : ri (A ⁻¹' D) = A ⁻¹' ri D :=
  Convex.relint_preimage hD A h

/-- **Theorem 6.7.** Under the same hypothesis, `cl (A⁻¹C) = A⁻¹(cl C)`. -/
theorem theorem_6_7_cl {D : Set (Rn m)} (hD : Convex ℝ D) (A : Rn n →ₗ[ℝ] Rn m)
    (h : (A ⁻¹' ri D).Nonempty) : closure (A ⁻¹' D) = A ⁻¹' closure D :=
  Convex.closure_preimage hD A h

/-! ### Theorem 6.8: slices of a convex set in a product -/

/-- **Theorem 6.8.** For convex `C ⊆ ℝᵐ⁺ᵖ` with slices `C_y = {z | (y, z) ∈ C}` and
`D = {y | C_y ≠ ∅}`, `(y, z) ∈ ri C` iff `y ∈ ri D` and `z ∈ ri C_y`. -/
theorem theorem_6_8 {C : Set (Rn m × Rn p)} (hC : Convex ℝ C) (y : Rn m) (z : Rn p) :
    (y, z) ∈ ri C ↔
      y ∈ ri {u : Rn m | {w : Rn p | (u, w) ∈ C}.Nonempty} ∧ z ∈ ri {w : Rn p | (y, w) ∈ C} := by
  have hD : {u : Rn m | {w : Rn p | (u, w) ∈ C}.Nonempty} = Prod.fst '' C := by
    ext u
    constructor
    · rintro ⟨w, hw⟩
      exact ⟨(u, w), hw, rfl⟩
    · rintro ⟨q, hq, rfl⟩
      exact ⟨q.2, hq⟩
  rw [hD]
  exact Convex.mem_relint_prod_iff hC

/-- **Corollary 6.8.1.** The convex cone `K` in `ℝⁿ⁺¹` generated by
`{(1, x) | x ∈ C}`. Rockafellar's cones need not contain the origin, so `K` is the set of positive
multiples of the cross-section, and nothing more. -/
def coneOver (C : Set (Rn n)) : Set (ℝ × Rn n) := {q | 0 < q.1 ∧ q.2 ∈ q.1 • C}

/-- The bridge: `coneOver C` is exactly the set of positive multiples of `{(1, x) | x ∈ C}`, which
is what Corollary 2.6.3 identifies as the smallest convex cone containing that set. -/
theorem mem_coneOver_iff {q : ℝ × Rn n} :
    q ∈ coneOver C ↔ ∃ l : ℝ, 0 < l ∧ ∃ x ∈ C, l • ((1 : ℝ), x) = q := by
  constructor
  · rintro ⟨hq, x, hx, hxq⟩
    exact ⟨q.1, hq, x, hx, Prod.ext (by simp) (by simpa using hxq)⟩
  · rintro ⟨l, hl, x, hx, rfl⟩
    exact ⟨by simpa using hl, x, hx, by simp⟩

/-- `coneOver C` is convex when `C` is: it is the intersection of the backbone's cone (which
carries the origin) with the open half-space `{q | 0 < q.1}`. -/
theorem convex_coneOver (hC : Convex ℝ C) : Convex ℝ (coneOver C) := by
  have hhalf : Convex ℝ {q : ℝ × Rn n | 0 < q.1} :=
    convex_halfSpace_gt (LinearMap.fst ℝ ℝ (Rn n)).isLinear 0
  have hset : coneOver C = insert 0 (coneOver C) ∩ {q : ℝ × Rn n | 0 < q.1} := by
    ext q
    constructor
    · exact fun hq => ⟨Set.mem_insert_of_mem _ hq, hq.1⟩
    · rintro ⟨hq | hq, hq'⟩
      · rw [hq] at hq'
        simp at hq'
      · exact hq
  rw [hset]
  exact _root_.Convex.inter (convex_cone_prodMk_one hC) hhalf

/-- **Corollary 6.8.1.** For non-empty convex `C` and `K` the convex cone in `ℝⁿ⁺¹` generated by
`{(1, x) | x ∈ C}`, `ri K` is the set of `(λ, x)` with `λ > 0` and `x ∈ λ (ri C)`. -/
theorem corollary_6_8_1 (hC : Convex ℝ C) (hne : C.Nonempty) :
    ri (coneOver C) = {q : ℝ × Rn n | 0 < q.1 ∧ q.2 ∈ q.1 • ri C} := by
  have hconv0 : Convex ℝ (insert 0 (coneOver C)) := convex_cone_prodMk_one hC
  have hri : ri (insert 0 (coneOver C)) = {q : ℝ × Rn n | 0 < q.1 ∧ q.2 ∈ q.1 • ri C} :=
    Convex.relint_cone_prodMk_one hC hne
  have hsub : ri (insert 0 (coneOver C)) ⊆ coneOver C := by
    rw [hri]
    rintro q ⟨h1, h2⟩
    exact ⟨h1, Set.smul_set_mono intrinsicInterior_subset h2⟩
  have hsup : coneOver C ⊆ closure (insert 0 (coneOver C)) :=
    (Set.subset_insert _ _).trans subset_closure
  have hcl := Convex.closure_eq_of_relint_subset_of_subset_closure hconv0 hsub hsup
  rw [← hri]
  exact (Convex.closure_eq_iff_relint_eq (convex_coneOver hC) hconv0).1 hcl

/-! ### Theorem 6.9 -/

/-- **Theorem 6.9**, for two sets. For non-empty convex `C₁`, `C₂` and `C₀ = conv (C₁ ∪ C₂)`,
`ri C₀ = ⋃ {λ₁ ri C₁ + λ₂ ri C₂ | λᵢ > 0, λ₁ + λ₂ = 1}`, the union written in the parametrised
form `λ₁ = 1 - a`, `λ₂ = a` with `a ∈ (0, 1)`. The book states the theorem for `m` sets. -/
theorem theorem_6_9 (h₁ : Convex ℝ C₁) (hne₁ : C₁.Nonempty) (h₂ : Convex ℝ C₂)
    (hne₂ : C₂.Nonempty) :
    ri (convexHull ℝ (C₁ ∪ C₂)) =
      ⋃ (l₁ : ℝ) (l₂ : ℝ) (_ : 0 < l₁) (_ : 0 < l₂) (_ : l₁ + l₂ = 1),
        (l₁ • ri C₁ + l₂ • ri C₂) := by
  rw [Convex.relint_convexHull_union h₁ hne₁ h₂ hne₂]
  ext x
  simp only [Set.mem_iUnion, Set.mem_Ioo, exists_prop]
  constructor
  · rintro ⟨a, ⟨ha₀, ha₁⟩, hx⟩
    exact ⟨1 - a, a, by linarith, ha₀, by ring, hx⟩
  · rintro ⟨l₁, l₂, hl₁, hl₂, hl, hx⟩
    refine ⟨l₂, ⟨hl₂, by linarith⟩, ?_⟩
    rw [show (1 : ℝ) - l₂ = l₁ by linarith]
    exact hx

/-! ### The relatively open sets of §6

The book closes the section (p. 49) by noting that relative openness is preserved by the operations
above, and that the relative interior and the closure of a convex cone are again convex cones. -/

/-- **Rockafellar, §6 (p. 49).** The class of relatively open convex sets is preserved under finite
intersections, provided the relative interiors meet — which for relatively open sets is just
non-emptiness of the intersection. -/
theorem isRelativelyOpen_iInter {ι : Type*} [Finite ι] {C : ι → Set (Rn n)}
    (hC : ∀ i, Convex ℝ (C i)) (hopen : ∀ i, IsRelativelyOpen (C i))
    (h : (⋂ i, C i).Nonempty) : IsRelativelyOpen (⋂ i, C i) := by
  have hopen' : ∀ i, ri (C i) = C i := fun i => (isRelativelyOpen_iff).1 (hopen i)
  have heq : (⋂ i, ri (C i)) = ⋂ i, C i := Set.iInter_congr hopen'
  refine isRelativelyOpen_iff.2 ?_
  rw [Convex.relint_iInter hC (heq ▸ h), heq]

/-- **Rockafellar, §6 (p. 49).** The class of relatively open convex sets is preserved under
addition. -/
theorem isRelativelyOpen_add (h₁ : Convex ℝ C₁) (h₂ : Convex ℝ C₂)
    (ho₁ : IsRelativelyOpen C₁) (ho₂ : IsRelativelyOpen C₂) : IsRelativelyOpen (C₁ + C₂) := by
  refine isRelativelyOpen_iff.2 ?_
  rw [Convex.relint_add h₁ h₂, isRelativelyOpen_iff.1 ho₁, isRelativelyOpen_iff.1 ho₂]

/-- **Rockafellar, §6 (p. 50).** The relative interior of a convex cone is a convex cone. This is
immediate from Corollary 6.6.1, because a convex set `C` is a cone exactly when `λ C = C` for every
`λ > 0` (§2's `isCone_iff_smul_set_eq`). -/
theorem isCone_relint (hK : IsCone C) (hC : Convex ℝ C) : IsCone (ri C) := by
  rw [isCone_iff_smul_set_eq] at hK ⊢
  intro a ha
  rw [← Convex.relint_smul hC a, hK a ha]

/-- **Rockafellar, §6 (p. 50).** The closure of a convex cone is a convex cone. Convexity is not
used on either side. -/
theorem isCone_closure (hK : IsCone C) : IsCone (closure C) := by
  rw [isCone_iff_smul_set_eq] at hK ⊢
  exact smul_closure_eq_of_isCone hK

end Rockafellar
