kind = 'module'
title = 'Subgradients, normal cones and directional derivatives'
module = 'Tdaf.Analysis.Convex.Subgradient.Defs'
namespace = 'Tdaf.ConvexAnalysis'

[[node]]
id = 'subgradient'

[[node]]
id = 'subgradientRel'

[[node]]
id = 'normalCone'

[[node]]
id = 'normalPointedCone'

[[node]]
id = 'domSubgradient'

[[node]]
id = 'Proper.mem_subgradient_tfae'

[[node]]
id = 'proper_of_mem_subgradient'

[[node]]
id = 'subgradient_indicatorFn'

[[node]]
id = 'dirDeriv'

[[node]]
id = 'posHomogeneous_dirDeriv'

[[node]]
id = 'monotoneOn_sub_div'

[[node]]
id = 'convexFn_dirDeriv'

[[node]]
id = 'mem_subgradient_iff_le_dirDeriv'

[[node]]
id = 'conj_dirDeriv'

[[node]]
id = 'subgradientRel_conj_eq_inv'

[[node]]
id = 'subgradient_clFn'

[[node]]
id = 'subgradient_supportFn'

[[node]]
id = 'clFn_dirDeriv'
