kind = 'module'
title = 'The Legendre transformation'
module = 'Tdaf.Analysis.Convex.Subgradient.Legendre'
namespace = 'Tdaf.ConvexAnalysis'

[[node]]
id = 'conj_eq_of_hasGradientAt'

[[node]]
id = 'legendreDom'

[[node]]
id = 'legendreDom_subset_dom_conj'
