/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Tdaf.Analysis.Convex.Operations.Hull
import Tdaf.Analysis.Convex.Recession.Closedness

/-!
# The convex cone generated by a convex set

Three closure theorems of the same shape: generate a cone, or a positively homogeneous function,
from a convex object and ask when the result is closed. For closed convex `C` with `0 ∉ C`, the
cone generated by `C` differs from its closure only by `0⁺C`. For closed proper convex `f` with
`f 0 > 0`, the closure of the positively homogeneous convex function generated by `f` is the
*attained* infimum `inf {fλ | λ > 0 or λ = 0⁺}`. And `conv (C ∪ D)` is closed once directions of
recession of `C` and of `D` can cancel only inside the lineality spaces. All three come from the
closed-image and sum theorems, read off the cone `{(λ, x) | λ > 0, x ∈ λC}` one dimension up,
around which the file is organised.

## Main definitions

* `closedConeOver C` — `{(λ, x) | λ > 0, x ∈ λ • C} ∪ ({0} ×ˢ 0⁺C)` in `ℝ × E`. Named for its
  conclusion: for nonempty closed convex `C` it *is* the closure of the cone generated by the copy
  of `C` at height one (`closure_coe_hull_prodMk_one`).
* `posHomGen f` — the positively homogeneous convex function generated by `f`: `ofEpi K` for `K`
  the convex cone generated by `epi f`, and the greatest positively homogeneous convex minorant of
  `f` that is nonpositive at the origin (`posHomGen_isGreatest`).

## Main results

* `coe_hull_of_convex` — for *convex* `S` the cone generated by `S` is `{0} ∪ ⋃ {t • S | t > 0}`,
  with no convex combinations; `coe_hull_convexHull` absorbs `convexHull`.
* `closure_coe_hull` — `cl (cone C) = ⋃ {t • C | t > 0} ∪ 0⁺C` (Theorem 9.6 in [^1]), with
  `isClosed_coe_hull_of_isBounded` for bounded `C`.
* `epi_lscHull_posHomGen`, `lscHull_posHomGen`, `proper_posHomGen` — the epigraph
  form `epi (cl k) = ⋃ {epi (fλ) | λ > 0} ∪ epi (f0⁺)` is the pointwise formula together with the
  attainment of its infimum. If `0 ∈ dom f` then `k` is already closed and `λ = 0⁺` may be dropped
  (`lscHull_posHomGen_eq`, `posHomGen_eq_iInf_smulRight`).
* `closure_convexHull_union`, `recessionCone_closure_convexHull_union` —
  `cl (conv (C ∪ D)) = conv (C ∪ D) + (0⁺C + 0⁺D)` and `0⁺(cl (conv (C ∪ D))) = 0⁺C + 0⁺D`
  (Theorem 9.8 in [^1]); `isClosed_convexHull_union_of_recessionCone_eq` is the case of equal
  recession cones, and `closedProperConvexFn_convFn₂` carries it to functions.

## Implementation notes

`PointedCone.hull ℝ` is `Submodule.span ℝ≥0`, built from finite `ℝ≥0`-combinations;
`coe_hull_of_convex` is the bridge to `{0} ∪ ⋃_{t>0} tC`, and is what the rest of the file uses.

## References

[^1]: R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §8 and §9.
-/

open Filter Pointwise Set Topology

namespace Tdaf.ConvexAnalysis

/-! ### Auxiliary facts about `epi` and `ofEpi`

General facts about the epi-closure operator `F ↦ epi (ofEpi F)`, used below for the positively
homogeneous convex function generated by `f`. -/

section Aux

variable {E : Type*}

/-- **The epi-closure is the least epi-like set containing `F`.** This is `epiClosure`-minimality,
and it is what turns "`F ⊆ G` with `G` an epigraph" into `epi (ofEpi F) ⊆ G`. -/
theorem epi_ofEpi_subset_of_isEpiLike {F G : Set (E × ℝ)} (hFG : F ⊆ G) (hG : IsEpiLike G) :
    epi (ofEpi F) ⊆ G := by
  have h := epi_anti (ofEpi_mono hFG)
  rwa [epi_ofEpi hG] at h

/-- `ofEpi` turns unions into infima: it is the left adjoint of the antitone Galois connection
`gc_ofEpi_epi`, so it carries suprema of sets to infima of functions. -/
theorem ofEpi_iUnion {ι : Sort*} (F : ι → Set (E × ℝ)) :
    ofEpi (⋃ i, F i) = ⨅ i, ofEpi (F i) := by
  refine le_antisymm (le_iInf fun i => ofEpi_mono (Set.subset_iUnion F i)) fun x => ?_
  rw [iInf_apply]
  refine le_ofEpi fun μ hμ => ?_
  obtain ⟨i, hi⟩ := Set.mem_iUnion.1 hμ
  exact (iInf_le _ i).trans (ofEpi_apply_le hi)

/-- The binary form of `ofEpi_iUnion`. -/
theorem ofEpi_union (F G : Set (E × ℝ)) : ofEpi (F ∪ G) = ofEpi F ⊓ ofEpi G := by
  refine le_antisymm (le_inf (ofEpi_mono Set.subset_union_left)
    (ofEpi_mono Set.subset_union_right)) fun x => ?_
  refine le_ofEpi fun μ hμ => ?_
  rcases hμ with h | h
  · exact (inf_le_left (a := ofEpi F) (b := ofEpi G) x).trans (ofEpi_apply_le h)
  · exact (inf_le_right (a := ofEpi F) (b := ofEpi G) x).trans (ofEpi_apply_le h)

end Aux

section AuxModule

variable {E : Type*} [AddCommGroup E] [Module ℝ E]

/-- Positive scaling commutes with the epi-closure. Both sides are the epigraph of `(ofEpi F) a`;
the proof only uses that `a • epi g` is an epigraph for `a > 0` (`epi_smulRight`). -/
theorem smul_epi_ofEpi {a : ℝ} (ha : 0 < a) (F : Set (E × ℝ)) :
    a • epi (ofEpi F) = epi (ofEpi (a • F)) := by
  have key : ∀ b : ℝ, 0 < b → ∀ G : Set (E × ℝ), epi (ofEpi (b • G)) ⊆ b • epi (ofEpi G) := by
    intro b hb G
    refine epi_ofEpi_subset_of_isEpiLike (Set.smul_set_mono (subset_epi_ofEpi G)) ?_
    rw [← epi_smulRight hb]
    exact isEpiLike_epi _
  refine subset_antisymm ?_ (key a ha F)
  have h := key a⁻¹ (inv_pos.2 ha) (a • F)
  rw [smul_smul, inv_mul_cancel₀ (ne_of_gt ha), one_smul] at h
  intro p hp
  obtain ⟨q, hq, hqp⟩ := hp
  have hq' : a • q = p := hqp
  obtain ⟨r, hr, hrq⟩ := h hq
  have hrq' : a⁻¹ • r = q := hrq
  have hrp : r = p := by rw [← hq', ← hrq', smul_smul, mul_inv_cancel₀ (ne_of_gt ha), one_smul]
  rwa [hrp] at hr

end AuxModule

section Hull

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {S : Set E}

/-- The convex cone generated by a *convex* set is the union of its positive multiples together
with the origin. -/
theorem coe_hull_of_convex (hS : Convex ℝ S) :
    (PointedCone.hull ℝ S : Set E) = insert 0 {y | ∃ t : ℝ, 0 < t ∧ y ∈ t • S} := by
  refine subset_antisymm (fun y hy => ?_) (fun y hy => ?_)
  · induction hy using Submodule.span_induction with
    | mem z hz => exact Or.inr ⟨1, one_pos, z, hz, one_smul ℝ z⟩
    | zero => exact Or.inl rfl
    | add y z _ _ ihy ihz =>
        rcases ihy with rfl | ⟨t₁, ht₁, a, ha, hay⟩
        · simpa using ihz
        rcases ihz with rfl | ⟨t₂, ht₂, b, hb, hbz⟩
        · exact Or.inr ⟨t₁, ht₁, a, ha, by rw [hay, add_zero]⟩
        have hay' : t₁ • a = y := hay
        have hbz' : t₂ • b = z := hbz
        have hsum : (0 : ℝ) < t₁ + t₂ := by linarith
        refine Or.inr ⟨t₁ + t₂, hsum, (t₁ / (t₁ + t₂)) • a + (t₂ / (t₁ + t₂)) • b, ?_, ?_⟩
        · exact hS ha hb (by positivity) (by positivity) (by field_simp)
        · have e₁ : (t₁ + t₂) * (t₁ / (t₁ + t₂)) = t₁ := by field_simp
          have e₂ : (t₁ + t₂) * (t₂ / (t₁ + t₂)) = t₂ := by field_simp
          have h : (t₁ + t₂) • ((t₁ / (t₁ + t₂)) • a + (t₂ / (t₁ + t₂)) • b) = y + z := by
            rw [smul_add, smul_smul, smul_smul, e₁, e₂, hay', hbz']
          exact h
    | smul c y _ ih =>
        rcases ih with rfl | ⟨t, ht, a, ha, hay⟩
        · exact Or.inl (by simp)
        rcases eq_or_lt_of_le c.2 with hc | hc
        · refine Or.inl ?_
          have h : ((c : ℝ)) • y = (0 : E) := by rw [← hc, zero_smul]
          exact h
        refine Or.inr ⟨(c : ℝ) * t, mul_pos hc ht, a, ha, ?_⟩
        have hay' : t • a = y := hay
        have h : ((c : ℝ) * t) • a = (c : ℝ) • y := by rw [mul_smul, hay']
        exact h
  · rcases hy with rfl | ⟨t, ht, a, ha, hay⟩
    · exact Submodule.zero_mem _
    · have hay' : t • a = y := hay
      rw [← hay']
      exact Submodule.smul_mem _ (⟨t, ht.le⟩ : {c : ℝ // 0 ≤ c}) (PointedCone.subset_hull ha)

theorem mem_coe_hull_iff_of_convex (hS : Convex ℝ S) {y : E} :
    y ∈ (PointedCone.hull ℝ S : Set E) ↔ y = 0 ∨ ∃ t : ℝ, 0 < t ∧ y ∈ t • S := by
  rw [coe_hull_of_convex hS]
  exact Iff.rfl

/-- Taking the convex hull first does not change the convex cone generated. -/
theorem coe_hull_convexHull (S : Set E) :
    (PointedCone.hull ℝ (convexHull ℝ S) : Set E) = (PointedCone.hull ℝ S : Set E) := by
  refine subset_antisymm ?_ (Submodule.span_mono (subset_convexHull ℝ S))
  refine Submodule.span_le.2 ?_
  exact convexHull_min PointedCone.subset_hull (PointedCone.hull ℝ S : ConvexCone ℝ E).convex

end Hull

/-! ### The cone over a convex set, one dimension up -/

section LiftOne

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {C : Set E}

theorem convex_prodMk_one_image (hC : Convex ℝ C) : Convex ℝ (Prod.mk (1 : ℝ) '' C) := by
  rintro _ ⟨x, hx, rfl⟩ _ ⟨y, hy, rfl⟩ a b ha hb hab
  refine ⟨a • x + b • y, hC hx hy ha hb hab, ?_⟩
  simp [Prod.smul_mk, Prod.mk_add_mk, smul_eq_mul, hab]

/-- **The convex cone in `ℝ × E` generated by `{1} × C`**, for a convex set `C`: it consists of the
origin together with the pairs `(λ, x)` with `λ > 0` and `x ∈ λC`.

This cone is the homogenisation of `C`, and the closure theorems of this file are all read
off its closure. -/
theorem coe_hull_prodMk_one (hC : Convex ℝ C) :
    (PointedCone.hull ℝ (Prod.mk (1 : ℝ) '' C) : Set (ℝ × E))
      = insert 0 {p : ℝ × E | 0 < p.1 ∧ p.2 ∈ p.1 • C} := by
  rw [coe_hull_of_convex (convex_prodMk_one_image hC)]
  refine congrArg _ (Set.ext fun p => ⟨?_, ?_⟩)
  · rintro ⟨t, ht, q, ⟨x, hx, rfl⟩, rfl⟩
    refine ⟨by simpa using ht, ?_⟩
    have hmem : t • x ∈ t • C := Set.smul_mem_smul_set hx
    simpa using hmem
  · rintro ⟨h1, x, hx, hxp⟩
    have hxp' : p.1 • x = p.2 := hxp
    refine ⟨p.1, h1, ((1 : ℝ), x), ⟨x, hx, rfl⟩, ?_⟩
    exact Prod.ext (by simp) (by simpa using hxp')

/-- The **closed cone over a set** `C ⊆ E`: the pairs `(λ, x)` in `ℝ × E` with `λ > 0` and
`x ∈ λC`, together with `{0} × 0⁺C`. For a nonempty closed convex `C` this is exactly the closure
of the convex cone generated by the copy of `C` at height one
(`closure_coe_hull_prodMk_one`), and the three closure theorems are all read off it. -/
def closedConeOver (C : Set E) : Set (ℝ × E) :=
  {p : ℝ × E | 0 < p.1 ∧ p.2 ∈ p.1 • C} ∪ ({0} ×ˢ recessionCone C)

/-- Membership of `closedConeOver`, as a disjunction on the homogenising coordinate. -/
theorem mem_closedConeOver {p : ℝ × E} :
    p ∈ closedConeOver C ↔
      (0 < p.1 ∧ p.2 ∈ p.1 • C) ∨ (p.1 = 0 ∧ p.2 ∈ recessionCone C) := by
  rw [closedConeOver, Set.mem_union, Set.mem_prod, Set.mem_singleton_iff]
  exact Iff.rfl

@[simp] theorem zero_mem_closedConeOver (C : Set E) : (0 : ℝ × E) ∈ closedConeOver C :=
  mem_closedConeOver.2 (Or.inr ⟨rfl, zero_mem_recessionCone C⟩)

/-- The convex cone generated by `{1} × C` sits inside `closedConeOver C`. -/
theorem coe_hull_prodMk_one_subset (hC : Convex ℝ C) :
    (PointedCone.hull ℝ (Prod.mk (1 : ℝ) '' C) : Set (ℝ × E)) ⊆ closedConeOver C := by
  rw [coe_hull_prodMk_one hC]
  rintro p (rfl | hp)
  · exact zero_mem_closedConeOver C
  · exact mem_closedConeOver.2 (Or.inl hp)

/-- The homogenising coordinate is nonnegative on `closedConeOver C`. -/
theorem fst_nonneg_of_mem_closedConeOver {p : ℝ × E} (hp : p ∈ closedConeOver C) : 0 ≤ p.1 := by
  rcases mem_closedConeOver.1 hp with ⟨h, -⟩ | ⟨h, -⟩
  · exact h.le
  · exact h.ge

/-- The half-line over a point of `C` in a direction of `closedConeOver C`, in the one form that
covers both branches of the disjunction: for `p = (λ, λu)` it is the convex combination
`(1 - aλ) x + aλ u`, and for `p = (0, z)` it is the recession half-line `x + a z`. -/
theorem add_sub_smul_mem_of_mem_closedConeOver (hC : Convex ℝ C) {p : ℝ × E}
    (hp : p ∈ closedConeOver C)
    {x : E} (hx : x ∈ C) {a : ℝ} (ha : 0 ≤ a) (hap : a * p.1 ≤ 1) :
    x + a • p.2 - (a * p.1) • x ∈ C := by
  rcases mem_closedConeOver.1 hp with ⟨hpos, u, hu, hup⟩ | hp
  · have hup' : p.1 • u = p.2 := hup
    have hcomb : (1 - a * p.1) • x + (a * p.1) • u ∈ C :=
      hC hx hu (by linarith) (by positivity) (by ring)
    have heq : (1 - a * p.1) • x + (a * p.1) • u = x + a • p.2 - (a * p.1) • x := by
      rw [← hup', smul_smul, sub_smul, one_smul]
      abel
    rwa [heq] at hcomb
  · obtain ⟨hp1, hp2⟩ := hp
    have hmem : x + a • p.2 ∈ C := hp2 x hx a ha
    simpa [hp1] using hmem

end LiftOne

/-! ### The closed cone over a set -/

section Topological

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] {C : Set E}

/-- `closedConeOver C` is closed when `C` is a closed convex set.

The two branches are separated by the sign of the limit of the homogenising coordinates: when it
is positive the points `(uₙ).1⁻¹ • (uₙ).2` lie in `C` and converge; when it is zero,
`add_sub_smul_mem_of_mem_closedConeOver` passes to the limit and gives the recession half-line. -/
theorem isClosed_closedConeOver (hC : Convex ℝ C) (hCc : IsClosed C) :
    IsClosed (closedConeOver C) := by
  refine IsSeqClosed.isClosed ?_
  intro u p hu hlim
  have hfst : Tendsto (fun n => (u n).1) atTop (𝓝 p.1) := (continuous_fst.tendsto p).comp hlim
  have hsnd : Tendsto (fun n => (u n).2) atTop (𝓝 p.2) := (continuous_snd.tendsto p).comp hlim
  have hnonneg : ∀ n, 0 ≤ (u n).1 := by
    intro n
    rcases mem_closedConeOver.1 (hu n) with ⟨h, -⟩ | ⟨h, -⟩
    · exact h.le
    · exact h.ge
  rcases eq_or_lt_of_le (ge_of_tendsto' hfst hnonneg) with hzero | hpos
  · refine mem_closedConeOver.2 (Or.inr ⟨hzero.symm, ?_⟩)
    intro x hx a ha
    have hcv : Tendsto (fun n => x + a • (u n).2 - (a * (u n).1) • x) atTop
        (𝓝 (x + a • p.2 - (a * p.1) • x)) :=
      (tendsto_const_nhds.add (hsnd.const_smul a)).sub ((tendsto_const_nhds.mul hfst).smul_const x)
    have hev : ∀ᶠ n in atTop, a * (u n).1 ≤ 1 := by
      have hmul : Tendsto (fun n => a * (u n).1) atTop (𝓝 0) := by
        simpa [← hzero] using tendsto_const_nhds.mul hfst
      exact (hmul.eventually_lt_const one_pos).mono fun n hn => hn.le
    have hmem : ∀ᶠ n in atTop, x + a • (u n).2 - (a * (u n).1) • x ∈ C := by
      filter_upwards [hev] with n hn
      exact add_sub_smul_mem_of_mem_closedConeOver hC (hu n) hx ha hn
    have hlimit := hCc.mem_of_tendsto hcv hmem
    rwa [← hzero, mul_zero, zero_smul, sub_zero] at hlimit
  · refine mem_closedConeOver.2 (Or.inl ⟨hpos, ?_⟩)
    have hne : p.1 ≠ 0 := ne_of_gt hpos
    have hcv : Tendsto (fun n => (u n).1⁻¹ • (u n).2) atTop (𝓝 (p.1⁻¹ • p.2)) :=
      (hfst.inv₀ hne).smul hsnd
    have hmem : ∀ᶠ n in atTop, (u n).1⁻¹ • (u n).2 ∈ C := by
      filter_upwards [hfst.eventually_const_lt hpos] with n hn
      rcases mem_closedConeOver.1 (hu n) with ⟨-, h⟩ | ⟨h0, -⟩
      · exact (Set.mem_smul_set_iff_inv_smul_mem₀ (ne_of_gt hn) C _).1 h
      · exact absurd h0 (ne_of_gt hn)
    exact (Set.mem_smul_set_iff_inv_smul_mem₀ hne C p.2).2 (hCc.mem_of_tendsto hcv hmem)

/-- **The closure of the convex cone `K` generated by `{1} × C`**, one dimension up: for a
nonempty closed convex set `C`,

`cl K = K ∪ {(0, x) | x ∈ 0⁺C}`.

The classical proof goes through relative interiors, which needs finite dimensions; this one does
not. `closedConeOver C` is closed, and each `(0, z)` with `z ∈ 0⁺C` is the limit of
`(n+1)⁻¹ • (1, x + (n+1) • z)` for any `x ∈ C`. -/
theorem closure_coe_hull_prodMk_one (hC : Convex ℝ C) (hCc : IsClosed C) (hne : C.Nonempty) :
    closure (PointedCone.hull ℝ (Prod.mk (1 : ℝ) '' C) : Set (ℝ × E)) = closedConeOver C := by
  refine subset_antisymm
    ((isClosed_closedConeOver hC hCc).closure_subset_iff.2 (coe_hull_prodMk_one_subset hC))
    fun p hp => ?_
  rcases mem_closedConeOver.1 hp with hpos | ⟨h0, hrec⟩
  · refine subset_closure ?_
    rw [coe_hull_prodMk_one hC]
    exact Or.inr hpos
  · obtain ⟨x, hx⟩ := hne
    have hseq : ∀ n : ℕ, ((((n : ℝ) + 1)⁻¹, ((n : ℝ) + 1)⁻¹ • (x + ((n : ℝ) + 1) • p.2)) : ℝ × E)
        ∈ (PointedCone.hull ℝ (Prod.mk (1 : ℝ) '' C) : Set (ℝ × E)) := by
      intro n
      rw [coe_hull_prodMk_one hC]
      exact Or.inr ⟨by positivity, Set.smul_mem_smul_set (hrec x hx _ (by positivity))⟩
    have hlim : Tendsto
        (fun n : ℕ => ((((n : ℝ) + 1)⁻¹, ((n : ℝ) + 1)⁻¹ • (x + ((n : ℝ) + 1) • p.2)) : ℝ × E))
        atTop (𝓝 (((0 : ℝ), p.2) : ℝ × E)) :=
      tendsto_inv_nat_add_one_atTop_nhds_zero.prodMk_nhds (tendsto_inv_smul_ray x p.2)
    have hmem := mem_closure_of_tendsto hlim (Eventually.of_forall hseq)
    rwa [show (((0 : ℝ), p.2) : ℝ × E) = p from Prod.ext h0.symm rfl] at hmem

/-- `closedConeOver C` is convex when `C` is a nonempty closed convex set: it is the closure of a
convex cone. -/
theorem convex_closedConeOver (hC : Convex ℝ C) (hCc : IsClosed C) (hne : C.Nonempty) :
    Convex ℝ (closedConeOver C) := by
  rw [← closure_coe_hull_prodMk_one hC hCc hne]
  exact ((PointedCone.hull ℝ (Prod.mk (1 : ℝ) '' C) : ConvexCone ℝ (ℝ × E)).convex).closure

end Topological

/-! ### The slices of a sum of two cones -/

section Slices

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {C D : Set E}

/-- **The level-zero slice of `closedConeOver C + closedConeOver D`** is `0⁺C + 0⁺D`: the two
homogenising coordinates are nonnegative and sum to zero, so both vanish. -/
theorem mem_recessionCone_add_of_mk_zero_mem {y : E}
    (h : (((0 : ℝ), y) : ℝ × E) ∈ closedConeOver C + closedConeOver D) :
    y ∈ recessionCone C + recessionCone D := by
  obtain ⟨q, hq, r, hr, hqr⟩ := h
  have hqr' : q + r = (((0 : ℝ), y) : ℝ × E) := hqr
  have h1 : q.1 + r.1 = 0 := congrArg Prod.fst hqr'
  have hq0 := fst_nonneg_of_mem_closedConeOver hq
  have hr0 := fst_nonneg_of_mem_closedConeOver hr
  have hq1 : q.1 = 0 := by linarith
  have hr1 : r.1 = 0 := by linarith
  refine ⟨q.2, ?_, r.2, ?_, congrArg Prod.snd hqr'⟩
  · rcases mem_closedConeOver.1 hq with ⟨hpos, -⟩ | ⟨-, h2⟩
    · exact absurd hq1 (ne_of_gt hpos)
    · exact h2
  · rcases mem_closedConeOver.1 hr with ⟨hpos, -⟩ | ⟨-, h2⟩
    · exact absurd hr1 (ne_of_gt hpos)
    · exact h2

/-- **The level-one slice of `closedConeOver C + closedConeOver D`** is contained in
`conv (C ∪ D) + (0⁺C + 0⁺D)`: the two homogenising coordinates are nonnegative and sum to one, so
they are the weights of a convex combination, with a vanishing weight contributing a direction of
recession instead. This is the classical `⋃ {λ₁C₁ + λ₂C₂ | λᵢ ≥ 0⁺, λ₁ + λ₂ = 1}`, written without
the `λᵢ = 0⁺` convention. -/
theorem mem_convexHull_add_of_mk_one_mem {x : E}
    (h : (((1 : ℝ), x) : ℝ × E) ∈ closedConeOver C + closedConeOver D) :
    x ∈ convexHull ℝ (C ∪ D) + (recessionCone C + recessionCone D) := by
  obtain ⟨q, hq, r, hr, hqr⟩ := h
  have hqr' : q + r = (((1 : ℝ), x) : ℝ × E) := hqr
  have h1 : q.1 + r.1 = 1 := congrArg Prod.fst hqr'
  have h2 : q.2 + r.2 = x := congrArg Prod.snd hqr'
  have hq0 := fst_nonneg_of_mem_closedConeOver hq
  have hr0 := fst_nonneg_of_mem_closedConeOver hr
  rcases mem_closedConeOver.1 hq with ⟨-, a, ha, haq⟩ | ⟨hqz, hqrec⟩
  · have haq' : q.1 • a = q.2 := haq
    rcases mem_closedConeOver.1 hr with ⟨-, b, hb, hbr⟩ | ⟨hrz, hrrec⟩
    · have hbr' : r.1 • b = r.2 := hbr
      refine ⟨x, ?_, 0, ⟨0, zero_mem_recessionCone C, 0, zero_mem_recessionCone D, add_zero 0⟩,
        add_zero x⟩
      rw [← h2, ← haq', ← hbr']
      exact convex_convexHull ℝ (C ∪ D) (subset_convexHull ℝ _ (Or.inl ha))
        (subset_convexHull ℝ _ (Or.inr hb)) hq0 hr0 h1
    · have hq1 : q.1 = 1 := by rw [hrz] at h1; linarith
      have hqC : q.2 ∈ C := by rw [← haq', hq1, one_smul]; exact ha
      exact ⟨q.2, subset_convexHull ℝ _ (Or.inl hqC), r.2,
        ⟨0, zero_mem_recessionCone C, r.2, hrrec, zero_add r.2⟩, h2⟩
  · have hr1 : r.1 = 1 := by rw [hqz] at h1; linarith
    have hrD : r.2 ∈ D := by
      rcases mem_closedConeOver.1 hr with ⟨-, hrs⟩ | ⟨hrz, -⟩
      · rw [hr1, one_smul] at hrs; exact hrs
      · exact absurd (hrz.symm.trans hr1) (by norm_num)
    refine ⟨r.2, subset_convexHull ℝ _ (Or.inr hrD), q.2,
      ⟨q.2, hqrec, 0, zero_mem_recessionCone D, add_zero q.2⟩, ?_⟩
    rw [← h2]
    exact add_comm r.2 q.2

end Slices

/-! ### The convex cone generated by a closed convex set -/

section Generated

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E] {C : Set E}

omit [FiniteDimensional ℝ E] in
/-- The second coordinate of `closedConeOver C` is the union of the positive multiples of `C`
together with `0⁺C`: this is the projection the proof below takes. -/
theorem image_snd_closedConeOver (C : Set E) :
    (LinearMap.snd ℝ ℝ E) '' closedConeOver C
      = {y | ∃ t : ℝ, 0 < t ∧ y ∈ t • C} ∪ recessionCone C := by
  refine Set.ext fun y => ⟨?_, ?_⟩
  · rintro ⟨p, hp, rfl⟩
    rcases mem_closedConeOver.1 hp with ⟨h1, h2⟩ | ⟨-, h2⟩
    · exact Or.inl ⟨p.1, h1, h2⟩
    · exact Or.inr h2
  · rintro (⟨t, ht, hy⟩ | hy)
    · exact ⟨(t, y), mem_closedConeOver.2 (Or.inl ⟨ht, hy⟩), rfl⟩
    · exact ⟨(0, y), mem_closedConeOver.2 (Or.inr ⟨rfl, hy⟩), rfl⟩

omit [FiniteDimensional ℝ E] in
/-- The second coordinate of the cone over `C` is the convex cone generated by `C`. -/
theorem image_snd_coe_hull_prodMk_one (hC : Convex ℝ C) :
    (LinearMap.snd ℝ ℝ E) '' (PointedCone.hull ℝ (Prod.mk (1 : ℝ) '' C) : Set (ℝ × E))
      = (PointedCone.hull ℝ C : Set E) := by
  rw [coe_hull_prodMk_one hC, coe_hull_of_convex hC, Set.image_insert_eq]
  refine congrArg _ (Set.ext fun y => ⟨?_, ?_⟩)
  · rintro ⟨p, ⟨h1, h2⟩, rfl⟩
    exact ⟨p.1, h1, h2⟩
  · rintro ⟨t, ht, hy⟩
    exact ⟨(t, y), ⟨ht, hy⟩, rfl⟩

/-- **The closure of the convex cone generated by a closed convex set.** Let `C` be a nonempty
closed convex set not containing the origin, and `K` the convex cone generated by `C`. Then

`cl K = ⋃ {λC | λ > 0 or λ = 0⁺}`,

which is the same as `K ∪ 0⁺C` (`closure_coe_hull_eq_union`). The hypothesis `0 ∉ C` makes the
projection `(λ, x) ↦ x` proper on the closed cone over `C`, so that the closed-image theorem
applies; it is not decoration — for `C` a ball with the origin on its boundary it fails. -/
theorem closure_coe_hull (hC : Convex ℝ C) (hCc : IsClosed C) (hne : C.Nonempty)
    (h0 : (0 : E) ∉ C) :
    closure (PointedCone.hull ℝ C : Set E)
      = {y | ∃ t : ℝ, 0 < t ∧ y ∈ t • C} ∪ recessionCone C := by
  have hKcl : closure (PointedCone.hull ℝ (Prod.mk (1 : ℝ) '' C) : Set (ℝ × E))
      = closedConeOver C := closure_coe_hull_prodMk_one hC hCc hne
  have hKconv : Convex ℝ (PointedCone.hull ℝ (Prod.mk (1 : ℝ) '' C) : Set (ℝ × E)) :=
    (PointedCone.hull ℝ (Prod.mk (1 : ℝ) '' C) : ConvexCone ℝ (ℝ × E)).convex
  have hkey : ∀ z ∈ recessionCone
        (closure (PointedCone.hull ℝ (Prod.mk (1 : ℝ) '' C) : Set (ℝ × E))),
      (LinearMap.snd ℝ ℝ E) z = 0 →
        z ∈ linealitySpace
          (closure (PointedCone.hull ℝ (Prod.mk (1 : ℝ) '' C) : Set (ℝ × E))) := by
    intro z hz hz0
    have hz2 : z.2 = 0 := hz0
    have hzmem : z ∈ closedConeOver C := by
      rwa [recessionCone_closure_coe_pointedCone, hKcl] at hz
    have hzzero : z = 0 := by
      rcases mem_closedConeOver.1 hzmem with ⟨hpos, x, hx, hxz⟩ | ⟨h1, -⟩
      · refine absurd ?_ h0
        have hxz' : z.1 • x = z.2 := hxz
        rw [hz2] at hxz'
        rcases smul_eq_zero.1 hxz' with h | h
        · exact absurd h (ne_of_gt hpos)
        · rwa [h] at hx
      · exact Prod.ext h1 hz2
    rw [hzzero]
    exact zero_mem_linealitySpace _
  have himg := Convex.closure_image_eq hKconv (LinearMap.snd ℝ ℝ E) hkey
  rwa [image_snd_coe_hull_prodMk_one hC, hKcl, image_snd_closedConeOver C] at himg

/-- The same, in the form "`cl K = K ∪ 0⁺C`". -/
theorem closure_coe_hull_eq_union (hC : Convex ℝ C) (hCc : IsClosed C) (hne : C.Nonempty)
    (h0 : (0 : E) ∉ C) :
    closure (PointedCone.hull ℝ C : Set E)
      = (PointedCone.hull ℝ C : Set E) ∪ recessionCone C := by
  have hmem : (0 : E) ∈ {y : E | ∃ t : ℝ, 0 < t ∧ y ∈ t • C} ∪ recessionCone C :=
    Or.inr (zero_mem_recessionCone C)
  rw [closure_coe_hull hC hCc hne h0, coe_hull_of_convex hC, Set.insert_union]
  exact (Set.insert_eq_self.2 hmem).symm

/-- **The cone generated by a bounded set is closed**: the convex cone generated by a nonempty
closed *bounded* convex set not containing the origin is closed.

Boundedness is needed: for `C` a line in the plane not through the origin, the cone generated by
`C` is an open half-plane together with the origin. -/
theorem isClosed_coe_hull_of_isBounded (hC : Convex ℝ C) (hCc : IsClosed C) (hne : C.Nonempty)
    (h0 : (0 : E) ∉ C) (hb : Bornology.IsBounded C) :
    IsClosed (PointedCone.hull ℝ C : Set E) := by
  have hmem : (0 : E) ∈ (PointedCone.hull ℝ C : Set E) := Submodule.zero_mem _
  rw [← closure_eq_iff_isClosed, closure_coe_hull_eq_union hC hCc hne h0,
    recessionCone_eq_zero_of_isBounded hne hb, Set.union_singleton]
  exact Set.insert_eq_self.2 hmem

end Generated

/-! ### The positively homogeneous convex function generated by a convex function -/

section PosHomGen

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {f g : E → EReal}

/-- **The positively homogeneous convex function generated by `f`**: the function determined by the
convex cone generated by `epi f`. It lives on the *same* space as `f`, and is the greatest
positively homogeneous convex `g ≤ f` with `g 0 ≤ 0` (`posHomGen_isGreatest`). It is not `hom f`
of `Homogenize.lean`, which is this operator applied to the level-1 lift of `f` and lives on
`ℝ × E`. The gauge of a convex set `C` is `posHomGen (δ(· | C) + 1)`, which is what makes
the gauge a special case of the theorem below. -/
noncomputable def posHomGen (f : E → EReal) : E → EReal :=
  ofEpi (PointedCone.hull ℝ (epi f) : Set (E × ℝ))

/-- The cone generating `posHomGen f` lies inside its epigraph. -/
theorem coe_hull_epi_subset_epi_posHomGen (f : E → EReal) :
    (PointedCone.hull ℝ (epi f) : Set (E × ℝ)) ⊆ epi (posHomGen f) := subset_epi_ofEpi _

theorem posHomGen_le (f : E → EReal) : posHomGen f ≤ f := by
  have h := ofEpi_mono (F := epi f) (G := (PointedCone.hull ℝ (epi f) : Set (E × ℝ)))
    PointedCone.subset_hull
  rwa [ofEpi_epi] at h

/-- `posHomGen f 0 ≤ 0`: the origin lies in the cone generated by `epi f`. -/
theorem posHomGen_apply_zero_le (f : E → EReal) : posHomGen f 0 ≤ 0 := by
  have hmem : (((0 : E), (0 : ℝ)) : E × ℝ) ∈ (PointedCone.hull ℝ (epi f) : Set (E × ℝ)) := by
    rw [Prod.mk_zero_zero]
    exact Submodule.zero_mem _
  have h : posHomGen f 0 ≤ ((0 : ℝ) : EReal) := ofEpi_apply_le hmem
  rwa [_root_.EReal.coe_zero] at h

/-- `posHomGen f` is convex, with no hypothesis on `f`: a cone hull is convex. -/
theorem convexFn_posHomGen (f : E → EReal) : ConvexFn (posHomGen f) :=
  convexFn_ofEpi (PointedCone.hull ℝ (epi f) : ConvexCone ℝ (E × ℝ)).convex

/-- `posHomGen f` is positively homogeneous, with no hypothesis on `f`. -/
theorem posHomogeneous_posHomGen (f : E → EReal) : PosHomogeneous (posHomGen f) := by
  refine posHomogeneous_iff_isCone_epi.2 fun a ha => ?_
  have hsmul : a • (PointedCone.hull ℝ (epi f) : Set (E × ℝ))
      = (PointedCone.hull ℝ (epi f) : Set (E × ℝ)) := by
    refine subset_antisymm ?_ fun x hx => ?_
    · rintro _ ⟨y, hy, rfl⟩
      exact Submodule.smul_mem _ (⟨a, ha.le⟩ : {c : ℝ // 0 ≤ c}) hy
    · refine ⟨a⁻¹ • x, Submodule.smul_mem _ (⟨a⁻¹, (inv_pos.2 ha).le⟩ : {c : ℝ // 0 ≤ c}) hx, ?_⟩
      change a • a⁻¹ • x = x
      rw [smul_smul, mul_inv_cancel₀ (ne_of_gt ha), one_smul]
  rw [posHomGen, smul_epi_ofEpi ha, hsmul]

/-- **The maximality property of `posHomGen f`**: it dominates every positively homogeneous convex
minorant of `f` that is nonpositive at the origin. -/
theorem le_posHomGen (hg : PosHomogeneous g) (hgc : ConvexFn g) (h0 : g 0 ≤ 0) (hle : g ≤ f) :
    g ≤ posHomGen f := by
  refine subset_epi_iff_le_ofEpi.1 fun p hp => ?_
  induction hp using Submodule.span_induction with
  | mem q hq => exact epi_anti hle hq
  | zero => simpa using mk_mem_epi.2 (by simpa using h0 : g 0 ≤ ((0 : ℝ) : EReal))
  | add q r _ _ ihq ihr => exact (hg.epiCone hgc).add_mem ihq ihr
  | smul c q _ ih =>
      rcases eq_or_lt_of_le c.2 with hc | hc
      · have hzero : ((c : ℝ)) • q = (0 : E × ℝ) := by rw [← hc, zero_smul]
        have h0mem : ((0 : E × ℝ)) ∈ epi g := by
          simpa using mk_mem_epi.2 (by simpa using h0 : g 0 ≤ ((0 : ℝ) : EReal))
        rw [← hzero] at h0mem
        exact h0mem
      · exact (hg.epiCone hgc).smul_mem hc ih

/-- **`posHomGen` is monotone.** A larger function generates a larger positively homogeneous
convex minorant: apply the maximality property to `posHomGen f ≤ f ≤ g`. -/
theorem posHomGen_mono (h : f ≤ g) : posHomGen f ≤ posHomGen g :=
  le_posHomGen (posHomogeneous_posHomGen f) (convexFn_posHomGen f) (posHomGen_apply_zero_le f)
    ((posHomGen_le f).trans h)

/-- **`posHomGen f` is the greatest positively homogeneous convex minorant of `f` vanishing (or
worse) at the origin** — the property that names it. -/
theorem posHomGen_isGreatest (f : E → EReal) :
    IsGreatest {g : E → EReal | PosHomogeneous g ∧ ConvexFn g ∧ g 0 ≤ 0 ∧ g ≤ f} (posHomGen f) :=
  ⟨⟨posHomogeneous_posHomGen f, convexFn_posHomGen f, posHomGen_apply_zero_le f, posHomGen_le f⟩,
    fun _ hg => le_posHomGen hg.1 hg.2.1 hg.2.2.1 hg.2.2.2⟩

end PosHomGen

/-! ### Its closure, as an attained infimum -/

section PosHomGenClosure

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  {f : E → EReal}

omit [NormedSpace ℝ E] [FiniteDimensional ℝ E] in
/-- `f 0 > 0` says exactly that `epi f` misses the origin, the hypothesis of the cone theorem. -/
theorem zero_notMem_epi (h0 : 0 < f 0) : (0 : E × ℝ) ∉ epi f := by
  intro h
  have h' : f 0 ≤ (0 : EReal) := by simpa using h
  exact absurd h' (not_le.2 h0)

omit [FiniteDimensional ℝ E] in
/-- The union over `λ > 0` of the epigraphs of the functions `fλ` is the set of positive multiples
of `epi f`. -/
theorem iUnion_epi_smulRight (f : E → EReal) :
    (⋃ t > (0 : ℝ), epi (smulRight f t)) = {p : E × ℝ | ∃ t : ℝ, 0 < t ∧ p ∈ t • epi f} := by
  refine Set.ext fun p => ⟨?_, ?_⟩
  · rintro hp
    obtain ⟨t, ht, hmem⟩ := Set.mem_iUnion₂.1 hp
    exact ⟨t, ht, by rwa [← epi_smulRight ht]⟩
  · rintro ⟨t, ht, hmem⟩
    exact Set.mem_iUnion₂.2 ⟨t, ht, by rwa [epi_smulRight ht]⟩

/-- **At the level of epigraphs**: for a closed proper convex `f` with
`f 0 > 0` the closed convex cone generated by `epi f` is the union of the epigraphs of the
functions `fλ`, `λ > 0`, together with the epigraph of `f0⁺`. -/
theorem closure_coe_hull_epi (hf : ConvexFn f) (hp : Proper f) (hc : IsClosed (epi f))
    (h0 : 0 < f 0) :
    closure (PointedCone.hull ℝ (epi f) : Set (E × ℝ))
      = (⋃ t > (0 : ℝ), epi (smulRight f t)) ∪ epi (recessionFn f) := by
  rw [closure_coe_hull hf.convex_epi hc ((epi_nonempty_iff f).2 hp.dom_nonempty)
      (zero_notMem_epi h0), iUnion_epi_smulRight, epi_recessionFn]

/-- The closed convex cone generated by `epi f` is itself an epigraph: it is closed, and it is
upward closed in the vertical coordinate because each of the two pieces above is. -/
theorem isEpiLike_closure_coe_hull_epi (hf : ConvexFn f) (hp : Proper f) (hc : IsClosed (epi f))
    (h0 : 0 < f 0) :
    IsEpiLike (closure (PointedCone.hull ℝ (epi f) : Set (E × ℝ))) := by
  refine IsEpiLike.of_isClosed (fun x μ ν hμ hμν => ?_) isClosed_closure
  rw [closure_coe_hull_epi hf hp hc h0] at hμ ⊢
  rcases hμ with h | h
  · obtain ⟨t, ht, hmem⟩ := Set.mem_iUnion₂.1 h
    exact Or.inl (Set.mem_iUnion₂.2 ⟨t, ht, (isEpiLike_epi _).mem_of_le hmem hμν⟩)
  · exact Or.inr ((isEpiLike_epi _).mem_of_le h hμν)

/-- **The closure of the generated function.** For a closed proper convex `f` with `f 0 > 0`, the
closure of the positively homogeneous convex function `k` generated by `f` has

`epi (cl k) = (⋃ {epi (fλ) | λ > 0}) ∪ epi (f0⁺)`.

Read pointwise this is `(cl k) x = inf {(fλ) x | λ > 0 or λ = 0⁺}` (`lscHull_posHomGen`); that the
right-hand side is a *union of epigraphs*, and not merely the epigraph of the infimum, is exactly
the assertion that the infimum is attained. -/
theorem epi_lscHull_posHomGen (hf : ConvexFn f) (hp : Proper f) (hc : IsClosed (epi f))
    (h0 : 0 < f 0) :
    epi (lscHull (posHomGen f))
      = (⋃ t > (0 : ℝ), epi (smulRight f t)) ∪ epi (recessionFn f) := by
  rw [epi_lscHull, ← closure_coe_hull_epi hf hp hc h0]
  refine subset_antisymm ?_ (closure_mono (coe_hull_epi_subset_epi_posHomGen f))
  refine isClosed_closure.closure_subset_iff.2 ?_
  exact epi_ofEpi_subset_of_isEpiLike subset_closure (isEpiLike_closure_coe_hull_epi hf hp hc h0)

/-- Pointwise: `(cl k) x = inf {(fλ) x | λ > 0 or λ = 0⁺}`. -/
theorem lscHull_posHomGen (hf : ConvexFn f) (hp : Proper f) (hc : IsClosed (epi f))
    (h0 : 0 < f 0) :
    lscHull (posHomGen f) = (⨅ t : ℝ, ⨅ _ : (0 : ℝ) < t, smulRight f t) ⊓ recessionFn f := by
  have h := congrArg ofEpi (epi_lscHull_posHomGen hf hp hc h0)
  rw [ofEpi_epi, ofEpi_union, ofEpi_epi] at h
  rw [h, ofEpi_iUnion]
  congr 1
  refine iInf_congr fun t => ?_
  rw [ofEpi_iUnion]
  exact iInf_congr fun _ => ofEpi_epi _

/-- **The attainment statement**: whenever `(cl k) x` is bounded above by a real number, that
bound is already achieved by some `(fλ) x` with `λ > 0`, or by `(f0⁺) x`. -/
theorem exists_smulRight_le_of_lscHull_posHomGen_le (hf : ConvexFn f) (hp : Proper f)
    (hc : IsClosed (epi f)) (h0 : 0 < f 0) {x : E} {μ : ℝ}
    (hμ : lscHull (posHomGen f) x ≤ (μ : EReal)) :
    (∃ t : ℝ, 0 < t ∧ smulRight f t x ≤ (μ : EReal)) ∨ recessionFn f x ≤ (μ : EReal) := by
  have hmem : ((x, μ) : E × ℝ) ∈ epi (lscHull (posHomGen f)) := mk_mem_epi.2 hμ
  rw [epi_lscHull_posHomGen hf hp hc h0] at hmem
  rcases hmem with h | h
  · obtain ⟨t, ht, hmem'⟩ := Set.mem_iUnion₂.1 h
    exact Or.inl ⟨t, ht, mk_mem_epi.1 hmem'⟩
  · exact Or.inr (mk_mem_epi.1 h)

/-- `k` is proper.

A vertical line in the epigraph of `k` would make `(0, -1)` a direction of recession of the closed
convex cone generated by `epi f`, hence a member of that cone; the description of that cone would
then force either `f 0 < 0` or `(f0⁺) 0 ≤ -1`, and both are excluded. -/
theorem proper_posHomGen (hf : ConvexFn f) (hp : Proper f) (hc : IsClosed (epi f))
    (h0 : 0 < f 0) : Proper (posHomGen f) := by
  refine ⟨?_, fun x hbot => ?_⟩
  · obtain ⟨x, hx⟩ := hp.dom_nonempty
    exact ⟨x, lt_of_le_of_lt (posHomGen_le f x) hx⟩
  · set S : Set (E × ℝ) := closure (PointedCone.hull ℝ (epi f) : Set (E × ℝ)) with hS
    have hSconv : Convex ℝ S :=
      ((PointedCone.hull ℝ (epi f) : ConvexCone ℝ (E × ℝ)).convex).closure
    have hline : ∀ μ : ℝ, ((x, μ) : E × ℝ) ∈ S :=
      fun μ => epi_ofEpi_subset_of_isEpiLike subset_closure
        (isEpiLike_closure_coe_hull_epi hf hp hc h0)
        (mk_mem_epi.2 (le_of_eq_of_le hbot bot_le))
    have hray : (((0 : E), (-1 : ℝ)) : E × ℝ) ∈ recessionCone S := by
      refine mem_recessionCone_of_exists_ray hSconv isClosed_closure ⟨((x, (0 : ℝ)) : E × ℝ),
        fun a ha => ?_⟩
      have heq : ((x, (0 : ℝ)) : E × ℝ) + a • (((0 : E), (-1 : ℝ)) : E × ℝ)
          = ((x, -a) : E × ℝ) := by simp [Prod.smul_mk, Prod.mk_add_mk]
      rw [heq]
      exact hline (-a)
    rw [hS, recessionCone_closure_coe_pointedCone, ← hS] at hray
    rw [hS, closure_coe_hull_eq_union hf.convex_epi hc
      ((epi_nonempty_iff f).2 hp.dom_nonempty) (zero_notMem_epi h0)] at hray
    rcases hray with hmem | hmem
    · rw [coe_hull_of_convex hf.convex_epi] at hmem
      rcases hmem with heq | ⟨t, ht, q, hq, hqp⟩
      · exact absurd (congrArg Prod.snd heq) (by norm_num)
      · have hqp' : t • q = (((0 : E), (-1 : ℝ)) : E × ℝ) := hqp
        have h2 : t * q.2 = -1 := congrArg Prod.snd hqp'
        have h1 : t • q.1 = (0 : E) := congrArg Prod.fst hqp'
        have hq1 : q.1 = 0 := by
          rcases smul_eq_zero.1 h1 with h | h
          · exact absurd h (ne_of_gt ht)
          · exact h
        have hle : f 0 ≤ ((q.2 : ℝ) : EReal) := by rw [← hq1]; exact mk_mem_epi.1 hq
        have hneg : q.2 < 0 := by nlinarith
        have : ((q.2 : ℝ) : EReal) < 0 := by
          rw [← EReal.coe_zero]
          exact_mod_cast hneg
        exact absurd (lt_of_lt_of_le h0 hle) (not_lt.2 this.le)
    · rw [← epi_recessionFn] at hmem
      have hle : recessionFn f 0 ≤ ((-1 : ℝ) : EReal) := mk_mem_epi.1 hmem
      rw [recessionFn_apply_zero hp] at hle
      exact absurd hle (by norm_num)

omit [FiniteDimensional ℝ E] in
/-- The function determined by `⋃ {epi (fλ) | λ > 0}` is the infimum of the `fλ` over `λ > 0`. -/
theorem ofEpi_iUnion_epi_smulRight (f : E → EReal) :
    ofEpi (⋃ t > (0 : ℝ), epi (smulRight f t)) = ⨅ t : ℝ, ⨅ _ : (0 : ℝ) < t, smulRight f t := by
  rw [ofEpi_iUnion]
  refine iInf_congr fun t => ?_
  rw [ofEpi_iUnion]
  exact iInf_congr fun _ => ofEpi_epi _

omit [FiniteDimensional ℝ E] in
/-- **The estimate behind the case `0 ∈ dom f`.** When `0 ∈ dom f`, the half-line
`(0, f 0) + a (z, ν)` stays in `epi f` for every `(z, ν) ∈ 0⁺(epi f)`, so `(fλ) z ≤ λ f 0 + ν` for
`λ = 1/a`; letting `a → ∞` puts `(z, ν)` in the epi-closure of `⋃ {epi (fλ) | λ > 0}`. This is why
the term `λ = 0⁺` can then be dropped from the infimum. -/
theorem recessionCone_epi_subset_epi_ofEpi_iUnion (hp : Proper f) (hdom : f 0 ≠ ⊤) :
    recessionCone (epi f) ⊆ epi (ofEpi (⋃ t > (0 : ℝ), epi (smulRight f t))) := by
  obtain ⟨r, hr⟩ := Tdaf.EReal.exists_coe_of_ne_bot_of_lt_top (hp.ne_bot 0)
    (lt_top_iff_ne_top.2 hdom)
  have hrmem : (((0 : E), r) : E × ℝ) ∈ epi f := mk_mem_epi.2 hr.le
  rintro ⟨z, ν⟩ hzν
  refine (isEpiLike_epi _).mem_of_forall_lt fun ρ hρ => ?_
  set a : ℝ := |r| / (ρ - ν) + 1 with ha
  have hρν : 0 < ρ - ν := by linarith
  have hapos : 0 < a := by positivity
  have hlt : r / a < ρ - ν := by
    rw [div_lt_iff₀ hapos, ha]
    have h1 : |r| / (ρ - ν) * (ρ - ν) = |r| := div_mul_cancel₀ _ (ne_of_gt hρν)
    nlinarith [le_abs_self r, abs_nonneg r]
  have hmem : ((a • z, r + a * ν) : E × ℝ) ∈ epi f := by
    have hstep := add_smul_mem_of_mem_recessionCone hzν hrmem hapos.le
    simpa [Prod.smul_mk, Prod.mk_add_mk, smul_eq_mul] using hstep
  have heq : (a⁻¹ : ℝ) • ((a • z, r + a * ν) : E × ℝ) = ((z, r / a + ν) : E × ℝ) := by
    have hz : (a⁻¹ : ℝ) • (a • z) = z := by
      rw [smul_smul, inv_mul_cancel₀ (ne_of_gt hapos), one_smul]
    have hn : a⁻¹ * (r + a * ν) = r / a + ν := by field_simp
    rw [Prod.smul_mk, hz, smul_eq_mul, hn]
  have hsmul : ((z, r / a + ν) : E × ℝ) ∈ epi (smulRight f a⁻¹) := by
    rw [epi_smulRight (inv_pos.2 hapos), ← heq]
    exact Set.smul_mem_smul_set hmem
  have hle : ofEpi (⋃ t > (0 : ℝ), epi (smulRight f t)) z ≤ ((r / a + ν : ℝ) : EReal) :=
    ofEpi_apply_le (Set.mem_iUnion₂.2 ⟨a⁻¹, inv_pos.2 hapos, hsmul⟩)
  refine mk_mem_epi.2 (hle.trans ?_)
  exact_mod_cast (by linarith : r / a + ν ≤ ρ)

omit [FiniteDimensional ℝ E] in
/-- `⋃ {epi (fλ) | λ > 0}` sits inside the convex cone generated by `epi f`. -/
theorem iUnion_epi_smulRight_subset_coe_hull (hf : ConvexFn f) :
    (⋃ t > (0 : ℝ), epi (smulRight f t)) ⊆ (PointedCone.hull ℝ (epi f) : Set (E × ℝ)) := by
  rw [iUnion_epi_smulRight, coe_hull_of_convex hf.convex_epi]
  exact Set.subset_insert _ _

/-- **The case `0 ∈ dom f`**: the epigraph of `k` is already the *closed*
convex cone generated by `epi f`, so `k` is closed (`lscHull_posHomGen_eq`) and `λ = 0⁺` may be
dropped from the infimum (`posHomGen_eq_iInf_smulRight`). -/
theorem epi_posHomGen_of_zero_mem_dom (hf : ConvexFn f) (hp : Proper f) (hc : IsClosed (epi f))
    (h0 : 0 < f 0) (hdom : f 0 ≠ ⊤) :
    epi (posHomGen f) = closure (PointedCone.hull ℝ (epi f) : Set (E × ℝ)) := by
  have hmono : epi (ofEpi (⋃ t > (0 : ℝ), epi (smulRight f t))) ⊆ epi (posHomGen f) :=
    epi_anti (ofEpi_mono (iUnion_epi_smulRight_subset_coe_hull hf))
  refine subset_antisymm
    (epi_ofEpi_subset_of_isEpiLike subset_closure (isEpiLike_closure_coe_hull_epi hf hp hc h0))
    ?_
  rw [closure_coe_hull_epi hf hp hc h0]
  refine Set.union_subset
    ((iUnion_epi_smulRight_subset_coe_hull hf).trans (coe_hull_epi_subset_epi_posHomGen f)) ?_
  rw [epi_recessionFn]
  exact (recessionCone_epi_subset_epi_ofEpi_iUnion hp hdom).trans hmono

/-- The case `0 ∈ dom f`: `k` is itself closed. -/
theorem lscHull_posHomGen_eq (hf : ConvexFn f) (hp : Proper f) (hc : IsClosed (epi f))
    (h0 : 0 < f 0) (hdom : f 0 ≠ ⊤) : lscHull (posHomGen f) = posHomGen f := by
  refine epi_injective ?_
  rw [epi_lscHull, epi_posHomGen_of_zero_mem_dom hf hp hc h0 hdom, closure_closure]

/-- The case `0 ∈ dom f`: the term `λ = 0⁺` may be dropped, and
`k x = inf {(fλ) x | λ > 0}` — although the infimum then need not be attained. -/
theorem posHomGen_eq_iInf_smulRight (hf : ConvexFn f) (hp : Proper f) (hc : IsClosed (epi f))
    (h0 : 0 < f 0) (hdom : f 0 ≠ ⊤) :
    posHomGen f = ⨅ t : ℝ, ⨅ _ : (0 : ℝ) < t, smulRight f t := by
  rw [← ofEpi_iUnion_epi_smulRight]
  refine epi_injective (subset_antisymm ?_
    (epi_anti (ofEpi_mono (iUnion_epi_smulRight_subset_coe_hull hf))))
  rw [epi_posHomGen_of_zero_mem_dom hf hp hc h0 hdom, closure_coe_hull_epi hf hp hc h0]
  refine Set.union_subset (subset_epi_ofEpi _) ?_
  rw [epi_recessionFn]
  exact recessionCone_epi_subset_epi_ofEpi_iUnion hp hdom

end PosHomGenClosure

/-! ### The convex hull of a union of two sets -/

section UnionOfSets

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  {C D : Set E}

/-- **The key step.** Under the recession hypothesis the sum of the closed cones over `C` and over
`D` is the closure of a convex cone — hence closed, hence its own recession cone. It is the sum
rule for cones applied one dimension up; the hypothesis transports because a cancelling pair in
the sum must have both homogenising coordinates zero. -/
theorem closedConeOver_add_eq_closure_coe_sup
    (hC : Convex ℝ C) (hCc : IsClosed C) (hCne : C.Nonempty)
    (hD : Convex ℝ D) (hDc : IsClosed D) (hDne : D.Nonempty)
    (h : ∀ z ∈ recessionCone C, ∀ w ∈ recessionCone D, z + w = 0 →
      z ∈ linealitySpace C ∧ w ∈ linealitySpace D) :
    closedConeOver C + closedConeOver D
      = closure ((PointedCone.hull ℝ (Prod.mk (1 : ℝ) '' C)
          ⊔ PointedCone.hull ℝ (Prod.mk (1 : ℝ) '' D) : PointedCone ℝ (ℝ × E)) : Set (ℝ × E)) := by
  have hcl₁ : closure (PointedCone.hull ℝ (Prod.mk (1 : ℝ) '' C) : Set (ℝ × E))
      = closedConeOver C := closure_coe_hull_prodMk_one hC hCc hCne
  have hcl₂ : closure (PointedCone.hull ℝ (Prod.mk (1 : ℝ) '' D) : Set (ℝ × E))
      = closedConeOver D := closure_coe_hull_prodMk_one hD hDc hDne
  have hrec₁ : recessionCone (closedConeOver C) = closedConeOver C := by
    rw [← hcl₁]; exact recessionCone_closure_coe_pointedCone _
  have hrec₂ : recessionCone (closedConeOver D) = closedConeOver D := by
    rw [← hcl₂]; exact recessionCone_closure_coe_pointedCone _
  have hkey : ∀ z ∈ closure (PointedCone.hull ℝ (Prod.mk (1 : ℝ) '' C) : Set (ℝ × E)),
      ∀ w ∈ closure (PointedCone.hull ℝ (Prod.mk (1 : ℝ) '' D) : Set (ℝ × E)), z + w = 0 →
      z ∈ linealitySpace (closure (PointedCone.hull ℝ (Prod.mk (1 : ℝ) '' C) : Set (ℝ × E))) ∧
        w ∈ linealitySpace
          (closure (PointedCone.hull ℝ (Prod.mk (1 : ℝ) '' D) : Set (ℝ × E))) := by
    rw [hcl₁, hcl₂]
    intro z hz w hw hzw
    have h1 : z.1 + w.1 = 0 := congrArg Prod.fst hzw
    have h2 : z.2 + w.2 = 0 := congrArg Prod.snd hzw
    have hz0 := fst_nonneg_of_mem_closedConeOver hz
    have hw0 := fst_nonneg_of_mem_closedConeOver hw
    have hz1 : z.1 = 0 := by linarith
    have hw1 : w.1 = 0 := by linarith
    have hzrec : z.2 ∈ recessionCone C := by
      rcases mem_closedConeOver.1 hz with ⟨hpos, -⟩ | ⟨-, hh⟩
      · exact absurd hz1 (ne_of_gt hpos)
      · exact hh
    have hwrec : w.2 ∈ recessionCone D := by
      rcases mem_closedConeOver.1 hw with ⟨hpos, -⟩ | ⟨-, hh⟩
      · exact absurd hw1 (ne_of_gt hpos)
      · exact hh
    obtain ⟨hzl, hwl⟩ := h z.2 hzrec w.2 hwrec h2
    constructor
    · refine mem_linealitySpace.2 ⟨?_, ?_⟩
      · rw [hrec₁]; exact mem_closedConeOver.2 (Or.inr ⟨hz1, hzrec⟩)
      · rw [hrec₁]
        refine mem_closedConeOver.2 (Or.inr ⟨?_, ?_⟩)
        · change -z.1 = 0
          rw [hz1, neg_zero]
        · exact (mem_linealitySpace.1 hzl).2
    · refine mem_linealitySpace.2 ⟨?_, ?_⟩
      · rw [hrec₂]; exact mem_closedConeOver.2 (Or.inr ⟨hw1, hwrec⟩)
      · rw [hrec₂]
        refine mem_closedConeOver.2 (Or.inr ⟨?_, ?_⟩)
        · change -w.1 = 0
          rw [hw1, neg_zero]
        · exact (mem_linealitySpace.1 hwl).2
  rw [Submodule.coe_sup, closure_add_coe_pointedCone _ _ hkey, hcl₁, hcl₂]

/-- **The closure of the convex hull of a union.** Let `C` and `D` be nonempty closed convex sets
such that the only way a direction of recession of `C` and a direction of recession of `D` can
cancel is inside the two lineality spaces. Then

`cl (conv (C ∪ D)) = conv (C ∪ D) + (0⁺C + 0⁺D)`  and  `0⁺(cl (conv (C ∪ D))) = 0⁺C + 0⁺D`.

The right-hand side of the first identity is classically written
`⋃ {λ₁C + λ₂D | λᵢ ≥ 0⁺, λ₁ + λ₂ = 1}`, with the convention that `0 · C` means `0⁺C`; the form
here says the same thing without the convention. Both sets have to be nonempty — `0⁺∅` is
everything. The two conclusions are packaged together because they come from one application of
the sum rule for cones, read off the level-one and the level-zero slice of the same sum. -/
theorem closure_convexHull_union_and_recessionCone
    (hC : Convex ℝ C) (hCc : IsClosed C) (hCne : C.Nonempty)
    (hD : Convex ℝ D) (hDc : IsClosed D) (hDne : D.Nonempty)
    (h : ∀ z ∈ recessionCone C, ∀ w ∈ recessionCone D, z + w = 0 →
      z ∈ linealitySpace C ∧ w ∈ linealitySpace D) :
    closure (convexHull ℝ (C ∪ D))
        = convexHull ℝ (C ∪ D) + (recessionCone C + recessionCone D) ∧
      recessionCone (closure (convexHull ℝ (C ∪ D))) = recessionCone C + recessionCone D := by
  have hsum := closedConeOver_add_eq_closure_coe_sup hC hCc hCne hD hDc hDne h
  have hSconv : Convex ℝ (closedConeOver C + closedConeOver D) :=
    (convex_closedConeOver hC hCc hCne).add (convex_closedConeOver hD hDc hDne)
  have hSclosed : IsClosed (closedConeOver C + closedConeOver D) := by
    rw [hsum]; exact isClosed_closure
  have hTclosed : IsClosed ((Prod.mk (1 : ℝ)) ⁻¹' (closedConeOver C + closedConeOver D)) :=
    hSclosed.preimage (by fun_prop)
  have hTconv : Convex ℝ ((Prod.mk (1 : ℝ)) ⁻¹' (closedConeOver C + closedConeOver D)) := by
    intro x hx y hy a b ha hb hab
    have heq : (((1 : ℝ), a • x + b • y) : ℝ × E)
        = a • (((1 : ℝ), x) : ℝ × E) + b • (((1 : ℝ), y) : ℝ × E) := by
      simp [Prod.smul_mk, Prod.mk_add_mk, smul_eq_mul, hab]
    change (((1 : ℝ), a • x + b • y) : ℝ × E) ∈ closedConeOver C + closedConeOver D
    rw [heq]
    exact hSconv hx hy ha hb hab
  have hCT : C ⊆ (Prod.mk (1 : ℝ)) ⁻¹' (closedConeOver C + closedConeOver D) := by
    intro x hx
    exact ⟨((1 : ℝ), x), mem_closedConeOver.2 (Or.inl ⟨one_pos, ⟨x, hx, one_smul ℝ x⟩⟩),
      0, zero_mem_closedConeOver D, add_zero _⟩
  have hDT : D ⊆ (Prod.mk (1 : ℝ)) ⁻¹' (closedConeOver C + closedConeOver D) := by
    intro x hx
    exact ⟨0, zero_mem_closedConeOver C,
      ((1 : ℝ), x), mem_closedConeOver.2 (Or.inl ⟨one_pos, ⟨x, hx, one_smul ℝ x⟩⟩), zero_add _⟩
  have hclT : closure (convexHull ℝ (C ∪ D))
      ⊆ (Prod.mk (1 : ℝ)) ⁻¹' (closedConeOver C + closedConeOver D) :=
    hTclosed.closure_subset_iff.2 (convexHull_min (Set.union_subset hCT hDT) hTconv)
  have hTsub : (Prod.mk (1 : ℝ)) ⁻¹' (closedConeOver C + closedConeOver D)
      ⊆ convexHull ℝ (C ∪ D) + (recessionCone C + recessionCone D) := by
    intro x hx
    exact mem_convexHull_add_of_mk_one_mem (Set.mem_preimage.1 hx)
  have hrec : ∀ {S : Set E}, S.Nonempty → S ⊆ closure (convexHull ℝ (C ∪ D)) →
      recessionCone S ⊆ recessionCone (closure (convexHull ℝ (C ∪ D))) := by
    intro S hSne hSsub y hy
    obtain ⟨x, hx⟩ := hSne
    exact mem_recessionCone_of_exists_ray ((convex_convexHull ℝ _).closure) isClosed_closure
      ⟨x, fun a ha => hSsub (hy x hx a ha)⟩
  have hinC : C ⊆ closure (convexHull ℝ (C ∪ D)) :=
    fun z hz => subset_closure (subset_convexHull ℝ _ (Or.inl hz))
  have hinD : D ⊆ closure (convexHull ℝ (C ∪ D)) :=
    fun z hz => subset_closure (subset_convexHull ℝ _ (Or.inr hz))
  have hfinal : convexHull ℝ (C ∪ D) + (recessionCone C + recessionCone D)
      ⊆ closure (convexHull ℝ (C ∪ D)) := by
    rintro x ⟨u, hu, v, hv, huv⟩
    have huv' : u + v = x := huv
    obtain ⟨z, hz, w, hw, hzw⟩ := hv
    have hzw' : z + w = v := hzw
    have h1 := add_mem_of_mem_recessionCone (hrec hCne hinC hz) (subset_closure hu)
    have h2 := add_mem_of_mem_recessionCone (hrec hDne hinD hw) h1
    have heq : u + z + w = x := by rw [← huv', ← hzw']; abel
    rwa [heq] at h2
  have hTeq : (Prod.mk (1 : ℝ)) ⁻¹' (closedConeOver C + closedConeOver D)
      = closure (convexHull ℝ (C ∪ D)) := subset_antisymm (hTsub.trans hfinal) hclT
  refine ⟨subset_antisymm (hclT.trans hTsub) hfinal, subset_antisymm (fun y hy => ?_) ?_⟩
  · obtain ⟨x, hx⟩ := hCne
    have hray : (((0 : ℝ), y) : ℝ × E)
        ∈ recessionCone (closedConeOver C + closedConeOver D) := by
      refine mem_recessionCone_of_exists_ray hSconv hSclosed ⟨(((1 : ℝ), x) : ℝ × E),
        fun a ha => ?_⟩
      have heq : (((1 : ℝ), x) : ℝ × E) + a • (((0 : ℝ), y) : ℝ × E)
          = (((1 : ℝ), x + a • y) : ℝ × E) := by simp [Prod.smul_mk, Prod.mk_add_mk]
      rw [heq, ← Set.mem_preimage, hTeq]
      exact hy x (hinC hx) a ha
    rw [hsum, recessionCone_closure_coe_pointedCone, ← hsum] at hray
    exact mem_recessionCone_add_of_mk_zero_mem hray
  · rintro y ⟨z, hz, w, hw, hzw⟩
    have hzw' : z + w = y := hzw
    rw [← hzw']
    exact add_mem_recessionCone (hrec hCne hinC hz) (hrec hDne hinD hw)

/-- The closure formula: `cl (conv (C ∪ D)) = conv (C ∪ D) + (0⁺C + 0⁺D)`. -/
theorem closure_convexHull_union
    (hC : Convex ℝ C) (hCc : IsClosed C) (hCne : C.Nonempty)
    (hD : Convex ℝ D) (hDc : IsClosed D) (hDne : D.Nonempty)
    (h : ∀ z ∈ recessionCone C, ∀ w ∈ recessionCone D, z + w = 0 →
      z ∈ linealitySpace C ∧ w ∈ linealitySpace D) :
    closure (convexHull ℝ (C ∪ D))
      = convexHull ℝ (C ∪ D) + (recessionCone C + recessionCone D) :=
  (closure_convexHull_union_and_recessionCone hC hCc hCne hD hDc hDne h).1

/-- The recession-cone formula: `0⁺(cl (conv (C ∪ D))) = 0⁺C + 0⁺D`. -/
theorem recessionCone_closure_convexHull_union
    (hC : Convex ℝ C) (hCc : IsClosed C) (hCne : C.Nonempty)
    (hD : Convex ℝ D) (hDc : IsClosed D) (hDne : D.Nonempty)
    (h : ∀ z ∈ recessionCone C, ∀ w ∈ recessionCone D, z + w = 0 →
      z ∈ linealitySpace C ∧ w ∈ linealitySpace D) :
    recessionCone (closure (convexHull ℝ (C ∪ D))) = recessionCone C + recessionCone D :=
  (closure_convexHull_union_and_recessionCone hC hCc hCne hD hDc hDne h).2

omit [FiniteDimensional ℝ E] in
/-- Directions of recession survive taking the convex hull: a translation carrying `S` into `S`
carries `conv S` into `conv S`. -/
theorem recessionCone_subset_recessionCone_convexHull (S : Set E) :
    recessionCone S ⊆ recessionCone (convexHull ℝ S) := by
  intro y hy x hx a ha
  have hconv : Convex ℝ ((fun z : E => z + a • y) ⁻¹' convexHull ℝ S) := by
    intro u hu v hv b c hb hc hbc
    have hsplit : b • (a • y) + c • (a • y) = a • y := by rw [← add_smul, hbc, one_smul]
    have heq : b • (u + a • y) + c • (v + a • y) = b • u + c • v + a • y := by
      rw [smul_add, smul_add, add_add_add_comm, hsplit]
    change b • u + c • v + a • y ∈ convexHull ℝ S
    rw [← heq]
    exact convex_convexHull ℝ S hu hv hb hc hbc
  refine convexHull_min (fun s hs => ?_) hconv hx
  change s + a • y ∈ convexHull ℝ S
  exact subset_convexHull ℝ S (hy s hs a ha)

omit [FiniteDimensional ℝ E] in
/-- A recession cone absorbs itself: it contains `0` and is closed under addition. -/
theorem recessionCone_add_self (C : Set E) :
    recessionCone C + recessionCone C = recessionCone C := by
  refine subset_antisymm ?_ fun y hy => ⟨y, hy, 0, zero_mem_recessionCone C, add_zero y⟩
  rintro x ⟨u, hu, v, hv, huv⟩
  have huv' : u + v = x := huv
  rw [← huv']
  exact add_mem_recessionCone hu hv

/-- **Equal recession cones.** The convex hull of the union of two nonempty closed convex
sets with the *same* recession cone `K` is closed, and has `K` as its recession cone.

The cancellation hypothesis is automatic here: if `z ∈ K` and `-z ∈ K` then `z` lies in the
lineality space of both sets. -/
theorem isClosed_convexHull_union_of_recessionCone_eq
    (hC : Convex ℝ C) (hCc : IsClosed C) (hCne : C.Nonempty)
    (hD : Convex ℝ D) (hDc : IsClosed D) (hDne : D.Nonempty)
    (heq : recessionCone C = recessionCone D) :
    IsClosed (convexHull ℝ (C ∪ D)) ∧
      recessionCone (convexHull ℝ (C ∪ D)) = recessionCone C := by
  have hkey : ∀ z ∈ recessionCone C, ∀ w ∈ recessionCone D, z + w = 0 →
      z ∈ linealitySpace C ∧ w ∈ linealitySpace D := by
    intro z hz w hw hzw
    have hw' : w = -z := by rw [eq_neg_iff_add_eq_zero, add_comm]; exact hzw
    subst hw'
    refine ⟨mem_linealitySpace.2 ⟨hz, by rw [heq]; exact hw⟩, mem_linealitySpace.2 ⟨hw, ?_⟩⟩
    rw [neg_neg, ← heq]
    exact hz
  have hunion : recessionCone C ⊆ recessionCone (C ∪ D) := by
    intro y hy x hx a ha
    have hyD : y ∈ recessionCone D := by rw [← heq]; exact hy
    rcases hx with hx | hx
    · exact Or.inl (hy x hx a ha)
    · exact Or.inr (hyD x hx a ha)
  have hrec : recessionCone C ⊆ recessionCone (convexHull ℝ (C ∪ D)) :=
    hunion.trans (recessionCone_subset_recessionCone_convexHull (C ∪ D))
  have hcl := closure_convexHull_union hC hCc hCne hD hDc hDne hkey
  have hself : recessionCone C + recessionCone D = recessionCone C := by
    rw [← heq]
    exact recessionCone_add_self C
  have hstable : convexHull ℝ (C ∪ D) + (recessionCone C + recessionCone D)
      ⊆ convexHull ℝ (C ∪ D) := by
    rw [hself]
    rintro x ⟨u, hu, v, hv, huv⟩
    have huv' : u + v = x := huv
    rw [← huv']
    exact add_mem_of_mem_recessionCone (hrec hv) hu
  have hclosed : IsClosed (convexHull ℝ (C ∪ D)) := by
    rw [← closure_eq_iff_isClosed, hcl]
    exact subset_antisymm hstable fun x hx =>
      ⟨x, hx, 0, ⟨0, zero_mem_recessionCone C, 0, zero_mem_recessionCone D, add_zero 0⟩, add_zero x⟩
  refine ⟨hclosed, ?_⟩
  have hrec2 := recessionCone_closure_convexHull_union hC hCc hCne hD hDc hDne hkey
  rw [hclosed.closure_eq, hself] at hrec2
  exact hrec2

end UnionOfSets

/-! ### The convex hull of two functions -/

section UnionOfFns

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  {f g : E → EReal}

/-- **The convex hull of two functions.** Two closed proper convex functions with the
*same* recession function `k` have a convex hull `conv {f, g}` that is again closed proper convex,
again with recession function `k`; and its epigraph is the convex hull of the two epigraphs.

The epigraph identity is the content: `conv (epi f ∪ epi g)` is closed by the previous result,
hence an epigraph, hence the epigraph of `conv {f, g}` — and that is at the same time the
statement that the infimum defining `conv {f, g}` is attained (`exists_combo_of_convFn₂_le`).
Properness is read off the recession cone: a vertical line would put `(0, -1)` in `epi k`. -/
theorem closedProperConvexFn_convFn₂ (hf : ClosedProperConvexFn f) (hg : ClosedProperConvexFn g)
    (heq : recessionFn f = recessionFn g) :
    epi (convFn₂ f g) = convexHull ℝ (epi f ∪ epi g) ∧ ClosedProperConvexFn (convFn₂ f g) ∧
      recessionFn (convFn₂ f g) = recessionFn f := by
  have hfne : (epi f).Nonempty := (epi_nonempty_iff f).2 hf.proper.dom_nonempty
  have hgne : (epi g).Nonempty := (epi_nonempty_iff g).2 hg.proper.dom_nonempty
  have hrec : recessionCone (epi f) = recessionCone (epi g) := by
    rw [← epi_recessionFn, ← epi_recessionFn, heq]
  obtain ⟨hclosed, hrecC⟩ := isClosed_convexHull_union_of_recessionCone_eq
    hf.convex.convex_epi hf.isClosed_epi hfne hg.convex.convex_epi hg.isClosed_epi hgne hrec
  have hepi : epi (convFn₂ f g) = convexHull ℝ (epi f ∪ epi g) :=
    epi_convFn₂ (isEpiLike_convexHull_epi_union hclosed)
  refine ⟨hepi, ?_, epi_injective (by rw [epi_recessionFn, epi_recessionFn, hepi, hrecC])⟩
  have hdomne : (dom (convFn₂ f g)).Nonempty := by
    obtain ⟨x, hx⟩ := hf.proper.dom_nonempty
    exact ⟨x, lt_of_le_of_lt (convFn₂_le_left f g x) hx⟩
  have hnebot : ∀ x : E, convFn₂ f g x ≠ ⊥ := by
    intro x hbot
    have hline : ∀ μ : ℝ, ((x, μ) : E × ℝ) ∈ convexHull ℝ (epi f ∪ epi g) := fun μ => by
      rw [← hepi]
      exact mk_mem_epi.2 (le_of_eq_of_le hbot bot_le)
    have hray : (((0 : E), (-1 : ℝ)) : E × ℝ) ∈ recessionCone (convexHull ℝ (epi f ∪ epi g)) := by
      refine mem_recessionCone_of_exists_ray (convex_convexHull ℝ _) hclosed
        ⟨((x, (0 : ℝ)) : E × ℝ), fun a ha => ?_⟩
      have hshift : ((x, (0 : ℝ)) : E × ℝ) + a • (((0 : E), (-1 : ℝ)) : E × ℝ)
          = ((x, -a) : E × ℝ) := by simp [Prod.smul_mk, Prod.mk_add_mk]
      rw [hshift]
      exact hline (-a)
    rw [hrecC, ← epi_recessionFn] at hray
    have hle : recessionFn f 0 ≤ ((-1 : ℝ) : EReal) := mk_mem_epi.1 hray
    rw [recessionFn_apply_zero hf.proper] at hle
    exact absurd hle (by norm_num)
  exact ClosedProperConvexFn.of_isClosed_epi (convexFn_convFn₂ f g)
    (by rw [hepi]; exact hclosed) ⟨hdomne, hnebot⟩

/-- **Attainment**: under the same hypothesis the infimum defining `conv {f, g}` is attained —
every real bound on `conv {f, g}` at `x` is realised by an actual convex combination
`a • u + b • v = x`. In `convFn₂_apply` the infimum is only approached. -/
theorem exists_combo_of_convFn₂_le (hf : ClosedProperConvexFn f) (hg : ClosedProperConvexFn g)
    (heq : recessionFn f = recessionFn g) {x : E} {μ : ℝ} (hμ : convFn₂ f g x ≤ (μ : EReal)) :
    ∃ (a b : ℝ) (u v : E), 0 ≤ a ∧ 0 ≤ b ∧ a + b = 1 ∧ a • u + b • v = x ∧
      (a : EReal) * f u + (b : EReal) * g v ≤ (μ : EReal) := by
  have hfne : (epi f).Nonempty := (epi_nonempty_iff f).2 hf.proper.dom_nonempty
  have hgne : (epi g).Nonempty := (epi_nonempty_iff g).2 hg.proper.dom_nonempty
  obtain ⟨hepi, -, -⟩ := closedProperConvexFn_convFn₂ hf hg heq
  have hmem : ((x, μ) : E × ℝ) ∈ convexHull ℝ (epi f ∪ epi g) := hepi ▸ mk_mem_epi.2 hμ
  rw [hf.convex.convex_epi.convexHull_union hg.convex.convex_epi hfne hgne] at hmem
  obtain ⟨p, hp, q, hq, a, b, ha, hb, hab, hcombo⟩ := mem_convexJoin.1 hmem
  have hx : a • p.1 + b • q.1 = x := congrArg Prod.fst hcombo
  have hν : a * p.2 + b * q.2 = μ := congrArg Prod.snd hcombo
  refine ⟨a, b, p.1, q.1, ha, hb, hab, hx, ?_⟩
  have h₁ : (a : EReal) * f p.1 ≤ (a : EReal) * ((p.2 : ℝ) : EReal) :=
    mul_le_mul_of_nonneg_left (mem_epi.1 hp) (by exact_mod_cast ha)
  have h₂ : (b : EReal) * g q.1 ≤ (b : EReal) * ((q.2 : ℝ) : EReal) :=
    mul_le_mul_of_nonneg_left (mem_epi.1 hq) (by exact_mod_cast hb)
  refine (add_le_add h₁ h₂).trans (le_of_eq ?_)
  rw [Tdaf.EReal.coe_mul_coe, Tdaf.EReal.coe_mul_coe, ← EReal.coe_add, hν]

end UnionOfFns


end Tdaf.ConvexAnalysis
