namespace = 'Rockafellar'

[[node]]
id = 'theorem_7_1'
source = 'Rockafellar 1970, Theorem 7.1'

[[node]]
id = 'theorem_7_2'
source = 'Rockafellar 1970, Theorem 7.2'

[[node]]
id = 'corollary_7_2_1'
source = 'Rockafellar 1970, Corollary 7.2.1'

[[node]]
id = 'corollary_7_2_2'
source = 'Rockafellar 1970, Corollary 7.2.2'

[[node]]
id = 'corollary_7_2_3'
source = 'Rockafellar 1970, Corollary 7.2.3'

[[node]]
id = 'lemma_7_3'
source = 'Rockafellar 1970, Lemma 7.3'

[[node]]
id = 'corollary_7_3_1'
source = 'Rockafellar 1970, Corollary 7.3.1'

[[node]]
id = 'corollary_7_3_2'
source = 'Rockafellar 1970, Corollary 7.3.2'

[[node]]
id = 'corollary_7_3_3'
source = 'Rockafellar 1970, Corollary 7.3.3'

[[node]]
id = 'corollary_7_3_4'
source = 'Rockafellar 1970, Corollary 7.3.4'

[[node]]
id = 'theorem_7_4'
source = 'Rockafellar 1970, Theorem 7.4'

[[node]]
id = 'corollary_7_4_1'
source = 'Rockafellar 1970, Corollary 7.4.1'

[[node]]
id = 'corollary_7_4_2'
source = 'Rockafellar 1970, Corollary 7.4.2'

[[node]]
id = 'theorem_7_5'
source = 'Rockafellar 1970, Theorem 7.5'

[[node]]
id = 'corollary_7_5_1'
source = 'Rockafellar 1970, Corollary 7.5.1'

[[node]]
id = 'theorem_7_6'
source = 'Rockafellar 1970, Theorem 7.6'

[[node]]
id = 'corollary_7_6_1'
source = 'Rockafellar 1970, Corollary 7.6.1'
