namespace = 'Tdaf.ConvexAnalysis'

[[node]]
id = 'hypo'

[[node]]
id = 'hypo_neg'

[[node]]
id = 'epi_neg'

[[node]]
id = 'domConcave'

[[node]]
id = 'domConcave_eq_dom_neg'

[[node]]
id = 'ProperConcave'

[[node]]
id = 'properConcave_iff_proper_neg'

[[node]]
id = 'restrictConcave'

[[node]]
id = 'ConcaveFn'

[[node]]
id = 'concaveFn_iff_convexFn_neg'

[[node]]
id = 'concaveFn_iff_forall_gt'

[[node]]
id = 'concaveFn_iff_le'

[[node]]
id = 'ConcaveFn.convex_gt'

[[node]]
id = 'ConcaveFn.convex_ge'

[[node]]
id = 'concaveOn_iff_concaveFn'
