/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Tdaf.Analysis.Convex.RelativeInterior
import Tdaf.Surface.Rockafellar.Part1.Section02

/-!
# Rockafellar §6 — Relative Interiors of Convex Sets

The eighteen numbered results of R. T. Rockafellar, *Convex Analysis* (Princeton, 1970), §6
(pp. 43–50), stated in the book's own terms over `Rn n = ℝⁿ`.

The book's `cl C` is Mathlib's `closure C`, its `int C` is `interior C`, and its `ri C` is the
backbone's `ri`, that is `intrinsicInterior ℝ`. Only the relative boundary and "relatively open"
need a surface definition.

## Main definitions

* `Rockafellar.relbd` — the book's **relative boundary** `(cl C) \ (ri C)`, bridged to Mathlib's
  `intrinsicFrontier ℝ` by `relbd_eq_intrinsicFrontier`.
* `Rockafellar.IsRelativelyOpen` — the book's **relatively open**: `ri C = C`.
* `Rockafellar.coneOver` — the convex cone `K` of Corollary 6.8.1, the one generated by
  `{(1, x) | x ∈ C}`, bridged to that description by `mem_coneOver_iff`.

## Main results

* `theorem_6_1` — the line segment principle.
* `theorem_6_2_*` — `cl C` and `ri C` are convex with the same affine hull and dimension as `C`;
  `theorem_6_2_nonempty` is the finite-dimensional heart of the book.
* `theorem_6_3_cl_ri`, `theorem_6_3_ri_cl`, `corollary_6_3_1`, `corollary_6_3_1_sandwich`,
  `corollary_6_3_2`, `corollary_6_3_3`.
* `theorem_6_4`, `corollary_6_4_1` — the prolongation criterion and its interior form.
* `theorem_6_5_cl`, `theorem_6_5_ri`, `corollary_6_5_1_ri`, `corollary_6_5_1_cl`,
  `corollary_6_5_2` — intersections.
* `theorem_6_6_ri`, `theorem_6_6_cl`, `corollary_6_6_1`, `corollary_6_6_2_ri`,
  `corollary_6_6_2_cl` — images under a linear transformation, scalar multiples and sums.
* `theorem_6_7_ri`, `theorem_6_7_cl` — inverse images.
* `theorem_6_8`, `corollary_6_8_1` — slices of a convex set in a product, and the cone over `C`.
* `theorem_6_9` — the relative interior of `conv (C₁ ∪ C₂)`.

## Design notes

**Theorem 6.2 is where finite-dimensionality enters the book, and it never leaves.** The clause
`ri C ≠ ∅` for non-empty convex `C` is false in infinite dimensions — the positive cone of `ℓ²`
with empty relative interior is the standard witness — and §§7, 9, 10, 11, 16, 18 and 20 use it
without saying so. In the backbone it is `Convex.relint_nonempty`, which is Mathlib's
`Set.Nonempty.intrinsicInterior`, and that lemma's hypothesis list is where the dependence is
recorded: `[FiniteDimensional ℝ E]`. Every result below that quantifies over `Rn n` inherits it
from the ambient instance of `Tdaf/Surface/Common/Euclidean.lean`, so nothing in this file needs a
dimension hypothesis of its own — which is exactly why the dependence is easy to lose sight of.

**`ℝᵐ⁺ᵖ` is `Rn m × Rn p` here**, as in §3; the transport between the two is separate work
(remediation §4.8). Theorem 6.8 is therefore stated on the product. Corollary 6.8.1's ambient space
is `ℝ × ℝⁿ` rather than `Rn 1 × Rn n` for the same reason and because the book's own proof reads
"apply the theorem with `ℝᵐ = R`".

**The book's `A` is a `LinearMap`, not an affine map.** Theorems 6.6 and 6.7 are stated for
`A : Rn n →ₗ[ℝ] Rn m`; the book's remark that everything also holds for affine transformations is
recorded in `What is not here`.

**Theorem 6.5 quantifies over an arbitrary index type**, matching the book's index set `I`, with
`Finite ι` added only to the relative interior formula. The book's own counterexample — the
intersection of `ri [0, 1 + α]` over `α > 0` — is what makes the finiteness necessary, and the
backbone records it in the docstring of `Convex.relint_iInter`.

## What is not here

* **Theorem 6.9 for `m > 2` sets.** The book states it for `C₀ = conv (C₁ ∪ ⋯ ∪ C_m)`; the
  backbone's `Convex.relint_convexHull_union` proves the two-set case, and the step to `m` sets is
  a bare induction that has not been done. `theorem_6_9` below is the two-set instance, in the
  book's two-coefficient form. **Deferred by scope**, and recorded as a backbone gap.
* **The exercise after Corollary 6.8.1** (book 2099): the relative interior of the convex cone in
  `ℝⁿ` generated by a non-empty convex set `C` consists of the `λx` with `λ > 0` and `x ∈ ri C`.
  The book sets it "as a simple exercise" and gives it no number. **Omitted with a reason.**
* **The counterexamples.** The pitfall `C₁ ⊇ C₂ ⇏ ri C₁ ⊇ ri C₂` (a cube and one of its faces,
  book 1873), the failure of Theorem 6.5 without a common relative interior point (book 1995), and
  the failure of Theorem 6.7 without `A⁻¹(ri C) ≠ ∅` (book 2079) carry no numbers and are not
  transcribed. **Omitted with a reason.**
* **The remark that Theorems 6.6 and 6.7 hold for affine transformations too** (book 2083) is not
  separately stated: the backbone's `Convex.relint_image` and `Convex.relint_preimage` take a
  `LinearMap`, and an affine version would need an affine-map form of both. **Omitted with a
  reason**; see the backbone-gap list in the section report.
* **The reduction device of book 1889–1901** — transporting a convex set onto a coordinate
  subspace by a one-to-one affine transformation of `ℝⁿ`, so as to assume `aff C = ℝⁿ` — is not
  formalized. The backbone deliberately avoids it: `mem_intrinsicInterior_iff` gives the metric
  description of `ri` directly, and every §6 proof runs through that instead. **Omitted with a
  reason.**

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §6 (pp. 43–50).
-/

namespace Rockafellar

open Tdaf.ConvexAnalysis Tdaf.Surface
open scoped Pointwise

variable {n m p : ℕ} {C C₁ C₂ : Set (Rn n)}

/-! ### The relative interior, the relative boundary and relatively open sets -/

/-- **Rockafellar, §6 (p. 44).** The **relative boundary** of `C` is `(cl C) ∖ (ri C)`. -/
def relbd (C : Set (Rn n)) : Set (Rn n) := closure C \ ri C

/-- The bridge: the book's relative boundary is Mathlib's `intrinsicFrontier`. -/
theorem relbd_eq_intrinsicFrontier (C : Set (Rn n)) : relbd C = intrinsicFrontier ℝ C :=
  closure_sdiff_intrinsicInterior (𝕜 := ℝ) C

/-- Membership in the relative boundary, spelled out. -/
theorem mem_relbd_iff {x : Rn n} : x ∈ relbd C ↔ x ∈ closure C ∧ x ∉ ri C := Iff.rfl

/-- **Rockafellar, §6 (p. 44).** `C` is **relatively open** when `ri C = C`. -/
def IsRelativelyOpen (C : Set (Rn n)) : Prop := ri C = C

/-- The bridge: relative openness is the equation `ri C = C`, by definition. -/
theorem isRelativelyOpen_iff : IsRelativelyOpen C ↔ ri C = C := Iff.rfl

/-- **Rockafellar, §6 (p. 44).** The sandwich `ri C ⊆ C ⊆ cl C`. -/
theorem relint_subset_subset_closure (C : Set (Rn n)) : ri C ⊆ C ∧ C ⊆ closure C :=
  ⟨intrinsicInterior_subset, subset_closure⟩

/-- **Rockafellar, §6 (p. 45).** For an `n`-dimensional convex set `aff C = ℝⁿ`, and then
`ri C = int C`.

Specialises `intrinsicInterior_eq_interior`. -/
theorem relint_eq_interior (h : affineSpan ℝ C = ⊤) : ri C = interior C :=
  intrinsicInterior_eq_interior h

/-- **Rockafellar, §6 (p. 45).** An affine set is relatively open. -/
theorem isRelativelyOpen_of_isAffineSet {M : Set (Rn n)} (h : IsAffineSet M) :
    IsRelativelyOpen M := by
  have key := AffineSubspace.intrinsicInterior_coe h.toAffineSubspace
  rw [h.coe_toAffineSubspace] at key
  exact key

/-- **Rockafellar, §6 (p. 45).** Every affine set is closed. In the book this is read off from
Corollary 1.4.1 and Theorem 1.3; here it is the finite-dimensionality of `ℝⁿ`. -/
theorem isClosed_of_isAffineSet {M : Set (Rn n)} (h : IsAffineSet M) : IsClosed M := by
  have key := h.toAffineSubspace.closed_of_finiteDimensional
  rwa [h.coe_toAffineSubspace] at key

/-- **Rockafellar, §6 (p. 45).** `cl C ⊆ cl (aff C) = aff C`, so a line through two points of
`cl C` lies in `aff C`.

Specialises `closure_subset_affineSpan`. -/
theorem closure_subset_affineSpan (C : Set (Rn n)) :
    closure C ⊆ (affineSpan ℝ C : Set (Rn n)) :=
  Tdaf.ConvexAnalysis.closure_subset_affineSpan C

/-! ### Theorem 6.1: the line segment principle -/

/-- **Rockafellar, Theorem 6.1.** Let `C` be a convex set in `ℝⁿ`, let `x ∈ ri C` and
`y ∈ cl C`. Then `(1 - λ) x + λ y` belongs to `ri C` (and hence in particular to `C`) for
`0 ≤ λ < 1`.

Specialises `Convex.segment_mem_relint`. -/
theorem theorem_6_1 (hC : Convex ℝ C) {x y : Rn n} (hx : x ∈ ri C) (hy : y ∈ closure C)
    {l : ℝ} (hl₀ : 0 ≤ l) (hl₁ : l < 1) : (1 - l) • x + l • y ∈ ri C :=
  Convex.segment_mem_relint hC hx hy hl₀ hl₁

/-! ### Theorem 6.2 -/

/-- **Rockafellar, Theorem 6.2.** `cl C` is convex.

Specialises Mathlib's `Convex.closure`. -/
theorem theorem_6_2_convex_cl (hC : Convex ℝ C) : Convex ℝ (closure C) :=
  hC.closure

/-- **Rockafellar, Theorem 6.2.** `ri C` is convex.

Specialises `Convex.relint`, which is Theorem 6.1 with `y` taken in `ri C`. -/
theorem theorem_6_2_convex_ri (hC : Convex ℝ C) : Convex ℝ (ri C) :=
  Convex.relint hC

/-- **Rockafellar, Theorem 6.2.** `cl C` has the same affine hull as `C`. No convexity is needed.

Specialises `affineSpan_closure`. -/
theorem theorem_6_2_aff_cl (C : Set (Rn n)) : affineSpan ℝ (closure C) = affineSpan ℝ C :=
  affineSpan_closure C

/-- **Rockafellar, Theorem 6.2.** `ri C` has the same affine hull as `C`.

Specialises `Convex.affineSpan_relint`. -/
theorem theorem_6_2_aff_ri (hC : Convex ℝ C) : affineSpan ℝ (ri C) = affineSpan ℝ C :=
  Convex.affineSpan_relint hC

/-- **Rockafellar, Theorem 6.2.** `cl C` has the same dimension as `C`. -/
theorem theorem_6_2_dim_cl (C : Set (Rn n)) : dim (closure C) = dim C := by
  rcases C.eq_empty_or_nonempty with rfl | hne
  · simp
  · rw [dim_of_nonempty (hne.mono subset_closure), dim_of_nonempty hne, ← direction_affineSpan,
      ← direction_affineSpan, affineSpan_closure]

/-- **Rockafellar, Theorem 6.2.** `ri C` has the same dimension as `C`. -/
theorem theorem_6_2_dim_ri (hC : Convex ℝ C) : dim (ri C) = dim C := by
  rcases C.eq_empty_or_nonempty with rfl | hne
  · simp
  · rw [dim_of_nonempty (Convex.relint_nonempty hC hne), dim_of_nonempty hne,
      ← direction_affineSpan, ← direction_affineSpan, Convex.affineSpan_relint hC]

/-- **Rockafellar, Theorem 6.2**, the parenthetical clause: `ri C ≠ ∅` when `C ≠ ∅`.

**This is the single fact that makes Part II finite-dimensional.** It is false in infinite
dimensions, and §§7, 9, 10, 11, 16, 18 and 20 use it silently. It specialises
`Convex.relint_nonempty`, which is Mathlib's `Set.Nonempty.intrinsicInterior`; that lemma's proof
runs through `Convex.openSegment_interior_self_subset_interior` on a finite-dimensional affine
hull, and its `[FiniteDimensional ℝ E]` hypothesis is discharged here by the ambient instance on
`Rn n`. Nothing weaker than finite-dimensionality will do. -/
theorem theorem_6_2_nonempty (hC : Convex ℝ C) (hne : C.Nonempty) : (ri C).Nonempty :=
  Convex.relint_nonempty hC hne

/-! ### Theorem 6.3 and its corollaries -/

/-- **Rockafellar, Theorem 6.3.** For any convex set `C` in `ℝⁿ`, `cl (ri C) = cl C`.

Specialises `Convex.closure_relint`. -/
theorem theorem_6_3_cl_ri (hC : Convex ℝ C) : closure (ri C) = closure C :=
  Convex.closure_relint hC

/-- **Rockafellar, Theorem 6.3.** For any convex set `C` in `ℝⁿ`, `ri (cl C) = ri C`.

Specialises `Convex.relint_closure`. -/
theorem theorem_6_3_ri_cl (hC : Convex ℝ C) : ri (closure C) = ri C :=
  Convex.relint_closure hC

/-- **Rockafellar, §6 (p. 46).** `ri (ri C) = ri C`: the relative interior of a convex set is
relatively open. The book asserts this for arbitrary sets, before Theorem 6.3; the backbone proves
it for convex sets, through Theorem 6.3.

Specialises `Convex.relint_relint`. -/
theorem isRelativelyOpen_relint (hC : Convex ℝ C) : IsRelativelyOpen (ri C) :=
  Convex.relint_relint hC

/-- **Rockafellar, Corollary 6.3.1.** Let `C₁` and `C₂` be convex sets in `ℝⁿ`. Then
`cl C₁ = cl C₂` if and only if `ri C₁ = ri C₂`.

Specialises `Convex.closure_eq_iff_relint_eq`. -/
theorem corollary_6_3_1 (h₁ : Convex ℝ C₁) (h₂ : Convex ℝ C₂) :
    closure C₁ = closure C₂ ↔ ri C₁ = ri C₂ :=
  Convex.closure_eq_iff_relint_eq h₁ h₂

/-- **Rockafellar, Corollary 6.3.1**, the third condition: the two conditions above are equivalent
to `ri C₁ ⊆ C₂ ⊆ cl C₁`.

Specialises `Convex.closure_eq_of_relint_subset_of_subset_closure` in one direction; the other is
Theorem 6.3 read backwards. -/
theorem corollary_6_3_1_sandwich (h₁ : Convex ℝ C₁) (h₂ : Convex ℝ C₂) :
    closure C₁ = closure C₂ ↔ ri C₁ ⊆ C₂ ∧ C₂ ⊆ closure C₁ := by
  constructor
  · intro h
    refine ⟨?_, h ▸ subset_closure⟩
    rw [(Convex.closure_eq_iff_relint_eq h₁ h₂).1 h]
    exact intrinsicInterior_subset
  · rintro ⟨hsub, hsup⟩
    exact (Convex.closure_eq_of_relint_subset_of_subset_closure h₁ hsub hsup).symm

/-- **Rockafellar, Corollary 6.3.2.** If `C` is a convex set in `ℝⁿ`, then every open set which
meets `cl C` also meets `ri C`.

Specialises `Convex.relint_inter_nonempty_of_isOpen`. -/
theorem corollary_6_3_2 (hC : Convex ℝ C) {U : Set (Rn n)} (hU : IsOpen U)
    (h : (U ∩ closure C).Nonempty) : (U ∩ ri C).Nonempty :=
  Convex.relint_inter_nonempty_of_isOpen hC hU h

/-- The step Corollary 6.3.3 needs and the backbone does not have: a non-empty convex set inside
`cl C₂` whose affine hull is that of `C₂` must already meet `ri C₂`.

This is Rockafellar's own argument — a relative interior point of `C₁` has a whole ball of
`aff C₁ = aff C₂` around it inside `C₁`, and `cl C₂ = cl (ri C₂)` puts a point of `ri C₂` in that
ball. `Tdaf/Analysis/Convex/Face.lean` proves the face-specific shadow of this as
`IsFace.affineSpan_ne`; the general statement is a backbone gap. -/
theorem inter_relint_nonempty_of_affineSpan_eq (h₁ : Convex ℝ C₁) (hne₁ : C₁.Nonempty)
    (h₂ : Convex ℝ C₂) (hsub : C₁ ⊆ closure C₂) (hspan : affineSpan ℝ C₁ = affineSpan ℝ C₂) :
    (C₁ ∩ ri C₂).Nonempty := by
  obtain ⟨z, hz⟩ := Convex.relint_nonempty h₁ hne₁
  have hzC₁ : z ∈ C₁ := intrinsicInterior_subset hz
  rw [mem_intrinsicInterior_iff] at hz
  obtain ⟨-, ε, hε, hball⟩ := hz
  have hzcl : z ∈ closure (ri C₂) := by
    rw [Convex.closure_relint h₂]
    exact hsub hzC₁
  obtain ⟨w, hw, hzw⟩ := Metric.mem_closure_iff.1 hzcl ε hε
  refine ⟨w, hball w ?_ (by rwa [dist_comm]), hw⟩
  rw [hspan]
  exact subset_affineSpan ℝ C₂ (intrinsicInterior_subset hw)

/-- **Rockafellar, Corollary 6.3.3.** If `C₁` is a convex subset of the relative boundary of a
non-empty convex set `C₂` in `ℝⁿ`, then `dim C₁ < dim C₂`.

The book's proof, transcribed: were the dimensions equal the affine hulls would coincide, and then
`C₁` would have to meet `ri C₂`, which it cannot. There is no backbone declaration for this; the
supporting step is `inter_relint_nonempty_of_affineSpan_eq` above. -/
theorem corollary_6_3_3 (h₁ : Convex ℝ C₁) (h₂ : Convex ℝ C₂) (hne₂ : C₂.Nonempty)
    (hsub : C₁ ⊆ relbd C₂) : dim C₁ < dim C₂ := by
  have hcl : C₁ ⊆ closure C₂ := fun x hx => (hsub hx).1
  have hdisj : ∀ x ∈ C₁, x ∉ ri C₂ := fun x hx => (hsub hx).2
  rcases C₁.eq_empty_or_nonempty with rfl | hne₁
  · rw [dim_empty, dim_of_nonempty hne₂]
    omega
  have hle : vectorSpan ℝ C₁ ≤ vectorSpan ℝ C₂ := by
    have h := vectorSpan_mono ℝ hcl
    rwa [← direction_affineSpan, ← direction_affineSpan, affineSpan_closure,
      direction_affineSpan, direction_affineSpan] at h
  rw [dim_of_nonempty hne₁, dim_of_nonempty hne₂, Nat.cast_lt]
  refine lt_of_le_of_ne (Submodule.finrank_mono hle) fun heq => ?_
  have hdir : vectorSpan ℝ C₁ = vectorSpan ℝ C₂ := Submodule.eq_of_le_of_finrank_eq hle heq
  have hspan : affineSpan ℝ C₁ = affineSpan ℝ C₂ := by
    refine AffineSubspace.ext_of_direction_eq ?_ ?_
    · rw [direction_affineSpan, direction_affineSpan, hdir]
    · obtain ⟨x, hx⟩ := hne₁
      exact ⟨x, subset_affineSpan ℝ C₁ hx,
        Tdaf.ConvexAnalysis.closure_subset_affineSpan C₂ (hcl hx)⟩
  obtain ⟨x, hx₁, hx₂⟩ := inter_relint_nonempty_of_affineSpan_eq h₁ hne₁ h₂ hcl hspan
  exact hdisj x hx₁ hx₂

/-! ### Theorem 6.4: the prolongation criterion -/

/-- **Rockafellar, Theorem 6.4.** Let `C` be a non-empty convex set in `ℝⁿ`. Then `z ∈ ri C` if and
only if, for every `x ∈ C`, there exists a `μ > 1` such that `(1 - μ) x + μ z` belongs to `C`.

Specialises `Convex.mem_relint_iff_prolong`. -/
theorem theorem_6_4 (hC : Convex ℝ C) (hne : C.Nonempty) {z : Rn n} :
    z ∈ ri C ↔ ∀ x ∈ C, ∃ μ > (1 : ℝ), (1 - μ) • x + μ • z ∈ C :=
  Convex.mem_relint_iff_prolong hC hne

/-- **Rockafellar, Corollary 6.4.1.** Let `C` be a convex set in `ℝⁿ`. Then `z ∈ int C` if and only
if, for every `y ∈ ℝⁿ`, there exists some `ε > 0` such that `z + ε y ∈ C`.

Specialises `Convex.mem_interior_iff_absorbs`. -/
theorem corollary_6_4_1 (hC : Convex ℝ C) {z : Rn n} :
    z ∈ interior C ↔ ∀ y : Rn n, ∃ ε : ℝ, 0 < ε ∧ z + ε • y ∈ C :=
  Convex.mem_interior_iff_absorbs hC

/-! ### Theorem 6.5: intersections -/

/-- **Rockafellar, Theorem 6.5**, the closure formula. Let `Cᵢ` be a convex set in `ℝⁿ` for
`i ∈ I`. Suppose that the sets `ri Cᵢ` have at least one point in common. Then
`cl ⋂ᵢ Cᵢ = ⋂ᵢ cl Cᵢ`. The index set is arbitrary.

Specialises `Convex.closure_iInter`. -/
theorem theorem_6_5_cl {ι : Type*} {C : ι → Set (Rn n)} (hC : ∀ i, Convex ℝ (C i))
    (h : (⋂ i, ri (C i)).Nonempty) : closure (⋂ i, C i) = ⋂ i, closure (C i) :=
  Convex.closure_iInter hC h

/-- **Rockafellar, Theorem 6.5**, the relative interior formula: if in addition `I` is finite,
`ri ⋂ᵢ Cᵢ = ⋂ᵢ ri Cᵢ`. Finiteness cannot be dropped — the book's own counterexample is the family
`[0, 1 + α]` for `α > 0`.

Specialises `Convex.relint_iInter`. -/
theorem theorem_6_5_ri {ι : Type*} [Finite ι] {C : ι → Set (Rn n)} (hC : ∀ i, Convex ℝ (C i))
    (h : (⋂ i, ri (C i)).Nonempty) : ri (⋂ i, C i) = ⋂ i, ri (C i) :=
  Convex.relint_iInter hC h

/-- **Rockafellar, Corollary 6.5.1.** Let `C` be a convex set, and let `M` be an affine set (such
as a line or a hyperplane) which contains a point of `ri C`. Then `ri (M ∩ C) = M ∩ ri C`.

Specialises `Convex.relint_inter_affine` through §1's `IsAffineSet.toAffineSubspace`. -/
theorem corollary_6_5_1_ri (hC : Convex ℝ C) {M : Set (Rn n)} (hM : IsAffineSet M)
    (h : (M ∩ ri C).Nonempty) : ri (M ∩ C) = M ∩ ri C := by
  have key := Convex.relint_inter_affine (M := hM.toAffineSubspace) hC
    (by rwa [hM.coe_toAffineSubspace])
  rwa [hM.coe_toAffineSubspace] at key

/-- **Rockafellar, Corollary 6.5.1**, the closure half: `cl (M ∩ C) = M ∩ cl C`.

Specialises `Convex.closure_inter_affine`. -/
theorem corollary_6_5_1_cl (hC : Convex ℝ C) {M : Set (Rn n)} (hM : IsAffineSet M)
    (h : (M ∩ ri C).Nonempty) : closure (M ∩ C) = M ∩ closure C := by
  have key := Convex.closure_inter_affine (M := hM.toAffineSubspace) hC
    (by rwa [hM.coe_toAffineSubspace])
  rwa [hM.coe_toAffineSubspace] at key

/-- **Rockafellar, Corollary 6.5.2.** Let `C₁` be a convex set. Let `C₂` be a convex set contained
in `cl C₁` but not entirely contained in the relative boundary of `C₁`. Then `ri C₂ ⊆ ri C₁`.

Specialises `Convex.relint_subset_relint_of_subset_closure`, whose hypothesis is the backbone's
positive reading `(C₂ ∩ ri C₁).Nonempty` of "not entirely contained in the relative boundary". -/
theorem corollary_6_5_2 (h₁ : Convex ℝ C₁) (h₂ : Convex ℝ C₂) (hsub : C₂ ⊆ closure C₁)
    (hnb : ¬ C₂ ⊆ relbd C₁) : ri C₂ ⊆ ri C₁ := by
  refine Convex.relint_subset_relint_of_subset_closure h₁ h₂ hsub ?_
  by_contra hem
  refine hnb fun x hx => ⟨hsub hx, fun hx₁ => hem ⟨x, hx, hx₁⟩⟩

/-! ### Theorem 6.6: images under a linear transformation -/

/-- **Rockafellar, Theorem 6.6.** Let `C` be a convex set in `ℝⁿ`, and let `A` be a linear
transformation from `ℝⁿ` to `ℝᵐ`. Then `ri (AC) = A (ri C)`.

Specialises `Convex.relint_image`. -/
theorem theorem_6_6_ri (hC : Convex ℝ C) (A : Rn n →ₗ[ℝ] Rn m) : ri (A '' C) = A '' ri C :=
  Convex.relint_image hC A

/-- **Rockafellar, Theorem 6.6.** `cl (AC) ⊇ A (cl C)`. This is just continuity of `A` and needs
no convexity.

Specialises `image_closure_subset`. -/
theorem theorem_6_6_cl (C : Set (Rn n)) (A : Rn n →ₗ[ℝ] Rn m) :
    A '' closure C ⊆ closure (A '' C) :=
  image_closure_subset C A

/-- **Rockafellar, Corollary 6.6.1.** For any convex set `C` and any real number `λ`,
`ri (λ C) = λ (ri C)`.

Specialises `Convex.relint_smul`. -/
theorem corollary_6_6_1 (hC : Convex ℝ C) (l : ℝ) : ri (l • C) = l • ri C :=
  Convex.relint_smul hC l

/-- **Rockafellar, §6 (p. 49).** The direct-sum formula the book calls "elementary":
`ri (C₁ ⊕ C₂) = ri C₁ ⊕ ri C₂`.

Specialises Mathlib's `intrinsicInterior_prod_eq`. -/
theorem relint_prod (D₁ : Set (Rn n)) (D₂ : Set (Rn m)) :
    ri (D₁ ×ˢ D₂) = ri D₁ ×ˢ ri D₂ :=
  intrinsicInterior_prod_eq D₁ D₂

/-- **Rockafellar, §6 (p. 49).** `cl (C₁ ⊕ C₂) = cl C₁ ⊕ cl C₂`.

Specialises Mathlib's `closure_prod_eq`. -/
theorem closure_prod (D₁ : Set (Rn n)) (D₂ : Set (Rn m)) :
    closure (D₁ ×ˢ D₂) = closure D₁ ×ˢ closure D₂ :=
  closure_prod_eq

/-- **Rockafellar, Corollary 6.6.2.** For any convex sets `C₁` and `C₂` in `ℝⁿ`,
`ri (C₁ + C₂) = ri C₁ + ri C₂`.

Specialises `Convex.relint_add`. -/
theorem corollary_6_6_2_ri (h₁ : Convex ℝ C₁) (h₂ : Convex ℝ C₂) :
    ri (C₁ + C₂) = ri C₁ + ri C₂ :=
  Convex.relint_add h₁ h₂

/-- **Rockafellar, Corollary 6.6.2.** `cl (C₁ + C₂) ⊇ cl C₁ + cl C₂`. No convexity is needed.

Specialises `closure_add_subset`. Corollary 9.1.1 sharpens this to an equality. -/
theorem corollary_6_6_2_cl (D₁ D₂ : Set (Rn n)) :
    closure D₁ + closure D₂ ⊆ closure (D₁ + D₂) :=
  closure_add_subset D₁ D₂

/-! ### Theorem 6.7: inverse images under a linear transformation -/

/-- **Rockafellar, Theorem 6.7.** Let `A` be a linear transformation from `ℝⁿ` to `ℝᵐ`. Let `C` be
a convex set in `ℝᵐ` such that `A⁻¹(ri C) ≠ ∅`. Then `ri (A⁻¹C) = A⁻¹(ri C)`.

Specialises `Convex.relint_preimage`. -/
theorem theorem_6_7_ri {D : Set (Rn m)} (hD : Convex ℝ D) (A : Rn n →ₗ[ℝ] Rn m)
    (h : (A ⁻¹' ri D).Nonempty) : ri (A ⁻¹' D) = A ⁻¹' ri D :=
  Convex.relint_preimage hD A h

/-- **Rockafellar, Theorem 6.7.** Under the same hypothesis, `cl (A⁻¹C) = A⁻¹(cl C)`.

Specialises `Convex.closure_preimage`. -/
theorem theorem_6_7_cl {D : Set (Rn m)} (hD : Convex ℝ D) (A : Rn n →ₗ[ℝ] Rn m)
    (h : (A ⁻¹' ri D).Nonempty) : closure (A ⁻¹' D) = A ⁻¹' closure D :=
  Convex.closure_preimage hD A h

/-! ### Theorem 6.8: slices of a convex set in a product -/

/-- **Rockafellar, Theorem 6.8.** Let `C` be a convex set in `ℝᵐ⁺ᵖ`. For each `y ∈ ℝᵐ` let `C_y`
be the set of `z ∈ ℝᵖ` with `(y, z) ∈ C`, and let `D = {y | C_y ≠ ∅}`. Then `(y, z) ∈ ri C` if and
only if `y ∈ ri D` and `z ∈ ri C_y`.

Specialises `Convex.mem_relint_prod_iff`, which is stated with `D` in the equivalent form
`Prod.fst '' C`. -/
theorem theorem_6_8 {C : Set (Rn m × Rn p)} (hC : Convex ℝ C) (y : Rn m) (z : Rn p) :
    (y, z) ∈ ri C ↔
      y ∈ ri {u : Rn m | {w : Rn p | (u, w) ∈ C}.Nonempty} ∧ z ∈ ri {w : Rn p | (y, w) ∈ C} := by
  have hD : {u : Rn m | {w : Rn p | (u, w) ∈ C}.Nonempty} = Prod.fst '' C := by
    ext u
    constructor
    · rintro ⟨w, hw⟩
      exact ⟨(u, w), hw, rfl⟩
    · rintro ⟨q, hq, rfl⟩
      exact ⟨q.2, hq⟩
  rw [hD]
  exact Convex.mem_relint_prod_iff hC

/-- **Rockafellar, Corollary 6.8.1.** The convex cone `K` in `ℝⁿ⁺¹` generated by
`{(1, x) | x ∈ C}`. Rockafellar's cones need not contain the origin, so `K` is the set of positive
multiples of the cross-section, and nothing more. -/
def coneOver (C : Set (Rn n)) : Set (ℝ × Rn n) := {q | 0 < q.1 ∧ q.2 ∈ q.1 • C}

/-- The bridge: `coneOver C` is exactly the set of positive multiples of `{(1, x) | x ∈ C}`, which
is what Corollary 2.6.3 identifies as the smallest convex cone containing that set. -/
theorem mem_coneOver_iff {q : ℝ × Rn n} :
    q ∈ coneOver C ↔ ∃ l : ℝ, 0 < l ∧ ∃ x ∈ C, l • ((1 : ℝ), x) = q := by
  constructor
  · rintro ⟨hq, x, hx, hxq⟩
    exact ⟨q.1, hq, x, hx, Prod.ext (by simp) (by simpa using hxq)⟩
  · rintro ⟨l, hl, x, hx, rfl⟩
    exact ⟨by simpa using hl, x, hx, by simp⟩

/-- `coneOver C` is convex when `C` is: it is the intersection of the backbone's cone (which
carries the origin) with the open half-space `{q | 0 < q.1}`. -/
theorem convex_coneOver (hC : Convex ℝ C) : Convex ℝ (coneOver C) := by
  have hhalf : Convex ℝ {q : ℝ × Rn n | 0 < q.1} :=
    convex_halfSpace_gt (LinearMap.fst ℝ ℝ (Rn n)).isLinear 0
  have hset : coneOver C = insert 0 (coneOver C) ∩ {q : ℝ × Rn n | 0 < q.1} := by
    ext q
    constructor
    · exact fun hq => ⟨Set.mem_insert_of_mem _ hq, hq.1⟩
    · rintro ⟨hq | hq, hq'⟩
      · rw [hq] at hq'
        simp at hq'
      · exact hq
  rw [hset]
  exact _root_.Convex.inter (convex_cone_prodMk_one hC) hhalf

/-- **Rockafellar, Corollary 6.8.1.** Let `C` be a non-empty convex set in `ℝⁿ`, and let `K` be the
convex cone in `ℝⁿ⁺¹` generated by `{(1, x) | x ∈ C}`. Then `ri K` consists of the pairs `(λ, x)`
such that `λ > 0` and `x ∈ λ (ri C)`.

Specialises `Convex.relint_cone_prodMk_one`, which is stated about `K ∪ {0}`; the origin is added
back and removed again through Corollary 6.3.1, since `K` and `K ∪ {0}` have the same closure. -/
theorem corollary_6_8_1 (hC : Convex ℝ C) (hne : C.Nonempty) :
    ri (coneOver C) = {q : ℝ × Rn n | 0 < q.1 ∧ q.2 ∈ q.1 • ri C} := by
  have hconv0 : Convex ℝ (insert 0 (coneOver C)) := convex_cone_prodMk_one hC
  have hri : ri (insert 0 (coneOver C)) = {q : ℝ × Rn n | 0 < q.1 ∧ q.2 ∈ q.1 • ri C} :=
    Convex.relint_cone_prodMk_one hC hne
  have hsub : ri (insert 0 (coneOver C)) ⊆ coneOver C := by
    rw [hri]
    rintro q ⟨h1, h2⟩
    exact ⟨h1, Set.smul_set_mono intrinsicInterior_subset h2⟩
  have hsup : coneOver C ⊆ closure (insert 0 (coneOver C)) :=
    (Set.subset_insert _ _).trans subset_closure
  have hcl := Convex.closure_eq_of_relint_subset_of_subset_closure hconv0 hsub hsup
  rw [← hri]
  exact (Convex.closure_eq_iff_relint_eq (convex_coneOver hC) hconv0).1 hcl

/-! ### Theorem 6.9 -/

/-- **Rockafellar, Theorem 6.9**, for two sets. Let `C₁` and `C₂` be non-empty convex sets in `ℝⁿ`
and let `C₀ = conv (C₁ ∪ C₂)`. Then
`ri C₀ = ⋃ {λ₁ ri C₁ + λ₂ ri C₂ | λᵢ > 0, λ₁ + λ₂ = 1}`.

Specialises `Convex.relint_convexHull_union`, which states the same union in the parametrised form
`λ₁ = 1 - a`, `λ₂ = a` with `a ∈ (0, 1)`. **The book states the theorem for `m` sets; only `m = 2`
is available** — see `What is not here`. -/
theorem theorem_6_9 (h₁ : Convex ℝ C₁) (hne₁ : C₁.Nonempty) (h₂ : Convex ℝ C₂)
    (hne₂ : C₂.Nonempty) :
    ri (convexHull ℝ (C₁ ∪ C₂)) =
      ⋃ (l₁ : ℝ) (l₂ : ℝ) (_ : 0 < l₁) (_ : 0 < l₂) (_ : l₁ + l₂ = 1),
        (l₁ • ri C₁ + l₂ • ri C₂) := by
  rw [Convex.relint_convexHull_union h₁ hne₁ h₂ hne₂]
  ext x
  simp only [Set.mem_iUnion, Set.mem_Ioo, exists_prop]
  constructor
  · rintro ⟨a, ⟨ha₀, ha₁⟩, hx⟩
    exact ⟨1 - a, a, by linarith, ha₀, by ring, hx⟩
  · rintro ⟨l₁, l₂, hl₁, hl₂, hl, hx⟩
    refine ⟨l₂, ⟨hl₂, by linarith⟩, ?_⟩
    rw [show (1 : ℝ) - l₂ = l₁ by linarith]
    exact hx

/-! ### The relatively open sets of §6

The book closes the section (p. 49) by noting that relative openness is preserved by the operations
above, and that the relative interior and the closure of a convex cone are again convex cones. -/

/-- **Rockafellar, §6 (p. 49).** The class of relatively open convex sets is preserved under finite
intersections, provided the relative interiors meet — which for relatively open sets is just
non-emptiness of the intersection. -/
theorem isRelativelyOpen_iInter {ι : Type*} [Finite ι] {C : ι → Set (Rn n)}
    (hC : ∀ i, Convex ℝ (C i)) (hopen : ∀ i, IsRelativelyOpen (C i))
    (h : (⋂ i, C i).Nonempty) : IsRelativelyOpen (⋂ i, C i) := by
  have hopen' : ∀ i, ri (C i) = C i := fun i => (isRelativelyOpen_iff).1 (hopen i)
  have heq : (⋂ i, ri (C i)) = ⋂ i, C i := Set.iInter_congr hopen'
  refine isRelativelyOpen_iff.2 ?_
  rw [Convex.relint_iInter hC (heq ▸ h), heq]

/-- **Rockafellar, §6 (p. 49).** The class of relatively open convex sets is preserved under
addition. -/
theorem isRelativelyOpen_add (h₁ : Convex ℝ C₁) (h₂ : Convex ℝ C₂)
    (ho₁ : IsRelativelyOpen C₁) (ho₂ : IsRelativelyOpen C₂) : IsRelativelyOpen (C₁ + C₂) := by
  refine isRelativelyOpen_iff.2 ?_
  rw [Convex.relint_add h₁ h₂, isRelativelyOpen_iff.1 ho₁, isRelativelyOpen_iff.1 ho₂]

/-- **Rockafellar, §6 (p. 50).** The relative interior of a convex cone is a convex cone. This is
immediate from Corollary 6.6.1, because a convex set `C` is a cone exactly when `λ C = C` for every
`λ > 0` (§2's `isCone_iff_smul_set_eq`). -/
theorem isCone_relint (hK : IsCone C) (hC : Convex ℝ C) : IsCone (ri C) := by
  rw [isCone_iff_smul_set_eq] at hK ⊢
  intro a ha
  rw [← Convex.relint_smul hC a, hK a ha]

/-- **Rockafellar, §6 (p. 50).** The closure of a convex cone is a convex cone. -/
theorem isCone_closure (hK : IsCone C) : IsCone (closure C) := by
  rw [isCone_iff_smul_set_eq] at hK ⊢
  intro a ha
  rw [← closure_smul₀ a C, hK a ha]

end Rockafellar
