/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Tdaf.Analysis.Convex.Polyhedral.Conjugate
import Tdaf.Analysis.Convex.RelativeInterior
import Tdaf.Analysis.Convex.Subgradient.Defs

/-!
# Existence of subgradients

Rockafellar's **Theorem 23.4** and **Theorem 23.10**: a proper convex function is subdifferentiable
at every relative interior point of its effective domain, and a polyhedral convex function is
subdifferentiable wherever it is finite. In both cases the directional derivative `f'(x; ·)` is
*exactly* the support function of `∂f x`, not merely its closure.

Theorem 23.2 (`clFn_dirDeriv`) already gives `cl (f'(x; ·)) = δ*(· | ∂f x)` for any convex `f`
finite at `x`. So both theorems reduce to one question — **is `f'(x; ·)` closed?** — and both
answers are recorded here:

* at a relative interior point the effective domain of `f'(x; ·)` is the subspace parallel to
  `aff (dom f)`, and a proper convex function with affine effective domain is closed
  (Corollary 7.4.2);
* for polyhedral `f` the epigraph of `f'(x; ·)` is the convex cone generated by
  `epi f - (x, f x)`, which is polyhedral by Corollary 19.7.1 and in particular closed.

Once `f'(x; ·)` is closed, nonemptiness of `∂f x` is immediate: the support function of the empty
set is the constant `−∞`, while `f'(x; 0) = 0`.

## Main results

* `dom_dirDeriv_of_mem_relint_dom`, `proper_dirDeriv_of_mem_relint_dom`,
  `closedFn_dirDeriv_of_mem_relint_dom` — the three steps of **Theorem 23.4**.
* `dirDeriv_eq_supportFn_of_mem_relint_dom`, `subgradient_nonempty_of_mem_relint_dom` —
  **Theorem 23.4**.
* `bddAbove_subgradient_iff_mem_interior_dom` — **Theorem 23.4**, last clause: `∂f x` is bounded
  exactly when `x` is an *interior* point of `dom f`.
* `polyhedralFn_dirDeriv`, `proper_dirDeriv_of_polyhedralFn` — **Theorem 23.10** for the
  directional derivative.
* `dirDeriv_eq_supportFn_of_polyhedralFn`, `subgradient_nonempty_of_polyhedralFn`,
  `polyhedral_subgradient_of_polyhedralFn` — **Theorem 23.10**.

## Design notes

**The two theorems share their last two steps.** `dirDeriv_eq_supportFn_of_closedFn` and
`subgradient_nonempty_of_closedFn_dirDeriv` take `ClosedFn (dirDeriv f x)` as a hypothesis and
are what each of Theorems 23.4 and 23.10 ends with; only the *supply* of that hypothesis differs.

**Properness of `f'(x; ·)` is not automatic.** For `f y = -√y` on `[0, ∞)` (and `+∞` elsewhere)
one has `f'(0; y) = −∞` for every `y > 0` while `f'(0; 0) = 0`, so `f'(x; ·)` really can be
improper — and indeed `0 ∉ ri (dom f)` there. What `x ∈ ri (dom f)` buys is that
`dom (f'(x; ·))` is a *subspace*, hence relatively open, so Theorem 7.2 locates the `−∞` values at
the origin, where there are none.

**The cone identity holds only up to closure in general.** For `f y = y²` at `x = 0` the cone
generated by `epi f` is the open upper half plane together with the origin, whereas
`epi (f'(0; ·))` is the closed upper half plane: `epi_dirDeriv_subset_coe_hull` therefore carries
`IsClosed` as a hypothesis, and it is Corollary 19.7.1 that discharges it in the polyhedral case.
The reverse inclusion `coe_hull_epi_sub_subset_epi_dirDeriv` is unconditional and needs no
topology at all.

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §23 (Theorems 23.4
  and 23.10).
-/

open Set
open scoped Pointwise

namespace Tdaf.ConvexAnalysis

/-! ### The epigraph of the directional derivative as a cone -/

section EpiCone

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {f : E → EReal} {x : E} {r : ℝ}

/-- The convex cone generated by `epi f - (x, f x)` always lies inside the epigraph of
`f'(x; ·)`: the generators are there because `f'(x; z - x) ≤ f z - f x`, and the epigraph of a
positively homogeneous convex function is a cone. -/
theorem coe_hull_epi_sub_subset_epi_dirDeriv (hf : ConvexFn f) (hr : f x = (r : EReal)) :
    (PointedCone.hull ℝ (epi f - {((x, r) : E × ℝ)}) : Set (E × ℝ)) ⊆ epi (dirDeriv f x) := by
  have ht : f x ≠ ⊤ := by rw [hr]; exact _root_.EReal.coe_ne_top r
  have hb : f x ≠ ⊥ := by rw [hr]; exact _root_.EReal.coe_ne_bot r
  have hisCone : ∀ a : ℝ, 0 < a → a • epi (dirDeriv f x) = epi (dirDeriv f x) :=
    (posHomogeneous_iff_isCone_epi (f := dirDeriv f x)).1 (posHomogeneous_dirDeriv f x)
  have hadd : ∀ p ∈ epi (dirDeriv f x), ∀ q ∈ epi (dirDeriv f x), p + q ∈ epi (dirDeriv f x) :=
    (convex_iff_add_mem_of_isCone hisCone).1 (convexFn_dirDeriv hf ht hb).convex_epi
  have hzero : (0 : E × ℝ) ∈ epi (dirDeriv f x) := by
    change dirDeriv f x (0 : E × ℝ).1 ≤ (((0 : E × ℝ).2 : ℝ) : EReal)
    simp [dirDeriv_zero ht hb]
  have hsmul : ∀ a : ℝ, 0 ≤ a → ∀ w ∈ epi (dirDeriv f x), a • w ∈ epi (dirDeriv f x) := by
    intro a ha w hw
    rcases eq_or_lt_of_le ha with h | h
    · rw [← h, zero_smul]; exact hzero
    · rw [← hisCone a h]; exact Set.smul_mem_smul_set hw
  intro w hw
  induction hw using Submodule.span_induction with
  | mem w hw =>
      obtain ⟨p, hp, q, hq, hpq⟩ := hw
      rw [Set.mem_singleton_iff] at hq
      subst hq
      have hpq' : p - (x, r) = w := hpq
      have hfp : f p.1 ≤ ((p.2 : ℝ) : EReal) := hp
      have h1 : dirDeriv f x (p.1 - x)
          ≤ (f (x + (1 : ℝ) • (p.1 - x)) - f x) / ((1 : ℝ) : EReal) := dirDeriv_le f x _ one_pos
      have hx1 : x + (1 : ℝ) • (p.1 - x) = p.1 := by module
      rw [hx1, hr] at h1
      have h2 : (f p.1 - (r : EReal)) / ((1 : ℝ) : EReal) ≤ ((p.2 - r : ℝ) : EReal) := by
        rw [EReal.sub_div_le_coe_iff one_pos]
        have hc : (r + (p.2 - r) * 1 : ℝ) = p.2 := by ring
        rw [hc]
        exact hfp
      rw [← hpq']
      change dirDeriv f x (p - (x, r)).1 ≤ (((p - (x, r)).2 : ℝ) : EReal)
      simpa using h1.trans h2
  | zero => exact hzero
  | add w₁ w₂ _ _ ih₁ ih₂ => exact hadd w₁ ih₁ w₂ ih₂
  | smul c w _ ih => exact hsmul (c : ℝ) c.2 w ih

end EpiCone

section EpiConeClosed

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] {f : E → EReal} {x : E} {r : ℝ}

/-- If the convex cone generated by `epi f - (x, f x)` is closed, it *is* the epigraph of
`f'(x; ·)`. Only this inclusion needs the closedness; the other one is
`coe_hull_epi_sub_subset_epi_dirDeriv`. -/
theorem epi_dirDeriv_subset_coe_hull (hf : ConvexFn f) (hr : f x = (r : EReal))
    (hK : IsClosed (PointedCone.hull ℝ (epi f - {((x, r) : E × ℝ)}) : Set (E × ℝ))) :
    epi (dirDeriv f x) ⊆ (PointedCone.hull ℝ (epi f - {((x, r) : E × ℝ)}) : Set (E × ℝ)) := by
  intro w hw
  have hle : dirDeriv f x w.1 ≤ ((w.2 : ℝ) : EReal) := hw
  have hcont : Continuous fun t : ℝ => ((w.1, t) : E × ℝ) := by fun_prop
  have hsec : IsClosed {t : ℝ |
      ((w.1, t) : E × ℝ) ∈ (PointedCone.hull ℝ (epi f - {((x, r) : E × ℝ)}) : Set (E × ℝ))} :=
    hK.preimage hcont
  have hsub : Set.Ioi w.2 ⊆ {t : ℝ |
      ((w.1, t) : E × ℝ) ∈ (PointedCone.hull ℝ (epi f - {((x, r) : E × ℝ)}) : Set (E × ℝ))} := by
    intro t ht
    have hlt : dirDeriv f x w.1 < (t : EReal) :=
      lt_of_le_of_lt hle (by exact_mod_cast (ht : w.2 < t))
    obtain ⟨a, ha, hbound⟩ := exists_le_of_dirDeriv_lt hf hr hlt
    have hmem : ((x + a • w.1, r + t * a) : E × ℝ) ∈ epi f := hbound a ha le_rfl
    have hmem2 : ((a • w.1, t * a) : E × ℝ) ∈ epi f - {((x, r) : E × ℝ)} := by
      refine ⟨(x + a • w.1, r + t * a), hmem, (x, r), rfl, ?_⟩
      have h : ((x + a • w.1, r + t * a) : E × ℝ) - (x, r) = (a • w.1, t * a) := by
        rw [Prod.mk_sub_mk, add_sub_cancel_left, add_sub_cancel_left]
      exact h
    have hscal := Submodule.smul_mem (PointedCone.hull ℝ (epi f - {((x, r) : E × ℝ)}))
      (⟨a⁻¹, le_of_lt (inv_pos.2 ha)⟩ : {c : ℝ // 0 ≤ c}) (PointedCone.subset_hull hmem2)
    have heq : (a⁻¹ : ℝ) • ((a • w.1, t * a) : E × ℝ) = (w.1, t) := by
      rw [Prod.smul_mk, smul_smul, inv_mul_cancel₀ ha.ne', one_smul, smul_eq_mul]
      congr 1
      field_simp
    have hfin : (a⁻¹ : ℝ) • ((a • w.1, t * a) : E × ℝ)
        ∈ (PointedCone.hull ℝ (epi f - {((x, r) : E × ℝ)}) : Set (E × ℝ)) := hscal
    rw [heq] at hfin
    exact hfin
  have hclos := hsec.closure_subset_iff.2 hsub
  rw [closure_Ioi] at hclos
  have hmem : w.2 ∈ {t : ℝ |
      ((w.1, t) : E × ℝ) ∈ (PointedCone.hull ℝ (epi f - {((x, r) : E × ℝ)}) : Set (E × ℝ))} :=
    hclos (by simp)
  simpa using hmem

/-- The epigraph of `f'(x; ·)` *is* the convex cone generated by `epi f - (x, f x)`, whenever that
cone is closed. -/
theorem epi_dirDeriv_eq_coe_hull (hf : ConvexFn f) (hr : f x = (r : EReal))
    (hK : IsClosed (PointedCone.hull ℝ (epi f - {((x, r) : E × ℝ)}) : Set (E × ℝ))) :
    epi (dirDeriv f x) = (PointedCone.hull ℝ (epi f - {((x, r) : E × ℝ)}) : Set (E × ℝ)) :=
  subset_antisymm (epi_dirDeriv_subset_coe_hull hf hr hK)
    (coe_hull_epi_sub_subset_epi_dirDeriv hf hr)

end EpiConeClosed

/-! ### The common ending: a closed directional derivative -/

section Closed

variable {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  [AddCommGroup F] [Module ℝ F] {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} {f : E → EReal} {x : E}

/-- **Theorem 23.2 with the closure removed.** As soon as `f'(x; ·)` is closed it *is* the support
function of `∂f x`; this is the last step of both Theorem 23.4 and Theorem 23.10. -/
theorem dirDeriv_eq_supportFn_of_closedFn [IsCompatiblePairing B] (hf : ConvexFn f)
    (ht : f x ≠ ⊤) (hb : f x ≠ ⊥) (hcl : ClosedFn (dirDeriv f x)) :
    dirDeriv f x = supportFn B.flip (subgradient B f x) :=
  hcl.symm.trans (clFn_dirDeriv hf ht hb)

/-- **Subdifferentiability from closedness.** The support function of the empty set is the
constant `−∞`, but `f'(x; 0) = 0`; so a closed `f'(x; ·)` forces `∂f x ≠ ∅`. -/
theorem subgradient_nonempty_of_closedFn_dirDeriv [IsCompatiblePairing B] (hf : ConvexFn f)
    (ht : f x ≠ ⊤) (hb : f x ≠ ⊥) (hcl : ClosedFn (dirDeriv f x)) :
    (subgradient B f x).Nonempty := by
  rcases Set.eq_empty_or_nonempty (subgradient B f x) with he | hne
  · exfalso
    have hEq := dirDeriv_eq_supportFn_of_closedFn (B := B) hf ht hb hcl
    rw [he, supportFn_empty] at hEq
    have h0 := congrFun hEq 0
    rw [dirDeriv_zero ht hb] at h0
    exact absurd h0 (by simp)
  · exact hne

end Closed

/-! ### Theorem 23.4: subdifferentiability on the relative interior -/

section Relint

variable {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  [AddCommGroup F] [Module ℝ F] {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} {f : E → EReal} {x : E}

omit [FiniteDimensional ℝ E] in
/-- **Rockafellar, Theorem 23.4**, first step: at a relative interior point of `dom f` the
effective domain of `f'(x; ·)` is the subspace parallel to the affine hull of `dom f`.

Both inclusions are elementary: a direction along which the difference quotient is ever finite
points from `x` into `dom f`, and conversely a relative interior point can be moved a little in
any direction of the affine hull without leaving `dom f`. -/
theorem dom_dirDeriv_of_mem_relint_dom (hf : ConvexFn f) (hp : Proper f) (hx : x ∈ ri (dom f)) :
    dom (dirDeriv f x) = ((affineSpan ℝ (dom f)).direction : Set E) := by
  obtain ⟨hxaff, ε, hε, hball⟩ := mem_intrinsicInterior_iff.1 hx
  have hxdom : x ∈ dom f := intrinsicInterior_subset hx
  obtain ⟨r, hr⟩ :=
    EReal.exists_coe_of_ne_bot_of_lt_top (hp.ne_bot x) (mem_dom.1 hxdom)
  ext y
  constructor
  · intro hy
    obtain ⟨m, hm, -⟩ := _root_.EReal.lt_iff_exists_real_btwn.1 (mem_dom.1 hy)
    obtain ⟨a, ha, hbound⟩ := exists_le_of_dirDeriv_lt hf hr hm
    have hmem : x + a • y ∈ dom f :=
      mem_dom.2 (lt_of_le_of_lt (hbound a ha le_rfl) (_root_.EReal.coe_lt_top _))
    have hvs : (x + a • y) - x ∈ (affineSpan ℝ (dom f)).direction :=
      AffineSubspace.vsub_mem_direction (subset_affineSpan ℝ (dom f) hmem) hxaff
    have hay : a • y ∈ (affineSpan ℝ (dom f)).direction := by
      have h : (x + a • y) - x = a • y := by abel
      rwa [h] at hvs
    have hfinal := Submodule.smul_mem _ (a⁻¹ : ℝ) hay
    rwa [smul_smul, inv_mul_cancel₀ ha.ne', one_smul] at hfinal
  · intro hy
    have hyd : y ∈ (affineSpan ℝ (dom f)).direction := hy
    set a : ℝ := ε / (‖y‖ + 1) with hadef
    have hpos : 0 < a := by positivity
    have hnorm : ‖a • y‖ < ε := by
      rw [norm_smul, Real.norm_eq_abs, abs_of_pos hpos, hadef, div_mul_eq_mul_div]
      rw [div_lt_iff₀ (by positivity)]
      nlinarith [norm_nonneg y, hε]
    have haff : x + a • y ∈ affineSpan ℝ (dom f) := by
      have h := AffineSubspace.vadd_mem_of_mem_direction
        (Submodule.smul_mem _ a hyd) hxaff
      have he : (a • y) +ᵥ x = x + a • y := by
        rw [vadd_eq_add]; abel
      rwa [he] at h
    have hdist : dist (x + a • y) x < ε := by
      rw [dist_eq_norm]
      have h : (x + a • y) - x = a • y := by abel
      rwa [h]
    have hmem : x + a • y ∈ dom f := hball _ haff hdist
    obtain ⟨c, hc, -⟩ := _root_.EReal.lt_iff_exists_real_btwn.1 (mem_dom.1 hmem)
    refine mem_dom.2 (lt_of_le_of_lt (dirDeriv_le f x y hpos) ?_)
    rw [hr]
    have hbound : (f (x + a • y) - (r : EReal)) / ((a : ℝ) : EReal)
        ≤ (((c - r) / a : ℝ) : EReal) := by
      rw [EReal.sub_div_le_coe_iff hpos]
      have hcc : (r + (c - r) / a * a : ℝ) = c := by
        rw [div_mul_cancel₀ _ hpos.ne']; ring
      rw [hcc]
      exact hc.le
    exact lt_of_le_of_lt hbound (_root_.EReal.coe_lt_top _)

omit [FiniteDimensional ℝ E] in
/-- **Rockafellar, Theorem 23.4**, second step: at a relative interior point `f'(x; ·)` is proper.
The effective domain is a subspace, hence relatively open, so Theorem 7.2 would put every `−∞`
value at the origin — where `f'(x; 0) = 0`. -/
theorem proper_dirDeriv_of_mem_relint_dom (hf : ConvexFn f) (hp : Proper f)
    (hx : x ∈ ri (dom f)) : Proper (dirDeriv f x) := by
  have hxdom : x ∈ dom f := intrinsicInterior_subset hx
  have ht : f x ≠ ⊤ := (mem_dom.1 hxdom).ne
  have hb : f x ≠ ⊥ := hp.ne_bot x
  have hdom := dom_dirDeriv_of_mem_relint_dom hf hp hx
  have h0 : (0 : E) ∈ dom (dirDeriv f x) := by
    rw [mem_dom, dirDeriv_zero ht hb]; exact _root_.EReal.zero_lt_top
  by_contra hcon
  have hopen : ri (dom (dirDeriv f x)) = dom (dirDeriv f x) := by
    have h := AffineSubspace.intrinsicInterior_coe
      (((affineSpan ℝ (dom f)).direction : Submodule ℝ E).toAffineSubspace)
    rw [hdom]
    exact h
  have hbot := (convexFn_dirDeriv hf ht hb).eq_bot_of_mem_relint_dom hcon
    (by rw [hopen]; exact h0)
  rw [dirDeriv_zero ht hb] at hbot
  exact absurd hbot (by simp)

/-- **Rockafellar, Theorem 23.4**, third step: `f'(x; ·)` is closed, by Corollary 7.4.2 — its
effective domain is affine. -/
theorem closedFn_dirDeriv_of_mem_relint_dom (hf : ConvexFn f) (hp : Proper f)
    (hx : x ∈ ri (dom f)) : ClosedFn (dirDeriv f x) := by
  have hxdom : x ∈ dom f := intrinsicInterior_subset hx
  refine (convexFn_dirDeriv hf (mem_dom.1 hxdom).ne (hp.ne_bot x)).closedFn_of_dom_eq_coe
    (proper_dirDeriv_of_mem_relint_dom hf hp hx)
    (M := ((affineSpan ℝ (dom f)).direction : Submodule ℝ E).toAffineSubspace) ?_
  rw [dom_dirDeriv_of_mem_relint_dom hf hp hx]
  rfl

/-- **Rockafellar, Theorem 23.4.** At a relative interior point of `dom f` the directional
derivative is *exactly* the support function of the subdifferential. -/
theorem dirDeriv_eq_supportFn_of_mem_relint_dom [IsCompatiblePairing B] (hf : ConvexFn f)
    (hp : Proper f) (hx : x ∈ ri (dom f)) :
    dirDeriv f x = supportFn B.flip (subgradient B f x) := by
  have hxdom : x ∈ dom f := intrinsicInterior_subset hx
  exact dirDeriv_eq_supportFn_of_closedFn hf (mem_dom.1 hxdom).ne (hp.ne_bot x)
    (closedFn_dirDeriv_of_mem_relint_dom hf hp hx)

/-- **Rockafellar, Theorem 23.4.** A proper convex function is subdifferentiable at every relative
interior point of its effective domain. -/
theorem subgradient_nonempty_of_mem_relint_dom [IsCompatiblePairing B] (hf : ConvexFn f)
    (hp : Proper f) (hx : x ∈ ri (dom f)) : (subgradient B f x).Nonempty := by
  have hxdom : x ∈ dom f := intrinsicInterior_subset hx
  exact subgradient_nonempty_of_closedFn_dirDeriv hf (mem_dom.1 hxdom).ne (hp.ne_bot x)
    (closedFn_dirDeriv_of_mem_relint_dom hf hp hx)

/-- **Rockafellar, Theorem 23.4**, last clause, in terms of the directional derivative: `f'(x; ·)`
is finite everywhere exactly when `x` is an interior point of `dom f`. -/
theorem dom_dirDeriv_eq_univ_iff_mem_interior_dom (hf : ConvexFn f) (hp : Proper f)
    (hx : x ∈ ri (dom f)) : dom (dirDeriv f x) = univ ↔ x ∈ interior (dom f) := by
  have hxaff : x ∈ affineSpan ℝ (dom f) := subset_affineSpan ℝ (dom f) (intrinsicInterior_subset hx)
  have hdom := dom_dirDeriv_of_mem_relint_dom hf hp hx
  constructor
  · intro huniv
    have hdir : ((affineSpan ℝ (dom f)).direction : Set E) = univ := by rw [← hdom, huniv]
    have htop : affineSpan ℝ (dom f) = ⊤ := by
      refine eq_top_iff.2 fun z _ => ?_
      have hz : z - x ∈ (affineSpan ℝ (dom f)).direction := by
        rw [← SetLike.mem_coe, hdir]; trivial
      have h := AffineSubspace.vadd_mem_of_mem_direction hz hxaff
      have he : (z - x) +ᵥ x = z := by rw [vadd_eq_add]; abel
      rwa [he] at h
    rw [← intrinsicInterior_eq_interior htop]
    exact hx
  · intro hint
    have htop : affineSpan ℝ (dom f) = ⊤ :=
      (Convex.interior_nonempty_iff_affineSpan_eq_top hf.convex_dom).1 ⟨x, hint⟩
    rw [hdom, htop, AffineSubspace.direction_top]
    exact Submodule.top_coe

/-- **Rockafellar, Theorem 23.4**, last clause. `∂f x` is bounded — in the pairing sense of
Corollary 13.2.2, that every `⟨·, y⟩` is bounded above on it — exactly when `x` is an interior
point of `dom f`. -/
theorem bddAbove_subgradient_iff_mem_interior_dom [IsCompatiblePairing B] (hf : ConvexFn f)
    (hp : Proper f) (hx : x ∈ ri (dom f)) :
    (∀ v : E, ∃ c : ℝ, ∀ y ∈ subgradient B f x, B v y ≤ c) ↔ x ∈ interior (dom f) := by
  rw [← dom_dirDeriv_eq_univ_iff_mem_interior_dom hf hp hx,
    dirDeriv_eq_supportFn_of_mem_relint_dom (B := B) hf hp hx]
  constructor
  · intro h
    refine eq_univ_of_forall fun v => ?_
    exact mem_dom.2 (supportFn_lt_top_iff.2 (h v))
  · intro h v
    exact supportFn_lt_top_iff.1 (mem_dom.1 (h ▸ Set.mem_univ v))

end Relint

/-! ### Theorem 23.10: polyhedral functions -/

section Polyhedral

variable {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  [AddCommGroup F] [Module ℝ F] {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} {f : E → EReal} {x : E}

/-- **Rockafellar, Theorem 23.10**, first step: the directional derivative of a polyhedral convex
function at a point where it is finite is again polyhedral. The polyhedral convex set
`epi f - (x, f x)` contains the origin, so the convex cone it generates is finitely generated
(Corollary 19.7.1), hence closed — and a closed cone of this kind *is* the epigraph of
`f'(x; ·)`. -/
theorem polyhedralFn_dirDeriv (hf : PolyhedralFn f) (ht : f x ≠ ⊤) (hb : f x ≠ ⊥) :
    PolyhedralFn (dirDeriv f x) := by
  obtain ⟨r, hr⟩ := EReal.exists_coe_of_ne_bot_of_lt_top hb (lt_top_iff_ne_top.2 ht)
  have hsub : Polyhedral (epi f - {((x, r) : E × ℝ)}) :=
    Polyhedral.sub hf (polyhedral_singleton _)
  have h0 : (0 : E × ℝ) ∈ epi f - {((x, r) : E × ℝ)} :=
    ⟨(x, r), (mk_mem_epi.2 hr.le : ((x, r) : E × ℝ) ∈ epi f), (x, r), rfl, sub_self _⟩
  have hfg := finitelyGeneratedCone_hull_of_zero_mem hsub h0
  change Polyhedral (epi (dirDeriv f x))
  rw [epi_dirDeriv_eq_coe_hull hf.convexFn hr hfg.isClosed]
  exact hfg.polyhedralCone.polyhedral

/-- **Rockafellar, Theorem 23.10**, second step: `f'(x; ·)` is proper. A polyhedral convex
function taking the value `−∞` somewhere is `−∞` on the whole closure of its effective domain
(Corollary 7.2.1), and `f'(x; 0) = 0`. -/
theorem proper_dirDeriv_of_polyhedralFn (hf : PolyhedralFn f) (ht : f x ≠ ⊤) (hb : f x ≠ ⊥) :
    Proper (dirDeriv f x) := by
  have hpoly := polyhedralFn_dirDeriv hf ht hb
  have h0 : (0 : E) ∈ dom (dirDeriv f x) := by
    rw [mem_dom, dirDeriv_zero ht hb]; exact _root_.EReal.zero_lt_top
  by_contra hcon
  have hbot := hpoly.convexFn.eq_bot_of_mem_closure_dom hpoly.lowerSemicontinuous hcon
    (subset_closure h0)
  rw [dirDeriv_zero ht hb] at hbot
  exact absurd hbot (by simp)

/-- **Rockafellar, Theorem 23.10.** For a polyhedral convex function the directional derivative is
exactly the support function of the subdifferential. -/
theorem dirDeriv_eq_supportFn_of_polyhedralFn [IsCompatiblePairing B] (hf : PolyhedralFn f)
    (ht : f x ≠ ⊤) (hb : f x ≠ ⊥) :
    dirDeriv f x = supportFn B.flip (subgradient B f x) :=
  dirDeriv_eq_supportFn_of_closedFn hf.convexFn ht hb
    ((polyhedralFn_dirDeriv hf ht hb).closedFn (proper_dirDeriv_of_polyhedralFn hf ht hb).ne_bot)

/-- **Rockafellar, Theorem 23.10.** A polyhedral convex function is subdifferentiable at every
point where it is finite. -/
theorem subgradient_nonempty_of_polyhedralFn [IsCompatiblePairing B] (hf : PolyhedralFn f)
    (ht : f x ≠ ⊤) (hb : f x ≠ ⊥) : (subgradient B f x).Nonempty :=
  subgradient_nonempty_of_closedFn_dirDeriv hf.convexFn ht hb
    ((polyhedralFn_dirDeriv hf ht hb).closedFn (proper_dirDeriv_of_polyhedralFn hf ht hb).ne_bot)

end Polyhedral

section PolyhedralSubgradient

variable {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F] [FiniteDimensional ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} {f : E → EReal} {x : E}

/-- **Rockafellar, Theorem 23.10.** The subdifferential of a polyhedral convex function is a
polyhedral convex set: `∂f x` is the effective domain of `(f'(x; ·))*`, which is the indicator of
`∂f x` by Theorem 23.2 and polyhedral by Theorem 19.2. -/
theorem polyhedral_subgradient_of_polyhedralFn (hf : PolyhedralFn f) (ht : f x ≠ ⊤) (hb : f x ≠ ⊥) :
    Polyhedral (subgradient B f x) := by
  have hconj : PolyhedralFn (conj B (dirDeriv f x)) :=
    PolyhedralFn.conj (polyhedralFn_dirDeriv hf ht hb)
  rw [conj_dirDeriv ht hb] at hconj
  have h := hconj.polyhedral_dom
  rwa [dom_indicatorFn] at h

end PolyhedralSubgradient

end Tdaf.ConvexAnalysis
