/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Tdaf.Analysis.Convex.Duality.Gauge
import Tdaf.Analysis.Convex.Duality.Level
import Tdaf.Analysis.Convex.Homogenize
import Tdaf.Analysis.Convex.Lattice
import Tdaf.Analysis.Convex.Operations.Image
import Tdaf.Analysis.Convex.Operations.InfConv
import Tdaf.Surface.Common.Euclidean

/-!
# Rockafellar, §5: Functional Operations

R. T. Rockafellar, *Convex Analysis* (Princeton, 1970), §5, pp. 32–42: the operations that build
new convex functions out of old ones. Every numbered result of the section is here, stated in the
book's own terms over `Rn n = ℝⁿ` with extended-real values, and closed by specialising the
backbone.

## Contents

| label | declaration |
|---|---|
| Theorem 5.1 | `theorem_5_1` — outer composition `φ ∘ f` |
| Theorem 5.2 | `theorem_5_2` — `f₁ + f₂` |
| Theorem 5.3 | `theorem_5_3` — the lower boundary of a convex set in `ℝⁿ⁺¹` |
| Theorem 5.4 | `theorem_5_4` — infimal convolution `f₁ □ ⋯ □ fₘ` |
| Theorem 5.5 | `theorem_5_5` — the pointwise supremum |
| Theorem 5.6 | `theorem_5_6` — the formula for `conv {fᵢ}` |
| Theorem 5.7 | `theorem_5_7_gA`, `theorem_5_7_Ah` — inverse image and image under `A` |
| Theorem 5.8 | `theorem_5_8_f`, `theorem_5_8_g`, `theorem_5_8_h`, `theorem_5_8_k` |

Theorem 5.7 and Theorem 5.8 have no letter labels in the book; the suffixes are the book's own
symbols — `gA` and `Ah` for Theorem 5.7, and the four displayed function names `f`, `g`, `h`, `k`
for Theorem 5.8.

The section's *definitions* are recorded alongside: the notation `□` (`infimalConvolution_apply`
and the monoid laws), left and right scalar multiplication (`convexFn_leftSMul`,
`rightSMul_apply_pos`, `rightSMul_zero`, `rightSMul_zero_of_top`), the positively
homogeneous convex function generated by `h` (`isGreatest_posHomGen`, `posHomGen_apply`), the
convex hull of a function and of a collection (`isGreatest_conv`, `isGreatest_convCollection`),
the complete lattice of convex functions (`coe_iInf_convexFns`, `coe_iSup_convexFns`), and the
two examples the book computes from Theorem 5.5 (`convexFn_maxCoord`,
`convexFn_tchebycheffNorm`).

## The two traps of §5

**Properness is not preserved by `□`** (book, p. 35). No declaration here concludes properness of
an infimal convolute, and `exists_not_proper_infimalConvolution` is the machine-checked witness:
`f x = ⟨v, x⟩` and `g x = -⟨v, x⟩` are proper convex with `f □ g ≡ -∞`. The same fact is why the
backbone *defines* `□` by adding epigraphs rather than by the infimum formula, which would be
`∞ - ∞`; `infimalConvolution_apply` recovers the formula under properness.

**`f0` is defined by cases.** `rightSMul_zero` gives `f0 = δ(· | 0)` when `f ≢ +∞` and
`rightSMul_zero_of_top` gives `f0 = f` when `f ≡ +∞`; the split is the book's own and is not
smoothed over. `hom_apply_smul` is where the case split meets the other convention of §4,
`0 · ∞ = 0`, and the two agree.

## What is not here

* **`ℝⁿ⁺¹` is `Rn n × ℝ`.** Theorem 5.3 quantifies over `Set (Rn n × ℝ)`, which is what "a convex
  set `F` in `ℝⁿ⁺¹`" means when the theorem goes on to write `(x, μ) ∈ F`. Transporting between
  `Rn n × ℝ` and `Rn (n + 1)` is separate work and is deliberately not attempted here.
* **The gauge is not identified with `posHomGen (δ(· | C) + 1)`** — *omitted, backbone gap*. The
  book defines `γ(· | C)` as the positively homogeneous convex function generated by
  `δ(· | C) + 1` and then computes `inf {λ ≥ 0 | x ∈ λ C}`; the backbone takes the computed
  formula as the definition (`gaugeFn`, `Duality/Gauge.lean`) and has no bridge lemma to
  `posHomGen` (`Recession/ConeHull.lean`). The bridge belongs in the backbone, beside one of those
  two files, not here.
* **The eight natural binary operations (book, pp. 40–41) are not constructed** — *deferred by
  scope*. They rest on the informal partial-addition construction of §3, which `Section03.lean`
  owns. Nothing here needs them: Theorem 5.8's four *statements* are explicit formulas, and each
  is proved as an instance of Theorem 5.7 instead of by partial addition.
* **`f` is the greatest of the components / Tchebycheff norm as support function and gauge** —
  *omitted*. The book adds that the two examples after Theorem 5.5 are the support function of the
  unit simplex and, respectively, the support function of the cross-polytope and the gauge of the
  cube. Those are §13 and §15 statements; only the convexity claims, which are what §5 proves, are
  recorded.
* **`(‖·‖ □ δ(· | C)) = d(· , C)`** — *omitted*. The book's illustration that the distance function
  is convex. `d(·, C)` is not a §5 notion and the backbone's distance function belongs with §8.

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §5.
-/

open Set Pointwise

namespace Rockafellar

open Tdaf.ConvexAnalysis Tdaf.Surface

/-! ### Linear functionals on `ℝⁿ`

Two small pieces of `ℝⁿ` bookkeeping that the examples of this section need and that the backbone,
which is written for a general topological vector space, has no reason to carry. -/

/-- The `j`-th coordinate of `ℝⁿ`, as a linear functional. -/
noncomputable def coordFunctional (n : ℕ) (j : Fin n) : Rn n →ₗ[ℝ] ℝ where
  toFun x := x j
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

@[simp] theorem coordFunctional_apply {n : ℕ} (j : Fin n) (x : Rn n) :
    coordFunctional n j x = x j := rfl

/-! ### Theorem 5.1 -/

/-- **Rockafellar, Theorem 5.1.** Let `f` be a convex function from `ℝⁿ` to `(-∞, +∞]`, and let
`φ` be a non-decreasing convex function from `ℝ` to `(-∞, +∞]`. Then `h x = φ (f x)` is convex on
`ℝⁿ`, where one sets `φ (+∞) = +∞`.

Specialises `ConvexFn.comp_extendTop`; `extendTop φ` is `φ` extended by Rockafellar's
convention `φ (+∞) = +∞`. -/
theorem theorem_5_1 {n : ℕ} {f : Rn n → EReal} {φ : ℝ → EReal} (hf : ConvexFn f)
    (hf' : ∀ x, f x ≠ ⊥) (hφ : ConvexFn φ) (hmono : Monotone φ) :
    ConvexFn fun x => extendTop φ (f x) :=
  hf.comp_extendTop hf' hφ hmono

/-! ### Theorem 5.2 -/

/-- **Rockafellar, Theorem 5.2.** If `f₁` and `f₂` are proper convex functions on `ℝⁿ`, then
`f₁ + f₂` is convex.

Specialises `ConvexFn.add`. Rockafellar's properness hypothesis is there only "for the sake of
avoiding `∞ - ∞`", and only its `≠ -∞` half is used. -/
theorem theorem_5_2 {n : ℕ} {f₁ f₂ : Rn n → EReal} (h₁ : ConvexFn f₁) (hp₁ : Proper f₁)
    (h₂ : ConvexFn f₂) (hp₂ : Proper f₂) : ConvexFn (f₁ + f₂) :=
  h₁.add h₂ hp₁.ne_bot hp₂.ne_bot

/-! ### Theorem 5.3 -/

/-- **Rockafellar, Theorem 5.3.** Let `F` be any convex set in `ℝⁿ⁺¹`, and let
`f x = inf {μ | (x, μ) ∈ F}`. Then `f` is a convex function on `ℝⁿ`.

Specialises `convexFn_ofEpi`. Rockafellar's `ℝⁿ⁺¹` is read as `Rn n × ℝ`: the theorem is
about pairs `(x, μ)`, and the transport between `Rn n × ℝ` and `Rn (n + 1)` is a separate
matter. -/
theorem theorem_5_3 {n : ℕ} {F : Set (Rn n × ℝ)} (hF : Convex ℝ F) {f : Rn n → EReal}
    (hf : ∀ x, f x = ⨅ μ ∈ {μ : ℝ | (x, μ) ∈ F}, (μ : EReal)) : ConvexFn f := by
  have hfF : f = ofEpi F := funext hf
  rw [hfF]
  exact convexFn_ofEpi hF

/-! ### Theorem 5.4 -/

/-- A convex function of a single coordinate of `(ℝⁿ)ᵐ` is convex as a function of the whole
tuple: this is the inverse image under the `i`-th projection, Theorem 5.7. -/
theorem convexFn_coord {n m : ℕ} {g : Rn n → EReal} (hg : ConvexFn g) (i : Fin m) :
    ConvexFn fun p : Fin m → Rn n => g (p i) := by
  have h := convexFn_compLin (E := Fin m → Rn n) (G := Rn n)
    (LinearMap.proj (R := ℝ) (φ := fun _ : Fin m => Rn n) i) hg
  exact h

/-- The linear map `(x₁, …, xₘ) ↦ x₁ + ⋯ + xₘ` on `(ℝⁿ)ᵐ`. Every `m`-ary operation of this
section that "adds in `x`" is an image under this map, in the sense of Theorem 5.7. -/
noncomputable def sumLin (n m : ℕ) : (Fin m → Rn n) →ₗ[ℝ] Rn n :=
  ∑ i, LinearMap.proj i

@[simp] theorem sumLin_apply {n m : ℕ} (p : Fin m → Rn n) : sumLin n m p = ∑ i, p i := by
  simp [sumLin, LinearMap.sum_apply]

/-- **Rockafellar, Theorem 5.4.** Let `f₁, …, fₘ` be proper convex functions on `ℝⁿ`, and let
`f x = inf {f₁ x₁ + ⋯ + fₘ xₘ | xᵢ ∈ ℝⁿ, x₁ + ⋯ + xₘ = x}`. Then `f` is a convex function
on `ℝⁿ`.

The function `f` is Rockafellar's infimal convolute `f₁ □ ⋯ □ fₘ`; `□` is defined below.

Proved as Rockafellar's Theorem 5.7 rather than his Theorem 5.3: the displayed infimum is exactly
the *image* `A h` of the separable function `h (x₁, …, xₘ) = f₁ x₁ + ⋯ + fₘ xₘ` under the summation
map, so `convexFn_mapLin` applies to `ConvexFn.sum` of the coordinate functions. Properness is
used only through its `≠ -∞` half, which is what makes the sum unambiguous. -/
theorem theorem_5_4 {n m : ℕ} {f : Fin m → Rn n → EReal} (hf : ∀ i, ConvexFn (f i))
    (hp : ∀ i, Proper (f i)) :
    ConvexFn fun x => ⨅ p ∈ {p : Fin m → Rn n | ∑ i, p i = x}, ∑ i, f i (p i) := by
  have hsep : ConvexFn fun p : Fin m → Rn n => ∑ i, f i (p i) :=
    ConvexFn.sum (s := (Finset.univ : Finset (Fin m)))
      (fun i _ => convexFn_coord (hf i) i) (fun i _ p => (hp i).ne_bot (p i))
  have hmap := convexFn_mapLin (sumLin n m) hsep
  have hkey : mapLin (sumLin n m) (fun p : Fin m → Rn n => ∑ i, f i (p i))
      = fun x => ⨅ p ∈ {p : Fin m → Rn n | ∑ i, p i = x}, ∑ i, f i (p i) := by
    funext x
    simp only [mapLin, sumLin_apply]
  rwa [hkey] at hmap

/-! ### Infimal convolution

Rockafellar, §5, after Theorem 5.4: "The function `f` in Theorem 5.4 will be denoted by
`f₁ □ f₂ □ ⋯ □ fₘ`. The operation `□` is called infimal convolution." -/

@[inherit_doc Tdaf.ConvexAnalysis.infConv]
scoped infixl:65 " □ " => Tdaf.ConvexAnalysis.infConv

/-- **Rockafellar, Theorem 5.4**, binary case: `f □ g` is convex whenever `f` and `g` are.

Specialises `convexFn_infConv`. Note that convexity of `f □ g` needs no properness: the
epigraph definition `f □ g = ofEpi (epi f + epi g)` is Theorem 5.3 applied to a sum of convex
sets, and Rockafellar's properness hypothesis is only what makes the *infimum formula*
meaningful. -/
theorem convexFn_infimalConvolution {n : ℕ} {f g : Rn n → EReal} (hf : ConvexFn f)
    (hg : ConvexFn g) : ConvexFn (f □ g) :=
  convexFn_infConv hf hg

/-- **Rockafellar, §5.** "When only two functions are involved, `□` can be expressed by
`(f □ g) x = infᵧ {f (x - y) + g y}`, and this is analogous to the classical formula for integral
convolution."

Specialises `infConv_apply`. Properness is what makes the right-hand side unambiguous: the
backbone *defines* `f □ g` through epigraph addition, exactly as Rockafellar does at line 1535,
because the displayed infimum produces the forbidden `∞ - ∞` when one function reaches `-∞`. -/
theorem infimalConvolution_apply {n : ℕ} {f g : Rn n → EReal} (hf : Proper f) (hg : Proper g)
    (x : Rn n) : (f □ g) x = ⨅ y, f (x - y) + g y :=
  infConv_apply hf.ne_bot hg.ne_bot x

/-- **Rockafellar, §5.** "The effective domain of `f □ g` is the sum of `dom f` and `dom g`."

Specialises `dom_infConv`, which needs no hypothesis at all. -/
theorem dom_infimalConvolution {n : ℕ} (f g : Rn n → EReal) :
    dom (f □ g) = dom f + dom g :=
  dom_infConv f g

/-- **Rockafellar, §5.** "`f □ δ(· | a)` is the function whose graph is obtained by translating
the graph of `f` horizontally by `a`."

Specialises `infConv_indicatorFn_singleton`. -/
theorem infimalConvolution_indicatorFn_singleton {n : ℕ} (f : Rn n → EReal) (a : Rn n) :
    (f □ indicatorFn ({a} : Set (Rn n))) = fun x => f (x - a) :=
  infConv_indicatorFn_singleton f a

/-- **Rockafellar, §5.** "As an operation on the collection of all functions from `ℝⁿ` to
`[-∞, +∞]`, infimal convolution is commutative, associative and convexity-preserving. The function
`δ(· | 0)` acts as the identity element for this operation."

The backbone records the monoid structure on the type synonym `InfConvFn (Rn n)`; the three
equations are `infConv_comm`, `infConv_assoc` and `infConv_indicatorFn_zero`, and
convexity-preservation is `convexFn_infimalConvolution` above. -/
theorem infimalConvolution_isCommMonoid {n : ℕ} :
    (∀ f g : Rn n → EReal, (f □ g) = g □ f) ∧
      (∀ f g h : Rn n → EReal, ((f □ g) □ h) = f □ (g □ h)) ∧
      (∀ f : Rn n → EReal, (f □ indicatorFn ({0} : Set (Rn n))) = f) :=
  ⟨infConv_comm, infConv_assoc, infConv_indicatorFn_zero⟩

/-- **Rockafellar, §5** (the paragraph at the top of p. 35): "Properness of convex functions is not
always preserved by infimal convolution, since the infimum in the formula in Theorem 5.4 may be
`-∞`."

The witness is the pair `f x = ⟨v, x⟩`, `g x = -⟨v, x⟩` for any `v ≠ 0`: both are finite, hence
proper, convex (and concave), while `(f □ g) x = infᵧ {⟨v, x - y⟩ - ⟨v, y⟩} = -∞` for every `x`.
This is why no result of this section concludes properness of `f □ g`, and why the backbone
defines `□` through epigraph addition rather than through the infimum formula. -/
theorem exists_not_proper_infimalConvolution {n : ℕ} {v : Rn n} (hv : v ≠ 0) :
    ∃ f g : Rn n → EReal, ConvexFn f ∧ Proper f ∧ ConvexFn g ∧ Proper g ∧ ¬ Proper (f □ g) := by
  have hsurj : Function.Surjective (pairing n v) := by
    refine LinearMap.surjective_of_ne_zero ?_
    intro hzero
    refine hv ((inner_self_eq_zero (𝕜 := ℝ)).1 ?_)
    have hvv := congrArg (fun t : Rn n →ₗ[ℝ] ℝ => t v) hzero
    simpa using hvv
  have hbot : infConv (fun x : Rn n => ((pairing n v x : ℝ) : EReal))
      (fun x : Rn n => ((-(pairing n v x) : ℝ) : EReal)) 0 = ⊥ := by
    rw [infConv_apply (fun x => by simp) (fun x => by simp) 0]
    refine Tdaf.EReal.eq_bot_of_forall_le_coe fun r => ?_
    obtain ⟨y, hy⟩ := hsurj (-r / 2)
    refine le_trans (iInf_le _ y) (le_of_eq ?_)
    rw [← _root_.EReal.coe_add, _root_.EReal.coe_eq_coe_iff, map_sub, map_zero, hy]
    ring
  exact ⟨_, _, convexFn_coe_linearMap (pairing n v), ⟨⟨0, by simp⟩, fun x => by simp⟩,
    convexFn_coe_linearMap (-(pairing n v)), ⟨⟨0, by simp⟩, fun x => by simp⟩,
    fun hproper => hproper.ne_bot 0 hbot⟩

/-! ### Left and right scalar multiplication

Rockafellar, §5: `(λf) x = λ (f x)` for `λ ≥ 0`, and `fλ` is the function obtained from
Theorem 5.3 with `F = λ (epi f)`. -/

/-- **Rockafellar, §5.** "The operation of non-negative left scalar multiplication preserves
convexity, where `(λ f) x = λ (f x)`."

Specialises `ConvexFn.smul`. `EReal` obeys Rockafellar's convention `0 · ∞ = 0`, so `λ = 0`
is not a special case here. -/
theorem convexFn_leftSMul {n : ℕ} {f : Rn n → EReal} (l : ℝ) (hl : 0 ≤ l) (hf : ConvexFn f) :
    ConvexFn fun x => (l : EReal) * f x :=
  hf.smul l hl

/-- **Rockafellar, §5.** Right scalar multiplication preserves convexity: `fλ` is Theorem 5.3
applied to the convex set `λ (epi f)`.

Specialises `convexFn_smulRight`. -/
theorem convexFn_rightSMul {n : ℕ} {f : Rn n → EReal} (l : ℝ) (hf : ConvexFn f) :
    ConvexFn (smulRight f l) :=
  convexFn_smulRight l hf

/-- **Rockafellar, §5**, first branch of the definition of `fλ`:
`(fλ) x = λ f (λ⁻¹ x)` for `λ > 0`.

Specialises `smulRight_apply_pos`. -/
theorem rightSMul_apply_pos {n : ℕ} {l : ℝ} (hl : 0 < l) (f : Rn n → EReal) (x : Rn n) :
    smulRight f l x = (l : EReal) * f (l⁻¹ • x) :=
  smulRight_apply_pos hl f x

/-- **Rockafellar, §5**, second branch: `(f0) x = δ(x | 0)` provided `f ≢ +∞`.

Specialises `smulRight_zero`. The side condition is Rockafellar's own, and it is not decoration:
see `rightSMul_zero_of_top`. This case split is the discontinuity that recurs in §§8, 9, 13,
15 and 19. -/
theorem rightSMul_zero {n : ℕ} {f : Rn n → EReal} (hf : (dom f).Nonempty) :
    smulRight f 0 = indicatorFn ({0} : Set (Rn n)) :=
  smulRight_zero hf

/-- **Rockafellar, §5**, third branch: "trivially `f0 = f` if `f ≡ +∞`".

Specialises `smulRight_of_epi_eq_empty`. Together with `rightSMul_zero` this is the whole of
the book's definition by cases at `λ = 0`. -/
theorem rightSMul_zero_of_top {n : ℕ} {f : Rn n → EReal} (hf : f = ⊤) :
    smulRight f 0 = f := by
  rw [smulRight_of_epi_eq_empty (by rw [hf]; exact epi_top) 0, hf]

/-- **Rockafellar, §5.** "A function `f` is positively homogeneous if and only if `fλ = f` for
every `λ > 0`."

Specialises `posHomogeneous_iff_smulRight_eq`. -/
theorem posHomogeneous_iff_rightSMul_eq {n : ℕ} {f : Rn n → EReal} :
    PosHomogeneous f ↔ ∀ l > (0 : ℝ), smulRight f l = f :=
  posHomogeneous_iff_smulRight_eq

/-! ### The positively homogeneous convex function generated by `h` -/

/-- **Rockafellar, §5.** Let `h` be a convex function on `ℝⁿ` and let `F` be the convex cone in
`ℝⁿ⁺¹` generated by `epi h`. The function obtained by applying Theorem 5.3 to `F` "is the greatest
of the positively homogeneous convex functions `f` such that `f 0 ≤ 0` and `f ≤ h`". It is called
the positively homogeneous convex function generated by `h`.

Specialises `posHomGen_isGreatest`. Note this is *not* the operator `hom` of the backbone,
which is the same construction applied to the level-one lift of `h` and therefore lives one
dimension up. -/
theorem isGreatest_posHomGen {n : ℕ} (h : Rn n → EReal) :
    IsGreatest {f : Rn n → EReal | PosHomogeneous f ∧ ConvexFn f ∧ f 0 ≤ 0 ∧ f ≤ h}
      (posHomGen h) :=
  posHomGen_isGreatest h

/-- **Rockafellar, §5.** `f x = inf {(hλ) x | λ ≥ 0}` for the positively homogeneous convex
function `f` generated by `h`; "`λ = 0` can be omitted from the infimum if `x ≠ 0`".

Specialises `posHomGen_apply_of_ne_zero`, which is the form with `λ = 0` omitted. -/
theorem posHomGen_apply {n : ℕ} {h : Rn n → EReal} (hh : ConvexFn h) {x : Rn n} (hx : x ≠ 0) :
    posHomGen h x = ⨅ l > (0 : ℝ), smulRight h l x := by
  rw [posHomGen_apply_of_ne_zero hh hx]
  exact iInf_congr fun l => iInf_congr fun hl => (smulRight_apply_pos hl h x).symm

/-! ### Theorem 5.5 -/

/-- **Rockafellar, Theorem 5.5.** The pointwise supremum of an arbitrary collection of convex
functions is convex.

Specialises `convexFn_iSup`. -/
theorem theorem_5_5 {n : ℕ} {ι : Sort*} {f : ι → Rn n → EReal} (hf : ∀ i, ConvexFn (f i)) :
    ConvexFn fun x => ⨆ i, f i x :=
  convexFn_iSup hf

/-- **Rockafellar, §5**, the illustration after Theorem 5.5: the function assigning to
`x = (ξ₁, …, ξₙ)` the greatest of its components is convex, "because it is the pointwise supremum
of the linear functions `⟨x, eⱼ⟩`". (It is also the support function of the unit simplex.) -/
theorem convexFn_maxCoord {n : ℕ} :
    ConvexFn fun x : Rn n => ⨆ j : Fin n, ((x j : ℝ) : EReal) :=
  convexFn_iSup fun j => convexFn_coe_linearMap (coordFunctional n j)

/-- **Rockafellar, §5**: the convexity of `k x = max {|ξⱼ| : j = 1, …, n}`, "which is called the
**Tchebycheff norm** on `ℝⁿ`, can be seen similarly from Theorem 5.5".

It is the pointwise supremum of the `2n` linear functions `± ξⱼ`. -/
theorem convexFn_tchebycheffNorm {n : ℕ} :
    ConvexFn fun x : Rn n => ⨆ j : Fin n, ((|x j| : ℝ) : EReal) := by
  have hrw : (fun x : Rn n => ⨆ j : Fin n, ((|x j| : ℝ) : EReal))
      = fun x : Rn n => ⨆ p : Fin n × Bool, ((cond p.2 (x p.1) (-(x p.1)) : ℝ) : EReal) := by
    funext x
    rw [iSup_prod]
    refine iSup_congr fun j => ?_
    simp only [abs_eq_max_neg, iSup_bool_eq, Bool.cond_true, Bool.cond_false]
    exact_mod_cast rfl
  rw [hrw]
  refine convexFn_iSup fun p => ?_
  obtain ⟨j, b⟩ := p
  cases b
  · exact convexFn_coe_linearMap (-coordFunctional n j)
  · exact convexFn_coe_linearMap (coordFunctional n j)

/-! ### The convex hull of a function, and of a collection

Rockafellar §5, after Theorem 5.5: `conv g` is the function obtained from Theorem 5.3 with
`F = conv (epi g)`, and `conv {fᵢ | i ∈ I}` is obtained the same way from the convex hull of the
union of the epigraphs. -/

/-- **Rockafellar, §5.** `conv g` "is the greatest convex function majorized by `g`".

Restates `isGreatest_convHullFn`. -/
theorem isGreatest_conv {n : ℕ} (g : Rn n → EReal) :
    IsGreatest {h : Rn n → EReal | ConvexFn h ∧ h ≤ g} (convHullFn g) :=
  isGreatest_convHullFn g

/-- **Rockafellar, §5.** `conv {fᵢ | i ∈ I}` "is the greatest convex function `f` (not necessarily
proper) on `ℝⁿ` such that `f x ≤ fᵢ x` for every `x ∈ ℝⁿ` and every `i ∈ I`".

Restates `isGreatest_convFn`. -/
theorem isGreatest_convCollection {n : ℕ} {ι : Sort*} (f : ι → Rn n → EReal) :
    IsGreatest {g : Rn n → EReal | ConvexFn g ∧ ∀ i, g ≤ f i} (convFn f) :=
  isGreatest_convFn f

/-! ### Theorem 5.6 -/

/-- **Rockafellar, Theorem 5.6.** Let `{fᵢ | i ∈ I}` be a collection of proper convex functions on
`ℝⁿ`, `I` an arbitrary index set, and let `f` be the convex hull of the collection. Then

`f x = inf {∑ᵢ λᵢ fᵢ xᵢ | ∑ᵢ λᵢ xᵢ = x}`,

the infimum being taken over all representations of `x` as a convex combination of elements `xᵢ`
in which only finitely many coefficients `λᵢ` are nonzero.

Specialises `convFn_apply`; the finitely-many-nonzero condition is carried by the `Finset t`.
This is the function-level analogue of Theorem 2.3. -/
theorem theorem_5_6 {n : ℕ} {ι : Type*} {f : ι → Rn n → EReal} (hf : ∀ i, ConvexFn (f i))
    (hp : ∀ i, Proper (f i)) (x : Rn n) :
    convFn f x = sInf {z : EReal | ∃ (t : Finset ι) (w : ι → ℝ) (p : ι → Rn n),
      (∀ i ∈ t, 0 ≤ w i) ∧ ∑ i ∈ t, w i = 1 ∧ ∑ i ∈ t, w i • p i = x ∧
        z = ∑ i ∈ t, (w i : EReal) * f i (p i)} :=
  convFn_apply hf (fun i y => (hp i).ne_bot y) x

/-- **Rockafellar, §5**, the paragraph after Theorem 5.6: the convex functions on `ℝⁿ`, ordered
pointwise, form a **complete lattice** whose greatest lower bound is `conv {fᵢ | i ∈ I}` and whose
least upper bound is `sup {fᵢ | i ∈ I}`.

The lattice is `ConvexFns (Rn n)`; `ConvexFns.coe_iInf` and `ConvexFns.coe_iSup` are the two
identifications, and `ConvexFns.not_coe_inf_eq_inf` is the machine-checked warning behind
Rockafellar's parenthesis "(relative to this particular partially ordered set!)". -/
theorem coe_iInf_convexFns {n : ℕ} {ι : Sort*} (f : ι → ConvexFns (Rn n)) :
    ((⨅ i, f i : ConvexFns (Rn n)) : Rn n → EReal) = convFn fun i => (f i : Rn n → EReal) :=
  ConvexFns.coe_iInf f

/-- The other half of the lattice sentence: the least upper bound is the pointwise supremum,
which is Theorem 5.5. -/
theorem coe_iSup_convexFns {n : ℕ} {ι : Sort*} (f : ι → ConvexFns (Rn n)) (x : Rn n) :
    ((⨆ i, f i : ConvexFns (Rn n)) : Rn n → EReal) x = ⨆ i, (f i : Rn n → EReal) x :=
  ConvexFns.coe_iSup_apply f x

/-! ### Theorem 5.7 -/

/-- **Rockafellar, Theorem 5.7**, first assertion. Let `A` be a linear transformation from `ℝⁿ` to
`ℝᵐ`. For each convex function `g` on `ℝᵐ`, the *inverse image* `gA`, `(gA) x = g (A x)`, is convex
on `ℝⁿ`.

Specialises `convexFn_compLin`. -/
theorem theorem_5_7_gA {n m : ℕ} (A : Rn n →ₗ[ℝ] Rn m) {g : Rn m → EReal} (hg : ConvexFn g) :
    ConvexFn fun x => g (A x) :=
  convexFn_compLin A hg

/-- **Rockafellar, Theorem 5.7**, second assertion. For each convex function `h` on `ℝⁿ`, the
*image* `Ah`, `(Ah) y = inf {h x | A x = y}`, is convex on `ℝᵐ`.

Specialises `convexFn_mapLin`. The infimum need not be attained, which is why `Ah` is not read off
the image of `epi h` as a set. -/
theorem theorem_5_7_Ah {n m : ℕ} (A : Rn n →ₗ[ℝ] Rn m) {h : Rn n → EReal} (hh : ConvexFn h) :
    ConvexFn fun y => ⨅ x ∈ {x | A x = y}, h x :=
  convexFn_mapLin A hh

/-! ### Theorem 5.8

Rockafellar derives the four operations below from partial additions of the convex cones
`K = {(λ, x, μ) | λ ≥ 0, μ ≥ (fλ) x}` in `ℝⁿ⁺²`, a construction described only informally in §3.
The *statements*, however, are four explicit formulas, and each of them is an instance of
Theorem 5.7 — an image under a linear map — applied to a jointly convex function of the auxiliary
variables. That is the route taken here, so nothing depends on the informal construction. -/

/-- The linear map `(λ, x) ↦ (λ₁ + ⋯ + λₘ, x)`, along which the two "adding in `λ`" operations of
Theorem 5.8 are images. -/
noncomputable def homSumLin (n m : ℕ) : ((Fin m → ℝ) × Rn n) →ₗ[ℝ] ℝ × Rn n :=
  LinearMap.prod ((∑ i, LinearMap.proj i).comp (LinearMap.fst ℝ (Fin m → ℝ) (Rn n)))
    (LinearMap.snd ℝ (Fin m → ℝ) (Rn n))

@[simp] theorem homSumLin_apply {n m : ℕ} (q : (Fin m → ℝ) × Rn n) :
    homSumLin n m q = (∑ i, q.1 i, q.2) := by
  simp [homSumLin]

/-- The linear map `(λ, x) ↦ (λᵢ, x)`, which reads off the `i`-th homogenising variable. -/
noncomputable def coordHomLin (n m : ℕ) (i : Fin m) : ((Fin m → ℝ) × Rn n) →ₗ[ℝ] ℝ × Rn n :=
  LinearMap.prod ((LinearMap.proj i).comp (LinearMap.fst ℝ (Fin m → ℝ) (Rn n)))
    (LinearMap.snd ℝ (Fin m → ℝ) (Rn n))

@[simp] theorem coordHomLin_apply {n m : ℕ} (i : Fin m) (q : (Fin m → ℝ) × Rn n) :
    coordHomLin n m i q = (q.1 i, q.2) := rfl

/-- The joint convexity behind clauses `g` and `h` of Theorem 5.8: `(λ, x) ↦ (fᵢ λᵢ) x` is convex
on `ℝᵐ × ℝⁿ`, since it is the inverse image of `hom fᵢ` under `(λ, x) ↦ (λᵢ, x)`. -/
theorem convexFn_hom_coord {n m : ℕ} {f : Fin m → Rn n → EReal} (hf : ∀ i, ConvexFn (f i))
    (i : Fin m) : ConvexFn fun q : (Fin m → ℝ) × Rn n => hom (f i) (q.1 i, q.2) := by
  have h := convexFn_compLin (coordHomLin n m i) (convexFn_hom (hf i))
  exact h

/-- **Rockafellar, Theorem 5.8**, first function. For proper convex `f₁, …, fₘ` on `ℝⁿ`,

`f x = inf {max {f₁ x₁, …, fₘ xₘ} | x₁ + ⋯ + xₘ = x}`

is convex. Rockafellar obtains it by "adding in `x` alone".

Proved as an instance of Theorem 5.7: the displayed infimum is the image, under
`(x₁, …, xₘ) ↦ x₁ + ⋯ + xₘ`, of the pointwise supremum of the coordinate functions, so
`convexFn_iSup` (Theorem 5.5) and `convexFn_mapLin` suffice. **Properness is not needed**;
the book carries it only because the whole theorem is stated for proper functions. -/
theorem theorem_5_8_f {n m : ℕ} {f : Fin m → Rn n → EReal} (hf : ∀ i, ConvexFn (f i)) :
    ConvexFn fun x => ⨅ p ∈ {p : Fin m → Rn n | ∑ i, p i = x}, ⨆ i, f i (p i) := by
  have hsup : ConvexFn fun p : Fin m → Rn n => ⨆ i, f i (p i) :=
    convexFn_iSup fun i => convexFn_coord (hf i) i
  have hmap := convexFn_mapLin (sumLin n m) hsup
  have hkey : mapLin (sumLin n m) (fun p : Fin m → Rn n => ⨆ i, f i (p i))
      = fun x => ⨅ p ∈ {p : Fin m → Rn n | ∑ i, p i = x}, ⨆ i, f i (p i) := by
    funext x
    simp only [mapLin, sumLin_apply]
  rwa [hkey] at hmap

/-- **Rockafellar, Theorem 5.8**, second function. For proper convex `f₁, …, fₘ` on `ℝⁿ`,

`g x = inf {(f₁ λ₁) x + ⋯ + (fₘ λₘ) x | λᵢ ≥ 0, λ₁ + ⋯ + λₘ = 1}`

is convex. Rockafellar obtains it by "adding in `λ` and `μ`". It is not the formula for
`conv {f₁, …, fₘ}` given after Theorem 5.6, which has `f₁λ₁ □ ⋯ □ fₘλₘ` in place of the
pointwise sum.

Proved as an instance of Theorem 5.7 one dimension up: `(λ, x) ↦ ∑ᵢ (fᵢ λᵢ) x` is convex on
`ℝᵐ × ℝⁿ` because each `(λ, x) ↦ hom fᵢ (λᵢ, x)` is, its image under `(λ, x) ↦ (∑ λᵢ, x)` is
convex, and the displayed function is the slice of that image at `∑ λᵢ = 1`. Properness
enters twice: to make the sum unambiguous (`ConvexFn.sum`), and to see that a tuple `λ` with a
negative entry contributes `+∞` rather than an indeterminate `∞ - ∞`. -/
theorem theorem_5_8_g {n m : ℕ} {f : Fin m → Rn n → EReal} (hf : ∀ i, ConvexFn (f i))
    (hp : ∀ i, Proper (f i)) :
    ConvexFn fun x => ⨅ l ∈ {l : Fin m → ℝ | (∀ i, 0 ≤ l i) ∧ ∑ i, l i = 1},
      ∑ i, smulRight (f i) (l i) x := by
  have hPsi : ConvexFn fun q : (Fin m → ℝ) × Rn n => ∑ i, hom (f i) (q.1 i, q.2) :=
    ConvexFn.sum (s := (Finset.univ : Finset (Fin m)))
      (fun i _ => convexFn_hom_coord hf i) (fun i _ q => hom_ne_bot (hp i).ne_bot (q.1 i, q.2))
  have hslice := (convexFn_mapLin (homSumLin n m) hPsi).slice_left 1
  have hkey : (fun x : Rn n =>
        mapLin (homSumLin n m) (fun q : (Fin m → ℝ) × Rn n => ∑ i, hom (f i) (q.1 i, q.2)) (1, x))
      = fun x => ⨅ l ∈ {l : Fin m → ℝ | (∀ i, 0 ≤ l i) ∧ ∑ i, l i = 1},
        ∑ i, smulRight (f i) (l i) x := by
    funext x
    refine le_antisymm (le_iInf₂ fun l hl => ?_) (le_mapLin fun q hq => ?_)
    · refine (mapLin_le (x := (l, x)) ?_).trans_eq ?_
      · rw [homSumLin_apply, hl.2]
      · exact Finset.sum_congr rfl fun i _ => hom_apply_nonneg (hl.1 i) (f i) x
    · obtain ⟨l, y⟩ := q
      rw [homSumLin_apply, Prod.mk.injEq] at hq
      obtain ⟨hq₁, rfl⟩ := hq
      by_cases hpos : ∀ i, 0 ≤ l i
      · refine le_trans (iInf₂_le l ⟨hpos, hq₁⟩) (le_of_eq ?_)
        exact Finset.sum_congr rfl fun i _ => (hom_apply_nonneg (hpos i) (f i) y).symm
      · obtain ⟨j, hj⟩ := not_forall.1 hpos
        have hbot : ∀ i ∈ (Finset.univ : Finset (Fin m)), hom (f i) (l i, y) ≠ ⊥ :=
          fun i _ => hom_ne_bot (hp i).ne_bot (l i, y)
        have htop : (∑ i, hom (f i) (l i, y)) = ⊤ := by
          by_contra hne
          exact absurd (hom_apply_neg (not_le.1 hj) (f j) y)
            (Tdaf.EReal.forall_ne_top_of_sum_ne_top _ _ hbot hne j (Finset.mem_univ j))
        rw [htop]
        exact le_top
  rwa [hkey] at hslice

/-- **Rockafellar, Theorem 5.8**, third function. For convex `f₁, …, fₘ` on `ℝⁿ`,

`h x = inf {max {(f₁ λ₁) x, …, (fₘ λₘ) x} | λᵢ ≥ 0, λ₁ + ⋯ + λₘ = 1}`

is convex. Rockafellar obtains it by "adding in `λ` alone"; it "amounts to inverse addition of
epigraphs".

Same route as `theorem_5_8_g`, with `max` in place of `∑`. The sign constraint `λᵢ ≥ 0` is
enforced by `hom`, which is `+∞` for negative `λᵢ`. **Properness is not needed** here, because
a supremum, unlike a sum, cannot produce `∞ - ∞`. -/
theorem theorem_5_8_h {n m : ℕ} {f : Fin m → Rn n → EReal} (hf : ∀ i, ConvexFn (f i)) :
    ConvexFn fun x => ⨅ l ∈ {l : Fin m → ℝ | (∀ i, 0 ≤ l i) ∧ ∑ i, l i = 1},
      ⨆ i, smulRight (f i) (l i) x := by
  have hPsi : ConvexFn fun q : (Fin m → ℝ) × Rn n => ⨆ i, hom (f i) (q.1 i, q.2) :=
    convexFn_iSup fun i => convexFn_hom_coord hf i
  have hslice := (convexFn_mapLin (homSumLin n m) hPsi).slice_left 1
  have hkey : (fun x : Rn n =>
        mapLin (homSumLin n m) (fun q : (Fin m → ℝ) × Rn n => ⨆ i, hom (f i) (q.1 i, q.2)) (1, x))
      = fun x => ⨅ l ∈ {l : Fin m → ℝ | (∀ i, 0 ≤ l i) ∧ ∑ i, l i = 1},
        ⨆ i, smulRight (f i) (l i) x := by
    funext x
    refine le_antisymm (le_iInf₂ fun l hl => ?_) (le_mapLin fun q hq => ?_)
    · refine (mapLin_le (x := (l, x)) ?_).trans_eq ?_
      · rw [homSumLin_apply, hl.2]
      · exact iSup_congr fun i => hom_apply_nonneg (hl.1 i) (f i) x
    · obtain ⟨l, y⟩ := q
      rw [homSumLin_apply, Prod.mk.injEq] at hq
      obtain ⟨hq₁, rfl⟩ := hq
      by_cases hpos : ∀ i, 0 ≤ l i
      · refine le_trans (iInf₂_le l ⟨hpos, hq₁⟩) (le_of_eq ?_)
        exact iSup_congr fun i => (hom_apply_nonneg (hpos i) (f i) y).symm
      · obtain ⟨j, hj⟩ := not_forall.1 hpos
        have htop : (⨆ i, hom (f i) (l i, y)) = ⊤ :=
          top_le_iff.1 (le_iSup_of_le j (hom_apply_neg (not_le.1 hj) (f j) y).ge)
        rw [htop]
        exact le_top
  rwa [hkey] at hslice

/-- The linear map `(λ, y) ↦ (λ₁ + ⋯ + λₘ, y₁ + ⋯ + yₘ)` on `ℝᵐ × (ℝⁿ)ᵐ`, along which the last
operation of Theorem 5.8 — "adding in `λ` and `x`" — is an image. -/
noncomputable def sumPairLin (n m : ℕ) : ((Fin m → ℝ) × (Fin m → Rn n)) →ₗ[ℝ] ℝ × Rn n :=
  LinearMap.prod ((∑ i, LinearMap.proj i).comp (LinearMap.fst ℝ (Fin m → ℝ) (Fin m → Rn n)))
    ((∑ i, LinearMap.proj i).comp (LinearMap.snd ℝ (Fin m → ℝ) (Fin m → Rn n)))

@[simp] theorem sumPairLin_apply {n m : ℕ} (q : (Fin m → ℝ) × (Fin m → Rn n)) :
    sumPairLin n m q = (∑ i, q.1 i, ∑ i, q.2 i) := by
  simp [sumPairLin]

/-- The linear map `(λ, y) ↦ (λᵢ, yᵢ)`. -/
noncomputable def coordPairLin (n m : ℕ) (i : Fin m) :
    ((Fin m → ℝ) × (Fin m → Rn n)) →ₗ[ℝ] ℝ × Rn n :=
  LinearMap.prod ((LinearMap.proj i).comp (LinearMap.fst ℝ (Fin m → ℝ) (Fin m → Rn n)))
    ((LinearMap.proj i).comp (LinearMap.snd ℝ (Fin m → ℝ) (Fin m → Rn n)))

@[simp] theorem coordPairLin_apply {n m : ℕ} (i : Fin m) (q : (Fin m → ℝ) × (Fin m → Rn n)) :
    coordPairLin n m i q = (q.1 i, q.2 i) := rfl

/-- **Rockafellar, Theorem 5.8**, fourth function. For proper convex `f₁, …, fₘ` on `ℝⁿ`,

`k x = inf {max {λ₁ f₁ x₁, …, λₘ fₘ xₘ}}`,

the infimum being over all representations of `x` as a convex combination
`x = λ₁ x₁ + ⋯ + λₘ xₘ`, is convex. Rockafellar obtains it by "adding in `λ` and `x`".

Proved as an instance of Theorem 5.7 on `ℝᵐ × (ℝⁿ)ᵐ`: under the substitution `yᵢ = λᵢ xᵢ` the
displayed maximum becomes `maxᵢ hom fᵢ (λᵢ, yᵢ)` (`hom_apply_smul`), which is jointly convex,
and `k` is the slice at `∑ λᵢ = 1` of its image under `(λ, y) ↦ (∑ λᵢ, ∑ yᵢ)`. The substitution
is not injective at `λᵢ = 0`, and the two directions handle that asymmetrically: going down one
takes `xᵢ = λᵢ⁻¹ yᵢ`, which is legitimate because `λᵢ = 0` forces `yᵢ = 0` unless the whole
expression is `+∞`. -/
theorem theorem_5_8_k {n m : ℕ} {f : Fin m → Rn n → EReal} (hf : ∀ i, ConvexFn (f i))
    (hp : ∀ i, Proper (f i)) :
    ConvexFn fun x => ⨅ lp ∈ {lp : (Fin m → ℝ) × (Fin m → Rn n) |
        (∀ i, 0 ≤ lp.1 i) ∧ ∑ i, lp.1 i = 1 ∧ ∑ i, lp.1 i • lp.2 i = x},
      ⨆ i, (lp.1 i : EReal) * f i (lp.2 i) := by
  have hPsi : ConvexFn fun q : (Fin m → ℝ) × (Fin m → Rn n) => ⨆ i, hom (f i) (q.1 i, q.2 i) :=
    convexFn_iSup fun i => by
      have h := convexFn_compLin (coordPairLin n m i) (convexFn_hom (hf i))
      exact h
  have hslice := (convexFn_mapLin (sumPairLin n m) hPsi).slice_left 1
  have hkey : (fun x : Rn n => mapLin (sumPairLin n m)
        (fun q : (Fin m → ℝ) × (Fin m → Rn n) => ⨆ i, hom (f i) (q.1 i, q.2 i)) (1, x))
      = fun x => ⨅ lp ∈ {lp : (Fin m → ℝ) × (Fin m → Rn n) |
          (∀ i, 0 ≤ lp.1 i) ∧ ∑ i, lp.1 i = 1 ∧ ∑ i, lp.1 i • lp.2 i = x},
        ⨆ i, (lp.1 i : EReal) * f i (lp.2 i) := by
    funext x
    refine le_antisymm (le_iInf₂ fun lp hlp => ?_) (le_mapLin fun q hq => ?_)
    · refine (mapLin_le (x := (lp.1, fun i => lp.1 i • lp.2 i)) ?_).trans_eq ?_
      · rw [sumPairLin_apply, hlp.2.1, hlp.2.2]
      · exact iSup_congr fun i => hom_apply_smul (hp i).dom_nonempty (hlp.1 i) (lp.2 i)
    · obtain ⟨l, y⟩ := q
      rw [sumPairLin_apply, Prod.mk.injEq] at hq
      obtain ⟨hq₁, hq₂⟩ := hq
      by_cases hpos : ∀ i, 0 ≤ l i
      · by_cases hzero : ∀ i, l i = 0 → y i = 0
        · have hsmul : ∀ i, l i • (l i)⁻¹ • y i = y i := by
            intro i
            rcases eq_or_lt_of_le (hpos i) with h | h
            · rw [← h, zero_smul, hzero i h.symm]
            · rw [smul_smul, mul_inv_cancel₀ h.ne', one_smul]
          refine le_trans (iInf₂_le (l, fun i => (l i)⁻¹ • y i) ⟨hpos, hq₁, ?_⟩) (le_of_eq ?_)
          · refine iSup_congr fun i => ?_
            calc (l i : EReal) * f i ((l i)⁻¹ • y i)
                = hom (f i) (l i, l i • (l i)⁻¹ • y i) :=
                  (hom_apply_smul (hp i).dom_nonempty (hpos i) ((l i)⁻¹ • y i)).symm
              _ = hom (f i) (l i, y i) := by rw [hsmul i]
          · change (∑ i, l i • (l i)⁻¹ • y i) = x
            simp_rw [hsmul]
            exact hq₂
        · obtain ⟨j, hj⟩ := not_forall.1 hzero
          have hj0 : l j = 0 := by
            by_contra hc
            exact hj fun h0 => absurd h0 hc
          have hjy : y j ≠ 0 := fun h0 => hj fun _ => h0
          have hjtop : hom (f j) (l j, y j) = ⊤ := by
            rw [hj0, hom_apply_zero, smulRight_zero (hp j).dom_nonempty,
              indicatorFn_of_notMem (by simpa using hjy)]
          have htop : (⨆ i, hom (f i) (l i, y i)) = ⊤ :=
            top_le_iff.1 (le_iSup_of_le j hjtop.ge)
          rw [htop]
          exact le_top
      · obtain ⟨j, hj⟩ := not_forall.1 hpos
        have htop : (⨆ i, hom (f i) (l i, y i)) = ⊤ :=
          top_le_iff.1 (le_iSup_of_le j (hom_apply_neg (not_le.1 hj) (f j) (y j)).ge)
        rw [htop]
        exact le_top
  rwa [hkey] at hslice

end Rockafellar
