kind = 'module'
title = 'The normal form of a polyhedral convex function'
parent = 'Analysis.Convex.Polyhedral'
module = 'Tdaf.Analysis.Convex.Polyhedral.NormalForm'
namespace = 'Tdaf.ConvexAnalysis'

[[node]]
id = 'maxAffineFn'

[[node]]
id = 'polyhedralFn_maxAffineFn'

[[node]]
id = 'polyhedralFn_maxAffineFn_add_indicatorFn'

[[node]]
id = 'PolyhedralFn.exists_maxAffineFn_add_indicatorFn_dom'

[[node]]
id = 'polyhedralFn_iff_maxAffineFn_add_indicatorFn'
