kind = 'module'
title = 'Convergence of gradients'
parent = 'Analysis.Convex.Subgradient'
module = 'Tdaf.Analysis.Convex.Subgradient.GradientLimit'
namespace = 'Tdaf.ConvexAnalysis'

[[node]]
id = 'dist_le_of_subgradient_subset'

[[node]]
id = 'tendsto_of_hasGradientAt'

[[node]]
id = 'tendstoUniformlyOn_fderiv_toReal'
