kind = 'module'
title = 'Differentiability almost everywhere of a saddle-function'
parent = 'Analysis.Convex.Saddle'
module = 'Tdaf.Analysis.Convex.Saddle.Rademacher'
namespace = 'Tdaf.ConvexAnalysis'

[[node]]
id = 'ConcaveConvexOn.exists_lipschitzOnWith_ball'

[[node]]
id = 'ae_differentiableAt_of_concaveConvexOn'

[[node]]
id = 'measure_diff_differentiableAt_of_concaveConvexOn'

[[node]]
id = 'subset_closure_differentiableAt_of_concaveConvexOn'

[[node]]
id = 'continuousOn_saddleGradient'

[[node]]
id = 'tendsto_of_hasSaddleGradientAt'

[[node]]
id = 'tendstoUniformlyOn_saddleGradient'
