kind = 'module'
title = 'The lower and upper closures of a saddle-function'
parent = 'Analysis.Convex.Saddle'
module = 'Tdaf.Analysis.Convex.Saddle.Closure'
namespace = 'Tdaf.ConvexAnalysis'

[[node]]
id = 'lowerCl'

[[node]]
id = 'upperCl'

[[node]]
id = 'LowerClosedFn'

[[node]]
id = 'UpperClosedFn'

[[node]]
id = 'FullyClosedFn'

[[node]]
id = 'fullyClosedFn_iff'

[[node]]
id = 'saddleSwap'

[[node]]
id = 'saddleSwapOrderIso'

[[node]]
id = 'upperClosedFn_upperCl'

[[node]]
id = 'lowerClosedFn_lowerCl'
