/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Tdaf.Analysis.Convex.Polyhedral.Cone

/-!
# Polyhedral convex sets and Theorem 19.1

A convex set is **polyhedral** when it is the solution set of finitely many linear inequalities,
and **finitely generated** when it is `conv P + cone D` for finite sets of points `P` and
directions `D`. **Theorem 19.1** says the two agree in finite dimensions.

The proof is the cone case (`Polyhedral/Cone.lean`) plus homogenisation: a set `C ⊆ E` is the
level-one slice `{x | (1, x) ∈ K}` of a cone `K ⊆ ℝ × E`, the two descriptions of `C` correspond
to the two descriptions of `K`, and the correspondence is `slice_hull_union`.

## Main definitions

* `Polyhedral C` — `C` is cut out by finitely many inequalities `φ x ≤ b`.
* `FinitelyGenerated C` — `C = conv P + cone D` for finite `P`, `D`.
* `coneOver C hC` — the convex cone in `ℝ × E` generated by `{1} × C`, for convex `C`.

## Main results

* `slice_hull_union` — the level-one slice of the cone generated by `{1} × P ∪ {0} × D` is
  `conv P + cone D`. This is the whole of the homogenisation dictionary.
* `polyhedral_iff_finitelyGenerated` — **Theorem 19.1**.
* `Polyhedral.isClosed`, `Polyhedral.convex`, and the same for `FinitelyGenerated`.

## Implementation notes

`Polyhedral` is stated as `{x | ∀ q ∈ s, q.1 x ≤ q.2}` rather than as the equal
`⋂ q ∈ s, {x | q.1 x ≤ q.2}`, because that is the form every proof here manipulates;
`Polyhedral.eq_biInter` records the other. The empty set is both polyhedral (a system can be
inconsistent) and finitely generated (`conv ∅ = ∅`); Rockafellar's statement of Theorem 19.1
quietly assumes `C ≠ ∅` in places, but the slice picture handles it, since `(1, x)` never lies in
the cone generated by `{0} × D`.

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §19.
-/

open Set

open scoped Pointwise

namespace Tdaf.ConvexAnalysis

/-! ### Lifting a set to level `0` or level `1` of `ℝ × E` -/

section Lift

variable {E : Type*} [AddCommGroup E] [Module ℝ E]

/-- The copy of `S` at height `a` in `ℝ × E`. -/
def liftAt (a : ℝ) (S : Set E) : Set (ℝ × E) := (fun x => (a, x)) '' S

omit [AddCommGroup E] [Module ℝ E] in
@[simp]
theorem mem_liftAt {a : ℝ} {S : Set E} {p : ℝ × E} :
    p ∈ liftAt a S ↔ p.1 = a ∧ p.2 ∈ S := by
  constructor
  · rintro ⟨x, hx, rfl⟩
    exact ⟨rfl, hx⟩
  · rintro ⟨h1, h2⟩
    exact ⟨p.2, h2, by rw [← h1]⟩

/-- The height-`0` lift, as a map of `ℝ≥0`-modules. Building it by hand rather than restricting
scalars along `ℝ≥0 → ℝ` keeps `Submodule.map_span` applicable without an `IsScalarTower` detour. -/
def inrₙ : E →ₗ[{c : ℝ // 0 ≤ c}] ℝ × E where
  toFun x := (0, x)
  map_add' x y := by simp
  map_smul' a x := by
    refine Prod.ext ?_ ?_ <;> simp

@[simp] theorem inrₙ_apply (x : E) : (inrₙ x : ℝ × E) = (0, x) := rfl

/-- The height-`0` lift of a cone hull is the cone hull of the height-`0` lift. -/
theorem coe_hull_liftZero (D : Set E) :
    (PointedCone.hull ℝ (liftAt 0 D) : Set (ℝ × E)) = liftAt 0 (PointedCone.hull ℝ D : Set E) := by
  have himg : liftAt (0 : ℝ) D = (inrₙ : E →ₗ[{c : ℝ // 0 ≤ c}] ℝ × E) '' D := rfl
  rw [PointedCone.hull, himg, ← Submodule.map_span]
  rfl

end Lift

/-! ### The cone over a convex set -/

section ConeOver

variable {E : Type*} [AddCommGroup E] [Module ℝ E]

/-- The convex cone in `ℝ × E` generated by the height-one copy of a convex set `C`: the pairs
`(a, x)` with `a > 0` and `a⁻¹ • x ∈ C`, together with the origin. -/
def coneOver (C : Set E) (hC : Convex ℝ C) : PointedCone ℝ (ℝ × E) where
  carrier := {p : ℝ × E | (0 < p.1 ∧ p.1⁻¹ • p.2 ∈ C) ∨ p = 0}
  add_mem' {p q} hp hq := by
    rcases hp with ⟨hp1, hp2⟩ | rfl
    · rcases hq with ⟨hq1, hq2⟩ | rfl
      · have hsum : 0 < p.1 + q.1 := add_pos hp1 hq1
        have hc1 : p.1 / (p.1 + q.1) * p.1⁻¹ = (p.1 + q.1)⁻¹ := by field_simp
        have hc2 : q.1 / (p.1 + q.1) * q.1⁻¹ = (p.1 + q.1)⁻¹ := by field_simp
        have hmem := hC hp2 hq2 (a := p.1 / (p.1 + q.1)) (b := q.1 / (p.1 + q.1))
          (by positivity) (by positivity) (by field_simp)
        refine Or.inl ⟨by simpa using hsum, ?_⟩
        have hval : (p + q).1⁻¹ • (p + q).2
            = (p.1 / (p.1 + q.1)) • (p.1⁻¹ • p.2) + (q.1 / (p.1 + q.1)) • (q.1⁻¹ • q.2) := by
          rw [smul_smul, smul_smul, hc1, hc2, ← smul_add]
          rfl
        rw [hval]
        exact hmem
      · simpa using Or.inl ⟨hp1, hp2⟩
    · simpa using hq
  zero_mem' := Or.inr rfl
  smul_mem' a {p} hp := by
    rcases eq_or_lt_of_le a.2 with ha | ha
    · refine Or.inr ?_
      change ((a : ℝ) • p) = 0
      rw [← ha, zero_smul]
    · rcases hp with ⟨hp1, hp2⟩ | rfl
      · refine Or.inl ⟨?_, ?_⟩
        · change 0 < (a : ℝ) * p.1
          exact mul_pos ha hp1
        · change (((a : ℝ) * p.1)⁻¹ : ℝ) • ((a : ℝ) • p.2) ∈ C
          rw [smul_smul]
          have hco : ((a : ℝ) * p.1)⁻¹ * (a : ℝ) = p.1⁻¹ := by
            field_simp
          rw [hco]
          exact hp2
      · refine Or.inr ?_
        change ((a : ℝ) • (0 : ℝ × E)) = 0
        rw [smul_zero]

@[simp]
theorem mem_coneOver {C : Set E} {hC : Convex ℝ C} {p : ℝ × E} :
    p ∈ coneOver C hC ↔ (0 < p.1 ∧ p.1⁻¹ • p.2 ∈ C) ∨ p = 0 := Iff.rfl

/-- **The level-one slice of the cone generated by a height-one lift is the convex hull.** -/
theorem slice_hull_liftOne (P : Set E) :
    {x : E | ((1 : ℝ), x) ∈ (PointedCone.hull ℝ (liftAt 1 P) : Set (ℝ × E))}
      = convexHull ℝ P := by
  refine subset_antisymm (fun x hx => ?_) ?_
  · have hle : PointedCone.hull ℝ (liftAt 1 P)
        ≤ coneOver (convexHull ℝ P) (convex_convexHull ℝ P) :=
      Submodule.span_le.2 (by
        rintro p hp
        rw [mem_liftAt] at hp
        exact Or.inl ⟨by rw [hp.1]; norm_num, by
          rw [hp.1, inv_one, one_smul]
          exact subset_convexHull ℝ P hp.2⟩)
    have hmem := hle hx
    rcases hmem with ⟨-, h⟩ | h
    · simpa using h
    · exact absurd congr(($h).1) (by norm_num)
  · refine convexHull_min (fun x hx => ?_) ?_
    · exact PointedCone.subset_hull (mem_liftAt.2 ⟨rfl, hx⟩)
    · intro x hx y hy a b ha hb hab
      have hsplit : ((1 : ℝ), a • x + b • y) = a • ((1 : ℝ), x) + b • ((1 : ℝ), y) := by
        refine Prod.ext ?_ ?_
        · change (1 : ℝ) = a * 1 + b * 1
          rw [mul_one, mul_one, hab]
        · rfl
      change ((1 : ℝ), a • x + b • y) ∈ (PointedCone.hull ℝ (liftAt 1 P) : Set (ℝ × E))
      rw [hsplit]
      exact add_mem (Submodule.smul_mem _ (⟨a, ha⟩ : {c : ℝ // 0 ≤ c}) hx)
        (Submodule.smul_mem _ (⟨b, hb⟩ : {c : ℝ // 0 ≤ c}) hy)

/-- **The homogenisation dictionary.** The level-one slice of the convex cone generated by
`{1} × P ∪ {0} × D` is `conv P + cone D`. Both halves of Theorem 19.1 go through this identity. -/
theorem slice_hull_union (P D : Set E) :
    {x : E | ((1 : ℝ), x) ∈ (PointedCone.hull ℝ (liftAt 1 P ∪ liftAt 0 D) : Set (ℝ × E))}
      = convexHull ℝ P + (PointedCone.hull ℝ D : Set E) := by
  rw [PointedCone.hull, Submodule.span_union, Submodule.coe_sup]
  ext x
  constructor
  · rintro ⟨p, hp, q, hq, hpq⟩
    rw [← PointedCone.hull, coe_hull_liftZero, mem_liftAt] at hq
    have hq1 : q.1 = 0 := hq.1
    have hp1 : p.1 = 1 := by
      have := congr($(hpq).1)
      simp only [Prod.fst_add, hq1, add_zero] at this
      exact this
    have hx : p.2 + q.2 = x := congr($(hpq).2)
    refine ⟨p.2, ?_, q.2, hq.2, hx⟩
    rw [← slice_hull_liftOne P]
    change ((1 : ℝ), p.2) ∈ (PointedCone.hull ℝ (liftAt 1 P) : Set (ℝ × E))
    have hpe : p = ((1 : ℝ), p.2) := Prod.ext hp1 rfl
    rw [← hpe]
    exact hp
  · rintro ⟨y, hy, z, hz, rfl⟩
    rw [← slice_hull_liftOne P] at hy
    refine ⟨((1 : ℝ), y), hy, ((0 : ℝ), z), ?_, ?_⟩
    · rw [← PointedCone.hull, coe_hull_liftZero, mem_liftAt]
      exact ⟨rfl, hz⟩
    · refine Prod.ext ?_ rfl
      change (1 : ℝ) + 0 = 1
      norm_num

end ConeOver

/-! ### Polyhedral and finitely generated sets -/

section Defs

variable {E : Type*} [AddCommGroup E] [Module ℝ E]

/-- A **polyhedral convex set**: the solution set of finitely many linear inequalities. -/
def Polyhedral (C : Set E) : Prop :=
  ∃ s : Finset ((E →ₗ[ℝ] ℝ) × ℝ), C = {x | ∀ q ∈ s, q.1 x ≤ q.2}

/-- A **finitely generated convex set**: `conv P + cone D` for finite sets of points `P` and
directions `D`. -/
def FinitelyGenerated (C : Set E) : Prop :=
  ∃ P D : Finset E, C = convexHull ℝ (P : Set E) + (PointedCone.hull ℝ (D : Set E) : Set E)

/-- The `⋂` form of the definition. -/
theorem Polyhedral.eq_biInter {C : Set E} (hC : Polyhedral C) :
    ∃ s : Finset ((E →ₗ[ℝ] ℝ) × ℝ), C = ⋂ q ∈ s, {x | q.1 x ≤ q.2} := by
  obtain ⟨s, rfl⟩ := hC
  exact ⟨s, by ext x; simp⟩

theorem Polyhedral.convex {C : Set E} (hC : Polyhedral C) : Convex ℝ C := by
  obtain ⟨s, rfl⟩ := hC
  intro x hx y hy a b ha hb hab q hq
  have h₁ : q.1 x ≤ q.2 := hx q hq
  have h₂ : q.1 y ≤ q.2 := hy q hq
  have hval : q.1 (a • x + b • y) = a * q.1 x + b * q.1 y := by
    rw [map_add, map_smul, map_smul, smul_eq_mul, smul_eq_mul]
  have hq2 : a * q.2 + b * q.2 = q.2 := by rw [← add_mul, hab, one_mul]
  rw [hval]
  nlinarith [mul_nonneg ha (sub_nonneg.2 h₁), mul_nonneg hb (sub_nonneg.2 h₂), hq2]

theorem FinitelyGenerated.convex {C : Set E} (hC : FinitelyGenerated C) : Convex ℝ C := by
  obtain ⟨P, D, rfl⟩ := hC
  exact (convex_convexHull ℝ _).add ((PointedCone.hull ℝ (D : Set E) : ConvexCone ℝ E)).convex

end Defs

/-! ### Homogenisation of a polyhedral set -/

section Homogenize

variable {E : Type*} [AddCommGroup E] [Module ℝ E]

/-- The level-one slice of a polyhedral cone is a polyhedral set: substituting `1` for the
homogenising variable turns `Ψ (a, x) ≤ 0` into `ψ x ≤ b`. -/
theorem Polyhedral.of_slice {K : Set (ℝ × E)} (hK : PolyhedralCone K) :
    Polyhedral {x : E | ((1 : ℝ), x) ∈ K} := by
  classical
  obtain ⟨t, rfl⟩ := hK
  refine ⟨t.image fun Ψ => (Ψ ∘ₗ LinearMap.inr ℝ ℝ E, -Ψ ((1 : ℝ), (0 : E))), ?_⟩
  ext x
  simp only [Set.mem_ofPred_eq, Finset.mem_image]
  constructor
  · rintro h q ⟨Ψ, hΨ, rfl⟩
    have hΨx := h Ψ hΨ
    have hsplit : Ψ ((1 : ℝ), x) = Ψ ((1 : ℝ), (0 : E)) + Ψ ((0 : ℝ), x) := by
      rw [← map_add]
      congr 1
      refine Prod.ext ?_ ?_ <;> simp
    rw [hsplit] at hΨx
    change Ψ ((0 : ℝ), x) ≤ -Ψ ((1 : ℝ), (0 : E))
    linarith
  · intro h Ψ hΨ
    have hΨx := h _ ⟨Ψ, hΨ, rfl⟩
    have hval : (Ψ ∘ₗ LinearMap.inr ℝ ℝ E) x = Ψ ((0 : ℝ), x) := rfl
    rw [hval] at hΨx
    have hsplit : Ψ ((1 : ℝ), x) = Ψ ((1 : ℝ), (0 : E)) + Ψ ((0 : ℝ), x) := by
      rw [← map_add]
      congr 1
      refine Prod.ext ?_ ?_ <;> simp
    rw [hsplit]
    linarith

/-- A polyhedral set is the level-one slice of a polyhedral cone lying in the closed upper
half-space. The cone is Rockafellar's homogenisation: `a ≥ 0` together with `φ x ≤ b a` for each
inequality `φ x ≤ b` of the original system. -/
theorem Polyhedral.exists_polyhedralCone {C : Set E} (hC : Polyhedral C) :
    ∃ K : Set (ℝ × E), PolyhedralCone K ∧ K ⊆ {p : ℝ × E | 0 ≤ p.1} ∧
      {x : E | ((1 : ℝ), x) ∈ K} = C := by
  classical
  obtain ⟨s, rfl⟩ := hC
  refine ⟨{p : ℝ × E | ∀ Ψ ∈ insert (-LinearMap.fst ℝ ℝ E)
      (s.image fun q => q.1 ∘ₗ LinearMap.snd ℝ ℝ E - q.2 • LinearMap.fst ℝ ℝ E), Ψ p ≤ 0},
    ⟨_, rfl⟩, ?_, ?_⟩
  · intro p hp
    have h := hp _ (Finset.mem_insert_self _ _)
    have hval : (-LinearMap.fst ℝ ℝ E) p = -p.1 := rfl
    rw [hval] at h
    change (0 : ℝ) ≤ p.1
    linarith
  · ext x
    simp only [Set.mem_ofPred_eq, Finset.mem_insert, Finset.mem_image]
    constructor
    · intro h q hq
      have hΨ := h _ (Or.inr ⟨q, hq, rfl⟩)
      have hval : (q.1 ∘ₗ LinearMap.snd ℝ ℝ E - q.2 • LinearMap.fst ℝ ℝ E) ((1 : ℝ), x)
          = q.1 x - q.2 := by
        change q.1 x - q.2 * (1 : ℝ) = q.1 x - q.2
        rw [mul_one]
      rw [hval] at hΨ
      linarith
    · rintro h Ψ (rfl | ⟨q, hq, rfl⟩)
      · change -(1 : ℝ) ≤ 0
        norm_num
      · have hq' := h q hq
        change q.1 x - q.2 * (1 : ℝ) ≤ 0
        rw [mul_one]
        linarith

/-- Rewriting a finite generating set of a cone contained in the closed upper half-space as a
height-one part and a height-zero part: the generators with `p.1 > 0` are rescaled to height one,
those with `p.1 = 0` are directions. -/
theorem exists_liftOne_liftZero {g : Finset (ℝ × E)} (hg : ∀ p ∈ g, 0 ≤ p.1) :
    ∃ P D : Finset E,
      (PointedCone.hull ℝ (g : Set (ℝ × E)) : Set (ℝ × E))
        = (PointedCone.hull ℝ (liftAt 1 (P : Set E) ∪ liftAt 0 (D : Set E)) : Set (ℝ × E)) := by
  classical
  refine ⟨(g.filter fun p => 0 < p.1).image fun p => p.1⁻¹ • p.2,
    (g.filter fun p => p.1 = 0).image Prod.snd, ?_⟩
  have h₁ : (g : Set (ℝ × E)) ⊆
      (PointedCone.hull ℝ (liftAt 1 (((g.filter fun p => 0 < p.1).image
        fun p => p.1⁻¹ • p.2 : Finset E) : Set E)
        ∪ liftAt 0 (((g.filter fun p => p.1 = 0).image Prod.snd : Finset E) : Set E)) :
          Set (ℝ × E)) := by
    intro p hp
    rcases eq_or_lt_of_le (hg p (Finset.mem_coe.1 hp)) with hp1 | hp1
    · -- a direction
      have hmem : p ∈ liftAt 0
          (((g.filter fun p => p.1 = 0).image Prod.snd : Finset E) : Set E) := by
        refine mem_liftAt.2 ⟨hp1.symm, ?_⟩
        exact Finset.mem_coe.2 (Finset.mem_image.2
          ⟨p, Finset.mem_filter.2 ⟨Finset.mem_coe.1 hp, hp1.symm⟩, rfl⟩)
      exact PointedCone.subset_hull (Or.inr hmem)
    · -- a point, after rescaling
      have hgen : ((1 : ℝ), p.1⁻¹ • p.2) ∈ liftAt 1
          (((g.filter fun p => 0 < p.1).image fun p => p.1⁻¹ • p.2 : Finset E) : Set E) := by
        refine mem_liftAt.2 ⟨rfl, ?_⟩
        exact Finset.mem_coe.2 (Finset.mem_image.2
          ⟨p, Finset.mem_filter.2 ⟨Finset.mem_coe.1 hp, hp1⟩, rfl⟩)
      have hscale : p = (p.1 : ℝ) • ((1 : ℝ), p.1⁻¹ • p.2) := by
        refine Prod.ext ?_ ?_
        · change p.1 = p.1 * 1
          rw [mul_one]
        · change p.2 = p.1 • p.1⁻¹ • p.2
          rw [smul_smul, mul_inv_cancel₀ hp1.ne', one_smul]
      rw [hscale]
      exact Submodule.smul_mem _ (⟨p.1, hp1.le⟩ : {c : ℝ // 0 ≤ c})
        (PointedCone.subset_hull (Or.inl hgen))
  have h₂ : liftAt 1 (((g.filter fun p => 0 < p.1).image fun p => p.1⁻¹ • p.2 : Finset E) : Set E)
      ∪ liftAt 0 (((g.filter fun p => p.1 = 0).image Prod.snd : Finset E) : Set E)
      ⊆ (PointedCone.hull ℝ (g : Set (ℝ × E)) : Set (ℝ × E)) := by
    rintro r (hr | hr) <;> rw [mem_liftAt] at hr
    · obtain ⟨hr1, hr2⟩ := hr
      obtain ⟨p, hp, hpr⟩ := Finset.mem_image.1 (Finset.mem_coe.1 hr2)
      obtain ⟨hpg, hp1⟩ := Finset.mem_filter.1 hp
      have hval : r = (p.1⁻¹ : ℝ) • p := by
        refine Prod.ext ?_ ?_
        · rw [hr1]
          change (1 : ℝ) = p.1⁻¹ * p.1
          rw [inv_mul_cancel₀ hp1.ne']
        · exact hpr.symm
      rw [hval]
      exact Submodule.smul_mem _ (⟨p.1⁻¹, (inv_pos.2 hp1).le⟩ : {c : ℝ // 0 ≤ c})
        (PointedCone.subset_hull (Finset.mem_coe.2 hpg))
    · obtain ⟨hr1, hr2⟩ := hr
      obtain ⟨p, hp, hpr⟩ := Finset.mem_image.1 (Finset.mem_coe.1 hr2)
      obtain ⟨hpg, hp1⟩ := Finset.mem_filter.1 hp
      have hval : r = p := by
        refine Prod.ext ?_ ?_
        · rw [hr1, hp1]
        · exact hpr.symm
      rw [hval]
      exact PointedCone.subset_hull (Finset.mem_coe.2 hpg)
  exact subset_antisymm (Submodule.span_le.2 h₁) (Submodule.span_le.2 h₂)

end Homogenize

/-! ### Theorem 19.1 -/

section Main

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]

/-- **Weyl's half of Theorem 19.1**: a finitely generated convex set is polyhedral. -/
theorem FinitelyGenerated.polyhedral {C : Set E} (hC : FinitelyGenerated C) : Polyhedral C := by
  classical
  obtain ⟨P, D, rfl⟩ := hC
  have hcone : PolyhedralCone
      (PointedCone.hull ℝ (liftAt 1 (P : Set E) ∪ liftAt 0 (D : Set E)) : Set (ℝ × E)) := by
    refine FinitelyGeneratedCone.polyhedralCone ⟨P.image (fun x => ((1 : ℝ), x))
      ∪ D.image (fun x => ((0 : ℝ), x)), ?_⟩
    congr 1
    ext p
    simp [liftAt]
  have h := Polyhedral.of_slice hcone
  rwa [slice_hull_union] at h

/-- **Minkowski's half of Theorem 19.1**: a polyhedral convex set is finitely generated. -/
theorem Polyhedral.finitelyGenerated {C : Set E} (hC : Polyhedral C) : FinitelyGenerated C := by
  obtain ⟨K, hKpoly, hKupper, hKslice⟩ := hC.exists_polyhedralCone
  obtain ⟨g, hg⟩ := hKpoly.finitelyGeneratedCone
  have hgnonneg : ∀ p ∈ g, 0 ≤ p.1 := by
    intro p hp
    exact hKupper (hg ▸ PointedCone.subset_hull (Finset.mem_coe.2 hp))
  obtain ⟨P, D, hPD⟩ := exists_liftOne_liftZero hgnonneg
  refine ⟨P, D, ?_⟩
  rw [← hKslice, hg, hPD, slice_hull_union]

/-- **Rockafellar, Theorem 19.1.** In a finite-dimensional space a convex set is polyhedral if and
only if it is finitely generated. -/
theorem polyhedral_iff_finitelyGenerated {C : Set E} :
    Polyhedral C ↔ FinitelyGenerated C :=
  ⟨Polyhedral.finitelyGenerated, FinitelyGenerated.polyhedral⟩

/-- A polyhedral set is closed. -/
theorem Polyhedral.isClosed {C : Set E} (hC : Polyhedral C) : IsClosed C := by
  obtain ⟨s, rfl⟩ := hC
  have hEq : {x : E | ∀ q ∈ s, q.1 x ≤ q.2} = ⋂ q ∈ s, {x : E | q.1 x ≤ q.2} := by
    ext x; simp
  rw [hEq]
  exact isClosed_iInter fun q => isClosed_iInter fun _ =>
    isClosed_le (LinearMap.continuous_of_finiteDimensional q.1) continuous_const

/-- **Corollary 19.1.2 (part).** A finitely generated convex set is closed; in particular the sum
of a polytope and a finitely generated cone is closed. -/
theorem FinitelyGenerated.isClosed {C : Set E} (hC : FinitelyGenerated C) : IsClosed C :=
  hC.polyhedral.isClosed

/-- **Corollary 19.1.1.** The convex hull of a finite set — a polytope — is polyhedral. -/
theorem polyhedral_convexHull_finset (P : Finset E) : Polyhedral (convexHull ℝ (P : Set E)) := by
  refine FinitelyGenerated.polyhedral ⟨P, ∅, ?_⟩
  have hbot : (PointedCone.hull ℝ ((∅ : Finset E) : Set E) : Set E) = {0} := by
    rw [Finset.coe_empty, PointedCone.hull, Submodule.span_empty]
    rfl
  rw [hbot]
  ext x
  constructor
  · intro hx
    exact ⟨x, hx, 0, rfl, add_zero x⟩
  · rintro ⟨y, hy, z, hz, rfl⟩
    have hz0 : z = 0 := hz
    simp only [hz0, add_zero]
    exact hy

end Main

end Tdaf.ConvexAnalysis
