/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Tdaf.Analysis.Convex.Polyhedral.Function
import Tdaf.Analysis.Convex.Recession.ConeHull

/-!
# Corollary 19.1.2 for functions

**Rockafellar, Corollary 19.1.2** says that a convex set generated by finitely many points and
directions is polyhedral. Its function-level form, which §21 consumes, says that the *positively
homogeneous convex function generated by finitely many points* is polyhedral.

The generated function is `posHomGen f`, whose epigraph is *not* the convex cone generated by
`epi f`: that cone is not upward closed at the origin. `posHomGen (δ(· | {a}) + α)`, for instance,
is generated by the ray through `(a, -α)`, and its epigraph has to contain the whole vertical ray
above the origin as well. This is exactly why Rockafellar's generator list for `epi k₀` carries the
extra point `(0, 1)`, and it is what `epi_posHomGen_of_epi_eq` records.

## Main results

* `epi_posHomGen_of_epi_eq` — if `epi f` is `conv P` plus the vertical ray, for a finite `P`, then
  `epi (posHomGen f)` is the convex cone generated by `P` together with `(0, 1)`.
* `polyhedralFn_posHomGen_of_epi_eq` — **Corollary 19.1.2 for functions**: that function is
  polyhedral.

## Design notes

**The hypothesis is `epi f = conv P + cone {(0,1)}`, not "`f` is polyhedral".** A polyhedral `f`
has `epi f = conv P + cone D` with a general direction set `D`, and then
`epi (posHomGen f) = cone (P ∪ D ∪ {(0,1)})` is **false**: for `f x = |x| + 1` on `ℝ` the point
`(1, 1)` lies in `epi (posHomGen f) = epi |·|` but in no finite non-negative combination of
`epi f ∪ {(0,1)}`, since every such combination has second coordinate at least
`|first coordinate| + λ` with `λ > 0`. A closure is needed in general, and the direction set has to
be exactly the vertical ray for the closure to be free. That is the case §21 uses: the conjugate of
an affine function is a point indicator, whose epigraph is a single translated vertical ray.

**Both inclusions avoid positive homogeneity of `ofEpi K`.** The hard direction is
`epi_ofEpi_subset_of_isEpiLike` — `epi (ofEpi F) ⊆ G` whenever `F ⊆ G` and `G` is an epigraph —
applied to `F = cone (epi f)`, which is the definition of `posHomGen f`. Nothing has to be checked
about the function `ofEpi K` itself.

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §19 (Corollary 19.1.2)
  and §5 (the paragraph after Theorem 5.3).
-/

open Set Pointwise

namespace Tdaf.ConvexAnalysis

section Homogeneous

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]

/-- The **vertical ray** `{0} × [0, ∞)` of `E × ℝ`, as a pointed cone: the cone generated by
`(0, 1)`. Adding it to a set is what makes the set upward closed. -/
noncomputable def verticalRay (E : Type*) [AddCommGroup E] [Module ℝ E] :
    PointedCone ℝ (E × ℝ) :=
  PointedCone.hull ℝ ({((0 : E), (1 : ℝ))} : Set (E × ℝ))

omit [FiniteDimensional ℝ E] in
/-- Membership in the vertical ray: its points are `(0, c)` with `c ≥ 0`. -/
theorem mem_verticalRay_iff {p : E × ℝ} :
    p ∈ verticalRay E ↔ ∃ c : ℝ, 0 ≤ c ∧ p = ((0 : E), c) := by
  rw [verticalRay, PointedCone.hull, Submodule.mem_span_singleton]
  constructor
  · rintro ⟨c, rfl⟩
    refine ⟨(c : ℝ), c.2, ?_⟩
    have hval : (c : ℝ) • (((0 : E), (1 : ℝ)) : E × ℝ) = ((0 : E), (c : ℝ)) := by
      rw [Prod.smul_mk, smul_zero, smul_eq_mul, mul_one]
    exact hval
  · rintro ⟨c, hc, rfl⟩
    refine ⟨⟨c, hc⟩, ?_⟩
    have hval : c • (((0 : E), (1 : ℝ)) : E × ℝ) = ((0 : E), c) := by
      rw [Prod.smul_mk, smul_zero, smul_eq_mul, mul_one]
    exact hval

/-- **The epigraph of the positively homogeneous convex function generated by finitely many
points.** If `epi f` is the convex hull of a finite set `P` plus the vertical ray, then
`epi (posHomGen f)` is the convex cone generated by `P` together with `(0, 1)`.

The extra generator `(0, 1)` is not decoration: the convex cone generated by `epi f` alone meets
the vertical axis in `{0}` only, whereas an epigraph must contain the whole ray above any of its
points. -/
theorem epi_posHomGen_of_epi_eq {f : E → EReal} {P : Finset (E × ℝ)}
    (hepi : epi f = convexHull ℝ (P : Set (E × ℝ)) + (verticalRay E : Set (E × ℝ))) :
    epi (posHomGen f)
      = (PointedCone.hull ℝ (insert ((0 : E), (1 : ℝ)) (P : Set (E × ℝ))) : Set (E × ℝ)) := by
  classical
  set Kc : PointedCone ℝ (E × ℝ) :=
    PointedCone.hull ℝ (insert ((0 : E), (1 : ℝ)) (P : Set (E × ℝ))) with hKc
  have hvert : ((0 : E), (1 : ℝ)) ∈ Kc := PointedCone.subset_hull (Set.mem_insert _ _)
  have hPsub : (P : Set (E × ℝ)) ⊆ (Kc : Set (E × ℝ)) := fun p hp =>
    PointedCone.subset_hull (Set.mem_insert_of_mem _ hp)
  -- `Kc` is closed and upward closed, hence an epigraph.
  have hKcl : IsClosed (Kc : Set (E × ℝ)) :=
    FinitelyGeneratedCone.isClosed ⟨insert ((0 : E), (1 : ℝ)) P, by rw [hKc, Finset.coe_insert]⟩
  have hKmono : ∀ (x : E) (μ ν : ℝ), (x, μ) ∈ (Kc : Set (E × ℝ)) → μ ≤ ν →
      (x, ν) ∈ (Kc : Set (E × ℝ)) := by
    intro x μ ν hmem hle
    have hsmul : (((0 : E), ν - μ) : E × ℝ) ∈ Kc := by
      have h := Submodule.smul_mem Kc (⟨ν - μ, by linarith⟩ : {c : ℝ // 0 ≤ c}) hvert
      simpa using h
    have heq : ((x, μ) : E × ℝ) + ((0 : E), ν - μ) = (x, ν) := by simp
    rw [← heq]
    exact Submodule.add_mem Kc hmem hsmul
  have hKepi : IsEpiLike (Kc : Set (E × ℝ)) := IsEpiLike.of_isClosed hKmono hKcl
  -- `epi f` sits inside `Kc`, hence so does the cone it generates.
  have hepiK : epi f ⊆ (Kc : Set (E × ℝ)) := by
    rw [hepi]
    rintro _ ⟨u, hu, v, hv, rfl⟩
    refine Submodule.add_mem Kc ?_ ?_
    · exact convexHull_min hPsub ((Kc : ConvexCone ℝ (E × ℝ))).convex hu
    · obtain ⟨c, hc, rfl⟩ := mem_verticalRay_iff.1 hv
      have h := Submodule.smul_mem Kc (⟨c, hc⟩ : {d : ℝ // 0 ≤ d}) hvert
      simpa using h
  refine Set.Subset.antisymm
    (epi_ofEpi_subset_of_isEpiLike (Submodule.span_le.2 hepiK) hKepi) fun p hp => ?_
  -- Conversely every generator of `Kc` lies in `epi (posHomGen f)`, which is a cone plus verticals.
  rw [hKc, ← Set.singleton_union, coe_hull_union] at hp
  obtain ⟨v, hv, u, hu, rfl⟩ := hp
  obtain ⟨c, hc, rfl⟩ := mem_verticalRay_iff.1 hv
  have hPepi : (P : Set (E × ℝ)) ⊆ epi f := by
    intro p hp
    rw [hepi]
    exact ⟨p, subset_convexHull ℝ _ hp, 0, (verticalRay E).zero_mem, add_zero p⟩
  have huepi : u ∈ epi (posHomGen f) :=
    coe_hull_epi_subset_epi_posHomGen f (Submodule.span_mono hPepi hu)
  rw [mem_epi] at huepi ⊢
  have hfst : ((((0 : E), c) : E × ℝ) + u).1 = u.1 := by simp
  have hsnd : ((((0 : E), c) : E × ℝ) + u).2 = c + u.2 := by simp
  rw [hfst, hsnd]
  refine le_trans huepi ?_
  exact_mod_cast le_add_of_nonneg_left hc

/-- **Rockafellar, Corollary 19.1.2, for functions**: the positively homogeneous convex function
generated by finitely many points is polyhedral. -/
theorem polyhedralFn_posHomGen_of_epi_eq {f : E → EReal} {P : Finset (E × ℝ)}
    (hepi : epi f = convexHull ℝ (P : Set (E × ℝ)) + (verticalRay E : Set (E × ℝ))) :
    PolyhedralFn (posHomGen f) := by
  classical
  have hfg : FinitelyGenerated (epi (posHomGen f)) := by
    refine ⟨{0}, insert ((0 : E), (1 : ℝ)) P, ?_⟩
    rw [epi_posHomGen_of_epi_eq hepi, Finset.coe_insert, Finset.coe_singleton,
      convexHull_singleton]
    ext q
    constructor
    · exact fun hq => ⟨0, rfl, q, hq, zero_add q⟩
    · rintro ⟨a, ha, b, hb, rfl⟩
      rw [Set.mem_singleton_iff] at ha
      subst ha
      simpa using hb
  exact hfg.polyhedral

end Homogeneous

end Tdaf.ConvexAnalysis
