import Tdaf.Analysis.Convex.Polyhedral.Defs
import Tdaf.Analysis.Convex.Recession.Cone
import Tdaf.Analysis.Convex.Separation

/-!
# The polyhedral calculus

The operations that preserve polyhedrality, and the recession cone of a polyhedral set.

Each operation is proved on the side of the description that makes it trivial. Intersections and
preimages are trivial for the *inequality* description — concatenate the systems, or compose each
functional with the map — and images and sums are trivial for the *generator* description — push
the generators forward, or add the point sets and unite the direction sets. The Minkowski–Weyl
theorem is what lets each proof pick its side.

## Main results

* `Polyhedral.inter`, `polyhedral_biInter`, `polyhedral_iInter`, `Polyhedral.comap` — the
  inequality side; no finite-dimensionality is needed. The indexed intersections are what a system
  of constraints `fᵢ x ≤ 0` needs.
* `Polyhedral.image`, `Polyhedral.add` — images and sums, through the generator description
  (Theorem 19.3 in [^1]).
* `recessionCone_polyhedral_system`, `Polyhedral.polyhedralCone_recessionCone` — dropping the
  right-hand sides of the system gives the recession cone.
* `separatesStrongly_of_polyhedral` — two disjoint polyhedral sets are strongly separated, with no
  closedness or compactness hypothesis to check.
* `finitelyGeneratedCone_hull_of_zero_mem` — the convex cone generated by a polyhedral set that
  contains the origin is finitely generated, with no closure taken.
* `finitelyGenerated_closure_convexHull_union`, `finitelyGenerated_closure_convexHull_biUnion` and
  `finitelyGeneratedCone_closure_coe_hull` — taking the closed convex hull of a union, or the
  closed convex cone generated by a set, adds exactly the recession cones
  (Theorems 19.6 and 19.7 in [^1]).

## References

[^1]: R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §19.
-/

open Set

open scoped Pointwise

namespace Tdaf.ConvexAnalysis

/-! ### The inequality side: intersections and preimages -/

section HSide

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]

theorem polyhedral_univ : Polyhedral (Set.univ : Set E) :=
  ⟨∅, by ext x; simp⟩

theorem polyhedral_halfSpace (φ : E →ₗ[ℝ] ℝ) (b : ℝ) : Polyhedral {x : E | φ x ≤ b} :=
  ⟨{(φ, b)}, by ext x; simp⟩

/-- An intersection of two polyhedral sets is polyhedral — concatenate the two systems.

`polyhedral_biInter` and `polyhedral_iInter` below are the indexed forms. -/
theorem Polyhedral.inter {C D : Set E} (hC : Polyhedral C) (hD : Polyhedral D) :
    Polyhedral (C ∩ D) := by
  classical
  obtain ⟨s, rfl⟩ := hC
  obtain ⟨t, rfl⟩ := hD
  refine ⟨s ∪ t, ?_⟩
  ext x
  simp only [Set.mem_inter_iff, Set.mem_ofPred_eq, Finset.mem_union]
  constructor
  · rintro ⟨h₁, h₂⟩ q (hq | hq)
    · exact h₁ q hq
    · exact h₂ q hq
  · intro h
    exact ⟨fun q hq => h q (Or.inl hq), fun q hq => h q (Or.inr hq)⟩

/-- **The intersection of finitely many polyhedral sets is polyhedral** (book, line 6817,
unnumbered): the `Finset`-indexed form, by induction on the index set from `polyhedral_univ` and
`Polyhedral.inter`.

Stated over a bare index type: neither the index nor the ambient space needs any structure beyond
the module structure `Polyhedral` itself is stated over. -/
theorem polyhedral_biInter {ι : Type*} {S : ι → Set E} (hS : ∀ i, Polyhedral (S i))
    (s : Finset ι) : Polyhedral (⋂ i ∈ s, S i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simpa using polyhedral_univ
  | insert i t _ ih =>
      rw [Finset.set_biInter_insert]
      exact Polyhedral.inter (hS i) ih

/-- The same over a finite index *type*, which is the shape a family of constraints arrives in. -/
theorem polyhedral_iInter {ι : Type*} [Finite ι] {S : ι → Set E} (hS : ∀ i, Polyhedral (S i)) :
    Polyhedral (⋂ i, S i) := by
  obtain ⟨hι⟩ := nonempty_fintype ι
  have h : (⋂ i, S i) = ⋂ i ∈ (Finset.univ : Finset ι), S i := by simp
  rw [h]
  exact polyhedral_biInter hS Finset.univ

/-- The preimage of a polyhedral set under a linear map is polyhedral — compose each functional
with the map. -/
theorem Polyhedral.comap {C : Set F} (hC : Polyhedral C) (A : E →ₗ[ℝ] F) :
    Polyhedral (A ⁻¹' C) := by
  classical
  obtain ⟨s, rfl⟩ := hC
  refine ⟨s.image fun q => (q.1 ∘ₗ A, q.2), ?_⟩
  ext x
  simp only [Set.mem_preimage, Set.mem_ofPred_eq, Finset.mem_image]
  constructor
  · rintro h q ⟨q', hq', rfl⟩
    exact h q' hq'
  · intro h q hq
    exact h _ ⟨q, hq, rfl⟩

/-- The preimage of a polyhedral set under an *affine* map is polyhedral. The translation is
absorbed into the right-hand sides. -/
theorem Polyhedral.comap_affine {C : Set F} (hC : Polyhedral C) (A : E →ₗ[ℝ] F) (v : F) :
    Polyhedral ((fun x => A x + v) ⁻¹' C) := by
  classical
  obtain ⟨s, rfl⟩ := hC
  refine ⟨s.image fun q => (q.1 ∘ₗ A, q.2 - q.1 v), ?_⟩
  ext x
  simp only [Set.mem_preimage, Set.mem_ofPred_eq, Finset.mem_image]
  constructor
  · rintro h q ⟨q', hq', rfl⟩
    have hq := h q' hq'
    rw [map_add] at hq
    change q'.1 (A x) ≤ q'.2 - q'.1 v
    linarith
  · intro h q hq
    have hq' := h _ ⟨q, hq, rfl⟩
    have hval : (q.1 ∘ₗ A) x = q.1 (A x) := rfl
    rw [hval] at hq'
    rw [map_add]
    linarith

/-- A polyhedral cone is a polyhedral set: its system has zero right-hand sides. -/
theorem PolyhedralCone.polyhedral {K : Set E} (hK : PolyhedralCone K) : Polyhedral K := by
  classical
  obtain ⟨s, rfl⟩ := hK
  refine ⟨s.image fun φ => (φ, (0 : ℝ)), ?_⟩
  ext x
  simp only [Set.mem_ofPred_eq, Finset.mem_image]
  constructor
  · rintro h q ⟨φ, hφ, rfl⟩
    exact h φ hφ
  · intro h φ hφ
    exact h _ ⟨φ, hφ, rfl⟩

/-- A product of polyhedral sets is polyhedral. -/
theorem Polyhedral.prod {C : Set E} {D : Set F} (hC : Polyhedral C) (hD : Polyhedral D) :
    Polyhedral (C ×ˢ D) := by
  have hEq : C ×ˢ D = (LinearMap.fst ℝ E F) ⁻¹' C ∩ (LinearMap.snd ℝ E F) ⁻¹' D := by
    ext p
    simp [Set.mem_prod]
  rw [hEq]
  exact Polyhedral.inter (hC.comap _) (hD.comap _)

/-- In finite dimensions a linear subspace is a polyhedral convex set: it is the preimage of the
origin of `E ⧸ S` under `S.mkQ`, and the origin of a finite-dimensional space is a polyhedral
cone. No norm is involved — `polyhedralCone_zero` needs only a finite basis — which matters,
because `E ⧸ S` carries no norm unless `S` is known to be closed. -/
theorem polyhedral_coe_submodule [FiniteDimensional ℝ E] (S : Submodule ℝ E) :
    Polyhedral (S : Set E) := by
  have h : Polyhedral ((S.mkQ : E →ₗ[ℝ] E ⧸ S) ⁻¹' ({0} : Set (E ⧸ S))) :=
    Polyhedral.comap (PolyhedralCone.polyhedral polyhedralCone_zero) S.mkQ
  have hset : (S.mkQ : E →ₗ[ℝ] E ⧸ S) ⁻¹' ({0} : Set (E ⧸ S)) = (S : Set E) := by
    ext x
    simp [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]
  rwa [hset] at h

/-- In finite dimensions a nonempty affine subspace is a polyhedral convex set: translate it to
its direction. This is what makes `indicatorFn (affineSpan ℝ (dom g))` a polyhedral convex
function, the device the polyhedral refinement of the exact-sum theorem runs on. -/
theorem polyhedral_coe_affineSubspace [FiniteDimensional ℝ E] {M : AffineSubspace ℝ E} {x₀ : E}
    (hx₀ : x₀ ∈ M) : Polyhedral (M : Set E) := by
  have h := Polyhedral.comap_affine (polyhedral_coe_submodule M.direction)
    (LinearMap.id : E →ₗ[ℝ] E) (-x₀)
  have hset : ((fun x => (LinearMap.id : E →ₗ[ℝ] E) x + (-x₀)) ⁻¹' (M.direction : Set E))
      = (M : Set E) := by
    ext x
    have hiff := AffineSubspace.vsub_right_mem_direction_iff_mem hx₀ x
    rw [vsub_eq_sub] at hiff
    rw [Set.mem_preimage, LinearMap.id_apply, ← sub_eq_add_neg]
    exact hiff
  rwa [hset] at h

end HSide

/-! ### The generator side: images and sums -/

section VSide

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]

/-- An `ℝ`-linear map read as a map of pointed cones. Constructed by hand rather than by
`LinearMap.restrictScalars`; see the note on `inrₙ`. -/
def toNNLinear (A : E →ₗ[ℝ] F) : E →ₗ[{c : ℝ // 0 ≤ c}] F where
  toFun := A
  map_add' := A.map_add
  map_smul' a x := A.map_smul (a : ℝ) x

@[simp] theorem toNNLinear_apply (A : E →ₗ[ℝ] F) (x : E) : toNNLinear A x = A x := rfl

/-- A linear map carries the cone hull of a set to the cone hull of its image. -/
theorem image_coe_hull (A : E →ₗ[ℝ] F) (S : Set E) :
    A '' (PointedCone.hull ℝ S : Set E) = (PointedCone.hull ℝ (A '' S) : Set F) := by
  have hmap : (Submodule.map (toNNLinear A) (PointedCone.hull ℝ S) : Set F)
      = (PointedCone.hull ℝ (A '' S) : Set F) := by
    rw [PointedCone.hull, Submodule.map_span]
    rfl
  rw [← hmap, Submodule.map_coe]
  rfl

/-- The cone hull of a linear subspace is the subspace itself. -/
theorem coe_hull_coe_submodule (S : Submodule ℝ E) :
    (PointedCone.hull ℝ (S : Set E) : Set E) = (S : Set E) := by
  refine subset_antisymm (fun x hx => ?_) (fun x hx => PointedCone.subset_hull hx)
  induction hx using Submodule.span_induction with
  | mem y hy => exact hy
  | zero => exact S.zero_mem
  | add y z _ _ hy hz => exact S.add_mem hy hz
  | smul c y _ hy => exact S.smul_mem (c : ℝ) hy

/-- The cone hull of a union is the sum of the cone hulls. -/
theorem coe_hull_union (S T : Set E) :
    (PointedCone.hull ℝ (S ∪ T) : Set E)
      = (PointedCone.hull ℝ S : Set E) + (PointedCone.hull ℝ T : Set E) := by
  rw [PointedCone.hull, Submodule.span_union, Submodule.coe_sup]

/-- The cone hull of a finite union is the pointwise sum of the cone hulls: `coe_hull_union`
iterated over a `Finset` of indices. -/
theorem coe_hull_biUnion {ι : Type*} (s : Finset ι) (D : ι → Set E) :
    (PointedCone.hull ℝ (⋃ i ∈ s, D i) : Set E)
      = ∑ i ∈ s, (PointedCone.hull ℝ (D i) : Set E) := by
  classical
  induction s using Finset.cons_induction with
  | empty =>
      have hu : (⋃ i ∈ (∅ : Finset ι), D i) = (∅ : Set E) := by simp
      rw [hu, Finset.sum_empty, PointedCone.hull, Submodule.span_empty]
      rfl
  | cons a s ha ih =>
      have hu : (⋃ i ∈ Finset.cons a s ha, D i) = D a ∪ ⋃ i ∈ s, D i := by
        ext x; simp
      rw [hu, coe_hull_union, Finset.sum_cons, ih]

omit [Module ℝ E] in
/-- A pointwise `Finset` sum of subsets of a set that contains the origin and is closed under
addition lands in that set. The two hypotheses are exactly what a cone supplies. -/
theorem finset_sum_subset_of_forall_subset {ι : Type*} {s : Finset ι} {A : ι → Set E}
    {T : Set E} (h0 : (0 : E) ∈ T) (hadd : ∀ x ∈ T, ∀ y ∈ T, x + y ∈ T)
    (h : ∀ i ∈ s, A i ⊆ T) : ∑ i ∈ s, A i ⊆ T := by
  classical
  induction s using Finset.cons_induction with
  | empty =>
      intro x hx
      rw [Finset.sum_empty] at hx
      have hx0 : x = 0 := hx
      rw [hx0]
      exact h0
  | cons a s ha ih =>
      intro x hx
      rw [Finset.sum_cons] at hx
      obtain ⟨u, hu, v, hv, huv⟩ := hx
      have huv' : u + v = x := huv
      rw [← huv']
      exact hadd _ (h a (Finset.mem_cons_self a s) hu) _
        (ih (fun i hi => h i (Finset.mem_cons_of_mem hi)) hv)

/-- The convex cone generated by a *convex* set containing the origin is simply the union of its
nonnegative multiples: convexity merges any two of them into one, so no sums are left over.

This is the description of `PointedCone.hull` that lets a hypothesis about the generating set be
transported to the whole cone, provided the property in question is invariant under positive
scaling. -/
theorem coe_hull_of_convex_zero_mem {S : Set E} (hS : Convex ℝ S) (h0 : (0 : E) ∈ S) :
    (PointedCone.hull ℝ S : Set E) = {y | ∃ t : ℝ, 0 ≤ t ∧ y ∈ t • S} := by
  refine subset_antisymm (fun y hy => ?_) (fun y hy => ?_)
  · induction hy using Submodule.span_induction with
    | mem z hz => exact ⟨1, zero_le_one, z, hz, one_smul ℝ z⟩
    | zero => exact ⟨1, zero_le_one, 0, h0, smul_zero 1⟩
    | add y z _ _ ihy ihz =>
        obtain ⟨t₁, ht₁, a, ha, hay⟩ := ihy
        obtain ⟨t₂, ht₂, b, hb, hbz⟩ := ihz
        have hay' : t₁ • a = y := hay
        have hbz' : t₂ • b = z := hbz
        rcases eq_or_lt_of_le (by linarith : (0 : ℝ) ≤ t₁ + t₂) with hsum | hsum
        · have h1 : t₁ = 0 := by linarith
          have h2 : t₂ = 0 := by linarith
          refine ⟨1, zero_le_one, 0, h0, ?_⟩
          have h : (1 : ℝ) • (0 : E) = y + z := by
            rw [smul_zero, ← hay', ← hbz', h1, h2, zero_smul, zero_smul, add_zero]
          exact h
        · have hne : t₁ + t₂ ≠ 0 := ne_of_gt hsum
          refine ⟨t₁ + t₂, le_of_lt hsum,
            (t₁ / (t₁ + t₂)) • a + (t₂ / (t₁ + t₂)) • b, ?_, ?_⟩
          · exact hS ha hb (by positivity) (by positivity) (by field_simp)
          · have e₁ : (t₁ + t₂) * (t₁ / (t₁ + t₂)) = t₁ := by field_simp
            have e₂ : (t₁ + t₂) * (t₂ / (t₁ + t₂)) = t₂ := by field_simp
            have h : (t₁ + t₂) • ((t₁ / (t₁ + t₂)) • a + (t₂ / (t₁ + t₂)) • b) = y + z := by
              rw [smul_add, smul_smul, smul_smul, e₁, e₂, hay', hbz']
            exact h
    | smul c y _ ih =>
        obtain ⟨t, ht, a, ha, hay⟩ := ih
        have hay' : t • a = y := hay
        refine ⟨(c : ℝ) * t, mul_nonneg c.2 ht, a, ha, ?_⟩
        have h : ((c : ℝ) * t) • a = (c : ℝ) • y := by rw [← hay', smul_smul]
        exact h
  · obtain ⟨t, ht, a, ha, hay⟩ := hy
    have hay' : t • a = y := hay
    have h : t • a ∈ (PointedCone.hull ℝ S : Set E) :=
      Submodule.smul_mem _ (⟨t, ht⟩ : {r : ℝ // 0 ≤ r}) (PointedCone.subset_hull ha)
    rwa [hay'] at h

/-- The point generators of a finitely generated set lie in the set. -/
theorem coe_subset_of_finitelyGenerated {C : Set E} {P D : Finset E}
    (hPD : C = convexHull ℝ (P : Set E) + (PointedCone.hull ℝ (D : Set E) : Set E)) :
    (P : Set E) ⊆ C := by
  intro p hp
  rw [hPD]
  have h := Set.add_mem_add (subset_convexHull ℝ (P : Set E) hp)
    (PointedCone.hull ℝ (D : Set E)).zero_mem
  rwa [add_zero] at h

/-- The direction generators of a finitely generated set are directions of recession of it. Only
this inclusion is needed below; the reverse one is the description of the recession cone. -/
theorem coe_hull_subset_recessionCone_of_finitelyGenerated {C : Set E} {P D : Finset E}
    (hPD : C = convexHull ℝ (P : Set E) + (PointedCone.hull ℝ (D : Set E) : Set E)) :
    (PointedCone.hull ℝ (D : Set E) : Set E) ⊆ recessionCone C := by
  intro y hy x hx a ha
  rw [hPD] at hx ⊢
  obtain ⟨u, hu, v, hv, huv⟩ := hx
  have huv' : u + v = x := huv
  refine ⟨u, hu, v + a • y, add_mem hv (Submodule.smul_mem _ (⟨a, ha⟩ : {c : ℝ // 0 ≤ c}) hy), ?_⟩
  have hsum : u + (v + a • y) = x + a • y := by rw [← huv']; abel
  exact hsum

/-- A finitely generated set sits inside the convex cone generated by its own generators. -/
theorem subset_coe_hull_of_finitelyGenerated {C : Set E} {P D : Finset E}
    (hPD : C = convexHull ℝ (P : Set E) + (PointedCone.hull ℝ (D : Set E) : Set E)) :
    C ⊆ (PointedCone.hull ℝ ((P : Set E) ∪ (D : Set E)) : Set E) := by
  rw [hPD]
  rintro y ⟨u, hu, v, hv, rfl⟩
  refine add_mem ?_ ?_
  · exact convexHull_min (fun q hq => PointedCone.subset_hull (Or.inl hq))
      ((PointedCone.hull ℝ ((P : Set E) ∪ (D : Set E)) : ConvexCone ℝ E)).convex hu
  · exact (Submodule.span_le.2 fun d hd => PointedCone.subset_hull (Or.inr hd) :
      PointedCone.hull ℝ (D : Set E) ≤ PointedCone.hull ℝ ((P : Set E) ∪ (D : Set E))) hv

/-- The sum of two finitely generated cones is finitely generated: concatenate the generators. -/
theorem FinitelyGeneratedCone.add {K L : Set E} (hK : FinitelyGeneratedCone K)
    (hL : FinitelyGeneratedCone L) : FinitelyGeneratedCone (K + L) := by
  classical
  obtain ⟨s, rfl⟩ := hK
  obtain ⟨t, rfl⟩ := hL
  exact ⟨s ∪ t, by rw [Finset.coe_union, coe_hull_union]⟩

theorem FinitelyGenerated.image {C : Set E} (hC : FinitelyGenerated C) (A : E →ₗ[ℝ] F) :
    FinitelyGenerated (A '' C) := by
  classical
  obtain ⟨P, D, rfl⟩ := hC
  refine ⟨P.image A, D.image A, ?_⟩
  rw [Set.image_add A, LinearMap.image_convexHull, image_coe_hull, Finset.coe_image,
    Finset.coe_image]

theorem FinitelyGenerated.add {C D : Set E} (hC : FinitelyGenerated C)
    (hD : FinitelyGenerated D) : FinitelyGenerated (C + D) := by
  classical
  obtain ⟨P₁, D₁, rfl⟩ := hC
  obtain ⟨P₂, D₂, rfl⟩ := hD
  refine ⟨P₁ + P₂, D₁ ∪ D₂, ?_⟩
  rw [Finset.coe_add, convexHull_add, Finset.coe_union, coe_hull_union]
  exact add_add_add_comm _ _ _ _

end VSide

/-! ### Images, sums and differences -/

section Main

variable {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F] [FiniteDimensional ℝ F]

/-- The image of a polyhedral convex set under a linear transformation is polyhedral. -/
theorem Polyhedral.image {C : Set E} (hC : Polyhedral C) (A : E →ₗ[ℝ] F) :
    Polyhedral (A '' C) :=
  (hC.finitelyGenerated.image A).polyhedral

/-- The sum of two polyhedral convex sets is polyhedral. -/
theorem Polyhedral.add {C D : Set E} (hC : Polyhedral C) (hD : Polyhedral D) :
    Polyhedral (C + D) :=
  (hC.finitelyGenerated.add hD.finitelyGenerated).polyhedral

/-- The negative of a polyhedral set is polyhedral. -/
theorem Polyhedral.neg {C : Set E} (hC : Polyhedral C) : Polyhedral (-C) := by
  have himg : (-C : Set E) = (-LinearMap.id : E →ₗ[ℝ] E) '' C := by
    ext x
    simp only [Set.mem_neg, Set.mem_image, LinearMap.neg_apply, LinearMap.id_apply]
    exact ⟨fun h => ⟨-x, h, by simp⟩, by rintro ⟨y, hy, rfl⟩; simpa using hy⟩
  rw [himg]
  exact hC.image _

/-- The difference of two polyhedral sets is polyhedral. -/
theorem Polyhedral.sub {C D : Set E} (hC : Polyhedral C) (hD : Polyhedral D) :
    Polyhedral (C - D) := by
  rw [sub_eq_add_neg]
  exact hC.add hD.neg

/-- The convex cone generated by a polyhedral convex set containing the origin is finitely
generated — by the very points and directions that generate the set. A closure is needed in
general; the origin is exactly what makes it unnecessary, since then `0⁺C ⊆ λ C` for `λ > 0`. -/
theorem finitelyGeneratedCone_hull_of_zero_mem {C : Set E} (hC : Polyhedral C)
    (h0 : (0 : E) ∈ C) : FinitelyGeneratedCone (PointedCone.hull ℝ C : Set E) := by
  classical
  obtain ⟨P, D, hPD⟩ := hC.finitelyGenerated
  refine ⟨P ∪ D, ?_⟩
  have hgen : ((P ∪ D : Finset E) : Set E) ⊆ C := by
    rw [Finset.coe_union]
    rintro y (hy | hy)
    · rw [hPD]
      have h := Set.add_mem_add (subset_convexHull ℝ (P : Set E) hy)
        (PointedCone.hull ℝ (D : Set E)).zero_mem
      rwa [add_zero] at h
    · rw [hPD] at h0 ⊢
      obtain ⟨q, hq, k, hk, hqk⟩ := Set.mem_add.1 h0
      refine ⟨q, hq, k + y, add_mem hk (PointedCone.subset_hull hy), ?_⟩
      change q + (k + y) = y
      rw [← add_assoc, hqk, zero_add]
  have hCsub : C ⊆ (PointedCone.hull ℝ ((P ∪ D : Finset E) : Set E) : Set E) := by
    rw [Finset.coe_union]
    exact subset_coe_hull_of_finitelyGenerated hPD
  refine subset_antisymm (fun x hx => (Submodule.span_le.2 hCsub) hx) (fun x hx => ?_)
  exact (Submodule.span_le.2 (fun y hy => PointedCone.subset_hull (hgen hy))) hx

/-- A linear subspace of a finite-dimensional space is a finitely generated cone. -/
theorem finitelyGeneratedCone_coe_submodule (S : Submodule ℝ E) :
    FinitelyGeneratedCone (S : Set E) := by
  have h := finitelyGeneratedCone_hull_of_zero_mem (polyhedral_coe_submodule S) S.zero_mem
  rwa [coe_hull_coe_submodule S] at h

/-- A nonnegative multiple of a polyhedral set is polyhedral. -/
theorem Polyhedral.smul {C : Set E} (hC : Polyhedral C) (a : ℝ) : Polyhedral (a • C) := by
  have himg : (a • C : Set E) = (a • LinearMap.id : E →ₗ[ℝ] E) '' C := by
    ext x
    simp only [Set.mem_smul_set, Set.mem_image, LinearMap.smul_apply, LinearMap.id_apply]
  rw [himg]
  exact hC.image _

/-- The origin is a polyhedral set. -/
theorem polyhedral_zero : Polyhedral ({0} : Set E) :=
  PolyhedralCone.polyhedral polyhedralCone_zero

/-- A singleton is a polyhedral set. -/
theorem polyhedral_singleton (v : E) : Polyhedral ({v} : Set E) := by
  classical
  have h := polyhedral_convexHull_finset ({v} : Finset E)
  rwa [Finset.coe_singleton, convexHull_singleton] at h

/-- Two disjoint polyhedral convex sets can be separated *strongly*.

This is cheaper than the general criterion, which asks that the origin miss the *closure* of
`C - D`: for polyhedral sets `C - D` is polyhedral, hence already closed. Neither set has to be
compact, and neither has to be nonempty. -/
theorem separatesStrongly_of_polyhedral {C D : Set E} (hC : Polyhedral C) (hD : Polyhedral D)
    (hdisj : Disjoint C D) : ∃ (f : E →L[ℝ] ℝ) (c : ℝ), SeparatesStrongly f c C D := by
  refine (separatesStrongly_iff_zero_notMem_closure_sub (Polyhedral.convex hC)
    (Polyhedral.convex hD)).2 ?_
  rw [IsClosed.closure_eq (Polyhedral.isClosed (hC.sub hD))]
  rintro ⟨x, hx, y, hy, hxy⟩
  have hxy' : x = y := sub_eq_zero.1 hxy
  exact Set.disjoint_left.1 hdisj hx (hxy' ▸ hy)

end Main

/-! ### The recession cone -/

section Recession

variable {E : Type*} [AddCommGroup E] [Module ℝ E]

/-- The recession cone of a nonempty polyhedral set is obtained by dropping the right-hand sides of
its system of inequalities.

This is `recessionCone_setOf_forall_le` (`Recession/Cone.lean`) with the inequalities turned
around, which is where the two `neg`s come from. -/
theorem recessionCone_polyhedral_system {s : Finset ((E →ₗ[ℝ] ℝ) × ℝ)}
    (hne : {x : E | ∀ q ∈ s, q.1 x ≤ q.2}.Nonempty) :
    recessionCone {x : E | ∀ q ∈ s, q.1 x ≤ q.2} = {y : E | ∀ q ∈ s, q.1 y ≤ 0} := by
  have hset : {x : E | ∀ q ∈ s, q.1 x ≤ q.2}
      = {x : E | ∀ i : {q : (E →ₗ[ℝ] ℝ) × ℝ // q ∈ s}, -(i : (E →ₗ[ℝ] ℝ) × ℝ).2
          ≤ (-(i : (E →ₗ[ℝ] ℝ) × ℝ).1 : E →ₗ[ℝ] ℝ) x} := by
    ext x
    simp only [Set.mem_ofPred_eq, Subtype.forall, LinearMap.neg_apply, neg_le_neg_iff]
  rw [hset, recessionCone_setOf_forall_le _ _ (by rw [← hset]; exact hne)]
  ext y
  simp only [Set.mem_ofPred_eq, Subtype.forall, LinearMap.neg_apply, Left.nonneg_neg_iff]

/-- The recession cone of a nonempty polyhedral set is a polyhedral cone: the same statement, in
the form that does not name the system. -/
theorem Polyhedral.polyhedralCone_recessionCone {C : Set E} (hC : Polyhedral C)
    (hne : C.Nonempty) : PolyhedralCone (recessionCone C) := by
  classical
  obtain ⟨s, rfl⟩ := hC
  rw [recessionCone_polyhedral_system hne]
  refine ⟨s.image Prod.fst, ?_⟩
  ext y
  simp only [Set.mem_ofPred_eq, Finset.mem_image]
  constructor
  · intro h φ hφ
    obtain ⟨q, hq, rfl⟩ := hφ
    exact h q hq
  · intro h q hq
    exact h q.1 ⟨q, hq, rfl⟩

end Recession

/-! ### Closed convex hulls of unions, and generated cones

Both say the same thing: a construction that generates a *non-closed* convex set out of polyhedral
ones — the convex hull of a union, the convex cone generated by a set — is repaired by adding the
recession cones, and the repaired set is again polyhedral. The classical statement gives it as a
union over weights `λᵢ` with `0⁺Cᵢ` substituted where `λᵢ = 0`; adding `0⁺C₁ + 0⁺C₂` to the hull
says the same and needs no convention.

The proof of each is a sandwich between three sets: the closure, the "repaired" set, and the
finitely generated set built from the generators of the pieces. -/

section Generated

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]

/-- The closed convex hull of the union of two nonempty polyhedral convex sets is finitely
generated — hence polyhedral — and is the convex hull of the union with the two recession cones
added.

Both sets have to be nonempty: `0⁺∅` is everything. The `m`-set form is
`finitelyGenerated_closure_convexHull_biUnion`, proved by the same sandwich rather than by
induction on this one. -/
theorem finitelyGenerated_closure_convexHull_union {C₁ C₂ : Set E} (h₁ : Polyhedral C₁)
    (hne₁ : C₁.Nonempty) (h₂ : Polyhedral C₂) (hne₂ : C₂.Nonempty) :
    FinitelyGenerated (closure (convexHull ℝ (C₁ ∪ C₂)))
      ∧ closure (convexHull ℝ (C₁ ∪ C₂))
          = convexHull ℝ (C₁ ∪ C₂) + (recessionCone C₁ + recessionCone C₂) := by
  classical
  obtain ⟨P₁, D₁, hPD₁⟩ := h₁.finitelyGenerated
  obtain ⟨P₂, D₂, hPD₂⟩ := h₂.finitelyGenerated
  set A : Set E := convexHull ℝ ((P₁ : Set E) ∪ (P₂ : Set E))
      + (PointedCone.hull ℝ ((D₁ : Set E) ∪ (D₂ : Set E)) : Set E) with hA
  have hAfg : FinitelyGenerated A := by
    refine ⟨P₁ ∪ P₂, D₁ ∪ D₂, ?_⟩
    rw [hA, Finset.coe_union, Finset.coe_union]
  have hApoly : Polyhedral A := hAfg.polyhedral
  -- (1) the closed convex hull is inside `A`.
  have hstep : ∀ {P D : Finset E} {C : Set E},
      C = convexHull ℝ (P : Set E) + (PointedCone.hull ℝ (D : Set E) : Set E) →
      (P : Set E) ⊆ (P₁ : Set E) ∪ (P₂ : Set E) →
      (D : Set E) ⊆ (D₁ : Set E) ∪ (D₂ : Set E) → C ⊆ A := by
    intro P D C hC hP hD x hx
    rw [hC] at hx
    obtain ⟨u, hu, v, hv, huv⟩ := hx
    have huv' : u + v = x := huv
    have hvmem : v ∈ (PointedCone.hull ℝ ((D₁ : Set E) ∪ (D₂ : Set E)) : Set E) :=
      (Submodule.span_le.2 (fun d hd => PointedCone.subset_hull (hD hd)) :
        PointedCone.hull ℝ (D : Set E) ≤ _) hv
    exact ⟨u, convexHull_mono hP hu, v, hvmem, huv'⟩
  have hclA : closure (convexHull ℝ (C₁ ∪ C₂)) ⊆ A :=
    hApoly.isClosed.closure_subset_iff.2
      (convexHull_min (Set.union_subset (hstep hPD₁ Set.subset_union_left Set.subset_union_left)
        (hstep hPD₂ Set.subset_union_right Set.subset_union_right)) hApoly.convex)
  -- (2) `A` is inside the repaired set.
  have hAsub : A ⊆ convexHull ℝ (C₁ ∪ C₂) + (recessionCone C₁ + recessionCone C₂) := by
    rw [hA]
    rintro x ⟨u, hu, v, hv, huv⟩
    have huv' : u + v = x := huv
    refine ⟨u, convexHull_mono ?_ hu, v, ?_, huv'⟩
    · exact Set.union_subset
        ((coe_subset_of_finitelyGenerated hPD₁).trans Set.subset_union_left)
        ((coe_subset_of_finitelyGenerated hPD₂).trans Set.subset_union_right)
    · rw [coe_hull_union] at hv
      obtain ⟨s, hs, t, ht, hst⟩ := hv
      have hst' : s + t = v := hst
      exact ⟨s, coe_hull_subset_recessionCone_of_finitelyGenerated hPD₁ hs,
        t, coe_hull_subset_recessionCone_of_finitelyGenerated hPD₂ ht, hst'⟩
  -- (3) the repaired set is inside the closure, because the closure recedes in both directions.
  have hrec : ∀ {C : Set E}, C.Nonempty → C ⊆ closure (convexHull ℝ (C₁ ∪ C₂)) →
      recessionCone C ⊆ recessionCone (closure (convexHull ℝ (C₁ ∪ C₂))) := by
    intro C hCne hCsub y hy
    obtain ⟨x, hx⟩ := hCne
    exact mem_recessionCone_of_exists_ray ((convex_convexHull ℝ _).closure) isClosed_closure
      ⟨x, fun a ha => hCsub (hy x hx a ha)⟩
  have hin₁ : C₁ ⊆ closure (convexHull ℝ (C₁ ∪ C₂)) := fun z hz =>
    subset_closure (subset_convexHull ℝ _ (Or.inl hz))
  have hin₂ : C₂ ⊆ closure (convexHull ℝ (C₁ ∪ C₂)) := fun z hz =>
    subset_closure (subset_convexHull ℝ _ (Or.inr hz))
  have hfinal : convexHull ℝ (C₁ ∪ C₂) + (recessionCone C₁ + recessionCone C₂)
      ⊆ closure (convexHull ℝ (C₁ ∪ C₂)) := by
    rintro x ⟨u, hu, v, hv, huv⟩
    have huv' : u + v = x := huv
    obtain ⟨s, hs, t, ht, hst⟩ := hv
    have hst' : s + t = v := hst
    have h1 := add_mem_of_mem_recessionCone (hrec hne₁ hin₁ hs) (subset_closure hu)
    have h2 := add_mem_of_mem_recessionCone (hrec hne₂ hin₂ ht) h1
    have heq : u + s + t = x := by rw [← huv', ← hst']; abel
    rwa [heq] at h2
  refine ⟨?_, subset_antisymm (hclA.trans hAsub) hfinal⟩
  have heq : closure (convexHull ℝ (C₁ ∪ C₂)) = A :=
    subset_antisymm hclA ((hAsub.trans hfinal))
  rw [heq]
  exact hAfg

/-- The closed convex hull of the union of two nonempty polyhedral convex sets is polyhedral. -/
theorem polyhedral_closure_convexHull_union {C₁ C₂ : Set E} (h₁ : Polyhedral C₁)
    (hne₁ : C₁.Nonempty) (h₂ : Polyhedral C₂) (hne₂ : C₂.Nonempty) :
    Polyhedral (closure (convexHull ℝ (C₁ ∪ C₂))) :=
  (finitelyGenerated_closure_convexHull_union h₁ hne₁ h₂ hne₂).1.polyhedral

/-- The closed convex hull of a union of finitely many nonempty polyhedral convex sets is finitely
generated — hence polyhedral — and is obtained from the convex hull of the union by adding the
recession cones of the pieces.

Not an induction on `finitelyGenerated_closure_convexHull_union`. Re-entering the binary statement
at `C₁ ∪ cl (conv (⋃ …))` would first have to show that the closed convex hull absorbs an inner
closure, and then that `0⁺` of the inner hull is the sum of the `0⁺ Cᵢ`. The binary proof's
three-set sandwich — the closed hull, the repaired set, and the finitely generated set built from
all the generators at once — runs over a `Finset` of indices with no extra work, so that is what is
done here.

The empty index set needs no side condition: both sides are then `∅`. -/
theorem finitelyGenerated_closure_convexHull_biUnion {ι : Type*} {s : Finset ι} {C : ι → Set E}
    (hC : ∀ i ∈ s, Polyhedral (C i)) (hne : ∀ i ∈ s, (C i).Nonempty) :
    FinitelyGenerated (closure (convexHull ℝ (⋃ i ∈ s, C i)))
      ∧ closure (convexHull ℝ (⋃ i ∈ s, C i))
          = convexHull ℝ (⋃ i ∈ s, C i) + ∑ i ∈ s, recessionCone (C i) := by
  classical
  obtain ⟨p, hp⟩ : ∃ p : ι → Finset E × Finset E, ∀ i ∈ s,
      C i = convexHull ℝ ((p i).1 : Set E) + (PointedCone.hull ℝ ((p i).2 : Set E) : Set E) := by
    have h : ∀ i : ι, ∃ q : Finset E × Finset E, i ∈ s →
        C i = convexHull ℝ (q.1 : Set E) + (PointedCone.hull ℝ (q.2 : Set E) : Set E) := by
      intro i
      by_cases hi : i ∈ s
      · obtain ⟨P, D, hPD⟩ := (hC i hi).finitelyGenerated
        exact ⟨(P, D), fun _ => hPD⟩
      · exact ⟨(∅, ∅), fun hmem => absurd hmem hi⟩
    choose q hq using h
    exact ⟨q, hq⟩
  set A : Set E := convexHull ℝ ((s.biUnion fun i => (p i).1 : Finset E) : Set E)
      + (PointedCone.hull ℝ ((s.biUnion fun i => (p i).2 : Finset E) : Set E) : Set E) with hA
  have hAfg : FinitelyGenerated A :=
    ⟨s.biUnion fun i => (p i).1, s.biUnion fun i => (p i).2, hA⟩
  have hApoly : Polyhedral A := hAfg.polyhedral
  -- (1) the closed convex hull is inside `A`.
  have hCsubA : ∀ i ∈ s, C i ⊆ A := by
    intro i hi x hx
    rw [hp i hi] at hx
    obtain ⟨u, hu, v, hv, huv⟩ := hx
    have huv' : u + v = x := huv
    refine ⟨u, convexHull_mono (fun y hy => ?_) hu, v, ?_, huv'⟩
    · exact Finset.mem_coe.2 (Finset.mem_biUnion.2 ⟨i, hi, Finset.mem_coe.1 hy⟩)
    · exact (Submodule.span_le.2 (fun d hd => PointedCone.subset_hull
        (Finset.mem_coe.2 (Finset.mem_biUnion.2 ⟨i, hi, Finset.mem_coe.1 hd⟩))) :
        PointedCone.hull ℝ ((p i).2 : Set E)
          ≤ PointedCone.hull ℝ ((s.biUnion fun i => (p i).2 : Finset E) : Set E)) hv
  have hclA : closure (convexHull ℝ (⋃ i ∈ s, C i)) ⊆ A :=
    hApoly.isClosed.closure_subset_iff.2
      (convexHull_min (Set.iUnion₂_subset hCsubA) hApoly.convex)
  -- (2) `A` is inside the repaired set.
  have hDcoe : ((s.biUnion fun i => (p i).2 : Finset E) : Set E)
      = ⋃ i ∈ s, ((p i).2 : Set E) := by
    ext y; simp
  have hAsub : A ⊆ convexHull ℝ (⋃ i ∈ s, C i) + ∑ i ∈ s, recessionCone (C i) := by
    rw [hA]
    rintro x ⟨u, hu, v, hv, huv⟩
    have huv' : u + v = x := huv
    refine ⟨u, convexHull_mono (fun y hy => ?_) hu, v, ?_, huv'⟩
    · obtain ⟨i, hi, hy'⟩ := Finset.mem_biUnion.1 (Finset.mem_coe.1 hy)
      exact Set.mem_biUnion hi
        (coe_subset_of_finitelyGenerated (hp i hi) (Finset.mem_coe.2 hy'))
    · rw [hDcoe, coe_hull_biUnion] at hv
      exact Finset.sum_le_sum
        (fun i hi => coe_hull_subset_recessionCone_of_finitelyGenerated (hp i hi)) hv
  -- (3) the repaired set is inside the closure, because the closure recedes in every direction.
  have hin : ∀ i ∈ s, C i ⊆ closure (convexHull ℝ (⋃ i ∈ s, C i)) := fun i hi z hz =>
    subset_closure (subset_convexHull ℝ _ (Set.mem_biUnion hi hz))
  have hrec : ∀ i ∈ s, recessionCone (C i)
      ⊆ recessionCone (closure (convexHull ℝ (⋃ i ∈ s, C i))) := by
    intro i hi y hy
    obtain ⟨x, hx⟩ := hne i hi
    exact mem_recessionCone_of_exists_ray ((convex_convexHull ℝ _).closure) isClosed_closure
      ⟨x, fun a ha => hin i hi (hy x hx a ha)⟩
  have hfinal : convexHull ℝ (⋃ i ∈ s, C i) + ∑ i ∈ s, recessionCone (C i)
      ⊆ closure (convexHull ℝ (⋃ i ∈ s, C i)) := by
    rintro x ⟨u, hu, v, hv, huv⟩
    have huv' : u + v = x := huv
    have hvrec : v ∈ recessionCone (closure (convexHull ℝ (⋃ i ∈ s, C i))) :=
      finset_sum_subset_of_forall_subset (zero_mem_recessionCone _)
        (fun _ ha _ hb => add_mem_recessionCone ha hb) hrec hv
    have h := add_mem_of_mem_recessionCone hvrec (subset_closure hu)
    rwa [huv'] at h
  refine ⟨?_, subset_antisymm (hclA.trans hAsub) hfinal⟩
  have heq : closure (convexHull ℝ (⋃ i ∈ s, C i)) = A :=
    subset_antisymm hclA (hAsub.trans hfinal)
  rw [heq]
  exact hAfg

/-- The closed convex hull of a union of finitely many nonempty polyhedral sets is polyhedral. -/
theorem polyhedral_closure_convexHull_biUnion {ι : Type*} {s : Finset ι} {C : ι → Set E}
    (hC : ∀ i ∈ s, Polyhedral (C i)) (hne : ∀ i ∈ s, (C i).Nonempty) :
    Polyhedral (closure (convexHull ℝ (⋃ i ∈ s, C i))) :=
  (finitelyGenerated_closure_convexHull_biUnion hC hne).1.polyhedral

/-- The closure of the convex cone generated by a nonempty polyhedral convex set is a finitely
generated cone, and is obtained from the cone itself by adding the recession cone of the set.

The closure is genuinely needed: for `C` the horizontal line at height `1` in `ℝ²` the cone
generated by `C` is the open upper half-plane together with the origin, and the missing horizontal
directions are exactly `0⁺C`. -/
theorem finitelyGeneratedCone_closure_coe_hull {C : Set E} (hC : Polyhedral C) (hne : C.Nonempty) :
    FinitelyGeneratedCone (closure (PointedCone.hull ℝ C : Set E))
      ∧ closure (PointedCone.hull ℝ C : Set E)
          = (PointedCone.hull ℝ C : Set E) + recessionCone C := by
  classical
  obtain ⟨P, D, hPD⟩ := hC.finitelyGenerated
  set A : Set E := (PointedCone.hull ℝ ((P : Set E) ∪ (D : Set E)) : Set E) with hA
  have hAfg : FinitelyGeneratedCone A := by
    refine ⟨P ∪ D, ?_⟩
    rw [hA, Finset.coe_union]
  have hclA : closure (PointedCone.hull ℝ C : Set E) ⊆ A :=
    hAfg.isClosed.closure_subset_iff.2
      (Submodule.span_le.2 (subset_coe_hull_of_finitelyGenerated hPD))
  have hAsub : A ⊆ (PointedCone.hull ℝ C : Set E) + recessionCone C := by
    rw [hA, coe_hull_union]
    rintro x ⟨s, hs, t, ht, hst⟩
    have hst' : s + t = x := hst
    refine ⟨s, ?_, t, coe_hull_subset_recessionCone_of_finitelyGenerated hPD ht, hst'⟩
    exact (Submodule.span_le.2 (fun q hq =>
      PointedCone.subset_hull (coe_subset_of_finitelyGenerated hPD hq)) :
      PointedCone.hull ℝ (P : Set E) ≤ PointedCone.hull ℝ C) hs
  have hCsubK : C ⊆ closure (PointedCone.hull ℝ C : Set E) :=
    fun z hz => subset_closure (PointedCone.subset_hull hz)
  have hrec : recessionCone C ⊆ recessionCone (closure (PointedCone.hull ℝ C : Set E)) := by
    intro y hy
    obtain ⟨x, hx⟩ := hne
    exact mem_recessionCone_of_exists_ray
      ((PointedCone.hull ℝ C : ConvexCone ℝ E).convex.closure) isClosed_closure
      ⟨x, fun a ha => hCsubK (hy x hx a ha)⟩
  have hfinal : (PointedCone.hull ℝ C : Set E) + recessionCone C
      ⊆ closure (PointedCone.hull ℝ C : Set E) := by
    rintro x ⟨u, hu, v, hv, huv⟩
    have huv' : u + v = x := huv
    have h := add_mem_of_mem_recessionCone (hrec hv) (subset_closure hu)
    rwa [huv'] at h
  refine ⟨?_, subset_antisymm (hclA.trans hAsub) hfinal⟩
  have heq : closure (PointedCone.hull ℝ C : Set E) = A :=
    subset_antisymm hclA (hAsub.trans hfinal)
  rw [heq]
  exact hAfg

/-- The closure of the convex cone generated by a nonempty polyhedral convex set is a polyhedral
cone. -/
theorem polyhedralCone_closure_coe_hull {C : Set E} (hC : Polyhedral C) (hne : C.Nonempty) :
    PolyhedralCone (closure (PointedCone.hull ℝ C : Set E)) :=
  (finitelyGeneratedCone_closure_coe_hull hC hne).1.polyhedralCone

end Generated

end Tdaf.ConvexAnalysis
