/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Tdaf.Analysis.Convex.Duality.Support
import Tdaf.Analysis.Convex.Polyhedral.Ops
import Tdaf.Analysis.Convex.RelativeInterior

/-!
# Proper separation from a polyhedral set

Rockafellar's Theorem 20.2. Theorem 11.3 separates two nonempty convex sets properly exactly when
their *relative interiors* are disjoint; when one of the two sets is polyhedral, the relative
interior on that side may be dropped, and the separating hyperplane can in addition be required not
to contain the other set.

## Main results

* `exists_separates_not_subset_iff_disjoint_relint` — **Theorem 20.2**.
* `disjoint_relint_of_separates_of_not_subset` — its easy half, which needs no polyhedrality.
* `nonempty_inter_relint_iff_forall_supportFn` — **Corollary 20.2.1**, the same condition read
  through support functions.
* `supportFn_le_neg_supportFn_neg_iff` — the dictionary entry it rests on: `δ*(y | s)` is at most
  `-δ*(-y | t)` exactly when `⟨·, y⟩` is nowhere larger on `s` than it is on `t`.
* `levelSet` — the level set of a continuous linear functional, packaged as an affine subspace; it
  is what turns "constant on `C`" into "constant on `aff C`".

## Design notes

**The translation is carried out by hand.** Rockafellar moves the common point of `C₁` and the
relative boundary of `C₂'` to the origin, "translating all the sets if necessary"; here the
translation stays explicit, so `K` is the cone generated by `C₁ - x₀` and the subspace playing the
role of `M` is `M₀ = (aff C₂).direction ⊓ ker f`, not a translate of it.

**The half-space that works is found by a positivity argument, not by elimination.** Rockafellar
argues that some `Hᵢ` in a representation of `C₁' = K + M` misses `ri C₂'`, because a half-space
meeting `ri C₂'` must swallow all of `C₂'`. The formalized version instead picks *any* `φ` in the
representation of `C₁'` with `φ w > 0` at a point `w` of `ri C₂'` lying outside `C₁'`, and then
checks directly that `φ ≥ 0` on all of `C₂'`: for `z` in `C₂'` the vector `z - (f z / f w) • w`
lies in `M₀`, where `φ` vanishes, so `φ z` is a nonnegative multiple of `φ w`.

**`ri C₂'` never appears.** What the argument actually uses about it is only that it contains the
translated set `{y | y + x₀ ∈ aff C₂ ∧ f (y + x₀) > c}`, so that set is used instead and no
relative interior of `C₂'` has to be computed.
-/

open Set
open scoped Pointwise

namespace Tdaf.ConvexAnalysis

section LevelSet

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- The level set `{x | f x = c}` of a continuous linear functional, as an affine subspace.

The only thing it is used for is `affineSpan_le`: a functional constant on a set is constant on the
set's affine hull. -/
def levelSet (f : E →L[ℝ] ℝ) (c : ℝ) : AffineSubspace ℝ E where
  carrier := {x | f x = c}
  smul_vsub_vadd_mem' := by
    intro t p₁ p₂ p₃ h₁ h₂ h₃
    have hp₁ : f p₁ = c := h₁
    have hp₂ : f p₂ = c := h₂
    have hp₃ : f p₃ = c := h₃
    have h : f (t • (p₁ - p₂) + p₃) = c := by
      rw [map_add, map_smul, map_sub, hp₁, hp₂, hp₃, smul_eq_mul]
      ring
    exact h

@[simp] theorem mem_levelSet {f : E →L[ℝ] ℝ} {c : ℝ} {x : E} :
    x ∈ levelSet f c ↔ f x = c := Iff.rfl

/-- A continuous linear functional constant on a set is constant on its affine hull. -/
theorem forall_eq_of_mem_affineSpan {f : E →L[ℝ] ℝ} {c : ℝ} {s : Set E}
    (h : ∀ x ∈ s, f x = c) : ∀ x ∈ affineSpan ℝ s, f x = c := by
  intro x hx
  have hle : affineSpan ℝ s ≤ levelSet f c := affineSpan_le.2 fun y hy => h y hy
  exact hle hx

end LevelSet

section Separation

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]

omit [FiniteDimensional ℝ E] in
/-- The easy half of **Theorem 20.2**, which needs no polyhedrality: a hyperplane separating `C₁`
and `C₂` and not containing `C₂` keeps `C₁` out of `ri C₂`.

A point of `C₁ ∩ ri C₂` would lie on the hyperplane, so `-f` would attain its maximum over `C₂` at
a relative interior point, forcing `f` to be constant on `C₂`. -/
theorem disjoint_relint_of_separates_of_not_subset {C₁ C₂ : Set E} {f : E →L[ℝ] ℝ} {c : ℝ}
    (hsep : Separates f c C₁ C₂) (hns : ¬ (C₂ ⊆ {x | f x = c})) : Disjoint C₁ (ri C₂) := by
  rw [Set.disjoint_left]
  intro x hx₁ hx₂
  have hxC₂ : x ∈ C₂ := intrinsicInterior_subset hx₂
  have hfx : f x = c := le_antisymm (hsep.le_of_mem_left hx₁) (hsep.le_of_mem_right hxC₂)
  have hmax : ∀ y ∈ C₂, (-(f : E →ₗ[ℝ] ℝ)) y ≤ (-(f : E →ₗ[ℝ] ℝ)) x := by
    intro y hy
    have hy' := hsep.le_of_mem_right hy
    have h : -(f y) ≤ -(f x) := by rw [hfx]; linarith
    exact h
  have hconst := eq_of_isMaxOn_of_mem_relint hx₂ hmax
  refine hns fun y hy => ?_
  have h' : -(f y) = -(f x) := hconst y hy
  have h : f y = c := by rw [hfx] at h'; linarith
  exact h

/-- **Rockafellar, Theorem 20.2.** Let `C₁` be a nonempty *polyhedral* convex set and `C₂` a
nonempty convex set. Then `C₁` and `C₂` can be separated by a hyperplane which separates them
properly and does *not* contain `C₂`, exactly when `C₁` misses `ri C₂`.

Compare Theorem 11.3, which asks for `ri C₁ ∩ ri C₂ = ∅` and promises nothing about containment:
polyhedrality of `C₁` buys both improvements at once. Properness of the separation is not stated
separately — it follows from the non-containment of `C₂`. -/
theorem exists_separates_not_subset_iff_disjoint_relint {C₁ C₂ : Set E} (h₁ : Polyhedral C₁)
    (h₂ : Convex ℝ C₂) (hne₂ : C₂.Nonempty) :
    (∃ (g : E →L[ℝ] ℝ) (c : ℝ), Separates g c C₁ C₂ ∧ ¬ (C₂ ⊆ {x | g x = c}))
      ↔ Disjoint C₁ (ri C₂) := by
  classical
  refine ⟨fun ⟨_, _, hsep, hns⟩ => disjoint_relint_of_separates_of_not_subset hsep hns,
    fun hdisj => ?_⟩
  -- Strong separation from any superset of `C₂` already gives what is wanted.
  have hstrong : ∀ A : Set E, C₂ ⊆ A →
      (∃ (f : E →L[ℝ] ℝ) (c : ℝ), SeparatesStrongly f c C₁ A) →
      ∃ (g : E →L[ℝ] ℝ) (c : ℝ), Separates g c C₁ C₂ ∧ ¬ (C₂ ⊆ {x | g x = c}) := by
    rintro A hCA ⟨f, c, hs⟩
    obtain ⟨y₀, hy₀⟩ := hne₂
    refine ⟨f, c, hs.separates.mono (subset_refl C₁) hCA, fun hcon => ?_⟩
    have hlt : c < f y₀ := hs.lt_of_mem_right (hCA hy₀)
    have heq : f y₀ = c := hcon hy₀
    linarith
  set MA : AffineSubspace ℝ E := affineSpan ℝ C₂ with hMA
  have hC₂MA : C₂ ⊆ (MA : Set E) := subset_affineSpan ℝ C₂
  have hMApoly : Polyhedral (MA : Set E) := by
    obtain ⟨y₀, hy₀⟩ := hne₂
    exact polyhedral_coe_affineSubspace (hC₂MA hy₀)
  by_cases hD : (C₁ ∩ (MA : Set E)).Nonempty
  · -- `C₁` meets `aff C₂`: separate `C₁ ∩ aff C₂` from `C₂` properly first (Theorem 11.3).
    obtain ⟨p₀, hp₀C₁, hp₀M⟩ := hD
    have hDconv : Convex ℝ (C₁ ∩ (MA : Set E)) := Polyhedral.convex (h₁.inter hMApoly)
    have hDne : (C₁ ∩ (MA : Set E)).Nonempty := ⟨p₀, hp₀C₁, hp₀M⟩
    have hdisjD : Disjoint (ri (C₁ ∩ (MA : Set E))) (ri C₂) := by
      rw [Set.disjoint_left]
      intro x hx hx₂
      have hxD : x ∈ C₁ ∩ (MA : Set E) := intrinsicInterior_subset hx
      exact Set.disjoint_left.1 hdisj hxD.1 hx₂
    obtain ⟨f, c, hsep⟩ :=
      (exists_separatesProperly_iff_disjoint_relint hDconv h₂ hDne hne₂).2 hdisjD
    -- Properness rules out `f` being constant on `C₂`, since it is then constant on `aff C₂ ⊇ D`.
    have hnsC₂ : ¬ (C₂ ⊆ {x | f x = c}) := by
      intro hcon
      refine hsep.not_subset ?_
      have hMAlevel : ∀ x ∈ affineSpan ℝ C₂, f x = c :=
        forall_eq_of_mem_affineSpan fun x hx => hcon hx
      rintro x (hx | hx)
      · exact hMAlevel x hx.2
      · exact hcon hx
    obtain ⟨x₂, hx₂C₂, hx₂ne⟩ : ∃ x ∈ C₂, f x ≠ c := by
      by_contra hcon
      push Not at hcon
      exact hnsC₂ fun x hx => hcon x hx
    have hx₂gt : c < f x₂ := lt_of_le_of_ne (hsep.le_of_mem_right hx₂C₂) (Ne.symm hx₂ne)
    -- `C₂'`, the closed half of `aff C₂` bounded by the separating hyperplane, contains `C₂`.
    have hhalf : Polyhedral {x : E | c ≤ f x} := by
      have h := polyhedral_halfSpace (-(f : E →ₗ[ℝ] ℝ)) (-c)
      have hset : {x : E | (-(f : E →ₗ[ℝ] ℝ)) x ≤ -c} = {x : E | c ≤ f x} := by
        ext x
        constructor
        · intro hx
          have hx' : -(f x) ≤ -c := hx
          have : c ≤ f x := by linarith
          exact this
        · intro hx
          have hx' : c ≤ f x := hx
          have : -(f x) ≤ -c := by linarith
          exact this
      rwa [hset] at h
    have hC₂'poly : Polyhedral ((MA : Set E) ∩ {x : E | c ≤ f x}) := hMApoly.inter hhalf
    have hC₂sub : C₂ ⊆ (MA : Set E) ∩ {x : E | c ≤ f x} :=
      fun x hx => ⟨hC₂MA hx, hsep.le_of_mem_right hx⟩
    by_cases hB : (C₁ ∩ ((MA : Set E) ∩ {x : E | c ≤ f x})).Nonempty
    · -- The interesting case: `C₁` touches the closed half `C₂'` of `aff C₂`.
      obtain ⟨x₀, hx₀C₁, hx₀C₂'⟩ := hB
      have hx₀M : x₀ ∈ MA := hx₀C₂'.1
      have hfx₀ : f x₀ = c := by
        have hle : f x₀ ≤ c := hsep.le_of_mem_left ⟨hx₀C₁, hx₀C₂'.1⟩
        have hge : c ≤ f x₀ := hx₀C₂'.2
        linarith
      set A : Submodule ℝ E := MA.direction with hAdef
      have hA : ∀ y : E, y - x₀ ∈ A ↔ y ∈ MA := by
        intro y
        have h := AffineSubspace.vsub_right_mem_direction_iff_mem hx₀M y
        rw [vsub_eq_sub] at h
        exact h
      set M₀ : Submodule ℝ E := A ⊓ LinearMap.ker (f : E →ₗ[ℝ] ℝ) with hM₀def
      -- The polyhedral cone `C₁' = K + M₀`, where `K` is the cone generated by `C₁ - x₀`.
      have hSpoly : Polyhedral (C₁ - ({x₀} : Set E)) := h₁.sub (polyhedral_singleton x₀)
      have hSmem : ∀ x ∈ C₁, x - x₀ ∈ C₁ - ({x₀} : Set E) :=
        fun x hx => Set.sub_mem_sub hx rfl
      have hS0 : (0 : E) ∈ C₁ - ({x₀} : Set E) := by
        have h := hSmem x₀ hx₀C₁
        rwa [sub_self] at h
      set K : Set E := (PointedCone.hull ℝ (C₁ - ({x₀} : Set E)) : Set E) with hKdef
      have hKfg : FinitelyGeneratedCone K := finitelyGeneratedCone_hull_of_zero_mem hSpoly hS0
      obtain ⟨s, hs⟩ :=
        (hKfg.add (finitelyGeneratedCone_coe_submodule M₀)).polyhedralCone
      have hKsub : K ⊆ K + (M₀ : Set E) := fun k hk => ⟨k, hk, 0, M₀.zero_mem, add_zero k⟩
      have hM₀sub : (M₀ : Set E) ⊆ K + (M₀ : Set E) := fun m hm =>
        ⟨0, (PointedCone.hull ℝ (C₁ - ({x₀} : Set E))).zero_mem, m, hm, zero_add m⟩
      -- `w` lies in the translated relative interior of `C₂'` but outside `C₁'`.
      have hwA : x₂ - x₀ ∈ A := (hA x₂).2 (hC₂MA hx₂C₂)
      have hfw : 0 < f (x₂ - x₀) := by rw [map_sub, hfx₀]; linarith
      have hwnot : x₂ - x₀ ∉ K + (M₀ : Set E) := by
        rintro ⟨k, hk, m, hm, hkm⟩
        have hkm' : k + m = x₂ - x₀ := hkm
        have hmA : m ∈ A := (Submodule.mem_inf.1 hm).1
        have hfm : f m = 0 := (Submodule.mem_inf.1 hm).2
        have hkeq : k = (x₂ - x₀) - m := by rw [← hkm']; abel
        have hkA : k ∈ A := by rw [hkeq]; exact A.sub_mem hwA hmA
        have hfk : 0 < f k := by rw [hkeq, map_sub, hfm]; linarith
        rw [hKdef, coe_hull_of_convex_zero_mem hSpoly.convex hS0] at hk
        obtain ⟨t, ht, v, hv, hvk⟩ := hk
        have hvk' : t • v = k := hvk
        rcases eq_or_lt_of_le ht with ht0 | ht0
        · rw [← ht0, zero_smul] at hvk'
          rw [← hvk', map_zero] at hfk
          exact lt_irrefl 0 hfk
        · obtain ⟨x, hx, y, hy, hxy⟩ := hv
          have hxy' : x - y = v := hxy
          have hyx₀ : y = x₀ := hy
          have hvx : x - x₀ = v := by rw [← hxy', hyx₀]
          have hvA : v ∈ A := by
            have h := A.smul_mem t⁻¹ hkA
            rwa [← hvk', inv_smul_smul₀ ht0.ne'] at h
          have hxM : x ∈ MA := (hA x).1 (by rw [hvx]; exact hvA)
          have hfx : f x ≤ c := hsep.le_of_mem_left ⟨hx, hxM⟩
          have hfv : f v ≤ 0 := by rw [← hvx, map_sub, hfx₀]; linarith
          have hfkv : f k = t * f v := by rw [← hvk', map_smul, smul_eq_mul]
          nlinarith
      -- Choose a constraint of `C₁'` violated by `w`.
      have hwnot' : ¬ (∀ φ ∈ s, φ (x₂ - x₀) ≤ 0) := by rw [hs] at hwnot; exact hwnot
      push Not at hwnot'
      obtain ⟨φ, hφs, hφw⟩ := hwnot'
      have hle : ∀ y ∈ K + (M₀ : Set E), φ y ≤ 0 := by
        intro y hy
        rw [hs] at hy
        exact hy φ hφs
      have hφM₀ : ∀ m ∈ M₀, φ m = 0 := by
        intro m hm
        have h1 : φ m ≤ 0 := hle m (hM₀sub hm)
        have h2 : φ (-m) ≤ 0 := hle _ (hM₀sub (M₀.neg_mem hm))
        rw [map_neg] at h2
        linarith
      -- `φ` is nonnegative on the translate of `C₂'`, and positive on its relative interior.
      have hclaim : ∀ z : E, z ∈ A → 0 ≤ f z → 0 ≤ φ z ∧ (0 < f z → 0 < φ z) := by
        intro z hzA hfz
        set r : ℝ := f z / f (x₂ - x₀) with hr
        have hu : z - r • (x₂ - x₀) ∈ M₀ := by
          refine Submodule.mem_inf.2 ⟨A.sub_mem hzA (A.smul_mem r hwA), ?_⟩
          have h2 : f (z - r • (x₂ - x₀)) = f z - r * f (x₂ - x₀) := by
            rw [map_sub, map_smul, smul_eq_mul]
          have h3 : (f : E →ₗ[ℝ] ℝ) (z - r • (x₂ - x₀)) = f (z - r • (x₂ - x₀)) := rfl
          refine LinearMap.mem_ker.2 ?_
          rw [h3, h2, hr, div_mul_cancel₀ _ hfw.ne', sub_self]
        have hφu := hφM₀ _ hu
        rw [map_sub, map_smul, smul_eq_mul] at hφu
        have hφz : φ z = r * φ (x₂ - x₀) := by linarith
        refine ⟨?_, ?_⟩
        · rw [hφz, hr]
          exact mul_nonneg (div_nonneg hfz hfw.le) hφw.le
        · intro hpos
          rw [hφz, hr]
          exact mul_pos (div_pos hpos hfw) hφw
      refine ⟨LinearMap.toContinuousLinearMap φ, φ x₀, ⟨?_, ?_⟩, ?_⟩
      · intro x hx
        have h := hle _ (hKsub (PointedCone.subset_hull (hSmem x hx)))
        rw [map_sub] at h
        have hco : (LinearMap.toContinuousLinearMap φ) x = φ x := rfl
        rw [hco]
        linarith
      · intro y hy
        have hyA : y - x₀ ∈ A := (hA y).2 (hC₂MA hy)
        have hfy : 0 ≤ f (y - x₀) := by
          have := hsep.le_of_mem_right hy
          rw [map_sub, hfx₀]
          linarith
        have h := (hclaim _ hyA hfy).1
        rw [map_sub] at h
        have hco : (LinearMap.toContinuousLinearMap φ) y = φ y := rfl
        rw [hco]
        linarith
      · intro hcon
        have heq : (LinearMap.toContinuousLinearMap φ) x₂ = φ x₀ := hcon hx₂C₂
        have hco : (LinearMap.toContinuousLinearMap φ) x₂ = φ x₂ := rfl
        rw [hco] at heq
        have hsplit : φ (x₂ - x₀) = φ x₂ - φ x₀ := by rw [map_sub]
        rw [hsplit] at hφw
        linarith
    · -- `C₁` misses the closed half `C₂'`: strong separation (Corollary 19.3.3) finishes.
      refine hstrong _ hC₂sub (separatesStrongly_of_polyhedral h₁ hC₂'poly ?_)
      rw [Set.disjoint_iff_inter_eq_empty]
      exact Set.not_nonempty_iff_eq_empty.1 hB
  · -- `C₁` misses `aff C₂` outright: strong separation from the affine hull.
    refine hstrong _ hC₂MA (separatesStrongly_of_polyhedral h₁ hMApoly ?_)
    rw [Set.disjoint_iff_inter_eq_empty]
    exact Set.not_nonempty_iff_eq_empty.1 hD

end Separation

/-! ### Corollary 20.2.1 -/

section SupportFn

variable {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F] {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} {C₁ C₂ : Set E}

omit [FiniteDimensional ℝ E] in
/-- **Separation, in support functions.** The hyperplanes `{x | ⟨x, y⟩ = α}` that separate `s` from
`t` are exactly those with `δ*(y | s) ≤ α ≤ -δ*(-y | t)`; there is such an `α` exactly when the
pairing with `y` is nowhere larger on `s` than on `t`.

Neither set has to be nonempty: an empty `s` sends the left side to `⊥` and an empty `t` sends the
right side to `⊤`, and both conditions are then vacuous. -/
theorem supportFn_le_neg_supportFn_neg_iff (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (s t : Set E) (y : F) :
    supportFn B s y ≤ -supportFn B t (-y) ↔ ∀ x₁ ∈ s, ∀ x₂ ∈ t, B x₁ y ≤ B x₂ y := by
  have hflip : ∀ x : E, -((B x (-y) : ℝ) : EReal) = ((B x y : ℝ) : EReal) := by
    intro x
    rw [map_neg, _root_.EReal.coe_neg, neg_neg]
  constructor
  · intro h x₁ hx₁ x₂ hx₂
    have h₁ : ((B x₁ y : ℝ) : EReal) ≤ supportFn B s y := le_supportFn hx₁ y
    have h₃ : -supportFn B t (-y) ≤ -((B x₂ (-y) : ℝ) : EReal) :=
      _root_.EReal.neg_le_neg_iff.2 (le_supportFn hx₂ (-y))
    have h₅ : ((B x₁ y : ℝ) : EReal) ≤ ((B x₂ y : ℝ) : EReal) := by
      rw [← hflip x₂]
      exact (h₁.trans h).trans h₃
    exact_mod_cast h₅
  · intro h
    rw [_root_.EReal.le_neg]
    refine supportFn_le_iff.2 fun x₂ hx₂ => ?_
    rw [_root_.EReal.le_neg, hflip x₂]
    exact supportFn_le_coe_iff.2 fun x₁ hx₁ => h x₁ hx₁ x₂ hx₂

/-- **Rockafellar, Corollary 20.2.1.** For a nonempty polyhedral `C₁` and a nonempty convex `C₂`,
`C₁` meets `ri C₂` exactly when every `y` for which some hyperplane `⟨·, y⟩ = α` separates the two
sets has `δ*(y | C₁) = δ*(y | C₂)` — that is, every separating hyperplane contains `C₂`.

This is Theorem 20.2 with both sides negated and translated: the separation condition there becomes
the support-function condition here. It is the form Theorem 20.3 applies, to the barrier cones. -/
theorem nonempty_inter_relint_iff_forall_supportFn [IsCompatiblePairing B]
    (h₁ : Polyhedral C₁) (hne₁ : C₁.Nonempty) (h₂ : Convex ℝ C₂) (hne₂ : C₂.Nonempty) :
    (C₁ ∩ ri C₂).Nonempty ↔
      ∀ y : F, supportFn B C₁ y ≤ -supportFn B C₂ (-y) →
        supportFn B C₁ y = supportFn B C₂ y := by
  rw [← Set.not_disjoint_iff_nonempty_inter,
    ← exists_separates_not_subset_iff_disjoint_relint h₁ h₂ hne₂]
  constructor
  · intro hno y hy
    rw [supportFn_le_neg_supportFn_neg_iff] at hy
    obtain ⟨x₁, hx₁⟩ := hne₁
    obtain ⟨x₂, hx₂⟩ := hne₂
    have hub : supportFn B C₁ y ≤ ((B x₂ y : ℝ) : EReal) :=
      supportFn_le_coe_iff.2 fun z hz => hy z hz x₂ hx₂
    have hnetop : supportFn B C₁ y ≠ ⊤ :=
      ne_top_of_le_ne_top (_root_.EReal.coe_ne_top _) hub
    have hnebot : supportFn B C₁ y ≠ ⊥ := supportFn_ne_bot ⟨x₁, hx₁⟩ y
    have hcoe : (((supportFn B C₁ y).toReal : ℝ) : EReal) = supportFn B C₁ y :=
      _root_.EReal.coe_toReal hnetop hnebot
    have hsep : Separates (evalCLM B y) (supportFn B C₁ y).toReal C₁ C₂ := by
      refine ⟨fun z hz => ?_, fun z hz => ?_⟩
      · have h := le_supportFn (B := B) hz y
        rw [← hcoe] at h
        exact_mod_cast h
      · have h : supportFn B C₁ y ≤ ((B z y : ℝ) : EReal) :=
          supportFn_le_coe_iff.2 fun w hw => hy w hw z hz
        rw [← hcoe] at h
        exact_mod_cast h
    have hsub : C₂ ⊆ {x | evalCLM B y x = (supportFn B C₁ y).toReal} := by
      by_contra hcon
      exact hno ⟨evalCLM B y, (supportFn B C₁ y).toReal, hsep, hcon⟩
    have hval : ∀ z ∈ C₂, B z y = (supportFn B C₁ y).toReal := fun z hz => hsub hz
    have h₂' : supportFn B C₂ y = (((supportFn B C₁ y).toReal : ℝ) : EReal) := by
      refine le_antisymm (supportFn_le_coe_iff.2 fun z hz => le_of_eq (hval z hz)) ?_
      have h := le_supportFn (B := B) hx₂ y
      rwa [hval x₂ hx₂] at h
    rw [h₂', hcoe]
  · rintro hcond ⟨g, c, hsep, hns⟩
    obtain ⟨y, hy⟩ := exists_pairing_eq B g
    have hpt : ∀ x₁ ∈ C₁, ∀ x₂ ∈ C₂, B x₁ y ≤ B x₂ y := by
      intro x₁ hx₁ x₂ hx₂
      have h1 : g x₁ ≤ c := hsep.le_of_mem_left hx₁
      have h2 : c ≤ g x₂ := hsep.le_of_mem_right hx₂
      rw [hy x₁] at h1
      rw [hy x₂] at h2
      linarith
    have heq := hcond y ((supportFn_le_neg_supportFn_neg_iff B C₁ C₂ y).2 hpt)
    obtain ⟨x₂, hx₂C₂, hx₂ne⟩ : ∃ x ∈ C₂, g x ≠ c := by
      by_contra hcon
      push Not at hcon
      exact hns fun x hx => hcon x hx
    have hgt : c < g x₂ := lt_of_le_of_ne (hsep.le_of_mem_right hx₂C₂) (Ne.symm hx₂ne)
    have hle₁ : supportFn B C₁ y ≤ ((c : ℝ) : EReal) :=
      supportFn_le_coe_iff.2 fun z hz => by rw [← hy z]; exact hsep.le_of_mem_left hz
    have hle₂ : ((B x₂ y : ℝ) : EReal) ≤ supportFn B C₂ y := le_supportFn hx₂C₂ y
    rw [heq] at hle₁
    have hcontr : ((B x₂ y : ℝ) : EReal) ≤ ((c : ℝ) : EReal) := hle₂.trans hle₁
    have hfin : B x₂ y ≤ c := by exact_mod_cast hcontr
    rw [← hy x₂] at hfin
    linarith

end SupportFn

end Tdaf.ConvexAnalysis
