/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Mathlib.Analysis.Convex.Caratheodory
import Mathlib.Geometry.Convex.Cone.Pointed
import Mathlib.Analysis.Convex.StdSimplex
import Mathlib.Analysis.Convex.Topology
import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
import Mathlib.Analysis.Normed.Module.FiniteDimension
import Tdaf.Analysis.Convex.Duality.Pairing
import Tdaf.Analysis.Convex.Operations.Hull
import Tdaf.Analysis.Convex.Recession.ConeHull
import Tdaf.Analysis.Convex.Separation

/-!
# Carathéodory: a fixed index, cones, and points with directions

Rockafellar's §17. Mathlib has Carathéodory's theorem in the form `convexHull_eq_union`: every
point of `convexHull 𝕜 s` lies in the convex hull of an *affinely independent* finite subset. What
it does not have is any of the three things Rockafellar actually uses — that `n + 1` points always
suffice with a *fixed* index type; the **conical** form, for the cone generated by a set; and
Theorem 17.2, that the convex hull of a compact set is compact (Mathlib has only
`Set.Finite.isCompact_convexHull`, for finite sets).

## Main results

* `mem_convexHull_iff_exists_fin_finrank_succ` — **Theorem 17.1** for points: membership in
  `convexHull ℝ S` is a convex combination indexed by `Fin (finrank ℝ E + 1)`.
* `exists_linearIndepOn_of_mem_coneHull` — **Carathéodory for convex cones**: a point of the cone
  generated by `S` is a positive combination of a *linearly independent* subset of `S`. This is the
  algebraic core of Rockafellar's Theorem 17.1, the part his proof runs in `R^{n+1}`.
* `exists_card_le_finrank_of_mem_coneHull` — the same with the count `≤ n`.
* `exists_of_mem_convexHull_add_coneHull` — **Theorem 17.1** for points *and directions*: a point of
  `conv P + cone D` uses at most `n + 1` generators in total.
* `IsCompact.isCompact_convexHull` — **Corollary 17.2.1**: the convex hull of a compact set is
  compact.
* `Bornology.IsBounded.closure_convexHull` — **Theorem 17.2**: `cl (conv S) = conv (cl S)` for
  bounded `S`.
* `exists_subset_linearIndepOn_of_sum`, `exists_subset_affineIndependent_of_sum` — the **indexed**
  elimination step: a representation `∑ i ∈ t, w i • v i` is thinned to a sub-*index set* on which
  the generators are linearly (resp. affinely) independent. The affine form carries a real cost
  `∑ i ∈ t, w i * c i` which the thinning is not allowed to increase.
* `exists_coalesced_sum` — Rockafellar's coalescing step: generators drawn from the same member of
  a family of convex sets are merged into their center of mass.
* `exists_affineIndependent_of_mem_convexHull_iUnion` — **Corollary 17.1.1**.
* `exists_linearIndepOn_of_mem_coneHull_iUnion` — **Corollary 17.1.2**.
* `exists_affineIndependent_of_convFn_lt`, `convFn_apply_affineIndependent` — **Corollary 17.1.3**.
* `convHullFn_apply_fin` — **Corollary 17.1.5**: the convex hull of an arbitrary function is
  computed by convex combinations of exactly `n + 1` points, indexed by `Fin (n + 1)`.
* `inequalitySet` and `inequalitySet_subset_halfSpace_iff` — **Theorem 17.3**: which closed
  half-spaces contain the solution set of a compact system of linear inequalities.

## What is not here

**Corollaries 17.1.4 and 17.1.6 are not formalised, and as Rockafellar states them they are
false.** Both assert that the positively homogeneous convex function generated by `conv {fᵢ}` is
computed by an infimum restricted to representations using at most `n` linearly independent
vectors. On `R¹` take `f₁(y) = -y` and `f₂(y) = y`. Then `conv {f₁, f₂} ≡ -∞`, so the generated
function is `-∞` everywhere, while at `x = 1` the only admissible representations use a single
index (`n = 1`) and give the values `-1` and `1`. The elimination that proves Corollary 17.1.3 is
unavailable here for a precise reason: an *affine* dependency has coefficients summing to zero, so
both of its signs have a positive coefficient and the sign may be chosen by the cost, whereas a
*conical* dependency may have all its coefficients of one sign, and then the sign that decreases
the cost cannot be used to eliminate an index. Rockafellar's own proof passes to "a minimal `α'`
on the vertical line", which does not exist when the generated function is improper. The
statements are presumably repairable by assuming the generated function proper; that is not
attempted here.

**Theorem 17.3 needs a hypothesis the book does not state.** Rockafellar's proof of Theorem 17.3
concludes that the origin of `R^{n+1}` is outside `conv (S ∪ {(0, 1)})`, which is false as soon as
the origin is one of the given vectors — and the theorem itself then fails. The counterexample is
recorded with `inequalitySet_subset_halfSpace_iff`, which carries `0 ∉ S`. His other hypothesis,
`x* ≠ 0`, is *not* needed: the empty combination covers `y₀ = 0`.

## Design notes

**The fixed index is what makes compactness available.** With a fixed `Fin (n+1)`,
`convexHull ℝ S` becomes the image of the compact set
`stdSimplex ℝ (Fin (n+1)) ×ˢ (univ.pi fun _ => S)` under the continuous map
`(w, z) ↦ ∑ i, w i • z i`, and Theorem 17.2 is one line. Carathéodory's affinely independent
subset has *at most* `n+1` elements; padding it out to exactly `n+1` — repeating one of its points
with weight zero — is the only real work, and `sum_dite_lt` isolates it.

**Boundedness, not compactness, is Rockafellar's hypothesis in Theorem 17.2**, and the two are the
same thing here only because the ambient space is finite-dimensional: `closure S` is compact
because it is closed and bounded.

**The conical Carathéodory is an induction on a cardinality bound, not on a minimal
representation.** Mathlib's convex version picks a subset of minimum cardinality
(`minCardFinsetOfMemConvexHull`) and derives independence from minimality; here the recursion is
explicit — `exists_linearIndepOn_coneRepr_aux` takes `t.card ≤ n` and either finds `t` independent
or produces a strictly smaller `t'`. The elimination step is Rockafellar's: from a dependency
`∑ μ y • y = 0` normalised so that some `μ y > 0`, subtract `lam = min (w y / μ y)` times the
relation. Every coefficient stays non-negative and the minimising one becomes `0`; the new index set
is `t.filter (0 < w' ·)`, which drops *all* coefficients that vanished, not just the one that was
engineered to.

**Strict positivity, not non-negativity, is the right form of the conclusion.** `0 < w y` on `t`
means the representation carries no dead weight, which is what lets `t.card ≤ finrank` be read off
directly from linear independence, and what makes the split into points and directions in Theorem
17.1 lossless.

**The corollaries need no coalescing after the fact, because the elimination is indexed.**
Rockafellar proves Corollaries 17.1.1–17.1.2 by running Carathéodory on the union of the family and
then merging two generators that happen to come from the same `Cᵢ`, re-establishing independence of
the merged family. Here the merging is done *first* — `exists_coalesced_sum`, one center of mass
per index — and the elimination is then run on the `Finset ι` of indices rather than on a set of
vectors, so it can only ever drop indices. That is why
`exists_subset_linearIndepOn_of_sum`/`exists_subset_affineIndependent_of_sum` are stated for a
family `v : ι → E` and a `Finset ι`, and it is what makes the "different `Cᵢ`" clause free.

**Theorem 17.1 for points and directions is proved in `ℝ × E`, not by a new argument.** `liftPD P D`
is Rockafellar's `S'` — `{1} × P ∪ {0} × D` — and `conv P + cone D` is the level-one slice of the
cone it generates. Applying the conical Carathéodory there and splitting the resulting finite set by
its first coordinate gives the two families at once; the first coordinate of the identity
`∑ w q • q = (1, x)` is exactly the statement that the point weights sum to `1`, and the bound
`n + 1` is `finrank ℝ (ℝ × E)`. The same homogenisation appears as `liftAt`/`slice_hull_union` in
`Polyhedral/Defs.lean`, but §17 must not depend on §19, so the few lines are repeated here.

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §17 (Theorems 17.1,
  17.2, Corollaries 17.1.1, 17.1.2, 17.1.3, 17.1.5, 17.2.1).
-/

open Set

namespace Tdaf.ConvexAnalysis

/-- A sum over `Fin N` of a family cut off after the first `m` indices is a sum over `Fin m`. This
is the padding lemma behind `mem_convexHull_iff_exists_fin_finrank_succ`. -/
theorem sum_ite_lt {M : Type*} [AddCommMonoid M] {m N : ℕ} (h : m ≤ N) (g : Fin N → M) :
    ∑ i : Fin N, (if (i : ℕ) < m then g i else 0) = ∑ j : Fin m, g (Fin.castLE h j) := by
  classical
  rw [← Finset.sum_subset (Finset.subset_univ (Finset.univ.map (Fin.castLEEmb h)))]
  · rw [Finset.sum_map]
    refine Finset.sum_congr rfl fun j _ => ?_
    have hlt : ((Fin.castLEEmb h j : Fin N) : ℕ) < m := j.2
    split
    · rfl
    · exact absurd hlt ‹_›
  · intro i _ hi
    have hnot : ¬ ((i : ℕ) < m) := fun hlt =>
      hi (Finset.mem_map.2 ⟨⟨i, hlt⟩, Finset.mem_univ _, by ext; rfl⟩)
    split
    · exact absurd ‹_› hnot
    · rfl

section Caratheodory

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]

/-- **Rockafellar, Theorem 17.1** for points: a point of `convexHull ℝ S` is a convex combination
of `finrank ℝ E + 1` points of `S`, indexed by a *fixed* type. Repetitions and zero weights are
allowed, which is exactly what turns Carathéodory's "at most `n + 1` points" into a statement about
a fixed index. -/
theorem mem_convexHull_iff_exists_fin_finrank_succ {S : Set E} {x : E} :
    x ∈ convexHull ℝ S ↔ ∃ (w : Fin (Module.finrank ℝ E + 1) → ℝ)
      (z : Fin (Module.finrank ℝ E + 1) → E), (∀ i, 0 ≤ w i) ∧ ∑ i, w i = 1 ∧
      (∀ i, z i ∈ S) ∧ ∑ i, w i • z i = x := by
  classical
  refine ⟨fun hx => ?_, fun ⟨w, z, hw₀, hw₁, hz, hx⟩ =>
    mem_convexHull_of_exists_fintype w z hw₀ hw₁ hz hx⟩
  rw [convexHull_eq_union] at hx
  simp only [Set.mem_iUnion] at hx
  obtain ⟨t, hts, hai, hxt⟩ := hx
  -- Carathéodory's subset has at most `finrank ℝ E + 1` elements
  have hcard : t.card ≤ Module.finrank ℝ E + 1 := by
    have h₁ := hai.card_le_finrank_succ (k := ℝ)
    have h₂ : Module.finrank ℝ (vectorSpan ℝ (Set.range ((↑) : t → E)))
        ≤ Module.finrank ℝ E := Submodule.finrank_le _
    rw [Fintype.card_coe] at h₁
    omega
  -- its convex combination
  rw [Finset.convexHull_eq] at hxt
  obtain ⟨w, hw₀, hw₁, hwx⟩ := hxt
  rw [Finset.centerMass_eq_of_sum_1 _ _ hw₁] at hwx
  have htne : t.Nonempty := by
    rw [Finset.nonempty_iff_ne_empty]
    intro hcon
    rw [hcon, Finset.sum_empty] at hw₁
    exact zero_ne_one hw₁
  have hm0 : 0 < t.card := Finset.card_pos.2 htne
  -- pad the index set out to `Fin (finrank ℝ E + 1)`, repeating the last point with weight zero
  set r : Fin (Module.finrank ℝ E + 1) → Fin t.card :=
    fun i => ⟨min (i : ℕ) (t.card - 1), by omega⟩ with hr
  set zz : Fin (Module.finrank ℝ E + 1) → E := fun i => ((t.equivFin.symm (r i) : E)) with hzz
  set ww : Fin (Module.finrank ℝ E + 1) → ℝ :=
    fun i => if (i : ℕ) < t.card then w (zz i) else 0 with hww
  have hrj : ∀ j : Fin t.card, r (Fin.castLE hcard j) = j := by
    intro j
    have hj := j.2
    refine Fin.ext ?_
    simp only [hr, Fin.val_castLE]
    omega
  have hmemt : ∀ i, zz i ∈ t := by
    intro i
    simpa only [hzz] using (t.equivFin.symm (r i)).2
  refine ⟨ww, zz, ?_, ?_, fun i => hts (hmemt i), ?_⟩
  · intro i
    simp only [hww]
    split
    · exact hw₀ _ (hmemt i)
    · exact le_rfl
  · have hstep : ∑ i, ww i = ∑ j : Fin t.card, w (zz (Fin.castLE hcard j)) := by
      simpa only [hww] using sum_ite_lt hcard fun i => w (zz i)
    rw [hstep]
    have hval : ∀ j : Fin t.card, zz (Fin.castLE hcard j) = ((t.equivFin.symm j : E)) := by
      intro j
      simp only [hzz, hrj j]
    rw [Finset.sum_congr rfl fun j _ => by rw [hval j],
      Fintype.sum_equiv t.equivFin.symm _ (fun y : {y // y ∈ t} => w (y : E)) fun _ => rfl,
      Finset.sum_coe_sort t w]
    exact hw₁
  · have hprod : ∀ i, ww i • zz i = if (i : ℕ) < t.card then w (zz i) • zz i else 0 := by
      intro i
      simp only [hww]
      split <;> simp
    rw [Finset.sum_congr rfl fun i _ => hprod i,
      sum_ite_lt hcard fun i => w (zz i) • zz i]
    have hval : ∀ j : Fin t.card, zz (Fin.castLE hcard j) = ((t.equivFin.symm j : E)) := by
      intro j
      simp only [hzz, hrj j]
    rw [Finset.sum_congr rfl fun j _ => by rw [hval j],
      Fintype.sum_equiv t.equivFin.symm _
        (fun y : {y // y ∈ t} => w (y : E) • (y : E)) fun _ => rfl,
      Finset.sum_coe_sort t fun y => w y • y]
    exact hwx

/-- **Rockafellar, Corollary 17.2.1.** The convex hull of a compact set is compact: it is the image
of `stdSimplex × Sⁿ⁺¹` under `(w, z) ↦ ∑ wᵢ zᵢ`. Mathlib has this only for *finite* sets
(`Set.Finite.isCompact_convexHull`). -/
theorem IsCompact.isCompact_convexHull {S : Set E} (hS : IsCompact S) :
    IsCompact (convexHull ℝ S) := by
  classical
  have hT : IsCompact (stdSimplex ℝ (Fin (Module.finrank ℝ E + 1)) ×ˢ
      (Set.univ.pi fun _ : Fin (Module.finrank ℝ E + 1) => S)) :=
    IsCompact.prod (isCompact_stdSimplex (𝕜 := ℝ) _) (isCompact_univ_pi fun _ => hS)
  have hcont : Continuous fun p : (Fin (Module.finrank ℝ E + 1) → ℝ) ×
      (Fin (Module.finrank ℝ E + 1) → E) => ∑ i, p.1 i • p.2 i :=
    continuous_finsetSum _ fun i _ =>
      ((continuous_apply i).comp continuous_fst).smul ((continuous_apply i).comp continuous_snd)
  have himg : convexHull ℝ S = (fun p : (Fin (Module.finrank ℝ E + 1) → ℝ) ×
      (Fin (Module.finrank ℝ E + 1) → E) => ∑ i, p.1 i • p.2 i) ''
      (stdSimplex ℝ (Fin (Module.finrank ℝ E + 1)) ×ˢ
        (Set.univ.pi fun _ : Fin (Module.finrank ℝ E + 1) => S)) := by
    ext x
    constructor
    · intro hx
      obtain ⟨w, z, hw₀, hw₁, hz, hwz⟩ := mem_convexHull_iff_exists_fin_finrank_succ.1 hx
      exact ⟨(w, z), ⟨⟨fun i => hw₀ i, hw₁⟩, fun i _ => hz i⟩, hwz⟩
    · rintro ⟨⟨w, z⟩, ⟨hw, hz⟩, rfl⟩
      exact mem_convexHull_of_exists_fintype w z hw.1 hw.2 (fun i => hz i (Set.mem_univ i)) rfl
  rw [himg]
  exact IsCompact.image hT hcont

/-- **Rockafellar, Theorem 17.2.** For a bounded set the closure and the convex hull commute. -/
theorem Bornology.IsBounded.closure_convexHull {S : Set E} (hS : Bornology.IsBounded S) :
    closure (convexHull ℝ S) = convexHull ℝ (closure S) := by
  have hcl : IsCompact (closure S) :=
    Metric.isCompact_of_isClosed_isBounded isClosed_closure hS.closure
  refine subset_antisymm ?_ ?_
  · exact closure_minimal (convexHull_mono subset_closure)
      (IsCompact.isClosed (IsCompact.isCompact_convexHull hcl))
  · exact convexHull_min (closure_mono (subset_convexHull ℝ S))
      (Convex.closure (convex_convexHull ℝ S))

end Caratheodory

/-! ### Carathéodory for convex cones -/

section Cone

variable {E : Type*} [AddCommGroup E] [Module ℝ E]

/-- The engine of the conical form of Carathéodory's theorem, as an induction on a cardinality
bound. A conical representation over a linearly *dependent* finite set can always be replaced by
one over a strictly smaller set: subtract a multiple of the dependency relation, chosen just large
enough to drive one positive coefficient to zero. -/
private theorem exists_linearIndepOn_coneRepr_aux {S : Set E} :
    ∀ (n : ℕ) (t : Finset E), t.card ≤ n → ↑t ⊆ S → ∀ w : E → ℝ, (∀ y ∈ t, 0 < w y) →
      ∃ (t' : Finset E) (w' : E → ℝ), ↑t' ⊆ S ∧ (∀ y ∈ t', 0 < w' y) ∧
        LinearIndepOn ℝ id (t' : Set E) ∧ ∑ y ∈ t', w' y • y = ∑ y ∈ t, w y • y := by
  classical
  intro n
  induction n with
  | zero =>
    intro t hcard hts w hw
    have ht : t = ∅ := Finset.card_eq_zero.1 (Nat.le_zero.1 hcard)
    subst ht
    exact ⟨∅, w, by simp, by simp, by simp, rfl⟩
  | succ n ih =>
    intro t hcard hts w hw
    by_cases hli : LinearIndepOn ℝ id (t : Set E)
    · exact ⟨t, w, hts, hw, hli, rfl⟩
    -- a non-trivial linear relation supported inside `t`
    obtain ⟨fr, hfsupp, hfsum, hfne⟩ := linearDepOn_iff.1 hli
    rw [Finsupp.mem_supported] at hfsupp
    simp only [id_eq] at hfsum
    have hsub : fr.support ⊆ t := by
      intro y hy
      exact_mod_cast hfsupp hy
    have hνsum : ∑ y ∈ t, fr y • y = 0 := by
      rw [← Finset.sum_subset hsub fun y _ hy => by
        rw [Finsupp.notMem_support_iff.1 hy, zero_smul]]
      exact hfsum
    obtain ⟨y₂, hy₂⟩ := Finsupp.support_nonempty_iff.2 hfne
    have hy₂t : y₂ ∈ t := hsub hy₂
    have hy₂ne : fr y₂ ≠ 0 := Finsupp.mem_support_iff.1 hy₂
    -- normalise the relation so that one coefficient is strictly positive
    obtain ⟨mu, hmusum, y₀, hy₀t, hy₀pos⟩ :
        ∃ mu : E → ℝ, (∑ y ∈ t, mu y • y = 0) ∧ ∃ y₀ ∈ t, 0 < mu y₀ := by
      rcases lt_or_gt_of_ne hy₂ne with hneg | hpos
      · refine ⟨fun y => -fr y, ?_, y₂, hy₂t, by linarith⟩
        simp only [neg_smul, Finset.sum_neg_distrib, hνsum, neg_zero]
      · exact ⟨fun y => fr y, hνsum, y₂, hy₂t, hpos⟩
    -- the largest multiple of the relation that keeps every coefficient non-negative
    set Pos : Finset E := t.filter (fun y => 0 < mu y) with hPosdef
    have hPosne : Pos.Nonempty := ⟨y₀, by simp [hPosdef, hy₀t, hy₀pos]⟩
    obtain ⟨y₁, hy₁Pos, hy₁min⟩ := Finset.exists_min_image Pos (fun y => w y / mu y) hPosne
    have hy₁t : y₁ ∈ t := (Finset.mem_filter.1 hy₁Pos).1
    have hy₁mu : 0 < mu y₁ := (Finset.mem_filter.1 hy₁Pos).2
    set lam : ℝ := w y₁ / mu y₁ with hlamdef
    have hlampos : 0 < lam := div_pos (hw y₁ hy₁t) hy₁mu
    set w' : E → ℝ := fun y => w y - lam * mu y with hw'def
    have hw'nonneg : ∀ y ∈ t, 0 ≤ w' y := by
      intro y hy
      by_cases hmy : 0 < mu y
      · have hmem : y ∈ Pos := by simp [hPosdef, hy, hmy]
        have hdiv := hy₁min y hmem
        have hmul : lam * mu y ≤ w y := (le_div_iff₀ hmy).1 hdiv
        simp only [hw'def]
        linarith
      · push Not at hmy
        have hle : lam * mu y ≤ 0 := mul_nonpos_of_nonneg_of_nonpos hlampos.le hmy
        have hwy := hw y hy
        simp only [hw'def]
        linarith
    have hw'y₁ : w' y₁ = 0 := by
      simp only [hw'def, hlamdef]
      rw [div_mul_cancel₀ _ hy₁mu.ne']
      ring
    have hsum' : ∑ y ∈ t, w' y • y = ∑ y ∈ t, w y • y := by
      have hsplit : ∑ y ∈ t, w' y • y
          = (∑ y ∈ t, w y • y) - lam • ∑ y ∈ t, mu y • y := by
        rw [Finset.smul_sum, ← Finset.sum_sub_distrib]
        refine Finset.sum_congr rfl fun y _ => ?_
        simp only [hw'def, sub_smul, smul_smul]
      rw [hsplit, hmusum, smul_zero, sub_zero]
    -- drop the coefficients that have become zero
    set t' : Finset E := t.filter (fun y => 0 < w' y) with ht'def
    have ht'sub : t' ⊆ t := Finset.filter_subset _ _
    have ht'pos : ∀ y ∈ t', 0 < w' y := fun y hy => (Finset.mem_filter.1 hy).2
    have ht'sum : ∑ y ∈ t', w' y • y = ∑ y ∈ t, w' y • y := by
      refine Finset.sum_subset ht'sub fun y hy hy' => ?_
      have hnp : ¬ (0 < w' y) := fun h => hy' (Finset.mem_filter.2 ⟨hy, h⟩)
      have h0 : w' y = 0 := le_antisymm (not_lt.1 hnp) (hw'nonneg y hy)
      rw [h0, zero_smul]
    have hy₁notin : y₁ ∉ t' := by
      simp [ht'def, hw'y₁]
    have ht'card : t'.card ≤ n := by
      have hss : t' ⊆ t.erase y₁ := fun y hy =>
        Finset.mem_erase.2 ⟨fun h => hy₁notin (h ▸ hy), ht'sub hy⟩
      have h1 := Finset.card_le_card hss
      rw [Finset.card_erase_of_mem hy₁t] at h1
      have h2 : 0 < t.card := Finset.card_pos.2 ⟨y₁, hy₁t⟩
      omega
    obtain ⟨t'', w'', hts'', hpos'', hli'', hsum''⟩ :=
      ih t' ht'card (fun y hy => hts (ht'sub (by exact_mod_cast hy))) w' ht'pos
    exact ⟨t'', w'', hts'', hpos'', hli'', by rw [hsum'', ht'sum, hsum']⟩

/-- **Carathéodory's theorem for convex cones.** A point of the cone generated by `S` is a
non-negative combination of a *linearly independent* finite subset of `S`, with strictly positive
coefficients.

This is the algebraic core of Rockafellar's Theorem 17.1 — the part his proof carries out in
`R^{n+1}` — and Mathlib does not have it: `Analysis/Convex/Caratheodory.lean` covers only the
convex hull. -/
theorem exists_linearIndepOn_of_mem_coneHull {S : Set E} {x : E}
    (hx : x ∈ PointedCone.hull ℝ S) :
    ∃ (t : Finset E) (w : E → ℝ), ↑t ⊆ S ∧ (∀ y ∈ t, 0 < w y) ∧
      LinearIndepOn ℝ id (t : Set E) ∧ ∑ y ∈ t, w y • y = x := by
  classical
  obtain ⟨c, hcs, hc0, hcx⟩ := PointedCone.mem_hull_set.1 hx
  have hpos : ∀ y ∈ c.support, 0 < c y := fun y hy =>
    lt_of_le_of_ne (hc0 y) (Ne.symm (Finsupp.mem_support_iff.1 hy))
  obtain ⟨t, w, hts, hw, hli, hsum⟩ :=
    exists_linearIndepOn_coneRepr_aux c.support.card c.support le_rfl hcs c hpos
  exact ⟨t, w, hts, hw, hli, by rw [hsum]; exact hcx⟩

variable [FiniteDimensional ℝ E]

/-- The conical Carathéodory bound: `n` generators suffice, where `n = dim E`. -/
theorem exists_card_le_finrank_of_mem_coneHull {S : Set E} {x : E}
    (hx : x ∈ PointedCone.hull ℝ S) :
    ∃ (t : Finset E) (w : E → ℝ), ↑t ⊆ S ∧ (∀ y ∈ t, 0 < w y) ∧
      t.card ≤ Module.finrank ℝ E ∧ ∑ y ∈ t, w y • y = x := by
  obtain ⟨t, w, hts, hw, hli, hsum⟩ := exists_linearIndepOn_of_mem_coneHull hx
  exact ⟨t, w, hts, hw, LinearIndependent.finset_card_le_finrank hli, hsum⟩

end Cone

/-! ### Theorem 17.1 for points and directions -/

section LiftPD

variable {E : Type*}

/-- The homogenisation of a set of points and directions: `P` is lifted to height `1` and `D` to
height `0` in `ℝ × E`. Rockafellar's `S'`. -/
def liftPD (P D : Set E) : Set (ℝ × E) :=
  (fun y : E => ((1 : ℝ), y)) '' P ∪ (fun y : E => ((0 : ℝ), y)) '' D

/-- A point of `P` sits at height `1` in `liftPD P D`. -/
theorem mem_liftPD_one {P D : Set E} {y : E} (hy : y ∈ P) :
    ((1 : ℝ), y) ∈ liftPD P D := Or.inl ⟨y, hy, rfl⟩

/-- A direction of `D` sits at height `0` in `liftPD P D`. -/
theorem mem_liftPD_zero {P D : Set E} {y : E} (hy : y ∈ D) :
    ((0 : ℝ), y) ∈ liftPD P D := Or.inr ⟨y, hy, rfl⟩

/-- Every element of `liftPD P D` sits at height `1` or at height `0`. -/
theorem fst_eq_or_of_mem_liftPD {P D : Set E} {q : ℝ × E} (hq : q ∈ liftPD P D) :
    q.1 = 1 ∨ q.1 = 0 := by
  rcases hq with ⟨y, _, rfl⟩ | ⟨y, _, rfl⟩
  · exact Or.inl rfl
  · exact Or.inr rfl

/-- An element of `liftPD P D` at height `1` is a point of `P`. -/
theorem mem_of_mem_liftPD_of_fst_eq_one {P D : Set E} {q : ℝ × E}
    (hq : q ∈ liftPD P D) (h1 : q.1 = 1) : q.2 ∈ P := by
  rcases hq with ⟨y, hy, rfl⟩ | ⟨y, _, rfl⟩
  · exact hy
  · exact absurd h1 (by norm_num)

/-- An element of `liftPD P D` at height `0` is a direction of `D`. -/
theorem mem_of_mem_liftPD_of_fst_eq_zero {P D : Set E} {q : ℝ × E}
    (hq : q ∈ liftPD P D) (h0 : q.1 = 0) : q.2 ∈ D := by
  rcases hq with ⟨y, _, rfl⟩ | ⟨y, hy, rfl⟩
  · exact absurd h0 (by norm_num)
  · exact hy

end LiftPD

section PointsDirections

open scoped Pointwise

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]

private theorem lift_mem_coneHull_liftPD {P D : Set E} {x : E}
    (hx : x ∈ convexHull ℝ P + (PointedCone.hull ℝ D : Set E)) :
    ((1 : ℝ), x) ∈ PointedCone.hull ℝ (liftPD P D) := by
  classical
  obtain ⟨u, hu, v, hv, huv⟩ := hx
  have h1u : ((1 : ℝ), u) ∈ PointedCone.hull ℝ (liftPD P D) := by
    obtain ⟨ww, zz, hw0, hw1, hzP, hzu⟩ := mem_convexHull_iff_exists_fin_finrank_succ.1 hu
    have hrepr : ((1 : ℝ), u) = ∑ i, ww i • (((1 : ℝ), zz i) : ℝ × E) := by
      refine Prod.ext ?_ ?_
      · simp [Prod.fst_sum, hw1]
      · simp [Prod.snd_sum, hzu]
    rw [hrepr]
    refine Submodule.sum_mem _ fun i _ => ?_
    exact Submodule.smul_mem _ (⟨ww i, hw0 i⟩ : {c : ℝ // 0 ≤ c})
      (PointedCone.subset_hull (mem_liftPD_one (D := D) (hzP i)))
  have h0v : ((0 : ℝ), v) ∈ PointedCone.hull ℝ (liftPD P D) := by
    obtain ⟨c, hcD, hc0, hcv⟩ := PointedCone.mem_hull_set.1 hv
    have hrepr : ((0 : ℝ), v) = ∑ y ∈ c.support, c y • (((0 : ℝ), y) : ℝ × E) := by
      refine Prod.ext ?_ ?_
      · simp [Prod.fst_sum]
      · simpa [Prod.snd_sum, Finsupp.sum] using hcv.symm
    rw [hrepr]
    refine Submodule.sum_mem _ fun y hy => ?_
    exact Submodule.smul_mem _ (⟨c y, hc0 y⟩ : {c : ℝ // 0 ≤ c})
      (PointedCone.subset_hull (mem_liftPD_zero (P := P) (hcD hy)))
  have hsplit : ((1 : ℝ), x) = ((1 : ℝ), u) + ((0 : ℝ), v) := by
    rw [← huv]
    refine Prod.ext ?_ ?_ <;> simp
  rw [hsplit]
  exact Submodule.add_mem _ h1u h0v

/-- **Rockafellar, Theorem 17.1**, points and directions. A point of `conv P + cone D` — the convex
hull of the set of points `P` together with the set of directions `D` — is a convex combination of
points of `P` plus a non-negative combination of directions of `D`, using **at most `n + 1`
generators in total**, where `n = dim E`, all with strictly positive coefficients.

Rockafellar's proof exactly: homogenise to `ℝ × E`, where `conv P + cone D` is the level-one slice
of the convex cone generated by `{1} × P ∪ {0} × D`, and apply the conical Carathéodory theorem
`exists_linearIndepOn_of_mem_coneHull` there. Linear independence in `ℝ × E` is what produces the
bound `n + 1`, and the first coordinate of the resulting identity is what makes the point weights
sum to `1`. -/
theorem exists_of_mem_convexHull_add_coneHull {P D : Set E} {x : E}
    (hx : x ∈ convexHull ℝ P + (PointedCone.hull ℝ D : Set E)) :
    ∃ (p d : Finset E) (a b : E → ℝ), ↑p ⊆ P ∧ ↑d ⊆ D ∧
      (∀ y ∈ p, 0 < a y) ∧ (∀ y ∈ d, 0 < b y) ∧ ∑ y ∈ p, a y = 1 ∧
      p.card + d.card ≤ Module.finrank ℝ E + 1 ∧
      (∑ y ∈ p, a y • y) + ∑ y ∈ d, b y • y = x := by
  classical
  obtain ⟨t, w, hts, hw, hli, hsum⟩ :=
    exists_linearIndepOn_of_mem_coneHull (lift_mem_coneHull_liftPD hx)
  -- the total number of generators is bounded by `dim (ℝ × E) = n + 1`
  have hcard : t.card ≤ Module.finrank ℝ E + 1 := by
    have h := LinearIndependent.finset_card_le_finrank hli
    rwa [Module.finrank_prod, Module.finrank_self, add_comm] at h
  have ht01 : ∀ q ∈ t, q.1 = 1 ∨ q.1 = 0 := fun q hq =>
    fst_eq_or_of_mem_liftPD (hts (by exact_mod_cast hq))
  set t₁ : Finset (ℝ × E) := t.filter (fun q => q.1 = 1) with ht₁def
  set t₀ : Finset (ℝ × E) := t.filter (fun q => q.1 = 0) with ht₀def
  have hdisj : Disjoint t₁ t₀ := by
    rw [Finset.disjoint_left]
    intro q hq hq'
    have h1 := (Finset.mem_filter.1 hq).2
    have h0 := (Finset.mem_filter.1 hq').2
    rw [h1] at h0
    norm_num at h0
  have hunion : t₁ ∪ t₀ = t := by
    refine Finset.Subset.antisymm
      (Finset.union_subset (Finset.filter_subset _ _) (Finset.filter_subset _ _)) fun q hq => ?_
    rcases ht01 q hq with h | h
    · exact Finset.mem_union_left _ (Finset.mem_filter.2 ⟨hq, h⟩)
    · exact Finset.mem_union_right _ (Finset.mem_filter.2 ⟨hq, h⟩)
  have hcardsplit : t₁.card + t₀.card = t.card := by
    rw [← Finset.card_union_of_disjoint hdisj, hunion]
  -- the two coordinate identities
  have hfst : ∑ q ∈ t, w q * q.1 = 1 := by
    simpa [Prod.fst_sum, Prod.smul_fst, smul_eq_mul] using congrArg Prod.fst hsum
  have hsnd : ∑ q ∈ t, w q • q.2 = x := by
    simpa [Prod.snd_sum, Prod.smul_snd] using congrArg Prod.snd hsum
  -- `Prod.snd` is injective on each of the two pieces
  have hinj₁ : ∀ q ∈ t₁, ∀ q' ∈ t₁, q.2 = q'.2 → q = q' := by
    intro q hq q' hq' h
    exact Prod.ext (by rw [(Finset.mem_filter.1 hq).2, (Finset.mem_filter.1 hq').2]) h
  have hinj₀ : ∀ q ∈ t₀, ∀ q' ∈ t₀, q.2 = q'.2 → q = q' := by
    intro q hq q' hq' h
    exact Prod.ext (by rw [(Finset.mem_filter.1 hq).2, (Finset.mem_filter.1 hq').2]) h
  have hinjOn₁ : Set.InjOn Prod.snd ↑t₁ := fun q hq q' hq' h =>
    hinj₁ q (by exact_mod_cast hq) q' (by exact_mod_cast hq') h
  have hinjOn₀ : Set.InjOn Prod.snd ↑t₀ := fun q hq q' hq' h =>
    hinj₀ q (by exact_mod_cast hq) q' (by exact_mod_cast hq') h
  have heq₁ : ∀ q ∈ t₁, ((1 : ℝ), q.2) = q := fun q hq =>
    Prod.ext (Finset.mem_filter.1 hq).2.symm rfl
  have heq₀ : ∀ q ∈ t₀, ((0 : ℝ), q.2) = q := fun q hq =>
    Prod.ext (Finset.mem_filter.1 hq).2.symm rfl
  refine ⟨t₁.image Prod.snd, t₀.image Prod.snd, fun y => w ((1 : ℝ), y), fun y => w ((0 : ℝ), y),
    ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · intro y hy
    simp only [Finset.coe_image, Set.mem_image, Finset.mem_coe] at hy
    obtain ⟨q, hq, rfl⟩ := hy
    exact mem_of_mem_liftPD_of_fst_eq_one (hts (Finset.filter_subset _ _ hq))
      (Finset.mem_filter.1 hq).2
  · intro y hy
    simp only [Finset.coe_image, Set.mem_image, Finset.mem_coe] at hy
    obtain ⟨q, hq, rfl⟩ := hy
    exact mem_of_mem_liftPD_of_fst_eq_zero (hts (Finset.filter_subset _ _ hq))
      (Finset.mem_filter.1 hq).2
  · intro y hy
    obtain ⟨q, hq, rfl⟩ := Finset.mem_image.1 hy
    change 0 < w ((1 : ℝ), q.2)
    rw [heq₁ q hq]
    exact hw q (Finset.filter_subset _ _ hq)
  · intro y hy
    obtain ⟨q, hq, rfl⟩ := Finset.mem_image.1 hy
    change 0 < w ((0 : ℝ), q.2)
    rw [heq₀ q hq]
    exact hw q (Finset.filter_subset _ _ hq)
  · change ∑ y ∈ t₁.image Prod.snd, w ((1 : ℝ), y) = 1
    have hA : ∑ y ∈ t₁.image Prod.snd, w ((1 : ℝ), y) = ∑ q ∈ t₁, w q := by
      rw [Finset.sum_image hinj₁]
      refine Finset.sum_congr rfl fun q hq => ?_
      rw [heq₁ q hq]
    have hz : ∑ q ∈ t₀, w q * q.1 = 0 :=
      Finset.sum_eq_zero fun q hq => by rw [(Finset.mem_filter.1 hq).2, mul_zero]
    have h1 : ∑ q ∈ t₁, w q * q.1 = ∑ q ∈ t₁, w q :=
      Finset.sum_congr rfl fun q hq => by rw [(Finset.mem_filter.1 hq).2, mul_one]
    have hall : ∑ q ∈ t₁, w q * q.1 + ∑ q ∈ t₀, w q * q.1 = ∑ q ∈ t, w q * q.1 := by
      rw [← Finset.sum_union hdisj, hunion]
    rw [hA, ← h1]
    calc ∑ q ∈ t₁, w q * q.1
        = ∑ q ∈ t₁, w q * q.1 + ∑ q ∈ t₀, w q * q.1 := by rw [hz, add_zero]
      _ = ∑ q ∈ t, w q * q.1 := hall
      _ = 1 := hfst
  · rw [Finset.card_image_of_injOn hinjOn₁, Finset.card_image_of_injOn hinjOn₀, hcardsplit]
    exact hcard
  · change (∑ y ∈ t₁.image Prod.snd, w ((1 : ℝ), y) • y)
      + ∑ y ∈ t₀.image Prod.snd, w ((0 : ℝ), y) • y = x
    have hB : ∑ y ∈ t₁.image Prod.snd, w ((1 : ℝ), y) • y = ∑ q ∈ t₁, w q • q.2 := by
      rw [Finset.sum_image hinj₁]
      refine Finset.sum_congr rfl fun q hq => ?_
      rw [heq₁ q hq]
    have hC : ∑ y ∈ t₀.image Prod.snd, w ((0 : ℝ), y) • y = ∑ q ∈ t₀, w q • q.2 := by
      rw [Finset.sum_image hinj₀]
      refine Finset.sum_congr rfl fun q hq => ?_
      rw [heq₀ q hq]
    rw [hB, hC, ← Finset.sum_union hdisj, hunion]
    exact hsnd

end PointsDirections


/-! ### Generators drawn from distinct members of a family

Rockafellar's Corollaries 17.1.1–17.1.3 all sharpen Carathéodory's theorem by insisting that the
generators come from *different* members of a family. The whole content is the elimination step
below, run on an **index set** rather than on a set of vectors: a representation
`x = ∑ i ∈ t, w i • v i` indexed by `t : Finset ι` already carries at most one generator per index,
so no coalescing is needed afterwards — what has to be arranged is that the elimination never
merges two indices, and that is automatic once the representation is phrased this way. -/

section Indexed

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {ι : Type*}

/-- The elimination step behind Corollaries 17.1.1–17.1.3, run on an index set and carrying a real
cost `c` that is not allowed to increase.

`hpick` is the only place the conical and the affine applications differ. It asks that every
non-trivial dependency among the `v i` be normalisable so that *some* coefficient is positive
**and** the cost does not increase. For a conical representation the cost is taken to be `0` and
only the sign of a coefficient matters; for an affine one the coefficients of a dependency sum to
zero, so a positive coefficient is automatic and the sign may be chosen by the cost. -/
private theorem exists_subset_linearIndepOn_aux (v : ι → E) (c : ι → ℝ)
    (hpick : ∀ (s : Finset ι) (mu : ι → ℝ), (∑ i ∈ s, mu i • v i = 0) → (∃ i ∈ s, mu i ≠ 0) →
      ∃ nu : ι → ℝ, (∑ i ∈ s, nu i • v i = 0) ∧ (∃ i ∈ s, 0 < nu i) ∧
        0 ≤ ∑ i ∈ s, nu i * c i) :
    ∀ (n : ℕ) (t : Finset ι), t.card ≤ n → ∀ w : ι → ℝ, (∀ i ∈ t, 0 < w i) →
      ∃ (t₂ : Finset ι) (w₂ : ι → ℝ), t₂ ⊆ t ∧ (∀ i ∈ t₂, 0 < w₂ i) ∧
        LinearIndepOn ℝ v (t₂ : Set ι) ∧
        ∑ i ∈ t₂, w₂ i • v i = ∑ i ∈ t, w i • v i ∧
        ∑ i ∈ t₂, w₂ i * c i ≤ ∑ i ∈ t, w i * c i := by
  classical
  intro n
  induction n with
  | zero =>
    intro t hcard w hw
    have ht : t = (∅ : Finset ι) := Finset.card_eq_zero.1 (Nat.le_zero.1 hcard)
    subst ht
    refine ⟨∅, w, Finset.Subset.refl _, by simp, ?_, rfl, le_rfl⟩
    simp
  | succ n ih =>
    intro t hcard w hw
    by_cases hli : LinearIndepOn ℝ v (t : Set ι)
    · exact ⟨t, w, Finset.Subset.refl _, hw, hli, rfl, le_rfl⟩
    obtain ⟨fr, hfsupp, hfsum, hfne⟩ := linearDepOn_iff.1 hli
    rw [Finsupp.mem_supported] at hfsupp
    have hsub : fr.support ⊆ t := fun i hi => by exact_mod_cast hfsupp hi
    have hfrt : ∑ i ∈ t, fr i • v i = 0 := by
      rw [← Finset.sum_subset hsub fun i _ hi => by
        rw [Finsupp.notMem_support_iff.1 hi, zero_smul]]
      exact hfsum
    obtain ⟨i₂, hi₂⟩ := Finsupp.support_nonempty_iff.2 hfne
    obtain ⟨mu, hmusum, ⟨y₀, hy₀t, hy₀pos⟩, hmuc⟩ :=
      hpick t (fun i => fr i) hfrt ⟨i₂, hsub hi₂, Finsupp.mem_support_iff.1 hi₂⟩
    set Pos : Finset ι := t.filter (fun i => 0 < mu i) with hPosdef
    have hPosne : Pos.Nonempty := ⟨y₀, by simp [hPosdef, hy₀t, hy₀pos]⟩
    obtain ⟨y₁, hy₁Pos, hy₁min⟩ := Finset.exists_min_image Pos (fun i => w i / mu i) hPosne
    have hy₁t : y₁ ∈ t := (Finset.mem_filter.1 hy₁Pos).1
    have hy₁mu : 0 < mu y₁ := (Finset.mem_filter.1 hy₁Pos).2
    set lam : ℝ := w y₁ / mu y₁ with hlamdef
    have hlampos : 0 < lam := div_pos (hw y₁ hy₁t) hy₁mu
    set w₂ : ι → ℝ := fun i => w i - lam * mu i with hw₂def
    have hw₂nonneg : ∀ i ∈ t, 0 ≤ w₂ i := by
      intro i hi
      by_cases hmi : 0 < mu i
      · have hmem : i ∈ Pos := by simp [hPosdef, hi, hmi]
        have hmul : lam * mu i ≤ w i := (le_div_iff₀ hmi).1 (hy₁min i hmem)
        simp only [hw₂def]
        linarith
      · push Not at hmi
        have hle : lam * mu i ≤ 0 := mul_nonpos_of_nonneg_of_nonpos hlampos.le hmi
        have hwi := hw i hi
        simp only [hw₂def]
        linarith
    have hw₂y₁ : w₂ y₁ = 0 := by
      simp only [hw₂def, hlamdef]
      rw [div_mul_cancel₀ _ hy₁mu.ne']
      ring
    have hsumv : ∑ i ∈ t, w₂ i • v i = ∑ i ∈ t, w i • v i := by
      have hsplit : ∑ i ∈ t, w₂ i • v i = (∑ i ∈ t, w i • v i) - lam • ∑ i ∈ t, mu i • v i := by
        rw [Finset.smul_sum, ← Finset.sum_sub_distrib]
        refine Finset.sum_congr rfl fun i _ => ?_
        simp only [hw₂def, sub_smul, smul_smul]
      rw [hsplit, hmusum, smul_zero, sub_zero]
    have hsumc : ∑ i ∈ t, w₂ i * c i ≤ ∑ i ∈ t, w i * c i := by
      have hsplit : ∑ i ∈ t, w₂ i * c i
          = (∑ i ∈ t, w i * c i) - lam * ∑ i ∈ t, mu i * c i := by
        rw [Finset.mul_sum, ← Finset.sum_sub_distrib]
        refine Finset.sum_congr rfl fun i _ => ?_
        simp only [hw₂def]
        ring
      have hnn : 0 ≤ lam * ∑ i ∈ t, mu i * c i := mul_nonneg hlampos.le hmuc
      rw [hsplit]
      linarith
    set t₂ : Finset ι := t.filter (fun i => 0 < w₂ i) with ht₂def
    have ht₂sub : t₂ ⊆ t := Finset.filter_subset _ _
    have ht₂pos : ∀ i ∈ t₂, 0 < w₂ i := fun i hi => (Finset.mem_filter.1 hi).2
    have hzero : ∀ i ∈ t, i ∉ t₂ → w₂ i = 0 := by
      intro i hi hi₂
      have hnp : ¬ (0 < w₂ i) := fun h => hi₂ (Finset.mem_filter.2 ⟨hi, h⟩)
      exact le_antisymm (not_lt.1 hnp) (hw₂nonneg i hi)
    have ht₂sumv : ∑ i ∈ t₂, w₂ i • v i = ∑ i ∈ t, w₂ i • v i :=
      Finset.sum_subset ht₂sub fun i hi hi₂ => by rw [hzero i hi hi₂, zero_smul]
    have ht₂sumc : ∑ i ∈ t₂, w₂ i * c i = ∑ i ∈ t, w₂ i * c i :=
      Finset.sum_subset ht₂sub fun i hi hi₂ => by rw [hzero i hi hi₂, zero_mul]
    have hy₁notin : y₁ ∉ t₂ := by simp [ht₂def, hw₂y₁]
    have ht₂card : t₂.card ≤ n := by
      have hss : t₂ ⊆ t.erase y₁ := fun i hi =>
        Finset.mem_erase.2 ⟨fun h => hy₁notin (h ▸ hi), ht₂sub hi⟩
      have h1 := Finset.card_le_card hss
      rw [Finset.card_erase_of_mem hy₁t] at h1
      have h2 : 0 < t.card := Finset.card_pos.2 ⟨y₁, hy₁t⟩
      omega
    obtain ⟨t₃, w₃, ht₃sub, ht₃pos, ht₃li, ht₃v, ht₃c⟩ := ih t₂ ht₂card w₂ ht₂pos
    refine ⟨t₃, w₃, ht₃sub.trans ht₂sub, ht₃pos, ht₃li, ?_, ?_⟩
    · rw [ht₃v, ht₂sumv, hsumv]
    · exact le_trans (le_trans ht₃c (le_of_eq ht₂sumc)) hsumc

/-- A family of reals summing to zero over a `Finset`, not identically zero there, has a strictly
positive member. This is what makes the sign of an *affine* dependency free to choose. -/
theorem exists_pos_of_sum_eq_zero {s : Finset ι} {g : ι → ℝ} (hsum : ∑ i ∈ s, g i = 0)
    (hne : ∃ i ∈ s, g i ≠ 0) : ∃ i ∈ s, 0 < g i := by
  by_contra hcon
  push Not at hcon
  obtain ⟨i, his, hi⟩ := hne
  exact hi ((Finset.sum_eq_zero_iff_of_nonpos fun j hj => hcon j hj).1 hsum i his)

/-- **Carathéodory's elimination, indexed, conical form.** A non-negative combination
`∑ i ∈ t, w i • v i` can be thinned to a sub-*index set* on which the `v i` are linearly
independent, keeping the value and strict positivity of the coefficients.

Because the index set only shrinks, at most one generator is used per index — which is exactly the
"each belonging to a different `Cᵢ`" clause of Rockafellar's Corollary 17.1.2. -/
theorem exists_subset_linearIndepOn_of_sum (v : ι → E) (t : Finset ι) (w : ι → ℝ)
    (hw : ∀ i ∈ t, 0 < w i) :
    ∃ (t' : Finset ι) (w' : ι → ℝ), t' ⊆ t ∧ (∀ i ∈ t', 0 < w' i) ∧
      LinearIndepOn ℝ v (t' : Set ι) ∧ ∑ i ∈ t', w' i • v i = ∑ i ∈ t, w i • v i := by
  have hpick : ∀ (s : Finset ι) (mu : ι → ℝ), (∑ i ∈ s, mu i • v i = 0) →
      (∃ i ∈ s, mu i ≠ 0) → ∃ nu : ι → ℝ, (∑ i ∈ s, nu i • v i = 0) ∧ (∃ i ∈ s, 0 < nu i) ∧
        0 ≤ ∑ i ∈ s, nu i * (0 : ℝ) := by
    rintro s mu hsum ⟨i₀, hi₀s, hi₀⟩
    rcases lt_or_gt_of_ne hi₀ with hneg | hpos
    · refine ⟨fun i => -mu i, ?_, ⟨i₀, hi₀s, by linarith⟩, by simp⟩
      simp only [neg_smul, Finset.sum_neg_distrib, hsum, neg_zero]
    · exact ⟨mu, hsum, ⟨i₀, hi₀s, hpos⟩, by simp⟩
  obtain ⟨t', w', hsub, hpos, hli, hv, -⟩ :=
    exists_subset_linearIndepOn_aux v (fun _ => (0 : ℝ)) hpick t.card t le_rfl w hw
  exact ⟨t', w', hsub, hpos, hli, hv⟩

/-- Linear independence over an index set bounds the size of the index set by the dimension. -/
theorem card_le_finrank_of_linearIndepOn [FiniteDimensional ℝ E] {v : ι → E} {t : Finset ι}
    (h : LinearIndepOn ℝ v (t : Set ι)) : t.card ≤ Module.finrank ℝ E := by
  have hfin : Fintype ((t : Set ι) : Type _) := FinsetCoe.fintype t
  have h₁ := LinearIndependent.fintype_card_le_finrank h
  simpa using h₁

/-- A linearly independent lift `i ↦ (1, p i)` is an affinely independent family `i ↦ p i`. This is
the standard homogenisation, read on an index set. -/
theorem affineIndependent_of_linearIndepOn_one {p : ι → E} {s : Set ι}
    (h : LinearIndepOn ℝ (fun i => ((1 : ℝ), p i)) s) :
    AffineIndependent ℝ fun i : s => p (i : ι) := by
  rw [affineIndependent_iff]
  intro u g hg0 hgp e he
  refine linearIndependent_iff'.1 h u g ?_ e he
  refine Prod.ext ?_ ?_
  · rw [Prod.fst_sum]
    simpa using hg0
  · rw [Prod.snd_sum]
    simpa using hgp

/-- **Carathéodory's elimination, indexed, affine form, with a cost.** A convex combination
`∑ i ∈ t, w i • p i` can be thinned to a sub-index set on which the points `p i` are *affinely*
independent, keeping the value, the total weight, strict positivity — and without increasing the
cost `∑ i ∈ t, w i * c i`.

The cost is what makes this the engine of Corollary 17.1.3 rather than only of Corollary 17.1.1:
with `c i = fᵢ(pᵢ)` it says that thinning a representation never makes the value of the
convex-hull formula worse. The sign of an affine dependency may be chosen freely because its
coefficients sum to zero, so *both* signs have a positive coefficient. -/
theorem exists_subset_affineIndependent_of_sum (p : ι → E) (c : ι → ℝ) (t : Finset ι) (w : ι → ℝ)
    (hw : ∀ i ∈ t, 0 < w i) :
    ∃ (t' : Finset ι) (w' : ι → ℝ), t' ⊆ t ∧ (∀ i ∈ t', 0 < w' i) ∧
      AffineIndependent ℝ (fun i : (t' : Set ι) => p (i : ι)) ∧
      ∑ i ∈ t', w' i = ∑ i ∈ t, w i ∧
      ∑ i ∈ t', w' i • p i = ∑ i ∈ t, w i • p i ∧
      ∑ i ∈ t', w' i * c i ≤ ∑ i ∈ t, w i * c i := by
  have hpick : ∀ (s : Finset ι) (mu : ι → ℝ), (∑ i ∈ s, mu i • ((1 : ℝ), p i) = 0) →
      (∃ i ∈ s, mu i ≠ 0) →
      ∃ nu : ι → ℝ, (∑ i ∈ s, nu i • ((1 : ℝ), p i) = 0) ∧ (∃ i ∈ s, 0 < nu i) ∧
        0 ≤ ∑ i ∈ s, nu i * c i := by
    rintro s mu hsum hne
    have hone : ∑ i ∈ s, mu i = 0 := by
      have h₁ := congrArg Prod.fst hsum
      rw [Prod.fst_sum] at h₁
      simpa using h₁
    by_cases hc0 : 0 ≤ ∑ i ∈ s, mu i * c i
    · exact ⟨mu, hsum, exists_pos_of_sum_eq_zero hone hne, hc0⟩
    · refine ⟨fun i => -mu i, ?_, ?_, ?_⟩
      · simp only [neg_smul, Finset.sum_neg_distrib, hsum, neg_zero]
      · refine exists_pos_of_sum_eq_zero ?_ ?_
        · simp only [Finset.sum_neg_distrib, hone, neg_zero]
        · obtain ⟨i, his, hi⟩ := hne
          exact ⟨i, his, by simpa using hi⟩
      · have : ∑ i ∈ s, -mu i * c i = -∑ i ∈ s, mu i * c i := by
          rw [← Finset.sum_neg_distrib]
          exact Finset.sum_congr rfl fun i _ => by ring
        rw [this]
        linarith [not_le.1 hc0]
  obtain ⟨t', w', hsub, hpos, hli, hv, hc⟩ :=
    exists_subset_linearIndepOn_aux (fun i => ((1 : ℝ), p i)) c hpick t.card t le_rfl w hw
  refine ⟨t', w', hsub, hpos, affineIndependent_of_linearIndepOn_one hli, ?_, ?_, hc⟩
  · have h₁ := congrArg Prod.fst hv
    rw [Prod.fst_sum, Prod.fst_sum] at h₁
    simpa using h₁
  · have h₂ := congrArg Prod.snd hv
    rw [Prod.snd_sum, Prod.snd_sum] at h₂
    simpa using h₂

/-- Affine independence over an index set bounds the size of the index set by `n + 1`. -/
theorem card_le_finrank_succ_of_affineIndependent [FiniteDimensional ℝ E] {p : ι → E}
    {t : Finset ι} (h : AffineIndependent ℝ fun i : (t : Set ι) => p (i : ι)) :
    t.card ≤ Module.finrank ℝ E + 1 := by
  have hfin : Fintype ((t : Set ι) : Type _) := FinsetCoe.fintype t
  have h₁ := h.card_le_finrank_succ (k := ℝ)
  have h₂ : Module.finrank ℝ (vectorSpan ℝ (Set.range fun i : (t : Set ι) => p (i : ι)))
      ≤ Module.finrank ℝ E := Submodule.finrank_le _
  have h₃ : Fintype.card ((t : Set ι) : Type _) = t.card := by simp
  omega

/-- **Coalescing** — Rockafellar's step "if two of the points with non-zero coefficients belong to
the same `Cᵢ`, the corresponding term can be coalesced". A positive combination of points each
drawn from *some* member of a family of convex sets can be rewritten with **one point per index**,
by replacing the points drawn from a single `C i` by their center of mass. -/
theorem exists_coalesced_sum {C : ι → Set E} (hC : ∀ i, Convex ℝ (C i)) {κ : Type*}
    (s : Finset κ) (w : κ → ℝ) (z : κ → E) (σ : κ → ι)
    (hw : ∀ j ∈ s, 0 < w j) (hz : ∀ j ∈ s, z j ∈ C (σ j)) :
    ∃ (t : Finset ι) (W : ι → ℝ) (Q : ι → E), (∀ i ∈ t, 0 < W i) ∧ (∀ i ∈ t, Q i ∈ C i) ∧
      ∑ i ∈ t, W i = ∑ j ∈ s, w j ∧ ∑ i ∈ t, W i • Q i = ∑ j ∈ s, w j • z j := by
  classical
  have hmaps : ∀ j ∈ s, σ j ∈ s.image σ := fun j hj => Finset.mem_image_of_mem σ hj
  have hWpos : ∀ i ∈ s.image σ, 0 < ∑ j ∈ s with σ j = i, w j := by
    intro i hi
    obtain ⟨j, hj, rfl⟩ := Finset.mem_image.1 hi
    exact Finset.sum_pos (fun k hk => hw k (Finset.mem_filter.1 hk).1)
      ⟨j, Finset.mem_filter.2 ⟨hj, rfl⟩⟩
  refine ⟨s.image σ, fun i => ∑ j ∈ s with σ j = i, w j,
    fun i => (s.filter fun j => σ j = i).centerMass w z, hWpos, ?_, ?_, ?_⟩
  · intro i hi
    refine Convex.centerMass_mem (hC i) (fun j hj => (hw j (Finset.mem_filter.1 hj).1).le)
      (hWpos i hi) fun j hj => ?_
    obtain ⟨hj₁, hj₂⟩ := Finset.mem_filter.1 hj
    exact hj₂ ▸ hz j hj₁
  · exact Finset.sum_fiberwise_of_maps_to hmaps w
  · have hstep : ∀ i ∈ s.image σ,
        (∑ j ∈ s with σ j = i, w j) • (s.filter fun j => σ j = i).centerMass w z
          = ∑ j ∈ s with σ j = i, w j • z j := by
      intro i hi
      rw [Finset.centerMass, smul_inv_smul₀ (hWpos i hi).ne']
    rw [Finset.sum_congr rfl hstep, Finset.sum_fiberwise_of_maps_to hmaps fun j => w j • z j]

/-- **Rockafellar, Corollary 17.1.2.** Every vector of the convex cone generated by a union of
convex sets `Cᵢ` is a non-negative combination of at most `n` *linearly independent* vectors, each
drawn from a **different** `Cᵢ`.

Rockafellar states it for non-zero vectors of the cone and non-empty `Cᵢ`; neither is needed, since
`t = ∅` covers the origin and an empty `Cᵢ` simply never contributes an index. -/
theorem exists_linearIndepOn_of_mem_coneHull_iUnion [FiniteDimensional ℝ E] {C : ι → Set E}
    (hC : ∀ i, Convex ℝ (C i)) {x : E} (hx : x ∈ PointedCone.hull ℝ (⋃ i, C i)) :
    ∃ (t : Finset ι) (w : ι → ℝ) (v : ι → E), (∀ i ∈ t, 0 < w i) ∧ (∀ i ∈ t, v i ∈ C i) ∧
      LinearIndepOn ℝ v (t : Set ι) ∧ t.card ≤ Module.finrank ℝ E ∧
      ∑ i ∈ t, w i • v i = x := by
  classical
  obtain ⟨c, hcs, hc0, hcx⟩ := PointedCone.mem_hull_set.1 hx
  have hsum : ∑ y ∈ c.support, c y • y = x := hcx
  rcases Finset.eq_empty_or_nonempty c.support with hsup | ⟨y₀, hy₀⟩
  · refine ⟨∅, fun _ => 0, fun _ => 0, by simp, by simp, by simp, by simp, ?_⟩
    rw [Finset.sum_empty, ← hsum, hsup, Finset.sum_empty]
  · have hchoice : ∀ y : E, ∃ i : ι, y ∈ c.support → y ∈ C i := by
      intro y
      by_cases hy : y ∈ c.support
      · obtain ⟨i, hi⟩ := Set.mem_iUnion.1 (hcs (by exact_mod_cast hy))
        exact ⟨i, fun _ => hi⟩
      · obtain ⟨i₀, hi₀⟩ := Set.mem_iUnion.1 (hcs (by exact_mod_cast hy₀))
        exact ⟨i₀, fun h => absurd h hy⟩
    choose σ hσ using hchoice
    have hpos : ∀ y ∈ c.support, 0 < c y := fun y hy =>
      lt_of_le_of_ne (hc0 y) (Ne.symm (Finsupp.mem_support_iff.1 hy))
    obtain ⟨t, W, Q, hWpos, hQmem, -, hQsum⟩ :=
      exists_coalesced_sum hC c.support c id σ hpos fun y hy => hσ y hy
    obtain ⟨t', W', hsub, hpos', hli, hval⟩ := exists_subset_linearIndepOn_of_sum Q t W hWpos
    exact ⟨t', W', Q, hpos', fun i hi => hQmem i (hsub hi), hli,
      card_le_finrank_of_linearIndepOn hli, by rw [hval, hQsum]; simpa using hsum⟩

/-- **Rockafellar, Corollary 17.1.1.** Every point of the convex hull of a union of convex sets
`Cᵢ` is a convex combination of at most `n + 1` *affinely independent* points, each drawn from a
**different** `Cᵢ`. -/
theorem exists_affineIndependent_of_mem_convexHull_iUnion [FiniteDimensional ℝ E] {C : ι → Set E}
    (hC : ∀ i, Convex ℝ (C i)) {x : E} (hx : x ∈ convexHull ℝ (⋃ i, C i)) :
    ∃ (t : Finset ι) (w : ι → ℝ) (p : ι → E), (∀ i ∈ t, 0 < w i) ∧ ∑ i ∈ t, w i = 1 ∧
      (∀ i ∈ t, p i ∈ C i) ∧ AffineIndependent ℝ (fun i : (t : Set ι) => p (i : ι)) ∧
      t.card ≤ Module.finrank ℝ E + 1 ∧ ∑ i ∈ t, w i • p i = x := by
  classical
  rw [convexHull_eq] at hx
  obtain ⟨κ, s, w, z, hw₀, hw₁, hz, hcm⟩ := hx
  set s' : Finset κ := s.filter (fun j => 0 < w j) with hs'def
  have hsub : s' ⊆ s := Finset.filter_subset _ _
  have hwpos : ∀ j ∈ s', 0 < w j := fun j hj => (Finset.mem_filter.1 hj).2
  have hzero : ∀ j ∈ s, j ∉ s' → w j = 0 := by
    intro j hj hj'
    rcases eq_or_lt_of_le (hw₀ j hj) with h | h
    · exact h.symm
    · exact absurd (Finset.mem_filter.2 ⟨hj, h⟩) hj'
  have hw₁' : ∑ j ∈ s', w j = 1 := by rw [Finset.sum_subset hsub hzero]; exact hw₁
  have hcm' : ∑ j ∈ s', w j • z j = x := by
    rw [Finset.sum_subset hsub fun j hj hj' => by rw [hzero j hj hj', zero_smul],
      ← Finset.centerMass_eq_of_sum_1 _ _ hw₁]
    exact hcm
  obtain ⟨j₀, hj₀⟩ : s'.Nonempty :=
    Finset.nonempty_of_sum_ne_zero (by rw [hw₁']; exact one_ne_zero)
  have hchoice : ∀ j : κ, ∃ i : ι, j ∈ s' → z j ∈ C i := by
    intro j
    by_cases hj : j ∈ s'
    · obtain ⟨i, hi⟩ := Set.mem_iUnion.1 (hz j (hsub hj))
      exact ⟨i, fun _ => hi⟩
    · obtain ⟨i₀, hi₀⟩ := Set.mem_iUnion.1 (hz j₀ (hsub hj₀))
      exact ⟨i₀, fun h => absurd h hj⟩
  choose σ hσ using hchoice
  obtain ⟨t, W, Q, hWpos, hQmem, hWsum, hQsum⟩ :=
    exists_coalesced_sum hC s' w z σ hwpos fun j hj => hσ j hj
  obtain ⟨t', W', hsub', hpos', hai, hone, hval, -⟩ :=
    exists_subset_affineIndependent_of_sum Q (fun _ => (0 : ℝ)) t W hWpos
  refine ⟨t', W', Q, hpos', by rw [hone, hWsum, hw₁'], fun i hi => hQmem i (hsub' hi), hai,
    card_le_finrank_succ_of_affineIndependent hai, by rw [hval, hQsum, hcm']⟩

end Indexed

/-! ### Carathéodory for the convex hull of a family of functions -/

section ConvFn

variable {E : Type*} [AddCommGroup E] [Module ℝ E] [FiniteDimensional ℝ E] {ι : Type*}

/-- **Rockafellar, Corollary 17.1.3**, in the form its consumers use: any value strictly above
`(conv {fᵢ})(x)` is already achieved by a convex combination in which at most `n + 1` coefficients
are non-zero, one point per index, and the points carrying a non-zero coefficient are affinely
independent.

Theorem 5.6 (`convFn_apply`) already produces one point per index; what is added here is the
thinning to an affinely independent family, which is
`exists_subset_affineIndependent_of_sum` with the cost `c i = fᵢ(pᵢ)`. Rockafellar's own proof of
this corollary passes to a "minimal `α'`" on the vertical line through `x`; that step is not
needed — and would not be available when `conv {fᵢ}` is improper — because the elimination can
choose the sign of an affine dependency by the cost, and both signs of an affine dependency have a
positive coefficient. -/
theorem exists_affineIndependent_of_convFn_lt {f : ι → E → EReal} (hf : ∀ i, ConvexFn (f i))
    (hf' : ∀ i x, f i x ≠ ⊥) {x : E} {r : ℝ} (h : convFn f x < (r : EReal)) :
    ∃ (t : Finset ι) (w : ι → ℝ) (p : ι → E), (∀ i ∈ t, 0 < w i) ∧ ∑ i ∈ t, w i = 1 ∧
      t.card ≤ Module.finrank ℝ E + 1 ∧
      AffineIndependent ℝ (fun i : (t : Set ι) => p (i : ι)) ∧ (∀ i ∈ t, f i (p i) ≠ ⊤) ∧
      ∑ i ∈ t, w i • p i = x ∧ ∑ i ∈ t, (w i : EReal) * f i (p i) < (r : EReal) := by
  classical
  rw [convFn_apply hf hf'] at h
  obtain ⟨z, ⟨t, w, p, hw₀, hw₁, hwx, rfl⟩, hlt⟩ := sInf_lt_iff.1 h
  -- discard the indices carrying zero weight
  set t₁ : Finset ι := t.filter (fun i => 0 < w i) with ht₁def
  have hsub : t₁ ⊆ t := Finset.filter_subset _ _
  have hwpos : ∀ i ∈ t₁, 0 < w i := fun i hi => (Finset.mem_filter.1 hi).2
  have hzero : ∀ i ∈ t, i ∉ t₁ → w i = 0 := by
    intro i hi hi'
    rcases eq_or_lt_of_le (hw₀ i hi) with h₀ | h₀
    · exact h₀.symm
    · exact absurd (Finset.mem_filter.2 ⟨hi, h₀⟩) hi'
  have hw₁' : ∑ i ∈ t₁, w i = 1 := by rw [Finset.sum_subset hsub hzero]; exact hw₁
  have hwx' : ∑ i ∈ t₁, w i • p i = x := by
    rw [Finset.sum_subset hsub fun i hi hi' => by rw [hzero i hi hi', zero_smul]]; exact hwx
  have hval : ∑ i ∈ t₁, (w i : EReal) * f i (p i) = ∑ i ∈ t, (w i : EReal) * f i (p i) := by
    refine Finset.sum_subset hsub fun i hi hi' => ?_
    rw [hzero i hi hi', _root_.EReal.coe_zero, zero_mul]
  -- on the surviving indices every term is finite
  have hbot : ∀ i ∈ t₁, (w i : EReal) * f i (p i) ≠ ⊥ := fun i hi =>
    Tdaf.EReal.coe_mul_ne_bot (hwpos i hi).le (hf' i (p i))
  have htop : ∑ i ∈ t₁, (w i : EReal) * f i (p i) ≠ ⊤ := by
    rw [hval]
    exact (hlt.trans (_root_.EReal.coe_lt_top r)).ne
  have hnetop := Tdaf.EReal.forall_ne_top_of_sum_ne_top t₁ _ hbot htop
  obtain ⟨c, hc⟩ : ∃ c : ι → ℝ, ∀ i ∈ t₁, f i (p i) = (c i : EReal) := by
    refine ⟨fun i => (f i (p i)).toReal, fun i hi => ?_⟩
    have hne : f i (p i) ≠ ⊤ := fun hcon =>
      hnetop i hi (by rw [hcon, _root_.EReal.coe_mul_top_of_pos (hwpos i hi)])
    exact (_root_.EReal.coe_toReal hne (hf' i (p i))).symm
  have hreal : ∀ (u : Finset ι), u ⊆ t₁ → ∀ v : ι → ℝ,
      ∑ i ∈ u, (v i : EReal) * f i (p i) = ((∑ i ∈ u, v i * c i : ℝ) : EReal) := by
    intro u hu v
    rw [Tdaf.EReal.coe_sum]
    exact Finset.sum_congr rfl fun i hi => by
      rw [hc i (hu hi), Tdaf.EReal.coe_mul_coe]
  -- thin the representation to an affinely independent one, without increasing the cost
  obtain ⟨t', w', hsub', hpos', hai, hone, hpt, hcost⟩ :=
    exists_subset_affineIndependent_of_sum p c t₁ w hwpos
  refine ⟨t', w', p, hpos', by rw [hone, hw₁'], card_le_finrank_succ_of_affineIndependent hai,
    hai, fun i hi => by rw [hc i (hsub' hi)]; exact _root_.EReal.coe_ne_top _,
    by rw [hpt, hwx'], ?_⟩
  rw [hreal t' hsub' w']
  refine lt_of_le_of_lt (_root_.EReal.coe_le_coe_iff.2 hcost) ?_
  rw [← hreal t₁ (Finset.Subset.refl _) w, hval]
  exact hlt

/-- **Rockafellar, Corollary 17.1.3.** The convex hull of a family of convex functions is computed
by the same infimum as in Theorem 5.6, restricted to convex combinations in which at most `n + 1`
coefficients are non-zero and the corresponding points are affinely independent. -/
theorem convFn_apply_affineIndependent {f : ι → E → EReal} (hf : ∀ i, ConvexFn (f i))
    (hf' : ∀ i x, f i x ≠ ⊥) (x : E) :
    convFn f x = sInf {z : EReal | ∃ (t : Finset ι) (w : ι → ℝ) (p : ι → E),
      (∀ i ∈ t, 0 < w i) ∧ ∑ i ∈ t, w i = 1 ∧ t.card ≤ Module.finrank ℝ E + 1 ∧
        AffineIndependent ℝ (fun i : (t : Set ι) => p (i : ι)) ∧ (∀ i ∈ t, f i (p i) ≠ ⊤) ∧
        ∑ i ∈ t, w i • p i = x ∧ z = ∑ i ∈ t, (w i : EReal) * f i (p i)} := by
  refine le_antisymm (le_sInf ?_) ?_
  · rintro z ⟨t, w, p, hpos, hone, -, -, -, hpt, rfl⟩
    rw [convFn_apply hf hf']
    exact sInf_le ⟨t, w, p, fun i hi => (hpos i hi).le, hone, hpt, rfl⟩
  · by_contra hcon
    rw [not_le] at hcon
    obtain ⟨r, hr₁, hr₂⟩ := _root_.EReal.lt_iff_exists_real_btwn.1 hcon
    obtain ⟨t, w, p, hpos, hone, hcard, hai, hnetop, hpt, hlt⟩ :=
      exists_affineIndependent_of_convFn_lt hf hf' hr₁
    have hmem : (∑ i ∈ t, (w i : EReal) * f i (p i)) ∈
        {z : EReal | ∃ (t : Finset ι) (w : ι → ℝ) (p : ι → E),
          (∀ i ∈ t, 0 < w i) ∧ ∑ i ∈ t, w i = 1 ∧ t.card ≤ Module.finrank ℝ E + 1 ∧
            AffineIndependent ℝ (fun i : (t : Set ι) => p (i : ι)) ∧ (∀ i ∈ t, f i (p i) ≠ ⊤) ∧
            ∑ i ∈ t, w i • p i = x ∧ z = ∑ i ∈ t, (w i : EReal) * f i (p i)} :=
      ⟨t, w, p, hpos, hone, hcard, hai, hnetop, hpt, rfl⟩
    exact absurd (sInf_le hmem) (not_le.2 (hlt.trans hr₂))

end ConvFn

/-! ### Carathéodory for the convex hull of a single function -/

section ConvHullFn

variable {E : Type*} [AddCommGroup E] [Module ℝ E] [FiniteDimensional ℝ E]

/-- The padding step of Corollary 17.1.5: a sum over a `Finset` of size at most `N` becomes a sum
over the *fixed* index type `Fin N` once the surplus indices are given a zero summand. `jj` is any
enumeration of the `Finset` by `Fin N` that is faithful on the first `t.card` indices. -/
private theorem sum_pad_eq {M : Type*} [AddCommMonoid M] {κ : Type*} (t : Finset κ) {N : ℕ}
    (hcard : t.card ≤ N) (jj : Fin N → κ)
    (hjj : ∀ j : Fin t.card, jj (Fin.castLE hcard j) = (t.equivFin.symm j : κ)) (H : κ → M) :
    ∑ i : Fin N, (if (i : ℕ) < t.card then H (jj i) else 0) = ∑ j ∈ t, H j := by
  classical
  rw [sum_ite_lt hcard fun i => H (jj i),
    Finset.sum_congr rfl fun j _ => by rw [hjj j],
    Fintype.sum_equiv t.equivFin.symm _ (fun y : {y // y ∈ t} => H (y : κ)) fun _ => rfl,
    Finset.sum_coe_sort t H]

/-- **Rockafellar, Corollary 17.1.5.** For an arbitrary function `g` never taking the value `-∞`,
the convex hull `conv g` is computed by convex combinations of exactly `n + 1` points:

`(conv g)(x) = inf {∑_{i<n+1} λᵢ g(xᵢ) | ∑ λᵢ xᵢ = x, ∑ λᵢ = 1, λᵢ ≥ 0}`.

No convexity is assumed, and the points are not required to be distinct — repetitions and zero
coefficients are what turn Carathéodory's "at most `n + 1` points" into a statement about the fixed
index type `Fin (n + 1)`, exactly as in `mem_convexHull_iff_exists_fin_finrank_succ`. The
convention `0 · (+∞) = 0` is what makes a zero coefficient harmless.

The proof is Rockafellar's: Theorem 17.1 applied to `epi g` in `Rⁿ⁺¹` would give `n + 2` points,
and the reduction to `n + 1` is `exists_subset_affineIndependent_of_sum` — the elimination run on
the *base* points with the vertical coordinate as its cost. -/
theorem convHullFn_apply_fin {g : E → EReal} (hg : ∀ x, g x ≠ ⊥) (x : E) :
    convHullFn g x = sInf {z : EReal |
      ∃ (w : Fin (Module.finrank ℝ E + 1) → ℝ) (p : Fin (Module.finrank ℝ E + 1) → E),
        (∀ i, 0 ≤ w i) ∧ ∑ i, w i = 1 ∧ ∑ i, w i • p i = x ∧
          z = ∑ i, (w i : EReal) * g (p i)} := by
  classical
  rw [convHullFn]
  refine le_antisymm (le_sInf ?_) ?_
  -- **`≤`**: the hull is below the value of every `n + 1`-point representation.
  · rintro z ⟨w, p, hw₀, hw₁, hwx, rfl⟩
    by_cases htop : ∑ i, (w i : EReal) * g (p i) = ⊤
    · rw [htop]; exact le_top
    have hbot : ∀ i ∈ (Finset.univ : Finset (Fin (Module.finrank ℝ E + 1))),
        (w i : EReal) * g (p i) ≠ ⊥ := fun i _ => Tdaf.EReal.coe_mul_ne_bot (hw₀ i) (hg (p i))
    have hnetop := Tdaf.EReal.forall_ne_top_of_sum_ne_top Finset.univ _ hbot htop
    set t' : Finset (Fin (Module.finrank ℝ E + 1)) :=
      Finset.univ.filter (fun i => 0 < w i) with ht'def
    have hsub : t' ⊆ Finset.univ := Finset.subset_univ _
    have hzero : ∀ i ∈ (Finset.univ : Finset (Fin (Module.finrank ℝ E + 1))),
        i ∉ t' → w i = 0 := by
      intro i _ hi'
      rcases eq_or_lt_of_le (hw₀ i) with h | h
      · exact h.symm
      · exact absurd (Finset.mem_filter.2 ⟨Finset.mem_univ i, h⟩) hi'
    have hw₁' : ∑ i ∈ t', w i = 1 := by rw [Finset.sum_subset hsub hzero]; exact hw₁
    have hwx' : ∑ i ∈ t', w i • p i = x := by
      rw [Finset.sum_subset hsub fun i hi hi' => by rw [hzero i hi hi', zero_smul]]; exact hwx
    obtain ⟨μ, hμ⟩ : ∃ μ : Fin (Module.finrank ℝ E + 1) → ℝ,
        ∀ i ∈ t', g (p i) = (μ i : EReal) := by
      refine ⟨fun i => (g (p i)).toReal, fun i hi => ?_⟩
      have hpos : 0 < w i := (Finset.mem_filter.1 hi).2
      have hne : g (p i) ≠ ⊤ := fun hcon =>
        hnetop i (Finset.mem_univ i) (by rw [hcon, _root_.EReal.coe_mul_top_of_pos hpos])
      exact (_root_.EReal.coe_toReal hne (hg (p i))).symm
    have hcm := Finset.centerMass_mem_convexHull t'
      (fun i hi => ((Finset.mem_filter.1 hi).2).le) (by rw [hw₁']; exact zero_lt_one)
      (z := fun i => ((p i, μ i) : E × ℝ))
      (fun i hi => mk_mem_epi.2 (le_of_eq (hμ i hi)))
    rw [Finset.centerMass_eq_of_sum_1 _ _ hw₁'] at hcm
    have hsplit : ∑ i ∈ t', w i • ((p i, μ i) : E × ℝ) = (x, ∑ i ∈ t', w i * μ i) := by
      refine Prod.ext ?_ ?_
      · rw [Prod.fst_sum]; simpa using hwx'
      · rw [Prod.snd_sum]; simp [smul_eq_mul]
    rw [hsplit] at hcm
    refine (ofEpi_apply_le hcm).trans (le_of_eq ?_)
    rw [Tdaf.EReal.coe_sum,
      ← Finset.sum_subset hsub (fun i hi hi' => by rw [hzero i hi hi']; simp)]
    exact Finset.sum_congr rfl fun i hi => by rw [hμ i hi, Tdaf.EReal.coe_mul_coe]
  -- **`≥`**: every point of the hull of `epi g` admits an `n + 1`-point representation.
  · refine le_ofEpi fun ν hν => ?_
    rw [convexHull_eq] at hν
    obtain ⟨κ, s, w, zz, hw₀, hw₁, hzz, hcm⟩ := hν
    set s' : Finset κ := s.filter (fun j => 0 < w j) with hs'def
    have hsub : s' ⊆ s := Finset.filter_subset _ _
    have hwpos : ∀ j ∈ s', 0 < w j := fun j hj => (Finset.mem_filter.1 hj).2
    have hzero : ∀ j ∈ s, j ∉ s' → w j = 0 := by
      intro j hj hj'
      rcases eq_or_lt_of_le (hw₀ j hj) with h | h
      · exact h.symm
      · exact absurd (Finset.mem_filter.2 ⟨hj, h⟩) hj'
    have hw₁' : ∑ j ∈ s', w j = 1 := by rw [Finset.sum_subset hsub hzero]; exact hw₁
    have hcm' : ∑ j ∈ s', w j • zz j = (x, ν) := by
      rw [Finset.sum_subset hsub fun j hj hj' => by rw [hzero j hj hj', zero_smul],
        ← Finset.centerMass_eq_of_sum_1 _ _ hw₁]
      exact hcm
    have hx : ∑ j ∈ s', w j • (zz j).1 = x := by
      have h := congrArg Prod.fst hcm'
      rw [Prod.fst_sum] at h
      simpa using h
    have hnu : ∑ j ∈ s', w j * (zz j).2 = ν := by
      have h := congrArg Prod.snd hcm'
      rw [Prod.snd_sum] at h
      simpa [smul_eq_mul] using h
    obtain ⟨t', w', hsubt, hpos', hai, hsum1, hsumx, hsumc⟩ :=
      exists_subset_affineIndependent_of_sum (fun j => (zz j).1) (fun j => (zz j).2) s' w hwpos
    rw [hw₁'] at hsum1
    rw [hx] at hsumx
    rw [hnu] at hsumc
    have hcard : t'.card ≤ Module.finrank ℝ E + 1 :=
      card_le_finrank_succ_of_affineIndependent (p := fun j => (zz j).1) hai
    have htne : t'.Nonempty := by
      rw [Finset.nonempty_iff_ne_empty]
      intro hcon
      rw [hcon, Finset.sum_empty] at hsum1
      exact zero_ne_one hsum1
    have hm0 : 0 < t'.card := Finset.card_pos.2 htne
    set r : Fin (Module.finrank ℝ E + 1) → Fin t'.card :=
      fun i => ⟨min (i : ℕ) (t'.card - 1), by omega⟩ with hrdef
    set jj : Fin (Module.finrank ℝ E + 1) → κ := fun i => (t'.equivFin.symm (r i) : κ) with hjjdef
    have hrj : ∀ j : Fin t'.card, r (Fin.castLE hcard j) = j := by
      intro j
      have hj := j.2
      refine Fin.ext ?_
      simp only [hrdef, Fin.val_castLE]
      omega
    have hjj : ∀ j : Fin t'.card, jj (Fin.castLE hcard j) = (t'.equivFin.symm j : κ) := by
      intro j
      simp only [hjjdef, hrj j]
    have hmemt : ∀ i, jj i ∈ t' := fun i => (t'.equivFin.symm (r i)).2
    set W : Fin (Module.finrank ℝ E + 1) → ℝ :=
      fun i => if (i : ℕ) < t'.card then w' (jj i) else 0 with hWdef
    set P : Fin (Module.finrank ℝ E + 1) → E := fun i => (zz (jj i)).1 with hPdef
    have hW0 : ∀ i, 0 ≤ W i := by
      intro i
      simp only [hWdef]
      split
      · exact (hpos' _ (hmemt i)).le
      · exact le_rfl
    have hWsum : ∑ i, W i = 1 := by
      rw [hWdef, sum_pad_eq t' hcard jj hjj w']
      exact hsum1
    have hWx : ∑ i, W i • P i = x := by
      have hterm : ∀ i, W i • P i =
          if (i : ℕ) < t'.card then (fun j => w' j • (zz j).1) (jj i) else 0 := by
        intro i
        simp only [hWdef, hPdef]
        split <;> simp
      rw [Finset.sum_congr rfl fun i _ => hterm i,
        sum_pad_eq t' hcard jj hjj fun j => w' j • (zz j).1]
      exact hsumx
    have hWE : ∑ i, (W i : EReal) * g (P i) = ∑ j ∈ t', (w' j : EReal) * g ((zz j).1) := by
      have hterm : ∀ i, (W i : EReal) * g (P i) =
          if (i : ℕ) < t'.card then (fun j => (w' j : EReal) * g ((zz j).1)) (jj i) else 0 := by
        intro i
        simp only [hWdef, hPdef]
        split
        · rfl
        · rw [_root_.EReal.coe_zero, zero_mul]
      rw [Finset.sum_congr rfl fun i _ => hterm i,
        sum_pad_eq t' hcard jj hjj fun j => (w' j : EReal) * g ((zz j).1)]
    have hmem : (∑ i, (W i : EReal) * g (P i)) ∈ {z : EReal |
        ∃ (w : Fin (Module.finrank ℝ E + 1) → ℝ) (p : Fin (Module.finrank ℝ E + 1) → E),
          (∀ i, 0 ≤ w i) ∧ ∑ i, w i = 1 ∧ ∑ i, w i • p i = x ∧
            z = ∑ i, (w i : EReal) * g (p i)} := ⟨W, P, hW0, hWsum, hWx, rfl⟩
    refine le_trans (sInf_le hmem) ?_
    rw [hWE]
    calc ∑ j ∈ t', (w' j : EReal) * g ((zz j).1)
        ≤ ∑ j ∈ t', (w' j : EReal) * (((zz j).2 : ℝ) : EReal) := by
          refine Finset.sum_le_sum fun j hj => ?_
          exact mul_le_mul_of_nonneg_left (hzz j (hsub (hsubt hj)))
            (by exact_mod_cast (hpos' j hj).le)
      _ = ((∑ j ∈ t', w' j * (zz j).2 : ℝ) : EReal) := by
          rw [Tdaf.EReal.coe_sum]
          exact Finset.sum_congr rfl fun j _ => (Tdaf.EReal.coe_mul_coe _ _).symm
      _ ≤ (ν : EReal) := by exact_mod_cast hsumc

end ConvHullFn




/-! ### Which half-spaces contain an intersection of half-spaces

`inequalitySet B S` is the solution set of the system `⟪x, y⟫ ≤ μ`, one inequality for each
`(y, μ) ∈ S`. A closed half-space `{x | ⟪x, y₀⟫ ≤ μ₀}` contains it as soon as `(y₀, μ₀)` lies in the
convex cone generated by `S` together with the upward vertical direction `(0, 1)`; the converse
holds when that cone is closed, and Corollary 9.6.1 makes it closed as soon as `S` is compact and
misses the origin of `F × ℝ`. -/

section HalfSpace

variable {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F] [FiniteDimensional ℝ F]

/-- The solution set of the system of linear inequalities `⟪x, y⟫ ≤ μ` indexed by `(y, μ) ∈ S`:
an arbitrary intersection of closed half-spaces of `E`. -/
def inequalitySet (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (S : Set (F × ℝ)) : Set E :=
  {x | ∀ q ∈ S, B x q.1 ≤ q.2}

variable {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} {S : Set (F × ℝ)}

omit [FiniteDimensional ℝ F] in
theorem mem_inequalitySet {x : E} : x ∈ inequalitySet B S ↔ ∀ q ∈ S, B x q.1 ≤ q.2 := Iff.rfl

omit [FiniteDimensional ℝ F] in
/-- A non-negative combination of the given inequalities, with the right-hand side weakened at
will, is again valid on the solution set. This half of the representation theorem asks nothing of
`S`. -/
theorem inequalitySet_subset_halfSpace_of_mem_coneHull {y₀ : F} {μ₀ : ℝ}
    (h : ((y₀, μ₀) : F × ℝ) ∈ PointedCone.hull ℝ (insert ((0 : F), (1 : ℝ)) S)) :
    inequalitySet B S ⊆ {x : E | B x y₀ ≤ μ₀} := by
  intro x hx
  have hcone : ∀ q ∈ PointedCone.hull ℝ (insert ((0 : F), (1 : ℝ)) S), B x q.1 ≤ q.2 := by
    intro q hq
    induction hq using Submodule.span_induction with
    | mem q hq =>
        rcases hq with rfl | hq
        · simp
        · exact hx q hq
    | zero => simp
    | add a b _ _ ha hb =>
        have hadd : B x (a + b).1 = B x a.1 + B x b.1 := by
          rw [Prod.fst_add, map_add]
        rw [hadd, Prod.snd_add]
        exact add_le_add ha hb
    | smul c a _ ha =>
        have hc : (0 : ℝ) ≤ (c : ℝ) := c.2
        have hfst : B x (c • a).1 = (c : ℝ) * B x a.1 := by
          change B x ((c : ℝ) • a.1) = (c : ℝ) * B x a.1
          rw [map_smul, smul_eq_mul]
        have hsnd : ((c • a).2 : ℝ) = (c : ℝ) * a.2 := rfl
        rw [hfst, hsnd]
        exact mul_le_mul_of_nonneg_left ha hc
  exact hcone _ h

omit [FiniteDimensional ℝ F] in
/-- A compatible pairing separates the points of its second space, so a non-zero `y` is moved by
some `⟪·, y⟫`. -/
private theorem exists_pairing_ne_zero [IsCompatiblePairing B.flip] {y : F} (hy : y ≠ 0) :
    ∃ x : E, B x y ≠ 0 := by
  by_contra hcon
  push Not at hcon
  refine hy (SeparatingDual.eq_zero_of_forall_dual_eq_zero (R := ℝ) fun g => ?_)
  obtain ⟨x, hx⟩ := exists_pairing_eq B.flip g
  rw [hx y]
  exact hcon x

omit [FiniteDimensional ℝ F] in
/-- An interior point of the solution set satisfies every one of the defining inequalities
*strictly*, unless the inequality is the trivial one `0 ≤ 0`. -/
private theorem sub_neg_of_mem_interior [IsCompatiblePairing B.flip] {x₀ : E}
    (hx₀ : x₀ ∈ interior (inequalitySet B S)) (hS0 : (0 : F × ℝ) ∉ S) {q : F × ℝ} (hq : q ∈ S) :
    B x₀ q.1 - q.2 < 0 := by
  obtain ⟨ε, hε, hball⟩ := Metric.isOpen_iff.1 isOpen_interior x₀ hx₀
  have hsub : Metric.ball x₀ ε ⊆ inequalitySet B S := hball.trans interior_subset
  have hx₀' : x₀ ∈ inequalitySet B S := interior_subset hx₀
  by_cases hq1 : q.1 = 0
  · have h0 : B x₀ q.1 = 0 := by rw [hq1, map_zero]
    have hle : (0 : ℝ) ≤ q.2 := by rw [← h0]; exact hx₀' q hq
    rcases eq_or_lt_of_le hle with h | h
    · have hq0 : q = (0 : F × ℝ) := Prod.ext hq1 h.symm
      exact absurd (hq0 ▸ hq) hS0
    · rw [h0]; linarith
  · obtain ⟨u, hu⟩ := exists_pairing_ne_zero (B := B) hq1
    obtain ⟨v, hv⟩ : ∃ v : E, 0 < B v q.1 := by
      rcases lt_or_gt_of_ne hu with h | h
      · refine ⟨-u, ?_⟩
        rw [map_neg, LinearMap.neg_apply]
        linarith
      · exact ⟨u, h⟩
    have hvne : v ≠ 0 := by rintro rfl; simp at hv
    have hvnorm : (0 : ℝ) < ‖v‖ := norm_pos_iff.2 hvne
    have hcpos : (0 : ℝ) < ε / (2 * ‖v‖) := by positivity
    have hnorm : ε / (2 * ‖v‖) * ‖v‖ = ε / 2 := by field_simp
    have hmem : x₀ + (ε / (2 * ‖v‖)) • v ∈ Metric.ball x₀ ε := by
      rw [Metric.mem_ball, dist_eq_norm, add_sub_cancel_left, norm_smul, Real.norm_eq_abs,
        abs_of_pos hcpos, hnorm]
      linarith
    have hineq := hsub hmem q hq
    have hval : B (x₀ + (ε / (2 * ‖v‖)) • v) q.1 = B x₀ q.1 + ε / (2 * ‖v‖) * B v q.1 := by
      rw [map_add, LinearMap.add_apply, map_smul, LinearMap.smul_apply, smul_eq_mul]
    rw [hval] at hineq
    nlinarith [mul_pos hcpos hv]

omit [FiniteDimensional ℝ F] in
/-- With a point interior to the solution set at hand, every generator lies strictly on one side of
the hyperplane `⟪x₀, ·⟫ = ·` of `F × ℝ`, so the origin is outside their convex hull. -/
private theorem zero_notMem_convexHull_insert [IsCompatiblePairing B.flip]
    (hS0 : (0 : F × ℝ) ∉ S) (hint : (interior (inequalitySet B S)).Nonempty) :
    (0 : F × ℝ) ∉ convexHull ℝ (insert ((0 : F), (1 : ℝ)) S) := by
  obtain ⟨x₀, hx₀⟩ := hint
  have hgen : insert ((0 : F), (1 : ℝ)) S ⊆
      {z : F × ℝ | ((B x₀).comp (LinearMap.fst ℝ F ℝ) - LinearMap.snd ℝ F ℝ) z < 0} := by
    rintro q (rfl | hq)
    · have h : ((B x₀).comp (LinearMap.fst ℝ F ℝ) - LinearMap.snd ℝ F ℝ)
          ((0 : F), (1 : ℝ)) = -1 := by simp
      rw [Set.mem_ofPred, h]
      norm_num
    · have h : ((B x₀).comp (LinearMap.fst ℝ F ℝ) - LinearMap.snd ℝ F ℝ) q
          = B x₀ q.1 - q.2 := rfl
      rw [Set.mem_ofPred, h]
      exact sub_neg_of_mem_interior hx₀ hS0 hq
  have hconv : Convex ℝ
      {z : F × ℝ | ((B x₀).comp (LinearMap.fst ℝ F ℝ) - LinearMap.snd ℝ F ℝ) z < 0} :=
    convex_halfSpace_lt (LinearMap.isLinear _) 0
  intro h0
  have hlt := convexHull_min hgen hconv h0
  rw [Set.mem_ofPred, map_zero] at hlt
  exact lt_irrefl (0 : ℝ) hlt

/-- **Corollary 9.6.1** applied to the compact convex hull of the generators: the convex cone
generated by `S` and the upward vertical direction is closed. -/
private theorem isClosed_coneHull_insert [IsCompatiblePairing B.flip] (hScl : IsClosed S)
    (hSb : Bornology.IsBounded S) (hS0 : (0 : F × ℝ) ∉ S)
    (hint : (interior (inequalitySet B S)).Nonempty) :
    IsClosed (PointedCone.hull ℝ (insert ((0 : F), (1 : ℝ)) S) : Set (F × ℝ)) := by
  have hcpt : IsCompact (insert ((0 : F), (1 : ℝ)) S) :=
    IsCompact.insert (Metric.isCompact_of_isClosed_isBounded hScl hSb) _
  have hT : IsCompact (convexHull ℝ (insert ((0 : F), (1 : ℝ)) S)) :=
    IsCompact.isCompact_convexHull hcpt
  have hcl := isClosed_coe_hull_of_isBounded (convex_convexHull ℝ _) hT.isClosed
    ⟨((0 : F), (1 : ℝ)), subset_convexHull ℝ _ (Set.mem_insert _ _)⟩
    (zero_notMem_convexHull_insert hS0 hint) hT.isBounded
  rwa [coe_hull_convexHull] at hcl

/-- The converse of `inequalitySet_subset_halfSpace_of_mem_coneHull`: a closed half-space
containing the solution set has its defining pair in the cone generated by `S` and `(0, 1)`.

The pair is separated from the (closed) cone by a functional `(y, μ) ↦ ⟪u, y⟫ + c μ` with `c ≤ 0`.
A negative `c` rescales `u` into a point of the solution set violating the half-space; a vanishing
`c` makes `u` a direction along which the solution set escapes the half-space. -/
theorem mem_coneHull_insert_of_subset_halfSpace [IsCompatiblePairing B.flip] (hScl : IsClosed S)
    (hSb : Bornology.IsBounded S) (hS0 : (0 : F × ℝ) ∉ S)
    (hint : (interior (inequalitySet B S)).Nonempty) {y₀ : F} {μ₀ : ℝ}
    (hsub : inequalitySet B S ⊆ {x : E | B x y₀ ≤ μ₀}) :
    ((y₀, μ₀) : F × ℝ) ∈ PointedCone.hull ℝ (insert ((0 : F), (1 : ℝ)) S) := by
  classical
  have hKcl : IsClosed (PointedCone.hull ℝ (insert ((0 : F), (1 : ℝ)) S) : Set (F × ℝ)) :=
    isClosed_coneHull_insert hScl hSb hS0 hint
  have hKconv : Convex ℝ (PointedCone.hull ℝ (insert ((0 : F), (1 : ℝ)) S) : Set (F × ℝ)) :=
    ((PointedCone.hull ℝ (insert ((0 : F), (1 : ℝ)) S) : PointedCone ℝ (F × ℝ)) :
      ConvexCone ℝ (F × ℝ)).convex
  have hKcone : ∀ ⦃a : ℝ⦄, 0 < a → ∀ ⦃z : F × ℝ⦄,
      z ∈ (PointedCone.hull ℝ (insert ((0 : F), (1 : ℝ)) S) : Set (F × ℝ)) →
      a • z ∈ (PointedCone.hull ℝ (insert ((0 : F), (1 : ℝ)) S) : Set (F × ℝ)) := by
    intro a ha z hz
    exact Submodule.smul_mem _ (⟨a, ha.le⟩ : {c : ℝ // 0 ≤ c}) hz
  have hKne : (PointedCone.hull ℝ (insert ((0 : F), (1 : ℝ)) S) : Set (F × ℝ)).Nonempty :=
    ⟨0, Submodule.zero_mem _⟩
  by_contra hnot
  have hmem : ((y₀, μ₀) : F × ℝ) ∉ ⋂ (f : (F × ℝ) →L[ℝ] ℝ)
      (_ : ∀ z ∈ (PointedCone.hull ℝ (insert ((0 : F), (1 : ℝ)) S) : Set (F × ℝ)), f z ≤ 0),
      (halfSpaceCone f : Set (F × ℝ)) := by
    rw [isClosed_convex_isCone_eq_iInter_halfSpaceCone hKconv hKcone hKcl hKne]
    exact hnot
  simp only [Set.mem_iInter, coe_halfSpaceCone, Set.mem_ofPred, not_forall, not_le] at hmem
  obtain ⟨φ, hφK, hφpos⟩ := hmem
  have hdecomp : ∀ (y : F) (μ : ℝ),
      φ (y, μ) = (φ.comp (ContinuousLinearMap.inl ℝ F ℝ)) y + φ ((0 : F), (1 : ℝ)) * μ :=
    dual_prod_apply φ
  obtain ⟨u, hu⟩ := exists_pairing_eq B.flip (φ.comp (ContinuousLinearMap.inl ℝ F ℝ))
  have hu' : ∀ y : F, (φ.comp (ContinuousLinearMap.inl ℝ F ℝ)) y = B u y := hu
  have hc0 : φ ((0 : F), (1 : ℝ)) ≤ 0 :=
    hφK _ (PointedCone.subset_hull (Set.mem_insert _ _))
  have hSK : ∀ q ∈ S, B u q.1 + φ ((0 : F), (1 : ℝ)) * q.2 ≤ 0 := by
    intro q hq
    have h := hφK q (PointedCone.subset_hull (Set.mem_insert_of_mem _ hq))
    rwa [show q = (q.1, q.2) from rfl, hdecomp q.1 q.2, hu' q.1] at h
  have hpos : 0 < B u y₀ + φ ((0 : F), (1 : ℝ)) * μ₀ := by
    rwa [hdecomp y₀ μ₀, hu' y₀] at hφpos
  rcases lt_or_eq_of_le hc0 with hcneg | hceq
  · -- the separating functional is not vertical: rescale `u` into the solution set
    have hane : φ ((0 : F), (1 : ℝ)) ≠ 0 := ne_of_lt hcneg
    have hapos : 0 < -(φ ((0 : F), (1 : ℝ)))⁻¹ := by
      rw [neg_pos, inv_neg'' ]
      exact hcneg
    have hprod : -(φ ((0 : F), (1 : ℝ)))⁻¹ * -(φ ((0 : F), (1 : ℝ))) = 1 := by
      field_simp
    have hxmem : (-(φ ((0 : F), (1 : ℝ)))⁻¹) • u ∈ inequalitySet B S := by
      intro q hq
      have h := hSK q hq
      have hval : B ((-(φ ((0 : F), (1 : ℝ)))⁻¹) • u) q.1
          = -(φ ((0 : F), (1 : ℝ)))⁻¹ * B u q.1 := by
        rw [map_smul, LinearMap.smul_apply, smul_eq_mul]
      rw [hval]
      have h1 : B u q.1 ≤ -(φ ((0 : F), (1 : ℝ))) * q.2 := by linarith
      calc -(φ ((0 : F), (1 : ℝ)))⁻¹ * B u q.1
          ≤ -(φ ((0 : F), (1 : ℝ)))⁻¹ * (-(φ ((0 : F), (1 : ℝ))) * q.2) :=
            mul_le_mul_of_nonneg_left h1 hapos.le
        _ = q.2 := by rw [← mul_assoc, hprod, one_mul]
    have hgoal := hsub hxmem
    rw [Set.mem_ofPred, map_smul, LinearMap.smul_apply, smul_eq_mul] at hgoal
    have h2 : -(φ ((0 : F), (1 : ℝ))) * μ₀ < B u y₀ := by linarith
    have h3 := mul_lt_mul_of_pos_left h2 hapos
    rw [← mul_assoc, hprod, one_mul] at h3
    linarith
  · -- the separating functional is vertical: `u` is a direction of escape
    obtain ⟨x₀, hx₀⟩ := hint
    have hx₀' : x₀ ∈ inequalitySet B S := interior_subset hx₀
    have hSu : ∀ q ∈ S, B u q.1 ≤ 0 := by
      intro q hq
      have h := hSK q hq
      rw [hceq, zero_mul, add_zero] at h
      exact h
    have hposu : 0 < B u y₀ := by rw [hceq, zero_mul, add_zero] at hpos; exact hpos
    set s : ℝ := (|μ₀ - B x₀ y₀| + 1) / B u y₀ with hs
    have hspos : 0 < s := by positivity
    have hxs : x₀ + s • u ∈ inequalitySet B S := by
      intro q hq
      have hval : B (x₀ + s • u) q.1 = B x₀ q.1 + s * B u q.1 := by
        rw [map_add, LinearMap.add_apply, map_smul, LinearMap.smul_apply, smul_eq_mul]
      rw [hval]
      nlinarith [hx₀' q hq, mul_nonpos_of_nonneg_of_nonpos hspos.le (hSu q hq)]
    have hgoal := hsub hxs
    rw [Set.mem_ofPred, map_add, LinearMap.add_apply, map_smul, LinearMap.smul_apply,
      smul_eq_mul] at hgoal
    have hsval : s * B u y₀ = |μ₀ - B x₀ y₀| + 1 := by
      rw [hs]; field_simp
    have habs : μ₀ - B x₀ y₀ ≤ |μ₀ - B x₀ y₀| := le_abs_self _
    linarith

/-- Carathéodory's theorem thins a conical representation down to `dim F` generators drawn from
`S` itself. The upward direction always disappears: either it does not occur in the representation
at all, or it can be eliminated, because a maximal linearly independent family of members of `S`
already spans it — and the sign that makes the elimination legal is available, since a family of
members of `S` combining to `(0, 1)` with non-positive coefficients would contradict the existence
of a solution. -/
theorem exists_card_le_finrank_of_mem_coneHull_insert (hne : (inequalitySet B S).Nonempty)
    {y₀ : F} {μ₀ : ℝ}
    (h : ((y₀, μ₀) : F × ℝ) ∈ PointedCone.hull ℝ (insert ((0 : F), (1 : ℝ)) S)) :
    ∃ (t : Finset (F × ℝ)) (l : (F × ℝ) → ℝ), ↑t ⊆ S ∧ (∀ q ∈ t, 0 ≤ l q) ∧
      t.card ≤ Module.finrank ℝ F ∧
      (∑ q ∈ t, l q • q.1 = y₀) ∧ ∑ q ∈ t, l q * q.2 ≤ μ₀ := by
  classical
  obtain ⟨t, w, hts, hwpos, hli, hsum⟩ := exists_linearIndepOn_of_mem_coneHull h
  have hfr : Module.finrank ℝ (F × ℝ) = Module.finrank ℝ F + 1 := by
    rw [Module.finrank_prod, Module.finrank_self]
  have hcard : t.card ≤ Module.finrank ℝ F + 1 := by
    have hb := LinearIndependent.finset_card_le_finrank hli
    rwa [hfr] at hb
  have hfst : ∑ q ∈ t, w q • q.1 = y₀ := by
    simpa [Prod.fst_sum, Prod.smul_fst] using congrArg Prod.fst hsum
  have hsnd : ∑ q ∈ t, w q * q.2 = μ₀ := by
    simpa [Prod.snd_sum, Prod.smul_snd, smul_eq_mul] using congrArg Prod.snd hsum
  by_cases hv : ((0 : F), (1 : ℝ)) ∈ t
  · -- the upward direction occurs: drop it, which only lowers the right-hand side
    refine ⟨t.erase ((0 : F), (1 : ℝ)), w, ?_, ?_, ?_, ?_, ?_⟩
    · intro q hq
      have hq' := Finset.mem_erase.1 (by exact_mod_cast hq)
      rcases hts (by exact_mod_cast hq'.2) with hq'' | hq''
      · exact absurd hq'' hq'.1
      · exact hq''
    · exact fun q hq => (hwpos q (Finset.mem_of_mem_erase hq)).le
    · have hc := Finset.card_erase_of_mem hv
      omega
    · have hsplit : (∑ q ∈ t.erase ((0 : F), (1 : ℝ)), w q • q.1)
          + w ((0 : F), (1 : ℝ)) • ((0 : F), (1 : ℝ)).1 = ∑ q ∈ t, w q • q.1 :=
        Finset.sum_erase_add t (fun q => w q • q.1) hv
      simp only [smul_zero, add_zero] at hsplit
      rw [hsplit]
      exact hfst
    · have hsplit : (∑ q ∈ t.erase ((0 : F), (1 : ℝ)), w q * q.2)
          + w ((0 : F), (1 : ℝ)) * (1 : ℝ) = ∑ q ∈ t, w q * q.2 :=
        Finset.sum_erase_add t (fun q => w q * q.2) hv
      have hwv : 0 < w ((0 : F), (1 : ℝ)) := hwpos _ hv
      rw [hsnd, mul_one] at hsplit
      linarith
  · have htS : (t : Set (F × ℝ)) ⊆ S := by
      intro q hq
      rcases hts hq with hq' | hq'
      · exact absurd (hq' ▸ (by exact_mod_cast hq : q ∈ t)) hv
      · exact hq'
    by_cases hcard' : t.card ≤ Module.finrank ℝ F
    · exact ⟨t, w, htS, fun q hq => (hwpos q hq).le, hcard', hfst, le_of_eq hsnd⟩
    · -- a maximal independent family: it spans, so it produces the upward direction itself
      have hteq : t.card = Module.finrank ℝ F + 1 := le_antisymm hcard (by omega)
      have hspan : Submodule.span ℝ (t : Set (F × ℝ)) = ⊤ := by
        refine Submodule.eq_top_of_finrank_eq ?_
        rw [finrank_span_set_eq_card hli, hfr, ← hteq]
        simp
      have hmem01 : ((0 : F), (1 : ℝ)) ∈ Submodule.span ℝ (t : Set (F × ℝ)) := by
        rw [hspan]; trivial
      obtain ⟨c, -, hc⟩ := Submodule.mem_span_finset.1 hmem01
      have hcfst : ∑ q ∈ t, c q • q.1 = (0 : F) := by
        simpa [Prod.fst_sum, Prod.smul_fst] using congrArg Prod.fst hc
      have hcsnd : ∑ q ∈ t, c q * q.2 = (1 : ℝ) := by
        simpa [Prod.snd_sum, Prod.smul_snd, smul_eq_mul] using congrArg Prod.snd hc
      obtain ⟨x₀, hx₀⟩ := hne
      have hexpos : ∃ q ∈ t, 0 < c q := by
        by_contra hcon
        push Not at hcon
        have hzero : ∑ q ∈ t, c q * B x₀ q.1 = 0 := by
          have hmap : B x₀ (∑ q ∈ t, c q • q.1) = ∑ q ∈ t, c q * B x₀ q.1 := by
            rw [map_sum]
            exact Finset.sum_congr rfl fun q _ => by rw [map_smul, smul_eq_mul]
          rw [hcfst, map_zero] at hmap
          exact hmap.symm
        have hge : ∀ q ∈ t, c q * q.2 ≤ c q * B x₀ q.1 := fun q hq =>
          mul_le_mul_of_nonpos_left (hx₀ q (htS hq)) (hcon q hq)
        have hle := Finset.sum_le_sum hge
        rw [hcsnd, hzero] at hle
        linarith
      obtain ⟨qm, hqm, hqmmin⟩ :=
        (t.filter (fun q => 0 < c q)).exists_min_image (fun q => w q / c q)
          (by obtain ⟨q, hqt, hqc⟩ := hexpos; exact ⟨q, Finset.mem_filter.2 ⟨hqt, hqc⟩⟩)
      have hqmt : qm ∈ t := (Finset.mem_filter.1 hqm).1
      have hqmc : 0 < c qm := (Finset.mem_filter.1 hqm).2
      have hspos : 0 < w qm / c qm := div_pos (hwpos qm hqmt) hqmc
      have hl0 : ∀ q ∈ t, 0 ≤ w q - (w qm / c qm) * c q := by
        intro q hq
        rcases le_or_gt (c q) 0 with hcq | hcq
        · nlinarith [hwpos q hq]
        · have hmin := hqmmin q (Finset.mem_filter.2 ⟨hq, hcq⟩)
          have := (le_div_iff₀ hcq).1 hmin
          linarith
      have hlq : w qm - (w qm / c qm) * c qm = 0 := by field_simp; ring
      have hsum' : ∑ q ∈ t, (w q - (w qm / c qm) * c q) • q
          = ((y₀, μ₀ - w qm / c qm) : F × ℝ) := by
        have hstep : ∑ q ∈ t, (w q - (w qm / c qm) * c q) • q
            = (∑ q ∈ t, w q • q) - (w qm / c qm) • ∑ q ∈ t, c q • q := by
          rw [Finset.smul_sum, ← Finset.sum_sub_distrib]
          exact Finset.sum_congr rfl fun q _ => by rw [sub_smul, smul_smul]
        rw [hstep, hsum, hc]
        refine Prod.ext ?_ ?_ <;> simp
      have hfst' : ∑ q ∈ t, (w q - (w qm / c qm) * c q) • q.1 = y₀ := by
        simpa [Prod.fst_sum, Prod.smul_fst] using congrArg Prod.fst hsum'
      have hsnd' : ∑ q ∈ t, (w q - (w qm / c qm) * c q) * q.2 = μ₀ - w qm / c qm := by
        simpa [Prod.snd_sum, Prod.smul_snd, smul_eq_mul] using congrArg Prod.snd hsum'
      refine ⟨t.erase qm, fun q => w q - (w qm / c qm) * c q, ?_, ?_, ?_, ?_, ?_⟩
      · exact fun q hq => htS (by exact_mod_cast Finset.mem_of_mem_erase (by exact_mod_cast hq))
      · exact fun q hq => hl0 q (Finset.mem_of_mem_erase hq)
      · have hcerase := Finset.card_erase_of_mem hqmt
        omega
      · have hsp : (∑ q ∈ t.erase qm, (w q - (w qm / c qm) * c q) • q.1)
            + (w qm - (w qm / c qm) * c qm) • qm.1
            = ∑ q ∈ t, (w q - (w qm / c qm) * c q) • q.1 :=
          Finset.sum_erase_add t (fun q => (w q - (w qm / c qm) * c q) • q.1) hqmt
        rw [hlq, zero_smul, add_zero] at hsp
        rw [hsp]
        exact hfst'
      · have hsp : (∑ q ∈ t.erase qm, (w q - (w qm / c qm) * c q) * q.2)
            + (w qm - (w qm / c qm) * c qm) * qm.2
            = ∑ q ∈ t, (w q - (w qm / c qm) * c q) * q.2 :=
          Finset.sum_erase_add t (fun q => (w q - (w qm / c qm) * c q) * q.2) hqmt
        rw [hlq, zero_mul, add_zero] at hsp
        rw [hsp, hsnd']
        linarith

omit [FiniteDimensional ℝ F] in
/-- The elementary direction, packaged for the representation theorem: a non-negative combination
of members of `S`, with the right-hand side weakened, lies in the cone. -/
theorem mem_coneHull_insert_of_exists_finset {y₀ : F} {μ₀ : ℝ} {t : Finset (F × ℝ)}
    {l : (F × ℝ) → ℝ} (hts : (t : Set (F × ℝ)) ⊆ S) (hl : ∀ q ∈ t, 0 ≤ l q)
    (hfst : ∑ q ∈ t, l q • q.1 = y₀) (hsnd : ∑ q ∈ t, l q * q.2 ≤ μ₀) :
    ((y₀, μ₀) : F × ℝ) ∈ PointedCone.hull ℝ (insert ((0 : F), (1 : ℝ)) S) := by
  classical
  have hrepr : ((y₀, μ₀) : F × ℝ)
      = (∑ q ∈ t, l q • q) + (μ₀ - ∑ q ∈ t, l q * q.2) • (((0 : F), (1 : ℝ)) : F × ℝ) := by
    refine Prod.ext ?_ ?_
    · simpa [Prod.fst_sum, Prod.smul_fst] using hfst.symm
    · simp [Prod.snd_sum, Prod.smul_snd, smul_eq_mul]
  rw [hrepr]
  refine Submodule.add_mem _ (Submodule.sum_mem _ fun q hq => ?_) ?_
  · exact Submodule.smul_mem _ (⟨l q, hl q hq⟩ : {c : ℝ // 0 ≤ c})
      (PointedCone.subset_hull (Set.mem_insert_of_mem _ (hts (by exact_mod_cast hq))))
  · exact Submodule.smul_mem _ (⟨μ₀ - ∑ q ∈ t, l q * q.2, by linarith⟩ : {c : ℝ // 0 ≤ c})
      (PointedCone.subset_hull (Set.mem_insert _ _))

/-- **Rockafellar, Theorem 17.3.** Let `S` be a non-empty compact set of pairs `(y, μ)` missing the
origin of `F × ℝ`, and let `C` be the solution set of the system `⟪x, y⟫ ≤ μ`, `(y, μ) ∈ S`. If `C`
has interior, then a closed half-space `{x | ⟪x, y₀⟫ ≤ μ₀}` contains `C` **iff** it is a
non-negative combination of at most `dim F` of the given inequalities, with the right-hand side
weakened at will.

**The hypothesis `0 ∉ S` is not in the book, and is not removable.** Rockafellar's proof shows
`0 ∉ conv (S ∪ {(0, 1)})` — which is false the moment `(0, 0) ∈ S`, and the *statement* fails too.
On `F = ℝ²` take `S = {t (cos φ t, sin φ t, t) | 0 < t ≤ 1} ∪ {0}` for a continuous, strictly
monotone `φ` with `φ t → φ₀` as `t → 0`. Then `S` is compact, `C` is a neighbourhood of the origin,
so two-dimensional, and the cone generated by `S` and `(0, 1)` meets the horizontal plane `μ = 1` in
`conv ({(cos φ t, sin φ t)} ∪ {0})`, which omits the unit vector at angle `φ₀`. The half-space that
unit vector defines contains `C` but has no representation. -/
theorem inequalitySet_subset_halfSpace_iff [IsCompatiblePairing B.flip] (hScl : IsClosed S)
    (hSb : Bornology.IsBounded S) (hS0 : (0 : F × ℝ) ∉ S)
    (hint : (interior (inequalitySet B S)).Nonempty) (y₀ : F) (μ₀ : ℝ) :
    inequalitySet B S ⊆ {x : E | B x y₀ ≤ μ₀} ↔
      ∃ (t : Finset (F × ℝ)) (l : (F × ℝ) → ℝ), (t : Set (F × ℝ)) ⊆ S ∧ (∀ q ∈ t, 0 ≤ l q) ∧
        t.card ≤ Module.finrank ℝ F ∧
        (∑ q ∈ t, l q • q.1 = y₀) ∧ ∑ q ∈ t, l q * q.2 ≤ μ₀ := by
  constructor
  · intro hsub
    exact exists_card_le_finrank_of_mem_coneHull_insert
      ⟨hint.choose, interior_subset hint.choose_spec⟩
      (mem_coneHull_insert_of_subset_halfSpace hScl hSb hS0 hint hsub)
  · rintro ⟨t, l, hts, hl, -, hfst, hsnd⟩
    exact inequalitySet_subset_halfSpace_of_mem_coneHull
      (mem_coneHull_insert_of_exists_finset hts hl hfst hsnd)

end HalfSpace

end Tdaf.ConvexAnalysis
