import Tdaf.Analysis.Convex.Helly
import Tdaf.Analysis.Convex.Polyhedral.Duality
import Tdaf.Analysis.Convex.Polyhedral.Homogeneous

/-!
# The refined theorems of the alternative

The recession hypothesis of the alternative for an infinite system of weak convex inequalities can
be weakened when the constraint set is the whole space: instead of asking that the `fᵢ` have *no*
common direction of recession, it is enough that finitely many of them be affine and that every
common direction of recession be a direction of *constancy* for all the others. The corresponding
weakening of Helly's theorem asks that finitely many of the `Cᵢ` be polyhedral and that every
common direction of recession be a direction of *linearity* for the rest.

The proof changes exactly one step of the unrefined one. Both run on the positively homogeneous
convex function `k` generated by `conv {fᵢ*}` and both finish with
`exists_multipliers_of_posHomGen_convFn_conj_eq_bot` (in `Helly.lean`) once `k(0) = -∞` is known.
The unrefined proof gets `k(0) = -∞` from `0 ∈ ri (dom k)`; here it comes from splitting the family
in two and separating the halves, one of which is polyhedral.

Only the case of the whole space is treated, as in the book. A version relative to a closed convex
`C` needs no new mathematics — fold `δ(· ∣ C)` into the family — but then carries the hypothesis
that `C` is linear in every common direction of recession, or polyhedral and cut into half-spaces.

## Main results

* `conj_affineFn`, `epi_conj_affineFn` — the conjugate of `⟨·, a⟩ - c` is `δ(· ∣ a) + c`, and its
  epigraph is a single translated vertical ray. This is what makes `k₀` below polyhedral.
* `polyhedralFn_posHomGen_convFn_conj_affineFn` — **the affine half `k₀` is polyhedral.**
* `conj_posHomGen_convFn_conj` — **`kⱼ* = δ(· ∣ Cⱼ)`**.
* `nonempty_neg_dom_inter_relint_dom` — **the separation step**: `(-dom k₀) ∩ ri (dom k₁) ≠ ∅`,
  from polyhedral separation and the constancy hypothesis.
* `apply_zero_eq_bot_of_le_of_le` — **the heart of the refinement**: `k(0) = -∞`.
* `alternative_infinite_system_univ_of_affine_tail` — the refined alternative for functions;
  Theorem 21.4 in [^1]. `exists_forall_le_zero_of_forall_subsystem_of_affine_tail` is the matching
  solvability criterion.
* `helly_of_polyhedral_tail` — the refined Helly theorem; Theorem 21.5 in [^1].
* `Polyhedral.exists_finset_pairing` — a polyhedral set is cut out by finitely many inequalities
  *of the pairing*, which is what lets the refined Helly theorem feed its half-spaces to the
  refined alternative.
* `constancySpace_indicatorFn`, `recessionFn_affineFn_nonpos_iff`,
  `mem_recessionCone_of_forall_pairing_nonpos` — the translation between the language of sets and
  the language of functions.
* `PosHomogeneous.add_le_add_of_ne_top` — subadditivity of a positively homogeneous convex function
  at the points where it is `< +∞`.

## Implementation notes

`k = conv {k₀, k₁}` is never formed: only `k(0) ≤ k₀(-z) + k₁(z)` is used, so
`apply_zero_eq_bot_of_le_of_le` takes an arbitrary positively homogeneous convex `k` below both.
The two halves are indexed by subtypes of `ι` and neither need be nonempty — Rockafellar adjoins
identically-zero functions to avoid that, but `posHomGen h` is `≤ 0` at the origin whatever `h` is,
and for an empty family `posHomGen (convFn g)` is `δ(· ∣ 0)`, polyhedral with domain `{0}`. The
hypothesis `B.SeparatingRight` replaces Rockafellar's identification of `Rⁿ` with its dual: it is
what makes `fᵢ*` a *point* indicator rather than the indicator of an affine subspace.

## References

[^1]: R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §13, §19, §20
  and §21.
-/
open Set Pointwise

namespace Tdaf.ConvexAnalysis

section AffineConj

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ}

/-- The conjugate of the affine function `⟨·, a⟩ - c` takes the value `c` at `a`. -/
theorem conj_affineFn_apply_self (a : F) (c : ℝ) :
    conj B (affineFn B a c) a = ((c : ℝ) : EReal) := by
  rw [conj_apply]
  refine le_antisymm (iSup_le fun x => ?_) ?_
  · rw [affineFn_eq_coe, ← _root_.EReal.coe_sub]
    exact_mod_cast le_of_eq (by ring)
  · have h := le_iSup (fun x : E => ((B x a : ℝ) : EReal) - affineFn B a c x) 0
    simpa using h

/-- Away from `a` the conjugate of `⟨·, a⟩ - c` is `+∞`: the pairing separates `y - a` from `0`,
so `⟨·, y - a⟩` is unbounded above. -/
theorem conj_affineFn_apply_of_ne (hB : B.SeparatingRight) {a y : F} (hy : y ≠ a) (c : ℝ) :
    conj B (affineFn B a c) y = ⊤ := by
  obtain ⟨x₀, hx₀⟩ : ∃ x : E, B x (y - a) ≠ 0 := by
    by_contra hcon
    push Not at hcon
    exact hy (sub_eq_zero.1 (hB _ hcon))
  set t : ℝ := B x₀ (y - a) with ht
  rw [conj_apply, _root_.EReal.eq_top_iff_forall_lt]
  intro d
  have hval : ∀ s : ℝ, ((B (s • x₀) y : ℝ) : EReal) - affineFn B a c (s • x₀)
      = ((s * t + c : ℝ) : EReal) := by
    intro s
    rw [affineFn_eq_coe, ← _root_.EReal.coe_sub]
    refine congrArg _ ?_
    have h1 : B (s • x₀) y = s * B x₀ y := by rw [map_smul]; simp
    have h2 : B (s • x₀) a = s * B x₀ a := by rw [map_smul]; simp
    have h3 : t = B x₀ y - B x₀ a := by rw [ht, map_sub]
    rw [h1, h2, h3]; ring
  obtain ⟨s, hs⟩ : ∃ s : ℝ, d < s * t + c := by
    rcases lt_or_gt_of_ne hx₀ with hneg | hpos
    · exact ⟨(d + 1 - c) / t, by rw [div_mul_cancel₀ _ (ne_of_lt hneg)]; linarith⟩
    · exact ⟨(d + 1 - c) / t, by rw [div_mul_cancel₀ _ (ne_of_gt hpos)]; linarith⟩
  refine lt_of_lt_of_le ?_ (le_iSup (fun x : E => ((B x y : ℝ) : EReal) - affineFn B a c x)
    (s • x₀))
  rw [hval s]
  exact_mod_cast hs

/-- **The conjugate of an affine function is a translated point indicator**: `fᵢ(x) = ⟨aᵢ, x⟩ - αᵢ`
has `fᵢ*(x*) = δ(x* ∣ aᵢ) + αᵢ`. The separating hypothesis on the pairing is what replaces
Rockafellar's identification of `Rⁿ` with its dual. -/
theorem conj_affineFn (hB : B.SeparatingRight) (a : F) (c : ℝ) :
    conj B (affineFn B a c) = indicatorFn ({a} : Set F) + fun _ => ((c : ℝ) : EReal) := by
  funext y
  by_cases hy : y = a
  · subst hy
    rw [conj_affineFn_apply_self]
    simp
  · rw [conj_affineFn_apply_of_ne hB hy]
    simp [indicatorFn_of_notMem (by simpa using hy : y ∉ ({a} : Set F))]

/-- **The epigraph of the conjugate of an affine function is a single translated vertical ray.**
This is the hypothesis shape of `epi_convFn_of_epi_eq`, and it is what makes Rockafellar's `k₀`
finitely generated. -/
theorem epi_conj_affineFn (hB : B.SeparatingRight) (a : F) (c : ℝ) :
    epi (conj B (affineFn B a c)) = {((a, c) : F × ℝ)} + (verticalRay F : Set (F × ℝ)) := by
  ext p
  rw [mem_epi]
  constructor
  · intro hp
    by_cases hy : p.1 = a
    · rw [hy, conj_affineFn_apply_self] at hp
      have hcp : (c : ℝ) ≤ p.2 := by exact_mod_cast hp
      refine ⟨(a, c), rfl, ((0 : F), p.2 - c),
        mem_verticalRay_iff.2 ⟨p.2 - c, by linarith, rfl⟩, ?_⟩
      refine Prod.ext ?_ ?_
      · simpa using hy.symm
      · simp
    · rw [conj_affineFn_apply_of_ne hB hy] at hp
      exact absurd hp (by simp)
  · rintro ⟨u, hu, v, hv, rfl⟩
    rw [Set.mem_singleton_iff] at hu
    obtain ⟨d, hd, rfl⟩ := mem_verticalRay_iff.1 hv
    subst hu
    have hfst : (((a, c) : F × ℝ) + ((0 : F), d)).1 = a := by simp
    have hsnd : (((a, c) : F × ℝ) + ((0 : F), d)).2 = c + d := by simp
    rw [hfst, hsnd, conj_affineFn_apply_self]
    exact_mod_cast le_add_of_nonneg_right hd

end AffineConj

section PosHomGenAux

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {f g : E → EReal}

/-- **A positively homogeneous convex function is subadditive wherever it is not `+∞`.** The usual
form of this asks instead that the function never take `-∞`, which cannot be paid here, because the
functions `kⱼ` built below may be improper; the epigraph, a convex cone, supplies subadditivity
directly wherever both values are `< +∞`. The hypothesis cannot be dropped: on `ℝ²` the function
with epigraph `{(s, t, μ) ∣ s > 0} ∪ {(0, 0, μ) ∣ μ ≥ 0}` is positively homogeneous and convex and
vanishes at the origin, yet `g(0, 0) = 0 > ⊥ = g(-1, 0) + g(1, 0)`. -/
theorem PosHomogeneous.add_le_add_of_ne_top (hg : PosHomogeneous g) (hgc : ConvexFn g) {x y : E}
    (hx : g x ≠ ⊤) (hy : g y ≠ ⊤) : g (x + y) ≤ g x + g y := by
  have key : ∀ μ ν : ℝ, g x ≤ ((μ : ℝ) : EReal) → g y ≤ ((ν : ℝ) : EReal) →
      g (x + y) ≤ ((μ + ν : ℝ) : EReal) := by
    intro μ ν hμ hν
    have h : ((x, μ) + (y, ν) : E × ℝ) ∈ epi g :=
      (hg.epiCone hgc).add_mem (mk_mem_epi.2 hμ) (mk_mem_epi.2 hν)
    rw [Prod.mk_add_mk] at h
    exact mk_mem_epi.1 h
  have hxr : g x ≤ (((g x).toReal : ℝ) : EReal) := _root_.EReal.le_coe_toReal hx
  have hyr : g y ≤ (((g y).toReal : ℝ) : EReal) := _root_.EReal.le_coe_toReal hy
  rcases eq_or_ne (g x) ⊥ with hxb | hxb
  · rw [hxb, _root_.EReal.bot_add, le_bot_iff, _root_.EReal.eq_bot_iff_forall_lt]
    intro r
    refine lt_of_le_of_lt (key (r - (g y).toReal - 1) (g y).toReal (by rw [hxb]; simp) hyr) ?_
    have hr : (r - (g y).toReal - 1 + (g y).toReal : ℝ) < r := by linarith
    exact_mod_cast hr
  rcases eq_or_ne (g y) ⊥ with hyb | hyb
  · rw [hyb, _root_.EReal.add_bot, le_bot_iff, _root_.EReal.eq_bot_iff_forall_lt]
    intro r
    refine lt_of_le_of_lt (key (g x).toReal (r - (g x).toReal - 1) hxr (by rw [hyb]; simp)) ?_
    have hr : ((g x).toReal + (r - (g x).toReal - 1) : ℝ) < r := by linarith
    exact_mod_cast hr
  · have hxe : g x = (((g x).toReal : ℝ) : EReal) := (_root_.EReal.coe_toReal hx hxb).symm
    have hye : g y = (((g y).toReal : ℝ) : EReal) := (_root_.EReal.coe_toReal hy hyb).symm
    rw [hxe, hye, ← _root_.EReal.coe_add]
    exact key _ _ hxr hyr

end PosHomGenAux

section Domains

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {ι : Sort*}

/-- **The effective domain of the convex hull of a family** is the convex hull of the union of the
effective domains: `Prod.fst` is linear, so it carries the convex hull of the union of epigraphs to
the convex hull of the union of their projections. -/
theorem dom_convFn (g : ι → E → EReal) :
    dom (convFn g) = convexHull ℝ (⋃ i, dom (g i)) := by
  have hfst : (Prod.fst : E × ℝ → E) = ⇑(LinearMap.fst ℝ E ℝ) := rfl
  rw [convFn, dom_ofEpi, hfst, LinearMap.image_convexHull, Set.image_iUnion]
  exact congrArg _ (Set.iUnion_congr fun i => (dom_eq_fst_image_epi (g i)).symm)

/-- **A linear inequality valid on every `dom (g i)` is valid on `dom (posHomGen (convFn g))`.**
`dom k₁` is the convex cone generated by the sets `dom fᵢ*`; this is the only consequence of that
description the refinement uses. -/
theorem dom_posHomGen_convFn_subset (ψ : E →ₗ[ℝ] ℝ) {g : ι → E → EReal}
    (hg : ∀ i, dom (g i) ⊆ {y : E | ψ y ≤ 0}) :
    dom (posHomGen (convFn g)) ⊆ {y : E | ψ y ≤ 0} := by
  have hconv : Convex ℝ {y : E | ψ y ≤ 0} := convex_halfSpace_le ψ.isLinear 0
  have hhull : dom (convFn g) ⊆ {y : E | ψ y ≤ 0} := by
    rw [dom_convFn]
    exact convexHull_min (Set.iUnion_subset hg) hconv
  rw [dom_posHomGen (convexFn_convFn g)]
  rintro y (hy | hy)
  · rw [Set.mem_singleton_iff] at hy
    simp [hy]
  · obtain ⟨a, ha, u, hu, rfl⟩ := by simpa using hy
    change ψ (a • u) ≤ 0
    rw [map_smul, smul_eq_mul]
    exact mul_nonpos_of_nonneg_of_nonpos ha.le (hhull hu)

end Domains

section Reflection

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]
  {f : E → EReal}

/-- The reflection `(x, μ) ↦ (-x, μ)` of `E × ℝ`, as a linear map. It carries `epi f` to
`epi (f ∘ -·)`. -/
noncomputable def reflectFst (E : Type*) [AddCommGroup E] [Module ℝ E] :
    (E × ℝ) →ₗ[ℝ] E × ℝ :=
  LinearMap.prodMap (-LinearMap.id) LinearMap.id

@[simp] theorem reflectFst_apply (p : E × ℝ) : reflectFst E p = (-p.1, p.2) := rfl

/-- The epigraph of `x ↦ f (-x)` is the reflection of the epigraph of `f`. -/
theorem epi_comp_neg (f : E → EReal) :
    epi (fun x => f (-x)) = reflectFst E '' epi f := by
  ext p
  constructor
  · intro hp
    exact ⟨(-p.1, p.2), mk_mem_epi.2 (mem_epi.1 hp), by simp⟩
  · rintro ⟨q, hq, rfl⟩
    rw [mem_epi]
    simpa using mk_mem_epi.1 hq

omit [Module ℝ E] in
/-- The effective domain of `x ↦ f (-x)` is `-dom f`. -/
theorem dom_comp_neg (f : E → EReal) : dom (fun x => f (-x)) = -dom f := by
  ext x
  rw [Set.mem_neg, mem_dom, mem_dom]

omit [Module ℝ E] in
/-- A function proper at `-x` is proper. -/
theorem Proper.comp_neg (hf : Proper f) : Proper (fun x => f (-x)) := by
  obtain ⟨⟨x, hx⟩, hb⟩ := hf
  exact ⟨⟨-x, by simpa using hx⟩, fun x => hb (-x)⟩

/-- Reflecting the argument reflects the conjugate variable. -/
theorem conj_comp_neg (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (f : E → EReal) (y : F) :
    conj B (fun x => f (-x)) y = conj B f (-y) := by
  rw [conj_apply, conj_apply]
  refine le_antisymm (iSup_le fun x => ?_) (iSup_le fun x => ?_)
  · refine le_trans (le_of_eq ?_) (le_iSup (fun u : E => ((B u (-y) : ℝ) : EReal) - f u) (-x))
    simp
  · refine le_trans (le_of_eq ?_) (le_iSup (fun u : E => ((B u y : ℝ) : EReal) - f (-u)) (-x))
    simp

end Reflection

section Halves

variable {E F : Type*}
  [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F] [FiniteDimensional ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ}

omit [FiniteDimensional ℝ E] [FiniteDimensional ℝ F] in
/-- **Directions of recession, read off the conjugate**: a direction is a direction of recession of
a closed proper convex `g` exactly when the pairing with it is nonpositive on `dom g*`. -/
theorem recessionFn_nonpos_iff_forall_mem_dom_conj [IsCompatiblePairing B] {g : E → EReal}
    (hg : ClosedProperConvexFn g) (y : E) :
    recessionFn g y ≤ 0 ↔ ∀ x' ∈ dom (conj B g), B y x' ≤ 0 := by
  rw [recessionFn_eq_supportFn_dom_conj (B := B) hg]
  constructor
  · intro h x' hx'
    have h1 := le_trans (le_supportFn (B := B.flip) hx' y) h
    exact_mod_cast h1
  · intro h
    have h1 : supportFn B.flip (dom (conj B g)) y ≤ ((0 : ℝ) : EReal) :=
      supportFn_le_coe_iff.2 fun x' hx' => h x' hx'
    simpa using h1

omit [FiniteDimensional ℝ E] [FiniteDimensional ℝ F] in
/-- **`kⱼ*` is the indicator of `Cⱼ`.** For a family of closed proper convex functions, the
conjugate of the positively homogeneous convex function generated by `conv {gᵢ*}` is the indicator
of `{x ∣ gᵢ(x) ≤ 0 for every i}`. The conjugate of a convex hull is the pointwise supremum, and the
**Fenchel–Moreau theorem** closes the loop; it is used below for both `k₀` and `k₁`. -/
theorem conj_posHomGen_convFn_conj [IsCompatiblePairing B] [IsCompatiblePairing B.flip]
    {ι : Type*} {g : ι → E → EReal} (hg : ∀ i, ClosedProperConvexFn (g i)) :
    conj B.flip (posHomGen (convFn fun i => conj B (g i)))
      = indicatorFn {x : E | ∀ i, g i x ≤ 0} := by
  have hconj : conj B.flip (convFn fun i => conj B (g i)) = ⨆ i, g i := by
    rw [conj_convFn]
    exact iSup_congr fun i => biconj_eq_self (hg i).convex (hg i).closed
  rw [conj_posHomGen, hconj]
  congr 1
  ext x
  simp only [Set.mem_ofPred_eq, iSup_apply]
  exact ⟨fun hx i => le_trans (le_iSup (fun j => g j x) i) hx, fun hx => iSup_le hx⟩

omit [FiniteDimensional ℝ E] in
/-- **The affine half `k₀` is polyhedral.** The positively homogeneous convex function generated by
the convex hull of the conjugates of finitely many *affine* functions is polyhedral, and so is its
effective domain: a convex hull of finitely many polyhedral epigraphs is polyhedral, and by
`epi_conj_affineFn` each `fᵢ*` is a point indicator whose epigraph is a single translated vertical
ray. -/
theorem polyhedralFn_posHomGen_convFn_conj_affineFn (hB : B.SeparatingRight)
    {ι : Type*} [Finite ι] {g : ι → E → EReal}
    (hg : ∀ i, ∃ (a : F) (c : ℝ), g i = affineFn B a c) :
    PolyhedralFn (posHomGen (convFn fun i => conj B (g i))) := by
  choose a c hac using hg
  refine polyhedralFn_posHomGen_convFn (p := fun i => (a i, c i)) fun i => ?_
  rw [hac i]
  exact epi_conj_affineFn hB (a i) (c i)

omit [FiniteDimensional ℝ E] in
/-- **The separation step**: `(-dom k₀) ∩ ri (dom k₁)` is nonempty. Both sets contain the origin,
so a separating hyperplane passes through it. If they could be separated properly without the
hyperplane containing `dom k₁` — the only way they can miss each other, `dom k₀` being polyhedral —
the separating direction would be a common direction of recession of the whole family, hence a
direction of *constancy* for the `g₁`, and then the hyperplane would contain `dom k₁` after all. -/
theorem nonempty_neg_dom_inter_relint_dom [IsCompatiblePairing B] [IsCompatiblePairing B.flip]
    {ι₀ ι₁ : Type*} {g₀ : ι₀ → E → EReal} {g₁ : ι₁ → E → EReal}
    (hg₀ : ∀ i, ClosedProperConvexFn (g₀ i)) (hg₁ : ∀ i, ClosedProperConvexFn (g₁ i))
    (hpoly : PolyhedralFn (posHomGen (convFn fun i => conj B (g₀ i))))
    (hrec : ∀ y : E, (∀ i, recessionFn (g₀ i) y ≤ 0) → (∀ i, recessionFn (g₁ i) y ≤ 0) →
      ∀ i, recessionFn (g₁ i) (-y) ≤ 0) :
    ((-dom (posHomGen (convFn fun i => conj B (g₀ i)))) ∩
      ri (dom (posHomGen (convFn fun i => conj B (g₁ i))))).Nonempty := by
  classical
  set k₀ : F → EReal := posHomGen (convFn fun i => conj B (g₀ i)) with hk₀
  set k₁ : F → EReal := posHomGen (convFn fun i => conj B (g₁ i)) with hk₁
  have hmem₀ : (0 : F) ∈ dom k₀ :=
    mem_dom.2 (lt_of_le_of_ne le_top (posHomGen_apply_zero_ne_top _))
  have hmem₁ : (0 : F) ∈ dom k₁ :=
    mem_dom.2 (lt_of_le_of_ne le_top (posHomGen_apply_zero_ne_top _))
  have hsub₀ : ∀ i, dom (conj B (g₀ i)) ⊆ dom k₀ := fun i y hy =>
    lt_of_le_of_lt (le_trans (posHomGen_le _ y) (convFn_le _ i y)) hy
  have hsub₁ : ∀ i, dom (conj B (g₁ i)) ⊆ dom k₁ := fun i y hy =>
    lt_of_le_of_lt (le_trans (posHomGen_le _ y) (convFn_le _ i y)) hy
  by_contra hcon
  rw [Set.not_nonempty_iff_eq_empty] at hcon
  obtain ⟨φ, c, hsep, hns⟩ := (exists_separates_not_subset_iff_disjoint_relint
    hpoly.polyhedral_dom.neg (convexFn_posHomGen _).convex_dom ⟨0, hmem₁⟩).2
    (Set.disjoint_iff_inter_eq_empty.2 hcon)
  have hmemneg : (0 : F) ∈ -dom k₀ := by simpa using hmem₀
  have hc0 : c = 0 := by
    have h1 : φ 0 ≤ c := hsep.le_of_mem_left hmemneg
    have h2 : c ≤ φ 0 := hsep.le_of_mem_right hmem₁
    rw [map_zero] at h1 h2
    linarith
  obtain ⟨w, hw, hwne⟩ : ∃ w ∈ dom k₁, φ w ≠ c := by
    by_contra hcon2
    push Not at hcon2
    exact hns fun w hw => hcon2 w hw
  have hwpos : 0 < φ w := lt_of_le_of_ne (hc0 ▸ hsep.le_of_mem_right hw) (Ne.symm (hc0 ▸ hwne))
  obtain ⟨y, hy⟩ := exists_pairing_eq B.flip φ
  have hrec₀ : ∀ i, recessionFn (g₀ i) (-y) ≤ 0 := by
    intro i
    rw [recessionFn_nonpos_iff_forall_mem_dom_conj (B := B) (hg₀ i)]
    intro x' hx'
    have hmem : -x' ∈ -dom k₀ := by simpa using hsub₀ i hx'
    have h1 : φ (-x') ≤ c := hsep.le_of_mem_left hmem
    rw [hy (-x'), hc0] at h1
    have h2 : B y (-x') ≤ 0 := h1
    rw [map_neg] at h2 ⊢
    simpa using h2
  have hrec₁ : ∀ i, recessionFn (g₁ i) (-y) ≤ 0 := by
    intro i
    rw [recessionFn_nonpos_iff_forall_mem_dom_conj (B := B) (hg₁ i)]
    intro x' hx'
    have h1 : c ≤ φ x' := hsep.le_of_mem_right (hsub₁ i hx')
    rw [hy x', hc0] at h1
    have h2 : (0 : ℝ) ≤ B y x' := h1
    rw [map_neg]
    simpa using h2
  have hback : ∀ i, recessionFn (g₁ i) y ≤ 0 := by
    have h := hrec (-y) hrec₀ hrec₁
    simpa using h
  have hdom₁ : dom k₁ ⊆ {x' : F | (B y) x' ≤ 0} :=
    dom_posHomGen_convFn_subset (B y) fun i x' hx' =>
      (recessionFn_nonpos_iff_forall_mem_dom_conj (B := B) (hg₁ i) y).1 (hback i) x' hx'
  have hfin : B y w ≤ 0 := hdom₁ hw
  rw [hy w] at hwpos
  exact absurd hfin (not_le.2 hwpos)

omit [FiniteDimensional ℝ E] in
/-- Reflecting the argument of a polyhedral convex function leaves it polyhedral. -/
theorem PolyhedralFn.comp_neg {g : F → EReal} (hg : PolyhedralFn g) :
    PolyhedralFn (fun y => g (-y)) := by
  have h : Polyhedral (epi (fun y => g (-y))) := by
    rw [epi_comp_neg]
    exact Polyhedral.image hg _
  exact h

/-- **The heart of the refinement**: if the two half-systems `{g₀ i}` and `{g₁ i}` have no common
solution of `gᵢ(x) ≤ 0`, if `k₀` is polyhedral, and if every common direction of recession of the
whole family is a direction of *constancy* of the `g₁`, then any positively homogeneous convex
minorant `k` of both `k₀` and `k₁` has `k(0) = -∞`.

Separation puts a `z` in `(-dom k₀) ∩ ri (dom k₁)`; if either `kⱼ` is improper there, `k(0) = -∞`
at once; otherwise the conjugate of the sum `k₀(-·) + k₁` is the infimal convolution of the two
conjugates, which are the indicators of the two solution sets, and those have empty intersection.
The textbook applies this to `k = conv {k₀, k₁}`, but only through `k(0) ≤ k₀(-z) + k₁(z)`, which
needs nothing of `k` beyond `k ≤ k₀`, `k ≤ k₁` and subadditivity. -/
theorem apply_zero_eq_bot_of_le_of_le [IsCompatiblePairing B] [IsCompatiblePairing B.flip]
    {ι₀ ι₁ : Type*} {g₀ : ι₀ → E → EReal} {g₁ : ι₁ → E → EReal}
    (hg₀ : ∀ i, ClosedProperConvexFn (g₀ i)) (hg₁ : ∀ i, ClosedProperConvexFn (g₁ i))
    (hpoly : PolyhedralFn (posHomGen (convFn fun i => conj B (g₀ i))))
    (hrec : ∀ y : E, (∀ i, recessionFn (g₀ i) y ≤ 0) → (∀ i, recessionFn (g₁ i) y ≤ 0) →
      ∀ i, recessionFn (g₁ i) (-y) ≤ 0)
    (hempty : ¬ ∃ x : E, (∀ i, g₀ i x ≤ 0) ∧ (∀ i, g₁ i x ≤ 0))
    {k : F → EReal} (hk : PosHomogeneous k) (hkc : ConvexFn k)
    (hle₀ : k ≤ posHomGen (convFn fun i => conj B (g₀ i)))
    (hle₁ : k ≤ posHomGen (convFn fun i => conj B (g₁ i))) :
    k 0 = ⊥ := by
  classical
  set k₀ : F → EReal := posHomGen (convFn fun i => conj B (g₀ i)) with hk₀def
  set k₁ : F → EReal := posHomGen (convFn fun i => conj B (g₁ i)) with hk₁def
  obtain ⟨z, hz₀, hz₁⟩ := nonempty_neg_dom_inter_relint_dom hg₀ hg₁ hpoly hrec
  have hzd₀ : k₀ (-z) < ⊤ := mem_dom.1 (Set.mem_neg.1 hz₀)
  have hzd₁ : k₁ z < ⊤ := mem_dom.1 (intrinsicInterior_subset hz₁)
  -- Subadditivity of `k` at the points where both `kⱼ` are finite.
  have hsub : ∀ w : F, k₀ (-w) ≠ ⊤ → k₁ w ≠ ⊤ → k 0 ≤ k₀ (-w) + k₁ w := by
    intro w hw₀ hw₁
    have h1 : k (-w) ≠ ⊤ := fun hc => hw₀ (top_le_iff.1 (hc ▸ hle₀ (-w)))
    have h2 : k w ≠ ⊤ := fun hc => hw₁ (top_le_iff.1 (hc ▸ hle₁ w))
    have h3 := hk.add_le_add_of_ne_top hkc h1 h2
    rw [neg_add_cancel] at h3
    exact le_trans h3 (add_le_add (hle₀ (-w)) (hle₁ w))
  by_cases hb : k₀ (-z) = ⊥ ∨ k₁ z = ⊥
  · refine le_bot_iff.1 ?_
    have h := hsub z (ne_of_lt hzd₀) (ne_of_lt hzd₁)
    rcases hb with hb | hb
    · rwa [hb, _root_.EReal.bot_add] at h
    · rwa [hb, _root_.EReal.add_bot] at h
  push Not at hb
  -- Both `kⱼ` are proper: `k₀` is polyhedral hence lower semicontinuous, and `z` is a relative
  -- interior point of `dom k₁`.
  have hp₀ : Proper k₀ := by
    by_contra hnp
    exact hb.1 (ConvexFn.eq_bot_of_mem_closure_dom (convexFn_posHomGen _)
      hpoly.lowerSemicontinuous hnp (subset_closure (Set.mem_neg.1 hz₀)))
  have hp₁ : Proper k₁ := by
    by_contra hnp
    exact hb.2 (ConvexFn.eq_bot_of_mem_relint_dom (convexFn_posHomGen _) hnp hz₁)
  -- the conjugate of a sum splits as an infimal convolution, for `g = k₀(-·)` and `k₁`.
  have hgpoly : PolyhedralFn (fun w : F => k₀ (-w)) := hpoly.comp_neg
  have hgproper : Proper (fun w : F => k₀ (-w)) := hp₀.comp_neg
  have hgdom : z ∈ dom (fun w : F => k₀ (-w)) := by rw [dom_comp_neg]; exact hz₀
  have hexact : IsExactSum B.flip (fun w : F => k₀ (-w)) k₁ :=
    IsExactSum.of_polyhedral hgpoly hgproper (convexFn_posHomGen _) hp₁ hgdom hz₁
  -- the two conjugates are the indicators of the two solution sets
  have hconj₀ : conj B.flip k₀ = indicatorFn {x : E | ∀ i, g₀ i x ≤ 0} :=
    conj_posHomGen_convFn_conj hg₀
  have hconj₁ : conj B.flip k₁ = indicatorFn {x : E | ∀ i, g₁ i x ≤ 0} :=
    conj_posHomGen_convFn_conj hg₁
  have htop : conj B.flip ((fun w : F => k₀ (-w)) + k₁) 0 = ⊤ := by
    rw [hexact.conj_add_apply]
    refine le_antisymm le_top (le_iInf fun y => ?_)
    rw [zero_sub, conj_comp_neg, neg_neg, hconj₀, hconj₁]
    have hne : ¬ ((∀ i, g₀ i y ≤ 0) ∧ ∀ i, g₁ i y ≤ 0) := fun hc => hempty ⟨y, hc⟩
    rcases not_and_or.1 hne with h | h
    · rw [indicatorFn_of_notMem (show y ∉ {x : E | ∀ i, g₀ i x ≤ 0} from h)]
      exact le_of_eq (_root_.EReal.top_add_of_ne_bot (indicatorFn_ne_bot _ y)).symm
    · rw [indicatorFn_of_notMem (show y ∉ {x : E | ∀ i, g₁ i x ≤ 0} from h)]
      exact le_of_eq (_root_.EReal.add_top_of_ne_bot (indicatorFn_ne_bot _ y)).symm
  -- `k(0)` is below the sum everywhere, and the sum has infimum `-∞`.
  have hfinal : ∀ w : F, k 0 ≤ ((fun w : F => k₀ (-w)) + k₁) w := by
    intro w
    rw [Pi.add_apply]
    by_cases hw₀ : k₀ (-w) = ⊤
    · rw [hw₀, _root_.EReal.top_add_of_ne_bot (hp₁.ne_bot w)]
      exact le_top
    by_cases hw₁ : k₁ w = ⊤
    · rw [hw₁, _root_.EReal.add_top_of_ne_bot (hp₀.ne_bot (-w))]
      exact le_top
    exact hsub w hw₀ hw₁
  have hle : conj B.flip ((fun w : F => k₀ (-w)) + k₁) 0 ≤ -(k 0) := by
    rw [conj_apply]
    refine iSup_le fun w => ?_
    have h0 : ((B.flip w 0 : ℝ) : EReal) = 0 := by simp
    rw [h0, zero_sub]
    exact _root_.EReal.neg_le_neg_iff.2 (hfinal w)
  rw [htop] at hle
  have h2 : -(k 0) = ⊤ := top_le_iff.1 hle
  have h3 := congrArg (fun a : EReal => -a) h2
  simpa using h3

omit [FiniteDimensional ℝ E] [FiniteDimensional ℝ F] in
/-- An affine function of a continuous pairing is closed, proper and convex. -/
theorem closedProperConvexFn_affineFn [IsContinuousPairing B] (a : F) (c : ℝ) :
    ClosedProperConvexFn (affineFn B a c) :=
  ⟨convexFn_affineFn a c, closedFn_affineFn (continuous_pairing B a), proper_affineFn a c⟩

omit [FiniteDimensional ℝ E] [FiniteDimensional ℝ F] in
/-- The effective domain of the conjugate of an affine function is the single point `a`. -/
theorem dom_conj_affineFn (hB : B.SeparatingRight) (a : F) (c : ℝ) :
    dom (conj B (affineFn B a c)) = {a} := by
  ext y
  rw [mem_dom]
  by_cases hy : y = a
  · subst hy
    rw [conj_affineFn_apply_self]
    simp
  · rw [conj_affineFn_apply_of_ne hB hy]
    simp [hy]

omit [FiniteDimensional ℝ E] [FiniteDimensional ℝ F] in
/-- A direction of recession of the affine function `⟨·, a⟩ - c` is one that pairs nonpositively
with `a`: the effective domain of its conjugate is the single point `a`. -/
theorem recessionFn_affineFn_nonpos_iff [IsCompatiblePairing B] (hB : B.SeparatingRight)
    (a : F) (c : ℝ) (y : E) :
    recessionFn (affineFn B a c) y ≤ 0 ↔ B y a ≤ 0 := by
  rw [recessionFn_nonpos_iff_forall_mem_dom_conj (B := B) (closedProperConvexFn_affineFn a c) y,
    dom_conj_affineFn hB]
  simp

omit [FiniteDimensional ℝ F] in
/-- **Every polyhedral convex set is cut out by finitely many inequalities of the pairing.** The
usual definition uses linear functionals; in finite dimensions a compatible pairing represents
every one of them, which lets the refined Helly theorem replace the polyhedral members of a family
by half-spaces described by affine functions of the pairing. -/
theorem Polyhedral.exists_finset_pairing [IsCompatiblePairing B] {C : Set E} (hC : Polyhedral C) :
    ∃ s : Finset (F × ℝ), C = {x : E | ∀ q ∈ s, B x q.1 ≤ q.2} := by
  classical
  have hrep : ∀ φ : E →ₗ[ℝ] ℝ, ∃ a : F, ∀ x, φ x = B x a := by
    intro φ
    obtain ⟨a, ha⟩ := exists_pairing_eq B (LinearMap.toContinuousLinearMap φ)
    exact ⟨a, fun x => ha x⟩
  choose rep hrep using hrep
  obtain ⟨t, ht⟩ := hC
  refine ⟨t.image fun q => (rep q.1, q.2), ?_⟩
  rw [ht]
  ext x
  simp only [Set.mem_ofPred_eq, Finset.mem_image]
  constructor
  · rintro h p ⟨q, hq, rfl⟩
    rw [← hrep q.1 x]
    exact h q hq
  · intro h q hq
    rw [hrep q.1 x]
    exact h (rep q.1, q.2) ⟨q, hq, rfl⟩

omit [FiniteDimensional ℝ E] [FiniteDimensional ℝ F] in
/-- A direction pairing nonpositively with every constraint vector recedes in the polyhedron those
constraints cut out. -/
theorem mem_recessionCone_of_forall_pairing_nonpos {t : Finset (F × ℝ)} {y : E}
    (hy : ∀ q ∈ t, B y q.1 ≤ 0) :
    y ∈ recessionCone {x : E | ∀ q ∈ t, B x q.1 ≤ q.2} := by
  intro x hx a ha q hq
  have hval : B (x + a • y) q.1 = B x q.1 + a * B y q.1 := by
    rw [map_add, LinearMap.add_apply, map_smul, LinearMap.smul_apply, smul_eq_mul]
  have hxq : B x q.1 ≤ q.2 := hx q hq
  have hterm : a * B y q.1 ≤ 0 := mul_nonpos_of_nonneg_of_nonpos ha (hy q hq)
  rw [hval]
  linarith

omit [FiniteDimensional ℝ E] [FiniteDimensional ℝ F] in
/-- **The constancy space of an indicator function is the lineality space of the set.** This is
what turns "a direction in which `Cᵢ` is linear" into "a direction in which `fᵢ` is constant". -/
theorem constancySpace_indicatorFn {C : Set E} (hC : C.Nonempty) :
    constancySpace (indicatorFn C) = linealitySpace C := by
  have hle : ∀ z : E, indicatorFn (recessionCone C) z ≤ 0 ↔ z ∈ recessionCone C := by
    intro z
    by_cases hz : z ∈ recessionCone C
    · simp [hz]
    · simp [hz]
  ext y
  rw [mem_constancySpace, mem_linealitySpace, recessionFn_indicatorFn hC, hle, hle]

end Halves

section Refined

variable {E F : Type*}
  [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F] [FiniteDimensional ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} {ι : Type*} {f : ι → E → EReal}

/-- **The refined alternative over the whole space.** The recession hypothesis may be weakened: it
is enough that there be a **finite** set of indices `I₀` on which the `fᵢ` are affine, such that
every direction of recession common to *all* the `fᵢ` is a direction in which `fᵢ` is **constant**
for every `i ∉ I₀`. The unrefined hypothesis — that the only common direction of recession is `0` —
implies this one with `I₀ = ∅`. The gain is that the affine members may now recede, and so may the
others provided they are flat in every direction the whole family recedes in. Only one step of the
unrefined proof changes: the passage to `k(0) = -∞`, which is here
`apply_zero_eq_bot_of_le_of_le`. -/
theorem alternative_infinite_system_univ_of_affine_tail [IsCompatiblePairing B]
    [IsCompatiblePairing B.flip] (hB : B.SeparatingRight)
    (hf : ∀ i, ClosedProperConvexFn (f i)) (I₀ : Finset ι)
    (haff : ∀ i ∈ I₀, ∃ (a : F) (c : ℝ), f i = affineFn B a c)
    (hrec : ∀ y : E, (∀ i, recessionFn (f i) y ≤ 0) → ∀ i ∉ I₀, y ∈ constancySpace (f i)) :
    (∃ x : E, ∀ i, f i x ≤ 0) ∨
      ∃ (t : Finset ι) (l : ι → ℝ) (ε : ℝ), (∀ i, 0 ≤ l i) ∧ (∀ i ∉ t, l i = 0) ∧ 0 < ε ∧
        t.card ≤ Module.finrank ℝ E + 1 ∧
        ∀ x : E, (ε : EReal) ≤ ∑ i ∈ t, (l i : EReal) * f i x := by
  classical
  by_cases halt : ∃ x : E, ∀ i, f i x ≤ 0
  · exact Or.inl halt
  refine Or.inr (exists_multipliers_of_posHomGen_convFn_conj_eq_bot (B := B) hf ?_)
  have hg₀ : ∀ j : {i // i ∈ I₀}, ClosedProperConvexFn ((fun j : {i // i ∈ I₀} => f j.1) j) :=
    fun j => hf j.1
  have hg₁ : ∀ j : {i // i ∉ I₀}, ClosedProperConvexFn ((fun j : {i // i ∉ I₀} => f j.1) j) :=
    fun j => hf j.1
  have hpoly : PolyhedralFn
      (posHomGen (convFn fun j : {i // i ∈ I₀} => conj B ((fun j => f j.1) j))) :=
    polyhedralFn_posHomGen_convFn_conj_affineFn hB fun j => haff j.1 j.2
  have hrec' : ∀ y : E, (∀ j : {i // i ∈ I₀}, recessionFn (f j.1) y ≤ 0) →
      (∀ j : {i // i ∉ I₀}, recessionFn (f j.1) y ≤ 0) →
      ∀ j : {i // i ∉ I₀}, recessionFn (f j.1) (-y) ≤ 0 := by
    intro y h0 h1 j
    have hall : ∀ i, recessionFn (f i) y ≤ 0 := by
      intro i
      by_cases hi : i ∈ I₀
      · exact h0 ⟨i, hi⟩
      · exact h1 ⟨i, hi⟩
    exact (mem_constancySpace.1 (hrec y hall j.1 j.2)).2
  have hempty : ¬ ∃ x : E, (∀ j : {i // i ∈ I₀}, f j.1 x ≤ 0) ∧
      ∀ j : {i // i ∉ I₀}, f j.1 x ≤ 0 := by
    rintro ⟨x, h0, h1⟩
    refine halt ⟨x, fun i => ?_⟩
    by_cases hi : i ∈ I₀
    · exact h0 ⟨i, hi⟩
    · exact h1 ⟨i, hi⟩
  have hle₀ : posHomGen (convFn fun i => conj B (f i))
      ≤ posHomGen (convFn fun j : {i // i ∈ I₀} => conj B (f j.1)) :=
    posHomGen_mono (le_convFn (convexFn_convFn _) fun j => convFn_le _ j.1)
  have hle₁ : posHomGen (convFn fun i => conj B (f i))
      ≤ posHomGen (convFn fun j : {i // i ∉ I₀} => conj B (f j.1)) :=
    posHomGen_mono (le_convFn (convexFn_convFn _) fun j => convFn_le _ j.1)
  exact apply_zero_eq_bot_of_le_of_le hg₀ hg₁ hpoly hrec' hempty
    (posHomogeneous_posHomGen _) (convexFn_posHomGen _) hle₀ hle₁

/-- **The solvability criterion under the refined hypothesis.** An infinite system of weak convex
inequalities is solvable as soon as every subsystem of at most `n + 1` of the inequalities is
solvable to within an arbitrarily small tolerance — provided that, outside a finite set of indices
carrying affine functions, every common direction of recession is a direction of constancy. -/
theorem exists_forall_le_zero_of_forall_subsystem_of_affine_tail [IsCompatiblePairing B]
    [IsCompatiblePairing B.flip] (hB : B.SeparatingRight)
    (hf : ∀ i, ClosedProperConvexFn (f i)) (I₀ : Finset ι)
    (haff : ∀ i ∈ I₀, ∃ (a : F) (c : ℝ), f i = affineFn B a c)
    (hrec : ∀ y : E, (∀ i, recessionFn (f i) y ≤ 0) → ∀ i ∉ I₀, y ∈ constancySpace (f i))
    (hsub : ∀ δ : ℝ, 0 < δ → ∀ S : Finset ι, S.card ≤ Module.finrank ℝ E + 1 →
      ∃ x : E, ∀ i ∈ S, f i x < (δ : EReal)) :
    ∃ x : E, ∀ i, f i x ≤ 0 := by
  rcases alternative_infinite_system_univ_of_affine_tail hB hf I₀ haff hrec with
    hgood | ⟨t, l, ε, hl0, -, hε, hcard, hineq⟩
  · exact hgood
  refine absurd (fun x (_ : x ∈ (Set.univ : Set E)) => hineq x)
    (not_forall_le_weighted_of_forall_subsystem (C := (Set.univ : Set E)) ⟨0, Set.mem_univ 0⟩
      hl0 hε hcard fun δ hδ S hS => ?_)
  obtain ⟨x, hx⟩ := hsub δ hδ S hS
  exact ⟨x, Set.mem_univ x, hx⟩

/-- **The refined Helly theorem.** The recession hypothesis of Helly's theorem for infinite
families may be weakened: it is enough that there be a **finite** set of indices `I₀` on which the
`Cᵢ` are polyhedral, such that every direction of recession common to *all* the `Cᵢ` is a direction
in which `Cᵢ` is **linear** for every `i ∉ I₀`. Compare `helly_of_no_common_recession`, whose
hypothesis is that the only common direction of recession is `0`. Each polyhedral `Cᵢ`, `i ∈ I₀`,
is replaced by the finitely many closed half-spaces cutting it out, and the refined alternative
applies with those as its affine part. -/
theorem helly_of_polyhedral_tail [IsCompatiblePairing B] [IsCompatiblePairing B.flip]
    (hB : B.SeparatingRight) {K : ι → Set E}
    (hconv : ∀ i, Convex ℝ (K i)) (hcl : ∀ i, IsClosed (K i)) (hne : ∀ i, (K i).Nonempty)
    (I₀ : Finset ι) (hpoly : ∀ i ∈ I₀, Polyhedral (K i))
    (hrec : ∀ y : E, (∀ i, y ∈ recessionCone (K i)) → ∀ i ∉ I₀, y ∈ linealitySpace (K i))
    (hinter : ∀ S : Finset ι, S.card ≤ Module.finrank ℝ E + 1 → (⋂ i ∈ S, K i).Nonempty) :
    (⋂ i, K i).Nonempty := by
  classical
  have hex : ∀ j : {i // i ∈ I₀},
      ∃ t : Finset (F × ℝ), K j.1 = {x : E | ∀ q ∈ t, B x q.1 ≤ q.2} :=
    fun j => Polyhedral.exists_finset_pairing (hpoly j.1 j.2)
  choose t ht using hex
  set g : ({i // i ∉ I₀} ⊕ ((j : {i // i ∈ I₀}) × {q : F × ℝ // q ∈ t j})) → E → EReal :=
    Sum.elim (fun j => indicatorFn (K j.1)) (fun p => affineFn B p.2.1.1 p.2.1.2) with hgdef
  have hg_inl : ∀ j, g (Sum.inl j) = indicatorFn (K j.1) := fun _ => rfl
  have hg_inr : ∀ p, g (Sum.inr p) = affineFn B p.2.1.1 p.2.1.2 := fun _ => rfl
  set J₀ : Finset ({i // i ∉ I₀} ⊕ ((j : {i // i ∈ I₀}) × {q : F × ℝ // q ∈ t j})) :=
    Finset.image Sum.inr Finset.univ with hJ₀def
  have hmemJ₀ : ∀ p, Sum.inr p ∈ J₀ := fun p => Finset.mem_image.2 ⟨p, Finset.mem_univ p, rfl⟩
  have hnotJ₀ : ∀ j, (Sum.inl j : _) ∉ J₀ := by
    intro j hj
    obtain ⟨p, -, hp⟩ := Finset.mem_image.1 hj
    exact absurd hp (by simp)
  have hgc : ∀ i, ClosedProperConvexFn (g i) := by
    rintro (j | p)
    · rw [hg_inl]
      exact ⟨convexFn_indicatorFn.2 (hconv j.1), closedFn_indicatorFn (hcl j.1),
        ⟨by rw [dom_indicatorFn]; exact hne j.1, indicatorFn_ne_bot (K j.1)⟩⟩
    · rw [hg_inr]
      exact closedProperConvexFn_affineFn _ _
  have haff : ∀ i ∈ J₀, ∃ (a : F) (c : ℝ), g i = affineFn B a c := by
    rintro (j | p) hi
    · exact absurd hi (hnotJ₀ j)
    · exact ⟨p.2.1.1, p.2.1.2, hg_inr p⟩
  have hrecg : ∀ y : E, (∀ i, recessionFn (g i) y ≤ 0) → ∀ i ∉ J₀, y ∈ constancySpace (g i) := by
    rintro y hy (j | p) hi
    · have hall : ∀ i : ι, y ∈ recessionCone (K i) := by
        intro i
        by_cases hi₀ : i ∈ I₀
        · rw [ht ⟨i, hi₀⟩]
          refine mem_recessionCone_of_forall_pairing_nonpos fun q hq => ?_
          have h := hy (Sum.inr ⟨⟨i, hi₀⟩, ⟨q, hq⟩⟩)
          rw [hg_inr] at h
          exact (recessionFn_affineFn_nonpos_iff hB _ _ y).1 h
        · have h := hy (Sum.inl ⟨i, hi₀⟩)
          rw [hg_inl, recessionFn_indicatorFn (hne i)] at h
          by_contra hcon
          rw [indicatorFn_of_notMem hcon] at h
          exact absurd h (by simp)
      rw [hg_inl, constancySpace_indicatorFn (hne j.1)]
      exact hrec y hall j.1 j.2
    · exact absurd (hmemJ₀ p) hi
  have hsubs : ∀ δ : ℝ, 0 < δ →
      ∀ S : Finset ({i // i ∉ I₀} ⊕ ((j : {i // i ∈ I₀}) × {q : F × ℝ // q ∈ t j})),
      S.card ≤ Module.finrank ℝ E + 1 → ∃ x : E, ∀ i ∈ S, g i x < (δ : EReal) := by
    intro δ hδ S hS
    obtain ⟨x, hx⟩ := hinter (S.image (Sum.elim (fun j => j.1) fun p => p.1.1))
      (le_trans (Finset.card_image_le) hS)
    refine ⟨x, ?_⟩
    rintro (j | p) hi
    · have hxK : x ∈ K j.1 :=
        Set.mem_iInter₂.1 hx j.1 (Finset.mem_image.2 ⟨Sum.inl j, hi, rfl⟩)
      rw [hg_inl, indicatorFn_of_mem hxK]
      exact_mod_cast hδ
    · have hxK : x ∈ K p.1.1 :=
        Set.mem_iInter₂.1 hx p.1.1 (Finset.mem_image.2 ⟨Sum.inr p, hi, rfl⟩)
      rw [ht p.1] at hxK
      have hle : B x p.2.1.1 ≤ p.2.1.2 := hxK p.2.1 p.2.2
      rw [hg_inr, affineFn_eq_coe]
      have hlt : B x p.2.1.1 - p.2.1.2 < δ := by linarith
      exact_mod_cast hlt
  obtain ⟨x, hx⟩ :=
    exists_forall_le_zero_of_forall_subsystem_of_affine_tail hB hgc J₀ haff hrecg hsubs
  refine ⟨x, Set.mem_iInter.2 fun i => ?_⟩
  by_cases hi₀ : i ∈ I₀
  · rw [ht ⟨i, hi₀⟩]
    intro q hq
    have h := hx (Sum.inr ⟨⟨i, hi₀⟩, ⟨q, hq⟩⟩)
    rw [hg_inr, affineFn_eq_coe] at h
    have h' : B x q.1 - q.2 ≤ 0 := by exact_mod_cast h
    linarith
  · have h := hx (Sum.inl ⟨i, hi₀⟩)
    by_contra hcon
    rw [hg_inl, indicatorFn_of_notMem hcon] at h
    exact absurd h (by simp)

end Refined

end Tdaf.ConvexAnalysis
