/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Mathlib.Analysis.Convex.Radon
import Tdaf.Analysis.Convex.Operations.Basic
import Tdaf.Analysis.Convex.Polyhedral.Separation
import Tdaf.Analysis.Convex.RelativeInterior

/-!
# Systems of convex inequalities: theorems of the alternative

Rockafellar's §21. The section's engine is **Theorem 21.1**: for proper convex functions
`f₁, …, f_m` that are finite on `ri C`, either the strict system `fᵢ(x) < 0` has a solution in `C`,
or some non-trivial non-negative combination `λ₁f₁ + ⋯ + λ_mf_m` is non-negative on all of `C`.
It is the existence workhorse behind the Lagrange multiplier theorems of §27 and §28.

## Main results

* `alternative_of_convex_system` — **Theorem 21.1**, the substantial half.
* `not_exists_forall_neg_of_forall_zero_le_weighted` — Theorem 21.1, the easy half: the two
  alternatives exclude each other.
* `alternative_of_convex_system_affine` — **Theorem 21.2**, the refinement that keeps affine
  constraints apart and so sharpens alternative (b) to "not all of the `λᵢ` on the *convex*
  constraints vanish".
* `helly_finite` — **Theorem 21.6**, Helly's theorem for finite collections (Mathlib's
  `Convex.helly_theorem'` under the book's number).
* `exists_mem_of_forall_subsystem`, `exists_mem_of_forall_subsystem_lt` — **Corollary 21.6.1**.
* `sparse_alternative_of_convex_system` — **Corollary 21.6.2**: the multipliers of Theorem 21.1 may
  be taken supported on at most `n + 1` indices.

## What is not here

**Theorems 21.3, 21.4, 21.5 and Corollaries 21.3.1, 21.3.2 are not formalised**, and the obstruction
is upstream of §21. Theorem 21.3 — the alternative for *weak* inequalities and *infinite* index sets
— runs through the positively homogeneous convex function generated by `conv {fᵢ* | i ∈ I}`, whose
conjugate is identified by **Theorem 13.5** (deferred in this development), and it extracts the
multipliers by **Corollary 17.1.3**, the directions half of Carathéodory's theorem (§17, not yet
done). Corollaries 21.3.1 and 21.3.2 (Helly's theorem with a recession hypothesis) are corollaries
of 21.3; Theorems 21.4 and 21.5 weaken its recession hypothesis using §20. Theorem 21.6 is
independent of all of them — Rockafellar derives it from Corollary 21.3.2, but Mathlib proves it
directly from Radon's theorem, so nothing here waits on §13 or §17.

## Design notes

**The weighted sum is read in `EReal` with Rockafellar's `0 · ∞ = 0`.** `∑ i, (l i : EReal) * f i x`
is exactly Rockafellar's `λ₁f₁(x) + ⋯ + λ_mf_m(x)`: `EReal` multiplication already sends `0 * ⊤`
to `0`, so a vanishing multiplier silently drops its constraint, which is the convention the
theorem needs.

**The proof is Rockafellar's, with `ℝ^m` read as `ι → ℝ`.** The convex set
`C₁ = {z | ∃ x ∈ C, ∀ i, fᵢ(x) < zᵢ}` is disjoint from the non-positive orthant exactly when the
strict system is unsolvable, and Theorem 11.3 separates the two properly. The separating
functional's coordinates are the multipliers; the non-positive orthant forces them non-negative,
and properness of the separation forces them not all zero.

**The passage from `ri C` to `C` is Corollary 7.3.3.** Separation only delivers the inequality at
points where every `fᵢ` is finite, which is where `ri C ⊆ dom fᵢ` puts them. `ConvexFn.sum` and
`ConvexFn.smul` make the weighted sum a convex function, and `ConvexFn.le_of_mem_closure` carries
its lower bound from `ri C` to `cl (ri C) = cl C ⊇ C`.

**The hypothesis `ri C ⊆ dom fᵢ` is not decoration.** Rockafellar's own counterexample: on `ℝ`
take `f₁ x = -√x` for `x ≥ 0` and `+∞` otherwise, `f₂ x = x`, `C = ℝ`. Neither alternative holds.

**Theorem 21.2 keeps the affine constraints in a separate index type.** Rockafellar splits
`1, …, m` at `k`; here the convex constraints are indexed by `ι` and the affine ones by `κ`, and the
separating space is `(ι ⊕ κ) → ℝ`. The affine constraints enter `C₁` as *equations*
`aⱼ(x) = z(inr j)` rather than inequalities, which is what makes the non-containment clause of
Theorem 20.2 usable, and
they are modelled as `E →ᵃ[ℝ] ℝ` rather than as `EReal`-valued convex functions — an affine function
is real-valued by definition, and the three little lemmas `combo_affine_sum`,
`convexFn_coe_affine_sum` and `eq_zero_of_nonneg_of_mem_relint_affine_sum` supply everything the
proof asks of them without needing the `AffineMap` module structure.

**Theorem 21.1 is the case `κ = Empty` of Theorem 21.2, but is proved independently.** Rockafellar
remarks that §21 can be read without §20 provided Theorems 21.2, 21.4 and 21.5 are skipped, and the
independent proof is what makes that true: 21.1 needs only Theorem 11.3, while 21.2 needs the
polyhedral separation Theorem 20.2. Corollary 28.2.1 uses the cheaper route.

**Corollary 21.6.2 is stated with an explicit support `Finset`.** `∃ S l, S.card ≤ n + 1 ∧
(∀ i ∉ S, l i = 0) ∧ …` avoids having to decide `l i ≠ 0`, and extending the subsystem's multipliers
by zero is harmless in `EReal` precisely because `0 · (+∞) = 0`.

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §21 (Theorems 21.1, 21.2,
  21.6, Corollaries 21.6.1, 21.6.2).
-/

open Set Filter Topology

namespace Tdaf.ConvexAnalysis

section Exclusive

variable {E : Type*} {ι : Type*} [Fintype ι] {C : Set E} {f : ι → E → EReal}

/-- **Rockafellar, Theorem 21.1**, the easy half: the two alternatives exclude each other. A point
of `C` at which every `fᵢ` is negative makes every term of `λ₁f₁ + ⋯ + λ_mf_m` non-positive, and
the terms with `λᵢ ≠ 0` strictly negative. -/
theorem not_exists_forall_neg_of_forall_zero_le_weighted {l : ι → ℝ} (hl : ∀ i, 0 ≤ l i)
    (hl0 : l ≠ 0) (h : ∀ x ∈ C, (0 : EReal) ≤ ∑ i, (l i : EReal) * f i x) :
    ¬ ∃ x ∈ C, ∀ i, f i x < 0 := by
  classical
  rintro ⟨x, hx, hneg⟩
  obtain ⟨j, hj⟩ : ∃ j, l j ≠ 0 := by
    by_contra hcon
    push Not at hcon
    exact hl0 (funext hcon)
  have hjpos : 0 < l j := lt_of_le_of_ne (hl j) (Ne.symm hj)
  have hterm : ∀ i, (l i : EReal) * f i x ≤ 0 := by
    intro i
    rcases eq_or_lt_of_le (hl i) with h0 | h0
    · rw [← h0]; simp
    · calc (l i : EReal) * f i x
          ≤ (l i : EReal) * 0 := by
            refine mul_le_mul_of_nonneg_left (hneg i).le ?_
            exact_mod_cast (hl i)
        _ = 0 := by simp
  have hjneg : (l j : EReal) * f j x < 0 := by
    have hlt : ¬ ((l j : EReal) * 0 ≤ (l j : EReal) * f j x) := by
      rw [EReal.coe_mul_le_coe_mul_iff hjpos]
      exact not_le.2 (hneg j)
    simpa using not_le.1 hlt
  have hrest : ∑ i ∈ Finset.univ.erase j, (l i : EReal) * f i x ≤ 0 :=
    Finset.sum_nonpos fun i _ => hterm i
  have hsum : ∑ i, (l i : EReal) * f i x < 0 := by
    rw [← Finset.add_sum_erase _ _ (Finset.mem_univ j)]
    calc (l j : EReal) * f j x + ∑ i ∈ Finset.univ.erase j, (l i : EReal) * f i x
        ≤ (l j : EReal) * f j x + 0 := add_le_add (le_refl _) hrest
      _ = (l j : EReal) * f j x := add_zero _
      _ < 0 := hjneg
  exact absurd (h x hx) (not_le.2 hsum)

end Exclusive

section Alternative

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
variable {ι : Type*} [Fintype ι] {C : Set E} {f : ι → E → EReal}

/-- **Rockafellar, Theorem 21.1.** For proper convex functions finite on `ri C`, exactly one of the
two alternatives holds: either the strict system `fᵢ(x) < 0` is solvable in `C`, or a non-trivial
non-negative combination of the `fᵢ` is non-negative throughout `C`.

Exclusivity is `not_exists_forall_neg_of_forall_zero_le_weighted`; this is the half with content. -/
theorem alternative_of_convex_system [Nonempty ι] (hC : Convex ℝ C) (hf : ∀ i, ConvexFn (f i))
    (hp : ∀ i, Proper (f i)) (hdom : ∀ i, ri C ⊆ dom (f i)) :
    (∃ x ∈ C, ∀ i, f i x < 0) ∨
      ∃ l : ι → ℝ, (∀ i, 0 ≤ l i) ∧ l ≠ 0 ∧
        ∀ x ∈ C, (0 : EReal) ≤ ∑ i, (l i : EReal) * f i x := by
  classical
  by_cases halt : ∃ x ∈ C, ∀ i, f i x < 0
  · exact Or.inl halt
  refine Or.inr ?_
  have hno : ∀ x ∈ C, ∃ i, (0 : EReal) ≤ f i x := by
    intro x hx
    by_contra hcon
    push Not at hcon
    exact halt ⟨x, hx, hcon⟩
  rcases C.eq_empty_or_nonempty with rfl | hCne
  · refine ⟨fun _ => 1, fun _ => zero_le_one, ?_, by simp⟩
    intro hzero
    have hone := congrFun hzero (Classical.arbitrary ι)
    norm_num at hone
  obtain ⟨y₀, hy₀⟩ := Convex.relint_nonempty hC hCne
  have hfinri : ∀ i, ∀ z ∈ ri C, f i z ≠ ⊤ := fun i z hz => (mem_dom.1 (hdom i hz)).ne
  -- the two convex sets of Rockafellar's proof, in `ι → ℝ`
  set C₁ : Set (ι → ℝ) := {z | ∃ x ∈ C, ∀ i, f i x < ((z i : ℝ) : EReal)} with hC₁def
  set C₂ : Set (ι → ℝ) := {z | ∀ i, z i ≤ 0} with hC₂def
  have hC₁conv : Convex ℝ C₁ := by
    rw [hC₁def]
    rintro z ⟨x, hx, hzx⟩ w ⟨u, hu, hwu⟩ a b ha hb hab
    refine ⟨a • x + b • u, hC hx hu ha hb hab, fun i => ?_⟩
    obtain ⟨rx, hrx⟩ := EReal.exists_coe_of_ne_bot_of_lt_top ((hp i).ne_bot x)
      (lt_of_lt_of_le (hzx i) le_top)
    obtain ⟨ru, hru⟩ := EReal.exists_coe_of_ne_bot_of_lt_top ((hp i).ne_bot u)
      (lt_of_lt_of_le (hwu i) le_top)
    have hrxlt : rx < z i := by
      have h := hzx i; rw [hrx] at h; exact_mod_cast h
    have hrult : ru < w i := by
      have h := hwu i; rw [hru] at h; exact_mod_cast h
    have hcombo : f i (a • x + b • u) ≤ (((a * rx + b * ru : ℝ)) : EReal) :=
      (hf i).epi_combo (le_of_eq hrx) (le_of_eq hru) ha hb hab
    have harith : a * rx + b * ru < a * z i + b * w i := by
      rcases eq_or_lt_of_le ha with h0 | h0
      · have hb1 : b = 1 := by linarith
        rw [← h0, hb1]; simpa using hrult
      · nlinarith
    refine lt_of_le_of_lt hcombo ?_
    have hpi : ((a • z + b • w) i : ℝ) = a * z i + b * w i := by simp
    rw [hpi]
    exact_mod_cast harith
  have hC₁ne : C₁.Nonempty := by
    refine ⟨fun i => (f i y₀).toReal + 1, ?_⟩
    rw [hC₁def]
    refine ⟨y₀, intrinsicInterior_subset hy₀, fun i => ?_⟩
    have hcoe : (((f i y₀).toReal : ℝ) : EReal) = f i y₀ :=
      _root_.EReal.coe_toReal (hfinri i y₀ hy₀) ((hp i).ne_bot y₀)
    rw [← hcoe]
    exact_mod_cast (by linarith : (f i y₀).toReal < (f i y₀).toReal + 1)
  have hC₂conv : Convex ℝ C₂ := by
    rw [hC₂def]
    intro z hz w hw a b ha hb hab i
    have hpi : ((a • z + b • w) i : ℝ) = a * z i + b * w i := by simp
    rw [hpi]
    have h1 : a * z i ≤ 0 := mul_nonpos_of_nonneg_of_nonpos ha (hz i)
    have h2 : b * w i ≤ 0 := mul_nonpos_of_nonneg_of_nonpos hb (hw i)
    linarith
  have hC₂ne : C₂.Nonempty := by
    refine ⟨0, ?_⟩
    rw [hC₂def]
    intro i; simp
  have hdisj : Disjoint C₁ C₂ := by
    rw [Set.disjoint_left]
    intro z hz1 hz2
    rw [hC₁def] at hz1
    rw [hC₂def] at hz2
    obtain ⟨x, hx, hzx⟩ := hz1
    obtain ⟨i, hi⟩ := hno x hx
    have hcast : ((z i : ℝ) : EReal) ≤ 0 := by exact_mod_cast hz2 i
    exact absurd (lt_of_lt_of_le (hzx i) hcast) (not_lt.2 hi)
  obtain ⟨g, c, hsep⟩ :=
    (exists_separatesProperly_iff_disjoint_relint hC₂conv hC₁conv hC₂ne hC₁ne).2
      (Disjoint.mono intrinsicInterior_subset intrinsicInterior_subset hdisj.symm)
  -- the multipliers are the coordinates of the separating functional
  set l : ι → ℝ := fun i => g (Pi.single i 1) with hldef
  have hsingle : ∀ (i : ι) (r : ℝ), (Pi.single i r : ι → ℝ) = r • Pi.single i (1 : ℝ) := by
    intro i r
    funext j
    simp [Pi.single_apply]
  have hrepr : ∀ z : ι → ℝ, g z = ∑ i, z i * l i := by
    intro z
    have hz : ∑ i, (Pi.single i (z i) : ι → ℝ) = z := Finset.univ_sum_single z
    calc g z = g (∑ i, (Pi.single i (z i) : ι → ℝ)) := by rw [hz]
      _ = ∑ i, g (Pi.single i (z i)) := map_sum _ _ _
      _ = ∑ i, z i * l i := by
          refine Finset.sum_congr rfl fun i _ => ?_
          rw [hsingle i (z i), map_smul, smul_eq_mul, hldef]
  have hc0 : 0 ≤ c := by
    have h0 : (0 : ι → ℝ) ∈ C₂ := by rw [hC₂def]; intro i; simp
    have hle := hsep.le_of_mem_left h0
    simpa using hle
  have hlnonneg : ∀ i, 0 ≤ l i := by
    intro i
    by_contra hneg
    push Not at hneg
    have hlpos : (0 : ℝ) < -l i := by linarith
    have hNpos : 0 < (c + 1) / (-l i) := div_pos (by linarith) hlpos
    have hmem : (Pi.single i (-((c + 1) / (-l i))) : ι → ℝ) ∈ C₂ := by
      rw [hC₂def]
      intro j
      rcases eq_or_ne j i with rfl | hji
      · simp only [Pi.single_eq_same]; linarith
      · simp [Pi.single_eq_of_ne hji]
    have hle := hsep.le_of_mem_left hmem
    rw [hrepr] at hle
    have hine : l i ≠ 0 := ne_of_lt hneg
    have hval : ∑ j, (Pi.single i (-((c + 1) / (-l i))) : ι → ℝ) j * l j
        = -((c + 1) / (-l i)) * l i := by
      rw [Finset.sum_eq_single i (fun j _ hj => by rw [Pi.single_eq_of_ne hj, zero_mul])
        (fun h => absurd (Finset.mem_univ i) h), Pi.single_eq_same]
    rw [hval] at hle
    have hcomp : -((c + 1) / (-l i)) * l i = c + 1 := by
      rw [div_neg, neg_neg, div_mul_cancel₀ _ hine]
    rw [hcomp] at hle
    linarith
  have hlne : l ≠ 0 := by
    intro hzero
    have hg0 : ∀ z : ι → ℝ, g z = 0 := by
      intro z; rw [hrepr, hzero]; simp
    obtain ⟨z₁, hz₁⟩ := hC₁ne
    have hc1 : c ≤ 0 := by
      have hle := hsep.le_of_mem_right hz₁
      rwa [hg0] at hle
    have hceq : c = 0 := le_antisymm hc1 hc0
    exact hsep.not_subset fun z _ => by simp [hg0 z, hceq]
  have hkey : ∀ z ∈ C₁, 0 ≤ ∑ i, z i * l i := by
    intro z hz
    have hle := hsep.le_of_mem_right hz
    rw [hrepr] at hle
    linarith
  -- the weighted sum, and its real value on `ri C`
  have hsumcoe : ∀ z ∈ ri C, ∑ i, (l i : EReal) * f i z
      = ((∑ i, (f i z).toReal * l i : ℝ) : EReal) := by
    intro z hz
    rw [EReal.coe_sum]
    refine Finset.sum_congr rfl fun i _ => ?_
    have hcoe : (((f i z).toReal : ℝ) : EReal) = f i z :=
      _root_.EReal.coe_toReal (hfinri i z hz) ((hp i).ne_bot z)
    rw [mul_comm, ← EReal.coe_mul_coe, hcoe]
  have hri : ∀ z ∈ ri C, (0 : EReal) ≤ ∑ i, (l i : EReal) * f i z := by
    intro z hz
    have hzC : z ∈ C := intrinsicInterior_subset hz
    have hcoe : ∀ i, (((f i z).toReal : ℝ) : EReal) = f i z :=
      fun i => _root_.EReal.coe_toReal (hfinri i z hz) ((hp i).ne_bot z)
    have hstep : ∀ ε : ℝ, 0 < ε → 0 ≤ ∑ i, ((f i z).toReal + ε) * l i := by
      intro ε hε
      refine hkey _ ?_
      rw [hC₁def]
      refine ⟨z, hzC, fun i => ?_⟩
      rw [← hcoe i]
      exact_mod_cast (by linarith : (f i z).toReal < (f i z).toReal + ε)
    have hexp : ∀ ε : ℝ, ∑ i, ((f i z).toReal + ε) * l i
        = (∑ i, (f i z).toReal * l i) + ε * ∑ i, l i := by
      intro ε
      rw [Finset.mul_sum, ← Finset.sum_add_distrib]
      exact Finset.sum_congr rfl fun i _ => by ring
    have hA : 0 ≤ ∑ i, (f i z).toReal * l i := by
      by_contra hcon
      push Not at hcon
      have hLnn : (0 : ℝ) ≤ ∑ i, l i := Finset.sum_nonneg fun i _ => hlnonneg i
      have hLpos : (0 : ℝ) < (∑ i, l i) + 1 := by linarith
      have hεpos : 0 < -(∑ i, (f i z).toReal * l i) / ((∑ i, l i) + 1) :=
        div_pos (by linarith) hLpos
      have h1 := hstep _ hεpos
      rw [hexp] at h1
      have h2 : (∑ i, (f i z).toReal * l i)
          + (-(∑ i, (f i z).toReal * l i) / ((∑ i, l i) + 1)) * ∑ i, l i
          = (∑ i, (f i z).toReal * l i) / ((∑ i, l i) + 1) := by
        field_simp
        ring
      rw [h2] at h1
      have h3 := (le_div_iff₀ hLpos).1 h1
      simp only [zero_mul] at h3
      linarith
    rw [hsumcoe z hz]
    exact_mod_cast hA
  -- Corollary 7.3.3 carries the bound from `ri C` to `C`
  refine ⟨l, hlnonneg, hlne, fun x hx => ?_⟩
  have hgconv : ConvexFn (fun x => ∑ i, (l i : EReal) * f i x) :=
    ConvexFn.sum (fun i _ => (hf i).smul (l i) (hlnonneg i))
      (fun i _ x => EReal.coe_mul_ne_bot (hlnonneg i) ((hp i).ne_bot x))
  have hgbot : ∀ z, (∑ i, (l i : EReal) * f i z) ≠ ⊥ := fun z =>
    EReal.sum_ne_bot fun i _ => EReal.coe_mul_ne_bot (hlnonneg i) ((hp i).ne_bot z)
  have hgfin : ∀ z ∈ ri C, (∑ i, (l i : EReal) * f i z) ≠ ⊤ := by
    intro z hz
    rw [hsumcoe z hz]
    exact _root_.EReal.coe_ne_top _
  have hxcl : x ∈ closure (ri C) := by
    rw [Convex.closure_relint hC]; exact subset_closure hx
  have hfinal := hgconv.le_of_mem_closure hgbot (Convex.relint hC) hgfin (c := 0)
    (fun z hz => by simpa using hri z hz) hxcl
  simpa using hfinal

end Alternative

/-! ### Theorem 21.2: the alternative with affine constraints -/

section AffineSum

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
variable {κ : Type*} [Fintype κ] {C : Set E} {a : κ → (E →ᵃ[ℝ] ℝ)}

omit [FiniteDimensional ℝ E] in
/-- A finite real combination of affine functions is affine along segments. -/
theorem combo_affine_sum (μ : κ → ℝ) {s t : ℝ} (hst : s + t = 1) (x y : E) :
    (∑ j, μ j * a j (s • x + t • y)) = s * (∑ j, μ j * a j x) + t * (∑ j, μ j * a j y) := by
  rw [Finset.mul_sum, Finset.mul_sum, ← Finset.sum_add_distrib]
  refine Finset.sum_congr rfl fun j _ => ?_
  rw [Convex.combo_affine_apply hst]
  simp only [smul_eq_mul]
  ring

omit [FiniteDimensional ℝ E] in
/-- Such a combination, read in `EReal`, is convex — it is in fact affine. -/
theorem convexFn_coe_affine_sum (μ : κ → ℝ) :
    ConvexFn (fun x => ((∑ j, μ j * a j x : ℝ) : EReal)) := by
  refine convexFn_of_epi_combo fun x y p q hx hy s t hs ht hst => ?_
  rw [_root_.EReal.coe_le_coe_iff] at hx hy ⊢
  rw [combo_affine_sum μ hst]
  nlinarith [mul_le_mul_of_nonneg_left hx hs, mul_le_mul_of_nonneg_left hy ht]

omit [FiniteDimensional ℝ E] in
/-- The affine step of Theorem 21.2: a combination of affine functions that is non-negative on a
convex set `C` and non-positive at a relative interior point of `C` vanishes on all of `C`. This is
the affine analogue of `eq_zero_of_nonpos_of_mem_relint`, and the reason Rockafellar's multipliers
`λ₁, …, λ_k` cannot all vanish. -/
theorem eq_zero_of_nonneg_of_mem_relint_affine_sum (μ : κ → ℝ) {z : E} (hz : z ∈ ri C)
    (hnonneg : ∀ x ∈ C, 0 ≤ ∑ j, μ j * a j x) (hz0 : (∑ j, μ j * a j z) ≤ 0) :
    ∀ x ∈ C, (∑ j, μ j * a j x) = 0 := by
  have hzC : z ∈ C := intrinsicInterior_subset hz
  have hFz : (∑ j, μ j * a j z) = 0 := le_antisymm hz0 (hnonneg z hzC)
  intro x hx
  refine le_antisymm ?_ (hnonneg x hx)
  obtain ⟨ν, hν, hw⟩ := exists_one_lt_smul_mem_of_mem_relint hz (subset_affineSpan ℝ C hx)
  have hval := combo_affine_sum (a := a) μ (s := 1 - ν) (t := ν) (by ring) x z
  have hcon := hnonneg _ hw
  rw [hval, hFz] at hcon
  nlinarith

end AffineSum

section Orthant

/-- The non-positive orthant of `σ → ℝ` is polyhedral: it is cut out by the coordinate
projections. -/
theorem polyhedral_nonpos_orthant (σ : Type*) [Finite σ] :
    Polyhedral {z : σ → ℝ | ∀ s, z s ≤ 0} := by
  classical
  have : Fintype σ := Fintype.ofFinite σ
  refine ⟨Finset.univ.image (fun s : σ => (LinearMap.proj s, (0 : ℝ))), ?_⟩
  ext z
  constructor
  · rintro hz q hq
    simp only [Finset.mem_image, Finset.mem_univ, true_and] at hq
    obtain ⟨s, rfl⟩ := hq
    simpa using hz s
  · intro hz s
    simpa using hz (LinearMap.proj s, (0 : ℝ)) (by simp)

end Orthant

section AffineAlternative

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
variable {ι κ : Type*} [Fintype ι] [Fintype κ] {C : Set E} {f : ι → E → EReal}
variable {a : κ → (E →ᵃ[ℝ] ℝ)}

/-- **Rockafellar, Theorem 21.2.** The refinement of Theorem 21.1 that treats affine constraints
separately: if the affine system `a_j x ≤ 0` is solvable in `ri C`, then either the mixed system
`f_i x < 0`, `a_j x ≤ 0` is solvable in `C`, or there are non-negative multipliers — *not all of
the `λ_i` zero* — making the combined function non-negative on `C`.

Theorem 21.1 is the case `κ = Empty`. What the affine constraints buy is the sharper conclusion
`l ≠ 0`, which alternative (b) of Theorem 21.1 could not give if the affine constraints were folded
in as ordinary convex functions; the price is that the separation must be the polyhedral one
(Theorem 20.2) rather than Theorem 11.3. -/
theorem alternative_of_convex_system_affine (hC : Convex ℝ C) (hf : ∀ i, ConvexFn (f i))
    (hp : ∀ i, Proper (f i)) (hdom : ∀ i, ri C ⊆ dom (f i))
    (hfeas : ∃ x ∈ ri C, ∀ j, a j x ≤ 0) :
    (∃ x ∈ C, (∀ i, f i x < 0) ∧ ∀ j, a j x ≤ 0) ∨
      ∃ (l : ι → ℝ) (μ : κ → ℝ), (∀ i, 0 ≤ l i) ∧ (∀ j, 0 ≤ μ j) ∧ l ≠ 0 ∧
        ∀ x ∈ C, (0 : EReal)
          ≤ (∑ i, (l i : EReal) * f i x) + ((∑ j, μ j * a j x : ℝ) : EReal) := by
  classical
  by_cases halt : ∃ x ∈ C, (∀ i, f i x < 0) ∧ ∀ j, a j x ≤ 0
  · exact Or.inl halt
  refine Or.inr ?_
  obtain ⟨y₀, hy₀, hy₀a⟩ := hfeas
  have hy₀C : y₀ ∈ C := intrinsicInterior_subset hy₀
  have hfinri : ∀ i, ∀ z ∈ ri C, f i z ≠ ⊤ := fun i z hz => (mem_dom.1 (hdom i hz)).ne
  -- Rockafellar's two sets, in `(ι ⊕ κ) → ℝ`
  set D₁ : Set (ι ⊕ κ → ℝ) :=
    {z | ∃ x ∈ C, (∀ i, f i x < ((z (Sum.inl i) : ℝ) : EReal)) ∧ ∀ j, a j x = z (Sum.inr j)}
    with hD₁def
  set D₂ : Set (ι ⊕ κ → ℝ) := {z | ∀ s, z s ≤ 0} with hD₂def
  have hD₂poly : Polyhedral D₂ := by rw [hD₂def]; exact polyhedral_nonpos_orthant _
  have hD₁conv : Convex ℝ D₁ := by
    rw [hD₁def]
    rintro z ⟨x, hx, hzx, hax⟩ w ⟨u, hu, hwu, hau⟩ p q hpp hqq hpq
    refine ⟨p • x + q • u, hC hx hu hpp hqq hpq, fun i => ?_, fun j => ?_⟩
    · obtain ⟨rx, hrx⟩ := EReal.exists_coe_of_ne_bot_of_lt_top ((hp i).ne_bot x)
        (lt_of_lt_of_le (hzx i) le_top)
      obtain ⟨ru, hru⟩ := EReal.exists_coe_of_ne_bot_of_lt_top ((hp i).ne_bot u)
        (lt_of_lt_of_le (hwu i) le_top)
      have hrxlt : rx < z (Sum.inl i) := by
        have h := hzx i; rw [hrx] at h; exact_mod_cast h
      have hrult : ru < w (Sum.inl i) := by
        have h := hwu i; rw [hru] at h; exact_mod_cast h
      have hcombo : f i (p • x + q • u) ≤ (((p * rx + q * ru : ℝ)) : EReal) :=
        (hf i).epi_combo (le_of_eq hrx) (le_of_eq hru) hpp hqq hpq
      have harith : p * rx + q * ru < p * z (Sum.inl i) + q * w (Sum.inl i) := by
        rcases eq_or_lt_of_le hpp with h0 | h0
        · have hq1 : q = 1 := by linarith
          rw [← h0, hq1]; simpa using hrult
        · nlinarith
      refine lt_of_le_of_lt hcombo ?_
      have hpi : ((p • z + q • w) (Sum.inl i) : ℝ)
          = p * z (Sum.inl i) + q * w (Sum.inl i) := by simp
      rw [hpi]
      exact_mod_cast harith
    · have hpi : ((p • z + q • w) (Sum.inr j) : ℝ)
          = p * z (Sum.inr j) + q * w (Sum.inr j) := by simp
      rw [hpi, ← hax j, ← hau j, Convex.combo_affine_apply hpq]
      simp
  have hD₁ne : D₁.Nonempty := by
    refine ⟨Sum.elim (fun i => (f i y₀).toReal + 1) (fun j => a j y₀), ?_⟩
    rw [hD₁def]
    refine ⟨y₀, hy₀C, fun i => ?_, fun j => by simp⟩
    have hcoe : (((f i y₀).toReal : ℝ) : EReal) = f i y₀ :=
      _root_.EReal.coe_toReal (hfinri i y₀ hy₀) ((hp i).ne_bot y₀)
    simp only [Sum.elim_inl]
    rw [← hcoe]
    exact_mod_cast (by linarith : (f i y₀).toReal < (f i y₀).toReal + 1)
  have hdisj : Disjoint D₁ D₂ := by
    rw [Set.disjoint_left]
    intro z hz1 hz2
    rw [hD₁def] at hz1
    rw [hD₂def] at hz2
    obtain ⟨x, hx, hzx, hax⟩ := hz1
    refine halt ⟨x, hx, fun i => ?_, fun j => ?_⟩
    · exact lt_of_lt_of_le (hzx i) (by exact_mod_cast hz2 (Sum.inl i))
    · rw [hax j]; exact hz2 (Sum.inr j)
  obtain ⟨g, α, hsep, hns⟩ :=
    (exists_separates_not_subset_iff_disjoint_relint hD₂poly hD₁conv hD₁ne).2
      (Disjoint.mono_right intrinsicInterior_subset hdisj.symm)
  -- the multipliers are the coordinates of the separating functional
  set w : (ι ⊕ κ) → ℝ := fun s => g (Pi.single s 1) with hwdef
  have hsingle : ∀ (s : ι ⊕ κ) (r : ℝ),
      (Pi.single s r : (ι ⊕ κ) → ℝ) = r • Pi.single s (1 : ℝ) := by
    intro s r
    funext t
    simp [Pi.single_apply]
  have hrepr : ∀ z : (ι ⊕ κ) → ℝ, g z = ∑ s, w s * z s := by
    intro z
    have hz : ∑ s, (Pi.single s (z s) : (ι ⊕ κ) → ℝ) = z := Finset.univ_sum_single z
    calc g z = g (∑ s, (Pi.single s (z s) : (ι ⊕ κ) → ℝ)) := by rw [hz]
      _ = ∑ s, g (Pi.single s (z s)) := map_sum _ _ _
      _ = ∑ s, w s * z s := by
          refine Finset.sum_congr rfl fun s _ => ?_
          rw [hsingle s (z s), map_smul, smul_eq_mul, hwdef, mul_comm]
  have hα0 : 0 ≤ α := by
    have h0 : (0 : (ι ⊕ κ) → ℝ) ∈ D₂ := by rw [hD₂def]; intro s; simp
    simpa using hsep.le_of_mem_left h0
  have hwnonneg : ∀ s, 0 ≤ w s := by
    intro s
    by_contra hneg
    push Not at hneg
    have hwne : w s ≠ 0 := ne_of_lt hneg
    have hpos : (0 : ℝ) < -w s := by linarith
    have hmem : (Pi.single s (-((α + 1) / (-w s))) : (ι ⊕ κ) → ℝ) ∈ D₂ := by
      rw [hD₂def]
      intro t
      rcases eq_or_ne t s with hts | hts
      · rw [hts, Pi.single_eq_same]
        have hq : 0 < (α + 1) / (-w s) := div_pos (by linarith) hpos
        linarith
      · simp [Pi.single_eq_of_ne hts]
    have hle := hsep.le_of_mem_left hmem
    rw [hrepr] at hle
    have hvalue : ∑ t, w t * (Pi.single s (-((α + 1) / (-w s))) : (ι ⊕ κ) → ℝ) t
        = w s * -((α + 1) / (-w s)) := by
      rw [Finset.sum_eq_single s (fun t _ ht => by rw [Pi.single_eq_of_ne ht, mul_zero])
        (fun h => absurd (Finset.mem_univ s) h), Pi.single_eq_same]
    rw [hvalue] at hle
    have hcomp : w s * -((α + 1) / (-w s)) = α + 1 := by
      rw [div_neg, neg_neg, mul_comm, div_mul_cancel₀ _ hwne]
    rw [hcomp] at hle
    linarith
  have hkey : ∀ z ∈ D₁, α ≤ ∑ s, w s * z s := by
    intro z hz
    have hle := hsep.le_of_mem_right hz
    rwa [hrepr] at hle
  -- the value of the combination on `ri C`
  have hval : ∀ x ∈ ri C, α ≤ (∑ i, w (Sum.inl i) * (f i x).toReal)
      + ∑ j, w (Sum.inr j) * a j x := by
    intro x hx
    have hxC : x ∈ C := intrinsicInterior_subset hx
    have hcoe : ∀ i, (((f i x).toReal : ℝ) : EReal) = f i x :=
      fun i => _root_.EReal.coe_toReal (hfinri i x hx) ((hp i).ne_bot x)
    have hstep : ∀ ε : ℝ, 0 < ε → α ≤ (∑ i, w (Sum.inl i) * ((f i x).toReal + ε))
        + ∑ j, w (Sum.inr j) * a j x := by
      intro ε hε
      have hz : Sum.elim (fun i => (f i x).toReal + ε) (fun j => a j x) ∈ D₁ := by
        rw [hD₁def]
        refine ⟨x, hxC, fun i => ?_, fun j => by simp⟩
        simp only [Sum.elim_inl]
        rw [← hcoe i]
        exact_mod_cast (by linarith : (f i x).toReal < (f i x).toReal + ε)
      have h := hkey _ hz
      rw [Fintype.sum_sum_type] at h
      simpa using h
    by_contra hcon
    push Not at hcon
    set A := ∑ i, w (Sum.inl i) * (f i x).toReal with hAdef
    set B := ∑ j, w (Sum.inr j) * a j x with hBdef
    set L := ∑ i, w (Sum.inl i) with hLdef
    have hLnn : (0 : ℝ) ≤ L := Finset.sum_nonneg fun i _ => hwnonneg _
    have hLpos : (0 : ℝ) < L + 1 := by linarith
    have hδ : 0 < α - (A + B) := by linarith
    have hεpos : 0 < (α - (A + B)) / (L + 1) := div_pos hδ hLpos
    have hexp : ∑ i, w (Sum.inl i) * ((f i x).toReal + (α - (A + B)) / (L + 1))
        = A + ((α - (A + B)) / (L + 1)) * L := by
      rw [hAdef, hLdef, Finset.mul_sum, ← Finset.sum_add_distrib]
      exact Finset.sum_congr rfl fun i _ => by ring
    have h1 := hstep _ hεpos
    rw [hexp] at h1
    have h2 : ((α - (A + B)) / (L + 1)) * L < α - (A + B) := by
      rw [div_mul_eq_mul_div, div_lt_iff₀ hLpos]
      nlinarith
    linarith
  -- Corollary 7.3.3 carries the bound from `ri C` to `C`
  have hAconv : ConvexFn (fun x => ∑ i, (w (Sum.inl i) : EReal) * f i x) :=
    ConvexFn.sum (fun i _ => (hf i).smul _ (hwnonneg _))
      (fun i _ x => EReal.coe_mul_ne_bot (hwnonneg _) ((hp i).ne_bot x))
  have hAbot : ∀ x, (∑ i, (w (Sum.inl i) : EReal) * f i x) ≠ ⊥ := fun x =>
    EReal.sum_ne_bot fun i _ => EReal.coe_mul_ne_bot (hwnonneg _) ((hp i).ne_bot x)
  have hFconv : ConvexFn (fun x => (∑ i, (w (Sum.inl i) : EReal) * f i x)
      + ((∑ j, w (Sum.inr j) * a j x : ℝ) : EReal)) :=
    hAconv.add (convexFn_coe_affine_sum _) hAbot (fun x => _root_.EReal.coe_ne_bot _)
  have hFbot : ∀ x, ((∑ i, (w (Sum.inl i) : EReal) * f i x)
      + ((∑ j, w (Sum.inr j) * a j x : ℝ) : EReal)) ≠ ⊥ := fun x =>
    _root_.EReal.add_ne_bot_iff.2 ⟨hAbot x, _root_.EReal.coe_ne_bot _⟩
  have hFcoe : ∀ x ∈ ri C, (∑ i, (w (Sum.inl i) : EReal) * f i x)
      + ((∑ j, w (Sum.inr j) * a j x : ℝ) : EReal)
      = (((∑ i, w (Sum.inl i) * (f i x).toReal) + ∑ j, w (Sum.inr j) * a j x : ℝ) : EReal) := by
    intro x hx
    rw [_root_.EReal.coe_add]
    congr 1
    rw [EReal.coe_sum]
    refine Finset.sum_congr rfl fun i _ => ?_
    have hcoe : (((f i x).toReal : ℝ) : EReal) = f i x :=
      _root_.EReal.coe_toReal (hfinri i x hx) ((hp i).ne_bot x)
    rw [← EReal.coe_mul_coe, hcoe]
  have hFC : ∀ x ∈ C, ((α : ℝ) : EReal) ≤ (∑ i, (w (Sum.inl i) : EReal) * f i x)
      + ((∑ j, w (Sum.inr j) * a j x : ℝ) : EReal) := by
    intro x hx
    have hxcl : x ∈ closure (ri C) := by
      rw [Convex.closure_relint hC]; exact subset_closure hx
    refine hFconv.le_of_mem_closure hFbot (Convex.relint hC) ?_ ?_ hxcl
    · intro z hz
      rw [hFcoe z hz]
      exact _root_.EReal.coe_ne_top _
    · intro z hz
      rw [hFcoe z hz]
      exact_mod_cast hval z hz
  -- the multipliers on the convex constraints are not all zero
  have hlne : (fun i => w (Sum.inl i)) ≠ (0 : ι → ℝ) := by
    intro hzero
    have hw0 : ∀ i, w (Sum.inl i) = 0 := fun i => congrFun hzero i
    have haff : ∀ x ∈ C, α ≤ ∑ j, w (Sum.inr j) * a j x := by
      intro x hx
      have h := hFC x hx
      have hz : (∑ i, (w (Sum.inl i) : EReal) * f i x) = 0 := by
        refine Finset.sum_eq_zero fun i _ => ?_
        rw [hw0 i]
        simp
      rw [hz, zero_add] at h
      exact_mod_cast h
    have hy₀le : (∑ j, w (Sum.inr j) * a j y₀) ≤ 0 :=
      Finset.sum_nonpos fun j _ => mul_nonpos_of_nonneg_of_nonpos (hwnonneg _) (hy₀a j)
    have hα : α = 0 := le_antisymm (le_trans (haff y₀ hy₀C) hy₀le) hα0
    have hconst : ∀ x ∈ C, (∑ j, w (Sum.inr j) * a j x) = 0 :=
      eq_zero_of_nonneg_of_mem_relint_affine_sum (a := a) _ hy₀
        (fun x hx => by rw [← hα]; exact haff x hx) hy₀le
    obtain ⟨z, hzD, hzne⟩ := Set.not_subset.1 hns
    have hzlt : α < g z := lt_of_le_of_ne (hsep.le_of_mem_right hzD) (Ne.symm hzne)
    rw [hD₁def] at hzD
    obtain ⟨x, hx, _, hax⟩ := hzD
    have hgz : g z = 0 := by
      rw [hrepr, Fintype.sum_sum_type]
      have h1 : ∑ i, w (Sum.inl i) * z (Sum.inl i) = 0 :=
        Finset.sum_eq_zero fun i _ => by rw [hw0 i, zero_mul]
      have h2 : ∑ j, w (Sum.inr j) * z (Sum.inr j) = 0 := by
        rw [show (∑ j, w (Sum.inr j) * z (Sum.inr j))
          = ∑ j, w (Sum.inr j) * a j x from Finset.sum_congr rfl fun j _ => by rw [hax j]]
        exact hconst x hx
      rw [h1, h2, add_zero]
    rw [hgz, hα] at hzlt
    exact lt_irrefl 0 hzlt
  refine ⟨fun i => w (Sum.inl i), fun j => w (Sum.inr j), fun i => hwnonneg _,
    fun j => hwnonneg _, hlne, fun x hx => ?_⟩
  exact le_trans (by exact_mod_cast hα0) (hFC x hx)

end AffineAlternative

/-! ### Theorem 21.6 and its corollaries: finite collections -/

section Finite

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
variable {ι κ : Type*} {C : Set E} {f : ι → E → EReal} {g : κ → E → EReal}

/-- **Rockafellar, Theorem 21.6** (Helly's theorem for finite collections): a finite collection of
convex sets in an `n`-dimensional space has a common point as soon as every `n + 1` of them do. No
closedness and no recession hypothesis is needed — that is what distinguishes this from Corollary
21.3.2.

This is Mathlib's `Convex.helly_theorem'`; the alias exists so that the book's numbering has a
name in this development, and so that Corollary 21.6.1 below reads as Rockafellar's proof does. -/
theorem helly_finite {F : ι → Set E} {s : Finset ι} (hconv : ∀ i ∈ s, Convex ℝ (F i))
    (hinter : ∀ I ⊆ s, I.card ≤ Module.finrank ℝ E + 1 → (⋂ i ∈ I, F i).Nonempty) :
    (⋂ i ∈ s, F i).Nonempty :=
  Convex.helly_theorem' hconv hinter

/-- **Rockafellar, Corollary 21.6.1.** A finite system of convex inequalities — some strict, some
weak — is solvable in a convex set `C` as soon as every subsystem of at most `n + 1` inequalities
is solvable in `C`.

Rockafellar's proof, verbatim: `C` and the sublevel sets `{x | fᵢ x < 0}`, `{x | gⱼ x ≤ 0}` form a
finite collection of convex sets to which Theorem 21.6 applies. Counting is the only fiddly point:
a subcollection of at most `n + 1` of the sets uses at most `n + 1` of the inequalities whether or
not it also uses `C`, so the hypothesis here covers every case of the Helly hypothesis. -/
theorem exists_mem_of_forall_subsystem [Finite ι] [Finite κ] (hC : Convex ℝ C)
    (hf : ∀ i, ConvexFn (f i)) (hg : ∀ j, ConvexFn (g j))
    (hsub : ∀ (S : Finset ι) (T : Finset κ), S.card + T.card ≤ Module.finrank ℝ E + 1 →
      ∃ x ∈ C, (∀ i ∈ S, f i x < 0) ∧ ∀ j ∈ T, g j x ≤ 0) :
    ∃ x ∈ C, (∀ i, f i x < 0) ∧ ∀ j, g j x ≤ 0 := by
  classical
  have : Fintype ι := Fintype.ofFinite ι
  have : Fintype κ := Fintype.ofFinite κ
  let F : Option (ι ⊕ κ) → Set E := fun o =>
    match o with
    | none => C
    | some (Sum.inl i) => {x | f i x < 0}
    | some (Sum.inr j) => {x | g j x ≤ 0}
  have hconv : ∀ o ∈ (Finset.univ : Finset (Option (ι ⊕ κ))), Convex ℝ (F o) := by
    rintro (_ | (i | j)) _
    · exact hC
    · exact (hf i).convex_lt 0
    · exact (hg j).convex_le 0
  have hinter : ∀ I ⊆ (Finset.univ : Finset (Option (ι ⊕ κ))),
      I.card ≤ Module.finrank ℝ E + 1 → (⋂ o ∈ I, F o).Nonempty := by
    intro I _ hcard
    set S : Finset ι := Finset.univ.filter (fun i => some (Sum.inl i) ∈ I) with hSdef
    set T : Finset κ := Finset.univ.filter (fun j => some (Sum.inr j) ∈ I) with hTdef
    have hSinj : Function.Injective (fun i : ι => (some (Sum.inl i) : Option (ι ⊕ κ))) := by
      intro i i' h
      simpa using h
    have hTinj : Function.Injective (fun j : κ => (some (Sum.inr j) : Option (ι ⊕ κ))) := by
      intro j j' h
      simpa using h
    have hdisj : Disjoint (S.image (fun i : ι => (some (Sum.inl i) : Option (ι ⊕ κ))))
        (T.image (fun j : κ => (some (Sum.inr j) : Option (ι ⊕ κ)))) := by
      simp only [Finset.disjoint_left, Finset.mem_image]
      rintro o ⟨i, _, rfl⟩ ⟨j, _, hj⟩
      simp at hj
    have hsubI : S.image (fun i : ι => (some (Sum.inl i) : Option (ι ⊕ κ)))
        ∪ T.image (fun j : κ => (some (Sum.inr j) : Option (ι ⊕ κ))) ⊆ I := by
      intro o ho
      simp only [Finset.mem_union, Finset.mem_image, hSdef, hTdef, Finset.mem_filter,
        Finset.mem_univ, true_and] at ho
      rcases ho with ⟨i, hi, rfl⟩ | ⟨j, hj, rfl⟩
      · exact hi
      · exact hj
    have hle : S.card + T.card ≤ I.card := by
      rw [← Finset.card_image_of_injective S hSinj, ← Finset.card_image_of_injective T hTinj,
        ← Finset.card_union_of_disjoint hdisj]
      exact Finset.card_le_card hsubI
    obtain ⟨x, hxC, hxf, hxg⟩ := hsub S T (le_trans hle hcard)
    refine ⟨x, ?_⟩
    simp only [Set.mem_iInter]
    rintro (_ | (i | j)) ho
    · exact hxC
    · exact hxf i (by simp [hSdef, ho])
    · exact hxg j (by simp [hTdef, ho])
  obtain ⟨x, hx⟩ := helly_finite hconv hinter
  simp only [Set.mem_iInter] at hx
  exact ⟨x, hx none (Finset.mem_univ _), fun i => hx (some (Sum.inl i)) (Finset.mem_univ _),
    fun j => hx (some (Sum.inr j)) (Finset.mem_univ _)⟩

/-- **Corollary 21.6.1** for a system of strict inequalities only — the form Corollary 21.6.2
uses. -/
theorem exists_mem_of_forall_subsystem_lt [Finite ι] (hC : Convex ℝ C)
    (hf : ∀ i, ConvexFn (f i))
    (hsub : ∀ S : Finset ι, S.card ≤ Module.finrank ℝ E + 1 → ∃ x ∈ C, ∀ i ∈ S, f i x < 0) :
    ∃ x ∈ C, ∀ i, f i x < 0 := by
  obtain ⟨x, hx, hxf, -⟩ :=
    exists_mem_of_forall_subsystem (κ := Empty) (g := fun j => j.elim) hC hf (fun j => j.elim)
      (fun S T hcard => by
        obtain ⟨x, hx, hxf⟩ := hsub S (le_trans (Nat.le_add_right _ _) hcard)
        exact ⟨x, hx, hxf, fun j => j.elim⟩)
  exact ⟨x, hx, hxf⟩

variable [Fintype ι]

/-- **Rockafellar, Corollary 21.6.2.** The multipliers of Theorem 21.1 can be chosen supported on
at most `n + 1` indices.

The proof is Rockafellar's one-liner: if alternative (a) fails, Corollary 21.6.1 says it already
fails for a subsystem of at most `n + 1` inequalities, and Theorem 21.1 applied to *that* subsystem
produces multipliers which extend by zero. The extension is harmless in `EReal` because
`0 · (+∞) = 0`, so the added terms contribute nothing even where the dropped `fᵢ` are infinite. -/
theorem sparse_alternative_of_convex_system [Nonempty ι] (hC : Convex ℝ C)
    (hf : ∀ i, ConvexFn (f i)) (hp : ∀ i, Proper (f i)) (hdom : ∀ i, ri C ⊆ dom (f i)) :
    (∃ x ∈ C, ∀ i, f i x < 0) ∨
      ∃ (S : Finset ι) (l : ι → ℝ), S.card ≤ Module.finrank ℝ E + 1 ∧ (∀ i ∉ S, l i = 0) ∧
        (∀ i, 0 ≤ l i) ∧ l ≠ 0 ∧ ∀ x ∈ C, (0 : EReal) ≤ ∑ i, (l i : EReal) * f i x := by
  classical
  by_cases halt : ∃ x ∈ C, ∀ i, f i x < 0
  · exact Or.inl halt
  refine Or.inr ?_
  -- Corollary 21.6.1: alternative (a) already fails for a small subsystem
  have hsmall : ∃ S : Finset ι, S.card ≤ Module.finrank ℝ E + 1
      ∧ ¬ ∃ x ∈ C, ∀ i ∈ S, f i x < 0 := by
    by_contra hcon
    push Not at hcon
    exact halt (exists_mem_of_forall_subsystem_lt hC hf hcon)
  obtain ⟨S, hScard, hSalt⟩ := hsmall
  rcases S.eq_empty_or_nonempty with rfl | hSne
  · -- an empty subsystem can only fail because `C` itself is empty
    have hCempty : C = ∅ := by
      rw [Set.eq_empty_iff_forall_notMem]
      exact fun x hx => hSalt ⟨x, hx, by simp⟩
    obtain ⟨i₀⟩ := ‹Nonempty ι›
    refine ⟨{i₀}, fun i => if i = i₀ then 1 else 0, by simp, ?_, ?_, ?_, ?_⟩
    · intro i hi
      simp only [Finset.mem_singleton] at hi
      simp [hi]
    · intro i; positivity
    · intro hzero
      have h := congrFun hzero i₀
      simp at h
    · intro x hx
      rw [hCempty] at hx
      exact absurd hx (Set.notMem_empty x)
  -- Theorem 21.1 applied to the subsystem
  have hSnonempty : Nonempty (↥S) := hSne.to_subtype
  obtain hsolv | ⟨l', hl'0, hl'ne, hl'⟩ :=
    alternative_of_convex_system (ι := ↥S) (f := fun i : ↥S => f i) hC
      (fun i => hf i) (fun i => hp i) (fun i => hdom i)
  · exact absurd ⟨hsolv.choose, hsolv.choose_spec.1,
      fun i hi => hsolv.choose_spec.2 ⟨i, hi⟩⟩ hSalt
  refine ⟨S, fun i => if h : i ∈ S then l' ⟨i, h⟩ else 0, hScard, ?_, ?_, ?_, ?_⟩
  · intro i hi
    simp [hi]
  · intro i
    by_cases h : i ∈ S
    · simpa [h] using hl'0 ⟨i, h⟩
    · simp [h]
  · intro hzero
    obtain ⟨i₀, hi₀⟩ : ∃ i₀ : ↥S, l' i₀ ≠ 0 := by
      by_contra hcon
      push Not at hcon
      exact hl'ne (funext hcon)
    have h := congrFun hzero (i₀ : ι)
    simp only [i₀.2, Pi.zero_apply, Subtype.coe_eta, ↓reduceDIte] at h
    exact hi₀ h
  · intro x hx
    have hshrink : ∑ i, ((if h : i ∈ S then l' ⟨i, h⟩ else 0 : ℝ) : EReal) * f i x
        = ∑ i ∈ S, ((if h : i ∈ S then l' ⟨i, h⟩ else 0 : ℝ) : EReal) * f i x := by
      refine (Finset.sum_subset (Finset.subset_univ S) ?_).symm
      intro i _ hi
      simp [hi]
    rw [hshrink, ← Finset.sum_coe_sort S]
    have hcongr : ∀ i : ↥S, ((if h : (i : ι) ∈ S then l' ⟨(i : ι), h⟩ else 0 : ℝ) : EReal)
        * f i x = (l' i : EReal) * f i x := by
      intro i
      simp only [i.2, Subtype.coe_eta, ↓reduceDIte]
    rw [Finset.sum_congr rfl fun i _ => hcongr i]
    exact hl' x hx

end Finite

end Tdaf.ConvexAnalysis
