/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Tdaf.Analysis.Convex.Homogeneous
import Tdaf.Analysis.Convex.Operations.Epi

/-!
# Right scalar multiplication and homogenisation

Rockafellar, *Convex Analysis*, §5 introduces two operations built from scalar multiplication of
epigraphs, and this file provides both.

*Right scalar multiplication* `fλ` is the function whose epigraph is `λ • epi f`; for `λ > 0` it is
`(fλ) x = λ * f (λ⁻¹ • x)`, and `f0 = δ(· | 0)`. It is a monoid action of the multiplicative monoid
`[0, ∞)` on functions, and positive homogeneity of `f` is exactly `fλ = f` for all `λ > 0`.

*Homogenisation* `hom f` is the positively homogeneous convex function on `ℝ × E` assembled from the
functions `fλ`, one for each `λ ≥ 0`. Its epigraph is (the epi-closure of) the convex cone generated
by `{1} ×ˢ epi f`, one dimension up.

## Main definitions

* `smulRight f a` — Rockafellar's `fa`, defined as `ofEpi (a • epi f)`.
* `smulRightHom` — the same operation packaged as a monoid homomorphism
  `ℝ≥0 →* Function.End (E → EReal)`, i.e. as an action of `([0, ∞), *)`.
* `levelOneLift f` — the *level-1 lift* `h (λ, x) = f x` if `λ = 1`, `⊤` otherwise.
* `hom f` — the positively homogeneous convex function on `ℝ × E` generated by
  `levelOneLift f`.
* `homCone f` — the convex cone generated by `epi (levelOneLift f)`, which is what `hom f`
  is `ofEpi` of.
* `homEpiCone` — `epi (hom f)`, bundled as a `ConvexCone ℝ ((ℝ × E) × ℝ)`.

## Main results

* `smulRight_apply_pos` — `(fa) x = a * f (a⁻¹ • x)` for `a > 0`.
* `smulRight_zero` — `f0 = δ(· | 0)` when `f ≢ +∞`, and `smulRight_of_epi_eq_empty` for
  the degenerate case `f ≡ +∞`.
* `epi_smulRight` — `epi (fa) = a • epi f`, **for `a > 0` only**; see the design note.
* `convexFn_smulRight`, `smulRight_one`, `smulRight_smulRight` — right scalar
  multiplication preserves convexity and is a monoid action.
* `posHomogeneous_iff_smulRight_eq` — `f` is positively homogeneous iff `fa = f` for `a > 0`.
* `hom_apply_pos`, `hom_apply_one`, `hom_apply_neg` — the defining equations.
* `hom_ne_bot` — `hom f` avoids `-∞` as soon as `f` does, and `hom_apply_smul` —
  `hom f (λ, λ x) = λ * f x` for `λ ≥ 0`.
* `posHomogeneous_hom`, `convexFn_hom` — `hom f` is positively homogeneous, and convex as
  soon as `f` is.
* `hom_isGreatest` — the **maximality property**: `hom f` is the greatest positively
  homogeneous convex `g` on `ℝ × E` with `g 0 ≤ 0` and `g ≤ levelOneLift f`.
* `hom_eq_ofEpi_homCone` and `epi_hom` — the cone description, and
  `homCone_eq_preimage` / `prodAssoc_image_homCone` for the associativity shuffle
  relating it to the cone generated by `{1} ×ˢ epi f` in `ℝ × (E × ℝ)`.

## Design notes

### `hom f` is *not* "the positively homogeneous convex function generated by `f`"

Two different operators occur in Rockafellar §5 and the plan's first draft conflated them.

*The positively homogeneous convex function generated by `h`* is `ofEpi K`, where `K` is the convex
cone generated by `epi h`; it is a function on the *same* space as `h`, and it is the greatest
positively homogeneous convex `g ≤ h` with `g 0 ≤ 0`. The gauge of a convex set `C` is that operator
applied to `δ(· | C) + 1`.

`hom f`, by contrast, lives on `ℝ × E`: it is that operator applied to the *level-1 lift*
`levelOneLift f` of `f`, so that `hom f (1, ·) = f` and `hom f (λ, ·) = fλ`. It is the object
Rockafellar uses to derive recession functions (Corollary 8.5.2), the support function of a level
set (Theorem 13.5) and the two-step homogenisation of Theorem 14.4. Applying the first operator to
`f` itself would give a function on `E`, and would lose the `λ` variable that all of those results
integrate over.

### `epi (fa) = a • epi f` fails at `a = 0`

`0 • epi f` is `{(0, 0)}` whenever `epi f` is nonempty, and `{(0, 0)}` is *not* an epigraph: its
vertical section over `0` is `{0}`, which is not upward closed (`not_isEpiLike_zero_smul_epi`).
So `epi (f0) = {0} ×ˢ Ici 0` is strictly larger than `0 • epi f`, and `epi_smulRight` is stated
for `a > 0` only. The *definition* `fa = ofEpi (a • epi f)` is nevertheless correct at `a = 0`:
`ofEpi` only ever sees the lower boundary, and `ofEpi {(0, 0)} = δ(· | 0)`, which is Rockafellar's
value for `f0`. The same degeneracy reappears one dimension up in `epi_hom`: the cone
`homCone f` is not epi-like, and `epi (hom f)` adds to it the ray `{0} ×ˢ Ici 0`.

### `f ≡ +∞`

Rockafellar's `f0 = δ(· | 0)` carries the side condition `f ≢ +∞`, and it is not decoration: for
`f ≡ +∞` one has `epi f = ∅` and hence `fa = +∞` for every `a`, including `a = 0`. The condition is
`(dom f).Nonempty` here, and it is needed exactly where the book needs it — `smulRight_zero`,
`hom_eq_ofEpi_homCone`, `epi_hom`, and the membership half of `hom_isGreatest`. It is
*not* needed for `posHomogeneous_hom`, `convexFn_hom` or the upper-bound half of the
maximality property, all of which are proved here without it.

### The associativity shuffle

`epi (hom f) ⊆ (ℝ × E) × ℝ`, whereas the cone over `epi f` naturally lives in `ℝ × (E × ℝ)`: the
extra homogenising variable is prepended to `E`, while the epigraph variable is appended. The two
are related by `LinearEquiv.prodAssoc ℝ ℝ E ℝ`, and `homCone_eq_preimage` states the
translation explicitly, so that downstream users (§8 recession functions, §13.5, §14.4, §15 gauges)
can move between the two pictures without rediscovering it.

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §5 — the paragraphs on
  right scalar multiplication and on the positively homogeneous convex function generated by a
  convex function, following Theorem 5.3.
-/

open Set Pointwise

open scoped NNReal

namespace Tdaf.ConvexAnalysis

/-! ### Auxiliary facts about epigraphs and `ofEpi`

These are general statements about `epi` and `ofEpi` that belong with
`Tdaf/Analysis/Convex/Operations/Epi.lean`; they are collected here because homogenisation is so far
their only consumer. -/

section Aux

variable {E : Type*} {f : E → EReal} {F G : Set (E × ℝ)} {x : E}

end Aux

/-! ### Right scalar multiplication -/

section SmulRight

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {f : E → EReal} {a b : ℝ} {x : E}

/-- **Right scalar multiplication** `fa` (Rockafellar §5): the function determined by the scaled
epigraph `a • epi f`.

For `a > 0` this is `(fa) x = a * f (a⁻¹ • x)` (`smulRight_apply_pos`) and its epigraph really
is `a • epi f` (`epi_smulRight`). At `a = 0` the epigraph identity fails, but the definition
still delivers Rockafellar's value `f0 = δ(· | 0)`; see the module docstring. -/
noncomputable def smulRight (f : E → EReal) (a : ℝ) : E → EReal := ofEpi (a • epi f)

/-- A positively scaled epigraph is an epigraph: scaling `epi f` by `a > 0` is the epigraph of
`x ↦ a * f (a⁻¹ • x)`. This is the computation behind every statement about `fa` for `a > 0`. -/
theorem smul_epi (ha : 0 < a) (f : E → EReal) :
    a • epi f = epi fun x => (a : EReal) * f (a⁻¹ • x) := by
  ext p
  rw [Set.mem_smul_set_iff_inv_smul_mem₀ ha.ne']
  simp only [mem_epi, Prod.smul_fst, Prod.smul_snd, smul_eq_mul]
  rw [Tdaf.EReal.coe_mul_le_coe_iff ha, inv_mul_eq_div]

/-- **Rockafellar §5.** `(fa) x = a * f (a⁻¹ • x)` for `a > 0`. -/
theorem smulRight_apply_pos (ha : 0 < a) (f : E → EReal) (x : E) :
    smulRight f a x = (a : EReal) * f (a⁻¹ • x) := by
  rw [smulRight, smul_epi ha, ofEpi_epi]

/-- Right scalar multiplication by `a > 0` *is* scalar multiplication of the epigraph.

The hypothesis `0 < a` is essential: see `not_isEpiLike_zero_smul_epi`. -/
theorem epi_smulRight (ha : 0 < a) (f : E → EReal) : epi (smulRight f a) = a • epi f :=
  epi_ofEpi ⟨_, smul_epi ha f⟩

/-- If `f ≡ +∞` then so is `fa`, for every `a` — including `a = 0`. This is Rockafellar's
parenthetical remark "trivially `f0 = f` if `f ≡ +∞`". -/
theorem smulRight_of_epi_eq_empty (h : epi f = ∅) (a : ℝ) : smulRight f a = ⊤ := by
  rw [smulRight, h, Set.smul_set_empty, ofEpi_empty]

/-- `0 • epi f` is the single point `(0, 0)` as soon as `f ≢ +∞`. -/
theorem zero_smul_epi (h : (dom f).Nonempty) : (0 : ℝ) • epi f = {(0 : E × ℝ)} := by
  rw [zero_smul_set ((epi_nonempty_iff f).2 h), Set.singleton_zero]

omit [Module ℝ E] in
/-- The function determined by the single point `(0, 0)` is `δ(· | 0)`. -/
theorem ofEpi_singleton_zero : ofEpi ({(0 : E × ℝ)} : Set (E × ℝ)) = indicatorFn ({0} : Set E) := by
  funext x
  by_cases hx : x = 0
  · subst hx
    have hind : indicatorFn ({0} : Set E) (0 : E) = 0 := indicatorFn_of_mem rfl
    rw [hind]
    refine le_antisymm ?_ (le_ofEpi fun μ hμ => ?_)
    · simpa using ofEpi_apply_le (F := ({(0 : E × ℝ)} : Set (E × ℝ)))
        (x := (0 : E)) (μ := (0 : ℝ)) rfl
    · rw [Set.mem_singleton_iff, Prod.mk_eq_zero] at hμ
      simp [hμ.2]
  · have hind : indicatorFn ({0} : Set E) x = ⊤ := indicatorFn_of_notMem hx
    rw [hind]
    refine ofEpi_eq_top_iff.2 fun μ hμ => hx ?_
    rw [Set.mem_singleton_iff, Prod.mk_eq_zero] at hμ
    exact hμ.1

/-- **Rockafellar §5**: `f0 = δ(· | 0)` when `f ≢ +∞`. -/
theorem smulRight_zero (h : (dom f).Nonempty) : smulRight f 0 = indicatorFn ({0} : Set E) := by
  rw [smulRight, zero_smul_epi h, ofEpi_singleton_zero]

/-- `0 • epi f` is never an epigraph, unless `f ≡ +∞`: its vertical section over the origin is the
single point `{0}`, which is not upward closed. This is why `epi_smulRight` is stated for
`a > 0` only — `epi (f0) = {0} ×ˢ Ici 0` is strictly larger than `0 • epi f`. -/
theorem not_isEpiLike_zero_smul_epi (h : (dom f).Nonempty) : ¬IsEpiLike ((0 : ℝ) • epi f) := by
  rw [zero_smul_epi h]
  intro hE
  have h1 : ((0 : E), (1 : ℝ)) ∈ ({(0 : E × ℝ)} : Set (E × ℝ)) :=
    hE.mem_of_le (x := (0 : E)) (μ := 0) (by simp [Prod.mk_eq_zero]) zero_le_one
  rw [Set.mem_singleton_iff, Prod.mk_eq_zero] at h1
  exact absurd h1.2 (by norm_num)

/-- The epigraph of `f0`, for `f ≢ +∞`: the closed half-line over the origin, which strictly
contains `0 • epi f = {(0, 0)}`. -/
theorem epi_smulRight_zero (h : (dom f).Nonempty) :
    epi (smulRight f 0) = ({0} : Set E) ×ˢ Ici (0 : ℝ) := by
  rw [smulRight_zero h, epi_indicatorFn]

/-- `δ(· | 0) ≤ f0`, with no hypothesis on `f`: the two sides agree when `f ≢ +∞` and the right-hand
side is `+∞` otherwise. This is the uniform form of `smulRight_zero`. -/
theorem indicatorFn_le_smulRight_zero (f : E → EReal) :
    indicatorFn ({0} : Set E) ≤ smulRight f 0 := by
  rw [← ofEpi_singleton_zero]
  refine ofEpi_mono ?_
  rintro p ⟨q, -, rfl⟩
  simp

/-- **Rockafellar §5**: right scalar multiplication preserves convexity.

The proof is Theorem 5.3 (`convexFn_ofEpi`) applied to the convex set `a • epi f`. Note that no
sign hypothesis on `a` is needed, because `Convex.smul` has none; Rockafellar defines `fa` only for
`0 ≤ a < ∞`, which is the range in which `fa` has its intended meaning. -/
theorem convexFn_smulRight (a : ℝ) (hf : ConvexFn f) : ConvexFn (smulRight f a) :=
  convexFn_ofEpi (hf.convex_epi.smul a)

/-- `f1 = f`: right scalar multiplication by `1` is the identity. -/
@[simp] theorem smulRight_one (f : E → EReal) : smulRight f 1 = f := by
  rw [smulRight, one_smul, ofEpi_epi]

/-- **Rockafellar §5.** `f` is positively homogeneous if and only if `fa = f` for every `a > 0`.

Both directions are `posHomogeneous_iff_isCone_epi` — positive homogeneity is `a • epi f =
epi f` — read through `ofEpi_epi` and `epi_smulRight`. -/
theorem posHomogeneous_iff_smulRight_eq : PosHomogeneous f ↔ ∀ a > 0, smulRight f a = f := by
  rw [posHomogeneous_iff_isCone_epi]
  refine ⟨fun h a ha => ?_, fun h a ha => ?_⟩
  · rw [smulRight, h a ha, ofEpi_epi]
  · rw [← epi_smulRight ha, h a ha]

/-- `f0` is positively homogeneous, whatever `f` is: it is either `δ(· | 0)`, the indicator of a
cone, or `+∞`. This is the degenerate case that makes `posHomogeneous_hom` work at `λ = 0`. -/
theorem posHomogeneous_smulRight_zero (f : E → EReal) : PosHomogeneous (smulRight f 0) := by
  by_cases h : (dom f).Nonempty
  · rw [smulRight_zero h]
    exact posHomogeneous_indicatorFn.2 fun a _ => by rw [Set.smul_set_singleton, smul_zero]
  · rw [Set.not_nonempty_iff_eq_empty] at h
    rw [smulRight_of_epi_eq_empty ((epi_eq_empty_iff f).2 h)]
    intro a ha x
    rw [Pi.top_apply, Pi.top_apply, _root_.EReal.coe_mul_top_of_pos ha]

/-- Scaling an epigraph by `0` does not see the difference between a set and the epigraph it
determines: both are empty together, and otherwise both collapse to `{(0, 0)}`. -/
theorem zero_smul_epi_ofEpi (F : Set (E × ℝ)) : (0 : ℝ) • epi (ofEpi F) = (0 : ℝ) • F := by
  rcases F.eq_empty_or_nonempty with rfl | hF
  · rw [ofEpi_empty, epi_top]
  · rw [zero_smul_set (hF.mono (subset_epi_ofEpi F)), zero_smul_set hF]

/-- **Rockafellar §5**: right scalar multiplication is an action, `f(ab) = (fa)b`.

The three cases are genuinely different: for `b > 0` and `a > 0` this is `epi_smulRight` and
associativity of the scalar action on sets; for `a = 0` it is positive homogeneity of `f0`; and for
`b = 0` it is `zero_smul_epi_ofEpi`, which is exactly the statement that the failure of
`epi (fa) = a • epi f` at `a = 0` does not propagate. -/
theorem smulRight_smulRight (f : E → EReal) (ha : 0 ≤ a) (hb : 0 ≤ b) :
    smulRight (smulRight f a) b = smulRight f (a * b) := by
  rcases hb.eq_or_lt with rfl | hb'
  · rw [mul_zero]
    simp only [smulRight]
    rw [zero_smul_epi_ofEpi, smul_smul, zero_mul]
  · rcases ha.eq_or_lt with rfl | ha'
    · rw [zero_mul]
      exact posHomogeneous_iff_smulRight_eq.1 (posHomogeneous_smulRight_zero f) b hb'
    · rw [smulRight, epi_smulRight ha', smul_smul, mul_comm b a, smulRight]

/-- Right scalar multiplication as a **monoid action** of `([0, ∞), *)` on `E → EReal`, packaged as
a monoid homomorphism into `Function.End (E → EReal)`. `smulRight_one` and
`smulRight_smulRight` are exactly the two axioms.

It is deliberately *not* declared as a `MulAction ℝ≥0 (E → EReal)` instance: `E → EReal` is a bare
Pi type, on which `•` already means the pointwise action, and shadowing that with an operation that
also moves the argument would be a trap. A `MonoidHom` into `Function.End` carries the same content
without touching instance resolution, and `MulAction.ofEndHom` turns it into an action on demand. -/
noncomputable def smulRightHom : ℝ≥0 →* Function.End (E → EReal) where
  toFun a f := smulRight f a
  map_one' := by
    funext f
    change smulRight f ((1 : ℝ≥0) : ℝ) = f
    rw [NNReal.coe_one, smulRight_one]
  map_mul' a b := by
    funext f
    change smulRight f ((a * b : ℝ≥0) : ℝ) = smulRight (smulRight f b) a
    rw [smulRight_smulRight f b.coe_nonneg a.coe_nonneg, NNReal.coe_mul, mul_comm]

/-- The monoid homomorphism `smulRightHom` is right scalar multiplication. -/
@[simp] theorem smulRightHom_apply (a : ℝ≥0) (f : E → EReal) :
    smulRightHom a f = smulRight f a := rfl

end SmulRight

/-! ### The level-1 lift -/

section LevelOneLift

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {f : E → EReal} {a : ℝ} {x : E}
  {p : ℝ × E}

/-- The **level-1 lift** of `f` to `ℝ × E`: `h (λ, x) = f x` if `λ = 1`, and `+∞` otherwise
(Rockafellar §5).

`hom f` is the positively homogeneous convex function generated by this lift, *not* the one
generated by `f`; see the module docstring. -/
noncomputable def levelOneLift (f : E → EReal) : ℝ × E → EReal :=
  Tdaf.ConvexAnalysis.restrict {p : ℝ × E | p.1 = 1} fun p => f p.2

omit [AddCommGroup E] [Module ℝ E] in
/-- The defining equation of the level-1 lift on the hyperplane `λ = 1`. -/
@[simp] theorem levelOneLift_of_fst_eq_one (h : p.1 = 1) : levelOneLift f p = f p.2 :=
  restrict_of_mem h

omit [AddCommGroup E] [Module ℝ E] in
/-- The level-1 lift is `+∞` off the hyperplane `λ = 1`. -/
@[simp] theorem levelOneLift_of_fst_ne_one (h : p.1 ≠ 1) : levelOneLift f p = ⊤ :=
  restrict_of_notMem h

omit [AddCommGroup E] [Module ℝ E] in
/-- The level-1 lift, evaluated on the hyperplane `λ = 1`. -/
theorem levelOneLift_apply_one (f : E → EReal) (x : E) : levelOneLift f (1, x) = f x :=
  levelOneLift_of_fst_eq_one rfl

omit [AddCommGroup E] [Module ℝ E] in
/-- The level-1 lift, evaluated off the hyperplane `λ = 1`. -/
theorem levelOneLift_apply_of_ne (h : a ≠ 1) (x : E) : levelOneLift f (a, x) = ⊤ :=
  levelOneLift_of_fst_ne_one h

/-- The epigraph of the level-1 lift is `{1} ×ˢ epi f`, read in `(ℝ × E) × ℝ` through the
associativity shuffle. -/
theorem epi_levelOneLift (f : E → EReal) :
    epi (levelOneLift f) = LinearEquiv.prodAssoc ℝ ℝ E ℝ ⁻¹' ({1} ×ˢ epi f) := by
  ext q
  by_cases h : q.1.1 = 1 <;> simp [mem_epi, h, Set.mem_prod]

omit [AddCommGroup E] [Module ℝ E] in
/-- Membership of the epigraph of the level-1 lift, unfolded: `((λ, x), μ)` lies in it exactly when
`λ = 1` and `μ ≥ f x`. -/
theorem mem_epi_levelOneLift {q : (ℝ × E) × ℝ} :
    q ∈ epi (levelOneLift f) ↔ q.1.1 = 1 ∧ f q.1.2 ≤ ((q.2 : ℝ) : EReal) := by
  by_cases h : q.1.1 = 1 <;> simp [mem_epi, h]

omit [AddCommGroup E] [Module ℝ E] in
/-- The vectors that generate the cone of `homCone`: `((1, x), μ)` with `μ ≥ f x`. -/
theorem mk_one_mem_epi_levelOneLift {x : E} {μ : ℝ} :
    (((1, x), μ) : (ℝ × E) × ℝ) ∈ epi (levelOneLift f) ↔ f x ≤ ((μ : ℝ) : EReal) := by
  simp

/-- The level-1 lift of a convex function is convex: its epigraph is a linear preimage of the
convex set `{1} ×ˢ epi f`. -/
theorem convexFn_levelOneLift (hf : ConvexFn f) : ConvexFn (levelOneLift f) := by
  refine ⟨?_⟩
  rw [epi_levelOneLift]
  exact ((convex_singleton (1 : ℝ)).prod hf.convex_epi).linear_preimage
    (LinearEquiv.prodAssoc ℝ ℝ E ℝ).toLinearMap

end LevelOneLift

/-! ### Homogenisation -/

section Hom

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {f : E → EReal} {a : ℝ} {x : E}
  {g : ℝ × E → EReal}

/-- The **positively homogeneous convex function generated by the level-1 lift of `f`**
(Rockafellar §5), assembled slice by slice out of the right scalar multiples `fλ`:

`hom f (λ, x) = (fλ) x` for `λ ≥ 0`, and `+∞` for `λ < 0`.

No closure is taken. See the module docstring for why this is a different operator from "the
positively homogeneous convex function generated by `f`". -/
noncomputable def hom (f : E → EReal) : ℝ × E → EReal :=
  fun p => if 0 ≤ p.1 then smulRight f p.1 p.2 else ⊤

/-- The defining equation at `λ ≥ 0`: the slice of `hom f` at level `λ` is `fλ`. -/
theorem hom_apply_nonneg (ha : 0 ≤ a) (f : E → EReal) (x : E) :
    hom f (a, x) = smulRight f a x := ite_eq_left_of_eq_true _ _ (eq_true ha)

/-- The defining equation at `λ > 0`: `hom f (λ, x) = λ * f (λ⁻¹ • x)`. -/
theorem hom_apply_pos (ha : 0 < a) (f : E → EReal) (x : E) :
    hom f (a, x) = (a : EReal) * f (a⁻¹ • x) := by
  rw [hom_apply_nonneg ha.le, smulRight_apply_pos ha]

/-- The defining equation at `λ = 0`: the slice is `f0`, which is `δ(· | 0)` unless `f ≡ +∞`. -/
theorem hom_apply_zero (f : E → EReal) (x : E) : hom f (0, x) = smulRight f 0 x :=
  hom_apply_nonneg le_rfl f x

/-- `hom f` restricts to `f` on the level `λ = 1`: this is the sense in which `hom f` is a
homogenisation *of `f`*. -/
theorem hom_apply_one (f : E → EReal) (x : E) : hom f (1, x) = f x := by
  rw [hom_apply_pos one_pos, inv_one, one_smul, _root_.EReal.coe_one, one_mul]

/-- `hom f` is `+∞` on the half-space `λ < 0`. -/
theorem hom_apply_neg (ha : a < 0) (f : E → EReal) (x : E) : hom f (a, x) = ⊤ :=
  ite_eq_right_of_eq_false _ _ (eq_false (not_le.2 ha))

/-- If `f ≡ +∞` then `hom f ≡ +∞`. -/
theorem hom_of_epi_eq_empty (h : epi f = ∅) : hom f = ⊤ := by
  funext p
  obtain ⟨a, x⟩ := p
  rcases le_or_gt 0 a with ha | ha
  · rw [hom_apply_nonneg ha, smulRight_of_epi_eq_empty h, Pi.top_apply, Pi.top_apply]
  · rw [hom_apply_neg ha, Pi.top_apply]

/-- **The homogenisation of a function that avoids `-∞` avoids it too.** `hom f (λ, x)` is `+∞`
for `λ < 0`, an indicator value for `λ = 0`, and `λ * f (λ⁻¹ x)` for `λ > 0`, and none of the three
is `-∞`.

Only the `ne_bot` half of `Proper f` is needed: if `dom f` is empty then `hom f ≡ +∞`. -/
theorem hom_ne_bot (hf : ∀ x, f x ≠ ⊥) (q : ℝ × E) : hom f q ≠ ⊥ := by
  obtain ⟨a, x⟩ := q
  rcases lt_trichotomy a 0 with h | h | h
  · rw [hom_apply_neg h]
    exact top_ne_bot
  · subst h
    rw [hom_apply_zero]
    rcases Set.eq_empty_or_nonempty (dom f) with hd | hd
    · rw [smulRight_of_epi_eq_empty ((epi_eq_empty_iff f).2 hd), Pi.top_apply]
      exact top_ne_bot
    · rw [smulRight_zero hd]
      exact indicatorFn_ne_bot _ _
  · rw [hom_apply_pos h]
    exact Tdaf.EReal.coe_mul_ne_bot h.le (hf _)

/-- `hom f (λ, λ x) = λ * f x` for `λ ≥ 0`: the substitution `y = λ x` that turns the homogenisation
into left scalar multiplication.

At `λ = 0` both sides are `0`, by two conventions at once: `f0 = δ(· | 0)` and `0 · ∞ = 0`. -/
theorem hom_apply_smul (hdom : (dom f).Nonempty) (ha : 0 ≤ a) (z : E) :
    hom f (a, a • z) = (a : EReal) * f z := by
  rcases ha.lt_or_eq with ha' | ha'
  · rw [hom_apply_pos ha', inv_smul_smul₀ ha'.ne']
  · subst ha'
    rw [zero_smul, hom_apply_zero, smulRight_zero hdom]
    simp

/-- `hom f` never exceeds the level-1 lift, and agrees with it at `λ = 1`. -/
theorem hom_le_levelOneLift (f : E → EReal) : hom f ≤ levelOneLift f := by
  rintro ⟨a, x⟩
  by_cases h : a = 1
  · subst h
    rw [hom_apply_one, levelOneLift_apply_one]
  · rw [levelOneLift_apply_of_ne h]
    exact le_top

/-- **`hom f` is positively homogeneous**, with no hypothesis on `f` at all.

Scaling `(λ, x)` by `c > 0`: at `λ > 0` the claim is the identity
`(cλ) * f ((cλ)⁻¹ • (c • x)) = c * (λ * f (λ⁻¹ • x))`; at `λ = 0` it is positive homogeneity of `f0`
(`posHomogeneous_smulRight_zero`), which is where the `a = 0` degeneracy is absorbed; at
`λ < 0` both sides are `+∞`. -/
theorem posHomogeneous_hom (f : E → EReal) : PosHomogeneous (hom f) := by
  rintro c hc ⟨a, x⟩
  simp only [Prod.smul_mk, smul_eq_mul]
  rcases lt_trichotomy a 0 with ha | rfl | ha
  · rw [hom_apply_neg (mul_neg_of_pos_of_neg hc ha), hom_apply_neg ha,
      _root_.EReal.coe_mul_top_of_pos hc]
  · rw [mul_zero, hom_apply_zero, hom_apply_zero]
    exact posHomogeneous_smulRight_zero f c hc x
  · have hx : (c * a)⁻¹ • (c • x) = a⁻¹ • x := by
      rw [smul_smul, mul_inv, mul_comm c⁻¹ a⁻¹, mul_assoc, inv_mul_cancel₀ hc.ne', mul_one]
    rw [hom_apply_pos (mul_pos hc ha), hom_apply_pos ha, hx, _root_.EReal.coe_mul, mul_assoc]

/-- **The upper-bound half of the maximality property**: every positively homogeneous `g` with
`g 0 ≤ 0` that is majorised by the level-1 lift of `f` is majorised by `hom f`.

Convexity of `g` is not used, and neither is `f ≢ +∞`. The hypothesis `g 0 ≤ 0` is *not* removable:
for `f ≡ 0` on `E = ℝ`, the indicator of the open half-space `{λ > 0}` is positively homogeneous,
convex, and below the level-1 lift, but takes the value `+∞ > 0 = hom f 0` at the origin. -/
theorem le_hom (hg : PosHomogeneous g) (h0 : g 0 ≤ 0) (hle : g ≤ levelOneLift f) : g ≤ hom f := by
  rintro ⟨a, x⟩
  rcases lt_trichotomy a 0 with ha | rfl | ha
  · rw [hom_apply_neg ha]
    exact le_top
  · rw [hom_apply_zero]
    by_cases hx : x = 0
    · subst hx
      have h00 : ((0 : ℝ), (0 : E)) = (0 : ℝ × E) := rfl
      have hind : indicatorFn ({0} : Set E) (0 : E) = 0 := indicatorFn_of_mem rfl
      rw [h00]
      refine h0.trans ?_
      have h := indicatorFn_le_smulRight_zero f 0
      rwa [hind] at h
    · have htop : smulRight f 0 x = ⊤ := by
        have hind : indicatorFn ({0} : Set E) x = ⊤ := indicatorFn_of_notMem hx
        have h := indicatorFn_le_smulRight_zero f x
        rw [hind] at h
        exact top_le_iff.1 h
      rw [htop]
      exact le_top
  · have hp : a • ((1, a⁻¹ • x) : ℝ × E) = (a, x) := by
      rw [Prod.smul_mk, smul_smul, mul_inv_cancel₀ ha.ne', one_smul, smul_eq_mul, mul_one]
    calc g (a, x) = (a : EReal) * g (1, a⁻¹ • x) := by rw [← hp, hg a ha]
      _ ≤ (a : EReal) * f (a⁻¹ • x) := by
          refine mul_le_mul_of_nonneg_left ?_ (by exact_mod_cast ha.le)
          simpa [levelOneLift_apply_one] using hle (1, a⁻¹ • x)
      _ = hom f (a, x) := (hom_apply_pos ha f x).symm

end Hom

/-! ### The cone generated by the level-1 lift -/

section Cone

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {f : E → EReal} {a : ℝ}
  {q : (ℝ × E) × ℝ}

/-- The convex cone in `(ℝ × E) × ℝ` generated by the epigraph of the level-1 lift of `f`: the
origin together with all positive multiples of `epi (levelOneLift f)`.

This is the set to which Rockafellar applies Theorem 5.3 to obtain `hom f`
(`hom_eq_ofEpi_homCone`). Under the associativity shuffle it is the cone generated by
`{1} ×ˢ epi f` in `ℝ × (E × ℝ)` (`homCone_eq_preimage`). It is *not* an epigraph:
`epi_hom` describes the ray that has to be added. -/
noncomputable def homCone (f : E → EReal) : Set ((ℝ × E) × ℝ) :=
  {0} ∪ ⋃ a > (0 : ℝ), a • epi (levelOneLift f)

/-- Membership of the generated cone, unfolded. -/
theorem mem_homCone_iff_exists :
    q ∈ homCone f ↔ q = 0 ∨ ∃ a > (0 : ℝ), q ∈ a • epi (levelOneLift f) := by
  simp [homCone]

/-- Membership of `a • epi (levelOneLift f)` for `a > 0`: the first coordinate pins down `a`. -/
theorem mem_smul_epi_levelOneLift (ha : 0 < a) :
    q ∈ a • epi (levelOneLift f) ↔
      q.1.1 = a ∧ f (a⁻¹ • q.1.2) ≤ ((a⁻¹ * q.2 : ℝ) : EReal) := by
  rw [Set.mem_smul_set_iff_inv_smul_mem₀ ha.ne', mem_epi]
  have hfst : (a⁻¹ • q).1.1 = a⁻¹ * q.1.1 := rfl
  by_cases h1 : q.1.1 = a
  · have hone : (a⁻¹ • q).1.1 = 1 := by rw [hfst, h1, inv_mul_cancel₀ ha.ne']
    rw [levelOneLift_of_fst_eq_one hone]
    simp [h1, Prod.smul_fst, Prod.smul_snd]
  · have hne : (a⁻¹ • q).1.1 ≠ 1 := by
      rw [hfst]
      intro hc
      exact h1 (by field_simp at hc; linarith)
    refine iff_of_false ?_ fun h => h1 h.1
    rw [levelOneLift_of_fst_ne_one hne, top_le_iff]
    exact _root_.EReal.coe_ne_top _

/-- The membership criterion for the generated cone, in closed form. -/
theorem mem_homCone_iff :
    q ∈ homCone f ↔
      q = 0 ∨ (0 < q.1.1 ∧ f (q.1.1⁻¹ • q.1.2) ≤ ((q.1.1⁻¹ * q.2 : ℝ) : EReal)) := by
  rw [mem_homCone_iff_exists]
  refine or_congr_right ⟨fun ⟨a, ha, hq⟩ => ?_, fun ⟨ha, hq⟩ => ?_⟩
  · rw [mem_smul_epi_levelOneLift ha] at hq
    obtain ⟨rfl, hq⟩ := hq
    exact ⟨ha, hq⟩
  · exact ⟨q.1.1, ha, (mem_smul_epi_levelOneLift ha).2 ⟨rfl, hq⟩⟩

/-- The generated cone is a cone: it is invariant under multiplication by positive scalars. -/
theorem smul_homCone (hc : 0 < a) (f : E → EReal) : a • homCone f = homCone f := by
  ext q
  simp only [Set.mem_smul_set_iff_inv_smul_mem₀ hc.ne', mem_homCone_iff_exists]
  constructor
  · rintro (h | ⟨b, hb, hq⟩)
    · left
      have : a • (a⁻¹ • q) = a • (0 : (ℝ × E) × ℝ) := by rw [h]
      rwa [smul_inv_smul₀ hc.ne', smul_zero] at this
    · right
      refine ⟨a * b, mul_pos hc hb, ?_⟩
      have : a • (a⁻¹ • q) ∈ a • (b • epi (levelOneLift f)) := Set.smul_mem_smul_set hq
      rwa [smul_inv_smul₀ hc.ne', smul_smul] at this
  · rintro (rfl | ⟨b, hb, hq⟩)
    · exact Or.inl (smul_zero _)
    · refine Or.inr ⟨a⁻¹ * b, mul_pos (inv_pos.2 hc) hb, ?_⟩
      rw [← smul_smul]
      exact Set.smul_mem_smul_set hq

/-- The generated cone is convex.

By Rockafellar's Theorem 2.6 (`convex_iff_add_mem_of_isCone`) it is enough to check closure
under addition, and that is `Convex.add_smul`: `a • S + b • S = (a + b) • S` for convex `S`. -/
theorem convex_homCone (hf : ConvexFn f) : Convex ℝ (homCone f) := by
  have hS : Convex ℝ (epi (levelOneLift f)) := (convexFn_levelOneLift hf).convex_epi
  rw [convex_iff_add_mem_of_isCone fun c hc => smul_homCone hc f]
  intro p hp q hq
  rw [mem_homCone_iff_exists] at hp hq ⊢
  rcases hp with rfl | ⟨a, ha, hp⟩
  · rw [zero_add]
    exact hq
  rcases hq with rfl | ⟨b, hb, hq⟩
  · rw [add_zero]
    exact Or.inr ⟨a, ha, hp⟩
  refine Or.inr ⟨a + b, by positivity, ?_⟩
  rw [hS.add_smul ha.le hb.le]
  exact Set.add_mem_add hp hq

omit [Module ℝ E] in
/-- A point of `(ℝ × E) × ℝ` whose homogenising coordinate is nonzero is not the origin. -/
theorem mk_ne_zero_of_ne_zero (ha : a ≠ 0) (x : E) (μ : ℝ) :
    (((a, x), μ) : (ℝ × E) × ℝ) ≠ 0 := by simp [Prod.mk_eq_zero, ha]

/-- **Rockafellar §5**: `hom f` is the function obtained from Theorem 5.3 applied to the convex cone
generated by the epigraph of the level-1 lift of `f`.

The hypothesis `f ≢ +∞` is needed: for `f ≡ +∞` the cone degenerates to `{0}`, whose associated
function is `δ(· | 0)`, whereas `hom f ≡ +∞`. -/
theorem hom_eq_ofEpi_homCone (hdom : (dom f).Nonempty) : hom f = ofEpi (homCone f) := by
  funext p
  obtain ⟨a, x⟩ := p
  rcases lt_trichotomy a 0 with ha | rfl | ha
  · rw [hom_apply_neg ha]
    refine (ofEpi_eq_top_iff.2 fun μ hμ => ?_).symm
    rcases mem_homCone_iff.1 hμ with h | ⟨h, -⟩
    · exact mk_ne_zero_of_ne_zero ha.ne x μ h
    · exact absurd h (by exact_mod_cast ha.asymm)
  · rw [hom_apply_zero, smulRight_zero hdom]
    by_cases hx : x = 0
    · subst hx
      have hind : indicatorFn ({0} : Set E) (0 : E) = 0 := indicatorFn_of_mem rfl
      rw [hind]
      refine le_antisymm (le_ofEpi fun μ hμ => ?_) ?_
      · rcases mem_homCone_iff.1 hμ with h | ⟨h, -⟩
        · rw [Prod.mk_eq_zero] at h
          simp [h.2]
        · exact absurd h (by norm_num)
      · simpa using ofEpi_apply_le (F := homCone f) (x := ((0 : ℝ), (0 : E))) (μ := (0 : ℝ))
          (mem_homCone_iff.2 (Or.inl rfl))
    · have hind : indicatorFn ({0} : Set E) x = ⊤ := indicatorFn_of_notMem hx
      rw [hind]
      refine (ofEpi_eq_top_iff.2 fun μ hμ => ?_).symm
      rcases mem_homCone_iff.1 hμ with h | ⟨h, -⟩
      · rw [Prod.mk_eq_zero, Prod.mk_eq_zero] at h
        exact hx h.1.2
      · exact absurd h (by norm_num)
  · refine ((ofEpi_apply_congr (F := homCone f) (G := epi (hom f)) fun μ => ?_).trans
      (congrFun (ofEpi_epi (hom f)) (a, x))).symm
    rw [mem_homCone_iff, mem_epi, hom_apply_pos ha, Tdaf.EReal.coe_mul_le_coe_iff ha]
    refine ⟨fun h => ?_, fun h => Or.inr ⟨ha, by rwa [inv_mul_eq_div]⟩⟩
    rcases h with h | ⟨-, h⟩
    · exact absurd h (mk_ne_zero_of_ne_zero ha.ne' x μ)
    · rwa [inv_mul_eq_div] at h

/-- **Rockafellar §5**: `hom f` is convex whenever `f` is.

For `f ≢ +∞` this is Theorem 5.3 applied to the cone `homCone f`, which is convex because it
is a cone closed under addition (Theorem 2.6). The remaining case `f ≡ +∞` is degenerate: then
`hom f ≡ +∞`, whose epigraph is empty. -/
theorem convexFn_hom (hf : ConvexFn f) : ConvexFn (hom f) := by
  by_cases hdom : (dom f).Nonempty
  · rw [hom_eq_ofEpi_homCone hdom]
    exact convexFn_ofEpi (convex_homCone hf)
  · rw [Set.not_nonempty_iff_eq_empty] at hdom
    rw [hom_of_epi_eq_empty ((epi_eq_empty_iff f).2 hdom)]
    exact ⟨by rw [epi_top]; exact convex_empty⟩

/-- **The maximality property of `hom f`** (Rockafellar §5).

`hom f` is the *greatest* positively homogeneous convex function `g` on `ℝ × E` satisfying
`g 0 ≤ 0` and `g ≤ levelOneLift f`. This is the precise form of the book's "it is the greatest of
the positively homogeneous convex functions `g` such that `g 0 ≤ 0` and `g ≤ h`", applied to the
level-1 lift `h` of `f`.

Three points about the statement:

* the side condition `g 0 ≤ 0` cannot be dropped — see `le_hom` for the counterexample;
* convexity of `g` is not used in the upper-bound half (`le_hom` proves the stronger
  statement), but it belongs in the set, since it is what makes `hom f` a *member*;
* `f ≢ +∞` is needed only for membership, and only for `hom f 0 ≤ 0`: for `f ≡ +∞` one has
  `hom f ≡ +∞`, whose value at the origin is `+∞`, and the greatest element of the set is
  `δ(· | 0)` instead. -/
theorem hom_isGreatest (hf : ConvexFn f) (hdom : (dom f).Nonempty) :
    IsGreatest {g : ℝ × E → EReal |
      PosHomogeneous g ∧ ConvexFn g ∧ g 0 ≤ 0 ∧ g ≤ levelOneLift f} (hom f) := by
  refine ⟨⟨posHomogeneous_hom f, convexFn_hom hf, ?_, hom_le_levelOneLift f⟩, ?_⟩
  · have h00 : (0 : ℝ × E) = (0, 0) := rfl
    have hind : indicatorFn ({0} : Set E) (0 : E) = 0 := indicatorFn_of_mem rfl
    rw [h00, hom_apply_zero, smulRight_zero hdom, hind]
  · rintro g ⟨hg, -, h0, hle⟩
    exact le_hom hg h0 hle

/-- **The epigraph of `hom f` against the cone that generates it.**

`epi (hom f)` is *not* the cone `homCone f`: the cone meets the hyperplane `λ = 0` in the
single point `0`, whereas an epigraph must contain the whole ray above it. The two differ exactly by
that ray, `{0} ×ˢ Ici 0`. (Equivalently, `epi (hom f)` is the epi-closure `epi (ofEpi (homCone f))`
of the cone, by `hom_eq_ofEpi_homCone`.) -/
theorem epi_hom (hdom : (dom f).Nonempty) :
    epi (hom f) = homCone f ∪ ({0} : Set (ℝ × E)) ×ˢ Ici (0 : ℝ) := by
  ext q
  obtain ⟨⟨a, x⟩, μ⟩ := q
  rcases lt_trichotomy a 0 with ha | rfl | ha
  · simp only [mem_epi, hom_apply_neg ha, Set.mem_union, mem_homCone_iff, Set.mem_prod,
      Set.mem_singleton_iff, Set.mem_Ici]
    refine iff_of_false (EReal.coe_lt_top μ).not_ge ?_
    rintro ((h | ⟨h, -⟩) | ⟨h, -⟩)
    · exact mk_ne_zero_of_ne_zero ha.ne x μ h
    · exact absurd h (by exact_mod_cast ha.asymm)
    · exact ha.ne (congrArg (fun p : ℝ × E => p.1) h)
  · have hL : (((0 : ℝ), x), μ) ∈ epi (hom f) ↔ x = 0 ∧ 0 ≤ μ := by
      rw [mem_epi, hom_apply_zero, ← mk_mem_epi, epi_smulRight_zero hdom]
      simp
    have hR : (((0 : ℝ), x), μ) ∈ homCone f ∪ ({0} : Set (ℝ × E)) ×ˢ Ici (0 : ℝ) ↔
        x = 0 ∧ 0 ≤ μ := by
      rw [Set.mem_union, mem_homCone_iff]
      constructor
      · rintro ((h | ⟨h, -⟩) | ⟨h, hμ⟩)
        · rw [Prod.mk_eq_zero, Prod.mk_eq_zero] at h
          exact ⟨h.1.2, le_of_eq h.2.symm⟩
        · exact absurd h (lt_irrefl 0)
        · rw [Set.mem_singleton_iff, Prod.mk_eq_zero] at h
          exact ⟨h.2, hμ⟩
      · rintro ⟨rfl, hμ⟩
        exact Or.inr ⟨by simp, hμ⟩
    exact hL.trans hR.symm
  · simp only [Set.mem_union, mem_homCone_iff, Set.mem_prod, Set.mem_singleton_iff, mem_epi,
      hom_apply_pos ha, Tdaf.EReal.coe_mul_le_coe_iff ha]
    constructor
    · intro h
      exact Or.inl (Or.inr ⟨ha, by rwa [inv_mul_eq_div]⟩)
    · rintro ((h | ⟨-, h⟩) | ⟨h, -⟩)
      · exact absurd h (mk_ne_zero_of_ne_zero ha.ne' x μ)
      · rwa [inv_mul_eq_div] at h
      · exact absurd (congrArg (fun p : ℝ × E => p.1) h) ha.ne'

/-- The epigraph of `hom f`, bundled as a Mathlib `ConvexCone`.

`posHomogeneous_hom` and `convexFn_hom` say precisely that `epi (hom f)` is a convex cone
in `(ℝ × E) × ℝ`, and §8, §13 and §14 all work with it in that form. This is
`PosHomogeneous.epiCone` specialised to `hom f`, except that no `∀ x, f x ≠ ⊥` hypothesis is
needed: closure under addition comes from Theorem 2.6 (`convex_iff_add_mem_of_isCone`) rather
than from subadditivity, and Theorem 2.6 has no such hypothesis. -/
noncomputable def homEpiCone (hf : ConvexFn f) : ConvexCone ℝ ((ℝ × E) × ℝ) where
  carrier := epi (hom f)
  smul_mem' c hc q hq := by
    rw [← posHomogeneous_iff_isCone_epi.1 (posHomogeneous_hom f) c hc]
    exact Set.smul_mem_smul_set hq
  add_mem' p hp q hq :=
    (convex_iff_add_mem_of_isCone
      (posHomogeneous_iff_isCone_epi.1 (posHomogeneous_hom f))).1 (convexFn_hom hf).convex_epi
      p hp q hq

/-- The carrier of `homEpiCone` is the epigraph of `hom f`. -/
@[simp] theorem coe_homEpiCone (hf : ConvexFn f) :
    (homEpiCone hf : Set ((ℝ × E) × ℝ)) = epi (hom f) := rfl

/-! ### The associativity shuffle

`epi (hom f)` and `homCone f` live in `(ℝ × E) × ℝ`, because that is where epigraphs of
functions on `ℝ × E` live. The cone generated by `{1} ×ˢ epi f` — the form in which §8, §13.5 and
§14.4 use it — lives in `ℝ × (E × ℝ)`. The two are related by `LinearEquiv.prodAssoc ℝ ℝ E ℝ`. -/

/-- The generated cone, read in `ℝ × (E × ℝ)`: it is the cone generated by `{1} ×ˢ epi f`, pulled
back along the associativity shuffle. -/
theorem homCone_eq_preimage (f : E → EReal) :
    homCone f = LinearEquiv.prodAssoc ℝ ℝ E ℝ ⁻¹' ({0} ∪ ⋃ a > (0 : ℝ), a • ({1} ×ˢ epi f)) := by
  ext q
  simp only [homCone, Set.mem_preimage, Set.mem_union, Set.mem_singleton_iff, Set.mem_iUnion,
    exists_prop]
  refine or_congr ?_ (exists_congr fun a => and_congr_right fun ha => ?_)
  · refine ⟨fun h => by rw [h, map_zero], fun h => ?_⟩
    have h' := congrArg (LinearEquiv.prodAssoc ℝ ℝ E ℝ).symm h
    rwa [LinearEquiv.symm_apply_apply, map_zero] at h'
  · rw [Set.mem_smul_set_iff_inv_smul_mem₀ ha.ne', Set.mem_smul_set_iff_inv_smul_mem₀ ha.ne',
      epi_levelOneLift, Set.mem_preimage, map_smul]

/-- The generated cone, transported to `ℝ × (E × ℝ)`: it *is* the convex cone generated by
`{1} ×ˢ epi f`. -/
theorem prodAssoc_image_homCone (f : E → EReal) :
    LinearEquiv.prodAssoc ℝ ℝ E ℝ '' homCone f = {0} ∪ ⋃ a > (0 : ℝ), a • ({1} ×ˢ epi f) := by
  rw [homCone_eq_preimage,
    Set.image_preimage_eq _ (LinearEquiv.prodAssoc ℝ ℝ E ℝ).surjective]

end Cone

end Tdaf.ConvexAnalysis
