import Tdaf.Analysis.Convex.Homogeneous
import Tdaf.Analysis.Convex.Operations.Epi

/-!
# Right scalar multiplication and homogenisation

Two operations built from scalar multiplication of epigraphs.

*Right scalar multiplication* `fλ` is the function whose epigraph is `λ • epi f`; for `λ > 0` it is
`(fλ) x = λ * f (λ⁻¹ • x)`, and `f0 = δ(· | 0)`. It is a monoid action of `([0, ∞), *)` on
functions, and positive homogeneity of `f` is exactly `fλ = f` for all `λ > 0`.

*Homogenisation* `hom f` is the positively homogeneous convex function on `ℝ × E` assembled from
the functions `fλ`, one for each `λ ≥ 0`; its epigraph is the convex cone generated by
`{1} ×ˢ epi f`, one dimension up, with one ray added. It is the function generated by the *level-1
lift* of `f`, not the one generated by `f` itself — only the first keeps the `λ` variable that
recession functions, support functions of level sets and the two-step homogenisation used for
polarity all integrate over.

## Main definitions

* `smulRight f a` — Rockafellar's `fa`, defined as `ofEpi (a • epi f)`; `smulRightHom` packages it
  as a monoid homomorphism `ℝ≥0 →* Function.End (E → EReal)`.
* `levelOneLift f` — the level-1 lift `h (λ, x) = f x` if `λ = 1`, `⊤` otherwise.
* `hom f` — the positively homogeneous convex function on `ℝ × E` generated by `levelOneLift f`.
* `homCone f` — the convex cone generated by `epi (levelOneLift f)`, which is what `hom f` is
  `ofEpi` of; `homEpiCone` bundles `epi (hom f)` as a `ConvexCone ℝ ((ℝ × E) × ℝ)`.

## Main results

* `smulRight_apply_pos`, `smulRight_zero` — the values of `fa` for `a > 0` and for `a = 0`.
* `epi_smulRight` — `epi (fa) = a • epi f`, **for `a > 0` only**; see below.
* `convexFn_smulRight`, `smulRight_one`, `smulRight_smulRight`,
  `posHomogeneous_iff_smulRight_eq` — convexity is preserved, `fa` is a monoid action, and `f` is
  positively homogeneous exactly when `fa = f` for all `a > 0`.
* `hom_apply_pos`, `hom_apply_one`, `hom_apply_neg`, `hom_apply_smul` — the defining equations.
* `posHomogeneous_hom`, `convexFn_hom`, `hom_ne_bot` — `hom f` is positively homogeneous, convex
  as soon as `f` is, and avoids `-∞` as soon as `f` does.
* `hom_isGreatest` — the **maximality property**: `hom f` is the greatest positively homogeneous
  convex `g` with `g 0 ≤ 0` and `g ≤ levelOneLift f`.
* `hom_eq_ofEpi_homCone`, `epi_hom`, `homCone_eq_preimage`, `prodAssoc_image_homCone` — the cone
  description, and the shuffle relating it to the cone over `{1} ×ˢ epi f` in `ℝ × (E × ℝ)`.

## Implementation notes

`epi (fa) = a • epi f` fails at `a = 0`: there `0 • epi f` is `{(0, 0)}` whenever `epi f` is
nonempty, which is not an epigraph, so `epi (f0) = {0} ×ˢ Ici 0` is strictly larger. The definition
`fa = ofEpi (a • epi f)` still delivers Rockafellar's value, since `ofEpi` sees only the lower
boundary; the same degeneracy reappears one dimension up in `epi_hom`. The side condition `f ≢ +∞`
on `f0 = δ(· | 0)` is likewise not decoration: for `f ≡ +∞`, `epi f = ∅` and `fa = +∞` for every
`a`. It is needed in `smulRight_zero`, `hom_eq_ofEpi_homCone`, `epi_hom` and the membership half of
`hom_isGreatest`, and nowhere else.

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §5.
-/

open Set Pointwise

open scoped NNReal

namespace Tdaf.ConvexAnalysis

/-! ### Auxiliary facts about epigraphs and `ofEpi` -/

section Aux

variable {E : Type*} {f : E → EReal} {F G : Set (E × ℝ)} {x : E}

end Aux

/-! ### Right scalar multiplication -/

section SmulRight

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {f : E → EReal} {a b : ℝ} {x : E}

/-- **Right scalar multiplication** `fa`: the function determined by the scaled epigraph
`a • epi f`. For `a > 0` this is `(fa) x = a * f (a⁻¹ • x)` and its epigraph really is
`a • epi f`; at `a = 0` the epigraph identity fails, but the definition still delivers
Rockafellar's value `f0 = δ(· | 0)`. -/
noncomputable def smulRight (f : E → EReal) (a : ℝ) : E → EReal := ofEpi (a • epi f)

/-- A positively scaled epigraph is an epigraph: scaling `epi f` by `a > 0` is the epigraph of
`x ↦ a * f (a⁻¹ • x)`. This is the computation behind every statement about `fa` for `a > 0`. -/
theorem smul_epi (ha : 0 < a) (f : E → EReal) :
    a • epi f = epi fun x => (a : EReal) * f (a⁻¹ • x) := by
  ext p
  rw [Set.mem_smul_set_iff_inv_smul_mem₀ ha.ne']
  simp only [mem_epi, Prod.smul_fst, Prod.smul_snd, smul_eq_mul]
  rw [Tdaf.EReal.coe_mul_le_coe_iff ha, inv_mul_eq_div]

/-- `(fa) x = a * f (a⁻¹ • x)` for `a > 0`. -/
theorem smulRight_apply_pos (ha : 0 < a) (f : E → EReal) (x : E) :
    smulRight f a x = (a : EReal) * f (a⁻¹ • x) := by
  rw [smulRight, smul_epi ha, ofEpi_epi]

/-- Right scalar multiplication by `a > 0` *is* scalar multiplication of the epigraph.

The hypothesis `0 < a` is essential: see `not_isEpiLike_zero_smul_epi`. -/
theorem epi_smulRight (ha : 0 < a) (f : E → EReal) : epi (smulRight f a) = a • epi f :=
  epi_ofEpi ⟨_, smul_epi ha f⟩

/-- If `f ≡ +∞` then so is `fa`, for every `a` — including `a = 0`. This is Rockafellar's
parenthetical remark "trivially `f0 = f` if `f ≡ +∞`". -/
theorem smulRight_of_epi_eq_empty (h : epi f = ∅) (a : ℝ) : smulRight f a = ⊤ := by
  rw [smulRight, h, Set.smul_set_empty, ofEpi_empty]

/-- `0 • epi f` is the single point `(0, 0)` as soon as `f ≢ +∞`. -/
theorem zero_smul_epi (h : (dom f).Nonempty) : (0 : ℝ) • epi f = {(0 : E × ℝ)} := by
  rw [zero_smul_set ((epi_nonempty_iff f).2 h), Set.singleton_zero]

omit [Module ℝ E] in
/-- The function determined by the single point `(0, 0)` is `δ(· | 0)`. -/
theorem ofEpi_singleton_zero : ofEpi ({(0 : E × ℝ)} : Set (E × ℝ)) = indicatorFn ({0} : Set E) := by
  funext x
  by_cases hx : x = 0
  · subst hx
    have hind : indicatorFn ({0} : Set E) (0 : E) = 0 := indicatorFn_of_mem rfl
    rw [hind]
    refine le_antisymm ?_ (le_ofEpi fun μ hμ => ?_)
    · simpa using ofEpi_apply_le (F := ({(0 : E × ℝ)} : Set (E × ℝ)))
        (x := (0 : E)) (μ := (0 : ℝ)) rfl
    · rw [Set.mem_singleton_iff, Prod.mk_eq_zero] at hμ
      simp [hμ.2]
  · have hind : indicatorFn ({0} : Set E) x = ⊤ := indicatorFn_of_notMem hx
    rw [hind]
    refine ofEpi_eq_top_iff.2 fun μ hμ => hx ?_
    rw [Set.mem_singleton_iff, Prod.mk_eq_zero] at hμ
    exact hμ.1

/-- `f0 = δ(· | 0)` when `f ≢ +∞`. -/
theorem smulRight_zero (h : (dom f).Nonempty) : smulRight f 0 = indicatorFn ({0} : Set E) := by
  rw [smulRight, zero_smul_epi h, ofEpi_singleton_zero]

/-- `0 • epi f` is never an epigraph, unless `f ≡ +∞`: its vertical section over the origin is the
single point `{0}`, which is not upward closed. This is why `epi_smulRight` is stated for
`a > 0` only — `epi (f0) = {0} ×ˢ Ici 0` is strictly larger than `0 • epi f`. -/
theorem not_isEpiLike_zero_smul_epi (h : (dom f).Nonempty) : ¬IsEpiLike ((0 : ℝ) • epi f) := by
  rw [zero_smul_epi h]
  intro hE
  have h1 : ((0 : E), (1 : ℝ)) ∈ ({(0 : E × ℝ)} : Set (E × ℝ)) :=
    hE.mem_of_le (x := (0 : E)) (μ := 0) (by simp [Prod.mk_eq_zero]) zero_le_one
  rw [Set.mem_singleton_iff, Prod.mk_eq_zero] at h1
  exact absurd h1.2 (by norm_num)

/-- The epigraph of `f0`, for `f ≢ +∞`: the closed half-line over the origin, which strictly
contains `0 • epi f = {(0, 0)}`. -/
theorem epi_smulRight_zero (h : (dom f).Nonempty) :
    epi (smulRight f 0) = ({0} : Set E) ×ˢ Ici (0 : ℝ) := by
  rw [smulRight_zero h, epi_indicatorFn]

/-- `δ(· | 0) ≤ f0`, with no hypothesis on `f`: the two sides agree when `f ≢ +∞` and the right-hand
side is `+∞` otherwise. This is the uniform form of `smulRight_zero`. -/
theorem indicatorFn_le_smulRight_zero (f : E → EReal) :
    indicatorFn ({0} : Set E) ≤ smulRight f 0 := by
  rw [← ofEpi_singleton_zero]
  refine ofEpi_mono ?_
  rintro p ⟨q, -, rfl⟩
  simp

/-- **Right scalar multiplication preserves convexity.** No sign hypothesis on `a` is needed,
although `fa` is only intended for `0 ≤ a < ∞`, the range in which it has its meaning. -/
theorem convexFn_smulRight (a : ℝ) (hf : ConvexFn f) : ConvexFn (smulRight f a) :=
  convexFn_ofEpi (hf.convex_epi.smul a)

/-- `f1 = f`: right scalar multiplication by `1` is the identity. -/
@[simp] theorem smulRight_one (f : E → EReal) : smulRight f 1 = f := by
  rw [smulRight, one_smul, ofEpi_epi]

/-- **`f` is positively homogeneous if and only if `fa = f` for every `a > 0`**;
both directions read `a • epi f = epi f` through `ofEpi_epi` and `epi_smulRight`. -/
theorem posHomogeneous_iff_smulRight_eq : PosHomogeneous f ↔ ∀ a > 0, smulRight f a = f := by
  rw [posHomogeneous_iff_isCone_epi]
  refine ⟨fun h a ha => ?_, fun h a ha => ?_⟩
  · rw [smulRight, h a ha, ofEpi_epi]
  · rw [← epi_smulRight ha, h a ha]

/-- `f0` is positively homogeneous, whatever `f` is: it is either `δ(· | 0)`, the indicator of a
cone, or `+∞`. This is the degenerate case that makes `posHomogeneous_hom` work at `λ = 0`. -/
theorem posHomogeneous_smulRight_zero (f : E → EReal) : PosHomogeneous (smulRight f 0) := by
  by_cases h : (dom f).Nonempty
  · rw [smulRight_zero h]
    exact posHomogeneous_indicatorFn.2 fun a _ => by rw [Set.smul_set_singleton, smul_zero]
  · rw [Set.not_nonempty_iff_eq_empty] at h
    rw [smulRight_of_epi_eq_empty ((epi_eq_empty_iff f).2 h)]
    intro a ha x
    rw [Pi.top_apply, Pi.top_apply, _root_.EReal.coe_mul_top_of_pos ha]

/-- Scaling an epigraph by `0` does not see the difference between a set and the epigraph it
determines: both are empty together, and otherwise both collapse to `{(0, 0)}`. -/
theorem zero_smul_epi_ofEpi (F : Set (E × ℝ)) : (0 : ℝ) • epi (ofEpi F) = (0 : ℝ) • F := by
  rcases F.eq_empty_or_nonempty with rfl | hF
  · rw [ofEpi_empty, epi_top]
  · rw [zero_smul_set (hF.mono (subset_epi_ofEpi F)), zero_smul_set hF]

/-- **Right scalar multiplication is an action**, `f(ab) = (fa)b`. The case `b = 0`
is where the failure of `epi (fa) = a • epi f` at `a = 0` is shown not to propagate. -/
theorem smulRight_smulRight (f : E → EReal) (ha : 0 ≤ a) (hb : 0 ≤ b) :
    smulRight (smulRight f a) b = smulRight f (a * b) := by
  rcases hb.eq_or_lt with rfl | hb'
  · rw [mul_zero]
    simp only [smulRight]
    rw [zero_smul_epi_ofEpi, smul_smul, zero_mul]
  · rcases ha.eq_or_lt with rfl | ha'
    · rw [zero_mul]
      exact posHomogeneous_iff_smulRight_eq.1 (posHomogeneous_smulRight_zero f) b hb'
    · rw [smulRight, epi_smulRight ha', smul_smul, mul_comm b a, smulRight]

/-- Right scalar multiplication as a **monoid action** of `([0, ∞), *)` on `E → EReal`, packaged as
a monoid homomorphism into `Function.End (E → EReal)`; `smulRight_one` and `smulRight_smulRight`
are the two axioms. It is deliberately not a `MulAction ℝ≥0 (E → EReal)` instance, since on the
bare Pi type `•` already means the pointwise action; `MulAction.ofEndHom` turns it into an action
on demand. -/
noncomputable def smulRightHom : ℝ≥0 →* Function.End (E → EReal) where
  toFun a f := smulRight f a
  map_one' := by
    funext f
    change smulRight f ((1 : ℝ≥0) : ℝ) = f
    rw [NNReal.coe_one, smulRight_one]
  map_mul' a b := by
    funext f
    change smulRight f ((a * b : ℝ≥0) : ℝ) = smulRight (smulRight f b) a
    rw [smulRight_smulRight f b.coe_nonneg a.coe_nonneg, NNReal.coe_mul, mul_comm]

/-- The monoid homomorphism `smulRightHom` is right scalar multiplication. -/
@[simp] theorem smulRightHom_apply (a : ℝ≥0) (f : E → EReal) :
    smulRightHom a f = smulRight f a := rfl

end SmulRight

/-! ### The level-1 lift -/

section LevelOneLift

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {f : E → EReal} {a : ℝ} {x : E}
  {p : ℝ × E}

/-- The **level-1 lift** of `f` to `ℝ × E`: `h (λ, x) = f x` if `λ = 1`, and `+∞` otherwise.
`hom f` is the positively homogeneous convex function generated by this lift,
*not* the one generated by `f`. -/
noncomputable def levelOneLift (f : E → EReal) : ℝ × E → EReal :=
  Tdaf.ConvexAnalysis.restrict {p : ℝ × E | p.1 = 1} fun p => f p.2

omit [AddCommGroup E] [Module ℝ E] in
/-- The defining equation of the level-1 lift on the hyperplane `λ = 1`. -/
@[simp] theorem levelOneLift_of_fst_eq_one (h : p.1 = 1) : levelOneLift f p = f p.2 :=
  restrict_of_mem h

omit [AddCommGroup E] [Module ℝ E] in
/-- The level-1 lift is `+∞` off the hyperplane `λ = 1`. -/
@[simp] theorem levelOneLift_of_fst_ne_one (h : p.1 ≠ 1) : levelOneLift f p = ⊤ :=
  restrict_of_notMem h

omit [AddCommGroup E] [Module ℝ E] in
/-- The level-1 lift, evaluated on the hyperplane `λ = 1`. -/
theorem levelOneLift_apply_one (f : E → EReal) (x : E) : levelOneLift f (1, x) = f x :=
  levelOneLift_of_fst_eq_one rfl

omit [AddCommGroup E] [Module ℝ E] in
/-- The level-1 lift, evaluated off the hyperplane `λ = 1`. -/
theorem levelOneLift_apply_of_ne (h : a ≠ 1) (x : E) : levelOneLift f (a, x) = ⊤ :=
  levelOneLift_of_fst_ne_one h

/-- The epigraph of the level-1 lift is `{1} ×ˢ epi f`, read in `(ℝ × E) × ℝ` through the
associativity shuffle. -/
theorem epi_levelOneLift (f : E → EReal) :
    epi (levelOneLift f) = LinearEquiv.prodAssoc ℝ ℝ E ℝ ⁻¹' ({1} ×ˢ epi f) := by
  ext q
  by_cases h : q.1.1 = 1 <;> simp [mem_epi, h, Set.mem_prod]

omit [AddCommGroup E] [Module ℝ E] in
/-- Membership of the epigraph of the level-1 lift, unfolded: `((λ, x), μ)` lies in it exactly when
`λ = 1` and `μ ≥ f x`. -/
theorem mem_epi_levelOneLift {q : (ℝ × E) × ℝ} :
    q ∈ epi (levelOneLift f) ↔ q.1.1 = 1 ∧ f q.1.2 ≤ ((q.2 : ℝ) : EReal) := by
  by_cases h : q.1.1 = 1 <;> simp [mem_epi, h]

omit [AddCommGroup E] [Module ℝ E] in
/-- The vectors that generate the cone of `homCone`: `((1, x), μ)` with `μ ≥ f x`. -/
theorem mk_one_mem_epi_levelOneLift {x : E} {μ : ℝ} :
    (((1, x), μ) : (ℝ × E) × ℝ) ∈ epi (levelOneLift f) ↔ f x ≤ ((μ : ℝ) : EReal) := by
  simp

/-- The level-1 lift of a convex function is convex: its epigraph is a linear preimage of the
convex set `{1} ×ˢ epi f`. -/
theorem convexFn_levelOneLift (hf : ConvexFn f) : ConvexFn (levelOneLift f) := by
  refine ⟨?_⟩
  rw [epi_levelOneLift]
  exact ((convex_singleton (1 : ℝ)).prod hf.convex_epi).linear_preimage
    (LinearEquiv.prodAssoc ℝ ℝ E ℝ).toLinearMap

end LevelOneLift

/-! ### Homogenisation -/

section Hom

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {f : E → EReal} {a : ℝ} {x : E}
  {g : ℝ × E → EReal}

/-- The **positively homogeneous convex function generated by the level-1 lift of `f`**,
assembled slice by slice out of the right scalar multiples `fλ`:
`hom f (λ, x) = (fλ) x` for `λ ≥ 0`, and `+∞` for `λ < 0`. No closure is taken. -/
noncomputable def hom (f : E → EReal) : ℝ × E → EReal :=
  fun p => if 0 ≤ p.1 then smulRight f p.1 p.2 else ⊤

/-- The defining equation at `λ ≥ 0`: the slice of `hom f` at level `λ` is `fλ`. -/
theorem hom_apply_nonneg (ha : 0 ≤ a) (f : E → EReal) (x : E) :
    hom f (a, x) = smulRight f a x := ite_eq_left_of_eq_true _ _ (eq_true ha)

/-- The defining equation at `λ > 0`: `hom f (λ, x) = λ * f (λ⁻¹ • x)`. -/
theorem hom_apply_pos (ha : 0 < a) (f : E → EReal) (x : E) :
    hom f (a, x) = (a : EReal) * f (a⁻¹ • x) := by
  rw [hom_apply_nonneg ha.le, smulRight_apply_pos ha]

/-- The defining equation at `λ = 0`: the slice is `f0`, which is `δ(· | 0)` unless `f ≡ +∞`. -/
theorem hom_apply_zero (f : E → EReal) (x : E) : hom f (0, x) = smulRight f 0 x :=
  hom_apply_nonneg le_rfl f x

/-- `hom f` restricts to `f` on the level `λ = 1`: this is the sense in which `hom f` is a
homogenisation *of `f`*. -/
theorem hom_apply_one (f : E → EReal) (x : E) : hom f (1, x) = f x := by
  rw [hom_apply_pos one_pos, inv_one, one_smul, _root_.EReal.coe_one, one_mul]

/-- `hom f` is `+∞` on the half-space `λ < 0`. -/
theorem hom_apply_neg (ha : a < 0) (f : E → EReal) (x : E) : hom f (a, x) = ⊤ :=
  ite_eq_right_of_eq_false _ _ (eq_false (not_le.2 ha))

/-- If `f ≡ +∞` then `hom f ≡ +∞`. -/
theorem hom_of_epi_eq_empty (h : epi f = ∅) : hom f = ⊤ := by
  funext p
  obtain ⟨a, x⟩ := p
  rcases le_or_gt 0 a with ha | ha
  · rw [hom_apply_nonneg ha, smulRight_of_epi_eq_empty h, Pi.top_apply, Pi.top_apply]
  · rw [hom_apply_neg ha, Pi.top_apply]

/-- **The homogenisation of a function that avoids `-∞` avoids it too.** Only the `ne_bot` half of
`Proper f` is needed: if `dom f` is empty then `hom f ≡ +∞`. -/
theorem hom_ne_bot (hf : ∀ x, f x ≠ ⊥) (q : ℝ × E) : hom f q ≠ ⊥ := by
  obtain ⟨a, x⟩ := q
  rcases lt_trichotomy a 0 with h | h | h
  · rw [hom_apply_neg h]
    exact top_ne_bot
  · subst h
    rw [hom_apply_zero]
    rcases Set.eq_empty_or_nonempty (dom f) with hd | hd
    · rw [smulRight_of_epi_eq_empty ((epi_eq_empty_iff f).2 hd), Pi.top_apply]
      exact top_ne_bot
    · rw [smulRight_zero hd]
      exact indicatorFn_ne_bot _ _
  · rw [hom_apply_pos h]
    exact Tdaf.EReal.coe_mul_ne_bot h.le (hf _)

/-- `hom f (λ, λ x) = λ * f x` for `λ ≥ 0`: the substitution `y = λ x` that turns homogenisation
into left scalar multiplication. At `λ = 0` both sides are `0`, by `f0 = δ(· | 0)` and
`0 · ∞ = 0`. -/
theorem hom_apply_smul (hdom : (dom f).Nonempty) (ha : 0 ≤ a) (z : E) :
    hom f (a, a • z) = (a : EReal) * f z := by
  rcases ha.lt_or_eq with ha' | ha'
  · rw [hom_apply_pos ha', inv_smul_smul₀ ha'.ne']
  · subst ha'
    rw [zero_smul, hom_apply_zero, smulRight_zero hdom]
    simp

/-- `hom f` never exceeds the level-1 lift, and agrees with it at `λ = 1`. -/
theorem hom_le_levelOneLift (f : E → EReal) : hom f ≤ levelOneLift f := by
  rintro ⟨a, x⟩
  by_cases h : a = 1
  · subst h
    rw [hom_apply_one, levelOneLift_apply_one]
  · rw [levelOneLift_apply_of_ne h]
    exact le_top

/-- **`hom f` is positively homogeneous**, with no hypothesis on `f` at all. The `λ = 0` slice is
where the `a = 0` degeneracy of right scalar multiplication is absorbed, by positive homogeneity
of `f0`. -/
theorem posHomogeneous_hom (f : E → EReal) : PosHomogeneous (hom f) := by
  rintro c hc ⟨a, x⟩
  simp only [Prod.smul_mk, smul_eq_mul]
  rcases lt_trichotomy a 0 with ha | rfl | ha
  · rw [hom_apply_neg (mul_neg_of_pos_of_neg hc ha), hom_apply_neg ha,
      _root_.EReal.coe_mul_top_of_pos hc]
  · rw [mul_zero, hom_apply_zero, hom_apply_zero]
    exact posHomogeneous_smulRight_zero f c hc x
  · have hx : (c * a)⁻¹ • (c • x) = a⁻¹ • x := by
      rw [smul_smul, mul_inv, mul_comm c⁻¹ a⁻¹, mul_assoc, inv_mul_cancel₀ hc.ne', mul_one]
    rw [hom_apply_pos (mul_pos hc ha), hom_apply_pos ha, hx, _root_.EReal.coe_mul, mul_assoc]

/-- **The upper-bound half of the maximality property**: every positively homogeneous `g` with
`g 0 ≤ 0` that is majorised by the level-1 lift of `f` is majorised by `hom f`. Convexity of `g` is
not used, and neither is `f ≢ +∞`. The hypothesis `g 0 ≤ 0` is *not* removable: for `f ≡ 0` on
`E = ℝ`, the indicator of `{λ > 0}` is positively homogeneous, convex and below the level-1 lift,
yet takes the value `+∞ > 0 = hom f 0` at the origin. -/
theorem le_hom (hg : PosHomogeneous g) (h0 : g 0 ≤ 0) (hle : g ≤ levelOneLift f) : g ≤ hom f := by
  rintro ⟨a, x⟩
  rcases lt_trichotomy a 0 with ha | rfl | ha
  · rw [hom_apply_neg ha]
    exact le_top
  · rw [hom_apply_zero]
    by_cases hx : x = 0
    · subst hx
      have h00 : ((0 : ℝ), (0 : E)) = (0 : ℝ × E) := rfl
      have hind : indicatorFn ({0} : Set E) (0 : E) = 0 := indicatorFn_of_mem rfl
      rw [h00]
      refine h0.trans ?_
      have h := indicatorFn_le_smulRight_zero f 0
      rwa [hind] at h
    · have htop : smulRight f 0 x = ⊤ := by
        have hind : indicatorFn ({0} : Set E) x = ⊤ := indicatorFn_of_notMem hx
        have h := indicatorFn_le_smulRight_zero f x
        rw [hind] at h
        exact top_le_iff.1 h
      rw [htop]
      exact le_top
  · have hp : a • ((1, a⁻¹ • x) : ℝ × E) = (a, x) := by
      rw [Prod.smul_mk, smul_smul, mul_inv_cancel₀ ha.ne', one_smul, smul_eq_mul, mul_one]
    calc g (a, x) = (a : EReal) * g (1, a⁻¹ • x) := by rw [← hp, hg a ha]
      _ ≤ (a : EReal) * f (a⁻¹ • x) := by
          refine mul_le_mul_of_nonneg_left ?_ (by exact_mod_cast ha.le)
          simpa [levelOneLift_apply_one] using hle (1, a⁻¹ • x)
      _ = hom f (a, x) := (hom_apply_pos ha f x).symm

end Hom

/-! ### The cone generated by the level-1 lift -/

section Cone

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {f : E → EReal} {a : ℝ}
  {q : (ℝ × E) × ℝ}

/-- The convex cone in `(ℝ × E) × ℝ` generated by the epigraph of the level-1 lift of `f`: the
origin together with all positive multiples of `epi (levelOneLift f)`. This is the cone from which
`hom f` is recovered by `ofEpi`. It is *not* itself an epigraph; `epi_hom` describes the ray that
has to be added. -/
noncomputable def homCone (f : E → EReal) : Set ((ℝ × E) × ℝ) :=
  {0} ∪ ⋃ a > (0 : ℝ), a • epi (levelOneLift f)

/-- Membership of the generated cone, unfolded. -/
theorem mem_homCone_iff_exists :
    q ∈ homCone f ↔ q = 0 ∨ ∃ a > (0 : ℝ), q ∈ a • epi (levelOneLift f) := by
  simp [homCone]

/-- Membership of `a • epi (levelOneLift f)` for `a > 0`: the first coordinate pins down `a`. -/
theorem mem_smul_epi_levelOneLift (ha : 0 < a) :
    q ∈ a • epi (levelOneLift f) ↔
      q.1.1 = a ∧ f (a⁻¹ • q.1.2) ≤ ((a⁻¹ * q.2 : ℝ) : EReal) := by
  rw [Set.mem_smul_set_iff_inv_smul_mem₀ ha.ne', mem_epi]
  have hfst : (a⁻¹ • q).1.1 = a⁻¹ * q.1.1 := rfl
  by_cases h1 : q.1.1 = a
  · have hone : (a⁻¹ • q).1.1 = 1 := by rw [hfst, h1, inv_mul_cancel₀ ha.ne']
    rw [levelOneLift_of_fst_eq_one hone]
    simp [h1, Prod.smul_fst, Prod.smul_snd]
  · have hne : (a⁻¹ • q).1.1 ≠ 1 := by
      rw [hfst]
      intro hc
      exact h1 (by field_simp at hc; linarith)
    refine iff_of_false ?_ fun h => h1 h.1
    rw [levelOneLift_of_fst_ne_one hne, top_le_iff]
    exact _root_.EReal.coe_ne_top _

/-- The membership criterion for the generated cone, in closed form. -/
theorem mem_homCone_iff :
    q ∈ homCone f ↔
      q = 0 ∨ (0 < q.1.1 ∧ f (q.1.1⁻¹ • q.1.2) ≤ ((q.1.1⁻¹ * q.2 : ℝ) : EReal)) := by
  rw [mem_homCone_iff_exists]
  refine or_congr_right ⟨fun ⟨a, ha, hq⟩ => ?_, fun ⟨ha, hq⟩ => ?_⟩
  · rw [mem_smul_epi_levelOneLift ha] at hq
    obtain ⟨rfl, hq⟩ := hq
    exact ⟨ha, hq⟩
  · exact ⟨q.1.1, ha, (mem_smul_epi_levelOneLift ha).2 ⟨rfl, hq⟩⟩

/-- The generated cone is a cone: it is invariant under multiplication by positive scalars. -/
theorem smul_homCone (hc : 0 < a) (f : E → EReal) : a • homCone f = homCone f := by
  ext q
  simp only [Set.mem_smul_set_iff_inv_smul_mem₀ hc.ne', mem_homCone_iff_exists]
  constructor
  · rintro (h | ⟨b, hb, hq⟩)
    · left
      have : a • (a⁻¹ • q) = a • (0 : (ℝ × E) × ℝ) := by rw [h]
      rwa [smul_inv_smul₀ hc.ne', smul_zero] at this
    · right
      refine ⟨a * b, mul_pos hc hb, ?_⟩
      have : a • (a⁻¹ • q) ∈ a • (b • epi (levelOneLift f)) := Set.smul_mem_smul_set hq
      rwa [smul_inv_smul₀ hc.ne', smul_smul] at this
  · rintro (rfl | ⟨b, hb, hq⟩)
    · exact Or.inl (smul_zero _)
    · refine Or.inr ⟨a⁻¹ * b, mul_pos (inv_pos.2 hc) hb, ?_⟩
      rw [← smul_smul]
      exact Set.smul_mem_smul_set hq

/-- The generated cone is convex: for a cone it is enough to check closure under addition, and
that is `a • S + b • S = (a + b) • S` for convex `S`. -/
theorem convex_homCone (hf : ConvexFn f) : Convex ℝ (homCone f) := by
  have hS : Convex ℝ (epi (levelOneLift f)) := (convexFn_levelOneLift hf).convex_epi
  rw [convex_iff_add_mem_of_isCone fun c hc => smul_homCone hc f]
  intro p hp q hq
  rw [mem_homCone_iff_exists] at hp hq ⊢
  rcases hp with rfl | ⟨a, ha, hp⟩
  · rw [zero_add]
    exact hq
  rcases hq with rfl | ⟨b, hb, hq⟩
  · rw [add_zero]
    exact Or.inr ⟨a, ha, hp⟩
  refine Or.inr ⟨a + b, by positivity, ?_⟩
  rw [hS.add_smul ha.le hb.le]
  exact Set.add_mem_add hp hq

omit [Module ℝ E] in
/-- A point of `(ℝ × E) × ℝ` whose homogenising coordinate is nonzero is not the origin. -/
theorem mk_ne_zero_of_ne_zero (ha : a ≠ 0) (x : E) (μ : ℝ) :
    (((a, x), μ) : (ℝ × E) × ℝ) ≠ 0 := by simp [Prod.mk_eq_zero, ha]

/-- **`hom f` is `ofEpi` of the convex cone generated by the epigraph of the level-1 lift of
`f`.** The hypothesis `f ≢ +∞` is needed: for
`f ≡ +∞` the cone degenerates to `{0}`, whose associated function is `δ(· | 0)`. -/
theorem hom_eq_ofEpi_homCone (hdom : (dom f).Nonempty) : hom f = ofEpi (homCone f) := by
  funext p
  obtain ⟨a, x⟩ := p
  rcases lt_trichotomy a 0 with ha | rfl | ha
  · rw [hom_apply_neg ha]
    refine (ofEpi_eq_top_iff.2 fun μ hμ => ?_).symm
    rcases mem_homCone_iff.1 hμ with h | ⟨h, -⟩
    · exact mk_ne_zero_of_ne_zero ha.ne x μ h
    · exact absurd h (by exact_mod_cast ha.asymm)
  · rw [hom_apply_zero, smulRight_zero hdom]
    by_cases hx : x = 0
    · subst hx
      have hind : indicatorFn ({0} : Set E) (0 : E) = 0 := indicatorFn_of_mem rfl
      rw [hind]
      refine le_antisymm (le_ofEpi fun μ hμ => ?_) ?_
      · rcases mem_homCone_iff.1 hμ with h | ⟨h, -⟩
        · rw [Prod.mk_eq_zero] at h
          simp [h.2]
        · exact absurd h (by norm_num)
      · simpa using ofEpi_apply_le (F := homCone f) (x := ((0 : ℝ), (0 : E))) (μ := (0 : ℝ))
          (mem_homCone_iff.2 (Or.inl rfl))
    · have hind : indicatorFn ({0} : Set E) x = ⊤ := indicatorFn_of_notMem hx
      rw [hind]
      refine (ofEpi_eq_top_iff.2 fun μ hμ => ?_).symm
      rcases mem_homCone_iff.1 hμ with h | ⟨h, -⟩
      · rw [Prod.mk_eq_zero, Prod.mk_eq_zero] at h
        exact hx h.1.2
      · exact absurd h (by norm_num)
  · refine ((ofEpi_apply_congr (F := homCone f) (G := epi (hom f)) fun μ => ?_).trans
      (congrFun (ofEpi_epi (hom f)) (a, x))).symm
    rw [mem_homCone_iff, mem_epi, hom_apply_pos ha, Tdaf.EReal.coe_mul_le_coe_iff ha]
    refine ⟨fun h => ?_, fun h => Or.inr ⟨ha, by rwa [inv_mul_eq_div]⟩⟩
    rcases h with h | ⟨-, h⟩
    · exact absurd h (mk_ne_zero_of_ne_zero ha.ne' x μ)
    · rwa [inv_mul_eq_div] at h

/-- **`hom f` is convex whenever `f` is.** The degenerate case `f ≡ +∞` is included:
there `hom f ≡ +∞`, whose epigraph is empty. -/
theorem convexFn_hom (hf : ConvexFn f) : ConvexFn (hom f) := by
  by_cases hdom : (dom f).Nonempty
  · rw [hom_eq_ofEpi_homCone hdom]
    exact convexFn_ofEpi (convex_homCone hf)
  · rw [Set.not_nonempty_iff_eq_empty] at hdom
    rw [hom_of_epi_eq_empty ((epi_eq_empty_iff f).2 hdom)]
    exact ⟨by rw [epi_top]; exact convex_empty⟩

/-- **The maximality property of `hom f`.** It is the *greatest* positively homogeneous convex `g`
on `ℝ × E` with `g 0 ≤ 0` and `g ≤ levelOneLift f`. The side condition
`g 0 ≤ 0` cannot be dropped (see `le_hom`), and `f ≢ +∞` is needed only for membership: for
`f ≡ +∞` one has `hom f ≡ +∞`, and the greatest element of the set is `δ(· | 0)` instead. -/
theorem hom_isGreatest (hf : ConvexFn f) (hdom : (dom f).Nonempty) :
    IsGreatest {g : ℝ × E → EReal |
      PosHomogeneous g ∧ ConvexFn g ∧ g 0 ≤ 0 ∧ g ≤ levelOneLift f} (hom f) := by
  refine ⟨⟨posHomogeneous_hom f, convexFn_hom hf, ?_, hom_le_levelOneLift f⟩, ?_⟩
  · have h00 : (0 : ℝ × E) = (0, 0) := rfl
    have hind : indicatorFn ({0} : Set E) (0 : E) = 0 := indicatorFn_of_mem rfl
    rw [h00, hom_apply_zero, smulRight_zero hdom, hind]
  · rintro g ⟨hg, -, h0, hle⟩
    exact le_hom hg h0 hle

/-- **The epigraph of `hom f` against the cone that generates it.** `epi (hom f)` is *not*
`homCone f`: the cone meets the hyperplane `λ = 0` in the single point `0`, whereas an epigraph
must contain the whole ray above it. The two differ exactly by that ray, `{0} ×ˢ Ici 0`. -/
theorem epi_hom (hdom : (dom f).Nonempty) :
    epi (hom f) = homCone f ∪ ({0} : Set (ℝ × E)) ×ˢ Ici (0 : ℝ) := by
  ext q
  obtain ⟨⟨a, x⟩, μ⟩ := q
  rcases lt_trichotomy a 0 with ha | rfl | ha
  · simp only [mem_epi, hom_apply_neg ha, Set.mem_union, mem_homCone_iff, Set.mem_prod,
      Set.mem_singleton_iff, Set.mem_Ici]
    refine iff_of_false (EReal.coe_lt_top μ).not_ge ?_
    rintro ((h | ⟨h, -⟩) | ⟨h, -⟩)
    · exact mk_ne_zero_of_ne_zero ha.ne x μ h
    · exact absurd h (by exact_mod_cast ha.asymm)
    · exact ha.ne (congrArg (fun p : ℝ × E => p.1) h)
  · have hL : (((0 : ℝ), x), μ) ∈ epi (hom f) ↔ x = 0 ∧ 0 ≤ μ := by
      rw [mem_epi, hom_apply_zero, ← mk_mem_epi, epi_smulRight_zero hdom]
      simp
    have hR : (((0 : ℝ), x), μ) ∈ homCone f ∪ ({0} : Set (ℝ × E)) ×ˢ Ici (0 : ℝ) ↔
        x = 0 ∧ 0 ≤ μ := by
      rw [Set.mem_union, mem_homCone_iff]
      constructor
      · rintro ((h | ⟨h, -⟩) | ⟨h, hμ⟩)
        · rw [Prod.mk_eq_zero, Prod.mk_eq_zero] at h
          exact ⟨h.1.2, le_of_eq h.2.symm⟩
        · exact absurd h (lt_irrefl 0)
        · rw [Set.mem_singleton_iff, Prod.mk_eq_zero] at h
          exact ⟨h.2, hμ⟩
      · rintro ⟨rfl, hμ⟩
        exact Or.inr ⟨by simp, hμ⟩
    exact hL.trans hR.symm
  · simp only [Set.mem_union, mem_homCone_iff, Set.mem_prod, Set.mem_singleton_iff, mem_epi,
      hom_apply_pos ha, Tdaf.EReal.coe_mul_le_coe_iff ha]
    constructor
    · intro h
      exact Or.inl (Or.inr ⟨ha, by rwa [inv_mul_eq_div]⟩)
    · rintro ((h | ⟨-, h⟩) | ⟨h, -⟩)
      · exact absurd h (mk_ne_zero_of_ne_zero ha.ne' x μ)
      · rwa [inv_mul_eq_div] at h
      · exact absurd (congrArg (fun p : ℝ × E => p.1) h) ha.ne'

/-- The epigraph of `hom f`, bundled as a Mathlib `ConvexCone`: `posHomogeneous_hom` and
`convexFn_hom` say precisely that `epi (hom f)` is a convex cone in `(ℝ × E) × ℝ`. Unlike
`PosHomogeneous.epiCone`, this needs no `∀ x, f x ≠ ⊥`, because closure under addition comes from
convexity of the cone rather than from subadditivity. -/
noncomputable def homEpiCone (hf : ConvexFn f) : ConvexCone ℝ ((ℝ × E) × ℝ) where
  carrier := epi (hom f)
  smul_mem' c hc q hq := by
    rw [← posHomogeneous_iff_isCone_epi.1 (posHomogeneous_hom f) c hc]
    exact Set.smul_mem_smul_set hq
  add_mem' p hp q hq :=
    (convex_iff_add_mem_of_isCone
      (posHomogeneous_iff_isCone_epi.1 (posHomogeneous_hom f))).1 (convexFn_hom hf).convex_epi
      p hp q hq

/-- The carrier of `homEpiCone` is the epigraph of `hom f`. -/
@[simp] theorem coe_homEpiCone (hf : ConvexFn f) :
    (homEpiCone hf : Set ((ℝ × E) × ℝ)) = epi (hom f) := rfl

/-! ### The associativity shuffle

`epi (hom f)` and `homCone f` live in `(ℝ × E) × ℝ`, while the cone generated by `{1} ×ˢ epi f` —
the form the downstream applications use — lives in `ℝ × (E × ℝ)`. `LinearEquiv.prodAssoc ℝ ℝ E ℝ`
relates them. -/

/-- The generated cone, read in `ℝ × (E × ℝ)`: it is the cone generated by `{1} ×ˢ epi f`, pulled
back along the associativity shuffle. -/
theorem homCone_eq_preimage (f : E → EReal) :
    homCone f = LinearEquiv.prodAssoc ℝ ℝ E ℝ ⁻¹' ({0} ∪ ⋃ a > (0 : ℝ), a • ({1} ×ˢ epi f)) := by
  ext q
  simp only [homCone, Set.mem_preimage, Set.mem_union, Set.mem_singleton_iff, Set.mem_iUnion,
    exists_prop]
  refine or_congr ?_ (exists_congr fun a => and_congr_right fun ha => ?_)
  · refine ⟨fun h => by rw [h, map_zero], fun h => ?_⟩
    have h' := congrArg (LinearEquiv.prodAssoc ℝ ℝ E ℝ).symm h
    rwa [LinearEquiv.symm_apply_apply, map_zero] at h'
  · rw [Set.mem_smul_set_iff_inv_smul_mem₀ ha.ne', Set.mem_smul_set_iff_inv_smul_mem₀ ha.ne',
      epi_levelOneLift, Set.mem_preimage, map_smul]

/-- The generated cone, transported to `ℝ × (E × ℝ)`: it *is* the convex cone generated by
`{1} ×ˢ epi f`. -/
theorem prodAssoc_image_homCone (f : E → EReal) :
    LinearEquiv.prodAssoc ℝ ℝ E ℝ '' homCone f = {0} ∪ ⋃ a > (0 : ℝ), a • ({1} ×ˢ epi f) := by
  rw [homCone_eq_preimage,
    Set.image_preimage_eq _ (LinearEquiv.prodAssoc ℝ ℝ E ℝ).surjective]

end Cone

end Tdaf.ConvexAnalysis
