/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Tdaf.Analysis.Convex.Caratheodory
import Tdaf.Analysis.Convex.Recession.Cone

/-!
# Convex hulls of points and directions

Rockafellar's §17 works throughout with the convex hull of a set `S` that mixes **points** and
**directions** (points at infinity): `conv S` is by definition the smallest convex set that
contains every point of `S` and *recedes* in every direction of `S`, and he immediately records
the formula `conv S = conv S₀ + cone S₁`. This file supplies that object and its API.

A "set of directions" is represented by a set of vectors, one or more per direction: `cone D`, and
therefore `convexHullPD P D`, depends only on the *directions* of the vectors in `D`, so nothing is
lost and no quotient type is needed.

## Main definitions

* `convexHullPD P D` — the convex hull of the points `P` together with the directions of the
  vectors in `D`, defined as `conv P + cone D`.
* `halfLine x y` — the closed half-line from `x` in the direction of `y`. It is `conv S` for the
  one-point, one-direction `S`, and it is the shape of the faces that carry the extreme and
  exposed directions of §18.
* `coneOverPD P D` — the cone over `conv S` in `ℝ × E`, enlarged by its level-zero directions;
  the auxiliary object in the proof of the homogenisation dictionary.
* `affineSpanPD P D` and `finrankPD P D` — the affine hull `aff S = aff (conv S)` of a mixed set
  and its dimension `dim S`.
* `AffineIndepPD P D` — **affine independence of a mixed set**: the homogenisation is linearly
  independent in `ℝ × E`.
* `IsSimplexPD m C` — a **generalized `m`-dimensional simplex**: the convex hull of `m + 1`
  affinely independent points and directions. Its points are the ordinary vertices and its
  directions the vertices at infinity.

## Main results

* `isLeast_convexHullPD` — `convexHullPD P D` **is** Rockafellar's definition: the least convex set
  containing `P` and receding in every direction of `D`. Everything else is a corollary of the
  `IsLeast` pair `convexHullPD_min` / `subset_convexHullPD` + `subset_recessionCone_convexHullPD`.
* `convexHullPD_eq_slice` — the **homogenisation dictionary**: `convexHullPD P D` is the level-one
  slice of the pointed cone in `ℝ × E` generated by `liftPD P D = ({1} × P) ∪ ({0} × D)`. This is
  design decision D7, and it is how Rockafellar proves everything about the object.
* `exists_of_mem_convexHullPD` — **Theorem 17.1**, Carathéodory for points and directions, in the
  vocabulary of this file.
* `IsCompact.isClosed_convexHullPD` — a closedness criterion: `conv P + cone D` is closed when `P`
  is compact and `cone D` is closed.
* `finrank_span_liftPD` — **the homogenisation raises the dimension by exactly one**:
  `dim (span (liftPD P D)) = dim S + 1` for a mixed set with at least one point. This is
  Rockafellar's `dim K = d + 1`, and it is what makes the padding step of Theorem 17.1 possible.
* `convexHullPD_eq_iUnion_simplex` — **Theorem 17.1**, second sentence: `conv S` is the union of
  all the generalized `d`-dimensional simplices with vertices in `S`, where `d = dim (conv S)`.
* `finrankPD_add_one_of_affineIndepPD`, `finrank_vectorSpan_of_isSimplexPD` — a generalized
  `m`-dimensional simplex really has dimension `m`, which is Rockafellar's own *definition* of
  affine independence for a mixed set recovered from the criterion taken as primitive here.

## What is not here

The `Polyhedral/Defs.lean` predicate `FinitelyGenerated C` is, definitionally,
`∃ P D : Finset E, C = convexHullPD ↑P ↑D`; that file is not rephrased in terms of `convexHullPD`
because it sits above this one in the import order (§19 uses the Minkowski–Weyl machinery, which
this file must not drag into §17 and §18). `Polyhedral/Defs.lean` carries its own copy of the
homogenisation dictionary, `slice_hull_union`, stated with its `liftAt`.

**The skew orthants are not separated out.** A generalized `m`-dimensional simplex with a single
ordinary vertex is what Rockafellar calls an `m`-dimensional skew orthant, and he records that
these are exactly the images of the non-negative orthant of `ℝᵐ` under injective affine maps, hence
closed, hence that every generalized simplex is closed. Nothing here consumes that yet; when §18
does, the predicate is `IsSimplexPD m C` with the point family a singleton.

## Design notes

**Why a separate file.** The object is §17 material, but its *defining* property — least among the
convex sets receding in the given directions — is phrased with `recessionCone`, from §8, and its
Carathéodory theorem is `Caratheodory.lean`'s. Putting it in either of those files would force that
file to import the other; a file of its own imports both and is imported by §18.

**The definition is the formula, the characterisation is a theorem.** Rockafellar defines `conv S`
by a minimality property and derives `conv S₀ + cone S₁`. Here the formula is the definition,
because it is what every proof manipulates, and `isLeast_convexHullPD` recovers the minimality
property. In particular `convexHullPD ∅ D = ∅`: a set of directions alone has empty convex hull,
which is Rockafellar's convention and is exactly what `IsLeast` gives (the empty set recedes in
every direction).

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §17.
-/

open Set

open scoped Pointwise

namespace Tdaf.ConvexAnalysis

/-! ### The definition -/

section Defs

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {P P₁ P₂ D D₁ D₂ C : Set E} {x : E}

/-- **The convex hull of a set of points and directions.** `convexHullPD P D` is the smallest
convex set containing the points `P` and receding in the direction of every vector of `D`; it is
`conv P + cone D`, which is Rockafellar's own formula for it (`isLeast_convexHullPD` proves that
the two descriptions agree).

Directions are represented by vectors: only the *directions* of the elements of `D` matter, since
`cone D` is unchanged by rescaling a generator by a positive scalar. -/
def convexHullPD (P D : Set E) : Set E :=
  convexHull ℝ P + (PointedCone.hull ℝ D : Set E)

/-- `conv S` unfolded: the Minkowski sum of the convex hull of the points and the cone hull of
the directions. -/
theorem convexHullPD_def (P D : Set E) :
    convexHullPD P D = convexHull ℝ P + (PointedCone.hull ℝ D : Set E) := rfl

/-- Membership in `conv S`: a point of the convex hull of `P` plus a direction of `cone D`. -/
theorem mem_convexHullPD :
    x ∈ convexHullPD P D ↔
      ∃ u ∈ convexHull ℝ P, ∃ v ∈ (PointedCone.hull ℝ D : Set E), u + v = x :=
  Set.mem_add

/-- The convex hull of the points alone is contained in the hull of the points and directions. -/
theorem convexHull_subset_convexHullPD (P D : Set E) :
    convexHull ℝ P ⊆ convexHullPD P D := fun x hx =>
  ⟨x, hx, 0, zero_mem _, add_zero x⟩

/-- The points of `S` belong to `conv S`. -/
theorem subset_convexHullPD (P D : Set E) : P ⊆ convexHullPD P D :=
  (subset_convexHull ℝ P).trans (convexHull_subset_convexHullPD P D)

/-- With no directions, `conv S` is the ordinary convex hull. -/
@[simp]
theorem convexHullPD_empty_right (P : Set E) : convexHullPD P ∅ = convexHull ℝ P := by
  rw [convexHullPD, PointedCone.hull, Submodule.span_empty, Submodule.bot_coe]
  simp

/-- **A set of directions alone has empty convex hull**, Rockafellar's convention. -/
@[simp]
theorem convexHullPD_empty_left (D : Set E) : convexHullPD (∅ : Set E) D = ∅ := by
  rw [convexHullPD, convexHull_empty, Set.empty_add]

/-- `conv S` is convex. -/
theorem convex_convexHullPD (P D : Set E) : Convex ℝ (convexHullPD P D) :=
  (convex_convexHull ℝ P).add ((PointedCone.hull ℝ D : ConvexCone ℝ E)).convex

/-- **`conv S` recedes in every direction of `S`** — indeed in every direction of `cone D`. -/
theorem coneHull_subset_recessionCone_convexHullPD (P D : Set E) :
    (PointedCone.hull ℝ D : Set E) ⊆ recessionCone (convexHullPD P D) := by
  rintro y hy x ⟨u, hu, v, hv, rfl⟩ a ha
  refine ⟨u, hu, v + a • y, add_mem hv (Submodule.smul_mem _ (⟨a, ha⟩ : {c : ℝ // 0 ≤ c}) hy), ?_⟩
  change u + (v + a • y) = u + v + a • y
  rw [add_assoc]

/-- **`conv S` recedes in every direction of `S`.** -/
theorem subset_recessionCone_convexHullPD (P D : Set E) :
    D ⊆ recessionCone (convexHullPD P D) :=
  PointedCone.subset_hull.trans (coneHull_subset_recessionCone_convexHullPD P D)

/-- **Minimality**: every convex set that contains the points of `S` and recedes in its directions
contains `conv S`. -/
theorem convexHullPD_min (hC : Convex ℝ C) (hP : P ⊆ C) (hD : D ⊆ recessionCone C) :
    convexHullPD P D ⊆ C := by
  have hcone : PointedCone.hull ℝ D ≤ recessionPointedCone C := Submodule.span_le.2 hD
  rintro x ⟨u, hu, v, hv, rfl⟩
  exact add_mem_of_mem_recessionCone (hcone hv) (convexHull_min hP hC hu)

/-- **Rockafellar's definition of `conv S`**: it is the least convex set containing the points of
`S` and receding in all the directions of `S`. -/
theorem isLeast_convexHullPD (P D : Set E) :
    IsLeast {C : Set E | Convex ℝ C ∧ P ⊆ C ∧ D ⊆ recessionCone C} (convexHullPD P D) :=
  ⟨⟨convex_convexHullPD P D, subset_convexHullPD P D, subset_recessionCone_convexHullPD P D⟩,
    fun _ hC => convexHullPD_min hC.1 hC.2.1 hC.2.2⟩

/-- `conv S` is monotone in the points and in the directions. -/
theorem convexHullPD_mono (hP : P₁ ⊆ P₂) (hD : D₁ ⊆ D₂) :
    convexHullPD P₁ D₁ ⊆ convexHullPD P₂ D₂ :=
  convexHullPD_min (convex_convexHullPD P₂ D₂) (hP.trans (subset_convexHullPD P₂ D₂))
    (hD.trans (subset_recessionCone_convexHullPD P₂ D₂))

/-- Monotonicity in the points. -/
theorem convexHullPD_mono_left (hP : P₁ ⊆ P₂) (D : Set E) :
    convexHullPD P₁ D ⊆ convexHullPD P₂ D := convexHullPD_mono hP Subset.rfl

/-- Monotonicity in the directions. -/
theorem convexHullPD_mono_right (P : Set E) (hD : D₁ ⊆ D₂) :
    convexHullPD P D₁ ⊆ convexHullPD P D₂ := convexHullPD_mono Subset.rfl hD

/-- Taking the convex hull of the points first changes nothing. -/
@[simp]
theorem convexHullPD_convexHull (P D : Set E) :
    convexHullPD (convexHull ℝ P) D = convexHullPD P D := by
  rw [convexHullPD, convexHullPD, (convex_convexHull ℝ P).convexHull_eq]

/-- Taking the cone hull of the directions first changes nothing. -/
@[simp]
theorem convexHullPD_coneHull (P D : Set E) :
    convexHullPD P (PointedCone.hull ℝ D : Set E) = convexHullPD P D := by
  rw [convexHullPD, convexHullPD, PointedCone.hull, PointedCone.hull,
    Submodule.span_coe_eq_restrictScalars]
  rfl

/-- `conv S` absorbs its own recession directions: adding `cone D` again changes nothing. -/
theorem convexHullPD_add_coneHull (P D : Set E) :
    convexHullPD P D + (PointedCone.hull ℝ D : Set E) = convexHullPD P D := by
  refine subset_antisymm ?_ (fun x hx => ⟨x, hx, 0, zero_mem _, add_zero x⟩)
  rintro x ⟨u, hu, v, hv, rfl⟩
  exact add_mem_of_mem_recessionCone
    (coneHull_subset_recessionCone_convexHullPD P D hv) hu

/-- A singleton of points with no directions. -/
@[simp]
theorem convexHullPD_singleton_empty (x : E) : convexHullPD ({x} : Set E) ∅ = {x} := by
  rw [convexHullPD_empty_right, convexHull_singleton]

/-- With the origin as its only point, the hull of points and directions is just the cone hull.
This is the identification behind Rockafellar's Corollary 18.5.2. -/
@[simp]
theorem convexHullPD_zero_singleton (D : Set E) :
    convexHullPD ({(0 : E)} : Set E) D = (PointedCone.hull ℝ D : Set E) := by
  ext z
  rw [mem_convexHullPD, convexHull_singleton]
  constructor
  · rintro ⟨u, hu, v, hv, rfl⟩
    rw [Set.mem_singleton_iff] at hu
    subst hu
    simpa using hv
  · intro hz
    exact ⟨0, rfl, z, hz, by rw [zero_add]⟩

/-- The cone generated by a single vector. -/
theorem coe_coneHull_singleton (y : E) :
    (PointedCone.hull ℝ ({y} : Set E) : Set E) = {z | ∃ a : ℝ, 0 ≤ a ∧ z = a • y} := by
  ext z
  rw [SetLike.mem_coe, PointedCone.hull, Submodule.mem_span_singleton]
  exact ⟨fun ⟨a, ha⟩ => ⟨a, a.2, ha.symm⟩, fun ⟨a, ha, hz⟩ => ⟨⟨a, ha⟩, hz.symm⟩⟩

/-- **The closed half-line** issuing from `x` in the direction of `y`. Rockafellar's half-line
faces, and with them the extreme and exposed directions of §18, are all phrased with it. -/
def halfLine (x y : E) : Set E := {z | ∃ a : ℝ, 0 ≤ a ∧ z = x + a • y}

/-- Membership in a half-line, unfolded. -/
theorem mem_halfLine {x y z : E} : z ∈ halfLine x y ↔ ∃ a : ℝ, 0 ≤ a ∧ z = x + a • y := Iff.rfl

/-- A half-line is the convex hull of one point and one direction. -/
theorem convexHullPD_singleton (x y : E) : convexHullPD ({x} : Set E) {y} = halfLine x y := by
  ext z
  rw [convexHullPD, convexHull_singleton, coe_coneHull_singleton]
  constructor
  · rintro ⟨u, rfl, v, ⟨a, ha, rfl⟩, rfl⟩
    exact ⟨a, ha, rfl⟩
  · rintro ⟨a, ha, rfl⟩
    exact ⟨x, rfl, a • y, ⟨a, ha, rfl⟩, rfl⟩

/-- The endpoint belongs to the half-line. -/
theorem left_mem_halfLine (x y : E) : x ∈ halfLine x y := ⟨0, le_rfl, by rw [zero_smul, add_zero]⟩

/-- A half-line is convex. -/
theorem convex_halfLine (x y : E) : Convex ℝ (halfLine x y) := by
  rw [← convexHullPD_singleton]
  exact convex_convexHullPD _ _

/-- A half-line depends only on the *direction* of `y`. -/
theorem halfLine_smul (x y : E) {a : ℝ} (ha : 0 < a) : halfLine x (a • y) = halfLine x y := by
  ext z
  constructor
  · rintro ⟨b, hb, rfl⟩
    exact ⟨b * a, by positivity, by rw [mul_smul]⟩
  · rintro ⟨b, hb, rfl⟩
    refine ⟨b / a, by positivity, ?_⟩
    rw [smul_smul, div_mul_cancel₀ _ ha.ne']

/-- The half-line issuing from `x` in the direction of `y` recedes in the direction of `y`. -/
theorem mem_recessionCone_halfLine (x y : E) : y ∈ recessionCone (halfLine x y) := by
  rw [← convexHullPD_singleton]
  exact subset_recessionCone_convexHullPD _ _ rfl

/-- **The recession cone of a half-line is the ray of its direction.** -/
theorem recessionCone_halfLine (x y : E) :
    recessionCone (halfLine x y) = {z | ∃ a : ℝ, 0 ≤ a ∧ z = a • y} := by
  ext z
  constructor
  · intro hz
    have h := hz x (left_mem_halfLine x y) 1 zero_le_one
    rw [one_smul] at h
    obtain ⟨s, hs, hzs⟩ := h
    exact ⟨s, hs, add_left_cancel hzs⟩
  · rintro ⟨a, ha, rfl⟩
    exact smul_mem_recessionCone ha (mem_recessionCone_halfLine x y)

end Defs

/-! ### The homogenisation dictionary -/

section Homogenize

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {P D : Set E}

/-- The auxiliary cone used to prove the homogenisation dictionary: the pairs `(a, x)` with `a > 0`
and `a⁻¹ • x ∈ conv S`, together with the pairs `(0, x)` with `x ∈ cone D`.

It is the cone over `conv S` (`Polyhedral/Defs.lean`'s `coneOver`) enlarged by its level-zero
directions, and it is the *largest* cone whose level-one slice is still `conv S`. -/
def coneOverPD (P D : Set E) : PointedCone ℝ (ℝ × E) where
  carrier := {p : ℝ × E | (0 < p.1 ∧ p.1⁻¹ • p.2 ∈ convexHullPD P D) ∨
    (p.1 = 0 ∧ p.2 ∈ (PointedCone.hull ℝ D : Set E))}
  add_mem' {p q} hp hq := by
    rcases hp with ⟨hp1, hp2⟩ | ⟨hp1, hp2⟩
    · rcases hq with ⟨hq1, hq2⟩ | ⟨hq1, hq2⟩
      · -- two points at positive levels: a convex combination
        have hsum : 0 < p.1 + q.1 := add_pos hp1 hq1
        have hc1 : p.1 / (p.1 + q.1) * p.1⁻¹ = (p.1 + q.1)⁻¹ := by field_simp
        have hc2 : q.1 / (p.1 + q.1) * q.1⁻¹ = (p.1 + q.1)⁻¹ := by field_simp
        have hmem := convex_convexHullPD P D hp2 hq2 (a := p.1 / (p.1 + q.1))
          (b := q.1 / (p.1 + q.1)) (by positivity) (by positivity) (by field_simp)
        refine Or.inl ⟨by simpa using hsum, ?_⟩
        have hval : (p + q).1⁻¹ • (p + q).2
            = (p.1 / (p.1 + q.1)) • (p.1⁻¹ • p.2) + (q.1 / (p.1 + q.1)) • (q.1⁻¹ • q.2) := by
          rw [smul_smul, smul_smul, hc1, hc2, ← smul_add]
          rfl
        rw [hval]
        exact hmem
      · -- a point at a positive level plus a direction
        refine Or.inl ⟨by simpa [hq1] using hp1, ?_⟩
        have hfst : (p + q).1 = p.1 := by simp [hq1]
        rw [hfst, show (p + q).2 = p.2 + q.2 from rfl, smul_add]
        refine add_mem_of_mem_recessionCone
          (coneHull_subset_recessionCone_convexHullPD P D ?_) hp2
        exact Submodule.smul_mem _ (⟨p.1⁻¹, (inv_pos.2 hp1).le⟩ : {c : ℝ // 0 ≤ c}) hq2
    · rcases hq with ⟨hq1, hq2⟩ | ⟨hq1, hq2⟩
      · refine Or.inl ⟨by simpa [hp1] using hq1, ?_⟩
        have hfst : (p + q).1 = q.1 := by simp [hp1]
        rw [hfst, show (p + q).2 = p.2 + q.2 from rfl, smul_add, add_comm]
        refine add_mem_of_mem_recessionCone
          (coneHull_subset_recessionCone_convexHullPD P D ?_) hq2
        exact Submodule.smul_mem _ (⟨q.1⁻¹, (inv_pos.2 hq1).le⟩ : {c : ℝ // 0 ≤ c}) hp2
      · exact Or.inr ⟨by simp [hp1, hq1], add_mem hp2 hq2⟩
  zero_mem' := Or.inr ⟨rfl, zero_mem _⟩
  smul_mem' a {p} hp := by
    rcases eq_or_lt_of_le a.2 with ha | ha
    · refine Or.inr ⟨?_, ?_⟩
      · change (a : ℝ) * p.1 = 0
        rw [← ha, zero_mul]
      · change (a : ℝ) • p.2 ∈ (PointedCone.hull ℝ D : Set E)
        rw [← ha, zero_smul]
        exact zero_mem _
    · rcases hp with ⟨hp1, hp2⟩ | ⟨hp1, hp2⟩
      · refine Or.inl ⟨mul_pos ha hp1, ?_⟩
        have hval : ((a : ℝ) * p.1)⁻¹ • ((a : ℝ) • p.2) = p.1⁻¹ • p.2 := by
          rw [smul_smul, mul_inv, mul_comm ((a : ℝ))⁻¹ p.1⁻¹, mul_assoc,
            inv_mul_cancel₀ ha.ne', mul_one]
        exact hval ▸ hp2
      · exact Or.inr ⟨by change (a : ℝ) * p.1 = 0; rw [hp1, mul_zero],
          Submodule.smul_mem _ a hp2⟩

/-- Membership in `coneOverPD`, unfolded. -/
@[simp]
theorem mem_coneOverPD {p : ℝ × E} :
    p ∈ coneOverPD P D ↔ (0 < p.1 ∧ p.1⁻¹ • p.2 ∈ convexHullPD P D) ∨
      (p.1 = 0 ∧ p.2 ∈ (PointedCone.hull ℝ D : Set E)) := Iff.rfl

/-- The easy half of the homogenisation dictionary: a point of `conv S`, lifted to height `1`,
lies in the pointed cone generated by `liftPD P D`. -/
theorem lift_mem_coneHull_liftPD {x : E} (hx : x ∈ convexHullPD P D) :
    ((1 : ℝ), x) ∈ PointedCone.hull ℝ (liftPD P D) := by
  obtain ⟨u, hu, v, hv, rfl⟩ := hx
  have hpt : convexHull ℝ P ⊆ {w : E | ((1 : ℝ), w) ∈ PointedCone.hull ℝ (liftPD P D)} := by
    refine convexHull_min (fun y hy => PointedCone.subset_hull (mem_liftPD_one hy)) ?_
    intro y hy z hz a b ha hb hab
    have hsplit : ((1 : ℝ), a • y + b • z) = a • ((1 : ℝ), y) + b • ((1 : ℝ), z) := by
      refine Prod.ext ?_ rfl
      change (1 : ℝ) = a * 1 + b * 1
      rw [mul_one, mul_one, hab]
    change ((1 : ℝ), a • y + b • z) ∈ PointedCone.hull ℝ (liftPD P D)
    rw [hsplit]
    exact add_mem (Submodule.smul_mem _ (⟨a, ha⟩ : {c : ℝ // 0 ≤ c}) hy)
      (Submodule.smul_mem _ (⟨b, hb⟩ : {c : ℝ // 0 ≤ c}) hz)
  have hdir : ((0 : ℝ), v) ∈ PointedCone.hull ℝ (liftPD P D) := by
    obtain ⟨c, hcD, hc0, hcv⟩ := PointedCone.mem_hull_set.1 hv
    have hrepr : ((0 : ℝ), v) = ∑ y ∈ c.support, c y • (((0 : ℝ), y) : ℝ × E) := by
      refine Prod.ext ?_ ?_
      · simp [Prod.fst_sum]
      · simpa [Prod.snd_sum, Finsupp.sum] using hcv.symm
    rw [hrepr]
    refine Submodule.sum_mem _ fun y hy => ?_
    exact Submodule.smul_mem _ (⟨c y, hc0 y⟩ : {c : ℝ // 0 ≤ c})
      (PointedCone.subset_hull (mem_liftPD_zero (P := P) (hcD hy)))
  have hsplit : ((1 : ℝ), u + v) = ((1 : ℝ), u) + ((0 : ℝ), v) := by
    refine Prod.ext ?_ rfl
    change (1 : ℝ) = 1 + 0
    rw [add_zero]
  rw [hsplit]
  exact add_mem (hpt hu) hdir

/-- **The homogenisation dictionary** (design decision D7). `conv S` is the level-one slice of the
convex cone in `ℝ × E` generated by `liftPD P D`, the copy of `P` at height `1` together with the
copy of `D` at height `0`. This is Rockafellar's `S'`, and the identification is how §17 and §18
prove everything about `conv S`. -/
theorem convexHullPD_eq_slice (P D : Set E) :
    {x : E | ((1 : ℝ), x) ∈ (PointedCone.hull ℝ (liftPD P D) : Set (ℝ × E))}
      = convexHullPD P D := by
  refine subset_antisymm (fun x hx => ?_) (fun x hx => lift_mem_coneHull_liftPD hx)
  have hle : PointedCone.hull ℝ (liftPD P D) ≤ coneOverPD P D := by
    refine Submodule.span_le.2 ?_
    rintro q (⟨y, hy, rfl⟩ | ⟨y, hy, rfl⟩)
    · refine Or.inl ⟨by norm_num, ?_⟩
      change ((1 : ℝ))⁻¹ • y ∈ convexHullPD P D
      rw [inv_one, one_smul]
      exact subset_convexHullPD P D hy
    · exact Or.inr ⟨rfl, PointedCone.subset_hull hy⟩
  rcases hle hx with ⟨-, h⟩ | ⟨h, -⟩
  · change ((1 : ℝ))⁻¹ • x ∈ convexHullPD P D at h
    rwa [inv_one, one_smul] at h
  · exact absurd h one_ne_zero

/-- The level-one slice form of membership in `conv S`. -/
theorem mem_convexHullPD_iff_lift_mem {x : E} :
    x ∈ convexHullPD P D ↔ ((1 : ℝ), x) ∈ (PointedCone.hull ℝ (liftPD P D) : Set (ℝ × E)) := by
  rw [← convexHullPD_eq_slice P D]
  exact Iff.rfl

end Homogenize

/-! ### Half-lines in a normed space -/

section Normed

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- **A half-line in a nonzero direction is unbounded.** -/
theorem not_isBounded_halfLine {x y : E} (hy : y ≠ 0) :
    ¬ Bornology.IsBounded (halfLine x y) := by
  intro hb
  obtain ⟨r, hr⟩ := hb.subset_closedBall x
  have hyn : 0 < ‖y‖ := norm_pos_iff.2 hy
  have hyne : ‖y‖ ≠ 0 := ne_of_gt hyn
  have hr0 : 0 ≤ r := by
    have h := Metric.mem_closedBall.1 (hr (left_mem_halfLine x y))
    simpa using h
  have hcnn : 0 ≤ (r + 1) / ‖y‖ := div_nonneg (by linarith) hyn.le
  have h := Metric.mem_closedBall.1 (hr (show x + ((r + 1) / ‖y‖) • y ∈ halfLine x y from
    ⟨(r + 1) / ‖y‖, hcnn, rfl⟩))
  rw [dist_eq_norm, show x + ((r + 1) / ‖y‖) • y - x = ((r + 1) / ‖y‖) • y by abel,
    norm_smul, Real.norm_eq_abs, abs_of_nonneg hcnn, div_mul_cancel₀ _ hyne] at h
  linarith

end Normed

/-! ### Carathéodory's theorem, and closedness -/

section FiniteDimensional

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  {P D : Set E} {x : E}

/-- **Rockafellar, Theorem 17.1** for points and directions, in the vocabulary of this file: every
point of `conv S` is a convex combination of at most `n + 1` points and directions of `S`, all with
strictly positive coefficients. -/
theorem exists_of_mem_convexHullPD (hx : x ∈ convexHullPD P D) :
    ∃ (p d : Finset E) (a b : E → ℝ), ↑p ⊆ P ∧ ↑d ⊆ D ∧
      (∀ y ∈ p, 0 < a y) ∧ (∀ y ∈ d, 0 < b y) ∧ ∑ y ∈ p, a y = 1 ∧
      p.card + d.card ≤ Module.finrank ℝ E + 1 ∧
      (∑ y ∈ p, a y • y) + ∑ y ∈ d, b y • y = x :=
  exists_of_mem_convexHull_add_coneHull hx

omit [FiniteDimensional ℝ E] in
/-- The converse of `exists_of_mem_convexHullPD`: any convex combination of points and directions
of `S` lies in `conv S`. -/
theorem sum_mem_convexHullPD {p d : Finset E} {a b : E → ℝ} (hp : ↑p ⊆ P) (hd : ↑d ⊆ D)
    (ha : ∀ y ∈ p, 0 ≤ a y) (hb : ∀ y ∈ d, 0 ≤ b y) (hsum : ∑ y ∈ p, a y = 1) :
    (∑ y ∈ p, a y • y) + ∑ y ∈ d, b y • y ∈ convexHullPD P D := by
  refine ⟨∑ y ∈ p, a y • y, ?_, ∑ y ∈ d, b y • y, ?_, rfl⟩
  · exact (convex_convexHull ℝ P).sum_mem ha hsum fun y hy => subset_convexHull ℝ P (hp hy)
  · exact Submodule.sum_mem _ fun y hy =>
      Submodule.smul_mem _ (⟨b y, hb y hy⟩ : {c : ℝ // 0 ≤ c}) (PointedCone.subset_hull (hd hy))

/-- **A closedness criterion.** `conv S` is closed as soon as the set of points is compact and the
cone generated by the directions is closed: the convex hull of a compact set is compact
(**Theorem 17.2**, second sentence), and a compact set plus a closed set is closed. -/
theorem IsCompact.isClosed_convexHullPD (hP : IsCompact P)
    (hD : IsClosed (PointedCone.hull ℝ D : Set E)) : IsClosed (convexHullPD P D) :=
  hD.add_left_of_isCompact (IsCompact.isCompact_convexHull hP)

/-- `conv S` is compact when there are no directions and the points are compact. -/
theorem IsCompact.isCompact_convexHullPD (hP : IsCompact P) :
    IsCompact (convexHullPD P (∅ : Set E)) := by
  rw [convexHullPD_empty_right]
  exact IsCompact.isCompact_convexHull hP

end FiniteDimensional

/-! ### Vertices: affine independence, dimension, generalized simplices -/

section Vertices

variable {E : Type*} [AddCommGroup E] [Module ℝ E] {P D : Set E}

/-- The pointed cone generated by a set lies inside its linear span. -/
theorem coe_coneHull_subset_span (S : Set E) :
    (PointedCone.hull ℝ S : Set E) ⊆ (Submodule.span ℝ S : Set E) := by
  intro x hx
  induction hx using Submodule.span_induction with
  | mem y hy => exact Submodule.subset_span hy
  | zero => exact zero_mem _
  | add a b _ _ ha hb => exact add_mem ha hb
  | smul c a _ ha => exact Submodule.smul_mem _ (c : ℝ) ha

/-- **The affine hull of a set of points and directions**: `aff S = aff (conv S)`, the smallest
affine set containing the points of `S` that recedes in all the directions of `S`. -/
def affineSpanPD (P D : Set E) : AffineSubspace ℝ E := affineSpan ℝ (convexHullPD P D)

/-- **The dimension of a set of points and directions**, `dim S = dim (aff S)`, as the dimension
of the direction space of `aff S`. Rockafellar gives the empty set dimension `-1`; a natural number
cannot, so `finrankPD ∅ D = 0` and every statement about it carries a non-emptiness hypothesis. -/
noncomputable def finrankPD (P D : Set E) : ℕ :=
  Module.finrank ℝ (vectorSpan ℝ (convexHullPD P D))

/-- `dim S` unfolded. -/
theorem finrankPD_def (P D : Set E) :
    finrankPD P D = Module.finrank ℝ (vectorSpan ℝ (convexHullPD P D)) := rfl

/-- `dim S` is the dimension of the direction space of `aff S`. -/
theorem finrankPD_eq_finrank_direction (P D : Set E) :
    finrankPD P D = Module.finrank ℝ (affineSpanPD P D).direction := by
  rw [finrankPD_def, affineSpanPD, direction_affineSpan]

/-- **A set of points and directions is affinely independent** when its homogenisation — the points
lifted to height `1` and the directions to height `0` — is a linearly independent subset of
`ℝ × E`.

Rockafellar defines the notion by `dim S = m - 1`, where `m` is the total number of points and
directions of `S`, and derives this criterion from it; here the criterion is the definition,
because it is what every proof uses. With no directions it is the affine independence of the points
(`affineIndependent_of_linearIndepOn_one`). -/
def AffineIndepPD (P D : Set E) : Prop := LinearIndepOn ℝ id (liftPD P D)

/-- Affine independence of a mixed set, unfolded. -/
theorem affineIndepPD_iff : AffineIndepPD P D ↔ LinearIndepOn ℝ id (liftPD P D) := Iff.rfl

/-- **A generalized `m`-dimensional simplex**: the convex hull of `m + 1` affinely independent
points and directions. The points are its *ordinary vertices* and the directions its *vertices at
infinity*; the one-dimensional generalized simplices are the line segments and the closed
half-lines, and a generalized simplex with a single ordinary vertex is a skew orthant. -/
def IsSimplexPD (m : ℕ) (C : Set E) : Prop :=
  ∃ p d : Finset E, AffineIndepPD (↑p : Set E) (↑d : Set E) ∧ p.card + d.card = m + 1 ∧
    C = convexHullPD (↑p : Set E) (↑d : Set E)

/-- The convex hull of `m + 1` affinely independent points and directions is a generalized
`m`-dimensional simplex. -/
theorem isSimplexPD_convexHullPD {p d : Finset E} {m : ℕ}
    (hai : AffineIndepPD (↑p : Set E) (↑d : Set E)) (hcard : p.card + d.card = m + 1) :
    IsSimplexPD m (convexHullPD (↑p : Set E) (↑d : Set E)) :=
  ⟨p, d, hai, hcard, rfl⟩

omit [AddCommGroup E] [Module ℝ E] in
/-- The homogenisation of a finite set of points and a finite set of directions has exactly as many
elements as there are points and directions: the heights `1` and `0` keep the two families apart,
and each lift is injective. -/
theorem ncard_liftPD_coe (p d : Finset E) :
    (liftPD (↑p : Set E) (↑d : Set E)).ncard = p.card + d.card := by
  have hf : Function.Injective (fun y : E => ((1 : ℝ), y)) := fun _ _ h => congrArg Prod.snd h
  have hg : Function.Injective (fun y : E => ((0 : ℝ), y)) := fun _ _ h => congrArg Prod.snd h
  have hdisj : Disjoint ((fun y : E => ((1 : ℝ), y)) '' (↑p : Set E))
      ((fun y : E => ((0 : ℝ), y)) '' (↑d : Set E)) := by
    rw [Set.disjoint_left]
    rintro q ⟨y, -, hyq⟩ ⟨z, -, hzq⟩
    have hyq' : ((1 : ℝ), y) = q := hyq
    have hzq' : ((0 : ℝ), z) = q := hzq
    have h1 : q.1 = 1 := by rw [← hyq']
    have h0 : q.1 = 0 := by rw [← hzq']
    rw [h1] at h0
    exact absurd h0 one_ne_zero
  rw [liftPD, Set.ncard_union_eq hdisj (p.finite_toSet.image _) (d.finite_toSet.image _),
    Set.ncard_image_of_injective _ hf, Set.ncard_image_of_injective _ hg,
    Set.ncard_coe_finset, Set.ncard_coe_finset]

end Vertices

/-! ### Theorem 17.1, second sentence: the union of the simplices -/

section Simplices

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  {P D : Set E}

/-- **The homogenisation raises the dimension by exactly one.** When `S` has at least one point,
the span of the homogenisation `liftPD P D` in `ℝ × E` has dimension `dim S + 1`.

This is the identification `dim K = d + 1` behind Rockafellar's proof of Theorem 17.1: fixing a
point `x₀` of `S`, the span is the direct sum of the line through `(1, x₀)` and the copy of the
direction space of `aff S` at height `0`. -/
theorem finrank_span_liftPD (hP : P.Nonempty) :
    Module.finrank ℝ (Submodule.span ℝ (liftPD P D)) = finrankPD P D + 1 := by
  obtain ⟨x₀, hx₀⟩ := hP
  have hx₀C : x₀ ∈ convexHullPD P D := subset_convexHullPD P D hx₀
  have hinrInj : Function.Injective (LinearMap.inr ℝ ℝ E) := fun a b h => congrArg Prod.snd h
  have hone : ((1 : ℝ), x₀) ∈ Submodule.span ℝ (liftPD P D) :=
    Submodule.subset_span (mem_liftPD_one hx₀)
  have hliftC : ∀ y ∈ convexHullPD P D, ((1 : ℝ), y) ∈ Submodule.span ℝ (liftPD P D) :=
    fun y hy => coe_coneHull_subset_span (liftPD P D) (lift_mem_coneHull_liftPD hy)
  -- the direction space of `aff S`, lifted to height `0`, lies in the span
  have hVW : vectorSpan ℝ (convexHullPD P D)
      ≤ (Submodule.span ℝ (liftPD P D)).comap (LinearMap.inr ℝ ℝ E) := by
    rw [vectorSpan_eq_span_vsub_set_right ℝ hx₀C]
    refine Submodule.span_le.2 ?_
    rintro v ⟨y, hy, hvy⟩
    have hv : v = y - x₀ := hvy.symm
    have hsplit : ((0 : ℝ), y - x₀) = ((1 : ℝ), y) - ((1 : ℝ), x₀) := by
      refine Prod.ext ?_ rfl
      change (0 : ℝ) = 1 - 1
      rw [sub_self]
    have hmem : LinearMap.inr ℝ ℝ E v ∈ Submodule.span ℝ (liftPD P D) := by
      rw [hv]
      change ((0 : ℝ), y - x₀) ∈ Submodule.span ℝ (liftPD P D)
      rw [hsplit]
      exact sub_mem (hliftC y hy) hone
    exact hmem
  -- and the span is exactly that sum
  have hkey : Submodule.span ℝ (liftPD P D)
      = Submodule.span ℝ {((1 : ℝ), x₀)}
        ⊔ (vectorSpan ℝ (convexHullPD P D)).map (LinearMap.inr ℝ ℝ E) := by
    refine le_antisymm (Submodule.span_le.2 ?_) (sup_le ?_ ?_)
    · rintro q (⟨y, hy, hqy⟩ | ⟨y, hy, hqy⟩)
      · have hq : q = ((1 : ℝ), y) := hqy.symm
        have hyV : y - x₀ ∈ vectorSpan ℝ (convexHullPD P D) :=
          vsub_mem_vectorSpan ℝ (subset_convexHullPD P D hy) hx₀C
        have hsplit : ((1 : ℝ), y) = ((1 : ℝ), x₀) + LinearMap.inr ℝ ℝ E (y - x₀) := by
          refine Prod.ext ?_ ?_
          · change (1 : ℝ) = 1 + 0
            rw [add_zero]
          · change y = x₀ + (y - x₀)
            rw [add_sub_cancel]
        rw [hq, hsplit]
        exact Submodule.add_mem _
          (Submodule.mem_sup_left (Submodule.mem_span_singleton_self _))
          (Submodule.mem_sup_right (Submodule.mem_map_of_mem hyV))
      · have hq : q = ((0 : ℝ), y) := hqy.symm
        have hmem : x₀ + (1 : ℝ) • y ∈ convexHullPD P D :=
          subset_recessionCone_convexHullPD P D hy x₀ hx₀C 1 zero_le_one
        rw [one_smul] at hmem
        have hyV : y ∈ vectorSpan ℝ (convexHullPD P D) := by
          have hy' : x₀ + y - x₀ ∈ vectorSpan ℝ (convexHullPD P D) :=
            vsub_mem_vectorSpan ℝ hmem hx₀C
          simpa using hy'
        rw [hq]
        exact Submodule.mem_sup_right (Submodule.mem_map_of_mem hyV)
    · rw [Submodule.span_le]
      rintro q hq
      rw [Set.mem_singleton_iff] at hq
      rw [hq]
      exact hone
    · rw [Submodule.map_le_iff_le_comap]
      exact hVW
  -- the two summands meet only at the origin
  have hdisj : Submodule.span ℝ {((1 : ℝ), x₀)}
      ⊓ (vectorSpan ℝ (convexHullPD P D)).map (LinearMap.inr ℝ ℝ E) = ⊥ := by
    refine le_antisymm (fun q hq => ?_) bot_le
    obtain ⟨a, ha⟩ := Submodule.mem_span_singleton.1 hq.1
    obtain ⟨v, -, hvq⟩ := hq.2
    have h1 : q.1 = a := by rw [← ha]; simp
    have h2 : q.1 = 0 := by rw [← hvq]; rfl
    have ha0 : a = 0 := by rw [← h1]; exact h2
    rw [Submodule.mem_bot, ← ha, ha0, zero_smul]
  have hne0 : ((1 : ℝ), x₀) ≠ 0 := fun h => one_ne_zero (congrArg Prod.fst h)
  have hA : Module.finrank ℝ (Submodule.span ℝ {((1 : ℝ), x₀)}) = 1 :=
    finrank_span_singleton hne0
  have hB : Module.finrank ℝ ((vectorSpan ℝ (convexHullPD P D)).map (LinearMap.inr ℝ ℝ E))
      = finrankPD P D := by
    rw [finrankPD_def]
    exact ((Submodule.equivMapOfInjective (LinearMap.inr ℝ ℝ E) hinrInj
      (vectorSpan ℝ (convexHullPD P D))).finrank_eq).symm
  have hsup := Submodule.finrank_sup_add_finrank_inf_eq (Submodule.span ℝ {((1 : ℝ), x₀)})
    ((vectorSpan ℝ (convexHullPD P D)).map (LinearMap.inr ℝ ℝ E))
  rw [← hkey, hdisj, finrank_bot, hA, hB, add_zero] at hsup
  omega

/-- **A generalized `m`-dimensional simplex really has dimension `m`.** Rockafellar *defines* affine
independence of a mixed set by `dim S = m - 1`, with `m` the number of points and directions, and
derives the linear-independence criterion; this recovers his definition from the criterion, which
`AffineIndepPD` takes as primitive. -/
theorem finrankPD_add_one_of_affineIndepPD {p d : Finset E} (hp : (↑p : Set E).Nonempty)
    (hai : AffineIndepPD (↑p : Set E) (↑d : Set E)) :
    finrankPD (↑p : Set E) (↑d : Set E) + 1 = p.card + d.card := by
  have hfinite : Finite (↥(liftPD (↑p : Set E) (↑d : Set E))) :=
    LinearIndependent.finite_of_isNoetherian hai
  let : Fintype (↥(liftPD (↑p : Set E) (↑d : Set E))) := Fintype.ofFinite _
  have h1 := finrank_span_set_eq_card (R := ℝ) hai
  rw [finrank_span_liftPD hp] at h1
  rw [h1, ← Set.ncard_eq_toFinset_card', ncard_liftPD_coe]

/-- **A generalized `m`-dimensional simplex has dimension `m`**, in the form its name promises. -/
theorem finrank_vectorSpan_of_isSimplexPD {m : ℕ} {C : Set E} (hC : IsSimplexPD m C)
    (hne : C.Nonempty) : Module.finrank ℝ (vectorSpan ℝ C) = m := by
  obtain ⟨p, d, hai, hcard, rfl⟩ := hC
  have hp : (↑p : Set E).Nonempty := by
    rcases Set.eq_empty_or_nonempty (↑p : Set E) with h | h
    · rw [h, convexHullPD_empty_left] at hne
      exact absurd hne (by simp)
    · exact h
  have h := finrankPD_add_one_of_affineIndepPD hp hai
  rw [hcard] at h
  rw [← finrankPD_def]
  omega

/-- **Rockafellar, Theorem 17.1**, second sentence: `conv S` is the union of all the generalized
`d`-dimensional simplices whose vertices belong to `S`, where `d = dim (conv S)`.

Carathéodory produces an independent family of at most `d + 1` generators; the padding to exactly
`d + 1` extends that family to a basis of the span of the homogenisation `liftPD P D`, drawing the
extra vectors from `liftPD P D` itself — possible because that span has dimension exactly `d + 1`
(`finrank_span_liftPD`). Each member of the union is a generalized `d`-dimensional simplex by
`isSimplexPD_convexHullPD`. -/
theorem convexHullPD_eq_iUnion_simplex (hP : P.Nonempty) :
    convexHullPD P D =
      ⋃ (p : Finset E) (d : Finset E) (_ : (↑p : Set E) ⊆ P) (_ : (↑d : Set E) ⊆ D)
        (_ : AffineIndepPD (↑p : Set E) (↑d : Set E))
        (_ : p.card + d.card = finrankPD P D + 1),
        convexHullPD (↑p : Set E) (↑d : Set E) := by
  refine subset_antisymm (fun x hx => ?_) ?_
  · obtain ⟨t, w, hts, hw, hli, hsum⟩ := exists_linearIndepOn_subset_liftPD hx
    obtain ⟨b, hbsub, htb, hspanb, hbli⟩ := exists_linearIndepOn_id_extension hli hts
    have hbfinite : Finite (↥b) := LinearIndependent.finite_of_isNoetherian hbli
    have hbfin : b.Finite := Set.toFinite b
    let : Fintype (↥b) := hbfin.fintype
    have hBcoe : (↑b.toFinset : Set (ℝ × E)) = b := Set.coe_toFinset b
    obtain ⟨p, d, hp, hd, hcard, hlift⟩ :=
      exists_finset_liftPD_eq (P := P) (D := D) (t := b.toFinset) (by rw [hBcoe]; exact hbsub)
    rw [hBcoe] at hlift
    -- the padded family has exactly `d + 1` members
    have hspaneq : Submodule.span ℝ b = Submodule.span ℝ (liftPD P D) :=
      le_antisymm (Submodule.span_mono hbsub) (Submodule.span_le.2 hspanb)
    have hcount : b.toFinset.card = finrankPD P D + 1 := by
      have h1 := finrank_span_set_eq_card (R := ℝ) hbli
      rw [hspaneq, finrank_span_liftPD (D := D) hP] at h1
      omega
    -- the point still lies in the hull of the padded family
    have hmem : x ∈ convexHullPD (↑p : Set E) (↑d : Set E) := by
      refine mem_convexHullPD_iff_lift_mem.2 ?_
      rw [← hsum]
      refine Submodule.sum_mem _ fun q hq => ?_
      have hqmem : q ∈ liftPD (↑p : Set E) (↑d : Set E) := by
        rw [hlift]
        exact htb (Finset.mem_coe.2 hq)
      exact Submodule.smul_mem _ (⟨w q, (hw q hq).le⟩ : {c : ℝ // 0 ≤ c})
        (PointedCone.subset_hull hqmem)
    have hai : AffineIndepPD (↑p : Set E) (↑d : Set E) := by
      change LinearIndepOn ℝ id (liftPD (↑p : Set E) (↑d : Set E))
      rw [hlift]
      exact hbli
    simp only [Set.mem_iUnion, exists_prop]
    exact ⟨p, d, hp, hd, hai, by rw [hcard, hcount], hmem⟩
  · refine Set.iUnion_subset fun p => Set.iUnion_subset fun d => Set.iUnion_subset fun hp =>
      Set.iUnion_subset fun hd => Set.iUnion_subset fun _ => Set.iUnion_subset fun _ => ?_
    exact convexHullPD_mono hp hd

end Simplices

end Tdaf.ConvexAnalysis
