/-
Copyright (c) 2026 TDAF contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TDAF contributors
-/
import Tdaf.Analysis.Convex.Duality.Gauge
import Tdaf.Analysis.Convex.Duality.Polar
import Tdaf.Analysis.Convex.Helly
import Tdaf.Analysis.Convex.Polyhedral.Cone

/-!
# Finite systems of linear inequalities

Rockafellar's §22, restricted to what the plan assigns to the backbone: the theorems of the
alternative for a finite system of weak linear inequalities (**Theorem 22.1**, Gale's theorem) and
for a mixed system of strict and weak ones (**Theorem 22.2**, Motzkin's transposition theorem), the
characterisation of the *consequences* of a consistent system (**Theorem 22.3**), and Farkas'
Lemma (**Corollary 22.3.1**).

## Main results

* `farkas`, `farkas_of_pairing` — **Corollary 22.3.1**, Farkas' Lemma.
* `alternative_linear_system` — **Theorem 22.1**.
* `alternative_linear_system_strict` — **Theorem 22.2**.
* `le_consequence_iff` — **Theorem 22.3**.
* `mem_pointedCone_hull_range_iff`, `isClosed_coe_pointedCone_hull_range` — the two facts about
  the cone generated by a finite family that Farkas' Lemma runs on.
* `eq_zero_of_forall_pairing_eq_zero`, `eq_zero_and_nonpos_of_forall_nonneg` — a compatible pairing
  separates its second variable, so an affine function of the pairing that is non-negative
  everywhere is a non-negative constant.

## What is not here

**Nothing beyond Theorem 22.3.** The plan assigns the rest of §22 — the elementary vectors of
Lemma 22.4 and Corollary 22.4.1, Theorem 22.6 and Tucker's complementarity Theorem 22.7 — to the
surface, and Rockafellar himself notes that §22 is used nowhere else in the book.

**Rockafellar's elementary, convexity-free development of §22 is not reproduced.** He offers it as
an alternative to deriving the section from §21; here Theorem 22.1 comes from Farkas' Lemma and
Theorem 22.2 from Theorem 21.2, which is the shorter route given what is already available.

## Design notes

**Theorem 22.1 does not go through Theorem 21.4.** That is Rockafellar's route, and Theorem 21.4 is
not formalised (see `Helly.lean`). Instead Theorem 22.1 is proved from Farkas' Lemma by the usual
homogenisation: the system `⟨aᵢ, x⟩ ≤ αᵢ` is inconsistent exactly when `(0, -1)` lies in the cone of
`F × ℝ` generated by the `(aᵢ, αᵢ)` together with `(0, 1)`, because a point of the polar with a
negative last coordinate rescales to a solution of the system. Farkas' Lemma in turn is
`K°° = K` (Theorem 14.1) for a cone that is closed because it is finitely generated
(Minkowski–Weyl, `Polyhedral/Cone.lean`).

**Farkas' Lemma is stated twice.** `farkas_of_pairing` puts the coefficient vectors in the *first*
space of the pairing, which is the orientation instance search can use at `epiPairing`; `farkas`
is the same statement for `B.flip`, with the solution variable in `E` and the coefficient vectors
in `F`, which is the orientation the rest of §22 reads in.

**Theorem 22.2 is Rockafellar's proof.** Theorem 21.2 with `C = Rⁿ`, the strict constraints as the
convex functions `fᵢ` and the weak ones as the affine constraints, delivers multipliers making the
weighted sum non-negative on all of `E`. That sum is an affine function of the pairing, so its
linear part vanishes — `eq_zero_and_nonpos_of_forall_nonneg` — and that is the multiplier condition.
The step needs the pairing to *separate* `F`, which `IsCompatiblePairing B.flip` supplies through
Hahn–Banach on `F`; `IsCompatiblePairing B` alone would not.

**"One and only one" is recorded as an `Iff` with a negated right-hand side.** `(a) ↔ ¬ (b)` says
exactly what Rockafellar's phrase says, and it keeps the elementary exclusivity half and the
substantial existence half in a single statement. `exists_multipliers_of_infeasible` is the
existence half of Theorem 22.1 on its own, for callers that only need that direction.

## References

* R. T. Rockafellar, *Convex Analysis*, Princeton University Press, 1970, §22 (Theorems 22.1, 22.2,
  22.3, Corollary 22.3.1).
-/
open Set

namespace Tdaf.ConvexAnalysis

/-! ### Conical combinations of a finite family -/

section Hull

variable {F : Type*} [AddCommGroup F] [Module ℝ F] {ι : Type*}

/-- Membership in the pointed-cone hull of a finite family, unfolded to a non-negative
combination. -/
theorem mem_pointedCone_hull_range_iff [Fintype ι] {a : ι → F} {x : F} :
    x ∈ PointedCone.hull ℝ (Set.range a) ↔ ∃ l : ι → ℝ, (∀ i, 0 ≤ l i) ∧ ∑ i, l i • a i = x := by
  rw [PointedCone.hull, Submodule.mem_span_range_iff_exists_fun]
  constructor
  · rintro ⟨c, rfl⟩
    exact ⟨fun i => (c i : ℝ), fun i => (c i).2, rfl⟩
  · rintro ⟨l, hl, rfl⟩
    exact ⟨fun i => ⟨l i, hl i⟩, rfl⟩

/-- The cone generated by a finite family is closed: it is finitely generated, hence polyhedral
(Weyl's half of Minkowski–Weyl), hence an intersection of finitely many closed half-spaces. -/
theorem isClosed_coe_pointedCone_hull_range {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]
    [FiniteDimensional ℝ F] {ι : Type*} [Finite ι] (a : ι → F) :
    IsClosed (PointedCone.hull ℝ (Set.range a) : Set F) := by
  classical
  have hfin : (Set.range a).Finite := Set.finite_range a
  refine FinitelyGeneratedCone.isClosed ⟨hfin.toFinset, ?_⟩
  rw [hfin.coe_toFinset]

end Hull

/-! ### Farkas' Lemma -/

section Farkas

variable {E F : Type*} [AddCommGroup E] [Module ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F] [FiniteDimensional ℝ F] {ι : Type*} [Fintype ι]

/-- **Farkas' Lemma** in the form the pairing calls for: an inequality `⟨a₀, x⟩ ≤ 0` is a
consequence of the homogeneous system `⟨aᵢ, x⟩ ≤ 0` exactly when `a₀` is a non-negative
combination of the `aᵢ`.

This is Rockafellar's remark that Farkas' Lemma *is* `K°° = K` for the cone `K` generated by the
`aᵢ`: `K°` is the solution set of the system, `K°°` is the set of consequences, and `K` is closed
because it is finitely generated (Theorem 19.1).

The pairing is written with the coefficient vectors in the *first* space, so that the theorem can
be applied to `epiPairing`, whose instances instance search only finds in that orientation. -/
theorem farkas_of_pairing (A : F →ₗ[ℝ] E →ₗ[ℝ] ℝ) [IsCompatiblePairing A] (a : ι → F) (a₀ : F) :
    (∀ x : E, (∀ i, A (a i) x ≤ 0) → A a₀ x ≤ 0) ↔
      ∃ l : ι → ℝ, (∀ i, 0 ≤ l i) ∧ ∑ i, l i • a i = a₀ := by
  have hpol := polarCone_setOf_forall_le_zero (B := A) a
  rw [(isClosed_coe_pointedCone_hull_range a).closure_eq] at hpol
  have hmem : a₀ ∈ polarCone A.flip {x : E | ∀ i, A (a i) x ≤ 0} ↔
      a₀ ∈ (PointedCone.hull ℝ (Set.range a) : Set F) := by rw [hpol]
  rw [← mem_pointedCone_hull_range_iff]
  refine Iff.trans ?_ hmem
  simp only [mem_polarCone, Set.mem_ofPred_eq, LinearMap.flip_apply]

end Farkas

/-! ### Theorem 22.1: the alternative for a weak system -/

section Weak

variable {E F : Type*} [AddCommGroup E] [Module ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F] [FiniteDimensional ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} {ι : Type*} [Fintype ι]

/-- **Farkas' Lemma**, Rockafellar's **Corollary 22.3.1**, in the orientation the rest of the
development uses: the solution variable lives in `E` and the coefficient vectors in `F`. -/
theorem farkas [IsCompatiblePairing B.flip] (a : ι → F) (a₀ : F) :
    (∀ x : E, (∀ i, B x (a i) ≤ 0) → B x a₀ ≤ 0) ↔
      ∃ l : ι → ℝ, (∀ i, 0 ≤ l i) ∧ ∑ i, l i • a i = a₀ :=
  farkas_of_pairing B.flip a a₀

/-- The substantial half of **Theorem 22.1**: an inconsistent finite system of weak linear
inequalities carries non-negative multipliers that annihilate the coefficient vectors while making
the right-hand sides negative.

The proof is Farkas' Lemma applied in `F × ℝ` to the vectors `(aᵢ, αᵢ)` together with the extra
generator `(0, 1)`: the point `(0, -1)` lies in the cone they generate exactly when the system is
inconsistent, because a solution of the Farkas condition with a negative last coordinate rescales
to a solution of the system. -/
theorem exists_multipliers_of_infeasible [IsCompatiblePairing B.flip] (a : ι → F) (α : ι → ℝ)
    (hno : ¬ ∃ x : E, ∀ i, B x (a i) ≤ α i) :
    ∃ l : ι → ℝ, (∀ i, 0 ≤ l i) ∧ (∑ i, l i • a i = 0) ∧ ∑ i, l i * α i < 0 := by
  classical
  have hkey : ∀ p : E × ℝ,
      (∀ o : Option ι,
        epiPairing B.flip (o.elim ((0 : F), (1 : ℝ)) fun i => (a i, α i)) p ≤ 0) →
      epiPairing B.flip ((0 : F), (-1 : ℝ)) p ≤ 0 := by
    rintro ⟨x, t⟩ hp
    have ht : t ≤ 0 := by simpa using hp none
    have hi : ∀ i, B x (a i) + α i * t ≤ 0 := by
      intro i
      simpa using hp (some i)
    have ht0 : 0 ≤ t := by
      by_contra hcon
      push Not at hcon
      have hpos : 0 < -t := by linarith
      have htne : t ≠ 0 := ne_of_lt hcon
      refine hno ⟨(-t)⁻¹ • x, fun i => ?_⟩
      have hipos : 0 < (-t)⁻¹ := inv_pos.2 hpos
      have hstep : B x (a i) ≤ α i * (-t) := by linarith [hi i]
      have h2 := mul_le_mul_of_nonneg_left hstep hipos.le
      have h3 : (-t)⁻¹ * (α i * -t) = α i := by field_simp
      rw [map_smul, LinearMap.smul_apply, smul_eq_mul, ← h3]
      exact h2
    have htz : t = 0 := le_antisymm ht ht0
    simp [htz]
  obtain ⟨L, hL0, hLsum⟩ :=
    (farkas_of_pairing (epiPairing B.flip)
      (fun o : Option ι => o.elim ((0 : F), (1 : ℝ)) fun i => (a i, α i))
      ((0 : F), (-1 : ℝ))).1 hkey
  have hfst := congrArg Prod.fst hLsum
  have hsnd := congrArg Prod.snd hLsum
  rw [Prod.fst_sum, Fintype.sum_option] at hfst
  rw [Prod.snd_sum, Fintype.sum_option] at hsnd
  simp only [Option.elim_none, Option.elim_some, Prod.smul_fst, Prod.smul_snd, smul_zero,
    zero_add, smul_eq_mul, mul_one] at hfst hsnd
  refine ⟨fun i => L (some i), fun i => hL0 (some i), hfst, ?_⟩
  have hL0n : 0 ≤ L none := hL0 none
  linarith [hsnd]

/-- **Rockafellar, Theorem 22.1** (Gale's theorem of the alternative). For `a₁, …, a_m` and
`α₁, …, α_m`, one and only one of the following holds: the system `⟨aᵢ, x⟩ ≤ αᵢ` has a solution, or
there are non-negative `λ₁, …, λ_m` with `∑ λᵢaᵢ = 0` and `∑ λᵢαᵢ < 0`.

"One and only one" is recorded as an `Iff` with a negation on the right: the forward direction is
the (elementary) exclusivity and the backward direction is `exists_multipliers_of_infeasible`.

Rockafellar derives this from Theorem 21.4, which is not formalised; the proof here is the
elementary one he offers as an alternative, through Farkas' Lemma. -/
theorem alternative_linear_system [IsCompatiblePairing B.flip] (a : ι → F) (α : ι → ℝ) :
    (∃ x : E, ∀ i, B x (a i) ≤ α i) ↔
      ¬ ∃ l : ι → ℝ, (∀ i, 0 ≤ l i) ∧ (∑ i, l i • a i = 0) ∧ ∑ i, l i * α i < 0 := by
  constructor
  · rintro ⟨x, hx⟩ ⟨l, hl0, hla, hlα⟩
    have h1 : ∑ i, l i * B x (a i) ≤ ∑ i, l i * α i :=
      Finset.sum_le_sum fun i _ => mul_le_mul_of_nonneg_left (hx i) (hl0 i)
    have h2 : ∑ i, l i * B x (a i) = 0 := by
      have h := congrArg (B x) hla
      rw [map_sum, map_zero] at h
      simpa using h
    linarith
  · intro hno
    by_contra hcon
    exact hno (exists_multipliers_of_infeasible a α hcon)

end Weak

/-! ### Theorem 22.2: the alternative for a mixed system -/

section Affine

variable {E F : Type*} [AddCommGroup E] [Module ℝ E] [AddCommGroup F] [Module ℝ F]

/-- The affine function `x ↦ ⟨x, y⟩ - c` of a pairing, bundled as an `AffineMap`. Theorem 21.2
keeps its affine constraints as `E →ᵃ[ℝ] ℝ`, and this is the bundling that presents a linear
inequality to it. `affineFn` is the same function read in `EReal`. -/
def affineMapOfPairing (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (y : F) (c : ℝ) : E →ᵃ[ℝ] ℝ :=
  AffineMap.mk' (fun x => B x y - c) (B.flip y) 0 fun _ => by simp [sub_eq_add_neg]

@[simp] theorem affineMapOfPairing_apply (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (y : F) (c : ℝ) (x : E) :
    affineMapOfPairing B y c x = B x y - c := rfl

variable {ι κ : Type*} [Fintype ι] [Fintype κ]

/-- Pulling a non-negative combination of coefficient vectors through the pairing. -/
theorem pairing_sum_smul (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (l : ι → ℝ) (a : ι → F) (x : E) :
    B x (∑ i, l i • a i) = ∑ i, l i * B x (a i) := by
  rw [map_sum]
  exact Finset.sum_congr rfl fun i _ => by rw [map_smul, smul_eq_mul]

/-- The value of a weighted mixed system at `x`, as one affine function of the pairing: the
coefficient vector is `∑ λᵢaᵢ + ∑ μⱼbⱼ` and the constant is `∑ λᵢαᵢ + ∑ μⱼβⱼ`. -/
theorem combined_value (B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ) (l : ι → ℝ) (a : ι → F) (α : ι → ℝ)
    (μ : κ → ℝ) (b : κ → F) (β : κ → ℝ) (x : E) :
    ((∑ i, l i * (B x (a i) - α i)) + ∑ j, μ j * (B x (b j) - β j))
      = B x (∑ i, l i • a i + ∑ j, μ j • b j) - (∑ i, l i * α i + ∑ j, μ j * β j) := by
  rw [map_add, pairing_sum_smul, pairing_sum_smul]
  simp only [mul_sub, Finset.sum_sub_distrib]
  ring

end Affine

section Separating

variable {E F : Type*} [AddCommGroup E] [Module ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F] {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ}

/-- A pairing whose flip is compatible **separates** its second variable: only `0` pairs to `0`
against every `x`. This is Hahn–Banach on `F` plus the surjectivity that `IsCompatiblePairing`
asserts. -/
theorem eq_zero_of_forall_pairing_eq_zero [IsCompatiblePairing B.flip] {c : F}
    (h : ∀ x : E, B x c = 0) : c = 0 := by
  refine SeparatingDual.eq_zero_of_forall_dual_eq_zero (R := ℝ) fun g => ?_
  obtain ⟨x, hx⟩ := exists_pairing_eq B.flip g
  rw [hx c]
  exact h x

/-- An affine function of the pairing that is non-negative on all of `E` is a non-negative
constant: its linear part vanishes. This is the step by which alternative (b) of Theorem 21.2
becomes the multiplier condition of Theorem 22.2. -/
theorem eq_zero_and_nonpos_of_forall_nonneg [IsCompatiblePairing B.flip] {c : F} {γ : ℝ}
    (h : ∀ x : E, 0 ≤ B x c - γ) : c = 0 ∧ γ ≤ 0 := by
  have hγ : γ ≤ 0 := by simpa using h 0
  refine ⟨eq_zero_of_forall_pairing_eq_zero (B := B) fun x => ?_, hγ⟩
  by_contra hv
  have hs := h (((γ - 1) / B x c) • x)
  rw [map_smul, LinearMap.smul_apply, smul_eq_mul] at hs
  have hcancel : (γ - 1) / B x c * B x c = γ - 1 := div_mul_cancel₀ _ hv
  rw [hcancel] at hs
  linarith

end Separating

section Strict

variable {E F : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F]
  {B : E →ₗ[ℝ] F →ₗ[ℝ] ℝ} {ι κ : Type*} [Fintype ι] [Fintype κ]

/-- **Rockafellar, Theorem 22.2** (Motzkin's transposition theorem). If the weak subsystem
`⟨bⱼ, x⟩ ≤ βⱼ` is consistent, then one and only one of the following holds: the mixed system
`⟨aᵢ, x⟩ < αᵢ`, `⟨bⱼ, x⟩ ≤ βⱼ` has a solution, or there are non-negative multipliers with at least
one of the `λᵢ` non-zero, `∑ λᵢaᵢ + ∑ μⱼbⱼ = 0` and `∑ λᵢαᵢ + ∑ μⱼβⱼ ≤ 0`.

This is Rockafellar's proof: Theorem 21.2 applied with `C = Rⁿ`, the strict constraints as the
convex functions `fᵢ` and the weak ones as the affine constraints. What Theorem 21.2 delivers is
that the weighted sum is non-negative on all of `E`; since that sum is affine, its linear part must
vanish, which is `eq_zero_and_nonpos_of_forall_nonneg`. -/
theorem alternative_linear_system_strict [IsCompatiblePairing B.flip]
    (a : ι → F) (α : ι → ℝ) (b : κ → F) (β : κ → ℝ)
    (hcons : ∃ x : E, ∀ j, B x (b j) ≤ β j) :
    (∃ x : E, (∀ i, B x (a i) < α i) ∧ ∀ j, B x (b j) ≤ β j) ↔
      ¬ ∃ (l : ι → ℝ) (μ : κ → ℝ), (∀ i, 0 ≤ l i) ∧ (∀ j, 0 ≤ μ j) ∧ (∃ i, l i ≠ 0) ∧
        (∑ i, l i • a i + ∑ j, μ j • b j = 0) ∧ ∑ i, l i * α i + ∑ j, μ j * β j ≤ 0 := by
  classical
  constructor
  · rintro ⟨x, hxs, hxw⟩ ⟨l, μ, hl0, hμ0, ⟨i₀, hi₀⟩, hc, hγ⟩
    have hlp : 0 < l i₀ := lt_of_le_of_ne (hl0 i₀) (Ne.symm hi₀)
    have hval := combined_value B l a α μ b β x
    rw [hc, map_zero] at hval
    have h1 : ∑ i, l i * (B x (a i) - α i) < ∑ _i : ι, (0 : ℝ) :=
      Finset.sum_lt_sum (fun i _ => by nlinarith [hl0 i, hxs i])
        ⟨i₀, Finset.mem_univ _, by nlinarith [hxs i₀]⟩
    rw [Finset.sum_const_zero] at h1
    have h2 : ∑ j, μ j * (B x (b j) - β j) ≤ 0 :=
      Finset.sum_nonpos fun j _ => by nlinarith [hμ0 j, hxw j]
    linarith
  · intro hno
    by_contra hcon
    refine hno ?_
    obtain ⟨x0, hx0⟩ := hcons
    have hfeas : ∃ x ∈ ri (Set.univ : Set E), ∀ j, affineMapOfPairing B (b j) (β j) x ≤ 0 := by
      refine ⟨x0, ?_, fun j => ?_⟩
      · rw [intrinsicInterior_univ]; trivial
      · rw [affineMapOfPairing_apply]; linarith [hx0 j]
    rcases alternative_of_convex_system_affine (C := (Set.univ : Set E))
        (f := fun i => affineFn B (a i) (α i))
        (a := fun j => affineMapOfPairing B (b j) (β j))
        convex_univ (fun i => convexFn_affineFn _ _) (fun i => proper_affineFn _ _)
        (fun _ _ _ => mem_dom.2 (lt_top_iff_ne_top.2 (affineFn_ne_top _ _ _)))
        hfeas with hgood | ⟨l, μ, hl0, hμ0, hlne, hineq⟩
    · exfalso
      obtain ⟨x, -, hs, hw⟩ := hgood
      refine hcon ⟨x, fun i => ?_, fun j => ?_⟩
      · have h : affineFn B (a i) (α i) x < 0 := hs i
        rw [affineFn_eq_coe] at h
        have hr : B x (a i) - α i < 0 := by exact_mod_cast h
        linarith
      · have h : B x (b j) - β j ≤ 0 := hw j
        linarith
    · have hineq' : ∀ x : E, (0 : EReal)
          ≤ (∑ i, (l i : EReal) * affineFn B (a i) (α i) x)
            + ((∑ j, μ j * (B x (b j) - β j) : ℝ) : EReal) :=
        fun x => hineq x (Set.mem_univ x)
      have hreal : ∀ x : E, 0 ≤ B x (∑ i, l i • a i + ∑ j, μ j • b j)
          - (∑ i, l i * α i + ∑ j, μ j * β j) := by
        intro x
        have h1 : (∑ i, (l i : EReal) * affineFn B (a i) (α i) x)
            = (((∑ i, l i * (B x (a i) - α i) : ℝ)) : EReal) := by
          rw [Tdaf.EReal.coe_sum]
          exact Finset.sum_congr rfl fun i _ => by
            rw [affineFn_eq_coe, Tdaf.EReal.coe_mul_coe]
        have h := hineq' x
        rw [h1, ← _root_.EReal.coe_add] at h
        have hr : (0 : ℝ) ≤ (∑ i, l i * (B x (a i) - α i))
            + ∑ j, μ j * (B x (b j) - β j) := by exact_mod_cast h
        rwa [combined_value B l a α μ b β x] at hr
      obtain ⟨hc0, hγ0⟩ := eq_zero_and_nonpos_of_forall_nonneg hreal
      obtain ⟨i₀, hi₀⟩ := Function.ne_iff.1 hlne
      exact ⟨l, μ, hl0, hμ0, ⟨i₀, hi₀⟩, hc0, hγ0⟩

/-- **Rockafellar, Theorem 22.3.** For a *consistent* system `⟨aᵢ, x⟩ ≤ αᵢ`, the inequality
`⟨a₀, x⟩ ≤ α₀` is a consequence of the system exactly when `a₀` is a non-negative combination
`∑ λᵢaᵢ` whose right-hand side `∑ λᵢαᵢ` does not exceed `α₀`.

Rockafellar's proof: the inequality fails to be a consequence exactly when the mixed system
`⟨-a₀, x⟩ < -α₀`, `⟨aᵢ, x⟩ ≤ αᵢ` is solvable, and Theorem 22.2 applies to that system because its
weak part is the given consistent one. The multiplier on the strict inequality is non-zero, so it
can be divided out. -/
theorem le_consequence_iff [IsCompatiblePairing B.flip] (a : ι → F) (α : ι → ℝ) (a₀ : F) (α₀ : ℝ)
    (hcons : ∃ x : E, ∀ i, B x (a i) ≤ α i) :
    (∀ x : E, (∀ i, B x (a i) ≤ α i) → B x a₀ ≤ α₀) ↔
      ∃ l : ι → ℝ, (∀ i, 0 ≤ l i) ∧ (∑ i, l i • a i = a₀) ∧ ∑ i, l i * α i ≤ α₀ := by
  classical
  constructor
  · intro hconseq
    have hnot : ¬ ∃ x : E, (∀ _ : Unit, B x (-a₀) < -α₀) ∧ ∀ i, B x (a i) ≤ α i := by
      rintro ⟨x, hs, hw⟩
      have h := hs ()
      rw [map_neg] at h
      exact absurd (hconseq x hw) (by linarith)
    have hb := not_not.1 (fun hcon =>
      hnot ((alternative_linear_system_strict (ι := Unit) (κ := ι)
        (fun _ => -a₀) (fun _ => -α₀) a α hcons).2 hcon))
    obtain ⟨l', μ, hl'0, hμ0, ⟨u, hu⟩, hvec, hsca⟩ := hb
    rw [Finset.univ_unique, Finset.sum_singleton] at hvec hsca
    have hu' : (default : Unit) = u := Subsingleton.elim _ _
    rw [hu'] at hvec hsca
    rw [smul_neg, neg_add_eq_zero] at hvec
    -- `hvec : l' u • a₀ = ∑ i, μ i • a i`,  `hsca : l' u * -α₀ + ∑ i, μ i * α i ≤ 0`
    have hlampos : 0 < l' u := lt_of_le_of_ne (hl'0 u) (Ne.symm hu)
    have hlamne : l' u ≠ 0 := ne_of_gt hlampos
    refine ⟨fun i => μ i / l' u, fun i => div_nonneg (hμ0 i) hlampos.le, ?_, ?_⟩
    · have hsm : ∑ i, (μ i / l' u) • a i = (l' u)⁻¹ • ∑ i, μ i • a i := by
        rw [Finset.smul_sum]
        exact Finset.sum_congr rfl fun i _ => by rw [smul_smul, div_eq_inv_mul]
      rw [hsm, ← hvec, smul_smul, inv_mul_cancel₀ hlamne, one_smul]
    · have hsm : ∑ i, (μ i / l' u) * α i = (l' u)⁻¹ * ∑ i, μ i * α i := by
        rw [Finset.mul_sum]
        exact Finset.sum_congr rfl fun i _ => by ring
      rw [hsm]
      have hle : ∑ i, μ i * α i ≤ l' u * α₀ := by linarith
      have hfin := mul_le_mul_of_nonneg_left hle (inv_nonneg.2 hlampos.le)
      rwa [← mul_assoc, inv_mul_cancel₀ hlamne, one_mul] at hfin
  · rintro ⟨l, hl0, hvec, hsca⟩ x hx
    have h1 : ∑ i, l i * B x (a i) ≤ ∑ i, l i * α i :=
      Finset.sum_le_sum fun i _ => mul_le_mul_of_nonneg_left (hx i) (hl0 i)
    have h2 : B x a₀ = ∑ i, l i * B x (a i) := by rw [← hvec, pairing_sum_smul]
    linarith

end Strict


end Tdaf.ConvexAnalysis
