namespace = 'Tdaf.ConvexAnalysis'

[[node]]
id = 'epsSubgradient'

[[node]]
id = 'iInter_epsSubgradient'

[[node]]
id = 'shiftFn'

[[node]]
id = 'epsSubgradient_eq_setOf_conj_le'

[[node]]
id = 'posHomGen_shiftFn'

[[node]]
id = 'supportFn_epsSubgradient_apply'

[[node]]
id = 'dirDeriv_eq_iInf_supportFn_epsSubgradient'
