namespace = 'Tdaf.ConvexAnalysis'

[[node]]
id = 'closedProperConvexFn_lineRestrict'

[[node]]
id = 'subgradient_eq_empty_iff_tendsto_dirDeriv'

[[node]]
id = 'subgradient_eq_empty_iff_tendsto_norm_fderiv'

[[node]]
id = 'essentiallySmooth_iff_tendsto_dirDeriv'
