namespace = 'Tdaf.ConvexAnalysis'

[[node]]
id = 'EssentiallySmooth'

[[node]]
id = 'domSubgradient_eq_interior_dom_of_essentiallySmooth'

[[node]]
id = 'subsingleton_subgradient_iff_essentiallySmooth'
