namespace = 'Tdaf.ConvexAnalysis'

[[node]]
id = 'rightDeriv'

[[node]]
id = 'leftDeriv'

[[node]]
id = 'mem_subgradient_iff_le_rightDeriv'

[[node]]
id = 'iInf_rightDeriv_Ioi'

[[node]]
id = 'iSup_leftDeriv_Iio'

[[node]]
id = 'iInf_leftDeriv_Ioi'

[[node]]
id = 'iSup_rightDeriv_Iio'

[[node]]
id = 'exists_eq_add_coe_of_le_le'

[[node]]
id = 'cycleVal'

[[node]]
id = 'IsMonotoneRel.isCyclicallyMonotone'

[[node]]
id = 'isMaximalMonotoneRel_iff_exists_closedProperConvexFn'
