namespace = 'Tdaf.ConvexAnalysis'

[[node]]
id = 'gradientLimits'

[[node]]
id = 'containsNoLine_subgradient'

[[node]]
id = 'recessionCone_subgradient_eq_normalCone'

[[node]]
id = 'exists_mem_interior_dom_of_forall_normalCone'

[[node]]
id = 'exposedPoints_subset_gradientLimits'

[[node]]
id = 'subgradient_eq_closure_convexHull_gradientLimits_add_normalCone'
